### ISSUE TITLE
Resample image to new size / spacing

### ISSUE THREAD

**Issue by trypag** [SimpleITK/SimpleITK#1005]
Hello,

I am trying to resample an image to a new size and optionally to a new spacing. So far it's working for an identity resampling but cleary fails when the size is changed (visually impossible). It seems I am wrong in the way I apply the transform and in the centering.
I was not able to find my mistake or understand it. I went through all possible solved issues and tutorials. Using the data augmentation notebook all fails but in different ways ^^

Fixed image infos :
Size: (181, 181, 217)
Spacing: (1.0, 1.0, 1.0)
Origin: (90.0, 125.0, -71.0)
Direction: (-1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 1.0, 0.0)

Resampled fixed image image infos:
Size: (256, 256, 40)
Spacing: (0.7058823529411765, 0.7058823529411765, 5.538461538461538)
Origin: (90.0, 125.0, -71.0)
Direction: (-1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 1.0, 0.0)

Moving image infos :
Size: (512, 512, 40)
Spacing: (0.4882810115814209, 0.4882810115814209, 2.5219993591308594)
Origin: (-125.0, -147.2310028076172, 46.632999420166016)
Direction: (1.0, 0.0, 0.0, 0.0, 0.9914448880836518, 0.13052598937071197, 0.0, -0.1305259893385041, 0.9914448880794114)

Resampled moving image image infos:
Size: (256, 256, 40)
Spacing: (0.9784768506592395, 0.9784768506592395, 2.5219993591308594)
Origin: (-125.0, -147.2310028076172, 46.632999420166016)
Direction: (1.0, 0.0, 0.0, 0.0, 0.9914448880836518, 0.13052598937071197, 0.0, -0.1305259893385041, 0.9914448880794114)

```python
def resize_image(img, img_size, spacing=None):
    dimension = img.GetDimension()

    if isinstance(img_size, int):
        img_size = [img_size]*dimension
    elif isinstance(img_size, list):
        assert(len(img_size) == dimension)

    # Create the reference image with a zero origin, identity direction cosine matrix and dimension     
    reference_image = sitk.Image(img_size, img.GetPixelIDValue())
    reference_image.SetOrigin(img.GetOrigin())
    reference_image.SetDirection(img.GetDirection())

    if spacing is None:
        reference_physical_size = np.zeros(dimension)
        reference_physical_size[:] = [(sz-1)*spc if sz*spc>mx  else mx for sz,spc,mx in zip(img.GetSize(), img.GetSpacing(), reference_physical_size)]
        reference_spacing = [ phys_sz/(sz-1) for sz,phys_sz in zip(img_size, reference_physical_size) ]
        reference_image.SetSpacing(reference_spacing)
    else:
        reference_image.SetSpacing(spacing)

    # Transform which maps from the reference_image to the current img 
    # with the translation mapping the image origins to each other.
    transform = sitk.AffineTransform(dimension)
    transform.SetMatrix(np.identity(dimension).flatten())
    transform.SetTranslation(np.zeros(dimension))
    
    reference_center = np.array(reference_image.TransformContinuousIndexToPhysicalPoint(np.array(reference_image.GetSize())/2.0))

    # Modify the transformation to align the centers of the original and reference image instead of their origins.
    centering_transform = sitk.TranslationTransform(dimension)
    img_center = np.array(img.TransformContinuousIndexToPhysicalPoint(np.array(img.GetSize())/2.0))
    centering_transform.SetOffset(np.array(transform.GetInverse().TransformPoint(img_center) - reference_center))
    centered_transform = sitk.Transform(transform)
    centered_transform.AddTransform(centering_transform)

    return sitk.Resample(img, reference_image, centered_transform, sitk.sitkLinear, 0.0)

moving_resampled = resize_image(moving_image, (256, 256, 40))
sitk.WriteImage(moving_resampled, '/home/pag/Desktop/test_series/moving_spacing.nii')

fixed_resampled = resize_image(fixed_image, (256, 256, 40))
sitk.WriteImage(fixed_resampled, '/home/pag/Desktop/test_series/fixed_spacing.nii')
```

![Screenshot from 2020-03-06 12-47-11](https://user-images.githubusercontent.com/13003839/76081323-239fac00-5fa9-11ea-8abb-e9e2ccee295f.png)
![Screenshot from 2020-03-06 12-44-20](https://user-images.githubusercontent.com/13003839/76081327-24384280-5fa9-11ea-8bca-d5a97e1e3533.png)

Thanks !

**Comment by zivy** [comment]
Hello @trypag,

It is unclear what exactly you want to do. Based on the usage of the fixed_image, moving_image terminology I suspect that you want to resample the moving_image onto the fixed_image location after registration?

If so, did you take a look at [this notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/61_Registration_Introduction_Continued.ipynb), particularly at the `save_transform_and_image` function?

The reason I am not sure about your intent is because you appear to be "resizing" both the moving and fixed images. 

Possibly what you are missing is the philosophy underlying SimpleITK/ITK images - "images are spatial objects". I highly recommend reading the [SimpleITK Fundamental Concepts](https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html) summary. 

If the 'save_transform_and_image` does not resolve your issue, please provide a description of what you want to do so that we can better help you.

**Comment by blowekamp** [comment]
This issue is already being discussed in ITK discourse:
https://discourse.itk.org/t/register-head-ct-to-common-template/2787

I am closing the issue so that the community does not duplicate efforts to address this questions.
