### ISSUE TITLE
Registration doesnt work for 2d brain histology slices 

### ISSUE THREAD

**Issue by anorak94** [SimpleITK/SimpleITK#1009]
I am following the examples in the registration notebooks(60) on github. when i use the example data provided with the notebook everything works fine but when i try to do an alignment on my data which is a 2d dataset of mouse brain sections. the results are not as good infact nothing changes i tried with various rotated angles 15 45 and 90 but the result is the same 

![cor_rot](https://user-images.githubusercontent.com/45297533/76630181-de96ef00-653f-11ea-9f5f-90db99c9e664.png)
![cor](https://user-images.githubusercontent.com/45297533/76630191-e0f94900-653f-11ea-91c4-7544feca24c2.png)

the image on top is the moving image and the image on the bottom is the fixed image 

so my output is the moving image unchanged does this mean that i have to compute masks of the image to do the alignment to make it work better or am i making some other error 

this is the link to the modified notebook

https://github.com/anorak94/example_notebooks/blob/master/60_Registration_Introduction.ipynb

**Comment by zivy** [comment]
Hello @anorak94,

This is very strange. From the notebook, the graph showing the registration metric is showing that there is no convergence.  Also, it is strange that the three registration levels are not in the graph, looks like only one level was run. Not sure what happened there.

When I downloaded the images and ran the notebook it did converge.

The graph looks like this:
![image](https://user-images.githubusercontent.com/338645/76635815-679d2e80-651e-11ea-90e0-e80f63c912f5.png)

And the resampled image looks like this:
![image](https://user-images.githubusercontent.com/338645/76635742-4c322380-651e-11ea-95a5-1f19e10a3460.png)

Please rerun and let us know if the problem persists. If not please close this issue.

**Comment by anorak94** [comment]
Yeah but from the output we can see that the example didnt work because the resampled image doesnt get aligned with the fixed image its still the same as the original moving image so i dont think this issue is resolved

**Comment by zivy** [comment]
Sorry, but you are misinterpreting the output, this is the alpha-blending of the fixed image with the resampled moving image. Notice the region behind the eyes where you can see the blending of the two images showing that they are aligned:
![76635742-4c322380-651e-11ea-95a5-1f19e10a3460](https://user-images.githubusercontent.com/338645/76659275-5834da00-654c-11ea-84d7-196df6f89e7b.png)

**Comment by anorak94** [comment]
But how do i see the new moving image so that its aligned with the fixed image

**Comment by zivy** [comment]
Hello @anorak94,

The transformation obtained from the registration maps point from the fixed image space to the moving image space. When we resample the moving image using this transformation onto the fixed image grid, the resampled moving image is aligned to the fixed. 

As the fixed image (top image in your original post) is the rotated one, the resampled moving image will be a rotated version of the moving image (bottom image in your original post) to match that.

If you want things to go the other way round, just switch the roles of fixed and moving images.
