### ISSUE TITLE
Save the mask as NumPy array to do histogram analysis

### ISSUE THREAD

**Issue by 3omarkamal** [SimpleITK/SimpleITK#1059]
I have 3D medical images (nii series). For each series, I have a hand-drawn ITK mask (3D, irregular masks using ITK snap). Now I am trying to analyze the pixels within each mask. LabelStatisticsImageFilter and LabelIntensityStatisticsImageFilter are good for some calculations but I want to get some percentile measurements of the pixel values for the mask.

I think converting the mask into Numpy array is the way to go but I can't figure a correct way.

Of course GetArrayFromImage works for the main image series but no way to get the mask as a numpy array with the real pixel values from the main image.

I tried LabelStatisticsImageFiler > GetRegion and applied that as a bounds for the numpy array of the main image but it is inaccurate as the bounds are for a uniform shape ( e.g cube) while my mask is very irregular and sometimes is formed of multiple disconnected rounded region of interest.

Any help?

**Comment by richardbeare** [comment]
A simple approach, which doesn't use much SimpleITK apart from the IO, but useful to test your ideas, is to convert both mask and series to numpy and do the extraction there, using numpy.extract or equivalent.

The LabelIntensityStatisticsImageFilter in SimpleITK uses histograms internally, and does export values based on those histograms (like medians), so may do some of what you're after. However I don't believe it exports this histograms.

**Comment by 3omarkamal** [comment]
converting the mask into Numpy array will have the same shape as the main image. I don't know why but the shape of the ITK mask always matches the shape of the original series. I don't really get to understand how sitk stores the masked pixels. 

The LabelIntensityStatisticsImageFilter in SimpleITK allows me to extract some values (Mean, Median) but I am interested in the percentiles.

**Comment by 3omarkamal** [comment]
Sorry on the previous post and thanks alot. Your approach works like magic!!
