### ISSUE TITLE
ResampleImageFilter.SetSize() does not accept numpy arrays in Python 3

### ISSUE THREAD

**Issue by haarburger** [SimpleITK/SimpleITK#106]
As reported [here](https://github.com/Radiomics/pyradiomics/issues/204), the following code works with Python 2 but not Python 3:

```python
rif = sitk.ResampleImageFilter()
rif.SetSize(np.array([1, 2, 3], dtype='int'))
```
In Python 3, SimpleITK throws
```
TypeError: in method 'ResampleImageFilter_SetSize', argument 2 of type 'std::vector< uint32_t,std::allocator< uint32_t > > const &'
```

Passing `dtype='uint32'` doesn't help. My temporary workaround is
```python
rif.SetSize(np.array([1, 2, 3], dtype='int').tolist())
```
I tested with both SimpleITK 0.10.0 and 1.0.0rc1+g57b8f

System:
* ubuntu 16.04 amd64
* python 3.5.2 (anaconda)
* numpy 1.12.0
* SimpleITK 0.10.0 and 1.0.0rc1+g57b8f

**Comment by blowekamp** [comment]
Thank you for reporting the issue.

@zivy Have you encountered this issue?

**Comment by zivy** [comment]
Confirmed the issue. I have never tried it with numpy arrays, as I either use tuple or list notation for these operations (these work in Python3).

@haarburger just out of curiosity, what was the motivation for using a numpy array for specifying size vs. the more concise list or tuple notation?

**Comment by haarburger** [comment]
@zivy Using numpy array was not my decision. It was [implemented](https://github.com/Radiomics/pyradiomics/blob/cc788414606f23b1bbd5c6327035ffb9c7bcadc3/radiomics/imageoperations.py#L187) like that in pyradiomics and as a pyradiomics user I stumbled upon this.

**Comment by blowekamp** [comment]
There looks like there is a related SWIG issue open: swig/swig#888
We will also look into finding a work around in SimpleITK too.

**Comment by Ivanka07** [comment]
@Grieverheart have you found a solution/workarround for this issue? I am using Python3.8 and SimpleITK 2.1.0 and above proposed solutions don't work for me...

**Comment by zivy** [comment]
Hello @Ivanka07,

That is strange. The conversion to list should work with the versions you are using. On OSX, Python 3.8.5, SimpleITK 2.1.0 the following works, please try:
```
import SimpleITK as sitk
import numpy as np

rif = sitk.ResampleImageFilter()
rif.SetSize(np.array([1, 2, 3], dtype='int').tolist())
```

**Comment by zhilothebest** [comment]
using tolist() does not work for me in my case.

**Comment by zivy** [comment]
Hello @zhilothebest,

Please provide a minimal working example showing that the usage of `tolist()` does not work. I tried resampling with a numpy array converted via the `tolist` function and it does work for me.

Possibly specify the Python version and OS you are using.
