### ISSUE TITLE
SetDirection() function unable to slice a angled axis

### ISSUE THREAD

**Issue by helwilliams** [SimpleITK/SimpleITK#1082]
Hello.

 Thanks for a great tool, I am just struggling to extract a 2D oblique plane. 

I have used SetDirection to create an angled coordinate system corresponding to a particular plane at a mid point position. However, when the go to slice the volume.SetDirection(newcoordinatesystem) it using python numpy slicing [:,:,i:i+1], it only does so in the original orthogonal coordinate system [1,0,0,0,1,0,0,0,1]. I have been told SimpleITK can resample the oblique plane simply by the method I used but it doesn't seem to be working.  Really struggling to see what tools are available to do this on SITK.  Thank you

**Comment by zivy** [comment]
Hello @helwilliams,

You're welcome.

Unfortunately, that is incorrect. When you set the direction cosine matrix it simply positions the image differently in 3D, the voxels are not resampled, so when you access them via the image slicing you won't see a difference. If you save that image and then load it into Slicer it will display it by doing the resampling for you. See example code below (image is available from [here](https://data.kitware.com/#item/57b5ddab8d777f10f2695f95)):

```
import SimpleITK as sitk
img = sitk.ReadImage('training_001_ct.mha')
print(img.GetDirection())
#"rotate" the image by 45 degrees around Y axis
img.SetDirection([0.7071,0,0.7071, 0, 1, 0, -0.7071, 0, 0.7071])
print(img.GetDirection())
sitk.WriteImage(img, 'training_001_ct_rotated.mha')
```

**Comment by helwilliams** [comment]
Great thank you for clearing this up , to do the resampling is that possible with SITK?

**Comment by zivy** [comment]
Yes, you can resample with SimpleITK. It is not trivial in the sense that you need to set everything up (understand how the pixels are mapped from the slicing image to the resampled image and the need to treat the slicing image as a 3D image even though it is 2D). 

Below is an example:
```
import SimpleITK as sitk

img = sitk.ReadImage('training_001_ct.mha')
img_center = img.TransformContinuousIndexToPhysicalPoint([(sz-1)/2.0 for sz in img.GetSize()])

#define a 2D image as a 3D image with z equal to one.
new_image_size = [1024,1024,1]
new_image_spacing = [0.5,0.5,1]
new_image_origin = [0,0,0]
new_image_direction = [1, 0, 0, 0, 1, 0, 0, 0, 1]

new_image_center = [(sz-1)*spc/2.0 for sz,spc in zip(new_image_size, new_image_spacing)]

#transform that positions our resampling grid in 3D space
transform = sitk.Euler3DTransform()
#rotate around the center of the image
transform.SetCenter(new_image_center)
#rotation of 45 degrees around z axis because it is easiest to visually confirm that we get what we want
transform.SetRotation(angleX=0.0, angleY=0.0, angleZ= 0.785398)
#translate to center of volume
transform.SetTranslation([ic-nic for ic,nic in zip(img_center,new_image_center)])

new_image = sitk.Resample(img, new_image_size, transform, sitk.sitkLinear, new_image_origin, new_image_spacing, new_image_direction, 0, img.GetPixelID())

sitk.Show(new_image)
```

**Comment by helwilliams** [comment]
Amazing thank you so much for the support, it makes a lot more sense now- I struggled to find an example so easy to follow online.
I just have one small final question: so for my particular problem I have a  rotated 2d frame that is usually in coronal view.
I have comprised a direction matrix that swaps the coronal to axial view and rotates the volume to show a specific oblique plane at a given origin. 
Direction matrix = [0, 0, -1, -0.973, 0.2307, 0, -0.2307, -0.9730, 0] 
Can I purely insert the direction matrix as the new direction of image or should I compute the angular rotation of this direction matrix and use the Euler transform?

Thanks again, Helena

**Comment by zivy** [comment]
@helwilliams, you're welcome. 

Again, setting the image's direction cosine matrix will do nothing to the pixel array content, it is just moving that array in physical space. You will need to use the appropriate Euler transform to position your slicing plane in the relevant pose in physical space to obtain the desired pixel values as a 2D image. I highly recommend reading the [fundamental concepts](https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html#images) description of how we think of images in SimpleITK (not arrays of pixels).

On the off chance I misunderstood your question, you don't need to specify angles for the Euler transform, just use the [SetMatrix](https://simpleitk.org//doxygen/v1_2/html/classitk_1_1simple_1_1Euler3DTransform.html#adae73d5f83d3c127173b0505c32b77b6) method.

**Comment by helwilliams** [comment]
Great thank you I have it working now and understand it a lot more, thanks for the support! :)
