### ISSUE TITLE
rgbcolormap with segmentation overlay 

### ISSUE THREAD

**Issue by manuel-lincbiotech** [SimpleITK/SimpleITK#1085]
Hello,
I´m trying to write some .png files from the slices of some medical images. So far everything worked fine. The problem comes when I try to do this with a segmentation overlay. The code where it fails:
```
    image = sitk.GetImageFromArray(image)
    maxi = sitk.MinimumMaximumImageFilter()
    maxi.Execute(image)
    rang = maxi.GetMaximum() - maxi.GetMinimum()
    img = image + np.abs(maxi.GetMinimum())
    img = 65535 * (img / rang)
    img = sitk.Cast(img, sitk.sitkUInt16)
    colormap = 'jet'
    if color=='grey':
        pass
    elif color=='jet':
        img = sitk.ScalarToRGBColormap(img, sitk.ScalarToRGBColormapImageFilter.Jet)
    elif color=='hot':
        img = sitk.ScalarToRGBColormap(img, sitk.ScalarToRGBColormapImageFilter.Hot)

    final_mask = sitk.GetImageFromArray(final_mask)

    green = [0, 255, 0]
    combined = sitk.LabelOverlay(image=sitk.Cast(img,sitk.sitkUInt16),
                                 labelImage=sitk.Cast(final_mask, sitk.sitkUInt8),
                                 opacity=0.8,colormap=green)
```

You can assume that image and final_mask come from numpy arrays. The problems seems that the labelOverlay does not work when I previously apply the jet colormap to the image. If I don´t apply the  sitk.ScalarToRGBColormapImageFilter.Jet everything works fine, but the final image is in grayscale, I would like to get the same result that appears in the attached file, but instead of greyscale I want to be able to specify any colormap (jet in this case, but it can vary). The segmentation overlay should be as in the attached file as well. The error I get:

> RuntimeError: Exception thrown in SimpleITK LabelOverlay: d:\a\1\sitk\code\common\include\sitkDualMemberFunctionFactory.hxx:201:
> sitk::ERROR: Pixel type: vector of 8-bit unsigned integer is not supported in 3D byclass itk::simple::LabelOverlayImageFilter
> 

Assuming the combined variable is created without errors I can then write the slices of that image.
I understand that basically it can´t be done the way I tried. But I couldn´t find any workaround this.
![1](https://user-images.githubusercontent.com/50863677/80608359-f1557c80-8a36-11ea-93ab-65b04c84547c.png)

PD: I know this can be somehow solved using matplotlib, but simpleitk is way faster at writing multiple slices, so I would prefer to stick to it if possible

Thanks in advance

**Comment by zivy** [comment]
Hello @manuel-lincbiotech,

Please take a look at the [results visualization notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/05_Results_Visualization.ipynb) for a guide on how to visualize results using SimpleITK, it describes how to do the label overlay on high dynamic range images and a variety of other ways to visualize results.

**Comment by manuel-lincbiotech** [comment]
Thanks @zivy 
The code I provided is already based on what I saw in the segmentation overlay section. Maybe is there another way of doing it like the alpha blending method? the segmentation overlay method seemed easier though.

**Comment by zivy** [comment]
Hello @manuel-lincbiotech,

Took a second look at your code and it looks a bit strange. The first section, ending before `final_mask =...`, creates a single channel image `img` which is then either left alone, `color=='grey'`, or converted to a three channel color image using one of two colormaps. Is the original, `image`, supposed to be the segmentation/labelmap/overlay or is this your anatomical image? Based on the call to `sitk.LabelOverlay` it appears that this should be the anatomical image. The conversions to three channel color images is strange, and won't work with the `LabelOverlay`.

To use the `LabelOverlay` you supply it with a single channel (anatomical image), a segmentation image (`sitk.sitkUInt8, sitk.sitkUInt16...) and the colormap.

If you can share the anatomical image and segmentation we can probably resolve this quickly.

**Comment by manuel-lincbiotech** [comment]
Yes, I attach a file with both the image and the segmentation. The thing is that I want sometimes the final .png to have the anatomical image in greyscale (like in the previous image) and sometimes I want it in a specific colormap (like hot or jet). Then I want to overlay a segmentation with a specific color (which I specified in the green variable, as in this case I wanted it green, other times I might want it red). I also attach an example of how I would like the final png to appear (obtained with itk-snap), the only difference is that I would like the segmentation to appear green intead of red. 

*For the attached image and segmentation it might be flipped (not important, but to get the exact same image orientation you would need to apply img = img[:,::-1,:]).
[example.zip](https://github.com/SimpleITK/SimpleITK/files/4558690/example.zip)
![overlay](https://user-images.githubusercontent.com/50863677/80718248-2f67a480-8afa-11ea-83b0-ab5d7c67231a.PNG)

**Comment by zivy** [comment]
Hello @manuel-lincbiotech,

Now I have a better understanding of what you want, solution below. 

Some things to note, you were manually rescaling the intensities to [0, 65535] using multiple operations this can be done in one line: ` img = sitk.Cast(sitk.RescaleIntensity(image, 0, 65535.0), sitk.sitkUInt16)`.

The code below uses the `alpha_blend` and `make_isotropic` functions found in the [notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/05_Results_Visualization.ipynb):

```
#Dictionary with functions mapping a scalar image to a three component vector image
image_mappings = {'grey': lambda x: sitk.Compose([x]*3),
                  'jet' : lambda x: sitk.ScalarToRGBColormap(x, sitk.ScalarToRGBColormapImageFilter.Jet),
                  'hot' : lambda x: sitk.ScalarToRGBColormap(x, sitk.ScalarToRGBColormapImageFilter.Hot)}

image = sitk.ReadImage('example/image.nii')
segmentation = sitk.ReadImage('example/seg.nii')

#Make the images isotropic so that when we save a slice along any axis 
#it will be fine (most image formats assume isotropic pixel sizes).
#Segmentation is interpolated with nearest neighbor so we don't introduce new
#labels.
image = make_isotropic(image, interpolator = sitk.sitkLinear)
segmentation = make_isotropic(segmentation, interpolator = sitk.sitkNearestNeighbor)

#Convert image to sitkUInt8 after rescaling, color image formats only work for [0,255]
image_255 = sitk.Cast(sitk.RescaleIntensity(image, 0, 255), sitk.sitkUInt8)

colormap = 'jet'
vec_image = image_mappings[colormap](image_255)
vec_segmentation = sitk.ScalarToRGBColormap(segmentation, sitk.ScalarToRGBColormapImageFilter.Green)
vec_combined = sitk.Cast(alpha_blend(image1=vec_image, image2=vec_segmentation,alpha=0.0, mask2=segmentation==1), sitk.sitkVectorUInt8)

sitk.Show(vec_image, 'image')
sitk.Show(vec_segmentation, 'segmentation')
sitk.Show(vec_combined, 'blended')
```

**Comment by manuel-lincbiotech** [comment]
Thanks @zivy  that did work,
I think I understand a bit better how to do it, I had some fundamental issues I didn´t understand. But that worked just fine.
