### ISSUE TITLE
Order of images returned by GetArrayFromImage - where is this this documented?

### ISSUE THREAD

**Issue by seandoyle** [SimpleITK/SimpleITK#1088]
I believe that I'm getting the images sorted in opposite directions (using the DICOM ImagePatientPosition's z-order) in Siemens and GE images. 

```
reader = sitk.ImageSeriesReader()
filenames = reader.GetGDCMSeriesFileNames(series_folder)
reader.SetFileNames(filenames)
sitk.GetArrayFromImage(reader.Execute())
```
Could someone point me at the documentation or source for this? I need to map the slices back into DICOM space and need to keep an association with the original SOPInstanceUIDs. Thanks.

**Comment by zivy** [comment]
Hello @seandoyle,

The order of the axes in SimpleITK is x,y,z and in numpy it is z,y,x. Please see [this notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/03_Image_Details.ipynb) the section titled "Conversion between numpy and SimpleITK".

**Comment by seandoyle** [comment]
I'm sorry - I wasn't clear. I've seen that document & it's excellent.

Here's what I see and I'm confused:

- I can read a directory of DICOM files in and view them just fine in numpy & matplot lib.
- I read the directory a second time with pydicom and sort the files by `ds.ImagePositionPatient[2]` (the z-order). All studies have the patient position FFS.
- It appears that the sorting by z-order is opposite in GE and Siemens  CT studies. So - the imported volumes are all good & reasonable - but I don't know which DICOM SOPInstanceUID is associated with each slice of the numpy array.

I'm working with someone else's code and I need to associate the slice data with the original DICOM source files so that I can generate GSPS annotations on top of the images. It would be easier just to read the files in directly but I don't want to modify their code.

A few years ago I looked at the source for dcm2niix and there were many vendor specific rules for how a series was classified as a series (MR studies were complicated and there is a lot of vendor-specific differences). So - I want to see the source for where the ordering is determined here. I did a quick grep through the SimpleITK source and it wasn't obvious to me but I'm probably grepping for the wrong thing.

**Comment by seandoyle** [comment]
Oops. I stopped reading the document when it was discussing the numpy/itk order. But the answer is in that document since you can get this information from the metadata fields:
```
reader = sitk.ImageSeriesReader()
filenames = reader.GetGDCMSeriesFileNames(series_folder)
reader.SetFileNames(filenames)
reader.MetaDataDictionaryArrayUpdateOn()
sitk.GetArrayFromImage(reader.Execute())
```

Once the `MetaDataDictionaryArrayUpdateOn()` is set - then I can get the values I need. For example -instance number for slice 0:
```
 reader.GetMetaData(0, '0020|0013')
```

Sorry for the bother! Closing this issue.

**Comment by zivy** [comment]
Hello @seandoyle,
No worries. One additional detail, if you need to access private tags you will also have to call `reader.LoadPrivateTagsOn()`.
