### ISSUE TITLE
the problem occurred when i use storescu to post the dcm on my dcm4chee server

### ISSUE THREAD

**Issue by dejavunHui** [SimpleITK/SimpleITK#1089]
it was return  an error likes E"ERROR: Received C-STORE-RSP with Status A900H for 0.dcm", but when i used the dcm file of website everthing is ok! please help me!!!

**Comment by zivy** [comment]
Hello @dejavunHui,

Your question is with respect to an error generated by dcm4chee. Please ask on their [google group](https://groups.google.com/forum/#!forum/dcm4che). If you have a SimpleITK specific question please ask on [ITK discourse](https://discourse.itk.org/).
