### ISSUE TITLE
I want to write a three-channels(RGB) to a new dcm file

### ISSUE THREAD

**Issue by dejavunHui** [SimpleITK/SimpleITK#1091]
I want to find a solution about how to create a dcm with rgb picture.I had  a wrong way about follows.
`def writeSlices(series_tag_values, new_img, out_dir, nd, i):
    image_slice = new_img[:,:,:]

    # Tags shared by the series.
    list(map(lambda tag_value: image_slice.SetMetaData(tag_value[0], tag_value[1]), series_tag_values))

    # Slice specific tags.
    image_slice.SetMetaData("0008|0012", time.strftime("%Y%m%d")) # Instance Creation Date
    image_slice.SetMetaData("0008|0013", time.strftime("%H%M%S")) # Instance Creation Time
    image_slice.SetMetaData("0010|0020", '1'+str(i)) # patient id
    image_slice.SetMetaData("0010|0010", 'name'+str(i)) # patient name
    image_slice.SetMetaData('0028|0008', '{}'.format(len(image_slice)))
    image_slice.SetMetaData('0028|0002', '{}'.format(nd))`
`writeSlices(series_tag_values, new_img, './project/python/unet/data/dcm/', 3, 0)`
but I got an error:
`RuntimeError: Exception thrown in SimpleITK ImageFileWriter_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/GDCM/src/itkGDCMImageIO.cxx:1051:
itk::ERROR: GDCMImageIO(0x717f6e70): Sorry Dave I can't do that`

**Comment by zivy** [comment]
Hello @dejavunHui,

Writing a color image to DICOM does work, but there is a caveat. ITK and SimpleITK assume your three channel image is in the RGB color space. DICOM supports multiple color spaces (Photometric Interpretation tag, 0028,0004). Also, please use the latest SimpleITK pre-release version: 
```pip install --upgrade --pre SimpleITK --find-links https://github.com/SimpleITK/SimpleITK/releases/tag/latest```

To try the basic saving to DICOM, you can read a color image (jpg) and save it to DICOM:
```
import SimpleITK as sitk
file_name = 'SimpleITK.jpg' 
sitk.WriteImage(sitk.ReadImage(file_name), 'result.dcm')
```

**Comment by dejavunHui** [comment]
cool!!Now i got it,but a new question that i dont know how to create that dcm if&nbsp; i want to use&nbsp; ndarrays.



---Original---

**Comment by zivy** [comment]
Hello @dejavunHui,

What do you mean by ndarrays? If you have a 3D numpy array you can slice it to get the relevant 2D image and then save that (after you convert it to a SimpleITK image `GetImageFromArray`). If you have a 3D SimpleITK image, just get the slice and save that.

Please take a look at [this jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/03_Image_Details.ipynb) for an introduction to working with SimpleITK images (moving back and forth from numpy, image IO etc.)

**Comment by dejavunHui** [comment]
OH! I am sorry,maybe i dont make it clear. what i want to say is how to write an array likes [samples, width,height, channels] (as far as i am concerned, channels are 3) to a dcm.At least, i am sorry to trouble  you again.

**Comment by zivy** [comment]
Hello @dejavunHui,
Still not clear, not sure what you mean by "samples" in your array description. 

In the same way we create an array in [the example](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesFromArray_docs.html), you can create an array (z,y,x,3) which when written to DICOM will be treated as an RGB image.
```
new_arr = np.random.uniform(-10, 10, size = (3,4,5,3)).astype(np.uint8)
```
