### ISSUE TITLE
SimpleITK cannot read VTK polydata?

### ISSUE THREAD

**Issue by wangyibin0011** [SimpleITK/SimpleITK#1095]
Hello, I want to use simpleITK to read the VTK file,My VTK was generated by TRK using dipy,as follows:

import vtk
from dipy.tracking.streamline import Streamlines
from dipy.io.streamline import load_trk, load_tractogram
from dipy.io.streamline import save_vtk

def saveStreamlinesVTK(streamlines, pStreamlines):
    polydata = vtk.vtkPolyData()
    lines = vtk.vtkCellArray()
    points = vtk.vtkPoints()
    ptCtr = 0
    for i in range(0, len(streamlines)):
        if ((i % 10000) == 0):
            print(str(i) + "/" + str(len(streamlines)))
        line = vtk.vtkLine()
        line.GetPointIds().SetNumberOfIds(len(streamlines[i]))
        for j in range(0, len(streamlines[i])):
            points.InsertNextPoint(streamlines[i][j])
            linePts = line.GetPointIds()
            linePts.SetId(j, ptCtr)
            ptCtr += 1
        lines.InsertNextCell(line)
    polydata.SetLines(lines)
    polydata.SetPoints(points)
    writer = vtk.vtkPolyDataWriter()
    writer.SetFileName(pStreamlines)
    writer.SetInputData(polydata)
    writer.Write()
    print("Wrote streamlines to " + writer.GetFileName())

if __name__ == '__main__':
    streams = load_tractogram("TOM_trackings/AF_left.trk", 'same', bbox_valid_check=False)
    streamlines = Streamlines(streams.streamlines)
    saveStreamlinesVTK(streamlines, 'AF_left.vtk')
This VTK file can be displayed in the VTK library：

![1](https://user-images.githubusercontent.com/53501301/81163501-76a1d980-8fc1-11ea-8495-f7ac4e4a0e14.png)

Then,I tried this：
import SimpleITK as sitk
reader = sitk.ImageFileReader()
reader.SetImageIO("VTKImageIO")
reader.SetFileName('C:/Users/wyb/Desktop/trk_test/AF_left.vtk')
image = reader.Execute()

An error is as follows：
itk::ERROR: VTKImageIO(000002097291C900): Not structured points, can't read

then,I tried this:
image = sitk.ReadImage('C:/Users/wyb/Desktop/trk_test/AF_left.vtk')
print(image)

An error is as follows：
sitk::ERROR: Unable to determine ImageIO reader for "C:/Users/wyb/Desktop/trk_test/AF_left.vtk"

What is the correct way to read, thank you.My simpleITK==1.2.4,

**Comment by zivy** [comment]
Hello @wangyibin0011,

Unfortunately, SimpleITK only deals with images and does not support this type of VTK data.

**Comment by blowekamp** [comment]
For clarity SimpleITK can read VTK Image Data but not the others such as unstructured grid or polydata etc.
