### ISSUE TITLE
incompatibility between python2 and python3

### ISSUE THREAD

**Issue by mlentwicklung** [SimpleITK/SimpleITK#1098]
I can call the `resampler.SetSize` function in python2 but I get the following error while calling the same function in python3.

`resampler.SetSize(list(new_size.astype(int)))`
 error:

```
  File "/home/amir/.local/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 58667, in SetSize
    return _SimpleITK.ResampleImageFilter_SetSize(self, Size)
TypeError: in method 'ResampleImageFilter_SetSize', argument 2 of type 'std::vector< uint32_t,std::allocator< uint32_t > > const &' 
```

**Comment by zivy** [comment]
Hello @mlentwicklung,

This is an interesting situation where the `astype` is not doing what you expected it, the data type for the list entries is not `int`, it is `numpy.int64`. The conversion of numpy array to list which works is also shown.
```
import SimpleITK as sitk
import numpy as np

new_size = np.array([512,1024])

lst1 = list(new_size.astype(int))
print(type(lst1[0]))

resampler = sitk.ResampleImageFilter()
resampler.SetSize([int(v) for v in new_size])

```

**Comment by blowekamp** [comment]
This issue was also raised here: #106

**Comment by mlentwicklung** [comment]
Thanks @zivy it works.
