### ISSUE TITLE
read dicom overlay

### ISSUE THREAD

**Issue by Mathematinho** [SimpleITK/SimpleITK#1101]
I have DICOM files (classic DICOM files with separate files for each slice) that have ROIs stored in the meta data as overlays (tag '60xx|3000'). each slice/file has its own overlays.

i know i can use sitk.ImageSeriesReader() to read the entire series as a whole and my understanding is i have to go to each slice to get the overlays. for example, myseries.GetMetaData(slice=20,key='6000|3000') should give the first overlay for slice 20.

but, myseries.GetMetaData(slice=20,key='6000|3000') returns a string. all non-string meta data entries are "printed to string before returning" per manual. is there a way to return as their native types (bits). if not, is there a way to convert them back to bits?

i used the 'tobits' function from here 

https://stackoverflow.com/questions/10237926/convert-string-to-list-of-bits-and-viceversa

and "unpack_bits" from pydicom

https://github.com/pydicom/pydicom/blob/8f6ad14d/pydicom/dataset.py#L1510

but not getting the correct conversions. hope someone can point me to the right direction.

attaching my code

ROI_row = int(myseries.GetMetaData(slice=slice_id,key='6000|0010'))
ROI_col = int(myseries.GetMetaData(slice=slice_id,key='6000|0011'))
print(ROI_row,ROI_col,ROI_row*ROI_col)
temp = unpack_bits(np.array(tobits(myseries.GetMetaData(slice=slice_id,key='6000|3000'))))[:(ROI_row*ROI_col)]
temp1 = temp.reshape(ROI_row,ROI_col)
plt.imshow(temp1)

thanks.

yin

**Comment by zivy** [comment]
Hello @Mathematinho,
Never had to do this and I don't have relevant data so I'll make some educated guesses with respect to potentially relevant methods.
1. string's `encode` method: `myseries.GetMetaData(slice=slice_id,key='6000|3000').encode('utf-8')`
2.numpy array `fromstring`: `np.fromstring(myseries.GetMetaData(slice=slice_id,key='6000|3000'), dtype=int)`

Can you share a slice?

**Comment by Mathematinho** [comment]
thanks for the reply @zivy. 

so what would be the right way of reading the overlay data into a mask using simpleitk? maybe i am doing this all wrong.

sorry, i am afraid i can't share any of the data due to confidential and security. 

i have tried both suggestions, the first one returns 

b'AAAAAA (a bunch of A, i assume these are the empty part of the mask. and then it had) AAIADAAAA (and after some more A's) A4P///z8AAAAAA 

it doesn't look like any type data i've seen.

the second one returns an error

ValueError: string size must be a multiple of element size


alternatively, from pydicom, i can get the values of the overlay as

b'\x00\x00\x00\x00\x00\

which is correct. 

so how would i get b'\x00\x00\x00\x00\x00\ from b'AAAAAAAA

**Comment by zivy** [comment]
Hello @Mathematinho,
Really not sure here. Possibly try the functions found in the [binascii](https://docs.python.org/3/library/binascii.html) module with the original string returned from the dictionary as input.
