### ISSUE TITLE
MattesMutualInformationImageToImageMetricv4: Joint PDF summed to zero

### ISSUE THREAD

**Issue by SylwekFr** [SimpleITK/SimpleITK#1106]
Hello,
I am using SimpleITK (Python V3.7) to affine registration on 2 CT-scan serie and I get the error :

> RuntimeError: Exception thrown in SimpleITK ImageRegistrationMethod_Execute: d:\a\1\sitk-build\itk-prefix\include\itk-4.13\itkMattesMutualInformationImageToImageMetricv4.hxx:205:
> itk::ERROR: MattesMutualInformationImageToImageMetricv4(01489590): Joint PDF summed to zero

An important point is that I don't always get this error, sometime it works fine I don't know why 
The code I use is :
```python
registration_method = sitk.ImageRegistrationMethod()
registration_method.SetMetricAsMattesMutualInformation(numberOfHistogramBins=50)
registration_method.SetMetricSamplingStrategy(registration_method.REGULAR)
registration_method.SetMetricSamplingPercentage(1)
registration_method.SetInterpolator(sitk.sitkLinear)
registration_method.SetOptimizerAsGradientDescent(learningRate=1, numberOfIterations=255)
registration_method.SetOptimizerScalesFromPhysicalShift()
registration_method.SetShrinkFactorsPerLevel(shrinkFactors = [6,4,2,1])
registration_method.SetSmoothingSigmasPerLevel(smoothingSigmas=[3,2,1,0])
registration_method.SmoothingSigmasAreSpecifiedInPhysicalUnitsOn()
registration_method.SetInitialTransform(initial_transform)
before_slice_cast = sitk.Cast(before_slice_image, sitk.sitkFloat32)
after_slice_cast = sitk.Cast(after_slice_image, sitk.sitkFloat32) 
final_transform = registration_method.Execute(before_slice_cast, after_slice_cast) #here i get the error
```
I attach an example of data of 2 slice where  before_slice_image si CT.... and after_slice_image is IMG....

[example.zip](https://github.com/SimpleITK/SimpleITK/files/4620608/example.zip)

**Comment by zivy** [comment]
Hello @SylwekFr,

That error usually means that the images are no longer overlapping, the optimizer took a large step in parameter space and the transform mapping points from the fixed image to the moving image is mapping all points outside the moving image.

Your configuration of the registration is a bit strange:
```
registration_method.SetMetricSamplingStrategy(registration_method.REGULAR)
registration_method.SetMetricSamplingPercentage(1)
```
Please try

```
registration_method.SetMetricSamplingStrategy(registration_method.NONE)
```
and no need to set the sampling percentage.

**Comment by blowekamp** [comment]
Are you using a transform initializer?

If you haven't already please read through the [Registration Overview](https://simpleitk.readthedocs.io/en/master/registrationOverview.html) and the linked Jupyter Notebook examples.

**Comment by SylwekFr** [comment]
@zivy thank you for your reply, i tried now an i get a diffrent error : 

> RuntimeError: Exception thrown in SimpleITK ImageRegistrationMethod_Execute: d:\a\1\sitk-build\itk-prefix\include\itk-4.13\itkMattesMutualInformationImageToImageMetricv4.hxx:238:
> itk::ERROR: MattesMutualInformationImageToImageMetricv4(0BE3BB68): Too many samples map outside moving image buffer. There are only 282 valid points out of 7225 total points. The images do not sufficiently overlap. They need to be initialized to have more overlap before this metric will work. For instance, you can align the image centers by translation.

@blowekamp thank you too for your reply, yes there is a transform initializer :
```
before_slice_image = sitk.Cast(before_image, sitk.sitkFloat32)
after_slice_image = sitk.Cast(after_image, sitk.sitkFloat32) 
initial_transform = sitk.CenteredTransformInitializer(before_slice_image,
                                                                  after_slice_image,
                                                                  sitk.AffineTransform(before_slice_image.GetDimension()),
                                                                  sitk.CenteredTransformInitializerFilter.GEOMETRY)
```
In case I am missing some part of code which may help in the problem I can add here or the "full code" is avaliable here : https://github.com/SylwekFr/lung_analysis/blob/master/patientAffineRegistration.py

**Comment by zivy** [comment]
Hello @SylwekFr ,

Thanks for sharing your code, makes it much easier to help.

So, after looking at your code I am a bit puzzled. Based on your naming conventions in the code "before_slice_image", "after_slice_image" and the data in the zip file, two CT slices:

You appear to be registering two volumes, but iterating over slices and only aligning these in 2D. So instead of a single 3D transform you have multiple 2D transformations. This requires that the two volumes have the same number of slices and that the anatomy of interest is pretty much in the same 3D location along the z-axis (cranial-caudal direction). These requirements will never be satisfied.  

You should align the volumes directly in 3D.

Also, it looks like in your code the images used for registration are [obtained from numpy arrays](https://github.com/SylwekFr/lung_analysis/blob/2e2acc16487c91f4cb9971aabea17babeb3d8d93/patientAffineRegistration.py#L85-L86). This means we are missing the physical sizes of the pixels (they are assumed to be 1x1mm). This is not happening in your case. The sample data you gave has a spacing of 0.98x0.98mm for one image and 0.59x0.59mm for the other. By ignoring this information any registration results you obtain will be problematic as registration is done in physical space.

If you can clarify your goal (input-output) we can better help you. Possibly explain the strategy you are using, I know you have a reason for the 2D approach, what is it?

**Comment by SylwekFr** [comment]
Hello @zivy ,

Actually the registration is the 3rd step of the full application ([lung_analysis](https://github.com/SylwekFr/lung_analysis)), the [ first step](https://github.com/SylwekFr/lung_analysis/blob/master/patient.py) is to load the patient data [(for example)](https://github.com/SylwekFr/lung_analysis/tree/master/Data) containing a serial of slices (before_images) with related data (before_data) and another serial of slices (after_images), the before is taken by a CT-Scan device before a radiation therapy and the after after a radiation therapy by another CT-Scan device. the after serial have more slice than the before one so the number of slices of the after serial is reduced in the first step also. Still in the first step only the slices with lung present are keeped.

In the [second step](https://github.com/SylwekFr/lung_analysis/blob/master/patientSegmentation.py) both selected slices for both series are segmented to only keep lungs on the images.  and then the segmented image are the input for the 3rd step which is the registration discussed here :)

The [next step](https://github.com/SylwekFr/lung_analysis/blob/master/preprocessedImagesViewer.py) is calculation of median and average on Hounsfield Unit for different radiation range 0-5Gy, 5-10Gy, 10-20Gy, 20-30Gy and 30-40Gy (from radiotherapy) for each slices for different ROI and then make the difference between before serie and after serie for each slice, then sum median and mean difference and export to csv.

The reason why I am using 2D is more that I don't know how to reconstruct the 3D model, to segment it and to make the calculation for the next step on a 3D model (for now I do the calculation and exportation with numpy and panda).

**Comment by zivy** [comment]
OK, thanks for providing the bigger picture. Now I can confidently say that you **should not** do the registration in 2D and that the conversion to numpy arrays after loading the data is not the path you should take. 
 
For the registration to work in your case you need to use 3D SimpleITK images. Going from numpy arrays to SimpleITK loses spatial information. If you want to go this way you will have to restore the SimpleITK image's spatial information (origin, spacing, direction cosine matrix).

Not sure what you mean by 3D model, are you referring to the 3D image, a segmentation on that image, something else?

**Comment by SylwekFr** [comment]
I mean the 3D images, probably from both CT serie I should create from slides one 3D representation for each serial and probably then make all steps (segmentation, registration and calculation) on those two 3D representation, am I right ?

**Comment by zivy** [comment]
Yes, that is the recommended approach. Work in the native dimensionality of your image, 3D in your case.
If you still want to work on a slice by slice fashion you can extract them from the volume using the slicing operation (`my_image[:,:,i]` - z slice `i` from `my_image`) and afterwards you can combine the processed list of 2D slices back into a 3D volume `JoinSeries`. This 2D approach is less natural in ITK/SimpleITK, but it is possible.

**Comment by SylwekFr** [comment]
Hello @zivy , 
Thank you very much for your recommendation I will try this approach, do you recommend a specific librabry for 3D segmentation if there is any ? Does SimpleITK have this functionality ?

**Comment by zivy** [comment]
Hello @SylwekFr,

All of the filters in SimpleITK work in 2D and 3D, mostly with minimal changes to input (I assume you were using those for performing your 2D segmentation so should be readily converted to 3D). Possibly take a look at our [Jupyter notebook repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks), the Python/3* series of notebooks illustrate various segmentation tasks.
