### ISSUE TITLE
RGBtoGrayscale

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#1111]
Create a filter that converts a three channel image, interpreted as RGB, to grayscale. Possibly support multiple conversion options for various lightness definitions.
Sources:
1. https://en.wikipedia.org/wiki/HSL_and_HSV
2. https://en.wikipedia.org/wiki/Grayscale
3. https://www.insight-journal.org/browse/publication/780
4. https://www.w3.org/TR/AERT/#color-contrast

Possible output pixel types: sitkUInt8 [0,255], or sitkFloat32 [0,1].

**Comment by ryancinsight** [comment]
Was this implemented?

**Comment by zivy** [comment]
Hello @ryancinsight,

This was not implemented. The rationale is that in SimpleITK there is no notion of color spaces. An image can have three channels but these are most often not RGB. They could be in other colorspaces (e.g. HSV) or they are a way of representing several MRI scans in one image (T1, T2, FLAIR). Thus, a function that converts from RGB to gray is outside the toolkit's scope, left to the developer who knows how to correctly interpret their three channel image.

Having said that, see the `srgb2gray` function in the toolkit's [Image Details Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/b75721a121102cf972f942fad927751089a7cc80/Python/03_Image_Details.ipynb).

**Comment by ryancinsight** [comment]
@zivy worked perfectly, thank you!
