### ISSUE TITLE
How can i plot registration field in grid?

### ISSUE THREAD

**Issue by yangglebin** [SimpleITK/SimpleITK#1122]
Hello~
    I am confused about How to get warp grid from registration field. Can you show me how to do this?
The registration field plot in grid is like this:

![image](https://user-images.githubusercontent.com/26767902/83410292-b1742180-a448-11ea-943c-bd548af13ab5.png)

the registration field is like this:
![343](https://user-images.githubusercontent.com/26767902/83410722-81794e00-a449-11ea-855e-a9ac1cbf4e94.png)

**Comment by zivy** [comment]
Hello @yangglebin ,
Not exactly sure what it is you want, but below is partial code that I think answers your question:
```
import SimpleITK as sitk

#moving_image from registration, below we create a substitute
moving_image = sitk.Image(256,256, sitk.sitkFloat32) 

# create grid image that occupies the same spatial location as the
# moving_image
grid_image = sitk.GridSource(outputPixelType=sitk.sitkUInt16,
                             size=moving_image.GetSize(), 
                             sigma=(0.1,0.1), gridSpacing=(20.0,20.0))
grid_image.CopyInformation(moving_image)

sitk.Show(grid_image, "original grid image")

#warp the grid image using the result of the registration
sitk.Resample(grid_image, fixed_image, registration_result_transform)

```
If this answers your question, please close the issue, otherwise please provide additional details.

**Comment by yangglebin** [comment]
thanks, but if i have a registration field not obtained from SimpleITK, how to plot?

**Comment by zivy** [comment]
If you have a displacement field in the form of a numpy array (2D or 3D), you can convert that into a SimpleITK image and then construct a DisplacementFieldTransform from the image. Something along the lines of shown below (printing of the data sizes is there to show changes in data - consumption by the DisplacementFieldTransform). Then just apply the previously posted code:
```
import SimpleITK as sitk
import numpy as np

#2D deformation field in numpy array
deformation_arr = np.random.random((256,512,2))
print(deformation_arr.shape)

#convert numpy array to SimpleITK image
deformation_image = sitk.GetImageFromArray(deformation_arr, isVector=True)
print(deformation_arr.shape)
print(deformation_image.GetSize())

#the image is consumed by the transform, so that we minimize memory consumption
displacement_transform = sitk.DisplacementFieldTransform(deformation_image)
print(deformation_arr.shape)
print(deformation_image.GetSize())
```

**Comment by gdevenyi** [comment]
ANTs has
```
CreateWarpedGridImage 
Usage: CreateWarpedGridImage ImageDimension deformationField outputImage [directions, e.g. 1x0x0] [gridSpacing, e.g. 10x10x10] [gridSigma, e.g. 1x1x1]
```

and the code underneath is based on ITK, so you can probably find more example there.

**Comment by 2Coolge** [comment]
> Hello~ I am confused about How to get warp grid from registration field. Can you show me how to do this? The registration field plot in grid is like this:
> 
> ![image](https://user-images.githubusercontent.com/26767902/83410292-b1742180-a448-11ea-943c-bd548af13ab5.png)
> 
> the registration field is like this: ![343](https://user-images.githubusercontent.com/26767902/83410722-81794e00-a449-11ea-855e-a9ac1cbf4e94.png)
Hi yangglebin! I have deformation field and I want to plot the field as you have in this question. can you please tell me how i can plot displacement field.
