### ISSUE TITLE
ModuleNotFoundError: No module named 'SimpleITK'

### ISSUE THREAD

**Issue by sofiaphys** [SimpleITK/SimpleITK#1127]
Hello, 
I'm using MacOs 10.15.4 and although I downloaded SimpleITK it cannot be loaded on the notebook.
I've tried 

- conda install -c simpleitk simpleitk

- pip install SimpleITK

- conda install -c simpleitk/label/dev simpleitk

- git clone https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks.git

Do you have any other ideas/instructions ?

Thank you very much in advance

**Comment by blowekamp** [comment]
Have you tried the instruction along with net notebooks which describe creating a new Conda environment:

https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/README.md#anaconda

**Comment by sofiaphys** [comment]
No, I will give a try, thank you!

**Comment by blowekamp** [comment]
This issue appears to have been resolved.

**Comment by BRim28** [comment]
use:
pip install simpleitk
