### ISSUE TITLE
When the code cannot obtain the series number of dicom, how to convert the dicom of the same series to nii.gz format

### ISSUE THREAD

**Issue by wei523712** [SimpleITK/SimpleITK#1133]
I use the following code to convert the dicom files of the same series into a nii.gz format file, but some dicom files cannot get the series number.
What should I do to convert these dicom files with no serial number to nii.gz format？

reader = sitk.ImageSeriesReader()
seids = reader.GetGDCMSeriesIDs(dicom_path)
dicom_names = reader.GetGDCMSeriesFileNames(dicom_path, seids[0])
reader.SetFileNames(dicom_names)
images = reader.Execute()
sitk.WriteImage(images, '/home/1.nii.gz')

**Comment by wei523712** [comment]
Ok, thanks. I checked some original data, the serial number of the data itself is empty。

Is there any solution for this problem below：
itk::ERROR: ImageSeriesReader(0x7f4d940173d0): Size mismatch! The size of /home/20181201/1.dcm is [650, 512, 1] and does not match the required size [512, 256, 1] from file /home/20181201/2.dcm 
There are multiple dcm files in directory 20181201, and they all belong to the same series. When I try to convert the dcm file in this directory to nii.gz, there is a problem of size mismatch.

**Comment by zivy** [comment]
Hello @wei523712,

Have you looked at the two files 1.dcm and 2.dcm? Based on the error message they do not belong in the same series as they have different sizes (number of pixels per dimension). This obviously means they are not part of the same volumetric image.

As the images have an empty series number it is likely these two did not belong in the same series. 

As a next step towards gaining a better understanding of what is happening with your data I suggest that you iterate over the images and print their size and spacing. Images that belong in the same series will have the same size and spacing. This will expose any discrepancies (for now we can't know which of 1.dcm or 2.dcm represents the series and the other is from another series).

**Comment by wei523712** [comment]
ok thanks.
