### ISSUE TITLE
Image_TransformIndexToPhysicalPoint', argument 2 of type 'std::vector< int64_t,std::allocator< int64_t > > const &'

### ISSUE THREAD

**Issue by FrankyTang** [SimpleITK/SimpleITK#1136]
in_path = R"H:\04_projects\02_jpg_to_raw\mask.mhd"
  image = sitk.ReadImage(in_path)
  print(image.TransformIndexToPhysicalPoint([10, 10, 10])) # is ok.

  point = np.array([10, 10, 10]).astype(np.int64)
  print(image.TransformIndexToPhysicalPoint(point)) # wrong

  print(image.TransformIndexToPhysicalPoint(tuple(point))) # wrong
  print(image.TransformIndexToPhysicalPoint(list(point))) # wrong

Traceback (most recent call last):
  File "H:/01_codes/REMD/workspace/workspace.py", line 97, in <module>
    print(image.TransformIndexToPhysicalPoint(point))
  File "C:\Users\amax\anaconda3\lib\site-packages\SimpleITK\SimpleITK.py", line 3874, in TransformIndexToPhysicalPoint
    return _SimpleITK.Image_TransformIndexToPhysicalPoint(self, index)
TypeError: in method 'Image_TransformIndexToPhysicalPoint', argument 2 of type 'std::vector< int64_t,std::allocator< int64_t > > const &'

**Comment by FrankyTang** [comment]
and i find another condition.
  box_center = ((box_max + box_min) / 2.0).astype(np.int64)
  center_mm = image.TransformIndexToPhysicalPoint((int(box_center[0]), int(box_center[1]), int(box_center[2]))) # is ok.
  center_mm = image.TransformIndexToPhysicalPoint((box_center[0], box_center[1], box_center[2])) # is wrong.

**Comment by zivy** [comment]
@blowekamp, is this also related to #106? I believe we only support basic Python types (int, float..) and not numpy types. Should we extend the support to numpy types?

@FrankyTang when you do `tuple(point)` or `list(point)` the problem is the same as the original, the usage of np.int64.

**Comment by FrankyTang** [comment]
Thanks @zivy . I always thought it was a data structure problem(as np.array, list , tuple).But it actually is a data element type problem. So , if the data element support the implicit conversion, it is prefect.Forgive my poor english which buttoned my feet.
