### ISSUE TITLE
Converting NRRD to DICOM?

### ISSUE THREAD

**Issue by praveen5959** [SimpleITK/SimpleITK#1146]
Can we convert NRRD to DICOM using SimpleITK? 

If so can someone help me with the code snippet?

**Comment by zivy** [comment]
Yes.
Please see the [examples on read-the-docs](https://simpleitk.readthedocs.io/en/master/link_examples.html), the relevant ones are "Dicom Series Read Modify Write" and "Dicom Series From Array".

**Comment by dave3d** [comment]
It can be as simple as this:

    import SimpleITK as sitk
    sitk.ReadImage("input.nrrd")
    sitk.WriteImage("output.dcm")

If your NRRD is a 3d volume, this will write a 3d DICOM image.   If you want to write out a series of slices, you can look at the following example:

https://simpleitk.readthedocs.io/en/next/Examples/DicomSeriesFromArray/Documentation.html

**Comment by praveen5959** [comment]
I tried the DicomSeriesFromArray method and I was able to convert it, but I had some doubts:

`new_img.SetSpacing([2.5,3.5,4.5])`

What does these values for SetSpacing do? Does my output DICOM images change according to these values?

**Comment by zivy** [comment]
Yes, that code changes the image spacing. In your case you should not do that.

**Comment by praveen5959** [comment]
So keep the values as given in the doc right?

**Comment by zivy** [comment]
Not sure what you mean by "values given in the doc". You just don't need to create the image as you are reading it. All lines including and after `writer = sitk.ImageFileWriter()` remain as is.

**Comment by praveen5959** [comment]
So can you specify how the SetSpacing() works? How the arguments and between which things it provides the spacing?

**Comment by zivy** [comment]
To better understand the SimpleITK Image structure, please read our [Fundamental Concepts](https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html) page, and [this Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/03_Image_Details.ipynb).

**Comment by praveen5959** [comment]
Thank you for the info
