### ISSUE TITLE
Exception about ConstantPadImageFilter

### ISSUE THREAD

**Issue by xulunk** [SimpleITK/SimpleITK#1149]
Python version: 3.7.7
simpleitk version: .1.2.4

When I pad image using simpleitk in my code, I got the exception in constantpadimagefilter:
>   File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\SimpleITK\SimpleITK.py", line 22001, in Execute
>     return _SimpleITK.ConstantPadImageFilter_Execute(self, *args)
> NotImplementedError: Wrong number or type of arguments for overloaded function 'ConstantPadImageFilter_Execute'.
>   Possible C/C++ prototypes are:
>     itk::simple::ConstantPadImageFilter::Execute(itk::simple::Image const &)
>     itk::simple::ConstantPadImageFilter::Execute(itk::simple::Image const &,std::vector< unsigned int,std::allocator< unsigned int > > const &,std::vector< unsigned int,std::allocator< unsigned int > > const &,double)

When I extract the image_padding function to an independent python script as below, it works well.
I checked the arguments by print them out, but didn't find any clue
I would appreciate any suggestions you may have.

```
import SimpleITK as sitk
import numpy as np

def image_padding(img, lower_bound=[0,0,0], upper_bound=[0,0,0], constant=0):
    filt = sitk.ConstantPadImageFilter()
    print('i am inside padding now')
    print(type(img))
    print(lower_bound)
    print(upper_bound)
    print(constant)
    padded_img = filt.Execute(img, lower_bound, upper_bound, constant)
    return padded_img


def main():
    #img = np.ones((512,512,64))
    #img_itk = sitk.GetImageFromArray(np.transpose(img, (2,1,0)))
    img_itk = sitk.ReadImage('test_cropped.nii.gz')
    img_itk_pad = image_padding(img_itk, [0, 0, 0], [0, 0, 4], 0)
    sitk.WriteImage(img_itk_pad, 'test_img.nii.gz')

main()
```

**Comment by dave3d** [comment]
I'm not sure what is going on.  I ran your code, and it worked fine for me.  Here is the output for me:

    source image size: (512, 512, 64)
    i am inside padding now
    <class 'SimpleITK.SimpleITK.Image'>
    [0, 0, 0]
    [0, 0, 4]
    0
    output image size: (512, 512, 68)

I put in a couple prints of the image sizes, and I used your commented out numpy array as input.

**Comment by zivy** [comment]
Your SimpleITK code is fine. I suspect that in your integrated code you are passing a numpy array as one of the inputs instead of a list to the `image_padding` function. That will trigger the error in the code you provided. This is related to https://github.com/SimpleITK/SimpleITK/issues/106.

**Comment by xulunk** [comment]
@dave3d @zivy 

Thanks a lot for your reply.
I wonder why the code can work fine independently while throw exception in my integrated code.
I added some print code to check the type of the inputs,  and here is the code and log info when I run the integrated code.  So I am sure that I did input a  SimpleITK.SimpleITK.Image to the image_padding function.
Do you think there are anything else that I should check?

```
def image_padding(img, lower_bound=[0,0,0], upper_bound=[0,0,0], constant=0):
    filt = sitk.ConstantPadImageFilter()
    print('i am inside padding now')
    print(type(img))
    print(lower_bound)
    print(type(lower_bound))
    print(upper_bound)
    print(type(upper_bound))
    print(constant)
    print(type(constant))
    padded_img = filt.Execute(img, lower_bound, upper_bound, constant)
    return padded_img

```
> i am inside padding now
> <class 'SimpleITK.SimpleITK.Image'>
> [0, 0, 0]
> <class 'list'>
> [0, 0, 4]
> <class 'list'>
> 0
> <class 'int'>

**Comment by xulunk** [comment]
@dave3d @zivy

Finally I found the reason. The upper_bound I input was  class 'numpy.int32'.
After I convert it to class 'int'. The code works fine now.
Thanks for your suggestion to check the class.
