### ISSUE TITLE
Unexpected result when applying transformation to .mha image

### ISSUE THREAD

**Issue by 1989HD** [SimpleITK/SimpleITK#1159]
Dear all,

I have two CT images of the knee which are segmented using a neural network. I have converted these segmentations into two .stl meshfiles and registered these using a coherent point drift algorithm in matlab. Applying the rotation translation to the moving pointcloud shows good results (see fig below). When I superimpose the meshfile onto the targetimage, this also gives the expected result.
![resultpcregistration](https://user-images.githubusercontent.com/41747965/89549465-a0f57400-d808-11ea-9c57-5580e22e57b5.jpg)
 
Now I would like to apply the same transformation to the .mha imagefile using SimpleITK. I've tried this by writing a transform file and using the script below to execute the transform. 
[transformfile.txt](https://github.com/SimpleITK/SimpleITK/files/5035851/transformfile.txt)

This however does not give me the results I was looking for, as there is no overlap in the image structures (or in the image at all for that matter). Unfortunately I'm unable to figure why it isn't working as I expect.

I'm hoping someone can point me in the right direction. 

Thanks in advance for any responses. 

Hans

p.s. As the new image direction I use an identity matrix. The moving image has a (1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0) as a direction, could this be (part of) the issue? However if I take the new direction = img.GetDirection(), the resulting resample space is completely blank.

```
import numpy as np
import SimpleITK as sitk
import math


inpath = 'imagetoberotated.mha'
outpath= 'output.mha' 
transform = 'transformfile.txt' 

img = sitk.ReadImage(inpath)

extreme_points = [img.TransformIndexToPhysicalPoint((0,0,0)),
                  img.TransformIndexToPhysicalPoint((img.GetWidth(),0,0)),
                  img.TransformIndexToPhysicalPoint((img.GetWidth(),img.GetHeight(),0)),
                  img.TransformIndexToPhysicalPoint((0,img.GetHeight(),0)),
                  img.TransformIndexToPhysicalPoint((0,0,img.GetDepth())),
                  img.TransformIndexToPhysicalPoint((img.GetWidth(),0,img.GetDepth())),
                  img.TransformIndexToPhysicalPoint((img.GetWidth(),img.GetHeight(),img.GetDepth())),
                  img.TransformIndexToPhysicalPoint((0,img.GetHeight(),img.GetDepth()))]

affine = sitk.ReadTransform(transform)
inv_aff = affine.GetInverse()
extreme_points_transformed = [inv_aff.TransformPoint(pnt) for pnt in extreme_points]

min_x = min(extreme_points_transformed)[0]
min_y = min(extreme_points_transformed, key=lambda p: p[1])[1]
min_z = min(extreme_points_transformed, key=lambda p: p[2])[2]
max_x = max(extreme_points_transformed)[0]
max_y = max(extreme_points_transformed, key=lambda p: p[1])[1]
max_z = max(extreme_points_transformed, key=lambda p: p[2])[2]


nw_spacing = img.GetSpacing()
nw_direction = np.eye(3).flatten()

nw_ori = [min_x, min_y, min_z]
nw_Defaultpixelvalue = float(-2048)
sz_out1 = [math.ceil((max_x-min_x)/nw_spacing[0]),math.ceil((max_y-min_y)/nw_spacing[1]),math.ceil((max_z-min_z)/nw_spacing[2])]

resamp1img = sitk.Resample(img,sz_out1,affine,sitk.sitkLinear,nw_ori,nw_spacing,nw_direction,nw_Defaultpixelvalue)
sitk.WriteImage(resamp1img,outpath)
```

**Comment by zivy** [comment]
Hello @1989HD,

Not clear exactly what it is you want to do. Below is my understanding:
1. Blue points - extracted in fixed image coordinate system.
2. Red points - extracted in moving image coordinate system.
3. Registration using coherent point drift yields an affine transformation, not rotation-translation. This transformation maps points from the fixed image coordinate system to the moving image coordinate system. You applied the transformation to the blue points and they were mapped close to the red ones.

Here is what's not clear:
4. You want to: (a) define a grid in the fixed coordinate system and resample the moving image using that, or (b)  define a grid in the moving coordinate system and resample the fixed image?

In both cases I'd recommend starting with the grid defined by the images, don't define your own unless you know how to position it relative to the image.

If option (a) then use the transformation as is and the fixed image defines your grid. If option (b) then use the inverse transformation `tx.GetInverse()` and the moving image defines your grid.

**Comment by 1989HD** [comment]
Hi @zivy 

Thanks for your response and sorry for the confusion. 

I have two CT images, both in their own coordinate system. I have segmented both images and made them into pointclouds (these pointclouds overlap their corresponding images) I then used a rigid registration (so only translation and rotation)on these pointclouds, with the picture above as the result (red = fixed, blue = moving).

From this registration I have a rotationmatrix and translationvector that I would like to apply to the .mha image to superimpose the images. For this I use the script above. 

As I apply the same rotation and translation to the image, I would expect the same results as with the pointclouds, i.e. superimposed tibiae. I do get an outputimage, but when I overlay the target and moving image, the tibiae are not superimposed. I do not understand why this is the case and what I'm doing wrong.

I hope this clarifies my question! 

Regards 

Hans

**Comment by zivy** [comment]
Hello @1989HD ,

Based on the transformation file you provided, you are not doing rigid registration (rotation, translation), you are doing affine (rotation, translation, scaling, shearing and reflection). The resulting matrix does not represent a rotation (RR^T=1 and det(R) =1).

Are you using [this matlab function](https://www.mathworks.com/help/vision/ref/pcregistercpd.html)? If yes, did you specify the optional transformation type? Default transformation type isn't rigid. Two possible issues: (1) The matlab result isn't a rotation matrix and the writing operation is fine. (2) The matlab result is a rotation and the writing operation modifies the data somehow.

Finally, ignoring the transformation type, I would suggest simply to resample the moving image onto the fixed image grid using the transformation you obtained. This will work for all transformation types.

```
import SimpleITK as sitk

fixed_image = sitk.ReadImage('fixed_image.mha')
moving_image = sitk.ReadImage('moving_image.mha')
tx = sitk.ReadTransform('transformfile.txt')
moving_resampled = sitk.Resample(moving_image, fixed_image, tx, sitk.sitkLinear, 0.0, moving_image.GetPixelID())
```

**Comment by 1989HD** [comment]
@zivy Thanks again for your reply!

Actually I'm using a different CPD algorithm that does result in a rigid transformation. There is no shearing, scaling or reflection. I write this to a transform file (.txt) from Matlab. When I calculate the dot(T,T') I do get 1 actually. The reason why you do not find the matrix to be orthogonal could be probably a precision error? http://itk-users.7.n7.nabble.com/Problems-with-the-orthogonal-rotation-matrix-in-versorRigid3DTransform-td26941.html 

The reason why I use Affine instead of any other transform is that it is (to my knowledge at least) is the only transformfile which directly contains a 3x3 rotation matrix (although flattened), and thus not requires for me to convert the rotations to another format. Am I right to assume that when other parameters like transform.Scale & transform.Skew are all zero, this is equivalent to a rigid transformation?  I will write it into a .tfm that is suitable for a VersorRigid3DTransform.

With respect to the resampling grid, your method will indeed give me the correct resampling grid if the transformation is done right, thanks! I will try this to get the transform right. However, I believe this might cause part of the moving image to fall out of the resampling grid, and I'm also interested in that part. 

Regards,

Hans

**Comment by zivy** [comment]
Hello @1989HD,

Easiest approach is to use the [Euler3DTransform](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1Euler3DTransform.html) (clear understanding of the rotation parameterization, three angles as opposed to unit quaternion).  Use its `SetMatrix` and `SetTranslation` methods.

The problem with the transformation file you provided is that it doesn't represent a rigid transformation, this isn't a precision issue, the matrix has a determinant of -1, so it isn't a rotation it's a reflection. I suspect the implementation of the CPD algorithm you are using admits reflections, similar to the issue solved by Umeyama vs. Arun's algorithm for absolute orientation - nothin new under the sun), code below shows this:
```
import SimpleITK as sitk
import numpy as np

tx = sitk.AffineTransform(sitk.ReadTransform('transformfile.txt'))
np_mat = np.array(tx.GetMatrix()).reshape(3,3)
np.linalg.det(np_mat)
```
With respect to resampling grid size, you can take the grid defined by the fixed image (spacing, direction cosine matrix) and simply enlarge it (bigger size, and move the origin based on the new size you use - how it pads the original grid).
