### ISSUE TITLE
Could the resampling (template based) of a CT image, lead to a cropped version of it?

### ISSUE THREAD

**Issue by makquel** [SimpleITK/SimpleITK#1160]
In order to align(Register) a CT scan, I'm currently using an [age-specific CT template](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3376197/) [Roden et. al], which has certain dimensions and pixel spacing.  This registration template needs to match the patient's size and pixel spacing. One way to solve this is to resample the original template. The following snippet tries to do it, however, I end up with a cropped version of template's border 

```python
def resampleTemplate(patient_CT, template_CT):
    '''
        original_CT: patient CT series
        template_CT: Chris Rorden's template
    '''
    original_CT = sitk.ReadImage(patient_CT)
    scct = sitk.ReadImage(template_CT)
​
    dimension = original_CT.GetDimension()
​
    reference_image = sitk.Image(original_CT.GetSize(), original_CT.GetPixelIDValue())
    reference_image.SetOrigin(scct.GetOrigin())
    reference_image.SetSpacing(original_CT.GetSpacing())
    reference_image.SetDirection(scct.GetDirection())
 ​
    reference_center = np.array(reference_image.TransformContinuousIndexToPhysicalPoint(np.array(original_CT.GetSize())/2.0))

​
    transform = sitk.AffineTransform(dimension)
    # To keep the original transform
    transform.SetMatrix(np.identity(dimension).flatten())
    transform.SetTranslation(np.array(scct.GetOrigin())- np.zeros(dimension))
    # Modify the transformation to align the centers of the original and reference image instead of their origins.
    centering_transform = sitk.TranslationTransform(dimension)
    img_center = np.array(scct.TransformContinuousIndexToPhysicalPoint(np.array(scct.GetSize())/2.0))
    offset = np.array(transform.GetInverse().TransformPoint(img_center) - reference_center)
    # print(offset)
    centering_transform.SetOffset(offset)
    centered_transform = sitk.Transform(transform)
    centered_transform.AddTransform(centering_transform)
  
    return sitk.Resample(scct, reference_image, centered_transform, sitk.sitkLinear, 0.0)
```
For instace, template's dimentions are 217 x 217 x 181 (left image) and target (resampled) dimentions are 512 x 512 x 501(right image).

![Screenshot from 2020-08-06 14-08-06](https://user-images.githubusercontent.com/1332029/89572267-473c7c00-d7ff-11ea-8932-9aadb8428631.png)

So, even though the resampled image has the right dimensions and pixel spacing, it has been cropped for some reason.

**Comment by zivy** [comment]
Hello @makquel,

Not exactly sure about your code. I think it is a bit complicated for the task at hand, at least my understanding of what you want: mapping points from the patient image to the template image. Essentially resampling the template onto the grid defined by the patient image.

Possibly the following solves your issue? If not, please elaborate so that we can help you resolve the issue.

```
def resampleTemplate(patient_CT, template_CT):
    '''
        original_CT: patient CT series
        template_CT: Chris Rorden's template
    '''
    original_CT = sitk.ReadImage(patient_CT)
    scct = sitk.ReadImage(template_CT)
    dimension = scct.GetDimension()

    # Mapping one parallelepiped onto another using an affine transformation.
    scalings = [((sz_t-1)*spc_t)/((sz_p-1)*spc_p) for sz_t, sz_p, spc_t, spc_p in zip(scct.GetSize(), original_CT.GetSize(), scct.GetSpacing(), original_CT.GetSpacing())]    
    world2patient = np.array(original_CT.GetDirection()).reshape(dimension, dimension)
    world2template = np.array(scct.GetDirection()).reshape(dimension, dimension)
    mat = np.dot(np.diag(scalings), np.dot(world2template, np.transpose(world2patient)))
    
    tx = sitk.AffineTransform(dimension)
    tx.SetMatrix(mat.ravel())
    tx.SetTranslation(np.array(scct.GetOrigin()) - np.array(original_CT.GetOrigin()))
    
    return sitk.Resample(scct, original_CT, tx)

```

**Comment by makquel** [comment]
Hi @zivy, thanks for the prompt reply, I completely missed this issue notification.

Regarding the snippet you provide me above, It didn't work, even though the resulting image, which has the patient's image dimensions and pixel spacing, was completely black, and that's the reason why I used resampling function instead. So let me elaborate better my question. 

I've got a CT template (image below) for CT registration that has a size of [121,145,121] and pixel spacing of [1.5x1.5x1.5] mm. In order to perform such a task, I need to resample the CT template to match each patient's image size and pixel spacing. 
 
![Screenshot from 2020-08-10 09-52-59](https://user-images.githubusercontent.com/1332029/89784597-523d2800-daef-11ea-8503-4b3c75e58b10.png)
For instance, let's say that our target patient's dimensions are [512,512,501] and pixel spacing [0.33,0,33,0,29] mm, so the resampled/resized template should match patient's properties. 
For the record, I've already tried to add arbitrary padding to the template's image, thus, I end up with the same cropped results. Am I missing something?

**Comment by zivy** [comment]
Hello @makquel,
I'm surprised that the code snippet didn't work. Can you share your template and a single CT so that I can figure out why that solution doesn't work?

**Comment by makquel** [comment]
@zivy sure thing!

Could you download the requested by clicking in this [link](https://mega.nz/folder/u9xyza7J#k_q0hqGiTovUX074IQoi3A) 
rscct.nii is the registration templated that I mentioned before.
Let me know if it work it for you!

**Comment by zivy** [comment]
Hello @makquel ,
The code I provided was incorrect, ignore it for now. The reason you are seeing cropping has to do with the physical size of the reference image as compared to the physical size of the template image. As your transformation has no scaling and you are aligning the centers of the images, the result won't fit into the physical extent defined by the reference, so it's cropped.

The template image is a bit strange, it has a direction cosine matrix which is a reflection.

In theory if you identify four corresponding points in the template and patient CT you can get the affine transformation that maps from the patient CT to the template using the `LandmarkBasedTransformInitializer`. Possibly four of the corners of the two images which will ensure that the template isn't cropped. The only thing though is that I'm not sure if the corners are the relevant matches with the reflection settings for the template.

**Comment by makquel** [comment]
Hi @zivy,

As a matter of fact, the template image has LAS orientation which is a radiological convention for orientation. instead of LPS.
Thanks for the feedback regarding the transformation, however, since I need to process several images, It would be impractical to perform landmark-based resampling or registration.
Notice that in order to deal with the template reflection, in the proto-function `resampleTemplate` I keep the original cosine matrix instead of the identity matrix. Not quite sure if this is the correct approach.

**Comment by zivy** [comment]
Hi @makquel 

OK, below is the solution, let me know if this worked for you. Note that I am using a "new" class we introduced into SimpleITK `CompositeTransform`. It is a refactored version of `Transform`. This is part of the changes in the upcoming SimpleITK 2.0 release. I highly recommend that you upgrade to it starting with the [release candidate](https://github.com/SimpleITK/SimpleITK/releases).


```
def resampleTemplate(patient_CT, template_CT):
    '''
        original_CT: patient CT series
        template_CT: Chris Rorden's template
    '''
    original_CT = sitk.ReadImage(patient_CT)
    scct = sitk.ReadImage(template_CT)
    
    dimension = original_CT.GetDimension()
    
    reference_image = sitk.Image(original_CT.GetSize(), original_CT.GetPixelIDValue())
    reference_image.SetOrigin(scct.GetOrigin())
    reference_image.SetSpacing(original_CT.GetSpacing())
    reference_image.SetDirection(scct.GetDirection())
    
    reference_center = np.array(reference_image.TransformContinuousIndexToPhysicalPoint(np.array(original_CT.GetSize())/2.0))
    template_center = np.array(scct.TransformContinuousIndexToPhysicalPoint(np.array(scct.GetSize())/2.0))
    scalings = [((sz_t-1)*spc_t)/((sz_p-1)*spc_p) for sz_t, sz_p, spc_t, spc_p in zip(scct.GetSize(), original_CT.GetSize(), scct.GetSpacing(), original_CT.GetSpacing())]    
    
    st = sitk.ScaleTransform(dimension)
    st.SetCenter(reference_center)
    st.SetScale(scalings)
    tr = sitk.TranslationTransform(dimension)
    tr.SetOffset(template_center - reference_center)
    
    tx = sitk.CompositeTransform([tr, st])
  
    return sitk.Resample(scct, reference_image, tx, sitk.sitkLinear, 0.0)
```

**Comment by makquel** [comment]
Hi @zivy,

Awesome! that worked like charm! I'm clossing this issue; thanks for your help!
