### ISSUE TITLE
how to get DICOM description

### ISSUE THREAD

**Issue by HaoLi12345** [SimpleITK/SimpleITK#1177]
Hi

I'm using simpleitk to convert a DICOM series to nifti.
I have a directory which contains all DICOM series, e.g. several series(T1 image series, T2 image series etc.) in 1 folder.

I used sitk.ImageSeriesReader() to get the series ID and convert corresponding DICOM to nifti.
I followed this example, https://simpleitk.readthedocs.io/en/next/Examples/DicomSeriesReader/Documentation.html

Here is my question: 

Since I have multiple series in 1 folder, how can I find each series description(when loading DICOM with itksnap, the description is shown as 'SAG T1', 'AX FLAIR' ) with simpleitk, that I can name the nifti images.

**Comment by HaoLi12345** [comment]
GetMetaDataKeys()
GetMetaData()
those 2 functions help.

for example, this meta key ( (0020|0011) ) means a specification mata data(seems the series number).
Can some one help me with meta data dictionary, I want to see the meaning of each key. 
Thank you!

**Comment by zivy** [comment]
To get the DICOM description associated with the tags you can use a service like that from [innolitics](https://dicom.innolitics.com/ciods#), see the search tab on the top right where you can enter the DICOM tag. Note that they use a comma as the separator between the group number and element number.

**Comment by HaoLi12345** [comment]
thank you very much!
