### ISSUE TITLE
Add support for MINCTransformIO

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#1179]
MINCTransformIO support missing from the supported transformation IOs.

**Comment by blowekamp** [comment]
The ITK TransfromMINC module in not enabled by default in ITK:
https://github.com/InsightSoftwareConsortium/ITK/blob/26079ef391de2df99fa65afaa67432e53c253842/Modules/IO/TransformMINC/itk-module.cmake#L22

By enabling this module for the ITK super build should enable the TransformIO for SimpleITK>
