### ISSUE TITLE
Deformable Image registration using simpleITK python framework

### ISSUE THREAD

**Issue by subhajitchatu** [SimpleITK/SimpleITK#118]
I am looking for deformable registrations using SimpleITK python framework.

As in RegistrationITKV4 there are FEM based ( itkFEMRegistrationFilter.h) deformable registration and thin plate spline code is available, I was trying to figure out how to start using them in SimpleITK or python based platform.

Demon registration is available in SimpleITK.

I need a sample code snippet for how to use FEM in simpleITK( python)

Thanks

**Comment by zivy** [comment]
SimpleITK currently only supports non-rigid registration using Free Form Deformation and the Demons approach. Will add this as a feature request for a future version of SimpleITK.

**Comment by dave3d** [comment]
Related to https://github.com/SimpleITK/SimpleITK/issues/186

See comment there.

**Comment by blowekamp** [comment]
We are not going to extend SimpleITK to include FEMRegistrationFilter advanced registration. It is recommended to look into other end user applications built on ITK such as[ ANTs](http://stnava.github.io/ANTs/) or [Elastixs](http://elastix.isi.uu.nl).
