### ISSUE TITLE
Coordinates to NRRD Mask

### ISSUE THREAD

**Issue by praveen5959** [SimpleITK/SimpleITK#1184]
Is there any way to convert ROI Volume (Say Contour or Polygon) to NRRD Mask?

**Comment by zivy** [comment]
Hello @praveen5959,

Unfortunately, SimpleITK does not have a way of converting a contour to an image mask. It does have the other way round, mask to contour, [LabelContourImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1LabelContourImageFilter.html).

The operation you are looking for is known as scan conversion or rasterization. For an algorithmic discussion see [this lecture note](https://www.cs.tau.ac.il/~dcor/Graphics/cg-slides/scan04.pdf). VTK has a class [vtkPolyDataToImageStencil](https://vtk.org/doc/nightly/html/classvtkPolyDataToImageStencil.html) which does what you need. For additional details see [this stackoverflow discussion](https://stackoverflow.com/questions/60622555/how-in-vtk-i-read-a-stl-file-and-write-to-a-mha-file).

**Comment by praveen5959** [comment]
I want to get binary data from co-ordinates so that I can use pynrrd and write it into nrrd file. Is there anyway to do that?

**Comment by zivy** [comment]
Hello @praveen5959,

If what you need is to convert a polygon represented as a list of vertices into a voxel/pixel based mask, then the answer remains the same as in the previous response. If this is not what you are looking for then please provide additional details.
