### ISSUE TITLE
ImageSeriesReader() slices mismatch

### ISSUE THREAD

**Issue by HaoLi12345** [SimpleITK/SimpleITK#1185]
Hi

I'm using simpleitk    ImageSeriesReader() to convert dicom to nifti.

I have T1, FLAIR, T2 and PD images in my dicom series.

I used:
reader = sitk.ImageSeriesReader()
for dicom_series_id in reader.GetGDCMSeriesIDs(dicom_directory):
    dicom_names = reader.GetGDCMSeriesFileNames(dicom_directory, dicom_series_id)
    reader.SetFileNames(dicom_names)
    image = reader.Execute()

For T1 and FLAIR, they are converted very well. 
But for T2 and PD, the slice mismatchs. For example, T2-w image has 100 slices(the slice with odd number is PD image). slice 0:2:99 is T2, slice 1:2:99 is PD. Same for the PD image.

I think this is because series_id mismatchs?

Thanks for helping!

![image](https://user-images.githubusercontent.com/56284140/92010450-73202400-ed0f-11ea-94d6-d00004504fc5.png)
slice 'x'
![image](https://user-images.githubusercontent.com/56284140/92010536-8501c700-ed0f-11ea-8e0b-1dceab6b4fd6.png)
slice 'x+1'

**Comment by zivy** [comment]
Hello @HaoLi12345,

I suspect that the T2 and PD images don't have unique series IDs which is how the `GetGDCMSeriesFileNames` identifies files as belonging to the same volume. Please print the  list of series ids you get from `reader.GetGDCMSeriesIDs(dicom_directory)`, if the number of series IDs is not 4 then multiple series are sharing the same ID. 

In this case, you will need to use another DICOM tag to separate the T2 and PD image file names into different lists before reading. Possibly the series time tag '0008|0031' is different between them even though they share the same series number. If not, you will need to find a tag that is distinct to each of the series.

Finally, the reason you are getting interleaved slices between the series is that there are two slices for each z location, so when the slices are sorted for reading you get T2_z0, PD_z0, T2_z1, PD_z1... .

**Comment by HaoLi12345** [comment]
I'm new to simpleitk and thanks for answering.

How to set a new tag? or how to use the tag '0008|0031' to separate them?

**Comment by zivy** [comment]
Hello @HaoLi12345,

This is more of a DICOM issue than a SimpleITK issue. It is up to you to decide which tag can be used to separate the data. You will need to familiarize yourself with the meaning of the tags (they are reported using their numerical values and the DICOM standard tells you what they mean).

When you have the list of files you can go over their DICOM tags and see if there is a tag that can be used to separate the data. Below is code that prints the tag values for the first two images in the file list:

```
import SimpleITK as sitk

dicom_directory = 'CIRS/'
reader = sitk.ImageSeriesReader()

series_ids = reader.GetGDCMSeriesIDs(dicom_directory)
dicom_names = reader.GetGDCMSeriesFileNames(dicom_directory,series_ids[0])
reader.SetFileNames(dicom_names)

# Have the reader read all of the DICOM metadata information, including private data
reader.MetaDataDictionaryArrayUpdateOn()
reader.LoadPrivateTagsOn()
image = reader.Execute()

# print all the tags for image_0 and image_1
for i in range(2):
    print('*'*30)
    for k in reader.GetMetaDataKeys(i):
        print('{0}: {1}'.format(k, reader.GetMetaData(i,k)))
```

**Comment by HaoLi12345** [comment]
thanks for helping me, this is really helpful!
