### ISSUE TITLE
Overlap and hausdroff measure after registration

### ISSUE THREAD

**Issue by subhajitchatu** [SimpleITK/SimpleITK#119]
Hi,
I have registered two images, let's say fixed and moving are Registered. After registration I want to measure overlap ratio etc.
The overlap_measures_filter.Execute(fixed, moving) and hausdroff_measures_filter.Execute() returns huge false negatives and positives. It seems it is not working. How exactly can I use these functions for registration evaluation?

**Comment by zivy** [comment]
To evaluate your registration using segmentation you will first need to resample the segmentation of the moving image onto the fixed image domain using a nearest neighbor interpolator, then you can evaluate the quality of the registration using overlap measures or surface distance measures. [This](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/65_Registration_FFD.ipynb) Jupyter Python notebook illustrates how to do it. 

A more detailed evaluation of segmentation is provided in [this](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/34_Segmentation_Evaluation.ipynb) notebook.
