### ISSUE TITLE
Swig build triggers JDK install dialog on mac

### ISSUE THREAD

**Issue by pieper** [SimpleITK/SimpleITK#1190]
When building SimpleITK as part of Slicer, the Swig configure/build step triggers this dialog if the JDK is not installed:

![image](https://user-images.githubusercontent.com/126077/92496300-f802b600-f1c5-11ea-9546-76ea7db3f43e.png)

The dialog can be ignored with no consequences and the easy workaround would be to install the JDK, but it would be much nicer if we could avoid triggering the dialog because it may lead people to think that java is a hard requirement rather than an option.

**Comment by blowekamp** [comment]
Thank you for reporting the issue.

This is a change of behavior for SWIG 3.x to 4.x?

Adding the " --without-java" flag to the [SWIG config](https://github.com/SimpleITK/SimpleITK/blob/master/SuperBuild/swig_configure_step.cmake.in#L32) may prevent the dialog from popping up. 

Do you have a system where this could be tested?

**Comment by pieper** [comment]
Hi @blowekamp - I think this just started showing up for me in the past few weeks, but I also switched to a new machine and my old machine had the JDK installed.

Yes, I had tried adding that line and rebuilding but no change but I didn't try a fresh build yet;  I am testing something else but can try in a bit.

**Comment by blowekamp** [comment]
I would try just directly configure SWIG on the command line to first see if the dialog pops up, and then if the added command line option resolves the issue.

Debugging a Superbuild within a Superbuild is more that I can figure out through Github comments. :)

**Comment by pieper** [comment]
> Debugging a Superbuild within a Superbuild is more that I can figure out through Github comments. :)

LOL, I agree!

In the end you had the right solution but the not the right file, at least for slicer.  I changed the Slicer Swig superbuild and that fixes things.

https://github.com/Slicer/Slicer/pull/5178

You might want to merge the PR for SimpleITK's superbuild too to avoid the same issue.

**Comment by blowekamp** [comment]
> You might want to merge the PR for SimpleITK's superbuild too to avoid the same issue.

SimpleITK supports Java, so we don't want to disable it. It is fortunate that Slicer already has its own build of SWIG to customize.
