### ISSUE TITLE
Issue with pip version of 2.0

### ISSUE THREAD

**Issue by pimmoeskops** [SimpleITK/SimpleITK#1192]
Installing version 2.0 with pip seems to cause segfaults in pytorch. The issue does *not* appear when installed with conda. 

With versions:
SimpleITK==2.0.0rc2
torch==1.6.0
onnx==1.7.0

The following would happen:
```
>>> import SimpleITK
>>> import torch
>>> import onnx
Segmentation fault (core dumped)
```

Installing rc2 with conda did not cause any issues.

**Comment by zivy** [comment]
Hello @pimmoeskops,

As we recently [released RC3](https://github.com/SimpleITK/SimpleITK/releases), would you be willing to test with that?

**Comment by pimmoeskops** [comment]
Yes sorry, I also tried with rc3, which had the same issue.

**Comment by blowekamp** [comment]
Hello,

Could you please provide information to reproduce this issue. Some information to include is listed here: https://github.com/SimpleITK/SimpleITK#report-an-issue

**Comment by pimmoeskops** [comment]
Thank you for the quick replies, below is some additional information to reproduce the issue.

Error message: Segmentation fault (core dumped)
OS: Ubuntu 18.04
Language: Python 3.7
SimpleITK version: 2.0.0rc2, 2.0.0rc3
Installation: 
`pip install --pre SimpleITK --find-links https://github.com/SimpleITK/SimpleITK/releases/tag/v2.0rc3`

**Comment by blowekamp** [comment]
Is this the system python, anaconda, or some other distribution?

**Comment by pimmoeskops** [comment]
In an anaconda environment

**Comment by dave3d** [comment]
I was able to re-create the crash that @pimmoeskops reports.  Interestingly enough, when I imported SimpleITK last, it did not core dump.

**Comment by blowekamp** [comment]
This issue has been addressed in PR #1210 and has been merged into master. It is available in the ["latest"](https://github.com/SimpleITK/SimpleITK/releases/tag/latest) nightly packages. Please download and test the package to verify it resolves the issue. Then it can be merged into the release branch for 2.0.1.

**Comment by pimmoeskops** [comment]
Thanks! Just tried it and did not experience any issues.

**Comment by blowekamp** [comment]
SimpleITK 2.0.1 has been uploaded to pypi which addresses this issue.
