### ISSUE TITLE
Error in sitk.Show

### ISSUE THREAD

**Issue by SouthAmericaB** [SimpleITK/SimpleITK#1199]
Hi!
I'm trying to see images with sitk.Show command.
I use Anaconda and Spyder like python IDE.

I have searched for my error in several webpages and I've tried a lot of solutions (ensure ImageJ installation, set SITK_SHOWN_COMMAND...), but nothing works.

Also I've tried to execute sitk.Imageviewer  but there are problems too.

An example of code:

```
import sys
import SimpleITK as sitk

grid_image = sitk.GridSource(outputPixelType=sitk.sitkUInt16, size=(512,512),
                             sigma=(0.1,0.1), gridSpacing=(20.0,20.0))
image_viewer=sitk.ImageViewer()
image_viewer.SetApplication('C:/Users/Usuario/ImageJ')

image_viewer.Execute(grid_image)
sys.exit( 0 )
```

The error:
`RuntimeError: Exception thrown in SimpleITK ImageViewer_Execute: C:\SimpleElastix\SimpleElastix\Code\IO\src\sitkImageViewer.cxx:542:
sitk::ERROR: Process returned 1.
Command line: 'C:/Users/Usuario/ImageJ' 'C:\\Users\\Usuario\\AppData\\Local\\Temp\\TempFile-8492-6.mha' `

Could you help me please?
Thank you very much in advance!

**Comment by dave3d** [comment]
The SetApplication method is expect the path to the actual ImageJ executable, not the parent folder.  So for a standard Windows version of ImageJ/Fiji, it's looking for the path to the file **ImageJ-win64.exe**.

Note that on Windows you should use backslash, '\', not forward slash.

**Comment by SouthAmericaB** [comment]
Ooooooooooh! It works!! What a little bur great detail!

Thank you very very much! You're very kind :)
