### ISSUE TITLE
bspline parameter tuning for multimodal 3D registration

### ISSUE THREAD

**Issue by subhajitchatu** [SimpleITK/SimpleITK#120]
I was trying to register two dicom image (T1W and T2W , 60 slices each) on a 8gb, quadcore processor (Ubuntu 14.04) using Bspline method with LBFGSB optimizer. The time taken with the below default parameter was about 2-3 hour+. 
SetOptimizerAsLBFGSB(gradientConvergenceTolerance=1e-5,
                               numberOfIterations=500,
                               maximumNumberOfCorrections=5,
                               maximumNumberOfFunctionEvaluations=2000,
                               costFunctionConvergenceFactor=1e+7)

but when I changed the gradientConvergenceTolerance to 1e-3, it worked in 6-8 minutes. Is there anything wrong with my parameter configuration?

**Comment by zivy** [comment]
There is nothing wrong with the parameter settings it is just that the ones you used (the defaults) were not appropriate for your specific problem. The performance of most registration algorithms depends on multiple parameter settings. In this case when you made the gradient convergence tolerance looser (larger) the algorithm terminated significantly earlier. You will have to play with these parameters to find the ideal ones for your task (time/accuracy). 

In the future, please post questions concerning SimpleITK to the ITK [mailing list](https://itk.org/mailman/listinfo/community). We use github issues only for reporting bugs/issues and for feature requests.
