### ISSUE TITLE
Reading DICOM with slope > 1.0

### ISSUE THREAD

**Issue by ilyanelken** [SimpleITK/SimpleITK#1205]
Hi,

I encounter an issue when reading DICOM data with slope that is different than 1.0,
data intensities I get are not scaled as it should.

Sample code:
```
import SimpleITK as sitk

def read_dicom(directory):
    reader = sitk.ImageSeriesReader()
    dicom_names = reader.GetGDCMSeriesFileNames(directory)
    reader.SetFileNames(dicom_names)
    image = reader.Execute()
    return image

nii = sitk.ReadImage('/tmp/T1_ano.nii.gz')
dcm = read_dicom('/tmp/dicom_test/')
print(sitk.GetArrayViewFromImage(nii).max())
print(sitk.GetArrayViewFromImage(dcm).max())
```

Results:
```
3086.9744
420
```

@fepegar

Please advise.

Ilya

**Comment by gdevenyi** [comment]
These files can be commonly found in the proprietary bruker-to-DICOM converter in Paravision 5 and 6

**Comment by zivy** [comment]
Hello @ilyanelken,

Not sure what causes the issue with the data you have. A slope other than 1.0 should work, run [this example](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesFromArray_docs.html):
```
python DicomSeriesFromArray.py out_dir float64
```

Possibly provide a sample image?

**Comment by ilyanelken** [comment]
Hi @zivy , I have uploaded the data:
https://www.dropbox.com/s/08pmmj69q1fuva7/%40%40%404015009553921.zip?dl=0

I will check it out and update, thanks!

**Comment by zivy** [comment]
Hello @ilyanelken,

 "it's not me, it's you" 😉 

The data you provided includes three series, the volumetric ones don't have the rescale slope (0028|1053) and rescale intercept (0028|1052) tags. These were stripped, possibly by a buggy piece of software. 

They do have private tags that refer to "Rescale Intercept Original" (2005|1409) and "Rescale Slope Original" (2005|140a). For correct usage of the content of private tags you need to know what they actually mean, this is not something a general DICOM reading library can automatically do for you. It is something you need to do on top of the generic library. Again, these are private tags so you need to be sure that you can use their values as rescale slope and intercept instead of the standard tags.


Code illustrating the situation below:
```
import SimpleITK as sitk

data_directory = '4015009553921'

series_IDs = sitk.ImageSeriesReader.GetGDCMSeriesIDs(data_directory)
# read a specific series, probably replace with iteration over all
series_file_names = sitk.ImageSeriesReader.GetGDCMSeriesFileNames(data_directory, series_IDs[1])

series_reader = sitk.ImageSeriesReader()
series_reader.SetFileNames(series_file_names)

series_reader.MetaDataDictionaryArrayUpdateOn()
series_reader.LoadPrivateTagsOn()
image3D = series_reader.Execute()

# print the slope intercept for the official DICOM tags and the private values
for i in range(image3D.GetDepth()):
	print('Has rescale slope {0}'.format(series_reader.HasMetaDataKey(i, '0028|1053'))) #rescale slope
	print('Has private tag rescale slope {0}'.format(series_reader.GetMetaData(i, '2005|140a')))
	print('Has rescale intercept {0}'.format(series_reader.HasMetaDataKey(i, '0028|1052'))) #rescale intercept
	print('Has private tag rescale intercept {0}'.format(series_reader.GetMetaData(i, '2005|1409')))

```

Feeling lucky and confident about using the private tags:

```
import SimpleITK as sitk

data_directory = '4015009553921'

series_IDs = sitk.ImageSeriesReader.GetGDCMSeriesIDs(data_directory)
# read a specific series, probably replace with iteration over all
series_file_names = sitk.ImageSeriesReader.GetGDCMSeriesFileNames(data_directory, series_IDs[1])

series_reader = sitk.ImageSeriesReader()
series_reader.SetFileNames(series_file_names)

series_reader.MetaDataDictionaryArrayUpdateOn()
series_reader.LoadPrivateTagsOn()
image3D = series_reader.Execute()

if not (series_reader.HasMetaDataKey(0, '0028|1053') and series_reader.HasMetaDataKey(0, '0028|1052')):
    if series_reader.HasMetaDataKey(0, '2005|140a') and series_reader.HasMetaDataKey(0, '2005|1409'):
        image3D = sitk.Cast(image3D, sitk.sitkFloat32)
        image3D*= float(series_reader.GetMetaData(0, '2005|140a'))
        image3D+= float(series_reader.GetMetaData(0, '2005|1409'))
```

**Comment by ilyanelken** [comment]
@zivy I see. Thanks a lot for fast and efficient response. There might be an issue with anonymization software I am using. I will check it.
