### ISSUE TITLE
Segmentation Fault when importing SimpleITK 2.0 before TensorFlow

### ISSUE THREAD

**Issue by alkamid** [SimpleITK/SimpleITK#1208]
Likely related to #1192 

OS: Ubuntu 20.04
Python 3.8.2 (tested with 3.7, too)

Make a virtualenv:
```
python -m venv sitk_venv
source sitk_venv/bin/activate
pip install tensorflow==2.3.1 SimpleITK==2.0.0
```

`test.py`:
```
import SimpleITK as sitk
import tensorflow as tf
```

```
$ python test.py
Segmentation fault (core dumped)
```

If we reverse the order of imports (TensorFlow first), it works fine. I'm not sure whether it's an issue with TF or SimpleITK, but it doesn't happen with SimpleITK==1.2.4.

**Comment by blowekamp** [comment]
Thank you for reporting this issue. We will look into it.

**Comment by blowekamp** [comment]
SimpleITK wheels are compiled per [PEP 513 manylinux1](https://www.python.org/dev/peps/pep-0513/), while tensor flow is manylinux2010. I believe these should be interpretable with I will need further investigation.

**Comment by blowekamp** [comment]
Here is an related piece with PyArrow: https://uwekorn.com/2019/09/15/how-we-build-apache-arrows-manylinux-wheels.html

Specifically the section "Annoying end users issue #2: 'Segmentation fault after import TensorFlow"' appear to be relevant.

**Comment by ltetrel** [comment]
I had the same issue.
Changing the import order as @alkamid suggested worked for me.

**Comment by blowekamp** [comment]
This issue has been addressed in PR #1210 and has been merged into master. It is available in the ["latest"](https://github.com/SimpleITK/SimpleITK/releases/tag/latest) nightly packages. Please download and test the package to verify it resolves the issue. Then it can be merged into the release branch for 2.0.1.

**Comment by alkamid** [comment]
I can confirm that using (https://github.com/SimpleITK/SimpleITK/releases/download/latest/SimpleITK-2.1.0.dev23-cp38-cp38-manylinux1_x86_64.whl)[this wheel] (`2.1.0.dev23`) fixes the issue.

**Comment by blowekamp** [comment]
SimpleITK 2.0.1 have been uploaded to pypi, which addresses the import order issue with tensor flow.
