### ISSUE TITLE
Slice by Slice Adaptive Histogram Equalization

### ISSUE THREAD

**Issue by Boyden** [SimpleITK/SimpleITK#1211]
I am trying to using SimpleITK to normalize nii data using the **Slice by Slice Adaptive Histogram Equalization** example in the documentation. However, I encountered such a problem at this line.
```python
image[paste_idx] = func(extractor.Execute(image), *args, **kwargs)
```
And got the error
```python
File "\anaconda3\lib\site-packages\SimpleITK\SimpleITK.py", line 4692, in __setitem__
    raise IndexError("invalid index")
IndexError: invalid index
```
It seems that SimpleITK cant assign values or slices to indexed arrays. Could you update new codes and fix this bug?

**Comment by dave3d** [comment]
What version of SimpleITK are you using?  That example requires the latest version, 2.0.0.

**Comment by Boyden** [comment]
Thanks, It solves my problem after update SimpleITK version to 2.0.0
