### ISSUE TITLE
c_make fails during configuration phase

### ISSUE THREAD

**Issue by Jimmy2027** [SimpleITK/SimpleITK#1219]
Hello, I am trying to build simpleitk but c_make breaks during the configuration. 
My build log:  [build.log](https://github.com/SimpleITK/SimpleITK/files/5316577/build.log)
The c_make error log: [CMakeError.log](https://github.com/SimpleITK/SimpleITK/files/5316581/CMakeError.log)
The cmake output log: [CMakeOutput.log](https://github.com/SimpleITK/SimpleITK/files/5316585/CMakeOutput.log)

**Comment by blowekamp** [comment]
It looks like the wrong version of Lua is being used:
```
CMake Error at CMake/sitkGenerateFilterSource.cmake:52 (message):
  Lua version 5.3 is required for SimpleITK_LUA_EXECUTABLE_VERSION.
```

Please review the update prerequisites for SimpleITK 2.0: https://simpleitk.readthedocs.io/en/master/building.html#additional-prerequisites

**Comment by blowekamp** [comment]
I hope the reference documentation resolved your question. Please feel free to re-open if the problem persists or create a new issue for another questions.

**Comment by TheChymera** [comment]
@blowekamp is there maybe some way to make it work with `=lua-5.1.5-r4`? More recent versions are not working very well on our end.

**Comment by blowekamp** [comment]
Lua 5.1.5 was [released](https://www.lua.org/versions.html) on 17 Feb 2012 and is quite old and not supported. Support for Lua 5.1 has bee dropped. Can you use a Lua 5.3.x version?

Lua 5.4.0 was release in June 2020. We have not build SimpleITK with this new version. We'd much rather move forward.

**Comment by blowekamp** [comment]
For reference, I believe these were the two patches that enable Lua 5.3 and broke 5.1:

77a3d8943f3c9a4d5b5dcc1452827cb228b7aa2e
0dfae3e91dded3eeeb0501b0d00d35f09ed1fe0b

**Comment by TheChymera** [comment]
Given the fact that newer lua remains a non-starter for the time being, and that reverse-patching doesn't work on account of too many changes in the interim, we're currently trying to package the last pre-update version. Though there are some other issues with that, as well: https://github.com/SimpleITK/SimpleITK/issues/1242
