### ISSUE TITLE
'N4BiasFieldCorrectionImageFilter' object has no attribute 'GetLogBiasFieldAsImage'

### ISSUE THREAD

**Issue by dakjin** [SimpleITK/SimpleITK#1248]
I am running the N4 bias field correction using simpleITK's implementation.  In the example here (https://simpleitk.readthedocs.io/en/master/link_N4BiasFieldCorrection_docs.html), it has a line of "log_bias_field = corrector.GetLogBiasFieldAsImage(inputImage)".  However, when executing, the error appears "AttributeError: 'N4BiasFieldCorrectionImageFilter' object has no attribute 'GetLogBiasFieldAsImage' ".  Can someone let me know why the N4 filter does not have the attribute of 'GetLogBiasFieldAsImage'?

Thank you very much

**Comment by blowekamp** [comment]
Hello,

You are looking at the documentation for the master branch. This method was added since the 2.0 release. You are download the [latest](https://simpleitk.readthedocs.io/en/v2.0.0/gettingStarted.html#latest-binaries) development version. Or look ad the example from 2.0:
https://simpleitk.readthedocs.io/en/v2.0.0/link_N4BiasFieldCorrection_docs.html

**Comment by dakjin** [comment]
Thank you very much for your quick reply.  I used the simpleITK version 1.2.4 when reporting the errors.  As you suggested, I have updated to the 2.0.0.  However, I still got the error that "'N4BiasFieldCorrectionImageFilter' object has no attribute 'GetLogBiasFieldAsImage' ".   Did I mis-understand something?

**Comment by zivy** [comment]
Hello @dakjin 
What @blowekamp suggested was that you install the latest binary files which are pre-release (you installed the official 2.0.0 release):
```
pip install --upgrade --pre SimpleITK --find-links https://github.com/SimpleITK/SimpleITK/releases/tag/latest
```

**Comment by dakjin** [comment]
@zivy Thank you very much for the clarification. Using the lastest binary files, it works now.
