### ISSUE TITLE
Many functions seem to not exist any more

### ISSUE THREAD

**Issue by SamuelVilz** [SimpleITK/SimpleITK#1250]
Dear developers of SimpleITK,
it's been approximately one month since successfully running my Python code with SimpleITK for the last time.

Since then, I receive this error for different functions, including `ReadImage `and all `GetXFromY`-functions:
`AttributeError: module 'SimpleITK.SimpleITK' has no attribute 'GetArrayFromImage'`

**Environment:**
I'm using Python 3.7.6 within a Jupyter Notebook, version 6.0.3.

**SimpleITK-Version:**
Executing the following two lines prints out the ones below them:
`from SimpleITK import SimpleITK as sitk`
`print(sitk.Version())`
`> SimpleITK Version: 2.0.1 (ITK 5.1)`
`> Compiled: Oct 15 2020 13:45:29`
Fittingly, the date of compiling is a possible candidate for when my code stopped working.

**OS and installation:**
OS is "Ubuntu 18.04.4 LTS (Bionic Beaver)"
I have installed (and reinstalled now several times) SimpleITK using the following command: `pip install SimpleITK -U`
`conda install -c simpleitk simpleitk` ran successfully as well but didn't do it for me either.

Seeing as how I'm the only one opening an Issue, this is probably a really banal problem, so thank you just the more in advance for answering my plea!

**Comment by zivy** [comment]
Hello @SamuelVilz,

You have a very strange import line, I wonder what it really does:
```
from SimpleITK import SimpleITK as sitk
```

It should be:
```
 import SimpleITK as sitk
```

**Comment by SamuelVilz** [comment]
Dear Ziv,

thank you so much for answering as soon as you did. Your advice has solved the problem and left me puzzling what a) led me to do it the way I did and b) made that import line work until one month ago :D

**Comment by blowekamp** [comment]
SimpleITK 2.0 changed the layout of the Python package to a more standard structure. The documented and recommended way by @zivy has worked for 1.x and 2.0+.
