### ISSUE TITLE
Unable to run SimpleITK filters (version 2.0.1) on Google Colab

### ISSUE THREAD

**Issue by JoaoSantinha** [SimpleITK/SimpleITK#1252]
Hi!

I was trying to use SimpleITK on google colabs. I installed it using

```
!pip install SimpleITK
```
and the installed version is 2.0.1. I am able to read an image but the execution of filters cause the notebook to crash and restart. I was unable to get an error message from the logs but maybe you can point to a way on how to do this in order to provide you more information.

Here is a minimal code so you can try to reproduce it

```
!pip install SimpleITK
!wget --max-redirect=20 -O prostate_example.nii.gz https://www.dropbox.com/s/xypjy4x5do9qtw8/prostate_example.nii.gz
import SimpleITK as sitk
image = sitk.ReadImage('prostate_example.nii.gz')
image_F32 = sitk.Cast(image, sitk.sitkFloat32)
```

Interestingly, I tried to use version 2.0.0 (`!pip install SimpleITK==2.0.0`) and it runs without crashing and restarting the colab notebook.

**Comment by dave3d** [comment]
Thank you for reporting the problem.  I have tried your code and the crash on Google Colab happens for me too.

**Comment by zivy** [comment]
Hello @JoaoSantinha,

This seems to be an issue with the multithreading model from ITK. A stopgap solution is to use the PLATFORM threading model:
```
reader = sitk.ImageFileReader()
reader.SetGlobalDefaultThreader('PLATFORM')
reader.SetFileName('prostate_example.nii.gz')
image = reader.Execute()
image_F32 = sitk.Cast(image, sitk.sitkFloat32)
```

Let us know if this resolved your issue.

**Comment by JoaoSantinha** [comment]
Thanks @zivy and @dave3d!

@zivy yes, the stopgap solution you provided solves the issue I was encountering!

Thanks

**Comment by blowekamp** [comment]
The previous report of incompatibility was narrowed down to a couple specific C++ library symbols that were not compatible between the manylinux1 and manylinux2010 packaging standards: #1208

We have just added manylinux2010 wheels to the "latest" distribution. The initial failing usage in Google Colab now works with the latest installed:
```
pip install --upgrade --pre SimpleITK --find-links https://github.com/SimpleITK/SimpleITK/releases/tag/latest
```

Please test and verify, so that we can add this packaging for version 2.0.2.

**Comment by JoaoSantinha** [comment]
Hi @blowekamp,

Thank you very much! 

I have tested and verified that the solution you provided is working!

Shall I close the issue?

**Comment by blowekamp** [comment]
Thanks for reporting the success!

**Comment by Angeluz-07** [comment]
Hello, I had a similar issue but using Resample. example code:
```
img = sitk.ReadImage('example.nii.gz')
_img = sitk.Resample(img,img)
```
The google colab session kept restarting when running this line. Fortunately the solution of @blowekamp solved the issue.

**Comment by CS-Rorita** [comment]
Hello , 
I am using google colab to process my images

when I run SimpleITK filters  command  , an error apears

I installed  the package using this line: !pip install SimpleITK==1.1.0

Then ,I tried using these lines 
!sudo apt-get install \
    git \
    cmake \
    build-essential \

However, the download of the library continued for more than two hours, then the connection to Collab was disconnected, and this happens every time I run this command

Any help plz

Thanks in advans
![image](https://user-images.githubusercontent.com/67325575/154845951-438f9a05-ab47-4bd0-8907-987e10d42e24.png)

**Comment by zivy** [comment]
Hello @CS-Rorita,

You are running [SimpleElastix](https://github.com/SuperElastix/SimpleElastix). That package is based on SimpleITK and for some reason the authors did not change the package name. Please post this question on [their github issues](https://github.com/SuperElastix/SimpleElastix/issues).
