### ISSUE TITLE
Convert Transform parameter file to transform matrix

### ISSUE THREAD

**Issue by XXZhou25** [SimpleITK/SimpleITK#1253]
Hi, 

I was trying to convert a euler 3D transform parameter file to a transform matrix to manually compute deformation field, by SimpleITK Euler3DTransform. I also used elastix command line to generate a deformation field. However, my manually computed results were always a little bit different from elastix generated. 
I was wondering if you would know the possible reasons? 
I thought for Euler transform, it only transforms the coordinates by the transform matrix, and no interpolation or other operations is needed, do I understand correctly? 

My code and result:

image_origin = np.array([0, -239, 0])
theta_x = -0.094891
theta_y = 0.006870
theta_z = 0.031377
translation = np.array([-9.053901, -23.358420, -8.338770])
rotation_center = np.array([119.5, -119.5, 77])
rigid_euler = sitk.Euler3DTransform(rotation_center, theta_x, theta_y, theta_z, translation)
A1 = np.asarray(rigid_euler.GetMatrix()).reshape(3,3)
c1 = np.asarray(rigid_euler.GetCenter())
t1 = np.asarray(rigid_euler.GetTranslation())

p = np.array([100, 200, 200])
truec = rotation_center - image_origin 
p_transform = np.dot(A1, p - truec) + t1 + truec
p_displacement = p_transform - p

result: 
p_displacement = array([-11.0793279 , -12.68448335, -16.38891453])
p_displacement_byelastix = DVF[100, 200, 200] = array([-11.518286, -19.103964, -16.620592], dtype=float32)

their difference is: array([-0.43895785, -6.4194805 , -0.23167759])

The transform file: 
(Transform "EulerTransform")
(NumberOfParameters 6)
(TransformParameters -0.094891 0.006870 0.031377 -9.053901 -23.358420 -8.338770)
(InitialTransformParametersFileName "NoInitialTransform")
(UseBinaryFormatForTransformationParameters "false")
(HowToCombineTransforms "Compose")

// Image specific
(FixedImageDimension 3)
(MovingImageDimension 3)
(FixedInternalImagePixelType "float")
(MovingInternalImagePixelType "float")
(Size 240 240 155)
(Index 0 0 0)
(Spacing 1.0000000000 1.0000000000 1.0000000000)
(Origin 0.0000000000 -239.0000000000 0.0000000000)
(Direction 1.0000000000 0.0000000000 0.0000000000 0.0000000000 1.0000000000 0.0000000000 0.0000000000 0.0000000000 1.0000000000)
(UseDirectionCosines "true")

// EulerTransform specific
(CenterOfRotationPoint 119.5000000000 -119.5000000000 77.0000000000)
(ComputeZYX "false")

// ResampleInterpolator specific
(ResampleInterpolator "FinalBSplineInterpolator")
(FinalBSplineInterpolationOrder 3)

// Resampler specific
(Resampler "DefaultResampler")
(DefaultPixelValue 0.000000)
(ResultImageFormat "nii.gz")
(ResultImagePixelType "short")
(CompressResultImage "false")

I will appreciate any of your ideas! 
Thank you so much!

**Comment by zivy** [comment]
Hello @XXZhou25,

I'm not too surprised by the results being significantly different when you have two registrations, one using Rigid and the other a deformation field. You need to know which transformation model is appropriate for your problem. If rigid then use rigid with both tools, if deformable then use deformable with both tools.

Also, even when you have a known rigid transformation and you convert it to a deformation field representation, you are introducing inaccuracies. The deformation field is a discrete representation of the transformation in a local bounded domain. The rigid transformation is a global and continuous function. As a result they will not map points to the same location. The less dense the deformation field the larger the difference (points inside the domain but not on the grid are mapped using interpolation).

Possibly use elastix to generate the corresponding rigid transformation and then you can compare that to the one obtained using SimpleITK.

**Comment by XXZhou25** [comment]
> Hello @XXZhou25,
> 
> I'm not too surprised by the results being significantly different when you have two registrations, one using Rigid and the other a deformation field. You need to know which transformation model is appropriate for your problem. If rigid then use rigid with both tools, if deformable then use deformable with both tools.
> 
> Also, even when you have a known rigid transformation and you convert it to a deformation field representation, you are introducing inaccuracies. The deformation field is a discrete representation of the transformation in a local bounded domain. The rigid transformation is a global and continuous function. As a result they will not map points to the same location. The less dense the deformation field the larger the difference (points inside the domain but not on the grid are mapped using interpolation).
> 
> Possibly use elastix to generate the corresponding rigid transformation and then you can compare that to the one obtained using SimpleITK.

Hi @zivy , thanks for your quick reply! That reminds me thinking deeper!
Sorry I am still a little bit confused about one thing that: 
if we know the rigid transformation, then I only want to use elastix to generate a deformation field, I thought it will traverse every location and multiply with rigid transformation matrix in order to obtain the displacement, may I know in this case, why is interpolation needed? 
I understand that if I am using control points only to register 2 images, then for points other than control points, interpolation is needed for their displacements. And if I want to convert an image with deformation field, interpolation is also needed to obtain some voxel's intensity, but deformation field is fixed and we are not interpolating it. Do I understand correctly? 

Please kindly correct me if there is any misunderstanding!
Thank you so much!

**Comment by zivy** [comment]
Hello @XXZhou25,

Not 100% sure I understood you, are you performing rigid registration and that is followed by a deformable one? Or do you just want to compare two representations of the same transformation? 

One thing to note about deformable transformations (other than affine) is that they have a local bounded domain. If your point is outside this domain it is often mapped using the identity transformation (at least that is what ITK/SimpleITK does).  This will be significantly different than mapping that same point using a transformation with global domain.

**Comment by XXZhou25** [comment]
> Hello @XXZhou25,
> 
> Not 100% sure I understood you, are you performing rigid registration and that is followed by a deformable one? Or do you just want to compare two representations of the same transformation?
> 
> One thing to note about deformable transformations (other than affine) is that they have a local bounded domain. If your point is outside this domain it is often mapped using the identity transformation (at least that is what ITK/SimpleITK does). This will be significantly different than mapping that same point using a transformation with global domain.

Hi @zivy , thanks for explaining so detailed! 
Sorry I didn't explain clearly. My motivation for what I am doing right now is actually figuring out: after rigid registration, a parameter file is generated with 6 parameters, how does Elastix generate the deformation field with them? That's why I am comparing my manually computed result with Elastix generated result. 

I don't quite understand how Elastix generates the deformation field with 6 parameters. I thought it should first produce transformation matrix, then traverse every location on the image, and multiply by transformation matrix to compute displacement. I don't quite understand why for rigid transformation, in this process, interpolation is needed. 

I am sorry I still don't quite understand this process..But your words are very instructive and I will think about it more!

**Comment by XXZhou25** [comment]
Hi, with @zivy 's help, I rethink my problem deeper. 
To make things more brief and clear, my current question is: with the 6 rigid transformation parameters fixed, why is the Elastix generated deformation field different from my manually computed displacements? I thought the procedure should be the same? 
1. convert 6 parameters to a 4*4 rigid transformation matrix (included 3*3 rotation + 3*1 translation)
2. traverse every voxel's coordinates, multiply by transformation matrix. 
3. then obtain displacement. 

I don't understand what the possible reason is resulting their slight differences? If interpolation method is used for generating Rigid deformation field, why is it needed? 

I will appreciate if anyone could help me understand how elastix generates deformation field or why it is different from my manually computing. 
Thank you so much!

**Comment by zivy** [comment]
Hi @XXZhou25,

OK, so this seems to be an elastix specific question. They have a [google forum](https://groups.google.com/g/elastix-imageregistration?pli=1) which is the right venue for this question (it isn't specific to simpleitk).

**Comment by XXZhou25** [comment]
> Hi @XXZhou25,
> 
> OK, so this seems to be an elastix specific question. They have a [google forum](https://groups.google.com/g/elastix-imageregistration?pli=1) which is the right venue for this question (it isn't specific to simpleitk).

Hi @zivy ,Thank you so much! I will post the question there. I hope I understand the process of generating deformation field with rigid transformation matrix correctly. May I ask one last question that:While generating deformation field for rigid registration, theoretically it should be also a matrix multiply operation for each point location? No more like interpolation should be needed?

**Comment by zivy** [comment]
Hello @XXZhou25,

Your understanding of how a deformation field is created from a rigid transformation is correct. It does not involve interpolation. The usage of the deformation field to transform a point does involve interpolation, which is not the case when using the original rigid transformation.

**Comment by XXZhou25** [comment]
> Hello @XXZhou25,
> 
> Your understanding of how a deformation field is created from a rigid transformation is correct. It does not involve interpolation. The usage of the deformation field to transform a point does involve interpolation, which is not the case when using the original rigid transformation.

Hi @zivy , Thanks for all of your very detailed explanations! I've learnt a lot from your words. Yes interpolation is needed when map points to obtain the intensity. I will try to see if Elastix forum could solve my question. Thanks for being so nice to share again!
