### ISSUE TITLE
How to apply registration transform on a point?

### ISSUE THREAD

**Issue by NeuZhangQiang** [SimpleITK/SimpleITK#1256]
I am using SimpleITK for image registration. Then, I want to apply the registration transform on a point. The registration code is:
```
R = sitk.ImageRegistrationMethod()
R.SetMetricAsMeanSquares()
R.SetOptimizerAsRegularStepGradientDescent(
    learningRate=2.0,
    minStep=1e-4,
    numberOfIterations=500,
    gradientMagnitudeTolerance=1e-8
)
R.SetOptimizerScalesFromIndexShift()
tx = sitk.CenteredTransformInitializer(fixed, moving, sitk.Similarity3DTransform())
R.SetInitialTransform(tx)
# R.SetInitialTransform(sitk.AffineTransform(fixed.GetDimension()))
R.SetInterpolator(sitk.sitkLinear)
outTx = R.Execute(fixed, moving)
```

Now, I want to apply the registration transform on a point. I don't know the method. Any suggestion is appreciated!

**Comment by zivy** [comment]
```
outTx.TransformPoint(pnt)
```
Note that `pnt` needs to be in physical space and not indexes in voxel space.
I highly recommend taking the [introduction to SimpleITK on-line tutorial](https://simpleitk.org/TUTORIAL/).

**Comment by NeuZhangQiang** [comment]
@zivy Thank you for your kindly reply. 

Let's say, I have fixed and moving image, and a point. The data is upload in [github](https://github.com/zhang-qiang-github/registrationDemo/blob/master/img.npz).

```
import numpy as np
from vedo import *  # pip install vedo
data = np.load('img.npz')
img1 = data['img1']
center = [39, 105, 109]
img2 = data['img2']

vol1 = Volume(img2).isosurface(1).c('r').alpha(0.5)
show(vol1, at=0, N=2)
point = Point(pos=[center[2], center[1], center[0]])
vol2 = Volume(img1).isosurface(1).c('b').alpha(0.2)
show(vol2, point, at=1, interactive=True)
```
![image](https://user-images.githubusercontent.com/62534955/98883527-4cc5f400-24c9-11eb-886e-045917f67ce7.png)


The red color indicates ```img2```, the blue color indicates ```img1```, and the red point is the center of ```img2```. Now, I want to set ```img2``` as the fixed image, ```img1``` as the moving image. Finally, I want to map the center point of ```img2``` (the red point) to the center point of ```img2```. 

The registration code is:

```
import numpy as np
from vedo import *  # pip install vedo
data = np.load('img.npz')
img1 = data['img1']
center = [39, 105, 109]
img2 = data['img2']

import SimpleITK as sitk
fixed = sitk.GetImageFromArray(img2.astype(np.float))
moving = sitk.GetImageFromArray(img1.astype(np.float))
R = sitk.ImageRegistrationMethod()
R.SetMetricAsMeanSquares()
R.SetOptimizerAsRegularStepGradientDescent(
    learningRate=2.0,
    minStep=1e-4,
    numberOfIterations=500,
    gradientMagnitudeTolerance=1e-8
)
R.SetOptimizerScalesFromIndexShift()
tx = sitk.CenteredTransformInitializer(fixed, moving, sitk.Similarity3DTransform())
R.SetInitialTransform(tx)
# R.SetInitialTransform(sitk.AffineTransform(fixed.GetDimension()))
R.SetInterpolator(sitk.sitkLinear)
outTx = R.Execute(fixed, moving)

resampler = sitk.ResampleImageFilter()
resampler.SetReferenceImage(fixed)
resampler.SetInterpolator(sitk.sitkLinear)
resampler.SetDefaultPixelValue(0)
resampler.SetTransform(outTx)
out = resampler.Execute(moving)
wrapImg = sitk.GetArrayFromImage(out)

p = outTx.TransformPoint([center[0], center[1], center[2]])
p1 = Point(pos=[p[2], p[1], p[0]])

vol1 = Volume(img2).isosurface(1).c('r').alpha(0.5)
show(vol1, at=0, N=2)
vol2 = Volume(wrapImg).isosurface(1).c('b').alpha(0.5)
show(vol2, p1, at=1, interactive=True)
```
![image](https://user-images.githubusercontent.com/62534955/98883795-bcd47a00-24c9-11eb-80fb-15754752b2a2.png)

The right figure show the transform image and point, but the center point is outside of ```wrapImg```. I think the result is wrong. How can I fix this problem?

**Comment by zivy** [comment]
Hello @NeuZhangQiang,

Two things that can go wrong that are due to differences between SimpleITK and numpy:
1. A point in numpy is specified in z-y-x order vs. x-y-z order in SimpleITK.
2. A point in SimpleITK is different from an index, you need to use an image's [TransformIndexToPhysicalPoint](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1Image.html#a87c1a1ecaa5bd379d3132c7e95619aaa) to get the physical coordinates and then transform those. On the other side you get from a physical point to an index using the second image's [TransformPhysicalPointToIndex](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1Image.html#a9474e4ded374c8350418fe5329187704) method.

**Comment by NeuZhangQiang** [comment]
Dear @zivy ,

1. Actually, I have tried both ```p = outTx.TransformPoint([center[0], center[1], center[2]])``` and ```p = outTx.TransformPoint([center[2], center[1], center[0]])```. And the results are wrong. 

2. A point in the world coordinate is different from the index. However, in the above code, the origin and spacing is default to [0,0,0], [1,1,1]. In this way, the world coordinate should be the same with the matrix coordinate. The ```moving.TransformIndexToPhysicalPoint([center[2], center[1], center[0]])``` would result the same coordinate with ```center```. 

Is there any thing else may cause this bug?

Qiang

**Comment by zivy** [comment]
Hello Qiang,

The only other thing is the direction of the mapping. `outTx` maps points from the fixed image, `img2` in the code, to the moving image, `img1`. 

If you just want to map a single point, then that point is given inn the fixed coordinate system and mapped to the moving coordinate system.

If you do a resampling of the moving image onto the fixed image grid then the point doesn't need to be transformed as it is already in the fixed image coordinate system.

**Comment by NeuZhangQiang** [comment]
The point is a key point of moving image. Since the moving image is warped, I think the point should also be warped.

**Comment by zivy** [comment]
Hello @NeuZhangQiang,

Not sure what you mean by "The point is a key point of moving image.". If the point is in the moving image coordinate system and you want to map it to the fixed image, you need to use the inverse transformation from the registration result (`outTx.GetInverse()`) to map the point.

**Comment by gdevenyi** [comment]
> A point in numpy is specified in z-y-x order vs. x-y-z order in SimpleITK.

Its also likely your numpy point is in RAS space, while SimpleITK will be in LPS space
