### ISSUE TITLE
Contribute with notebook on BSplineTransform

### ISSUE THREAD

**Issue by fepegar** [SimpleITK/SimpleITK#1258]
Hi all,

@jhlegarreta has suggested contributing a notebook on the `BSplineTransform`, after seeing the [gist](https://gist.github.com/fepegar/b723d15de620cd2a3a4dbd71e491b59d) that I shared in a [comment on the ITK forum](https://discourse.itk.org/t/parameters-in-bsplinetransform/3395/4). I created the gist for myself, to understand the transform and use it in [TorchIO's `RandomElasticDeformation`](https://torchio.readthedocs.io/transforms/augmentation.html#randomelasticdeformation), but I'd be happy if it could be refactored into a more educational format.

As I won't be able to dedicate much of my time for this before February 2021, I think @jhlegarreta will try to work on this if you consider this contribution is helpful. Please let us know what you think.

**Comment by jhlegarreta** [comment]
:+1: to give this a first go and to help with this. Maybe @zivy and @blowekamp you can let us know how you see things, and based on that we can start elaborating a notebook to have Fernando's awesome work here.

Note: I think the issue should rather be in the [SimpleITK-Notebooks](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) repository, though :upside_down_face: .

**Comment by fepegar** [comment]
> Note: I think the issue should rather be in the SimpleITK-Notebooks repository, though.

Oops, my bad!

**Comment by zivy** [comment]
Closing this, lets continue on the notebook repo, [opened here](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/issues/287).
