### ISSUE TITLE
Missing Parts of an Image in Registration

### ISSUE THREAD

**Issue by Jennsoo** [SimpleITK/SimpleITK#1259]
Hi, I'm using AffineTransform method for 3D MRI image registration. 
In most cases, it works well. But in some cases, a corner of the first or last few slices seems to be cut off.
In fact, not just the AffineTransform, I also encountered this problem when using other transform methods. I have no idea in which cases this will happen. Could you please give me some guidance to solve this problem?

This is my code:
```
fixed_image = sitk.ReadImage('t1c.nii.gz', sitk.sitkFloat32)
moving_image = sitk.ReadImage('t2.nii.gz', sitk.sitkFloat32)
initial_transform = sitk.CenteredTransformInitializer(fixed_image,
                                                      moving_image,
                                                      sitk.AffineTransform(3),
                                                      sitk.CenteredTransformInitializerFilter.GEOMETRY)
registration_method = sitk.ImageRegistrationMethod()
registration_method.SetMetricAsMattesMutualInformation(numberOfHistogramBins=50)
registration_method.SetMetricSamplingStrategy(registration_method.RANDOM)
registration_method.SetMetricSamplingPercentage(0.05)
registration_method.SetInterpolator(sitk.sitkLinear)
registration_method.SetOptimizerAsGradientDescent(learningRate=1.0, numberOfIterations=300, convergenceMinimumValue=1e-6, convergenceWindowSize=10)
registration_method.SetOptimizerScalesFromPhysicalShift()
registration_method.SetInitialTransform(initial_transform, inPlace=False)
final_transform = registration_method.Execute(fixed_image, moving_image)

print('Optimizer\'s stopping condition, {0}'.format(registration_method.GetOptimizerStopConditionDescription()))

# Sample and save after registration.
moving_resampled = sitk.Resample(moving_image, fixed_image, final_transform, sitk.sitkLinear, 0.0, moving_image.GetPixelID())
sitk.WriteImage(moving_resampled, 'reg_t2.nii.gz')
```
An incomplete registration slice.
![10321217_0020](https://user-images.githubusercontent.com/25947811/99361626-59918000-28ed-11eb-8712-9757a6b2924c.png)

**Comment by zivy** [comment]
Hello @Jennsoo,

This is not a registration problem, I expect the registration is correct (quantitatively evaluate it by mapping corresponding points between fixed and moving image, as done in [this function](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/c6a2c0236d5fe1ce180f3af2a114c90954c753de/Python/registration_utilities.py#L125)). What you are seeing is a feature of resampling onto the fixed image grid, the re-slicing of the original moving image. 

To convince yourself that the resampled image is still valid/complete, you can visualize it using [Slicer](https://www.slicer.org/), volume render it. You should see that the whole scan is there. If you are working in a Jupyter notebook an even easier path is to visualize the volume using [itkwidgets](https://github.com/InsightSoftwareConsortium/itkwidgets).

**Comment by Jennsoo** [comment]
Thank you for recommending itkwidgets to me. It is very useful. 

I checked the resampled image and found that it is incomplete. I wounder why this happens, because both my fixed image and original moving image are complete.

I am new to registration, so maybe I have done something wrong in the process. Let me explain my operation in more detail. If there is a mistake, please point it out.

What am I doing is registering t2 .pngs to t1c .pngs (but I also have the original .dcms). In some of my cases, t2 and t1c have **different resolutions** (but the same thickness). For example, t2 with 512x512 and t1c with 240x320. So when making .nii file for t2, I first **resized** (the method in cv2) all the .pngs to match the t1c resolution. And then, I use the registration method in Simpleitk to register the t2.nii to t1c.nii. 

Is there something incorrect in my operation?

I upload an example to let you better understand my task. But sorry for not being able to provide the original .dcms due to privacy issues.
[0001.zip](https://github.com/SimpleITK/SimpleITK/files/5557569/0001.zip)

**Comment by zivy** [comment]
Hello @Jennsoo,

The workflow you are using is problematic. You move from DICOM data which contains 3D information to png which doesn't. You should work directly with your DICOM data. Do not "resize" anything as SimpleITK is aware of the physical sizes of the images from the DICOM information.

Please read the images using the relevant SimpleITK class, [ImageSeriesReader](https://simpleitk.org/doxygen/v2_0/html/classitk_1_1simple_1_1ImageSeriesReader.html), and the relevant functions `GetGDCMSeriesIDs`, and `GetGDCMSeriesFileNames`. 

This may not address the current issue but is the correct workflow. Another possible problem is that the fixed image extent is too small and when the head is aligned correctly it is partially outside the fixed image box. This can be remedied by specifying a larger resampling grid (see notebook on resampling).

I highly recommend going over the [SimpleITK tutorial](https://simpleitk.org/TUTORIAL/), and skimming both the [Jupyter notebook repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) and [Examples](https://simpleitk.readthedocs.io/en/master/link_examples.html).

**Comment by Jennsoo** [comment]
Thank you for pointing out the problem in my workflow. 

It seems that my previous workflow is the main cause of this issue (not sure). When operating directly on the DICOM files, the problem disappeared.

**Comment by Jennsoo** [comment]
Sorry to reopen this issue. After checking all my cases, I found the issue still occurred 'randomly'.

I ran the official [60. Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/60_Registration_Introduction.ipynb) (did not make any changes to the code) and got a similar result.
![image](https://user-images.githubusercontent.com/25947811/101475313-35264200-3987-11eb-8eac-6efc77e2d28a.png)
