### ISSUE TITLE
Failed to allocate memory for image.

### ISSUE THREAD

**Issue by dzerkes** [SimpleITK/SimpleITK#1263]
I have saved as .nrrd files some ct scan series and their masks as 3d inputs. For example (x,y,z) where z shows the instance number and (x,y) is the image.

Just to mention I had converted the dicom images into numpy and then to .nrrd and same for masks that were .png files.

So when I'm trying to read these .nrrd files using the command sitk.ReadImage(filepath) I get the following error  " RuntimeError: Exception thrown in SimpleITK Cast: /tmp/SimpleITK-build/ITK-prefix/include/ITK-5.1/itkImportImageContainer.hxx:192: Failed to allocate memory for image." 

My goal is to extract some 3d features from 3d scans using pyRadiomics but I'm getting an error here. Can I do anything for that to fix except for getting more RAM?

**Comment by zivy** [comment]
Hello @dzerkes,

Unless your machine has very little RAM (2GB) or you created a single input image from all of your volumes this shouldn't be a problem.

Is there a reason your workflow is DICOM->numpy->nrrd. SimpleITK can read the DICOM directly. Also, storing the masks as png files means they have lost the 3D information associating them with the original DICOM. You are relying on a slice by slice matching between the pngs and DICOMs using possibly some file naming convention. This is error prone. It is better to store the masks as a 3D volume (nrrd/mha...).

If you can share your data and code we could help pinpoint your problem. Right now we can only provide the general advice given above.

**Comment by dzerkes** [comment]
> Hello @dzerkes,
> 
> Unless your machine has very little RAM (2GB) or you created a single input image from all of your volumes this shouldn't be a problem.
> 
> Is there a reason your workflow is DICOM->numpy->nrrd. SimpleITK can read the DICOM directly. Also, storing the masks as png files means they have lost the 3D information associating them with the original DICOM. You are relying on a slice by slice matching between the pngs and DICOMs using possibly some file naming convention. This is error prone. It is better to store the masks as a 3D volume (nrrd/mha...).
> 
> If you can share your data and code we could help pinpoint your problem. Right now we can only provide the general advice given above.

Unfortunately I cannot provide the data since they contain medical information. I will try to give a description of my data and code. I have a directory lets call it "/main_path" where inside it I have folders of Patients. So "/main_path/[patients_name_folder]". Each patient's folder has inside 2 other folders named "ct" and "mask". The "ct" folder has inside a series of dicom images while the "mask" folder has inside a series of .png images which indicates lung-segmentation.

So we can find our data like that "/main_path/patient_name/ct" for ct dicom series and "/main_path/patient_name/mask" for the masks.

To match every dicom image with the correct mask I do the following. Mask filenames are already sorted by filename 001,002, etc... while for the dicom images I need to read the image using pydicom and extract the instance_number so that I can do the sorting.

That's why I read the dicom and .png images as numpy arrays, do the sorting and concatenate them to two 3d numpy arrays, with the 3rd axis showing the instance number. After that I want to extract some features using pyRadiomics. That's why I write them as .nrrd files and then read them with SimpleITK module. Also I tried using sitk.GetImageFromArray(). Sometimes I don't have memory error when I read them using SITK but I get it when using pyRadiomics feature extractor. So I was wondering if there is any better solution path than what I did.

P.S.: I have 4gb RAM

Code:

`patients =['01D610FD','A12BCCAF','0491B406','765B210D','F5EF8BA1'] 

main_path = 'images_masks/'
ct_paths = [main_path + k +'/ct' for k in patients]
mask_paths = [main_path + k +'/masks' for k in patients]

ct_mask = zip(ct_paths,mask_paths)

if not os.path.exists('nrrd_files'):
    os.makedirs('nrrd_files')

for i in ct_mask: 
    
    ct_scan_dict = {}
    
    ct_scans_paths = os.listdir(i[0]) 
    ct_masks_paths = sorted(os.listdir(i[1])) 
    ### GET IMAGE AND MASK AS - 3D SERIES ###
    
    for k in ct_scans_paths: 
        ct_img = dcmread(i[0] +'/' + k)
        ct_scan_dict[int(ct_img[0x0020,0x0013].value)] = ct_img.pixel_array[:,:,newaxis]
    
    flag = 0
    for k in ct_masks_paths:
        if flag == 0:
            ct_masks = imageio.imread(i[1] +'/' + k)[:,:,newaxis]
            flag = 1
        else:
            ct_masks = np.concatenate((ct_masks, imageio.imread(i[1] +'/' + k)[:,:,newaxis]),2 )
        
    ct_scan_dict = OrderedDict(sorted(ct_scan_dict.items(), key=lambda t: t[0]))
    ct_scan_3d = np.concatenate([ct_scan_dict[x] for x in ct_scan_dict],2) # got the 3d series
    
    #### make numpies to .nrrd ####
    if not os.path.exists('nrrd_files/' + i[0].split('/')[1]):
        os.makedirs('nrrd_files/'+i[0].split('/')[1])

    #nrrd.write( 'nrrd_files/' + i[0].split('/')[1] +  '/ct.nrrd' , ct_scan_3d)
    #nrrd.write( 'nrrd_files/' + i[0].split('/')[1] + '/mask.nrrd', ct_masks)

    break # if you want to run only for one patient.`

I can use either  sitk.ReadImage after I write as .nrrd the 3d images or immediately convert the 3d numpy arrays to sitk using itk.GetImageFromArray.

Then I finally want to extract features with the following code.

`extractor = featureextractor.RadiomicsFeatureExtractor(**settings)
 featureVector = extractor.execute(inputImage, inputMask ,label=1000)
`

**Comment by zivy** [comment]
Hello @dzerkes,

4GB is a bit small, but I think you can still get it to work. Your workflow is overly complex for what you want to do. Below find a simplified flow which only relies on SimpleITK, no pydicom or numpy:

```
patients =['01D610FD','A12BCCAF','0491B406','765B210D','F5EF8BA1'] 
main_path = 'images_masks/'
ct_paths = [main_path + k +'/ct' for k in patients]
mask_paths = [main_path + k +'/masks' for k in patients]
ct_mask = zip(ct_paths,mask_paths)

extractor = featureextractor.RadiomicsFeatureExtractor(**settings)

for ct_dir, mask_dir in ct_mask:
    #assuming a single CT in the directory, otherwise this reads the first series
    ct_image = sitk.ReadImage(sitk.ImageSeriesReader_GetGDCMSeriesFileNames(ct_dir))
    mask = sitk.ReadImage(sorted(os.listdir(mask_dir)))
    #ensure that the mask is spatially in the same location as the ct_image
    mask.CopyInformation(ct_image)
    featureVector = extractor.execute(ct_image, mask ,label=1000)
    #write the feature vector to disk or accumulate the feature vectors in a list or do something else
```

**Comment by dzerkes** [comment]
> Hello @dzerkes,
> 
> 4GB is a bit small, but I think you can still get it to work. Your workflow is overly complex for what you want to do. Below find a simplified flow which only relies on SimpleITK, no pydicom or numpy:
> 
> ```
> patients =['01D610FD','A12BCCAF','0491B406','765B210D','F5EF8BA1'] 
> main_path = 'images_masks/'
> ct_paths = [main_path + k +'/ct' for k in patients]
> mask_paths = [main_path + k +'/masks' for k in patients]
> ct_mask = zip(ct_paths,mask_paths)
> 
> extractor = featureextractor.RadiomicsFeatureExtractor(**settings)
> 
> for ct_dir, mask_dir in ct_mask:
>     #assuming a single CT in the directory, otherwise this reads the first series
>     ct_image = sitk.ReadImage(sitk.ImageSeriesReader_GetGDCMSeriesFileNames(ct_dir))
>     mask = sitk.ReadImage(sorted(os.listdir(mask_dir)))
>     #ensure that the mask is spatially in the same location as the ct_image
>     mask.CopyInformation(ct_image)
>     featureVector = extractor.execute(ct_image, mask ,label=1000)
>     #write the feature vector to disk or accumulate the feature vectors in a list or do something else
> ```


I changed sorted(os.listdir(mask_dir))  to [mask_dir + '/' + mask_name for mask_name in sorted(os.listdir(mask_dir))] so that It doesnt have an error.

It worked on my computer and it worked pretty fast actually.

Thanks a lot for helping out!
