### ISSUE TITLE
Not able to pass image files directly as argument to sitk.ReadImage() function in Python

### ISSUE THREAD

**Issue by rvadhith** [SimpleITK/SimpleITK#1267]
I am trying to use simpleITK.ReadImage function to read an image file in Python. When I store the image file in a variable and pass it as an argument to simpleITK.ReadImage function, I was getting the following error

TypeError: in method 'ImageSeriesReader_SetFileNames', argument 2 of type 'std::vector< std::string,std::allocator< std::string > > const &'

However if I fetch the file from directory and pass it as an argument, it works fine. How can I use the variable which holds the image file as an argument for simpleITK.ReadImage function

**Comment by zivy** [comment]
Hello @rvadhith,

Please provide the couple of lines of source code so that we can address your issue. The `ReadImage` method expects a string which is the path to the file or a list of file paths if loading a volume comprised of multiple slices:
```
file_name = 'tmp/image.mha'
sitk.ReadImage(file_name) 
```

**Comment by GopinathBalaji** [comment]
Hey @zivy,
I am facing the same problem. I'm not able to load images using the file path. My command was:

dataDir = '\BrainTumorData\Training\glioma_tumor'
imageName = str(dataDir + os.path.sep + 'gg (1).jpg')
image = sitk.ReadImage(imageName)

The error was:
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: C:\Miniconda\envs\bld\conda-bld\work\Code\IO\src\sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "\BrainTumorData\Training\glioma_tumor\gg (1).jpg" does not exist.

**Comment by zivy** [comment]
Hello @GopinathBalaji,

The path you are providing does not make sense. You appear to be working on a Windows machine, so the `dataDir` string is either missing the drive name `dataDir='C:\BrainTumorData\Training\glioma_tumor'` or if it is a relative directory then it should not have the backslash `dataDir='BrainTumorData\Training\glioma_tumor'`.
