### ISSUE TITLE
ImageSeriesReader to read DICOM series in correct order

### ISSUE THREAD

**Issue by Ingrid1989** [SimpleITK/SimpleITK#1270]
For a project I am currently working on I need to read a lot of dicom series. All series are stored in a seperate folder, so there is no problem there. and the reader does what it has to do. But I have one question: In which order will the slices appear in the array? Is it just randomly reading all the slices or does it place the slices in the order of the correct DICOM position?

**Comment by zivy** [comment]
Hello @Ingrid1989,

You need to use the [GetGDCMSeriesFileNames](https://simpleitk.org/doxygen/v2_0/html/classitk_1_1simple_1_1ImageSeriesReader.html#a148badf23595d59e34b1d9360c79b539) to obtain the file names in the correct order for the reader. Also if you have multiple series in each directory you need to select one, or go over all of them. The default behavior, if you do not specify a series ID, is to get the file names for the first series encountered in the directory. Please take a look at the [DicomSeriesReader](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReader_docs.html) and [DicomSeriesReadModifyWrite](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReadModifyWrite_docs.html) examples. 

For future reference, the toolkit's usage examples can be found on [read-the-docs](https://simpleitk.readthedocs.io/en/master/link_examples.html#) and in our [Jupyter notebook repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks).
