### ISSUE TITLE
Attribute not found in Transform class

### ISSUE THREAD

**Issue by makquel** [SimpleITK/SimpleITK#1271]
The following snipped was presented in the last MICCAI SimpleITK tutorial regarding data augmentation strategies.

 ```python
centering_transform = sitk.TranslationTransform(dimension)
img_center = np.array(img.TransformContinuousIndexToPhysicalPoint(np.array(img.GetSize())/2.0))
centering_transform.SetOffset(np.array(transform.GetInverse().TransformPoint(img_center) - reference_center))
centered_transform = sitk.Transform(transform)
centered_transform.AddTransform(centering_transform)
```
However, seems that the [Transform](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1Transform.html) object doesn't have the AddTransform method as shown, Is there any alternative class that I could use instead?

**Comment by blowekamp** [comment]
Hello,

Since that tutorial SimpleITK 2.0 has been released and the interface to composite transforms has changed. Please see the following in the 2.0 Migration Guide:
https://simpleitk.readthedocs.io/en/master/migrationGuide2.0.html#composite-transforms

**Comment by zivy** [comment]
Hello @makquel ,

Possibly you are looking at an older version of the tutorial? The [MICCAI 2020 tutorial](https://github.com/SimpleITK/TUTORIAL/) uses the new interface. Please update your code base.

**Comment by makquel** [comment]
Hello, 
@blowekamp thanks for the update, I'm gonna try it out with the migration guide.
@zivy I've just double checked, and it seems that the tutorial presented in 2020 still has the version 1.x, take a look to this [notebook](https://github.com/SimpleITK/TUTORIAL/blob/master/04_data_augmentation.ipynb) for instance.

Thanks

**Comment by zivy** [comment]
Hello @makquel 

Really not sure what is going on. When I follow the link you provided there is no line `centered_transform = sitk.Transform(transform)`. Are you sure you are looking at the correct location?

**Comment by makquel** [comment]
Hello @zivy 
My mistake, I was looking for the wrong version actually. I ended up using this form of the composite transformation, which I believe is the same.
```python 
centered_transform = sitk.CompositeTransform([transform, centering_transform])
```
Instead of 
```python 
centered_transform = sitk.CompositeTransform(transform)
centered_transform.AddTransform(centering_transform)
```

**Comment by zivy** [comment]
Hello @makquel,

No worries. You had us worried there for a moment. Will close this.

happy coding
