### ISSUE TITLE
Different header after writing and reading

### ISSUE THREAD

**Issue by fepegar** [SimpleITK/SimpleITK#1276]
Hi, all. I am having a precision issue. It looks like some header values are stored in single precision and loaded in double, making writing and reading a lossy process.

I think the code is self-explanatory:

```python
import numpy as np
import SimpleITK as sitk

print(sitk.__version__)  # prints 2.0.1

old = 3.39850907e+01
path = '/tmp/im_tol_test.nii.gz'

im = sitk.Image(1, 1, 1)
im.SetOrigin((old, 0))
sitk.WriteImage(im, path)
im2 = sitk.ReadImage(path)
new = im2.GetOrigin()[0]

down_up = float(np.array(old, np.float32))

print(old)      # prints 33.9850907
print(new)      # prints 33.98509216308594
print(down_up)  # prints 33.98509216308594
```

Is this expected?

**Comment by zivy** [comment]
Hello @fepegar,

I believe this is a "feature", not a bug. The nifti-1 header stores data in float and I believe that is what was implemented in ITK and consequentially is what is available in SimpleITK. 

@hjmjohnson can probably give a more detailed response.

**Comment by fepegar** [comment]
Thanks, @zivy. I just verified in the [NIfTI specifications](https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields) that the `voxel_offset` is stored using 4 bytes. I'll take that into account then.
