### ISSUE TITLE
module 'SimpleITK' has no attribute 'sitkNearestNeighbour'

### ISSUE THREAD

**Issue by dardaa** [SimpleITK/SimpleITK#1279]
Hi everyone,
I trying to resize my medical dataset (format .mhd), howeever i had this error: AttributeError: module 'SimpleITK' has no attribute 'sitkNearestNeighbour'
anyone have idea, please let me know.
thank you in advance

**Comment by richardbeare** [comment]
Try US spelling - sitkNearestNeighbor

**Comment by dardaa** [comment]
Thank you
it resolved
