### ISSUE TITLE
Warning when loading .img.gz file

### ISSUE THREAD

**Issue by inqlee0704** [SimpleITK/SimpleITK#1280]
I am trying to load a mask file which has .img.gz format. 
The mask file is successfully loaded, but I wonder if I can suppress the warning message created below. 
I tried to load python's warning library and suppress it, but it doesn't work since warnings are created from a cxx file. 

WARNING: In /Users/runner/work/1/sitk-build/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx, line 1009
NiftiImageIO (0x7ff6a74b3950): /Users/inkyu/Desktop/SNUH/LungSeg/177_WORST/ZUNU_vida-airtree.img.gz is Analyze file and it's deprecated

**Comment by blowekamp** [comment]
Hello, thank you for reporting this. Adding support to expose ITK logging mechanism is a good feature to add. Specifically, enabling use with the Python login module would be good.

**Comment by blowekamp** [comment]
All warnings from ITK can be suppressed by the [ProcessObject::SetGlobalWarningDisplay](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ProcessObject.html#a99d3df8ad7db82bc587edaa8706d135a) proper to false.

**Comment by inqlee0704** [comment]
How can I set this to be false in python?

**Comment by inqlee0704** [comment]
Thank you. 
I was able to fix it by
sitk.ProcessObject_SetGlobalWarningDisplay(False)
in python.

**Comment by blowekamp** [comment]
Support fo a logging object has also been added to the 2.1 development. This can provide finer grained logging control. Here is an example: https://simpleitk.readthedocs.io/en/master/link_Logging_docs.html
