### ISSUE TITLE
Is there any built-in method to read all series files within DICOM study folder?

### ISSUE THREAD

**Issue by makquel** [SimpleITK/SimpleITK#1281]
Hi,

I'm trying to read all series files within a studies folder  using the `ImageSeriesReader`, however, using the `GetGDCMSeriesIDs` method, I can't read unless I'm the *dcm folder. The following is the file tree that I'm working with: 

```shell
DICOM_studies
├── Study_1
│   ├── Series_1
│   ├── Series_2
│   ├── Series_N
├── Study_2
│   ├── Series_1
│   ├── Series_2
│   ├── Series_N
├── Study_N
```
So the method above only works if I'm just reading in series file (e.g. DICOM_studies/Study_2/Series_1)

**Comment by zivy** [comment]
Hello @makquel,

That is a feature not a bug 😉 . To get the functionality you want you need to traverse the file system starting with your data root directory. Please take a look at the [characterize_data.py](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/characterize_data.py#L323) script in our notebooks repository. More specifically, look at the [this code](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/b4ca695a25d5990a8aed8bcc2c89e734f480f342/Python/characterize_data.py#L323) in the `inspect_series` method. The combination of `inspect_series` and `inspect_single_series` addresses an even more generic structure where you can have:
```
DICOM_studies
├── Study_1
│   ├── Series_1_part_1
│   ├── Series_1_part_2
│   ├── Series_2
│   ├── Series_N
├── Study_2
│   ├── Series_1
│   ├── Series_2_part_1
│   ├── Series_2_part_2
│   ├── Series_2_part_3
│   ├── Series_N
├── Study_N
```

**Comment by makquel** [comment]
Hi @zivy , 
Thanks for the update, I hadn't watched for the examples in the notebooks in the first place, that seems to work well.
