### ISSUE TITLE
How to convert a displacement field in numpy array to sitk.transform type ?

### ISSUE THREAD

**Issue by XXZhou25** [SimpleITK/SimpleITK#1285]
Hi, 

I want to apply a displacement field in matrix(numpy array), with shape: N * M * K * 3 to deform images. 
May I know how to convert the np.array to sitk.transform type? 

I am using below code for deforming images with known DVF: 

	resampler = sitk.ResampleImageFilter()
	resampler.SetReferenceImage(fix)
	resampler.SetInterpolator(sitk.sitkBSpline)
	resampler.SetDefaultPixelValue(0)
	resampler.SetTransform(DVF in .tfm)                 -> where np.array to .tfm is needed
	regmov = resampler.Execute(mov)

I tried couples of functions but all fail to convert np.array to .tfm . 
I will appreciate for any of your suggestions!

**Comment by zivy** [comment]
Hello @XXZhou25,

The following code creates a deformation field from a numpy array:
```
import SimpleITK as sitk
import numpy as np

arr = np.random.random((10,20,30,3))
displacement_image = sitk.GetImageFromArray(arr, isVector=True)
# Set the displacement image's origin and spacing to relevant values
#displacement_image.SetOrigin()
#displacement_image.SetSpacing()
tx = sitk.DisplacementFieldTransform(displacement_image)
```

**Comment by XXZhou25** [comment]
> Hello @XXZhou25,
> 
> The following code creates a deformation field from a numpy array:
> 
> ```
> import SimpleITK as sitk
> import numpy as np
> 
> arr = np.random.random((10,20,30,3))
> displacement_image = sitk.GetImageFromArray(arr, isVector=True)
> # Set the displacement image's origin and spacing to relevant values
> #displacement_image.SetOrigin()
> #displacement_image.SetSpacing()
> tx = sitk.DisplacementFieldTransform(displacement_image)
> ```

Hi @zivy , 
Thank you so much for your prompt reply!
It works perfect!
Happy new 2021 year:)
