### ISSUE TITLE
compose 2 dense displacement field problem

### ISSUE THREAD

**Issue by XXZhou25** [SimpleITK/SimpleITK#1291]
Hi,

I want to compose 2 dense displacement field `T1`, `T2 `like below: 
         `T2(T1(A)) = B` 
I used sitk.CompositeTransform to comose them: 
`compose = sitk.CompositeTransform(T1, T2)`
in which `compose` is a `CompositeTransform` object. It worked well.

Then, I want to convert `compose` to a numpy array by converting it into `Transform object -> DisplacementFieldTransform -> numpy array`.
But I didn't find relative attributes, and failed with `tf = sitk.DisplacementFieldTransform(compose)`,`ERROR: Transform is not of type DisplacementFieldTransform!`

May I know the right way to convert `CompositeTransform` to numpy array? 
Thank you so much!

**Comment by zivy** [comment]
Hello @XXZhou25,

To convert a `CompositeTransform`, irrespective of what's inside, into a DeformationFieldTransform, use the [TransformToDisplacementFieldFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1TransformToDisplacementFieldFilter.html). Other than the CompositeTransform it requires that you specify the grid defining the DisplacementFieldTransform (origin, size, spacing) as part of the input.

**Comment by XXZhou25** [comment]
> Hello @XXZhou25,
> 
> To convert a `CompositeTransform`, irrespective of what's inside, into a DeformationFieldTransform, use the [TransformToDisplacementFieldFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1TransformToDisplacementFieldFilter.html). Other than the CompositeTransform it requires that you specify the grid defining the DisplacementFieldTransform (origin, size, spacing) as part of the input.

Hi @zivy ,
Thank you so much for your help! 
`TransformToDisplacementFieldFilter` works perfectly!
May I ask one more question? 

I tried to compose one DVF `T` and its inverse `inv(T)`. Theoretically I think `compose(T, inv(T))` should be complete 0, but since they are originally from different space, there might be some interpolation when compose them? 

If that is true, their compose should be at least close to 0? But I found the compose ranges from -2 ~ 7, which is quite large to me.

May I know what the problem might be here? 
Thank you so much @zivy for always helping us!

**Comment by zivy** [comment]
Hello @XXZhou25,

You are correct, the composition of a transformation and its inverse is expected to be close to the identity. I don't think the issue would be from interpolation as these errors appear to be large (I'm assuming sub-millimetric spacing for the images and deformation fields).

How was the inverse transformation obtained? There are several options for computing it (see this [Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/22_Transforms.ipynb)) and they will give slightly different results.

I am not sure what you mean by "originally from different space".

**Comment by XXZhou25** [comment]
> Hello @XXZhou25,
> 
> You are correct, the composition of a transformation and its inverse is expected to be close to the identity. I don't think the issue would be from interpolation as these errors appear to be large (I'm assuming sub-millimetric spacing for the images and deformation fields).
> 
> How was the inverse transformation obtained? There are several options for computing it (see this [Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/22_Transforms.ipynb)) and they will give slightly different results.
> 
> I am not sure what you mean by "originally from different space".

Hi @zivy , 
I do appreciate your reply!
I did some tests, found that it was indeed the inverse problem. 
I tested with: 
`a = np.zeros([80, 80, 80, 3])
a[20:40, 20:40, 20:40, :] = 10.0`
and I supposed I should obtain a perfect inverse with `a_inv[20:40, 20:40, 20:40, :] = -10.0`. However the inverse is hard to be perfect. 

I tested 3 inverse functions, and fund 'sitk.InvertDisplacementFieldImageFilter()' works best. I visualize generated dvfs in Slicer in x/y/z axis. The code is as below, please feel free to test it:

import SimpleITK as sitk
import numpy as np

a = np.zeros([80, 80, 80, 3])
a[20:40, 20:40, 20:40, :] = 10.0
aimg = sitk.GetImageFromArray(a)
sitk.WriteImage(aimg, 'dvf.nii.gz')
sitk.WriteImage(sitk.GetImageFromArray(a[:, :, :, 0]), 'dvf_x.nii.gz')
sitk.WriteImage(sitk.GetImageFromArray(a[:, :, :, 1]), 'dvf_y.nii.gz')
sitk.WriteImage(sitk.GetImageFromArray(a[:, :, :, 2]), 'dvf_z.nii.gz')

inv2 = sitk.IterativeInverseDisplacementFieldImageFilter()
inv2.SetNumberOfIterations(40)
inv2.SetStopValue(0.01)
a_inv2 = inv2.Execute(aimg)
a_inv2 = sitk.Transform(a_inv2)
a_inv2 = sitk.DisplacementFieldTransform(a_inv2)
a_inv2_img = a_inv2.GetDisplacementField()
a_inv2_imgd = sitk.GetArrayFromImage(a_inv2_img)
sitk.WriteImage(sitk.GetImageFromArray(a_inv2_imgd[:, :, :, 0]), 'dvf_inv2x.nii.gz')
sitk.WriteImage(sitk.GetImageFromArray(a_inv2_imgd[:, :, :, 1]), 'dvf_inv2y.nii.gz')
sitk.WriteImage(sitk.GetImageFromArray(a_inv2_imgd[:, :, :, 2]), 'dvf_inv2z.nii.gz')
aT = sitk.DisplacementFieldTransform(aimg)
aimg = sitk.GetImageFromArray(a)
compose2 = sitk.CompositeTransform([aT, a_inv2])
df = sitk.TransformToDisplacementFieldFilter()
df.SetReferenceImage(aimg)
compose2 = df.Execute(compose2)
dsp2 = sitk.GetArrayFromImage(compose2)
dsp2_x = sitk.GetImageFromArray(dsp2[:, :, :, 0])
dsp2_y = sitk.GetImageFromArray(dsp2[:, :, :, 1])
dsp2_z = sitk.GetImageFromArray(dsp2[:, :, :, 2])
sitk.WriteImage(compose2, 'compose2.nii.gz')
sitk.WriteImage(dsp2_x, 'compose2_x.nii.gz')
sitk.WriteImage(dsp2_y, 'compose2_y.nii.gz')
sitk.WriteImage(dsp2_z, 'compose2_z.nii.gz')

aimg = sitk.GetImageFromArray(a)
inv3 = sitk.InvertDisplacementFieldImageFilter()
inv3.SetMaximumNumberOfIterations(100)
inv3.SetMaxErrorToleranceThreshold(0.001)
a_inv3 = inv3.Execute(aimg)
a_inv3 = sitk.Transform(a_inv3)
a_inv3 = sitk.DisplacementFieldTransform(a_inv3)
a_inv3_img = a_inv3.GetDisplacementField()
a_inv3_imgd = sitk.GetArrayFromImage(a_inv3_img)
sitk.WriteImage(sitk.GetImageFromArray(a_inv3_imgd[:, :, :, 0]), 'dvf_inv3x.nii.gz')
sitk.WriteImage(sitk.GetImageFromArray(a_inv3_imgd[:, :, :, 1]), 'dvf_inv3y.nii.gz')
sitk.WriteImage(sitk.GetImageFromArray(a_inv3_imgd[:, :, :, 2]), 'dvf_inv3z.nii.gz')
aT = sitk.DisplacementFieldTransform(aimg)
aimg = sitk.GetImageFromArray(a)
compose3 = sitk.CompositeTransform([aT, a_inv3])
df = sitk.TransformToDisplacementFieldFilter()
df.SetReferenceImage(aimg)
compose3 = df.Execute(compose3)
dsp3 = sitk.GetArrayFromImage(compose3)
dsp3_x = sitk.GetImageFromArray(dsp3[:, :, :, 0])
dsp3_y = sitk.GetImageFromArray(dsp3[:, :, :, 1])
dsp3_z = sitk.GetImageFromArray(dsp3[:, :, :, 2])
sitk.WriteImage(compose3, 'compose3.nii.gz')
sitk.WriteImage(dsp3_x, 'compose3_x.nii.gz')
sitk.WriteImage(dsp3_y, 'compose3_y.nii.gz')
sitk.WriteImage(dsp3_z, 'compose3_z.nii.gz')

**Comment by XXZhou25** [comment]
> Hello @XXZhou25,
> 
> You are correct, the composition of a transformation and its inverse is expected to be close to the identity. I don't think the issue would be from interpolation as these errors appear to be large (I'm assuming sub-millimetric spacing for the images and deformation fields).
> 
> How was the inverse transformation obtained? There are several options for computing it (see this [Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/22_Transforms.ipynb)) and they will give slightly different results.
> 
> I am not sure what you mean by "originally from different space".

Hi @zivy 
I feel like all 3 inverse functions seem hard to obtain an inverse as accurate as possible. Their inverse all have not small biases. 
May I know if you have any suggestions for getting a good inverse? 

> "originally from different space"
Sorry I didn't clarify it clearly. I mean for `T2(T1(A)) = B`, `T1` is defined from the grids of `A`, T2 is defined from grids of `T1(A)`. 

Thank you so much for your kind help all the time!

**Comment by zivy** [comment]
Hello @XXZhou25,

These are the only options for obtaining an inverse deformation field. I have rarely used them as I usually set up my registrations so that the estimated transformations are in the direction I want.

In any case, there seems to be some misunderstanding here. Given a DisplacementFieldTransform `T_1`, it is defined over the grid `A`. `T_1(A)` does not define a regular grid as the DisplacementFieldTransform is arbitrary. The resulting point set defined by `T_1(A)` will not be on a regular grid. What the inverse transformation should give is `T_1_inv(T_1(A)) ~= A`.

If you can provide one of your deformation fields I can take a look at this (check if the inverse given by our code makes sense).

**Comment by XXZhou25** [comment]
> Hello @XXZhou25,
> 
> These are the only options for obtaining an inverse deformation field. I have rarely used them as I usually set up my registrations so that the estimated transformations are in the direction I want.
> 
> In any case, there seems to be some misunderstanding here. Given a DisplacementFieldTransform `T_1`, it is defined over the grid `A`. `T_1(A)` does not define a regular grid as the DisplacementFieldTransform is arbitrary. The resulting point set defined by `T_1(A)` will not be on a regular grid. What the inverse transformation should give is `T_1_inv(T_1(A)) ~= A`.
> 
> If you can provide one of your deformation fields I can take a look at this (check if the inverse given by our code makes sense).

Hi @zivy , sorry for my late response. 
Thank you so much for your clarification! I am much clearer. May I hold this question for sometime? Since I am doing some experiments, and may come back later. 
I do appreciate your help all the time! I've learned a lot from your expertises!

**Comment by XXZhou25** [comment]
Hi @zivy , 

Thank you so much for your kind help! I visualized my inverse dvf and original dvf in the Slicer, I feel like they are within expectation as you said above. There exists small biases due to regridding and interpolation, but I think it is acceptable in my registration pairs. 
Sorry for holding this issue session for such long time! 
I am going to close it if you don't mind!
