### ISSUE TITLE
How to convert one segmentation file 'nii.gz' to multiple individual '.stl' slice files using SimpleITK

### ISSUE THREAD

**Issue by DavidTu21** [SimpleITK/SimpleITK#1298]
Hi there,

I am performing a vertebrae segmentation task and I've output multiple segmentation.nii.gz files. Each of the segmented niftis files contains different segments (segment 1,2,3...), corresponding different vertebraes labelled in the file.

My question is how to convert the individual slices from each segmented nii.gz file?

**Input:** one segmented niftis file including slices for each vertebrae (nii.gz)

**Desired output:** individual '.stl'/'obj'/'nii'/'nrrd' files for each of the slices

Thank you in advance for your time and effort.

**Comment by zivy** [comment]
Hello @DavidTu21,

Not sure that I understand the question, so please clarify the following:
**Input**: A single 3D image with multiple vertebra, each identified by a unique label. A single slice (2D axial) can include multiple labels (multiple vertebra parts were visible on that slice)?
**Output**: For each vertebra output all the slices in which it appears so that you have a binary volume represented as a set of files? This can result in repetition of slices when multiple vertebra appear in the same slice.

If you can provide a sample volume will be easier to help.

**Comment by dave3d** [comment]
STL and OBJ are different than NII and NRRD.  The first two a geometric surface mesh formats, while the later two are image formats.  

Which output type are you trying to produce?  Producing surface meshes from images is outside the realm of ITK/SimpleITK.  You'd need to use iso-surface extraction to do that such as provided by VTK.

**Comment by DavidTu21** [comment]
Hi @zivy,

Here is the segmented nii.gz file viewed from some other software, there are unique labels to identify each vertebrae (segment 1, segment 2...)
<img width="960" alt="slicer" src="https://user-images.githubusercontent.com/50521351/106210992-00629880-621c-11eb-9ef2-ef9d45719abd.PNG">

What I am trying to do is to generate the individual slices for each segment (ideally in a .stl file), so the output should be somthing like this

<img width="752" alt="new" src="https://user-images.githubusercontent.com/50521351/106211147-50415f80-621c-11eb-94cf-19723b596d08.PNG">

I will add the original volumn file too to refer. https://drive.google.com/drive/folders/1pFwVvYQHN9l41-ksnLZhAgYgTST4jnEJ?usp=sharing

Please let me know if anything above is not cleared :)

**Comment by DavidTu21** [comment]
Hi @dave3d,

Thank you for the information. It is ok to just produce the nrrd or nii file from the input. Is this achievable by SimpleITK? Thanks.

**Comment by zivy** [comment]
Hello @DavidTu21,

Here is code that I believe does what you want, please modify to suite your needs:
```
import glob
import SimpleITK as sitk

# Create artificial input image
multi_label_image = sitk.Image([3]*3, sitk.sitkUInt8)
multi_label_image[0,0,0] = 1
multi_label_image[0,1,0] = 2
multi_label_image[0,0,1] = 2
multi_label_image[0,1,1] = 1
multi_label_image[0,2,1] = 3
multi_label_image[0,0,2] = 3


# As we don't know what the real original labels are we relabel
# so they start at 1 and are contiguous
multi_label_image = sitk.RelabelComponent(multi_label_image, sortByObjectSize=False)

label_shape_filter = sitk.LabelShapeStatisticsImageFilter()
label_shape_filter.ComputeFeretDiameterOff()
label_shape_filter.ComputeOrientedBoundingBoxOff()
label_shape_filter.ComputePerimeterOff()
label_shape_filter.Execute(multi_label_image)

# Either binary slices or label slices depending on if we want
# to keep_label
keep_label = True
for label in range(1, label_shape_filter.GetNumberOfLabels()+1):
    bounding_box = label_shape_filter.GetBoundingBox(label)
    for z in range(bounding_box[2], bounding_box[2] + bounding_box[5]):
        sitk.WriteImage((multi_label_image[:,:,z:z+1]==label)*(label if keep_label else 1), f'label{label}_{z}.nrrd')

# Read the slices on a per label basis to create the volumes, sorting is based on z coordinate so that
# we only rely on the label number appearing in the file name but ignore the z coordinate in the file name, it 
# is obtained from the actual data.
label_vols = []
file_reader = sitk.ImageFileReader()
for label in range(1, label_shape_filter.GetNumberOfLabels()+1):
    vol_files = []
    file_names = glob.glob(f'label{label}_*.nrrd')
    for fname in file_names:
        file_reader.SetFileName(fname)
        file_reader.ReadImageInformation()
        vol_files.append([file_reader.GetOrigin()[2] ,fname])
        vol_files.sort()
    _,vol_files = zip(*vol_files)
    label_vols.append(sitk.ReadImage(vol_files))
```

**Comment by DavidTu21** [comment]
Hi @zivy ,

Thank you so much for your reply which is so detailed and I really appreciate your time!

May I just ask last question in modifying the above code as I am new to SimpleITK and may have some misunderstandings. So firstly I don't need to 'create the artificial input image', so instead I will read the nii.gz image using  `sitk.SetFileName` and `ReadImageInformation.`

Also I don't need to relabel all the labels using `RelabelComponent` and also write the file to `.stl` instead of `.nrrd` in the above code. Please clarify me if there is anything wrong. Thank you again :)

**Comment by zivy** [comment]
Hello @DavidTu21,
1. Instead of "create artificial input image", read the image: `multi_label_image=sitk.ReadImage(file_name)`.
2. You cannot write the output in stl format as SimpleITK does not support that and the segmentation image is not a mesh, please see @dave3d's response. You will need to use some other tool to create the mesh and save it to stl.

**Comment by DavidTu21** [comment]
Thank you @zivy !!

**Comment by dave3d** [comment]
@DavidTu21 If you want to extract STL or OBJ from your images, you need to do iso-surface extraction.  You can use an interactive application to do that, such as Slicer.  Or you can script it using VTK.  I wrote such a script, dicom2stl, which you can see on GitHub:

https://github.com/dave3d/dicom2stl

It can take as input a stack of DICOM images, or any 3d image that SimpleITK supports, such as Nifti or NRRD.

**Comment by DavidTu21** [comment]
Hi @dave3d ,

Thank you for your reply. I have actually looked at your code and tried that before. It works perfectly with the unsegmented bone image  (.nii.gz file) and could output its corresponding mesh (.stl). However when I tried with a segmented image (still .nii.gz file but with segments in it), there will be no output and vtk says that 'there is nothing to write'. Have you faced this issue before? Thank you.
![image](https://user-images.githubusercontent.com/50521351/106523695-97d62d00-6535-11eb-9f35-9b3d4a6b5f3e.png)

**Comment by DavidTu21** [comment]
Hi @zivy ,

I really apologize to bother you again, the code you sent to me on https://github.com/SimpleITK/SimpleITK/issues/1298#issuecomment-770051351 works very well on generating slices for each label in the image. However I just have one last question in regards to create the volume in the final step and I am appreciated that if you could help me with that. 

The output currently has few nrrd files for each label, along with their z coordinates value. I am quite confused with the final step when we create the `label volume` and later we append volume files to it `label_vols.append(sitk.ReadImage(vol_files))`

I am wondering once we create the volume file, do we generate any output for each label from there?

**Comment by zivy** [comment]
Hello @DavidTu21,
I just checked if your desired functionality exists in [ITK-SNAP](http://www.itksnap.org/pmwiki/pmwiki.php), and it does. Their [code is here](https://sourceforge.net/p/itk-snap/src/ci/master/tree/).

In ITK-SNAP
1. Segmentation->Open Segmentation, select your file
2. Segmentation->Export as Surface Mesh
     "Export meshes for all labels as separate files"
     "File Format" STL mesh file.

**Comment by dave3d** [comment]
First you need to select a proper iso-value.  You can see near the top of your output it's using an is-value of 0.  That's the background color, so the script will not find an iso-surface.

If you use the '-i 0.5' flag, selecting an iso-value of 0.5, you will get one STL file that has all the segments.  Here's the result I get:

![spine](https://user-images.githubusercontent.com/611581/106640711-5ef98080-6554-11eb-80d9-99c98ed9a2a0.jpg)


If you want an STL file for each segment, you want to create an image that has just that value.  You can do it something like this:

```
import SimpleITK as sitk

img = sitk.ReadImage("GL045_CT_ax.nii.gz")

# create a image of just segment 5

segment5 = (img==5)

```
