### ISSUE TITLE
4D PermuteAxesImageFilter in build 1.2.2 from conda

### ISSUE THREAD

**Issue by laqua-stack** [SimpleITK/SimpleITK#1300]
Hey all,

i desperately tried to stack some (2D + t) series to 4D with the python wrapped SimpleITK. 

The JoinSeriesImageFilter works fine, however the axes are not ordered in a way i would prefer it.
Actually they are x, y, t, z and I would like to have the temp axis last.

    import SimpleITK as sitk
    imageReader = sitk.ImageSeriesReader()
    imageReader.MetaDataDictionaryArrayUpdateOn()
    imageReader.LoadPrivateTagsOn()
    imageReader.SetOutputPixelType(sitk.sitkUInt8)  # Here i tried different PixelTypes
    series_ids = imageReader.GetGDCMSeriesIDs(path)
    images = []

    for series_id in series_ids:
        series_file_names = imageReader.GetGDCMSeriesFileNames(path, series_id)
        imageReader.SetFileNames(series_file_names)
        image = imageReader.Execute()  # type: sitk.Image
        images.append(image)

    join = sitk.JoinSeriesImageFilter()
    joined_image = join.Execute(images)
    # here the actual error happens
    joined_image = sitk.PermuteAxes(joined_image, (0, 1, 3, 2))

   

`RuntimeError: Exception thrown in SimpleITK PermuteAxes: c:\miniconda3\envs\bld\conda-bld\simpleitk_1563387058023\work\code\common\include\sitkMemberFunctionFactory.hxx:185:
sitk::ERROR: Pixel type: 8-bit unsigned integer is not supported in 4D by class itk::simple::PermuteAxesImageFilter or SimpleITK compiled with SimpleITK_4D_IMAGES set to OFF.`

I tested loading the images with the following PixelTypes and failed with the same error as above.

sitk.sitkUInt8
sitk.sitkUInt16
sitk.sitkInt16
sitk.sitkFloat32

Is there any 4D support for the filter? Is there any straightforward solution for this? Is conversion to numpy competitive in terms of speed? I have about 9000 series to be processed in this way.

Thanks a lot in advance!

**Comment by blowekamp** [comment]
Let me look into adding 4D support.

**Comment by laqua-stack** [comment]
Thank you very much @blowekamp!

For those like me, who can't wait ;-). I did the numpy extra turn. And it is quite fast.
      
      import SimpleITK as sitk
      import numpy as np
      
      def numpyPermuteAxes(image, order):
          """
          Takes an sitk image,
          takes a numpy view to it,
          changes the order of axes,
          transforms the numpy array back to sitk image
      
          CAVE: numpy axis ordering is reversed. For convenience with PermutateAxesImageFilter,
          it should be supplied in sitk ordering.
          :param image: sitk image to be transformed. Considers Origin, Direction and Spacing set accordingly.
          :param order: list or tuple, len = no. of axes giving the new order of axes in sitk order
          :return: sitk image with reordered axes
          """
          # Get array view to image data CAVE: inversed ordering of axes
          np_arr = sitk.GetArrayViewFromImage(image)
      
          # CAVE: inversed ordering of axes
          np_order = [len(order) - axis - 1 for axis in reversed(order)]
          order = np.array(order)  # speeds up take a little
      
          # Get direction, origin and spacing of original array.
          direction = np.array(image.GetDirection()).reshape(image.GetDimension(), -1)
          origin = np.array(image.GetOrigin())
          spacing = np.array(image.GetSpacing())
      
          # Transform direction, origin and spacing in the same way as original.
          xv, yv = np.meshgrid(order, order)
          tf_direction = direction[xv, yv].reshape((-1), )
          tf_origin = origin[order]
          tf_spacing = spacing[order]
      
          # Reorder the np array and transform to sitk image.
          transformed_image = sitk.GetImageFromArray(np.transpose(np_arr, axes=np_order), isVector=False)
      
          # Apply transformed Direction, Origin, Spacing
          transformed_image.SetDirection(tf_direction)
          transformed_image.SetOrigin(tf_origin)
          transformed_image.SetSpacing(tf_spacing)
      
          return transformed_image

**Comment by blowekamp** [comment]
Here is the PR to add 4D+ support: #1301

**Comment by blowekamp** [comment]
The PR was merged and `PermuteAxes` now supports for 4D and 5D images in the nightly [latest](https://simpleitk.readthedocs.io/en/master/gettingStarted.html#latest-binaries) binaries.
