### ISSUE TITLE
ImageSeriesReader.GetGDCMSeriesFileNames takes incredible long time to execute

### ISSUE THREAD

**Issue by SpearlikeCorn** [SimpleITK/SimpleITK#1309]
Hi,
I have several, different DICOM series stored in the one directory (around 80 of them). I have access to their IDs and I am executing following code to gather the complete DICOM series:
```
reader = sitk.ImageSeriesReader()`
series_id = "1.2.300.2222"
path_series = "C:\Dicom_data"
dicom_names = reader.GetGDCMSeriesFileNames(path_series, series_id)
```
The problem is that it takes around 9min 47s to execute. Am I doing something wrong? Is there way to speed this up? My other idea is to gather the images of single series and distribute them between directories, is this common practice?

**Comment by zivy** [comment]
Hello @SpearlikeCorn,

You are doing nothing wrong, "it is a feature not a bug". For further details and a solution, please see the discussion and code options I provided [on the ITK discourse](https://discourse.itk.org/t/imageseriesreader-speed/3558/2). Run the script provided there to see the timing in your case. The second option of aggregating the study:series is the recommended solution.
