### ISSUE TITLE
Resizing a MRI in Python

### ISSUE THREAD

**Issue by batuhansozer** [SimpleITK/SimpleITK#1317]
Hi I have a nii.gz file and i read the file with this code `sitk.ReadImage('file.nii.gz')` and i want to resize it and then resave it.
How can I do that in python ?

**Comment by zivy** [comment]
Hello @batuhansozer,

Please see [this Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/21_Transforms_and_Resampling.ipynb) for details on transformations and resampling. 

If you are interested in other aspects of SimpleITK, we recommend skimming through [the notebook repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) and if you have time, take the [online tutorial](https://simpleitk.org/TUTORIAL/).
