### ISSUE TITLE
R Documentation Warning/Errors

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#132]
On dashboard builds [1] we are seeing the following errors/warnings:

> Warning: /mntSimpleITK-build/SimpleITK-build/Wrapping/R/Packaging/SimpleITK/man/AntiAliasBinaryImageFilter.Rd:70: unexpected section header '\section'
> Warning: /mntSimpleITK-build/SimpleITK-build/Wrapping/R/Packaging/SimpleITK/man/AntiAliasBinaryImageFilter.Rd:107: unexpected END_OF_INPUT '
> Warning: /mntSimpleITK-build/SimpleITK-build/Wrapping/R/Packaging/SimpleITK/man/ShotNoiseImageFilter.Rd:39: unexpected section header '\section'
> /mntSimpleITK-build/SimpleITK-build/Wrapping/R/Packaging/SimpleITK/man/ShotNoiseImageFilter.Rd:76: unexpected END_OF_INPUT '
> 

[1] https://open.cdash.org/viewBuildError.php?buildid=4824513

**Comment by blowekamp** [comment]
@richardbeare Can you look at these warnings/errors to see if they can be easily cleaned up?

**Comment by richardbeare** [comment]
I'll check, but I think I recall seeing problems caused by equations. I guess manual fixes are feasible, given the small number of errors and the fact that we're not aiming for regular rebuilds.
