### ISSUE TITLE
Having a weird problem while Writing images

### ISSUE THREAD

**Issue by sarthakpati** [SimpleITK/SimpleITK#1323]
Hi,

I am having a very weird issue when writing images whose information has changed:

```python
>>> import SimpleITK as sitk
>>> base_image = sitk.ReadImage("C:/test/test_flair.nii.gz")
>>> test_image = sitk.ReadImage("C:/test/test_001.nii.gz")
>>> test_image.CopyInformation(base_image)
>>> sitk.WriteImage(test_image, "C:/test/test_new.nii.gz")
>>> test_image_new = sitk.ReadImage("C:/test/test_new.nii.gz")
>>> test_image_new.GetOrigin()
(0.0, 0.0, 0.0)
>>> test_image.GetOrigin()
(-0.0, -239.0, 0.0)
```

As you can see, the information is no longer preserved. I am running on Windows with SimpleITK version 1.2.4 and 2.0.2. Any help towards this would be very helpful, thank you.

[test_flair.nii.gz](https://github.com/SimpleITK/SimpleITK/files/5982320/test_flair.nii.gz)
[test_001.nii.gz](https://github.com/SimpleITK/SimpleITK/files/5982321/test_001.nii.gz)

Cheers,
Sarthak

Updates: 
- also present in ITK's python package, but not in C++
- replicable in Linux as well
- Cross-posted in https://discourse.itk.org/t/python-writing-is-not-working-correctly/3864/3

**Comment by dzenanz** [comment]
Which version of ITK Python are you using? Is it present in [5.2 RC2](https://pypi.org/project/itk/5.2rc2/)?

**Comment by sarthakpati** [comment]
This was using 5.1.2, the current stable.

**Comment by dzenanz** [comment]
Please also try the recently released RC. If it is present there too, sharing your variant of ITK Python code which reproduces the error would be appreciated.

**Comment by sarthakpati** [comment]
Hi @dzenanz, please see the reponse from @zivy in Discourse related to this: https://discourse.itk.org/t/python-writing-is-not-working-correctly/3864/3?u=sarthakpati

I trying to replicate the issue in RC2 right now.
