### ISSUE TITLE
Specific label unique volume

### ISSUE THREAD

**Issue by ryancinsight** [SimpleITK/SimpleITK#1332]
Hello,

I have a 3D label map volume with potentially overlapping labels, I.e. areas that are retreated, is there a filter that will allow me to get unique volume or volume not overlapped by all other potential labels per label?

Labeloverlapmeasures looks like potential route but was unsure how to implement this route.

best regards

**Comment by zivy** [comment]
Hello @ryancinsight,

Not clear what exactly it is you want to do, please provide additional details (not sure what retreated means and why that is relevant to what you want to do).

The [LabelOverlapMeasuresImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1LabelOverlapMeasuresImageFilter.html#details) is intended for evaluating the overlap between two segmentations (Dice/Jaccard/Mean...). The overlap is between corresponding labels (how well does label x in the first image overlap with label x in the second image).

**Comment by richardbeare** [comment]
Maybe you need a combination of masking and volume measures? If you have two images, each with a single object and you want to measure the volume of object in image A that isn't covered by the object in image B:

if you're using python

AnotB = A & (!B)

then volume can be computed in a number of ways - convert to numpy and add up, or use one of the LabelStatisticsFilters

**Comment by ryancinsight** [comment]
@zivy thank you very much for the explanation.

Intro:
I am using a focused source of radiation to create a small spheroid dose. I move these spheres inferior, medial, lateral, and superior to the initial target while labeling each one based on when they were made, I.e target 1, target 2, etc... So this creates my label map of let’s say 1-7 for the different targets. 

problem:
Some of these spheres overlap though and while it is easy enough to get individual label statistics or create binary map and get total volume treated not over counting overlap, I am finding it more difficult to get the volume of label 1 that is not overlapped with 2-7. Otherwise, how to create new label to show all overlapped areas to see if this overlap in dose is beneficial to treatment or if overlap between specific labels were significant, so label overlap statistics.


@richardbeare thanks for your thoughts on this, it would certainly be possible to do a numpy where function and determine volume that is label 1 but not label 2... but I was hoping there may be a faster filter since I’m looking at 20+ labels.

**Comment by richardbeare** [comment]
Are your labels in different images? If all the labels are in a single volume then there's no simple way of determining the overlap, as only one label per voxel is stored. If this is the scenario, and you can't reacquire, then I guess your only choice is to use some kind of shape assumptions to make a guess.

If the targets are imaged in separate volumes, the I don't see you have any choice apart from building something that removes all other targets from the one of interest. 

There may be some short cuts - for example:
 Add up all the masks (after binarizing). 
 Any value of 1 is not overlapping anything else, so create an image of nonoverlapping things with (sum==1). 
 Then take your label targets one at a time and mask with the original label image. You can combine the results of each iteration together in a single image, if you like. This will give you a new label image containing all your target labels, without overlap. You can feed this through the labelstatisticsfilter to get the measures.

I wouldn't worry too much about speed at this stage. Converting to numpy isn't ideal, but it can be convenient and it isn't especially slow. You can optimize using other filters after you're sure it is doing the right thing.

**Comment by ryancinsight** [comment]
I am creating the labels since I have the targets coordinates and 3D shapes. Therefore, for each target I am labeling the voxels with the target number and doing label statistics between the treatment images and the mask image at the label of target. That way at target 2 I can override the label map voxels that were in target 1 with a 2 instead and do statistics on label 2. Since I am resampling to 1 mm iso-voxels I then make everything above 0 in label map be 1 to flatten and sum to the total volume actually treated.

However, if I keep the label volumes separate, as you mention, than I should be able to convert to numpy make label of only overlapped volumes and also get the volume per target that is not overlapped with any other target using conditional statements...

Thank you very much for this suggestion, I'll give it a shot and let you know!

**Comment by blowekamp** [comment]
Another option if you have less that 64 target is to use uint64 ( or 32 target with uint 32 etc ) and have each target's value be a bit in the "bit" label map.

Target 1: 0001b
...
Target 4: 1000b

After this encoding you can do bitwise operations on the whole image to answer some of these questions.

**Comment by ryancinsight** [comment]
Actually @richardbeare suggestion worked just fine for now but I'll look into the bit label map as well. Thanks everyone!
