### ISSUE TITLE
Converting ITK image to VTK

### ISSUE THREAD

**Issue by mrsaleh** [SimpleITK/SimpleITK#1335]
Hi
Thanks to your great work, recently we added ITK to our project, we mostly use VTK. but the issue is that we need to convert image data between these two.
I found [this](https://itk.org/ITKExamples/src/Bridge/VtkGlue/ConvertAnitkImageTovtkImageData/Documentation.html), but when I looked library for ImageToVTKImageFilter I found nothing.
Edit: I'm using C# language
Thanks in advance.

**Comment by dave3d** [comment]
Hello.

What language are you developing in?  I wrote Python functions to convert between VTK and SimpleITK image.  You can see them here:

https://github.com/dave3d/dicom2stl/tree/main/utils

Basically they use numpy arrays as a conduit to go from VTK to SimpleITK and back.

**Comment by mrsaleh** [comment]
Sorry, I totally forgot to mention that I'm using C#.

**Comment by zivy** [comment]
Hello @mrsaleh,

For SimpleITK2VTK in C# you don't have `GetArrayFromImage`, you will need to use the [Image's](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1Image.html) `GetBufferAs*` family of functions (e.g. GetBufferAsUInt8) to get the array of raw pixel values. The rest is pretty much the same, just in C#.

The other way round from VTK2SimpleITK, there isn't a nice way of setting the raw intensities into the image other than it's `SetPixelAs*` family of functions and iteration.

**Comment by dave3d** [comment]
I have no experience with VTK in CSharp (Activiz), but could you use vtkImageData's GetScalarPointer method to get access to a VTK Image's pixel data?  Then construct a SimpleITK image from that pixel buffer.

**Comment by mrsaleh** [comment]
Actually, I used vtkImageImport to convert from SimpleITK image to vtkImageImport , but working with memory directly is weird and causes many issues. I was just considering that ImageToVTKImageFilter class would make life easier for people like me that use both ITK and VTK library hand to hand in the project. Is there any reason that ImageToVTKImageFilter is missing? @dave3d @zivy

**Comment by zivy** [comment]
Hello @mrsaleh,

The primary reason that itk::ImageToVTKImageFilter isn't wrapped is that adding this filter introduces a dependency on VTK which we want to avoid.
