### ISSUE TITLE
c_make fails with: Could NOT find TCLTK (missing: TK_LIBRARY TK_INCLUDE_PATH)

### ISSUE THREAD

**Issue by Jimmy2027** [SimpleITK/SimpleITK#1336]
Hi, I'm trying to build simpleitk 1.2.4 but c_make fails with the error: ` Could NOT find TCLTK (missing: TK_LIBRARY TK_INCLUDE_PATH)`

Is this a problem with my tck package?
My build log: [build.log](https://github.com/SimpleITK/SimpleITK/files/6045585/build.log)
The c_make error log: [CMakeError.log](https://github.com/SimpleITK/SimpleITK/files/6045586/CMakeError.log)
The cmake output log: [CMakeOutput.log](https://github.com/SimpleITK/SimpleITK/files/6045588/CMakeOutput.log)

**Comment by blowekamp** [comment]
Can you build and use SimpleITK 2? The difference between the CMake version you are using and the version 1.2 was developed with is suspicion.

**Comment by TheChymera** [comment]
This is fixed by adding the `dev-lang/tk` dependency for the simpleitk package :)
