### ISSUE TITLE
How to get the afffine metrix from dicom files

### ISSUE THREAD

**Issue by gaody9527** [SimpleITK/SimpleITK#1340]
I have used the simpleitk to read a series  dcm files, and I want to get the affine metrix, 
first， I use the simpleITK to read the dcm files and then write to a nii file 
second, I use the nibabel package to read the nii file and get the affine,
so, how I can get the affine from dcm file by simpleITK directly
A further step, I get the direction by `GetDirection()`, and find it is different with the `nii.affine`

```
import numpy as np
import SimpleITK as sitk
import nibabel as nib

data_path = r'F:\test_data\136401000949983\136401000949983_T2'
save_path = r'F:\test_data\136401000949983_T2.nii'

reader = sitk.ImageSeriesReader()
dicom_files = reader.GetGDCMSeriesFileNames(data_path)
reader.SetFileNames(dicom_files)
image = reader.Execute()
sitk.WriteImage(image, save_path)
direction = image.GetDirection()
direction = np.reshape(direction, (3, 3))
print(direction)
nii = nib.load(save_path)
data = nii.get_data()
affine = nii.affine
print(data.shape)
print(affine)
```

the result is followed:
```
Direction : 
 [[ 9.99975940e-01  2.07761000e-10  6.93680831e-03]
 [ 1.08982899e-04  9.99876577e-01 -1.57104651e-02]
 [-6.93595215e-03  1.57108431e-02  9.99852520e-01]]
nii.affine : 
 [[-3.90615564e-01  1.52083900e-04 -3.33113177e-02  1.18197067e+02]
 [-1.94655424e-04 -3.90576750e-01  7.54036526e-02  7.77070770e+01]
 [-2.70816142e-03  6.13757529e-03  4.79928609e+00 -7.03303223e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
```

**Comment by zivy** [comment]
Hello @gaody9527 ,

It is to be expected that the results are different:
1. ITK/SimpleITK use a LPS coordinate system and nifti/nibable uses a RAS coordinate system, [more on RAS/LPS here](https://www.slicer.org/wiki/Coordinate_systems).
2. nibabel's `affine` is the transformation that maps indexes to physical points in the RAS coordinate system and in SimpleITK the GetMatrix is just the rotation matrix. To get the equivalent matrix from SimpleITK you need to manually create it: $\left[\begin{array}{cc}R*S & \mathbf{o} \\ 0 & 1 \end{array}\right]$. The matrix `S` is the diagonal matrix with the image's spacing and the vector `o` is the image's origin.

In SimpleITK the computation of this matrix is under the hood and you use the Image class's `TransformIndexToPhysicalPoint ` and `TransformPhysicalPointToIndex` methods.

**Comment by gaody9527** [comment]
Got it, Thank you for your answer！
