### ISSUE TITLE
How to edit .mhd file

### ISSUE THREAD

**Issue by koeglfryderyk** [SimpleITK/SimpleITK#1343]
I have some metadata that I want to add to the .mhd file (I am using Python 3.8.5)

For now, I was just handling it like a regular text file to add lines of text.

I was wondering if there is a SimpleITK function that allows to add lines of text to an .mhd file (I couldn't find any).

Thanks for your help in advance

**Comment by dave3d** [comment]
You can view an Image's meta data information using the GetMetaDataKeys and GetMetaData methods.  To add a new field you can use the SetMetaData method.

This example reads a file's header and shows all its meta data:
https://simpleitk.readthedocs.io/en/master/link_DicomImagePrintTags_docs.html

To write new metadata you have to read the the entire image (not just the header).

**Comment by koeglfryderyk** [comment]
Thank you!

**Comment by koeglfryderyk** [comment]
Thank you!

And is there a way to remove a key-value pair?
