### ISSUE TITLE
Getting a 2D image from a 3D image in c#

### ISSUE THREAD

**Issue by mabelzunce** [SimpleITK/SimpleITK#1345]
Hi,
I'm trying to save same jpg images with slices from a 3d image. This is very simple in python but I haven't been able to do this in c#. I have tried different ways unsuccessfully. If I get a slice using  SimpleITK.Slice(), I can get a slice of the image but internally is a three dimensional image of size(X,Y,1) and WriteImage only accepts 2d images for jpg format. Is there any way of doing this without having to copy the arrays between the 3D slice and a new 2D image?

Thanks,
Martin

**Comment by zivy** [comment]
Hello @mabelzunce,

What you are looking for is the [ExtractImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ExtractImageFilter.html). It will collapse a dimension if you set that size to zero in the [SetSize](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ExtractImageFilter.html#af3c522ffc6b88628a2778caf9c7d48e1) method.

**Comment by mabelzunce** [comment]
That's exactly what I was looking for. Thanks.
