### ISSUE TITLE
SimpleITK.ReadImage throws exception if used within QT Application

### ISSUE THREAD

**Issue by Elektropepi** [SimpleITK/SimpleITK#1346]
### What I'm trying to do:
- Use `SimpleITK.ReadImage` to read a Nrrd within a QT Application. Reading the Nrrd file outside of the QT Application works just fine.

### Expected outcome:
- The Nrrd file has been successfully loaded

### Actual outcome:
- SimpleITK throws an exception:
```
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK-build/ITK-prefix/include/ITK-5.1/itkImageBase.hxx:177:
itk::ERROR: itk::ERROR: Image(0x557ffc4214e0): A spacing of 0 is not allowed: Spacing is [0, 0, 1]
```

### Specifications
- OS: Manjaro Linux x86_64
- Kernel: 5.10.18-1-MANJARO
- Python: 3.8.8
- SimpleITK: 2.0.2
- PySide6: 6.0.2

### Minimal example:
The NRRD File was taken from the CT Scan of Patient 11 of [this data collection](https://figshare.com/articles/dataset/MedicalAugmentedRealityFacialData_Collection/8857007)
You can get it directly [here](https://we.tl/t-W56P519WIE).

```python
import SimpleITK as sitk
# Doesn't matter if pyside2, pyside6, pyqt5 or pyqt6 is used, they all crash the same
from PySide6.QtWidgets import QApplication 

pat11_nrrd = "Pat11_CT.nrrd"

app = QApplication() # When removing this line, the image is read successfully!
sitk.ReadImage(pat11_nrrd, imageIO="NrrdImageIO") # Above exception is thrown
```

**Comment by zivy** [comment]
Hello @Elektropepi,

I tried the code on OSX (catalina),  pyside2 (5.13.2) and simpleitk (2.0.2). It worked without any problems.

What OS are you on and what version of SimpleITK are you using?

**Comment by Elektropepi** [comment]
Hi @zivy 

Thank you very much for testing, that's strange that it works in your case.

My exact specs are

- OS: Manjaro Linux x86_64
- Kernel: 5.10.18-1-MANJARO
- Python: 3.8.8
- SimpleITK: 2.0.2
- PySide2: 5.15.2

Just tried it again there is no race condition or something like that, the same exception always occurs if a `QApplication()` is instantiated before reading the image.

May I ask, what python version did you use for your test? Maybe I can try it with the same python version.

**Comment by zivy** [comment]
Hello @Elektropepi,

Tried it with Python 3.7.0 (anaconda distribution).

**Comment by Elektropepi** [comment]
Just tested it with Python 3.7.10, same exception occurs, strange. Maybe it's a Linux thing since you use Mac? 

The weirdest thing is, the exception is not thrown if I remove the instantiation of `QApplication() `

**Comment by blowekamp** [comment]
Perhaps there is some type of Qt Locale setting that is effecting the Standard C++ IO?
