### ISSUE TITLE
SimpleITK fails to build with `unable to locate template_code_filename` 

### ISSUE THREAD

**Issue by TheChymera** [SimpleITK/SimpleITK#1347]
The build of an older simpleitk version (as needed for lua `5.1` compatibility), fails with the following build log:
[build.log](https://github.com/SimpleITK/SimpleITK/files/6135751/build.log)

Additional CMake files can be seen here:
[CMakeError.log](https://github.com/SimpleITK/SimpleITK/files/6135752/CMakeError.log)
[CMakeOutput.log](https://github.com/SimpleITK/SimpleITK/files/6135754/CMakeOutput.log)

I presume these `unable to locate template_code_filename` errors, which are all over the place, might be what's causing the issue, e.g.:

```
CMake Warning at CMake/sitkGenerateFilterSource.cmake:129 (message):
  Error processing
  /var/tmp/portage/sci-libs/simpleitk-1.2.4/work/SimpleITK-1.2.4/Code/BasicFilters/json/ZeroCrossingImageFilter.json,
  unable to locate template_code_filename
Call Stack (most recent call first):
  CMake/sitkGenerateFilterSource.cmake:163 (get_dependent_template_components)
  CMake/sitkGenerateFilterSource.cmake:250 (expand_template)
  Code/BasicFilters/CMakeLists.txt:5 (generate_filter_source)
  ```
  
  but I am really unsure. Can you help me out?

**Comment by blowekamp** [comment]
Thank you for working on packaging SimpleITK.

Those error messages should not occur. I don't believe I have seen the before. What CMake version are you using?

The log seem incomplete as the do not include your posted error message. Is there a complete configuration log?

For SimpleITK Lua 5.2+ is only needed for compilation time and not at runtime.

**Comment by TheChymera** [comment]
@blowekamp thank you for continuing to assist me :)

I use `=cmake-3.19.6`.
The build log indeed includes the error message, as seen in many places, including e.g. line 2272.

The complete cmake command (also found in the log on line 22) is:

```
cmake -C /var/tmp/portage/sci-libs/simpleitk-1.2.4/work/simpleitk-1.2.4_build/gentoo_common_config.cmake
    -G Ninja
    -DCMAKE_INSTALL_PREFIX=/usr
    -DUSE_SYSTEM_GTEST=ON
    -DUSE_SYSTEM_ITK=ON
    -DUSE_SYSTEM_LUA=ON
    -DUSE_SYSTEM_SWIG=ON
    -DUSE_SYSTEM_VIRTUALENV=ON
    -DBUILD_TESTING:BOOL=OFF
    -DSimpleITK_FORBID_DOWNLOADS=ON
    -DSimpleITK_PYTHON_USE_VIRTUALENV:BOOL=OFF
    -DSimpleITK_EXPLICIT_INSTANTIATION=OFF
    -DModule_SimpleITKFilters:BOOL=ON
    -DExternalData_OBJECT_STORES:STRING=/var/tmp/portage/sci-libs/simpleitk-1.2.4/work/simpleitk-1.2.4_build/.ExternalData
    -DSimpleITK_INSTALL_LIBRARY_DIR=lib64
    -DWRAP_PYTHON=no
    -DCMAKE_BUILD_TYPE=Gentoo
    -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-libs/simpleitk-1.2.4/work/simpleitk-1.2.4_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-libs/simpleitk-1.2.4/work/SimpleITK-1.2.4
```

**Comment by blowekamp** [comment]
The following variables should be unused:
```
    -DUSE_SYSTEM_GTEST=ON
    -DUSE_SYSTEM_ITK=ON
    -DUSE_SYSTEM_LUA=ON
    -DUSE_SYSTEM_SWIG=ON
    -DUSE_SYSTEM_VIRTUALENV=ON
    -DModule_SimpleITKFilters:BOOL=ON
```

There is the following error in the configuration:
```
-- Could NOT find Lua (missing: LUA_EXECUTABLE) (found version "5.1.5")
```

Please try setting `LUA_EXECUTABLE` maybe `SimpleITK_LUA_EXECUTABLE` too.

**Comment by TheChymera** [comment]
I have tried to build again without the listed variables, and the error stays as far as I can tell, the same. As seen in the full [build.log](https://github.com/SimpleITK/SimpleITK/files/6142520/build.log).
As for the LUA executable, the build system reports finding it:

```
-- Found Lua: /usr/lib64/liblua5.1.so;/usr/lib64/libm.so (found version "5.1.5")

```

**Comment by blowekamp** [comment]
Please try to configure with setting LUA_EXECUTABLE maybe SimpleITK_LUA_EXECUTABLE too.

**Comment by TheChymera** [comment]
what should I point it to? `/usr/lib64/liblua5.1.so` or `/usr/lib64/libm.so`?

**Comment by TheChymera** [comment]
@blowekamp thank you, that solved this issue :)
However there is another follow-up issue: https://github.com/SimpleITK/SimpleITK/issues/1348
