### ISSUE TITLE
Error in reading NRRD images in python using SimpleITK package

### ISSUE THREAD

**Issue by vikram-sreedhar** [SimpleITK/SimpleITK#1350]
I am working on a image segmentation question. I am trying to load the nrrd format images and getting the following errors. What am I doing wrong? My code is shown below.

`import cv2
import numpy
import glob
import nrrd
from matplotlib import pyplot as plt
import SimpleITK as sitk
print(sitk.__version__)
`
`mylist =[]
        laendo_nrrdextns = ['*laendo.nrrd']
        for file in [glob.glob('D:/Training Set' + '/**/'+ z, recursive=True) for z in laendo_nrrdextns]:
               a=sitk.ReadImage(file)
               mylist.append(a)
`
I tried modifying the code with

` mylist =[]
    laendo_nrrdextns = ['*laendo.nrrd']
    for file in [glob.glob('D:/Training Set' + '/**/'+ z, recursive=True) for z in laendo_nrrdextns]:
          a=sitk.Show(sitk.ReadImage(file))
          mylist.append(a)
`

But I get error in both the codes on execution as below

RuntimeError: Exception thrown in SimpleITK ImageSeriesReader_Execute: d:\a\1\sitk-build\itk-prefix\include\itk-5.1\itkImageSeriesReader.hxx:356:
itk::ERROR: itk::ERROR: ImageSeriesReader(0000017F690AC2E0): Size mismatch! The size of  D:/Training Set\1D7CUD1955YZPGK8XHJX\1D7CUD1955YZPGK8XHJX_laendo.nrrd is [640, 640, 88, 1] and does not match the required size [576, 576, 88, 1] from file D:/Training Set\06SR5RBREL16DQ6M8LWS\06SR5RBREL16DQ6M8LWS_laendo.nrrd

What am I doing wrong?  Kindly help.

**Comment by zivy** [comment]
Hello @vikram-sreedhar,

You have two bugs in your code:

1. Your usage of glob returns a list of lists. As a result you are calling the `sitk.ReadImage` with a list of file names (the variable `file` is actually a list. The read interprets this as a set of slices to read into a volume. In practice they are a set of volumes which should be read separately. When reading a set of slices they are expected to have the same dimensions (the error you see).
2. The `sitk.Show()` method does not return a value, so the assignment `a=sitk.Show(...)` will set `a` to `None`. You should do something like:
```
mylist.append(sitk.ReadImage(file)) # file is a single image file name
sitk.Show(mylist[-1])
```

**Comment by vikram-sreedhar** [comment]
Thanks.  I did try as per your suggestions but i still get the following error code on two iterations.

`mylist =[ ]`
`laendo_nrrdextns = ['*laendo.nrrd']`
`for file in [glob.glob('D:/Phd LJMU/2018 AF Challenge/Training Set' + '/**/'+ z, recursive=True) for z in laendo_nrrdextns]:
       mylist.append(sitk.ReadImage(file))`

I get below error message, 

RuntimeError                              Traceback (most recent call last)
<ipython-input-179-d324f7e97625> in <module>
      2 laendo_nrrdextns = ['*laendo.nrrd']
      3 for file in [glob.glob('D:/Phd LJMU/2018 AF Challenge/Training Set' + '/**/'+ z, recursive=True) for z in laendo_nrrdextns]:
----> 4        mylist.append(sitk.ReadImage(file))
      5 

~\Anaconda3\envs\tf-gpu1\lib\site-packages\SimpleITK\extra.py in ReadImage(fileName, outputPixelType, imageIO)
    344     reader.SetImageIO(imageIO)
    345     reader.SetOutputPixelType(outputPixelType)
--> 346     return reader.Execute()
    347 
    348 

~\Anaconda3\envs\tf-gpu1\lib\site-packages\SimpleITK\SimpleITK.py in Execute(self)
   5723         SetScale(ScaleTransform self, VectorDouble params)
   5724 
-> 5725 
   5726         """
   5727         return _SimpleITK.ScaleTransform_SetScale(self, params)

RuntimeError: Exception thrown in SimpleITK ImageSeriesReader_Execute: d:\a\1\sitk-build\itk-prefix\include\itk-5.1\itkImageSeriesReader.hxx:356:
itk::ERROR: itk::ERROR: ImageSeriesReader(0000017F690ABB60): Size mismatch! The size of  D:/Phd LJMU/2018 AF Challenge/Training Set\1D7CUD1955YZPGK8XHJX\1D7CUD1955YZPGK8XHJX_laendo.nrrd is [640, 640, 88, 1] and does not match the required size [576, 576, 88, 1] from file D:/Phd LJMU/2018 AF Challenge/Training Set\06SR5RBREL16DQ6M8LWS\06SR5RBREL16DQ6M8LWS_laendo.nrrd


I did other iteration on code which is like below

`mylist =[ ]`
`laendo_nrrdextns = ['*laendo.nrrd']`
`for file in [glob.glob('D:/Phd LJMU/2018 AF Challenge/Training Set' + '/**/'+ z, recursive=True) for z in laendo_nrrdextns]:
       mylist.append(sitk.ReadImage(file))`
      `sitk.Show(mylist[-1])`

I get below error

RuntimeError                              Traceback (most recent call last)
<ipython-input-181-969d696582dc> in <module>
      2 laendo_nrrdextns = ['*laendo.nrrd']
      3 for file in [glob.glob('D:/Phd LJMU/2018 AF Challenge/Training Set' + '/**/'+ z, recursive=True) for z in laendo_nrrdextns]:
----> 4        mylist.append(sitk.ReadImage(file))
      5        sitk.Show(mylist[-1])

~\Anaconda3\envs\tf-gpu1\lib\site-packages\SimpleITK\extra.py in ReadImage(fileName, outputPixelType, imageIO)
    344     reader.SetImageIO(imageIO)
    345     reader.SetOutputPixelType(outputPixelType)
--> 346     return reader.Execute()
    347 
    348 

~\Anaconda3\envs\tf-gpu1\lib\site-packages\SimpleITK\SimpleITK.py in Execute(self)
   5723         SetScale(ScaleTransform self, VectorDouble params)
   5724 
-> 5725 
   5726         """
   5727         return _SimpleITK.ScaleTransform_SetScale(self, params)

RuntimeError: Exception thrown in SimpleITK ImageSeriesReader_Execute: d:\a\1\sitk-build\itk-prefix\include\itk-5.1\itkImageSeriesReader.hxx:356:
itk::ERROR: itk::ERROR: ImageSeriesReader(0000017F690AC160): Size mismatch! The size of  D:/Phd LJMU/2018 AF Challenge/Training Set\1D7CUD1955YZPGK8XHJX\1D7CUD1955YZPGK8XHJX_laendo.nrrd is [640, 640, 88, 1] and does not match the required size [576, 576, 88, 1] from file D:/Phd LJMU/2018 AF Challenge/Training Set\06SR5RBREL16DQ6M8LWS\06SR5RBREL16DQ6M8LWS_laendo.nrrd

I am sorry, but what I am doing wrong now?

**Comment by zivy** [comment]
Hello @vikram-sreedhar,

The problem is that you are giving the read function a list of file names instead of a single file name. You have a bug in your standard Python globbing code, nothing related to SimpleITK.  Make sure to only provide a single nrrd file name to the read function.

**Comment by vikram-sreedhar** [comment]
Thanks.  I have tried reading single file and it works.  But how do I read multiple nrrd files.  I am looping the same way we loop jpeg and png files in opencv.  But this is not working.

**Comment by zivy** [comment]
Hello @vikram-sreedhar,

Unfortunately this is a bug in your regular Python code (usage of glob) that you will have to debug on your own. This is not related to SimpleITK.
