### ISSUE TITLE
Python Simple ITK Resample and Convert DICOM to Common Image Formats

### ISSUE THREAD

**Issue by charlotte10170** [SimpleITK/SimpleITK#1352]
Hi everyone, 
I'm trying to use this example code (https://simpleitk.readthedocs.io/en/master/link_DicomConvert_docs.html)  for reading and manipulating a sequence of Dicom images which I stored into a folder on my computer. I can't understand how or where to add my folder path in order to get python to run this code for my images.  
Can anyone help me? 
Thanks in advance

**Comment by zivy** [comment]
Hello @charlotte10170,

To understand what parameters the program is expecting run (will print all options):
```
python DicomConvert.py -h
```

To run with minimal settings, input directory name is "input/" convert to "png" format:
```
python DicomConvert.py input/ png
```

The program uses the [argparse](https://docs.python.org/3/library/argparse.html) module to parse the commandline.
