### ISSUE TITLE
Resize nii images to the same pixel size size

### ISSUE THREAD

**Issue by SouthAmericaB** [SimpleITK/SimpleITK#1355]
HI!
I have several nii images of different matrix and pixel sizes.
I would like to achieve that all the images have the same matrix dimensions and pixel size. For example, a matrix dimensions of 256x256 and a pixel size of 0.42x0.42.

My doubt is: are there some simpleitk function to achieve it? Or maybe I should to normalize all the images to the same pixel size and then crop them to the same matrix dimensions? 

Thank you very much!

**Comment by zivy** [comment]
Hello @SouthAmericaB,

What you are looking for is the `Resample` function, but to get the effect you want you need to set its parameters correctly. 

Please take a look at the [Transforms and Resampling Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/21_Transforms_and_Resampling.ipynb) section beginning with "Creating thumbnails". Also relevant is the [Data Augmentation notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/70_Data_Augmentation.ipynb).
