### ISSUE TITLE
Errors when building SimpleITK on aarch64

### ISSUE THREAD

**Issue by aletru01** [SimpleITK/SimpleITK#1359]
Hi,

I've been trying to build SimpleITK on aarch64 following this: https://simpleitk.readthedocs.io/en/master/building.html
But I have these errors when I build with Superbuild. How can I solve this issue ?
It also happens when I run: pip install git+https://github.com/SimpleITK/SimpleITKPythonPackage.git -v --no-use-pep517
from https://github.com/SimpleITK/SimpleITKPythonPackage

../../../../lib/libitkpng-5.2.a(pngrtran.c.o):pngrtran.c:function itk_png_do_read_transformations: error: undefined reference to 'itk_png_do_expand_palette_rgba8_neon'
../../../../lib/libitkpng-5.2.a(pngrtran.c.o):pngrtran.c:function itk_png_do_read_transformations: error: undefined reference to 'itk_png_riffle_palette_neon'
../../../../lib/libitkpng-5.2.a(pngrtran.c.o):pngrtran.c:function itk_png_do_read_transformations: error: undefined reference to 'itk_png_do_expand_palette_rgb8_neon'
../../../../lib/libitkpng-5.2.a(pngrutil.c.o):pngrutil.c:function itk_png_read_filter_row: error: undefined reference to 'itk_png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
Modules/Core/TestKernel/src/CMakeFiles/itkTestDriver.dir/build.make:163: recipe for target 'bin/itkTestDriver' failed
make[5]: *** [bin/itkTestDriver] Error 1
CMakeFiles/Makefile2:16052: recipe for target 'Modules/Core/TestKernel/src/CMakeFiles/itkTestDriver.dir/all' failed
make[4]: *** [Modules/Core/TestKernel/src/CMakeFiles/itkTestDriver.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/ITK.dir/build.make:111: recipe for target 'ITK-prefix/src/ITK-stamp/ITK-build' failed
make[2]: *** [ITK-prefix/src/ITK-stamp/ITK-build] Error 2
CMakeFiles/Makefile2:360: recipe for target 'CMakeFiles/ITK.dir/all' failed
make[1]: *** [CMakeFiles/ITK.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Thanks

**Comment by seth-priya** [comment]
Hi @aletru01 I was facing a similar issue on ppc64le. running cmake with
cmake -DITK_USE_SYSTEM_PNG:BOOL=ON -DBUILD_TESTING:BOOL=ON ../SimpleITK/SuperBuild/

helped but I am seeing two test failures which I just created an issue for, those seem unrelated to the use of SYSTEM_PNG though

**Comment by aletru01** [comment]
Hi @seth-priya, the build is successful on aarch64 with your command.
Thanks
