### ISSUE TITLE
Converting .nrrd segmentations to nifti

### ISSUE THREAD

**Issue by Hball99** [SimpleITK/SimpleITK#1363]
I have 200+ CT-Volume Files with matching segmentations. The Volumes are in .nrrd format and the segmentations are in seg.nrrd format. I need both of those as .nii.gz format and I want to script the conversion from one into the other format.

Regarding the Volumes, everything has been quite easy, using sitk:

import SimpleITK as sitk

img = sitk.ReadImage(“your_image.nrrd”) 
sitk.WriteImage(img, “your_image.nii.gz”)

I just did the same thing with the segmenations, too, which worked fine at first glance. But the problem is now that the segmentations are not registered with the Volumes anymore. The image dimensions as well as image origins are not the same anymore and thus, I cannot process the converted images.

The same happens, when I do the following manual steps with 3D-Slicer : 1. Load the .seg.nrrd files into Slicer as Segementation 2. Save the segmentation as .nrrd file instead of seg.nrrd 3. Import the .nrrd file as Volume and save the segmentation as .nii.gz

But I figured out a way to convert the data types manually while keeping all dimensions: 1. Import the Volume as well as the corresponding segmentation (.seg.nrrd) 2. Export the segmentation to a labelmap with reference volume set to my corresponding volume 3. Save the Labelmap as nii.gz (4. Not sure if I need that step for my project: Convert Labelmap to Scalar Volume and safe as nii.gz)

In both cases 3. and 4. I have a nii.gz file with matching dimensions. But since I have 200+ Volumes, I need to script that. But I haven’t found anything so far. Do you have any ideas? Thanks!

**Comment by dave3d** [comment]
Assuming the segments and the images were matching all meta information as NRRD files, there's no reason that would change in writing Nifti.  Is it possible the segmentations are just a subsection of the CT images?  Can you share an example dataset that we can take a look at?

**Comment by Hball99** [comment]
I am afraid that I cannot share an example data-set since those are patient data.. But can I look something up without sharing the data that could help?

**Comment by dave3d** [comment]
I would print out all the meta information (dimensions, spacing, direction, origin) for your CT image and segmentation in the original NRRD and the converted Nifti and see if there's any disparity.

How are you creating the segmentations?  Slicer?  Sometimes there are coordinate system issues in going from Slicer to other platforms.  Slicer uses the LPS (Left, Posterior, Superior) coordinate system, while ITK/SimpleITK uses RAS (Right, Anterior, Superior).  You can read about it here:  https://www.slicer.org/wiki/Coordinate_systems
