### ISSUE TITLE
Zero padding an image based on position in "image space"

### ISSUE THREAD

**Issue by TereseH** [SimpleITK/SimpleITK#1364]
Hi!
I am trying to reshape a 3D image to the size of another 3D image by zeropadding to different extents in different directions. I started making a script to do this using numpy and DICOM tags but I feel like there would be a better way to do it using SimpleITK as I want to be sure that the position of the 3D image data is in the same position with respect to the other 3D image. Here is an illustration of the idea. 
[
<img width="711" alt="zero_padding_illustration" src="https://user-images.githubusercontent.com/80116570/113294930-caaf5e00-92f7-11eb-9abd-e1047a626fdc.png">
](url)

So my question is: What would be the best way to do this using SimpleITK?

**Comment by dave3d** [comment]
I'd create a blank image the size of image1, and then use the Paste function to paste image2 into that blank image.

**Comment by zivy** [comment]
Hello @TereseH,

You are looking for [ConstantPadImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ConstantPadImageFilter.html), as shown here:
```
import SimpleITK as sitk

# Image with constant value of 10
img = sitk.Image([8,8], sitk.sitkUInt16) + 10

# Pad it with constant value of 32
padded = sitk.ConstantPad(img, padLowerBound = [2,4], padUpperBound = [8,16], constant = 32)

# See that the original image is in the same physical location in the padded version.
print(img.GetOrigin())
print(img.GetSpacing())

print(padded.GetOrigin())
print(padded.GetSpacing())
```

**Comment by blowekamp** [comment]
I'd use the building sitk::Image indexing operator to paste:
```
zeroImage = sitk.Image([new_xsize, new_ysize], sitk.sitkUInt8) #initialized to zero
zeroImage[xpos:xpos+img_size, ypos:ypos+img_size] = img
```

Internally this will use the paste image filter, but with a more pythonic interface. I don't recall the constraints of the meta-data matching for the PasteImageFilter. the zeroImage may need to has additional metadata set.

If you want to preserve everything from the original Image ( the origin and size will of course change ), then @zivy approach would be best/easiest.

**Comment by TereseH** [comment]
Okay, do you think there might be a way to do it without specifying how much I should padd with on each side, that there would be some way to match two images together?

**Comment by zivy** [comment]
@blowekamp's code snippet does what you want. If you do care about the physical location you just need to add one more line:
```
zeroImage = sitk.Image(image1.GetSize(), sitk.sitkUInt8) #initialized to zero
# ensure that zeroImage is in the same physical location as image1
zeroImage.CopyInformation(image1)
img_size = img.GetSize()
zeroImage[xpos:xpos+img_size, ypos:ypos+img_size] = img
```

**Comment by TereseH** [comment]
> @blowekamp's code snippet does what you want. If you do care about the physical location you just need to add one more line:


Hi thank you for the help. I tried the code you sent but I got an error saying the sizes were wrong. The size of image2 is (261, 112) but it seems to say it is [195, 12]. Did I use the code how you intended?

```
zeroImage = sitk.Image(image1.GetSize(), sitk.sitkUInt8)  # initialized to zero
# ensure that zeroImage is in the same physical location as image1
zeroImage.CopyInformation(image1)
img2_size = image2.GetSize()
xpos, ypos= np.around(image2.GetOrigin()).astype(int)
zeroImage[xpos:(xpos + img2_size[0]), ypos:(ypos + img2_size[1])] = image2
```
```
Error message: IndexError: cannot paste source with size [195, 12] into destination with size (261, 112)
```

**Comment by zivy** [comment]
Hello @TereseH,

Your `xpos, ypos` assignment is incorrect. The origin of an image is its spatial origin in the physical world and what you need to use for `xpos, ypos` are indexes. If you want to paste at location [0,0], then just set to that:
```
xpos = ypos = 0
```

**Comment by TereseH** [comment]
@zivy 
Okay I understand, so then I would need to find the offset in the origin of image 1 and 2 and use that for xpos and ypos?

**Comment by zivy** [comment]
Hello @TereseH,

To paste `image2` in a specific location with respect to image1's coordinate system you need to have the indexes `xpos,ypos`. You either have these indexes directly or if you have the physical coordinates, you obtain the indexes from calling `image1.TransformPhysicalPointToContinuousIndex((xpos_physical,ypos_physical))`.

**Comment by TereseH** [comment]
Thank you for all the help! I managed to do it now.
