### ISSUE TITLE
Exception thrown in SimpleITK Show..  Python, Windows. Issue in function of sitk.Show

### ISSUE THREAD

**Issue by WenhongLan** [SimpleITK/SimpleITK#1365]
I have a question on running the simpleITK with Fiji. There is an error on the function of sitk.Show:
Exception thrown in SimpleITK Show: D:\a\1\sitk\Code\IO\src\sitkImageViewer.cxx:562:
sitk::ERROR: Error in administrating child process: [The system cannot find the file specified].

I followed the installation guideline absolutely and put the Fiji.app in the specific path required. But it still does not work.
My system is Windows 10 1909. 
Simple ITK 2.0.2 in Python 3.9 in windows.
Fiji version is ImageJ  1.53c

**Comment by zivy** [comment]
Please follow the [FAQ on this subject](https://simpleitk.readthedocs.io/en/latest/faq.html#why-isn-t-imagej-found-by-the-show-function-runtimeerror-exception-thrown) and see if the function is indeed searching in the location where you installed Fiji.

**Comment by WenhongLan** [comment]
Thanks for your reply. I put the Fiji in the path describing on the F&Q C:\...Users\XXX\Fiji.app. But it still does not work.

**Comment by dave3d** [comment]
Can you see the debugOn parameter to True and show us the output?

**Comment by WenhongLan** [comment]
I

> Can you see the debugOn parameter to True and show us the output?

I set the debugOn=True  : sitk.Show(img, debugOn=True) Then, the output is:
>>
Traceback (most recent call last):
  File "F:\software\ima_regi.py", line 19, in <module>
    sitk.Show(img, debugOn=True)
  File "C:\Users\lanwe\AppData\Roaming\Python\Python39\site-packages\SimpleITK\SimpleITK.py", line 5425, in Show
    return _SimpleITK.Show(*args, **kwargs)
RuntimeError: Exception thrown in SimpleITK Show: D:\a\1\sitk\Code\IO\src\sitkImageViewer.cxx:562:
sitk::ERROR: Error in administrating child process: [The system cannot find the file specified].
Command line: 'C:\blah\blah\ImageJ\ImageJ.exe' 'C:\\Users\\lanwe\\AppData\\Local\\Temp\\TempFile-8784-0.mha'

My Fiji location is C:\Users\lanwe\Fiji.app

But I do not know where is the problem.

**Comment by dave3d** [comment]
what happens and you just copy and paste that command line into a shell to try and run it by hand?

**Comment by WenhongLan** [comment]
> what happens and you just copy and paste that command line into a shell to try and run it by hand?

Sorry I have not explained it clearly.

**I write a small .py script. the code is below:**

import SimpleITK as sitk
import os
#---------------------------------
# generate the pathway to the data
#---------------------------------
index_volter = '4' # index of the volunteer
index_case = '1' # index of the scanning

temp_volter = 'volunteer ' + index_volter
temp_case = 'case ' + index_case
path1=os.path.abspath('.')
temp_path= os.path.join(path1,'data',temp_volter,'raw data',temp_case,'MR images','navigator','')

file_list = os.listdir(temp_path) # this is the list of the file name.

fixed_ima = os.path.join(temp_path,file_list[0])
img = sitk.ReadImage(fixed_ima) # variable of the fixed image based on dicom
sitk.Show(img, debugOn=True)

**Then, I run it at Vs Code terminal as PS F:\software> python .\ima_regi.py**
There are several warning and errors, which are presented below: 

WARNING: In D:\a\1\sitk-build\ITK\Modules\IO\Meta\src\itkMetaImageIO.cxx, line 669
MetaImageIO (0000020688C62330): Unsupported or empty metaData item 0008|0050 of type class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >found, won't be written to image file

WARNING: In D:\a\1\sitk-build\ITK\Modules\IO\Meta\src\itkMetaImageIO.cxx, line 669
MetaImageIO (0000020688C62330): Unsupported or empty metaData item 0008|0090 of type class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >found, won't be written to image file

WARNING: In D:\a\1\sitk-build\ITK\Modules\IO\Meta\src\itkMetaImageIO.cxx, line 669
MetaImageIO (0000020688C62330): Unsupported or empty metaData item 0008|1050 of type class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >found, won't be written to image file

WARNING: In D:\a\1\sitk-build\ITK\Modules\IO\Meta\src\itkMetaImageIO.cxx, line 669
MetaImageIO (0000020688C62330): Unsupported or empty metaData item 0020|1040 of type class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >found, won't be written to image file

WARNING: In D:\a\1\sitk-build\ITK\Modules\IO\Meta\src\itkMetaImageIO.cxx, line 669
MetaImageIO (0000020688C62330): Unsupported or empty metaData item 0040|0280 of type class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >found, won't be written to image file

Debug: In D:\a\1\sitk\Code\IO\src\sitkImageViewer.cxx, line 495: ExecuteCommand: 'C:\blah\blah\ImageJ\ImageJ.exe' 'C:\\Users\\lanwe\\AppData\\Local\\Temp\\TempFile-9468-0.mha'

Traceback (most recent call last):
  File "F:\software\ima_regi.py", line 19, in <module>
    sitk.Show(img, debugOn=True)
  File "C:\Users\lanwe\AppData\Roaming\Python\Python39\site-packages\SimpleITK\SimpleITK.py", line 5425, in Show
    return _SimpleITK.Show(*args, **kwargs)
RuntimeError: Exception thrown in SimpleITK Show: D:\a\1\sitk\Code\IO\src\sitkImageViewer.cxx:562:
sitk::ERROR: Error in administrating child process: [The system cannot find the file specified].
Command line: 'C:\blah\blah\ImageJ\ImageJ.exe' 'C:\\Users\\lanwe\\AppData\\Local\\Temp\\TempFile-9468-0.mha'
PS F:\software>

**Comment by dave3d** [comment]
OK, so it looks like it didn't properly write the temporary image out.  'img' is supposed to be written out as a MetaIO image at  'C:\Users\lanwe\AppData\Local\Temp\TempFile-9468-0.mha', but that image does not seem to be there.

**Comment by WenhongLan** [comment]
> OK, so it looks like it didn't properly write the temporary image out. 'img' is supposed to be written out as a MetaIO image at 'C:\Users\lanwe\AppData\Local\Temp\TempFile-9468-0.mha', but that image does not seem to be there.

I have checked the Temp file and the image file is there. But the Fiji does not automated work. And I do not know why.

**Comment by dave3d** [comment]
I don't think it's finding ImageJ.  Your command line says: Command line: 'C:\blah\blah\ImageJ\ImageJ.exe' 'C:\Users\lanwe\AppData\Local\Temp\TempFile-8784-0.mha'

Why does it say "\blah\blah" for the path to ImageJ?

Here's what I get on my system:

```
>>> import SimpleITK as sitk
>>> img = sitk.Image(100,100,sitk.sitkUInt8)
>>> sitk.Show(img, debugOn=True)
Debug: In C:\SimpleITK\Code\IO\src\sitkImageViewer.cxx, line 495: ExecuteCommand: 'C:/Users/dchen/Fiji.app/ImageJ-win64.exe' '-eval' 'open("C:\\Users\\dchen\\AppData\\Local\\Temp\\TempFile-9588-0.mha"); rename("C:\\Users\\dchen\\AppData\\Local\\Temp\\TempFile-9588-0.mha");'
```

You should be able to copy everything after "ExecuteCommand", paste it into a shell and run it by had.  That is exactly what SimpleITK is doing.

**Comment by WenhongLan** [comment]
> I don't think it's finding ImageJ. Your command line says: Command line: 'C:\blah\blah\ImageJ\ImageJ.exe' 'C:\Users\lanwe\AppData\Local\Temp\TempFile-8784-0.mha'
> 
> Why does it say "\blah\blah" for the path to ImageJ?
> 
> Here's what I get on my system:
> 
> ```
> >>> import SimpleITK as sitk
> >>> img = sitk.Image(100,100,sitk.sitkUInt8)
> >>> sitk.Show(img, debugOn=True)
> Debug: In C:\SimpleITK\Code\IO\src\sitkImageViewer.cxx, line 495: ExecuteCommand: 'C:/Users/dchen/Fiji.app/ImageJ-win64.exe' '-eval' 'open("C:\\Users\\dchen\\AppData\\Local\\Temp\\TempFile-9588-0.mha"); rename("C:\\Users\\dchen\\AppData\\Local\\Temp\\TempFile-9588-0.mha");'
> ```
> 
> You should be able to copy everything after "ExecuteCommand", paste it into a shell and run it by hand. That is exactly what SimpleITK is doing.

Thank you for reply. I think I found the issue now. Thank you very much.
