### ISSUE TITLE
How to use Write Image function to write a file and save it in a variable rather than a directory in python?

### ISSUE THREAD

**Issue by rvadhith** [SimpleITK/SimpleITK#1373]
I am trying to convert png/jpeg files to dicom format. I am using SITK library for the process. While writing the file to dicom, I have been so far writing to a file directory by specifying the path. May I please know is it possible to write the file and store it in a variable. Just wanted to show the piece of code where I am trying to write to a path

```
dicom_filename = nondcm_file_name + '.dcm'
dicom_path = os.path.join(output_dir, dicom_filename)
sitk.WriteImage(image_slice, dicom_path)
return dicom_path
```

This piece of code is a part of method which I used to convert non dicom images to dicom. The nondcm_file_name variable stores the name of non dicom file. output_dir variable specifies the directory path where I want to write the dicom files. The image_slice variable contains all the dicom tags and pixel data before conversion. Once after conversion I have been accessing the files from the output_dir path. Please suggest me how can I avoid writing to directories and rather store it in a variable and return the file

**Comment by zivy** [comment]
Hello @rvadhith,

Not sure what it is you are trying to achieve. The motivation for writing a file to disk in a specific format, DICOM in this case, and immediately reading it back into memory is not clear.

Possibly consider using Python's [tempfile module](https://docs.python.org/3/library/tempfile.html)?
