### ISSUE TITLE
sitk.transformix()

### ISSUE THREAD

**Issue by XXZhou25** [SimpleITK/SimpleITK#1381]
Hi, 
May I know how to install simpleitk 1.0+? 
Since I used to use sitk.transformix() to transform point sets, but now I can only install simpleitk 2.0+ from pip install/conda install. 

It seems in simpleitk 2.0+ I cannot find any of these functions: 

>>> import SimpleITK as sitk
>>> sitk.TransformixImageFilter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'SimpleITK' has no attribute 'TransformixImageFilter'
>>> sitk.SimpleTransformix()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'SimpleITK' has no attribute 'SimpleTransformix'
>>> sitk.ElastixImageFilter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'SimpleITK' has no attribute 'ElastixImageFilter'
>>> sitk.SimpleElastix()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'SimpleITK' has no attribute 'SimpleElastix' 

I will appreciate if you could point out how I can transform point sets with this new version of simpleitk. Thanks.
Or how to degrade back to sitk 1.0+? 
i tried pip install simpleitk==1.0 it just cannot find this version. 
Thanks!

**Comment by blowekamp** [comment]
You are using SimpleElastix. This is the repository you are looking for: https://github.com/SuperElastix/SimpleElastix
