### ISSUE TITLE
SITK fails while reading image series. sitk::ERROR: File names information is empty. Cannot read series.

### ISSUE THREAD

**Issue by theVmagnificient** [SimpleITK/SimpleITK#1386]
Greetings! I've attached file series which cannot be read by sitk. ITK-SNAP also fails on it. How it could be fixed? SITK version is 2.0.2. Also all the files can be successfully read by pydicom.
https://drive.google.com/file/d/1KpC03uSLOnDp4wAwTiTEz8ISSImVhv_X/view?usp=sharing

**Comment by zivy** [comment]
Hello @theVmagnificient,

The files are not compliant with the DICOM standard. To check compliance with the standard I use the [dciodvfy program](https://www.dclunie.com/dicom3tools/dciodvfy.html) from David Clunie. You can run the program to see the various issues with the images (e.g. `dciodvfy 12.dcm`). The GDCM image reader underlying SimpleITK is relatively strict with respect to compliance to the standard and will not read them (throws an error). 

Pydiocm is more flexible in terms of enforcing compliance with the standard, this has advantages and disadvantages.
