### ISSUE TITLE
WriteImage loses "origin" data in 4D

### ISSUE THREAD

**Issue by beathvn** [SimpleITK/SimpleITK#1394]
Hello there,

I'm using the SimpleITK package for python (version 2.0.2) and i have a series of 3D images, which I want to store in a 4D Image (first dimension is for the series, dimension 2, 3, 4 are used for the individual images-> there are 7 images of size (192, 192, 64), saved in a 4D image of size (7, 192, 192, 64)). Although it saves the image, it loses some meta data: there are no problems regarding the 'spacing' information, but for the Origin, the last value is lost and I don't understand why.

Here is a code snippet, for better understanding (joined Image is of size (7, 192, 192, 64) and seg_image of size (192, 192, 64)):

`print(seg_image.GetOrigin())`
`print(joined_image.GetOrigin())`
`print(seg_image.GetSpacing())`
`print(joined_image.GetSpacing())`

outputs:
(-94.38999938964844, 268.6099853515625, -516.0)
(0.0, -94.38999938964844, 268.6099853515625, -516.0)
(1.0, 1.0, 3.0)
(1.0, 1.0, 1.0, 3.0)

so far so good... but now i want to save this 4D image (and directly reload it to check if it saved correctly)
`sitk.WriteImage(joined_image, out_path)`
`check_image = sitk.ReadImage(out_path)`
`print(check_image.GetOrigin())`
`print(check_image.GetSpacing())`

outputs:
(0.0, -94.38999938964844, 268.6099853515625, 0.0)
(1.0, 1.0, 1.0, 3.0)

as you can see, the last value of Origin is wrong, whereas the spacing information is correct. Don't really understand where this goes wrong - hoping someone could help me.

Thanks in advance and best regards

**Comment by zivy** [comment]
Hello @beathvn,

Not sure what is going on with the images, the `joined_image.GetOrigin()` and `joined_image.GetSpacing()` are not in the expected order, should be `(-94.38999938964844, 268.6099853515625, -516.0, 0.0)` and `(1.0, 1.0, 3.0, 1.0)`. Please see the following code:
```
import SimpleITK as sitk

img = sitk.Image([192, 192, 64], sitk.sitkUInt8)
img.SetOrigin([0.7,8,90])
img.SetSpacing([0.1,2,30])
print(f'Original image origin:{img.GetOrigin()}\nOriginal image spacing:{img.GetSpacing()}')

joined_img = sitk.JoinSeries([img]*7)
print(f'Joined image origin:{joined_img.GetOrigin()}\nJoined image spacing:{joined_img.GetSpacing()}')

sitk.WriteImage(joined_img, 'joined.mha')
read_joined_img = sitk.ReadImage('joined.mha')
print(f'Joined read image origin:{read_joined_img.GetOrigin()}\nJoined read image spacing:{read_joined_img.GetSpacing()}')
```

**Comment by beathvn** [comment]
Hello @zivy,

thanks for the quick response! 
The order is actually correct in my use-case: i need this 4D image for AI training and the first dimension has to be the the one with the different channels, so in the form (7, 192, 192, 64). 
I tried using JoinSeries, which brings them in the form (192, 192, 64, 7) and than use PermuteAxes to reorder the axes, but since my images use sitkFloat32, PermuteAxes does not work:
`sitk::ERROR: Pixel type: 32-bit float is not supported in 4D by N3itk6simple22PermuteAxesImageFilterE.`

Therefore i put them manually in the correct order (seg_image is the starting point, from which I create the 7 images I want to combine in a new 4D image):
```
# generate new 4D Image, all black, to store the other images
    size = (7,) + seg_Image.GetSize()
    joined_image = sitk.Image(size, sitk.sitkFloat32)

   # going over all labels and setting the center of mass to 1
    for i in range(7):
        buffer_image = sitk.Image(seg_Image.GetSize(), sitk.sitkFloat32)
       ... 
        # setting some pixels to 1.0 in this for loop 
       ...
        joined_image[i] = buffer_image

    # set the spacing, orientation of the output image (direction default to the correct one)
    joined_image.SetSpacing((1.0, ) + seg_Image.GetSpacing())
    joined_image.SetOrigin((1.0, ) + seg_Image.GetOrigin())

    # save the image
    sitk.WriteImage(joined_image, out_path)
```

and if I now read the joined_image File, I lose the last value of 'Origin' (check my previous comment...)

**Comment by zivy** [comment]
Hello @beathvn,

Was not able to replicate the issue. Below is code that creates the 4D image in the order you wanted and everything seems fine.
```
import SimpleITK as sitk

img = sitk.Image([192, 192, 64], sitk.sitkUInt8)
img.SetOrigin([0.7,8,90])
img.SetSpacing([0.1,2,30])
print(f'Original image origin:{img.GetOrigin()}\nOriginal image spacing:{img.GetSpacing()}')


images_to_join = [img]*7

size = (len(images_to_join),) + img.GetSize()
joined_img = sitk.Image(size, img.GetPixelID())
joined_img.SetSpacing((1,) + img.GetSpacing())
joined_img.SetOrigin((0.0,) + img.GetOrigin())
img_direction = img.GetDirection()
joined_img.SetDirection(img_direction[0:3] + (0,) +
                        img_direction[3:5] + (0,) +
                        img_direction[5:9] + (0,) +
                        (0, 0, 0, 1))

for i, image_to_join in enumerate(images_to_join):
    joined_img[i,:,:,:] = images_to_join[i]
print(f'Joined image origin:{joined_img.GetOrigin()}\nJoined image spacing:{joined_img.GetSpacing()}')

sitk.WriteImage(joined_img, 'joined.mha')
read_joined_img = sitk.ReadImage('joined.mha')
print(f'Joined read image origin:{read_joined_img.GetOrigin()}\nJoined read image spacing:{read_joined_img.GetSpacing()}')

```

**Comment by beathvn** [comment]
Hello @zivy 

I tried using you code, and it works fine... but: i want to save the images in nifty format ('.nii.gz' sorry I forgot to mention that earlier) for storage reasons and this seems to cause the issue because as soon as i change .mha to nii.gz the last value of the origin information gets lost.

**Comment by zivy** [comment]
Hello @beathvn,

Based on the definitions of nifti ([nifti1](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h) and [nifti2](https://nifti.nimh.nih.gov/pub/dist/doc/nifti2.h)), it appears that the origin is only 3D as it is defined by three numbers (`srow_x[3], srow_y[3], srow_z[3]` or `qoffset_x, qoffset_y, qoffset_z`). It doesn't look like nifti supports a 4D origin. I could be wrong here, so I'd recommend asking on the [nifti forum](https://www.nitrc.org/forum/forum.php?forum_id=1941).

If what you need is the compression offered by nifti, you could use the `nrrd` format and set the `WriteImage`'s `useCompression` variable to `True`.

**Comment by beathvn** [comment]
Hello @zivy 

ah yes I didn't check that beforehand. 

Thanks for your help!
