### ISSUE TITLE
Create new Python package for SimpleITK utilities and contributions

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#1398]

**Comment by blowekamp** [comment]
The package should contain utilities to convert to vtk images. Maybe the slice by slice decorators. Also some useful utilities from the SimpleITKNotebooks.

**Comment by zivy** [comment]
Look into creating this package when we have a list of about 10 classes/functions:
1. Get VTK image from SimpleITK image.
2. Slice by slice decorator [code in example](https://simpleitk.readthedocs.io/en/master/link_SliceBySliceDecorator_docs.html).
3. Logger adaptor [code example](https://simpleitk.readthedocs.io/en/master/link_Logging_docs.html).
4. Standardize image, make it isotropic with standard axes `make_isotropic` function in [this notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/05_Results_Visualization.ipynb).
5. Alpha blending with masks (not sure about this one), [this notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/05_Results_Visualization.ipynb).

**Comment by dave3d** [comment]
My SITK <-> VTK routines are here:
https://github.com/dave3d/dicom2stl/tree/main/utils

**Comment by josetascon** [comment]
The numpy solution is nice for SITK <-> vtk but is there a plan to have a built-in function similar to [ITK python](https://itkpythonpackage.readthedocs.io/en/master/Quick_start_guide.html#itk-and-vtk) that probably use [ITKVtkGlue](https://github.com/InsightSoftwareConsortium/ITKVtkGlue)?. @blowekamp @dave3d

**Comment by blowekamp** [comment]
@josetascon I don't believe that ITK python uses ITKVtkGlue. Using that ITK module would require tight coupling with the VTK library. That is it would require ITK to be built against and linked to a specific version of VTK.

We have talked about creating a pure python package(s) to help convert SimpleITK to other packages' data structures. That is the topic of this issue.

**Comment by blowekamp** [comment]
This SimpleITK "utilities" package(s) could contain a set of [namespace](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) packages. Where the third party dependencies are specified as in the separate namespace packages. For example simpleitk-utils-vtk, would have the dependency of the vtk python library.

**Comment by blowekamp** [comment]
The initial repository for the package has been created: https://github.com/SimpleITK/SimpleITKUtilities

**Comment by blowekamp** [comment]
The remaining "features" to add should be added as GH issues in the SimpleITKUtilities repository.

**Comment by zivy** [comment]
Added to the new repo as [an issue](https://github.com/SimpleITK/SimpleITKUtilities/issues/2).
