### ISSUE TITLE
Make Testing a standalone CMake project

### ISSUE THREAD

**Issue by ghisvail** [SimpleITK/SimpleITK#140]
As a follow-up from the discussion in #92, I am opening this issue to request the test suite to be usable as a standalone CMake project. This would allow testing to be carried out on packaged binaries for SimpleITK, such as the ones provided by the future Debian packaging. Other distribution mechanism could benefit from this feature as well (`conda` for instance).

**Comment by blowekamp** [comment]
This is a been a too low of a priority.
