### ISSUE TITLE
How to Transformix: Optimize registration on downsampled image and use transformations on full resolution image ?

### ISSUE THREAD

**Issue by JLrumberger** [SimpleITK/SimpleITK#1401]
Hey all,

first of all, thanks for building and maintaining this library, it really is a great tool. My question is fairly simple, I have two images per modality (HE, IF), a downsampled version with 1/4 the resolution (e.g. `IF_itk_x4`) and a full resolution version `IF`. I optimize registration parameters on the downsampled image like this:

`elastixImageFilter = sitk.ElastixImageFilter()`
`elastixImageFilter.SetFixedImage(HE_itk_x4)`
`elastixImageFilter.SetMovingImage(IF_itk_x4)`
`elastixImageFilter.SetParameterMap(params["affine"])`
`elastixImageFilter.AddParameterMap(params["nl"])`
`transformedNewImage = elastixImageFilter.Execute()`

Then I'll get the found parameters and change the size to my desired output size (the size of the fixed image):
`transformParameterMapVector = elastixImageFilter.GetTransformParameterMap()`
`transformParameterMapVector[0]['Size'] = tuple([str(element) for element in HE.GetSize()])`
`transformParameterMapVector[1]['Size'] = tuple([str(element) for element in HE.GetSize()])`

and apply it via Transformix
`res = sitk.Transformix(IF, transformParameterMapVector)`

The resulting registration looks okay, but certainly way worse when compared to the registered version of `IF_itk_x4` without changing any parameters in `transformParameterMapVector`. So I need to rescale more parameters in `transformParameterMapVector`, can you help me which of them do it need to change and how?

Best
Lorenz

**Comment by zivy** [comment]
Hello @JLrumberger,

You are using SimpleElastix, not SimpleITK. SimpleElastix is based SimpleITK but is a different tool. Unfortunately, that toolkit added on top of SimpleITK without changing the toolkit package name.

The SimpleElastix issue tracker can be [found here](https://github.com/SuperElastix/SimpleElastix/issues).
