### ISSUE TITLE
`SetReferenceImage` method unavailable for `HistogramMatchingImageFilter` class

### ISSUE THREAD

**Issue by function2-llx** [SimpleITK/SimpleITK#1402]
`SetReferenceImage` is available for the `HistogramMatchingImageFilter` class in itk ([related doc](https://itk.org/Doxygen/html/classitk_1_1HistogramMatchingImageFilter.html#a029b304c69977ad9b7c018614d64fba2)), but not available in SimpleITK ([related doc](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1HistogramMatchingImageFilter.html)).

Is there any plan to add support for this? Thanks!

**Comment by blowekamp** [comment]
Hello,

The "ReferenceImage" is the second input image for the filter, so it is the second parameter for the `Execute` method. In SimpleITK filter "inputs" are arguments to the `Execute` method, while filter parameters have the set/get accessor methods.

For this filter the second parameter name should be changed from "image2" to "referenceImage".

**Comment by function2-llx** [comment]
@blowekamp Hello, thanks for the reply.

I understand that the `ReferenceImage` corresponds to the second parameter for the `Execute`. But what I'm concerning is the execution efficiency. I'm going to match multiple images while there's only one fixed reference chosen previously. Though I didn't check the implementation, it's possible that the instance may do some pre-proecssing on the reference image if there's an interface of `SetReferenceImage`  available.

**Comment by blowekamp** [comment]
What is the phrase: "premature optimization is the root of evil"?

The underlying implementation is multi-threaded C++ and is reasonable fast. The general best practice is to get a working implantation, verify results, set performance goals, analyze for bottle necks, the optimize those areas that would see the most benefit.
