### ISSUE TITLE
Document details of metric sampling strategies

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#1409]
In the doxygen member/enum documentation in the ImageRegistrationMethod, details about the different sampling strategies should written. This should include that even with the None/Regular strategies, the sample point are randomly perturbed.

**Comment by zivy** [comment]
This requires a bit of a longer "discussion" so not 100% sure if doxygen is the place, or should it go on the read-the-docs registration page. So rtd or doxygen?

**Comment by blowekamp** [comment]
Both? There is nothing in the doxygen documentation. A sentence or so about each would be useful in Doxygen. Extended prose could be added to RTD too.
