### ISSUE TITLE
ComputeJacobianWithRespectToPosition not yet implemented for BSplineTransform

### ISSUE THREAD

**Issue by ctorti** [SimpleITK/SimpleITK#1415]
Hello,

I originally posted this as a question [here](https://discourse.itk.org/t/using-landmarkbasedtransforminitializer-for-bspline-registrations/4096/8) but it was a follow up question from the original post.  I thought it useful to post as a sole "issue" and leave out the rest.

I get the following error when trying to perform a bspline registration with initialisation with `LandmarkBasedTransformInitializer` in the ITKv4 framework:

> Exception thrown in SimpleITK ImageRegistrationMethod_Execute: d:\a\1\sitk-build\itk-prefix\include\itk-5.1\itkImageToImageMetricv4GetValueAndDerivativeThreaderBase.hxx:268:
> Exception in GetValueAndDerivativeProcessPoint:
> d:\a\1\sitk-build\itk-prefix\include\itk-5.1\itkBSplineBaseTransform.h:302:
> itk::ERROR: itk::ERROR: BSplineTransform: ComputeJacobianWithRespectToPosition not yet implemented for BSplineTransform

I'm using SimpleITK v 2.0.2 and the method is as follows:

```
def BsplineRegWithFiducials(FixIm, MovIm, FixPts, MovPts,
                            NumControlPts=8, SamplingPercentage=5, 
                            LearningRate=5.0, NumIters=100):
    
    import SimpleITK as sitk
    import numpy as np
    from ipywidgets import interact, fixed

    dim = FixIm.GetDimension()

    # Get landmark transform:
    LandmarkTx = sitk.LandmarkBasedTransformInitializer(transform=sitk.BSplineTransform(dim), 
                                                        fixedLandmarks=FixPts, 
                                                        movingLandmarks=MovPts,
                                                        referenceImage=FixIm,
                                                        numberOfControlPoints=4)
  
    SamplingPercentage = SamplingPercentage/100

    ScaleFactors = [1, 2, 4]
    
    MeshSize = [NumControlPts // ScaleFactors[-1]] * dim
    
    OptimizedTx = sitk.BSplineTransformInitializer(image1=FixIm,
                                                   transformDomainMeshSize=MeshSize)
    
    RegMethod = sitk.ImageRegistrationMethod()
    
    # Set the initial moving and optimized transforms in ITKv4
    RegMethod.SetMovingInitialTransform(LandmarkTx)
    RegMethod.SetInitialTransformAsBSpline(OptimizedTx, inPlace=True, 
                                           scaleFactors=ScaleFactors)
    # Also tried:
    # RegMethod.SetInitialTransform(OptimisedTx, inPlace=True)
    
    RegMethod.SetMetricAsMattesMutualInformation(numberOfHistogramBins=50)
    RegMethod.SetMetricSamplingStrategy(RegMethod.RANDOM)
    RegMethod.SetMetricSamplingPercentage(SamplingPercentage)
    
    RegMethod.SetOptimizerAsGradientDescentLineSearch(learningRate=LearningRate, 
                                                      numberOfIterations=NumIters,
                                                      convergenceMinimumValue=1e-4,
                                                      convergenceWindowSize=5)
    RegMethod.SetOptimizerScalesFromPhysicalShift()
    
    RegMethod.SetInterpolator(sitk.sitkLinear)
    
    RegMethod.SetShrinkFactorsPerLevel([4, 2, 1])
    RegMethod.SetSmoothingSigmasPerLevel([4, 2, 1])
    
    RegMethod.AddCommand(sitk.sitkStartEvent, StartPlot)
    RegMethod.AddCommand(sitk.sitkEndEvent, EndPlot)
    RegMethod.AddCommand(sitk.sitkMultiResolutionIterationEvent, UpdateMultiresIterations) 
    RegMethod.AddCommand(sitk.sitkIterationEvent, lambda: PlotValues(RegMethod))
    
    OptimizedTx = RegMethod.Execute(FixIm, MovIm)
    
    # Compose the transformations: 
    FinalTx = sitk.CompositeTransform(OptimizedTx)
    FinalTx.AddTransform(LandmarkTx)
    
    #FinalTx = sitk.BSplineTransform(FinalTx)

    print(f'Final metric value: {RegMethod.GetMetricValue()}')
    print("Optimizer stop condition:",
          f"{RegMethod.GetOptimizerStopConditionDescription()}")
    
    # Resample MovIm using FinalTx to get the registered image:
    RegIm = sitk.Resample(MovIm, FixIm, FinalTx, sitk.sitkLinear, 0.0, 
                          MovIm.GetPixelID())
  
    return RegIm
```

which occurs at the line:

`OptimizedTx = RegMethod.Execute(FixIm, MovIm)`

I can see from the definition of [`itkBSplineBaseTransform`](https://itk.org/Doxygen/html/itkBSplineBaseTransform_8h_source.html) that `ComputeJacobianWithRespectToPosition` isn't yet implemented for BSplines.  Is there a work-around for this?

I am able to perform a bspline registration using a very similar method to the above when landmark initialisation is not required by the following changes:

```
    ...
    InitialTx = sitk.BSplineTransformInitializer(image1=FixIm,
                                                 transformDomainMeshSize=MeshSize)

    RegMethod = sitk.ImageRegistrationMethod()
    
    RegMethod.SetInitialTransform(InitialTx, True)
    ....
    FinalTx = RegMethod.Execute(FixIm, MovIm)
``` 

Other than the fact that for the method using fiducials I call `SetMovingInitialTransform(LandmarkTx)`,  the two methods are the same, so I don't see why the error would be raised in one and not the other.

Could someone please shed some light on this error?

**Comment by zivy** [comment]
Hello @ctorti,

The main difference is that the `LandmarkBasedTransformInitializer` isn't returning a `BSplineTransform`, it is returning a generic transform inside of which you will find the BSplineTransform. The following code illustrates this using an affine transformation, for simplicity. The resulting estimate is correct and when you print the transforms they look the same except one line at the top which is easy to miss. For the `estimated_tx` the first line is `itk::simple::Transform` vs. `itk::simple::AffineTransform` for the `known_tx`. You can just cast the result from the landmark initializer, same as illustrated below:
```
import SimpleITK as sitk
import numpy as np

flatten = lambda t: [item for sublist in t for item in sublist]

dim = 2
known_tx = sitk.AffineTransform(dim)
known_tx.SetTranslation([3]*dim)
fixed_points = np.random.random((5,dim)).tolist()
moving_points = [known_tx.TransformPoint(p) for p in fixed_points]

estimated_tx = sitk.LandmarkBasedTransformInitializer(transform=sitk.AffineTransform(dim), 
                                                        fixedLandmarks=flatten(fixed_points), 
                                                        movingLandmarks=flatten(moving_points))
print(known_tx)
print(estimated_tx)
print(sitk.AffineTransform(estimated_tx))
```

**Comment by ctorti** [comment]
Thanks @zivy for pointing out that subtle difference.  It's not the first time I've been caught out on that.  

I casted the transform from `LandmarkBasedTransformInitializer` (`LandmarkTx` in the code above), i.e.:

`LandmarkTx = sitk.BSplineTransform(LandmarkTx)`

prior to the line:

`RegMethod.SetMovingInitialTransform(LandmarkTx)`

and confirmed that `LandmarkTx.GetName()` is now 'BSplineTransform', but unfortunately I still get the "ComputeJacobianWithRespectToPosition not yet implemented for BSplineTransform" error.

If I've missed another critical step or a detail from your explanation can you please help to clarify?

**Comment by zivy** [comment]
Hello @ctorti ,

OK, so I suspect that the issue is with the selection of the optimizer `GradientDescentLineSearch` calling the function that wasn't implemented. For the BSplineTransform the recommended optimizer is either LBFGSB or LBFGS2, in your case LBFGS2 should be used due to the multiresolution configuration. [This notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/65_Registration_FFD.ipynb) includes an example).

I also realized now that you are setting the `LandmarkTx` for the moving initial transform, which is not the common usage. It may or may not be the correct approach for your task, it's just less common than:
1. Initialization: `LandmarkTx = sitk.BSplineTransform(sitk.LandmarkBasedTransformInitializer())`
2. Main registration code, optimize `LandmarkTx`: `RegMethod.SetInitialTransformAsBSpline(LandmarkTx, inPlace=True, scaleFactors=ScaleFactors)`

**Comment by ctorti** [comment]
Hi @zivy ,

Thanks very much for your help - you are a star.  

It's difficult to remember the details of why, but I seem to remember having issues in trying to use LBFGSB and LBFGS2 (probably because I had not converted the Transform to a BSplineTransform!), but I seem to remember getting somewhere with GradientDescentLineSearch, and didn't look back.

In any case I've followed the approach and notebook example you provided and got it working.

**Comment by dyollb** [comment]
I get the same error "ComputeJacobianWithRespectToPosition not yet implemented for BSplineTransform" for all optimizers mentioned above, when the `MovingInitialTransform` is as `BSplineTransform`.

I was trying to fine tune an existing non-linear registration by providing the moving initial transform.

**Comment by zivy** [comment]
Hello @dyollb,

The error is not due to the optimizer, it is due to the BSplineTransform. As you can [see from the code in ITK](https://github.com/InsightSoftwareConsortium/ITK/blob/d8063f38ee9cefb7def37330103d59e75b1468f3/Modules/Core/Transform/include/itkBSplineBaseTransform.h#L298-L304) for the BSplineBaseTransform, this functionality is not implemented. Hence, not available in SimpleITK too.
