### ISSUE TITLE
return concrete transform class and not base class - Python specific

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#1417]
In Python, some methods return the base transform class, C++ behavior, which is confusing to Python developers. 

Add swig code to automatically convert return value to derived class. Locations where this happens:
1. `ImageRegistrationMethod.Execute()`
2.  `LandmarkBasedTransformInitializer()`

Related to #1415

**Comment by blowekamp** [comment]
Additionally, there are some transform class object which return Transform type:
1.`Transform::GetInverse()`
2.`CompositeTransform::GetBackTransform()`
3.`CompositeTransform::GetNthTransform()`

**Comment by blowekamp** [comment]
`ReadTransform`

**Comment by blowekamp** [comment]
PR #1539 did not addd this feature to ReadTransform #1564
