### ISSUE TITLE
ElastixImageFilter attribute

### ISSUE THREAD

**Issue by stavrizinonos** [SimpleITK/SimpleITK#1418]
Hello, I have been trying to get an affine transformation to MNI space where i am using my image and one on the MNI space as a reference, i also have installed simpleITK but the ElastixImageFilter() is not available. How can i solve this problem? Also, is there a tutorial available by you on python with examples? e.g, an MNI transformation example  using these libraries.
This is what i i run:
!pip install SimpleITK
import SimpleITK as sitk

elastixImageFilter = sitk.ElastixImageFilter()
elastixImageFilter.SetFixedImage(sitk.ReadImage("fixedImage.nii"))
elastixImageFilter.SetMovingImage(sitk.ReadImage("movingImage.nii"))
elastixImageFilter.SetParameterMap(sitk.GetDefaultParameterMap("affine"))
elastixImageFilter.Execute()
sitk.WriteImage(elastixImageFilter.GetResultImage())

And what i get:
AttributeError: module 'SimpleITK' has no attribute 'ElastixImageFilter'

Thank you!

**Comment by zivy** [comment]
Hello @stavrizinonos,

SimpleITK is a different project from SimpleElastix, so likely you installed SimpleITK and not SimpleElastix. Unfortunately, the SimpleElastix project built on top of SimpleITK and kept the SimpleITK package name, we don't know why. 

To obtain the SimpleElastix functionality you will need to install SimpleElastix. For instructions see the [SimplElastix GitHub repository](https://github.com/SuperElastix/SimpleElastix), for issues see their [issue tracker](https://github.com/SuperElastix/SimpleElastix/issues)
