### ISSUE TITLE
RuntimeError: Exception thrown in SimpleITK ReadTransform:

### ISSUE THREAD

**Issue by XXZhou25** [SimpleITK/SimpleITK#1421]
Hi, I used demons registration algorithm, and used sitk.ReadTransform to read .tfm file. 
It's all good with some of them, but for some of them I met the error showed as below: 

`
  File "computedvf.py", line 14, in <module>
    tf = sitk.ReadTransform(join(path, folder + str(i), 'tf.tfm'))
  File "/home/myname/anaconda3/envs/coral3/lib/python3.6/site-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 5144, in ReadTransform
    return _SimpleITK.ReadTransform(filename)
RuntimeError: Exception thrown in SimpleITK ReadTransform: /scratch/ghugo/SimpleElastix.build/ITK/Modules/IO/TransformInsightLegacy/include/itkTxtTransformIO.hxx:191:
itk::ERROR: TxtTransformIOTemplate(0x267bb90): Couldn't find end of line in #Insight Transform File V1.0
#Transform 0
Transform: DisplacementFieldTransform_double_3_3
Parameters: 6.226382249056537 12.498851129600338 2.725090934963547 6.227190375433648 12.501757678913098 2.7261849622851044 6.228460487538332 12.506327086303244 2.7279052963024966 6.230240617168931 12.512733719139046 2.7303180899516524 6.232550050274709 12.521049266503155 2.7334510770253737 6.23537162520491 12.531215080034384 2.7372831742611012 6.238706503265414 12.54323904502261 2.741818544690707 6.242551709441672 12.55711485235887 2.7470562271740193 6.246903077290112 12.572832575593324 2.7529941121685 6.251756737583374 12.590384012728222 2.7596309475670227 6.257108138884557 12.609759159544145 2.7669650089863658 6.262952301252621 12.630947112284161 2.7749944352451474 6.269283844218566 12.653936158818288 2.783717258330454 6.276096961820862 12.678713679047325 2.793131361265813 6.283385448172204 12.705266226221896 2.8032345036087882 6.291142708081154 12.73357955412519 2.814024326230172 6.299361767901048 12.763638644669188 2.825498355881349 6.308035287886607 12.79542774057889 2.8376540113103563 6.3171555734768186 12.828930373977338 2.8504886074774 6.326714586282664 12.864129393746717 2.86399935895209 6.336703954612963 12.901006991150215 2.8781833822999996 6.347114983388505 12.939544723261355 2.893037697288608 6.3579386634246315 12.979723534215825 2.908559226917868 6.369165680026912 13.021523774174598 2.9247447962325737 6.380786420864983 13.06492521596241 2.9415911299015214 6.392790983105122 13.109907069402421 2.9590948485694435 6.405169179790982 13.15644799340147 2.9772524640002356 6.417910545472152 13.20452610587826 2.9960603730444872 6.431004341088117 13.254118991657169 3.0155148504760914 6.444439558121523 13.305203708473684 3.035612040752432 6.458204922039061 13.357756791255328 3.0563479487604033 6.472288895041267 13.411754254852914 3.0777184296163176 6.486679678143682 13.467171595402124 3.099719177591693 6.501365212611642 13.523983790494672 3.1223457142391515 6.516333180769364 13.582165298332404 3.1455933757934265 6.531571006201406 13.641690056026865 3.1694572999220068 6.547065853361008 13.702531477192071 3.1939324118984924 6.562804626595652 13.764662448959793 3.219013410269529 6.578773968595649 13.828055328525382 3.244694752083551 6.594960258266911 13.892681939308668 3.2709706377467103 6.611349608024571 13.958513566789279 3.297834995568503 6.627927860500158 14.025520954049371 3.3252814660569925 6.644680584651774 14.093674297029946 3.3533033860212744 6.661593071264638 14.162943239479812 3.381893772537139 6.678650327828688 14.2332968675494 3.4110453068307476 6.69583707278103 14.304703703955393 3.4407503181347474 6.713137729104309 14.377131701616717 3.4710007675714905 6.730536417277984 14.450548236638072 3.501788232118974 6.748016947588321 14.524920100494306 3.5331038887166457 6.765562811815262 14.600213491247459 3.5649384985703088 6.7831571743305705 14.676394003608703 3.5972823917178838 6.8007828626623645 14.753426617639867 3.630125451920571 6.8184223576066305 14.831275685873882 3.6634571019469733 6.836057782997293 14.909904918620935 3.697266289320795 6.85367089528306 14.98927736721748 3.731541472605679 6.871243073102096 15.069355404969356 3.7662706083036217 6.888755307094768 15.15010070553819 3.8014411384459383 6.906188190250517 15.231474218523587 3.837039978958161 6.92352190914695 15.313436142002159 3.873053508882289 6.940736236507815 15.395945891799936 3.9094675605418083 6.957810525580451 15.478962067298452 3.946267410736742 6.974723706912221 15.56244241360694 3.98343777305806 6.9914542881879695 15.646343779976878 4.0209627914131625 7.007980357875005 15.730622074390135 4.0588260348572005 7.024279593506689 15.815232214321647 4.097010493829005 7.040329275517642 15.900128073761943 4.135498577895643 7.056106307619904 15.985262426686683 4.174272115116454 7.071587244776569 16.070586887279983 4.213312353146081 7.086748329882977 16.15605184735698 4.252599962206594 7.101565540300704 16.24160641158908 4.292115040071514 7.116014645400681 16.327198331311127 4.331837119219091 7.130071276252034 16.412773937882015 4.371745176328264 7.143711008535512 16.498278076774596 4.4118176443078205 7.156909459655838 16.583654043781237 4.452032427066331 7.169642400866567 16.668843524929724 4.492366917246121 7.1818858849929 16.753786541898368 4.532798017157559 7.193616390030529 16.838421404884606 4.573302163157572 7.204810978498279 16.922684675000013 4.613855353716877 7.215447471915007 17.00651113831414 4.6544331814104645 7.2255046391420255 17.08983379362621 4.695010869042648 7.234962396566622 17.17258385588057 4.73556331007798 7.243802017187128 17.254690776831307 4.776065113489178 7.252006344585044 17.336082284078167 4.8164906530496445 7.259560006530397 17.416684438916565 4.856814120988046 7.266449621564948 17.496421712552966 4.89700958578417 7.272663990357799 17.575217079126197 4.9370510537173145 7.278194261956864 17.652992122649895 4.976912533582522 7.283034063312701 17.729667153471947 5.016568103768681 7.28717957869561 17.805161328170026 5.055991980652939 7.290629563954988 17.879392765023674 5.095158587016911 7.293385279102251 17.952278645395754 5.134042618945639 7.295450321586668 18.023735289610233 5.172619109444912 7.296830342058954 18.093678194332036 5.210863486824503 7.2975326245896595 18.162022017155437 5.248751625760447 7.297565514456499 18.228680493214387 5.286259888883883 7.29693767896651 18.293566268283374 5.323365156758686 7.295657190539186 18.356590633200614 5.360044844212644 7.293730426580784 18.417663145724802 5.396276901184161 7.291160787540358 18.476691128404713 5.432039796547377 7.287947242769433 18.53357903508537 5.467312483801818 7.284082722975687 18.58822768480505 5.502074348090845 7.279552387422796 18.640533370690765 5.536305134797403 7.274331802508019 18.690386863737885 5.569984861020419 7.268385074815238 18.7376723474998 5.603093712640852 7.2616629849484875 18.78226633988661 5.6356119314980235 7.254101167618886 18.824036681634205 5.667519699434789 7.245618379624798 18.862841695044228 5.698797028597441 7.236114891332082 18.898529640120273 5.729423670089979 7.225471033840917 18.93093861146048 5.759379055459706 7.2135459403331845 18.959897029290435 5.788642287021979 7.200176538704844 18.985224891837852 5.817192192441048 7.185176897965726 19.00673595738889 5.8450074554469875 7.168338099427084 19.024241075056505 5.8720668274488625 7.149428896267112 19.037552956306282 5.898349409906628 7.12819752534181 19.046492789400336 5.923834975714959 7.10437514543378 19.050899248577824 5.948504270374287 7.077681449949341 19.05064041334767 5.972339207455784 7.0478330299079035 19.045628883443815 5.995322871375339 7.014555060525823 19.035839699368584 6.017439299810166 6.977596637289053 19.021329581298268 6.038673110070336 6.936749816494858 19.002254982236913 6.059009202426043 6.891871635461917 18.97888439412466 6.078432921267419 6.8429072046191886 18.95160065891041 6.09693095007028 6.789910562454832 18.92089045635747 6.11449326435131 6.733060435938011 18.887317823568765 6.131115849898956 6.672665671568432 18.851483632115936 6.146802525316235 6.609157104042179 18.813981038480055 6.16156796336801 6.543066882556493 18.77531941544202 6.175437029087904 6.474980413923326 18.735895034124443 6.188444332442904 6.405503226483396 18.695911358535056 6.200626490975097 6.335201478265443 18.655346638812475 6.21201765883904 6.264615644212718 18.61367808461191 6.222641457306924 6.194008416935498 18.569786853484562 6.232512670604756 6.1235030131965456 18.52298281992666 6.241616055639301 6.053705655987327 18.470209075809557 6.2499929295441765 5.984277520168086 18.41251179955776 6.257702648922302 5.917244042061997 18.34343814293049 6.264776779546954 5.851867701634151 18.264508605574846 6.270907911256072 5.792505063195568 18.173054924572373 6.276182723491344 5.740135288876362 18.066194705363504 6.280642811964137 5.696108352316505 17.942625518695635 6.283543840219878 5.662167368846531 17.81041159057056 6.285297733528946 5.630478994215588 17.70293890159009 6.28493818125046 5.602446532335739 17.63406710841848 6.282314982685519 5.575860378057254 17.606436300904562 6.277969880847107 5.5449270485006705 17.58917894420632 6.271549433104324 5.5173335245454584 17.573605567793706 6.262751408314887 5.482258665509524 17.52558016080691 6.2521179004189875 5.435619745155446 17.46135186384908 6.241204264774959 5.382434270241459 17.38537901958252 6.229605975508293 5.3214558466831186 17.313701466630967 6.21576864425128 5.27825936164604 17.230597642973102 6.197609542039175 5.248473798752808 17.1325202854052 6.171353321420385 5.229604907244592 16.995626819002663 6.139408653439048 5.215852171124026 16.831990431811775 6.108943736414758 5.184081652416819 16.64716267249446 6.086683557247355 5.1445201457108025 16.42025360361591 6.080465052769558 5.085663632025064 16.171748444579165 6.087113733277956 5.020590039381558 15.935023692808429 6.097582344532226 4.971855649505314 15.727184217629274 6.1039243600925275 4.939207854014443 15.572283364331799 6.100451957627951 4.93679671712256 15.464730128907776 6.087888129312174 4.956268874648625 15.375078061298472 6.0750006173989295 4.970677810955647 15.288026857181226 6.064931315144404 4.981361158013805 15.17608946255212 6.051993736545027 4.96059302265165 15.050887639017558 6.028661692782992 4.920808256421063 14.920842920331221 5.99108430834189 4.875627380982268 14.793295189987248 5.937812391964835 4.825556649059654 14.67275245365608 5.883054519476833 4.778800636475162 14.537694284175496 5.837804728123646 4.735892608038105 14.403544970786808 5.80689124303927 4.7019268426147 14.255705339126116 5.783368640851288 4.679542592678371 14.092880536418667 5.753091126159207 4.660926057773014 13.939511022163718 5.719422344583818 4.635467009093767 13.798839381852858 5.692498092150868 4.601298967046784 13.67922814236939 5.6810594880727034 4.56504207454777 13.576712263795027 5.689071498151737 4.535312089831497 13.469203662373635 5.703491135117039 4.506532469978891 13.362752431891868 5.708433774254631 4.474430573893402 13.25817777443088 5.699023079377219 4.430011663855003 1
`

**Comment by XXZhou25** [comment]
I wonder if you have any idea about what the error is? Thanks!

**Comment by zivy** [comment]
Hello @XXZhou25,

Does the file end with a newline? The error indicates it does not. Possibly add one and try to read it again. 

In any case, for deformation field transformations we recommend using the 'hdf' format. It provides much faster IO and you won't loose precision due to writing the values as text to a file (`sitk.WriteTransform(tfm, 'tx.hdf')`).

**Comment by XXZhou25** [comment]
> Hello @XXZhou25,
> 
> Does the file end with a newline? The error indicates it does not. Possibly add one and try to read it again.
> 
> In any case, for deformation field transformations we recommend using the 'hdf' format. It provides much faster IO and you won't loose precision due to writing the values as text to a file (`sitk.WriteTransform(tfm, 'tx.hdf')`).

Hi @zivy , thank you so much for your advice!
I haven't tried to add a newline, I am not sure why part of .tfm can be read without errors but why the others are not. I can try later. 
For the '.hdf' format, I just tried, I can save it successfully with `sitk.WriteTransform(tx, join(outputStem, 'tf.hdf'))`.
But I failed to read it with `tf = sitk.ReadTransform(join(path, folder + str(i), 'tf.hdf'))`, it came with an error: 
`
>>> tf = sitk.ReadTransform('tf.hdf')
HDF5-DIAG: Error detected in HDF5 (1.8.17) thread 0:
  #000: /scratch/ghugo/SimpleElastix.build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5D.c line 358 in H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  #001: /scratch/ghugo/SimpleElastix.build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #002: /scratch/ghugo/SimpleElastix.build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #003: /scratch/ghugo/SimpleElastix.build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Gtraverse.c line 641 in H5G_traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #004: /scratch/ghugo/SimpleElastix.build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Gloc.c line 385 in H5G_loc_find_cb(): object 'TranformFixedParameters' doesn't exist
    major: Symbol table
    minor: Object not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xiaoxiao.z/anaconda3/envs/coral3/lib/python3.6/site-packages/SimpleITK-1.0.1rc1.dev345+g9dfa8-py3.6-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 5144, in ReadTransform
    return _SimpleITK.ReadTransform(filename)
RuntimeError: Exception thrown in SimpleITK ReadTransform: /scratch/ghugo/SimpleElastix.build/ITK/Modules/IO/TransformHDF5/include/itkHDF5TransformIO.hxx:356:
itk::ERROR: HDF5TransformIOTemplate(0x2d2cb00): H5Dopen2 failed
`

**Comment by XXZhou25** [comment]
Hi @zivy , I just found out the issue is the version of SimpleITK. I just used version `2.0.2` and it is all good right now! Thank you so much for your help!

**Comment by blowekamp** [comment]
To clarify, previously you were using SimpleITK 1.x with ITK 4.x, and after upgrading to SimpleITK 2.x with ITK 5.x you were able to read the file?

**Comment by XXZhou25** [comment]
> To clarify, previously you were using SimpleITK 1.x with ITK 4.x, and after upgrading to SimpleITK 2.x with ITK 5.x you were able to read the file?

Hi @blowekamp , unfortunately no. I cannot read some .tfm files with SimpIeITK 2.x version or SimpleITK 1.x version, by generating the error `/scratch/ghugo/SimpleElastix.build/ITK/Modules/IO/TransformInsightLegacy/include/itkTxtTransformIO.hxx:191: itk::ERROR: TxtTransformIOTemplate(0x267bb90): Couldn't find end of line in #Insight Transform File V1.0.` 
but for some .tfm files, both SimpIeITK 2.x version and SimpleITK 1.x can read it. 
I am not sure what the reason is. Probably when I did registration, I used two different environments (one of them have SimpleITK 1.x version installed, the other one has SimpleITK 2.x version installed). 
But I am not sure if different version of SimpleITK would generate different format of .tfm files?

**Comment by XXZhou25** [comment]
> To clarify, previously you were using SimpleITK 1.x with ITK 4.x, and after upgrading to SimpleITK 2.x with ITK 5.x you were able to read the file?

Hi @blowekamp , sorry do you mean: 

> ## Hi @zivy , I just found out the issue is the version of SimpleITK. I just used version `2.0.2` and it is all good right now! Thank you so much for your help!

Here I mean I can read tf = sitk.ReadTransform('tf.hdf') successfully. But still cannot read some `.tfm`. So I re-register my images by saving `.hdf` format.
