### ISSUE TITLE
Python Question :  How to convert .mha files to dicom files ?

### ISSUE THREAD

**Issue by ParthiBa** [SimpleITK/SimpleITK#1422]
I am trying to find an way to convert .mha files to dicom files . Is there any way to do that via SimpleITK ?
I have an .mha file . how to convert that to DICOM files

**Comment by zivy** [comment]
Hello @ParthiBa,

Yes, this is easily done with SimpleITK. Please see [this example](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesFromArray_docs.html) on the toolkit's read-the-docs site.
