### ISSUE TITLE
Error in ReadImage(args[[1]], "sitkFloat32") : could not find function "ReadImage"

### ISSUE THREAD

**Issue by r-melo** [SimpleITK/SimpleITK#1424]
I am trying to follow the image registration example in R:
https://simpleitk.readthedocs.io/en/master/link_ImageRegistrationMethod1_docs.html

I am getting the error: "could not find function "ReadImage""

I installed version 2.0.0 compiling the source (devtools::install_github("SimpleITK/SimpleITKRInstaller")) on a windows 10 machine.

Is this function provided by SimpleITK or should I load some other library?

Thanks

**Comment by zivy** [comment]
Hello @r-melo,

Welcome to SimpleITK!

The `ReadImage` function is part of SimpleITK and should work out of the box. Try the following minimal example (don't forget to change the file name):
```
library(SimpleITK)
image <- ReadImage('image_file_name.jpg')
```
To make debugging easier we [recommend installing the Fiji image viewer](https://simpleitk.readthedocs.io/en/master/gettingStarted.html#recommended-software), on Windows it should be installed in your user directory (e.g. C:\Users\your_user_name\Fiji.app). This allows you to call the `Show` function to display the image.

**Comment by richardbeare** [comment]
We have had considerable trouble compiling the SimpleITK/R/Windows combination, and the changes required aren't part of the main branch yet. I don't think the devtools installer will work under windows (different makefiles/configure scripts expected). If it does work then you should expect the compilation/installation to take many minutes up to several hours. If this didn't happen then the compilation didn't succeed.

FYI - the way we have had success is with the latest Rtools v 4.0, which is required to build R and packages.

**Comment by r-melo** [comment]
> 
> 
> Hello @r-melo,
> 
> Welcome to SimpleITK!
> 
> The `ReadImage` function is part of SimpleITK and should work out of the box. Try the following minimal example (don't forget to change the file name):
> 
> ```
> library(SimpleITK)
> image <- ReadImage('image_file_name.jpg')
> ```
> 
> To make debugging easier we [recommend installing the Fiji image viewer](https://simpleitk.readthedocs.io/en/master/gettingStarted.html#recommended-software), on Windows it should be installed in your user directory (e.g. C:\Users\your_user_name\Fiji.app). This allows you to call the `Show` function to display the image.

This caused the same error. I have Fiji installed.




> 
> 
> We have had considerable trouble compiling the SimpleITK/R/Windows combination, and the changes required aren't part of the main branch yet. I don't think the devtools installer will work under windows (different makefiles/configure scripts expected). If it does work then you should expect the compilation/installation to take many minutes up to several hours. If this didn't happen then the compilation didn't succeed.
> 
> FYI - the way we have had success is with the latest Rtools v 4.0, which is required to build R and packages.

It concluded in a matter of seconds, so it seems to not have worked. I do have lates R and Rtools. I'll give it another shot. Would you recommend the anaconda installation in my situation? I should mention in my anaconda environments, Both R and Rtools are a little older.

Thank you

**Comment by richardbeare** [comment]
I haven't played with anaconda/R, if that is what you mean. The python packaging in general, and python windows in particular, is more mature than the R packaging. R packaging works fine on linux/mac, but is problematic under windows, basically because the resources we need to build are larger than available for free on github/azure runners. It is much easier to get the right tool combination post Rtools4, which completely changes the way the r build process works under windows.

My notes for building in a privately hosted github runner:



Setup of the selfhosted runner:

1. CMake for windows
1. Chocolatey
1. R: `choco install r.project`
1. Rtools: `choco install rtools --params "'/AddToPath'"`
1. ninja: `choco install ninja -fdvy`
1.  execute bash: `C:\rtools40\usr\bin\bash.exe -login`, `pacman -Sy`, `pacman --noconfirm -S mingw-w64-{i686,x86_64}-intel-tbb`
1. Put rtools in the path

clone the githubrunner branch from
 
github.com/richardbeare/SimpleITK

```bash

SITKFOLDER=${1}


which gcc
which git
which cmake

cmake --version
#which ninja
echo ${RHOME}

export CC=/mingw64/bin/gcc.exe
export CXX=/mingw64/bin/g++.exe
export FC=/mingw64/bin/gfortran.exe

#LP=$(cygpath "${AGENT_BUILDDIRECTORY}")
#export VERBOSE=1
#export LD_LIBRARY_PATH=${LP}/ITK-build/lib:${LP}/SimpleITK-build/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

#echo $LD_LIBRARY_PATH
cmake -G "MSYS Makefiles" -DWRAP_DEFAULT:BOOL=OFF -DBUILD_TESTING:BOOL=ON -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=OFF -DWRAP_TCL:BOOL=OFF -DWRAP_PYTHON:BOOL=OFF -DEXTERNAL_ITK_Module_ITKTBB:BOOL=ON -DWRAP_R:BOOL=ON ${SITKFOLDER}

#/c/Program\ Files/CMake/bin/cmake.exe -G 'MSYS Makefiles' -DCMAKE_CXX_COMPILER=${RTO}/g++.exe \
#-DCMAKE_C_COMPILER=${RTO}/gcc.exe -DCMAKE_FORTRAN_COMPILER=${RTO}/gfortran.exe -DWRAP_DEFAULT=OFF \
#-DWRAP_R=ON  -DEXTERNAL_ITK_Module_ITKTBB:BOOL=ON \
#-DR_COMMAND="${RHOME}/bin/x64/R.exe" \
#-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  ../SimpleITK/Superbuild

make -j2

cd SimpleITK-build/
make -j2 test
```
