### ISSUE TITLE
Runtime error with itkNiftiImageIO when using SimpleITK 2.1.0 instead of 2.0.2

### ISSUE THREAD

**Issue by alexandreroutier** [SimpleITK/SimpleITK#1433]
Hi everyone,

Thanks for this great tool! :)

When using the latest version of SimpleITK (2.1.0), I recently had the following error on some images:
> ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

Afer some investigation, I think this appears when migrating from 2.0.2 to 2.1.0:

```
$ pip install SimpleITK==2.1.0
Collecting SimpleITK==2.1.0
  Downloading SimpleITK-2.1.0-cp36-cp36m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (48.4 MB)
     |████████████████████████████████| 48.4 MB 726 kB/s
Installing collected packages: SimpleITK
  Attempting uninstall: SimpleITK
    Found existing installation: SimpleITK 2.0.2
    Uninstalling SimpleITK-2.0.2:
      Successfully uninstalled SimpleITK-2.0.2
Successfully installed SimpleITK-2.1.0

$ python -c "import SimpleITK as sitk; img = sitk.ReadImage('my_img.nii.gz'); print(img.GetDirection())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aroutier/Software/Miniconda3/envs/ProstateCareAdvisor/lib/python3.6/site-packages/SimpleITK/extra.py", line 346, in ReadImage
    return reader.Execute()
  File "/home/aroutier/Software/Miniconda3/envs/ProstateCareAdvisor/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 8015, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:1980:
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

$ pip install SimpleITK==2.0.2
Collecting SimpleITK==2.0.2
  Downloading SimpleITK-2.0.2-cp36-cp36m-manylinux2010_x86_64.whl (47.4 MB)
     |████████████████████████████████| 47.4 MB 207 kB/s
Installing collected packages: SimpleITK
  Attempting uninstall: SimpleITK
    Found existing installation: SimpleITK 2.1.0
    Uninstalling SimpleITK-2.1.0:
      Successfully uninstalled SimpleITK-2.1.0
Successfully installed SimpleITK-2.0.2

$ python -c "import SimpleITK as sitk; img = sitk.ReadImage('my_img.nii.gz'); print(img.GetDirection())"
(-1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0)
```

I didn't find any information on the Release notes. Does this change of behaviour is known? If so, how can I modify my code so that sitk 2.1.0 behaves similarly to 2.0.4?

Best,
Alexandre

**Comment by gdevenyi** [comment]
This is the upstream change where this check was turned on: https://github.com/InsightSoftwareConsortium/ITK/pull/1868

I Believe this could mean your nifti file may not be standards-compliant and ITK was previously too lax about loading it.

**Comment by malteekj** [comment]
I know this is old, but it is still a problem in simpleitk 2.2.0. After searching for a while, I realized the problem can stem from the `qform_code` and `sform_code` having different codes (`qform` is for using quaternion and `sform` is for using the affine matrix). A solution can be to play around with these and ensure that they conform with the definition of the coordinate system for your image.

A good resource to understand this better: [https://brainder.org/2012/09/23/the-nifti-file-format/](https://brainder.org/2012/09/23/the-nifti-file-format/ )
