### ISSUE TITLE
Maximum intensity projection

### ISSUE THREAD

**Issue by yimuu** [SimpleITK/SimpleITK#1436]
I am trying to calculate Maximum intensity projection of 4D image, But get the error
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-e3d7ebf8af09> in <module>
----> 1 projection = sitk.MaximumProjection(itk, 0)

D:\ProgramsFiles\Program\Anaconda\lib\site-packages\SimpleITK\SimpleITK.py in MaximumProjection(image1, projectionDimension)
  17327 def MaximumProjection(image1, projectionDimension=0):
  17328     r"""MaximumProjection(Image image1, unsigned int projectionDimension=0) -> Image"""
> 17329     return _SimpleITK.MaximumProjection(image1, projectionDimension)
  17330 class MeanImageFilter(ImageFilter):
  17331     r"""Proxy of C++ itk::simple::MeanImageFilter class."""

RuntimeError: Exception thrown in SimpleITK MaximumProjection: d:\a\1\work\code\common\include\sitkMemberFunctionFactory.hxx:158:
sitk::ERROR: Pixel type: 32-bit float is not supported in 4D by class itk::simple::MaximumProjectionImageFilter.

what should I do?

**Comment by gdevenyi** [comment]
#1431

**Comment by zivy** [comment]
Closing as this will be addressed when by implementing the referenced feature request.
