### ISSUE TITLE
sitk.ReadImage occurs error

### ISSUE THREAD

**Issue by yimuu** [SimpleITK/SimpleITK#1440]
When I use sitk.ReadImage to load a nii file, I got the error
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

**Comment by gdevenyi** [comment]
https://github.com/InsightSoftwareConsortium/ITK/issues/2674

**Comment by yimuu** [comment]
I got this error with SimpleITK==2.1.0. But it works with SimpleITK==2.0.2.
