### ISSUE TITLE
request for capability to read fits files

### ISSUE THREAD

**Issue by jslavin** [SimpleITK/SimpleITK#1444]
Hi,

SimpleITK has begun to be used for astronomical data for exploring the evolution of features. The most popular file format for astronomical data is fits. I'm wondering if anyone has started working on, or considered adding fits file format support to SimpleITK. That would be greatly appreciated.

Somewhat related, I can write to HDF5 files easily enough, but it's not clear to me what format SimpleITK expects in HDF5 files that it reads. In particular what group or dataset names does it look for. I couldn't find and documentation on this.

Regards,
Jon

**Comment by zivy** [comment]
Hello @jslavin,

Thanks for sharing your usage of SimpleITK. This is taking SimpleITK into uncharted territory. The toolkit's origins are in medical imaging and more recently forays into microscopy. Apparently we are now aiming for the stars.

Short question, long answer. I apologize in advance:

With respect to the fits file format, unfortunately we don't have plans for supporting it, at least not in the near future. Note that SimpleITK is based on ITK and both are C++ toolkits. We wrap the C++ implementation for usage in eight languages. For native SimpleITK support of a file format we need to implement it in C++ in ITK, making it more complicated than a non-SimpleITK implementation which directly uses one of the wrapped languages.

Having said that, solving your specific need may be easy if hdf5 is sufficient. I'll make the assumption that you are using SimpleITK in Python(the most popular language):
1. Write an image to hdf5 file:
 ```
import SimpleITK as sitk

img = sitk.Image([100]*3, sitk.sitkUInt16)
# Change default origin and spacing and add information into the metadata dictionary, just to make it interesting
img.SetOrigin([1000]*3)
img.SetSpacing([500]*3) 
img.SetMetaData(key="Simple", value = "Astronomy") 
sitk.WriteImage(img, 'demo.hdf')
 ```
2. View the hdf file content using [hdfview](https://www.hdfgroup.org/downloads/hdfview/) (trust but verify, file format description is one thing, implementation another):

<img width="265" alt="Screen Shot 2021-08-18 at 4 51 51 PM" src="https://user-images.githubusercontent.com/338645/129970660-23ca7114-bb16-4a29-8a9c-ca54a07d5e9b.png">


3. Add domain specific groups, attributes, and datasets associated with the image (don't modify the ITKImage group):
  
```
import h5py
import numpy as np

with h5py.File("demo.hdf", "a") as f:
    f.create_group("AdditionalAstronomyInfo")
    f["AdditionalAstronomyInfo"].attrs["Creator"] = np.frombuffer(
                b"SimpleITK", dtype="S1"
            )
   ```

Finally, an example of an IO implementation for a hdf5 based microscopy file format (Imaris) is available [here](https://github.com/niaid/imaris_extensions/blob/main/sitk_ims_file_io.py), illustrates adding file format support in a specific wrapped language.

**Comment by jslavin** [comment]
Thanks Ziv for your reply. I had a feeling that might be the case. Although
I have written code to read and write fits files (in Fortran!) it's not so
straightforward. I certainly don't have any ambition to do that in C++.
HDF5 will work for me. Thanks for explaining the structure of the HDF5
files that SimpleITK uses.

Regards,
Jon

**Comment by dave3d** [comment]
FYI, I googled around and there a number of libraries out there for reading and writing FITS images.

https://fits.gsfc.nasa.gov/fits_libraries.html

If someone wanted to incorporate a C or C++ FITS library into ITK, we would certainly be happy to assist them.
