### ISSUE TITLE
Wrap TransformGeometryImageFilter (Slicer HardenTransform)

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#1447]
Possibly change the name in SimpleITK, the `ResampleInPlaceImageFilter` modifies the image metadata based on the transformation, so no real resampling happens (inplace or out). In slicer they refer to it as hardening the transform. I prefer that naming convention as it doesn't imply resampling.

Based on [user questions](https://discourse.itk.org/t/simpleitk-euler3d-transform-adjust-image-origin-and-direction/3966/6) on the ITK discourse.

**Comment by blowekamp** [comment]
closed by #1522
