### ISSUE TITLE
Doxygen "See" issue

### ISSUE THREAD

**Issue by dave3d** [SimpleITK/SimpleITK#145]
The doxygen documentation for class can contain "See" references to connect to other classes.  For a class that has more than one of these "See" references, we would like them to be grouped together in one "simplesect" node in the XML.  

This grouping is not always happening, and it seems to depend on the operating system and version of Doxygen being used.  On my mac (OS X, Doxygen 1.8.5) the "Sees" are not properly grouped.  On beast2 (RedHat 7, Doxygen 1.8.7) they are properly grouped.

**Comment by dave3d** [comment]
I've determined that the problem happens with Doxygen versions 1.8.7 and newer.  My original comment about version number is wrong.  RedHat 7 has 1.8.5 and my Mac runs 1.8.7.  Also Ubuntu 14 (trusty) runs 1.8.6.

So if we stick to an older version of Doxygen we can avoid the problem.  The same issue can occur with ITK's documentation.  It does not with the nightly build of ITK documentation, because version 1.8.5 is used.

**Comment by blowekamp** [comment]
@dave3d  With the #166 merged is this issue resolved?
