### ISSUE TITLE
Typo in SuperBuild.cmake

### ISSUE THREAD

**Issue by rickardcronholm** [SimpleITK/SimpleITK#1455]
In SuperBuild.cmake the following line is found
`-DBUILD_EXAMPLES:BOOL=${BUILD_TESTING}`

Building of examples, hinges on the variable set for building of tests. Surely this is a typo and should be corrected to
`-DBUILD_EXAMPLES:BOOL=${BUILD_EXAMPLES}`

**Comment by blowekamp** [comment]
Thank you for pointing this out. Could you make a pull request with the fix?
