### ISSUE TITLE
[Question] How to extend and customize my own metric method?

### ISSUE THREAD

**Issue by raykie** [SimpleITK/SimpleITK#1462]
I know it already provides a series of similarity metric methods, but what if I need to use something different in my research? Thanks!

**Comment by zivy** [comment]
Hello @raykie,

Adding a similarity metric to SimpleITK is a two step process (not trivial, depends on proficiency in C++):
1. Implement the similarity metric in ITK, requires expertise in C++ and template usage (start with one that already exists and modify it).
2. Add the appropriate code into SimpleITK, [here](https://github.com/SimpleITK/SimpleITK/blob/19e9aa7014e2101561fe5fdf12f95d32f003d601/Code/Registration/src/sitkImageRegistrationMethod_CreateMetric.hxx#L54).

**Comment by raykie** [comment]
Any way, I need to learn more about ITK and C++ to write my own code, they are not just one or two day things. I am trying to handle it. Thanks for your reply!
