### ISSUE TITLE
[Question] Documenting exceptions

### ISSUE THREAD

**Issue by akiross** [SimpleITK/SimpleITK#1463]
Hello,
this is more of a question than an issue report, but we are working on a library using (python) SimpleITK and it seems that there is a general lack of documentation regarding raised exceptions in the (python) API. What is the status in this regard?

**Comment by zivy** [comment]
Hello @akiross,

SimpleITK is a C++ library on top of ITK. The [core API documentation](https://simpleitk.org/doxygen/latest/html/) is thus for C++, published using doxygen and relying on the ITK documentation.  The SimpleITK documentation uses the core documentation to provide language specific conventions, e.g. docstrings in Python, and similar functionality in all eight languages SimpleITK is wrapped for. The ITK documentation does not include exception information.  

Unfortunately, at this time we don't have the resources to update all of the ITK documentation (major task). Not out of the question that we look into it sometime in the future. 

As ITK and SimpleITK are open source projects we always welcome contributions from the community, so if you are willing to improve the ITK documentation by documenting the exceptions that would be a great contribution to the community, both for ITK and SimpleITK users.
