### ISSUE TITLE
VersorTransform not copied correctly when added to CompositeTransform

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#1467]
The `offset` parameter for the VersorTransform is not updated when it is copied into the CompositeTransform:
```
import SimpleITK as sitk
    
axis = [1.0,0.0,0.0]
angle = 0.15
fixed_center = [92.5, 92.5, 62]

rotation = sitk.VersorTransform(axis, angle, fixed_center)
print(rotation)
print('*'*30)
print(sitk.CompositeTransform([rotation]))
```

Original discussion on [ITK discourse](https://discourse.itk.org/t/understanding-compositetransform-discrepancies/4474/2).

**Comment by zivy** [comment]
@blowekamp, I can confirm your prediction, missing call to `ComputeOffset()` [here](https://github.com/InsightSoftwareConsortium/ITK/blob/c54ad6715a68570f9db14f002c239ec7ea06383d/Modules/Core/Transform/include/itkVersorTransform.hxx#L76). Will create a PR for ITK.

**Comment by zivy** [comment]
Closing here.
Addressed in ITK by InsightSoftwareConsortium/ITK#2783. 

@blowekamp, please add yourself and @dzenan as reviewers there. For some reason I cannot assign reviewers.

**Comment by dzenanz** [comment]
You can't assign reviewers unless you have write access. That annoys me on some projects 😄

**Comment by zivy** [comment]
@dzenanz, @thewtex,

Please add me back to the group with write privileges so that I can assign reviewers in ITK and more importantly that I can configure the SimpleITK notebooks repository. I currently do not have access to the repo settings as it is under the ITK organization. Thanks.

**Comment by blowekamp** [comment]
@dzenanz I just gave @zivy admin privileges to the notebooks. Thanks!
