### ISSUE TITLE
Access to Meta-Data dictionaries from ImageSeriesReader

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#147]
Add methods to ImageSeriesReader:

1. GetMetaDataKeys(unsigned int i), get metadata keys for image i, where i is the index of the image in the series and is in [ 0, number_of_files) . 

2. GetMetaData(unsigned int i, const std::string &key) - get the metadata for a specific image.

**Comment by blowekamp** [comment]
Addressed by #200
