### ISSUE TITLE
GetImageFromArray doesn't work well with ResampleImageFilter

### ISSUE THREAD

**Issue by kvrd18** [SimpleITK/SimpleITK#148]
Hi,

I'm trying to resample, using `sitk.ResampleImageFilter`, an ITK image initiated from a NumPy array with the help of `sitk.GetImageFromArray`. Unfortunately, post resampling, the image is filled with zeros irrespective of what the input array is. Please refer to the snippets below to reproduce the bug.

**Image loading snippet**
```python
import SimpleITK as sitk
import numpy as np

# Load moving image
reader = sitk.ImageSeriesReader()
dicom_names = reader.GetGDCMSeriesFileNames(<< filepath to moving image >>)
reader.SetFileNames(dicom_names)
moving_image = reader.Execute()

# Load fixed image
dicom_names = reader.GetGDCMSeriesFileNames(<< filepath to fixed image >>)
reader.SetFileNames(dicom_names)
fixed_image = reader.Execute()
```
Once the images are loaded, I experimented with transferring the pixel data from ITK to NumPy with the bridge.

**The bridging snippet.**
```python
moving_image = sitk.GetArrayFromImage(moving_image)
print(np.unique(moving_image))
moving_image = sitk.GetImageFromArray(moving_image)
```
`np.unique` returns `[-3024 -1024 -1023 ...,  2633  2684  3071]` for a traditional DICOM series of a CT scan that I had used.

**Resampling snippet**
```python
resampler = sitk.ResampleImageFilter()
resampler.SetReferenceImage(fixed_image)
resampler.SetOutputSpacing(fixed_image.GetSpacing())
resampler.SetOutputOrigin(fixed_image.GetOrigin())
resampler.SetOutputDirection(fixed_image.GetDirection())
resampler.SetInterpolator(sitk.sitkLinear)
out = resampler.Execute(moving_image)
out_array = sitk.GetArrayFromImage(out)
print(np.unique(out_array))
```
The above snippet returns `[0]` if the bridging snippet is used. If I don't use the bridging snippet, I get  `[-3024 -3023 -1024 ...,  2806  3070  3071]`.

I believe there's a fault in the usage of bridge with resampling because `np.unique` returns a populated list of correct values if I probe before resampling.

**Comment by blowekamp** [comment]
What versions of SimpleITK are you using? Have you tried the 1.0 Release Candidates?

**Comment by kvrd18** [comment]
I'm not able to import SimpleITK after updating it through pip.

**Comment by blowekamp** [comment]
Care to share which wheel was downloaded? You Python version, OS, and architecture? Additionally, the error message you are receiving would be quite useful.

**Comment by blowekamp** [comment]
There was a problem with SimpleITK on PyPI. The source distribution `SimpleITK-1.0.0-1.tar.gz` version was superseding all of the binary wheels without the `-1` post release. The source file on PyPI has been removed. Please uninstall and reinstall SimpleITK.

**Comment by blowekamp** [comment]
The original issue related to resampling and meta-data I believe has been addressed.
