### ISSUE TITLE
How to compute Euler angle from a given  Affine (4*4) matrix

### ISSUE THREAD

**Issue by romainVala** [SimpleITK/SimpleITK#1484]
Hello
thanks you for providing this nice sofware.

I need help to construct the 2 functions, to switch from Euler representation to the affine matrix representation. (and other way around)

reading the docs, I come up with the first one, which should be  something like that

```python
def euler_to_affine(Euler_angle, Translation, v_center):
    #euler angle in radian
    rigid_euler = sitk.Euler3DTransform(v_center,Euler_angle[0],Euler_angle[1],Euler_angle[2],Translation)
    A1 = np.asarray(rigid_euler.GetMatrix()).reshape(3,3)
    c1 = np.asarray(rigid_euler.GetCenter())
    t1 = np.asarray(rigid_euler.GetTranslation())
    affine = np.eye(4)
    affine[:3,:3] = A1
    affine[:3,3] = t1+c1 - np.matmul(A1,c1)
    return affine

```
Any help would be appreciate, to build the affine_to_euler fonction. Actually the general case is more complex, as one need to compute from the Affine: Euler rotation Translation, but also scaling and shearing

Many thanks

**Comment by zivy** [comment]
Hello @romainVala,

What you are asking for is not related to SimpleITK, it is matrix decomposition. Having said that, given a SimpleITK affine transformation `affine_tx`, the transformation component for the affine transformation which it represents is given by the `GetOffset()` method (t + c - Ac). Then get the matrix part A, via`GetMatrix()`, and decompose it.

The goal is to decompose the matrix A into a rotation*skew*scaling matrix representation. Using the [QR matrix decomposition from numpy](https://numpy.org/doc/stable/reference/generated/numpy.linalg.qr.html) you obtain an orthonormal matrix Q and an upper triangular matrix R. The scaling matrix is 1/diag(R), and the skew matrix is ones on the diagonal and everything above the diagonal. Be aware that QR decomposition admits reflection matrices (QQ^t=I, det(Q)=-1), so check that the Q matrix is indeed a rotation (QQ^t = I, det(Q)=1).

**Comment by romainVala** [comment]
thanks
yes you did understand

(I though I had to know the Euler Angle, before I can create a Eule3DTransform, but with the SetMatrix, I can just put the rotation matrix, and so I do not need how to decompose it, to get each euler angle)
