### ISSUE TITLE
Hi I am new to simpleITK, I want to use the example DemonsRegistration2, but I have some problems

### ISSUE THREAD

**Issue by markofan** [SimpleITK/SimpleITK#149]
Hi I am so sorry, but can you tell me how to use the DemonsRegistration2? 
I want to use it for 3D MRI data,and my data are save as .mat, but I don't know how to do with the code, can you tell me ? Thank you so much!

**Comment by markofan** [comment]
If I want to use the code, what is the format of moving and fixed?

**Comment by blowekamp** [comment]
What image format does SimpleITK/ITK Support?

Some of the common ones that are appropriate for 3D medical imaging are:
MetaIO (mha, mhd), Nifti, nrrd, dicom

If you are able to convert you images to one of these standard formats, the example will be able to read the image.

Alternatively, you can use [scipy.io](https://docs.scipy.org/doc/scipy/reference/tutorial/io.html) to read the file into numpy, then use [sitk.GetImageFromArray](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/8b004f1baca333df0b5a1f1299e5a1c312272873/Python/03_Image_Details.ipynb).

**Comment by markofan** [comment]
Hi my format are .hdr/.img  and   .nii           
Are these two work?

**Comment by blowekamp** [comment]
Did you try them before you asked?

They should work with ITK's Nifti image support.
https://itk.org/Doxygen/html/classitk_1_1NiftiImageIO.html

**Comment by markofan** [comment]
In your examples, I see the  [initialTransformFile] , but I don't know how to set it, can you tell me more?
I am so sorry, I am new here, please forgive me.

**Comment by blowekamp** [comment]
Please work through the relevant SimpleITK notebooks to understand the fundamentals for Images, Transforms, and the Registration process is SimpleITK:
 https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks
