### ISSUE TITLE
How to calculate the voxel-wise Jacobian determinant from multiple transforms?

### ISSUE THREAD

**Issue by karllandheer** [SimpleITK/SimpleITK#1505]
Hello, I would like to calculate the Jacobian determinant from two successively applied transforms. The first transform is a rigid transformation, the second is a BSpline transformation. This is what I've tried so far, but I get an error. Any ideas? 

transform_1 = registration_method.Execute(fixed_image, moving_image1) #this is first transform (rigid)
transform_2 = registration_method.Execute(fixed_image, moving_image2) #this is second transform (deformable)

compositeTransform = sitk.CompositeTransform(transform_1)
compositeTransform.AddTransform(transform_2)

displaceField=sitk.TransformToDisplacementField(compositeTransform, 
                                  sitk.sitkVectorFloat64,
                                  fixed_image.GetSize(),
                                  fixed_image.GetOrigin(),
                                  fixed_image.GetSpacing(),
                                  fixed_image.GetDirection())

sitk_displacement_field = sitk.GetImageFromArray(displaceField, isVector=True)
jacobian_det_volume = sitk.DisplacementFieldJacobianDeterminant(sitk_displacement_field)

This is the error I get:
Exception thrown in SimpleITK DisplacementFieldJacobianDeterminant: /Users/runner/work/1/sitk/Code/Common/include/sitkImageConvert.hxx:45:
sitk::ERROR: Expected number of elements in vector image to be the same as the dimension!

**Comment by zivy** [comment]
Hello @karllandheer,

There is something strange in the code. `displaceField` is a SimpleITK image, but then there is a call to `sitk.GetImageFromArray` which doesn't make sense here. The result of calling `sitk.TransformToDisplacementField` should be directly passed to the `sitk.DisplacementFieldJacobianDeterminant`.
