### ISSUE TITLE
Error writing Spacing Between Slices DICOM tag?

### ISSUE THREAD

**Issue by wwaleww** [SimpleITK/SimpleITK#1510]
I’m writing a DICOM volume after some image processing, and to do that I’m following the code in the [example](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReadModifyWrite_docs.html).

Other than the tags modified in the example, I also want to chage the Spacing Between Slices tag (0018,0088), but once the Dicom images are written, the tag is always set to 1.

Here is an extract of the code (after having loaded a sitk image, `img`, and its metadata, `reader`):

```
# Initialize writer object
writer = sitk.ImageFileWriter()
    
# Use the study/series/frame of reference information given in the meta-data
# dictionary and not the automatically generated information from the file IO
writer.KeepOriginalImageUIDOn()
    
# Copy all the DICOM tags from the first slice
tags_to_copy = reader.GetMetaDataKeys( 0 )
    
# Get spacing between slices (DICOM tag "0018|0088")
spacing = img.GetSpacing()[2]
    
# Create list of tuples (tag, values), and add the ones to modify
series_tag_values = [
                            (k, reader.GetMetaData(0, k))
                            for k in tags_to_copy
                            if reader.HasMetaDataKey(0, k)] + \
                        [   # Tags to modify #
                            ("0018|0088", str(spacing)),    # Spacing Between Slices
                         ]
    
# Save DICOM slices                
for i in range( img.GetDepth() ):
        image_slice = img[:, :, i]
        
        # Tags shared by the series.
        for tag, value in series_tag_values:
            image_slice.SetMetaData(tag, unidecode.unidecode(value))
            
        # Slice specific tags.
        #   Instance Creation Date
        image_slice.SetMetaData("0008|0012", time.strftime("%Y%m%d"))
        #   Instance Creation Time
        image_slice.SetMetaData("0008|0013", time.strftime("%H%M%S"))
        #   Instance Number
        image_slice.SetMetaData("0020|0013", str(i))
        #   Image Position (Patient)
        image_slice.SetMetaData("0020|0032", '\\'.join(
            map(str, volume.TransformIndexToPhysicalPoint((0, 0, i)))))
        # In-Stack Position Number
        image_slice.SetMetaData("0020|9057", str(i))
        
        # Write to the output directory and add the extension dcm, to force writing
        # in DICOM format.
        writer.SetFileName( os.path.join( saving_directory, "IM-" + str(i).zfill(4) + '.dcm') )
        writer.Execute(image_slice)
```

If I print the SpacingBetweenSlices tag just before the writer execution,
by image_slice.GetMetaData("0018|0088"), I get the correct spacing, but once the whole volume is written the spacing between slices tag is always changed to 1.
I have the same problem even if I leave the tag empty using:
```
# Create list of tuples (tag, values), and add the ones to modify
series_tag_values = [
                            (k, reader.GetMetaData(0, k))
                            for k in tags_to_copy
                            if reader.HasMetaDataKey(0, k)] + \
                        [   # Tags to modify #
                            ("0018|0088", "",    # Spacing Between Slices
                         ]
```

Do you think I might be doing something wrong, or is there a bug in the writing of the tag?

**Comment by dave3d** [comment]
For DICOM, I believe SimpleITK computes the spacing base on the distance between neighboring slices automatically.  So I don't think you can just set the value yourself.

**Comment by wwaleww** [comment]
But none of my spacing values correspond to 1, so even if it was calculating it itself, there would be something wrong I guess

**Comment by zivy** [comment]
Hello @wwaleww,

The DICOM tag `0018|0088` is not used by ITK when writing the output. It either relies on the slice origin or if tag `0020|0032` is in the meta-data dictionary [will use that](https://github.com/InsightSoftwareConsortium/ITK/blob/ad64a79f657ecbf59fec980ca37c700222008ebc/Modules/IO/GDCM/src/itkGDCMImageIO.cxx#L1019).

To help us debug the issue:
1. Please run the example code using your image as input and see that the gaussian blurred output is as expected (correct sizes, spacing, all slices are in the same series etc.), this will indicate if the issue is with the code or something unexpected with the data.
2. Before writing the output DICOM slices print their origins and spacing, per slice, see if each slice is a 3D image which it should be. The expected spacing is (dx,dy,1) and origin should be (x,y,z).

**Comment by wwaleww** [comment]
Hello @zivy ,

So I tried what you suggested:
1.  Using the example code I load my image, which has spacing (dx, dy, dz) and origin (x, y z). None of those values are = 1. I then write the DICOM volume using the example code (the `0018|0088` tag is not explicitly modified). When I load the image rewritten by SimpleITK, and I call for `image.GetSpacing()` and `image.GetOrigin()`, the SimpleITK image spacing and origin are correctly recovered as (dx, dy, dz) and (x, y, z). But in the metadata the tag `0018|0088` is changed to 1.

2. If I print the origin and spacing per slice I get a 3D image, with expected spacing (dx, dy, dz) and origin (x,y,z).

The only thing that is wrongly written is the `0018|0088` tag. In my case it can be problematic because the metadata are not only seen by ITK users, but also by radiologists, so even if ITK handles the image spacing correctly independently of the `0018|0088` tag, I would like to print the tag correctly.

But then I ask myself: where does ITK take the 3D spacing from if not from `0018|0088`? Because I [see](https://github.com/InsightSoftwareConsortium/ITK/blob/ad64a79f657ecbf59fec980ca37c700222008ebc/Modules/IO/GDCM/src/itkGDCMImageIO.cxx#L636), if I interpret correctly the code, that 2D spacing is taken from the PixelSpacing `0028|0030` tag, but what about the third dimension? I don't see how it can reconstruct it only from `0020|0032`, which just represents the Origin point, but carries no info about spacing.

Thanks for your answer!

**Comment by zivy** [comment]
Hello @wwaleww,

No magic with the third dimension. The important thing to understand is that the 2D images are actually positioned in 3D (using image position patient + direction cosine matrix, [section C.7.6.2.1 in the DICOM standard](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.6.2.html)). If you have multiple images and **assume that they are equally spaced** you can compute the spacing from that information, which is what ITK does (see [code here](https://github.com/InsightSoftwareConsortium/ITK/blob/047fa6934ac32711d1d7b84fa6eb81c72db01960/Modules/IO/ImageBase/include/itkImageSeriesReader.hxx#L198)). 

With respect to setting the value for `0018|0088`, that should probably be a feature request on the [ITK issue tracker](https://github.com/InsightSoftwareConsortium/ITK/issues). It makes sense that ITK will ignore this entry in the meta-data dictionary as it can be arbitrary and different from the actual image spacing, but it is a reasonable expectation that this tag be written correctly in the DICOM header.

**Comment by wwaleww** [comment]
Thanks a lot for the explanation @zivy, and I'll follow your suggestion!
