### ISSUE TITLE
SimpleITK 2.1.0 in python could not print metadata value if it contains Chinese character

### ISSUE THREAD

**Issue by Ermenymw** [SimpleITK/SimpleITK#1512]
Steps to reproduce the issue with simpleITK 2.1.0.
First declared a reader
```
reader = sitk.ImageFileReader()

reader.SetFileName(os.path.join(sample_dicom_path, os.listdir(sample_dicom_path)[0]))
reader.LoadPrivateTagsOn()  # LOOKHERE

reader.ReadImageInformation()
```

then I'm calling `v = reader.GetMetaData(k)` where `k` is the tag key, and `v` should be the value with "全身磁共振平扫 WHOLE BODY MRI", however, is getting `UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1-3: surrogates not allowed`

**Comment by zivy** [comment]
Hello @Ermenymw,
I tried reproducing the issue (set the patient name to the character string with Chinese characters) but this seems to work:
```
import SimpleITK as sitk

file_name = 'problem.dcm'
image = sitk.Image([2,2], sitk.sitkUInt8)
image.SetMetaData('0010|0010',  "全身磁共振平扫 WHOLE BODY MRI")
writer = sitk.ImageFileWriter()
writer.SetFileName(file_name)
writer.Execute(image)

reader = sitk.ImageFileReader()
reader.SetFileName(file_name)
reader.ReadImageInformation()
print(reader.GetMetaData('0010|0010'))
```
Can you share the file after anonymization so that we can reproduce the issue?

**Comment by Ermenymw** [comment]
[1849_782-MR-1.3.12.2.1107.5.2.50.176320.30000021102714534502000015092.dcm.zip](https://github.com/SimpleITK/SimpleITK/files/7544943/1849_782-MR-1.3.12.2.1107.5.2.50.176320.30000021102714534502000015092.dcm.zip)

my code to reproduce the issue with OS system:

```
import SimpleITK as sitk

reader = sitk.ImageFileReader()

filePath =  {{FilePath}}
reader.SetFileName(filePath)
reader.LoadPrivateTagsOn() 

reader.ReadImageInformation()
v = reader.GetMetaData('0040|0254')
print(v)
```

**Comment by zivy** [comment]
Hello @Ermenymw,

After looking into this, I don't think that this is an issue with ITK/SimpleITK. Looks more like a string encoding issue in the DICOM file. 

The error is thrown by the print function which is internally trying to encode the string using the 'utf-8' encoding.

I dumped the tag information using the [dcdump program](https://support.dcmtk.org/docs/dcmdump.html) from dcmtk. That also didn't yield a readable string:
`(0040,0254) LO [ȫ???Ź???ƽɨ WHOLE BODY MRI]`

I also tried converting the string using [various encodings specified in the DICOM standard](https://dicom.nema.org/medical/dicom/current/output/html/part05.html#chapter_6), specifically:
```
v.encode('GB18030')
```
This didn't work either. The character encoding used above is what is specified in the file's Specific Character Set, [0008|0005](https://dicom.innolitics.com/ciods/cr-image/sop-common/00080005) tag.

Possibly ask on the [ITK discourse](https://discourse.itk.org/) forum where there is a larger audience. Someone there may have more experience with these DICOM string encodings.

**Comment by Ermenymw** [comment]
Hi, @zivy . Tks for your input, I could use pydicom to read the metadata with no issue. Like you said, possibly an encoding issue in the DCM itself. But since we have no control of how the DCM is outputted, we will use pydicom instead, for now, tks.
