### ISSUE TITLE
DLL loading problem SimpleITK in python 3.8+ on Windows

### ISSUE THREAD

**Issue by fbordignon** [SimpleITK/SimpleITK#1513]
I am building SimpleITK though 3D Slicer and trying to update to python 3.9.8 on Windows.
The compile step runs smoothly and everything seems to be fine, but when it gets to the install step, i.e. installing the SimpleITK package on my python 3.9.8 build, python cannot find the DLL dependencies of _simpleitk

The problem is that python 3.8+ changed the policy on where to search for dlls https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew

In summary, python does not search the PATH environment variable for dlls anymore, and ITK, DCM, etc... dlls are not found. Now we need to call os.add_dll_directory on relevant dirs for python to find the DLLs.

My proposal: Add an environment variable such as SIMPLEITK_PYTHON_LIBS and iterate through it (if available) on SimpleITK/Wrapping/Python/SimpleITK/__init__.py adding the designated dll folders checking if we are on python 3.8+ and windows
I am only having issues on the setup, so maybe adding the folders on setup.py could solve it for me.

Does anyone have any advice or course of action for this case? Any suggestion is greatly appreciated. Thanks

<details>
<summary markdown="span">Build error:</summary>
45>Traceback (most recent call last):
45>  File "F:\ss\build\SimpleITK-build\SimpleITK-build\Wrapping\Python\setup.py", line 14, in <module>
45>    from SimpleITK._version import __version__
45>  File "F:\ss\build\SimpleITK-build\SimpleITK-build\Wrapping\Python\SimpleITK\__init__.py", line 18, in <module>
45>    from SimpleITK.SimpleITK import *
45>  File "F:\ss\build\SimpleITK-build\SimpleITK-build\Wrapping\Python\SimpleITK\SimpleITK.py", line 13, in <module>
45>    from . import _SimpleITK
</details>

**Comment by blowekamp** [comment]
Question addressed in https://github.com/Slicer/Slicer/issues/6163
