### ISSUE TITLE
consolidate sitkBSplineResampler enums

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#1518]
Consolidate all enums [sitkBSplineResamplerOrder1-5](https://github.com/SimpleITK/SimpleITK/blob/e7df1c1b2cc6ce0a07636df7444546b0070bab01/Code/Common/include/sitkInterpolator.h#L119-L131) into the sitkBSplineResampler which will have a default order of 3.

**Comment by blowekamp** [comment]
The those enums can not be removed for compatibility reasons. Issue #1550  is related.
