### ISSUE TITLE
Python 3.10 support and wheel publikaction

### ISSUE THREAD

**Issue by Czaki** [SimpleITK/SimpleITK#1521]
When wheels for python 3.10 will be released and published on PyPI?

**Comment by zivy** [comment]
Hello @Czaki,

They will be available in the next release. For now you can install them from the [latest pre-release assets on GitHub](https://github.com/SimpleITK/SimpleITK/releases/tag/latest).

**Comment by dave3d** [comment]
We've been in a holding pattern, waiting for the next release of ITK.

**Comment by Czaki** [comment]
python 3.10 is released over 4 months ago. It is impossible to compile the last release against python 3.10?

**Comment by blowekamp** [comment]
Yes. We are looking to into a 2.1.2 with 3.10 support very shortly.

**Comment by zivy** [comment]
Hello @Czaki,

If you need to use SimpleITK with Python3.10 right now, you can [install the latest binaries from GitHub](https://github.com/SimpleITK/SimpleITK/releases/tag/latest) and later on upgrade to an official release.

**Comment by Czaki** [comment]
> Hello @Czaki,
> 
> If you need to use SimpleITK with Python3.10 right now, you can [install the latest binaries from GitHub](https://github.com/SimpleITK/SimpleITK/releases/tag/latest) and later on upgrade to an official release.

I do this, and my code works. But when someone would try to install version form pypi it will fail.

**Comment by Czaki** [comment]
Solved
