### ISSUE TITLE
Python Wheels for aarch64 and Apple M1 availability 

### ISSUE THREAD

**Issue by ruidc** [SimpleITK/SimpleITK#1534]
Is there any plan to provide wheels for these architectures?

**Comment by zivy** [comment]
Hello @ruidc,

Apple M1 wheels for SimpleITK release 2.1.1 for Python 3.8 and 3.9 are on pypi. Wheels for Python 3.10 are expected to be available in the next release. If  this does not address the issue, please provide additional specifications.

**Comment by ruidc** [comment]
Thanks for the info. We are evaluating M1 for local development (as Apple can no longer provide us with Intel laptops) and use Docker and AWS Graviton2 ARM instances where the architecture is aarch64 with a variety of python versions from 3.7-3.10. At the moment it seems our only option is compiling from source, as SimpleITK is also not available on Miniforge for this architecture. Is there a roadmap to support it in future?

**Comment by blowekamp** [comment]
As Ziv said, We already have the Apple M1 ARM wheels. 

The linux ARM wheels are not on the road map as they have neither been requested before nor contributed for the community.

Currently, we are using Azure Dev Op for packaging. They do not have native ARM hardware. There appears to be a way to use docker and "qemu" to emulate the ARM on intel hardware. https://www.plcnext-community.net/makersblog/container-builds-for-arm-on-x86/ I have not tried. Getting this emulation to work with the manylinux https://github.com/pypa/manylinux docker image should be the way forward to automate the wheel packaging. Contribution and help with this would be welcomed.

By "available on Miniforge"? Do you me conda-forge? or do you mean the [SimpleITK channel](https://anaconda.org/SimpleITK/simpleitk) on anaconda.org?

The conda-forge SimpleITK package has a few dependencies which will need to be packaged for ARM. I made an initial PR to get libitk working on the ARM architecture: https://github.com/conda-forge/libitk-feedstock/pull/68

**Comment by ruidc** [comment]
Thanks for your reply.
By miniforge I mean [this](https://github.com/conda-forge/miniforge) which seems to me to be becoming the natural home for conda non-amd64 packages and several M1 and data science articles link there for obtaining binaries and interoperable versions of dependencies. I succeeded in compiling from source natively in an EC2 Graviton instance after a few false starts, but have not yet found a good recipe for doing so with QEMU on my Intel Mac.

I have however got an ARM64 container running under docker desktop using:
`docker run --rm --platform linux/arm64/v8 -it quay.io/pypa/manylinux2014_aarch64 arch`

This seems to rely upon Docker for Mac Desktop functionality in recent releases: https://docs.docker.com/desktop/multi-arch/
it then reports as being an aarch64 container. Is this something that would be usable in your build pipeline?

If so I can look to verifying that it compiles and can produce a workable wheel.

How do your M1 wheels get produced currently?

R

**Comment by dave3d** [comment]
I build the M1 wheels by hand on my laptop at home.  You can see the scripts I use here:

https://github.com/SimpleITK/SimpleITK/tree/master/Utilities/Distribution/MacARM

**Comment by dave3d** [comment]
I've create a PR for building ARM64 wheels.  We should be able to produce them automatically soon.

https://github.com/SimpleITK/SimpleITK/pull/1548

**Comment by ruidc** [comment]
> I've create a PR for building ARM64 wheels. We should be able to produce them automatically soon.
> 
> #1548

Thanks, we've stopped out aarch64 experiments for now, as there were too many libraries not yet available. Hope to revisit in several months

**Comment by zachmullen** [comment]
Hi all, I'm using SimpleITK python in docker on an Apple M1 machine, so I have a desire for Linux aarch64 bdist wheels. I see #1548 was merged, but don't yet see the wheels on pypi. Is that expected? Is it just a matter of performing a release? (I notice the last pypi release predates this thread.)

**Comment by dave3d** [comment]
Yeah, since we don't yet have an automated way of generating those wheels, we were going to wait til the next release.  But if you have an immediate need for aarch64 wheels, we can generate them for you.

**Comment by zachmullen** [comment]
No rush. Thanks for the response!

**Comment by dave3d** [comment]
We have just published our first Linux aarch64 wheels, SimpleITK version 2.2, release candidate 1.  You can see them here:

https://github.com/SimpleITK/SimpleITK/releases/tag/v2.2rc1

We would appreciate it if folks could try them out and give us feedback.

**Comment by blowekamp** [comment]
Also the 2.1.1.2 release contains macosx_11_0_arm64 wheels.
