### ISSUE TITLE
Signed Danielsson Distance does not return a vector map

### ISSUE THREAD

**Issue by PatrikBrynolfsson** [SimpleITK/SimpleITK#1540]
Hello!

In the documentation for the Signed Danielsson DIstance filter ([here](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1SignedDanielssonDistanceMapImageFilter.html)), it says that it returns "A vector map containing the component of the vector relating the current pixel with the closest point of the closest object to this pixel."  However, there is no method for accessing this vector map. Is this an oversight in the implementation of the filter, or in the documentation?

Thanks in advance!

**Comment by zivy** [comment]
Hello @PatrikBrynolfsson,

This is an oversight in the wrapping of the filter. Opened a [feature request issue](https://github.com/SimpleITK/SimpleITK/issues/1542) to add this method.

**Comment by blowekamp** [comment]
@Zivy No need to create another issue.

**Comment by PatrikBrynolfsson** [comment]
Thank you for the info! Great to hear that it will be added.
