### ISSUE TITLE
Improve tolerance of DiscreteGaussian filter

### ISSUE THREAD

**Issue by gut** [SimpleITK/SimpleITK#156]
I'm testing SimpleITK on a POWER8 system and I noticed that the `BasicFilters_DiscreteGaussianImageFilter_short_Test` test is not passing. The situation is the following:

1) If I turn off all compiler optimizations  with `-O0`, then the test outputs a difference of `0.0` and it doesn't fail
2) If I let the default compiler optimizations with `-O3`, then the test outputs a difference of around `0.48` and the test fails.

I am taking a closer look to understand why such a discrepancy exists but then I wanted to ask why is 0.4 the threshold as I noticed that this has changed already in the past, but no reason is given in the commit:
https://github.com/SimpleITK/SimpleITK/commit/89e45ae2d26de68b4c9ed6101f94c7134dc2f69c

Would it be the solution to simply readjust this value? (Then please allow me to run several times more in order to come up with a safer value)

**Comment by gut** [comment]
@blowekamp : Hi, it's been a while, but you could expose the rationale behind this change:
https://github.com/SimpleITK/SimpleITK/commit/89e45ae2d26de68b4c9ed6101f94c7134dc2f69c

**Comment by blowekamp** [comment]
Hi!

I have not compiled SimpleITK for a POWER8 system. Judging by only reporting one test failing it sounds like it was quite successful! :tada:

I believe that this field was just adjusted based on the reports from the dashboard for different architectures and configurations.

I think the algorithm is operating correctly, and the tolerance could just be adjusted. But I would also verify that the fpu model for your compiler is proper to check that the computation is still precise and not taking short cuts which degrade accuracy. For example on some Intel compilers I have had to add this flag: `-fp-model precise`

Unfortunately, this RMS output is omitted on the our testing dashboard. So I manually ran this test a couple ways:

 1. x86_64 architecture in Release -> RMS: 0
 1. i686 w/ sse2 architecture in Release -> RMS: 0.3.7
 1. i686 w/ sse2 architecture in Debug -> RMS: 0.455 *failure*

What is important to know about this test is that the filter's input and output are signed short integers. While the intermediate processing is done with floats. So there is some "rounding" that need to occour, with RMS approaching 0.5 it is seeming like the rounding is done in a non-portable way.

@thewtex 
It may be the the filter should be improve to have more portable results, perhaps adding in a proper rounding in the conversion to the output is required.

**Comment by thewtex** [comment]
Yes, this is likely related to floating point precision errors.

**Comment by gut** [comment]
> Yes, this is likely related to floating point precision errors.

and it's indeed expected, right? It looks like the only issue is that there is no easy way to set a good tolerance threshold so it's been set by mere experience, right? 

If so, how many times did you run and is there a safe margin to add on top of that?

**Comment by thewtex** [comment]
> and it's indeed expected, right? It looks like the only issue is that there is no easy way to set a good tolerance threshold so it's been set by mere experience, right?

Correct.


> If so, how many times did you run and is there a safe margin to add on top of that?

Results are generally related to processor architecture, processor features enabled, and the number of threads running. Since we do not have many POWER8 systems, your feedback through patches to ITK and SimpleITK with the correct tolerances is appreciated.

**Comment by thewtex** [comment]
>> It looks like the only issue is that there is no easy way to set a good tolerance threshold so it's been set by mere experience, right?

> Correct.

And, sometimes, we can improve the numerical stability of an implementation.

**Comment by gut** [comment]
Alright, I'll send them next. Thanks for the feedback

**Comment by blowekamp** [comment]
fixed with #157

**Comment by gut** [comment]
great! Thanks
