### ISSUE TITLE
'N4BiasFieldCorrectionImageFilter' object has no attribute 'GetLogBiasFieldAsImage'

### ISSUE THREAD

**Issue by LieCai** [SimpleITK/SimpleITK#1560]
I am running the N4 bias field correction using simpleITK's implementation. In the example here (https://simpleitk.readthedocs.io/en/master/link_N4BiasFieldCorrection_docs.html), it has a line of "log_bias_field = corrector.GetLogBiasFieldAsImage(inputImage)". However, when executing, the error appears "AttributeError: 'N4BiasFieldCorrectionImageFilter' object has no attribute 'GetLogBiasFieldAsImage' ". 

I tried suggestions on **https://github.com/SimpleITK/SimpleITK/issues/1248https://github.com/SimpleITK/SimpleITK/issues/1248**
but still not worked.
Are there any other solutions?
Thank you very much.

**Comment by zivy** [comment]
Hello @LieCai,

The `GetLogBiasFieldAsImage` is available in versions 2.1.0 and above. What version of SimpleITK are you using? `import SimpleITK as sitk; print(sitk.Version()`

**Comment by LieCai** [comment]
> Hello @LieCai,
> 
> The `GetLogBiasFieldAsImage` is available in versions 2.1.0 and above. What version of SimpleITK are you using? `import SimpleITK as sitk; print(sitk.Version())`

![1641995628(1)](https://user-images.githubusercontent.com/97592733/149153430-01d9e2f9-6cf6-4689-9dc9-3afc278d5f91.png)
Hi zivy, my version shows it's 2.2.0

**Comment by zivy** [comment]
Hello @LieCai,

This is strange. I can see you are on a windows machine using anaconda and that the installed version is the recent release candidate for version 2.2.0. Also, I see this is a mix of conda and pip package managment, which is not recommended.

I did check the new release candidate on a windows machine and there is no problem accessing the`GetLogBiasFieldAsImage` method.

Please create  a clean virtual environment and install SimpleITK into it.

**Comment by LieCai** [comment]
> Hello @LieCai,
> 
> This is strange. I can see you are on a windows machine using anaconda and that the installed version is the recent release candidate for version 2.2.0. Also, I see this is a mix of conda and pip package managment, which is not recommended.
> 
> I did check the new release candidate on a windows machine and there is no problem accessing the`GetLogBiasFieldAsImage` method.
> 
> Please create a clean virtual environment and install SimpleITK into it. That should resolve this issue.

Wow! It works! Thanks a lot!

**Comment by blowekamp** [comment]
Most likely there were multiple versions of SimpleITK libraries around causing the loading of the wrong runtime C++ libraries.
