### ISSUE TITLE
"Streaming" a pythonic-iterator to access voxels?

### ISSUE THREAD

**Issue by gdevenyi** [SimpleITK/SimpleITK#1561]
I see from the examples here:
https://simpleitk.readthedocs.io/en/master/link_AdvancedImageReading_docs.html

That some ImageIO interfaces offer the ability to load partial files. (I'm guessing the limitations listed are due to the underlying ITK implementations)

I think an interesting feature for (the python part at least) of SimpleITK would be to provide a generator/iterator which could be used to read all voxels in a streaming manner using this interface.

**Comment by zivy** [comment]
Also, a not so refined example in the *Streaming Image IO* section of the [Image Details Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/03_Image_Details.ipynb), illustrates the concept but not ideal code.

**Comment by blowekamp** [comment]
Continuing brainstorming here. I would be interesting to have a python iterator for an image/file which generates image regions. This could be used with `map` to process image chunks.

**Comment by gdevenyi** [comment]
> Continuing brainstorming here. I would be interesting to have a python iterator for an image/file which generates image regions. This could be used with map to process image chunks.

This is exactly what I'm thinking about this.

Long term -- the idea here is wrapping SimpleITK + statsmodels to do voxel-wise statistics *without* loading everything.

**Comment by blowekamp** [comment]
@gdevenyi Do you have an example of statsmodles using a generic iterator as input?

**Comment by gdevenyi** [comment]
> @gdevenyi Do you have an example of statsmodles using a generic iterator as input?

No I don't right now, but I'm literally envisioning an iterator object to do something like:
```
# voxels is an iterator which will return the same voxel from a collection of N input volumes (assume identical space)
# voxel_values are the values is an array of the i'th value from the N input volumes

for voxel_values in voxels:
	model = sm.OLS(voxel,X)
	results = model.fit()
	# store or otherwise aggregate results
```

This structure would (ideally) allow a variety of parallel toolkits to do replace the for loop as well.

I'm not necessarily expecting the iterator to do N volumes, but rather I could construct something that could aggregate across N image readers myself, but it would be nice if it could.

**Comment by blowekamp** [comment]
The additional classes may be considered for an external python package, but are outside the scope of the SimpleITK library.
