### ISSUE TITLE
How to install packages then successfully operate N4 bias field correction in R?

### ISSUE THREAD

**Issue by LieCai** [SimpleITK/SimpleITK#1562]
I've tried code from https://simpleitk.readthedocs.io/en/master/link_N4BiasFieldCorrection_docs.html
But failed, and I was told that some packages need to be installed first.
And I found there is inconsistency in installing them.
Can anyone have successful experience in installing and operating it in R?

Thanks a lot!

**Comment by zivy** [comment]
Hello @LieCai,

To install SimpleITK in R (latest release):

- OSX/linux: use the devtools installer, [see instructions here](https://github.com/SimpleITK/SimpleITKRInstaller). You will need to install devtools (`install.packages("devtools")`) to use this installer.
- Windows: build SimpleITK using the [instructions from read-the-docs](https://simpleitk.readthedocs.io/en/master/building.html) in the "Building using SuperBuild" section, (set WRAP_R to on) and then follow the instructions in the "R Installation" section.

**Comment by LieCai** [comment]
> Hello @LieCai,
> 
> To install SimpleITK in R (latest release):
> 
> * OSX/linux: use the devtools installer, [see instructions here](https://github.com/SimpleITK/SimpleITKRInstaller). You will need to install devtools (`install.packages("devtools")`) to use this installer.
> * Windows: build SimpleITK using the [instructions from read-the-docs](https://simpleitk.readthedocs.io/en/master/building.html) in the "Building using SuperBuild" section, (set WRAP_R to on) and then follow the instructions in the "R Installation" section.

When I use
"> devtools::install_github("SimpleITK/SimpleITKRInstaller", args=c("--configure-vars=MAKEJ=6"))"

It shows:
Skipping install of 'SimpleITK' from a github remote, the SHA1 (e1d03f6e) has not changed since last install.
  Use `force = TRUE` to force installation
Warning message:
1 components of `...` were not used.

We detected these problematic arguments:
* `args`

Did you misspecify an argument?

What should I do next?
