### ISSUE TITLE
Inconsistent and wrong results when using DisplacementFieldTransform

### ISSUE THREAD

**Issue by OscarPellicer** [SimpleITK/SimpleITK#1567]
When using a DisplacementFieldTransform, I can transform points correctly using the TransformPoint method, but it does not work properly for transforming images.

I present two minimal (I tried) code snippets highlighting the problems that I am experiencing:

## Code 1
If the transform is simple, I have empirically found that I can simply multiply the displacement field by -1 to make it work with images.
In this first example, a simple translation (+10, +10, +10) is defined as a displacement field and applied to some sample points and to a mask image with a value of 1 in the positions defined by those points.
I would expect that the code after `#Tranform image` should return the same point positions as the code in `#Transform points` (except in zyx ordering). However, it does not, and I must use a hack (multiplying the displacement field  by -1) to make it work. 
It must be noted that I have also had this first problem happen with transforms other than DisplacementFieldTransform.

```{python}
import SimpleITK as sitk, numpy as np

#Create small sample problem
img_np= np.zeros([100]*3)
spacing= [1]*3
displacement= np.array([10.]*3)

#Create sample points and add them to the image
points= [[50, 20, 20], [20, 50, 20], [20, 20, 50]]  #SITK ordering: xyz
print('Original points (xyz):', points)
for p in points: img_np[p[2], p[1], p[0]]= 1. #NP ordering: zyx

#Create image
img= sitk.GetImageFromArray(img_np)
img.SetSpacing(spacing)
    
#Create the DDF transform
DDF= np.stack([img_np.copy()]*3, axis=-1)
DDF[...,:]= displacement
# DDF= np.load('ddf.npy')
DDF_sitk= sitk.GetImageFromArray(DDF, isVector=True)
DDF_sitk.SetSpacing(spacing)
DDF_sitk_double= sitk.Cast(DDF_sitk, sitk.sitkVectorFloat64)
DDF_sitk_tfm= sitk.DisplacementFieldTransform(DDF_sitk_double)

#Transform points
points_after= [DDF_sitk_tfm.TransformPoint(p) for p in points]
print('Transformed points (xyz):', points_after) #Correct result

#Tranform image
resampler= sitk.ResampleImageFilter()
resampler.SetInterpolator(sitk.sitkNearestNeighbor)
resampler.SetReferenceImage(img)
resampler.SetTransform(DDF_sitk_tfm)
img_after= resampler.Execute(img)
img_after_np= sitk.GetArrayFromImage(img_after)
print('Transformed image (zyx):', np.argwhere(img_after_np)) #Wrong result (inverse translation)

#Transform image (v2)
DDF_sitk_double= sitk.Cast(DDF_sitk, sitk.sitkVectorFloat64)
DDF_sitk_hack_tfm= sitk.DisplacementFieldTransform(-DDF_sitk_double) #Notice the minus sign
resampler.SetTransform(DDF_sitk_hack_tfm)
img_after= resampler.Execute(img)
img_after_np= sitk.GetArrayFromImage(img_after)
print('Transformed image (hack, zyx):', np.argwhere(img_after_np)) #Correct result (in zyx ordering)
```

Output:
```
Original points (xyz): [[50, 20, 20], [20, 50, 20], [20, 20, 50]]
Transformed points (xyz): [(60.0, 30.0, 30.0), (30.0, 60.0, 30.0), (30.0, 30.0, 60.0)]
Transformed image (zyx): [[10 10 40]
 [10 40 10]
 [40 10 10]]
Transformed image (hack, zyx): [[30 30 60]
 [30 60 30]
 [60 30 30]]
```

## Code 2

In this second example, I use a displacement field that I have computed previously (see attached `ddf.npy`) and apply it to some points, and to the same mask image as before.
Here, neither the direct transform nor the transform multiplied by -1 give results similar to the transformed points (which I have checked to be correctly transformed):
Notice that only the first three lines after `#Create the DDF transform` have been altered with respect to the previous code fragment.
Please, download and unzip the displacement field first to reproduce this error: [ddf.zip](https://github.com/SimpleITK/SimpleITK/files/7882475/ddf.zip)

```{python}
import SimpleITK as sitk, numpy as np

#Create small sample problem
img_np= np.zeros([100]*3)
spacing= [1]*3
displacement= np.array([10.]*3)

#Create sample points and add them to the image
points= [[50, 20, 20], [20, 50, 20], [20, 20, 50]]  #SITK ordering: xyz
print('Original points (xyz):', points)
for p in points: img_np[p[2], p[1], p[0]]= 1. #NP ordering: zyx

#Create image
img= sitk.GetImageFromArray(img_np)
img.SetSpacing(spacing)
    
#Create the DDF transform
#DDF= np.stack([img_np.copy()]*3, axis=-1)
#DDF[...,:]= displacement
DDF= np.load('ddf.npy')
DDF_sitk= sitk.GetImageFromArray(DDF, isVector=True)
DDF_sitk.SetSpacing(spacing)
DDF_sitk_double= sitk.Cast(DDF_sitk, sitk.sitkVectorFloat64)
DDF_sitk_tfm= sitk.DisplacementFieldTransform(DDF_sitk_double)

#Transform points
points_after= [DDF_sitk_tfm.TransformPoint(p) for p in points]
print('Transformed points (xyz):', points_after) #Correct result

#Tranform image
resampler= sitk.ResampleImageFilter()
resampler.SetInterpolator(sitk.sitkNearestNeighbor)
resampler.SetReferenceImage(img)
resampler.SetTransform(DDF_sitk_tfm)
img_after= resampler.Execute(img)
img_after_np= sitk.GetArrayFromImage(img_after)
print('Transformed image (zyx):', np.argwhere(img_after_np)) #Completely wrong result

#Transform image (v2)
DDF_sitk_double= sitk.Cast(DDF_sitk, sitk.sitkVectorFloat64) #If I reuse DDF_sitk_double directly I receive a type error ??
DDF_sitk_hack_tfm= sitk.DisplacementFieldTransform(-DDF_sitk_double) #Notice the minus sign
resampler.SetTransform(DDF_sitk_hack_tfm)
img_after= resampler.Execute(img)
img_after_np= sitk.GetArrayFromImage(img_after)
print('Transformed image (hack, zyx):', np.argwhere(img_after_np)) #Completely wrong result (in zyx ordering)
```

Output:

```
Original points (xyz): [[50, 20, 20], [20, 50, 20], [20, 20, 50]]
Transformed points (xyz): [(55.555600090106, 38.42119721650134, 15.42357639866944), (27.288450936153794, 65.60356925539814, 18.307491855935464), (24.894789497084734, 33.897251514735856, 41.57442608134224)]
Transformed image (zyx): [[25 33 13]
 [28  0 45]
 [62  6 16]]
Transformed image (hack, zyx): [[18 36 56]
 [21 64 27]
 [44 33 25]]
```

There is a high likelihood that it is my fault for misunderstanding something about the library, so thank you in any case for your patience and for developing such a useful library!

EDIT 1: Added some more comments to the code
EDIT 2: I am using SimpleITK 2.1.0 installed from Anaconda, but I had the same issue with 2.0.2

**Comment by zivy** [comment]
Hello @OscarPellicer,

What you are encountering is the difference between forward mapping  of points and reverse mapping (a.k.a. resampling). The semantics in SimpleITK is that applying a transform to a point is forward mapping and the resampling process does backwards mapping. 

The reason resampling is done using backwards mapping is that we iterate over all pixel locations and map each of them to arbitrary locations in the original image. If we mapped the original pixel locations to the resampled image they would land at arbitrary locations and we would then have to reconstruct the resampled image from non-grid aligned values. [This presentation](https://www.cs.princeton.edu/courses/archive/spr11/cos426/notes/cos426_s11_lecture03_warping.pdf) visually illustrates the differences.

Finally, inverting a deformation field is not equivalent to multiplying it by -1. Please see [this Jupyer notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/22_Transforms.ipynb), section titled *Inverting bounded transforms*.

**Comment by OscarPellicer** [comment]
Thank you very much for your quick answer, which solved my problem and furthered my understanding.
I am sure I knew about this at some point, but then I forgot 😅
Also, although transforming in reverse makes sense from an algorithmical point of view, I would say it is rather unintuitive and has caused me many headaches in the past. Could the inverse not be computed automatically when the resampling is called? 
Also, the fact that calling the method GetInverse returns an error for a DisplacementFieldTransform probably discouraged me from trying this route, since I did not know about InvertDisplacementFieldImageFilter; maybe the GetInverse could perform the same action as the InvertDisplacementFieldImageFilter with default parameters?
Probably these changes would go against some design guidelines of the library, but I have had much frustration with this problem until I dared to ask. In any case, thank you again!

**Comment by zivy** [comment]
Hello @OscarPellicer,

Your intuition is correct. Inverting a deformation field is tricky in that there are multiple iterative solutions with variations in results based on algorithm and parameter value settings. Unfortunately there are no universally good default settings, so in this case the design is intended to force the user to make a sensible selection for themselves.

In the future don't hesitate to ask questions. The ITK/SimpleITK community is very diverse in terms of experience and we try to help everyone as much as we can. We've interacted with novices, students working on class projects, and highly experienced algorithm developers and software engineers developing commercial products. 

Happy coding!
