### ISSUE TITLE
compile SimpleITK faild on centos8-aarch64

### ISSUE THREAD

**Issue by HappyCockroach** [SimpleITK/SimpleITK#1570]
Follow the compile guide:
[https://simpleitk.readthedocs.io/en/v2.1.0/building.html](url)

Here's an error: **No matching distribution found for numpy**

<pre><code>
creating 'dist/SimpleITK-2.2.0rc1.post9+ga885b-py3.8-linux-aarch64.egg' and adding 'build/bdist.linux-aarch64/egg' to it
removing 'build/bdist.linux-aarch64/egg' (and everything under it)
Processing SimpleITK-2.2.0rc1.post9+ga885b-py3.8-linux-aarch64.egg
creating /root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/Testing/Installation/pyvenv/lib/python3.8/site-packages/SimpleITK-2.2.0rc1.post9+ga885b-py3.8-linux-aarch64.egg
Extracting SimpleITK-2.2.0rc1.post9+ga885b-py3.8-linux-aarch64.egg to /root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/Testing/Installation/pyvenv/lib/python3.8/site-packages
Adding SimpleITK 2.2.0rc1.post9+ga885b to easy-install.pth file

Installed /root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/Testing/Installation/pyvenv/lib/python3.8/site-packages/SimpleITK-2.2.0rc1.post9+ga885b-py3.8-linux-aarch64.egg
Processing dependencies for SimpleITK==2.2.0rc1.post9+ga885b
Finished processing dependencies for SimpleITK==2.2.0rc1.post9+ga885b
<b><u><font color="#FF8c00">ERROR: Could not find a version that satisfies the requirement numpy (from versions: none)
ERROR: No matching distribution found for numpy</font></u></b>
make[5]: *** [Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/build.make:79: PythonVirtualEnv] Error 1
make[4]: *** [CMakeFiles/Makefile2:4120: Wrapping/Python/CMakeFiles/PythonVirtualEnv.dir/all] Error 2
make[3]: *** [Makefile:166: all] Error 2
make[2]: *** [CMakeFiles/SimpleITK.dir/build.make:88: SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:262: CMakeFiles/SimpleITK.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
(python38_SimpleITK) [root@ad614c78a12c SimpleITK-build]#
</code>
</pre>

But I already have numpy installed in my conda virtual environment.
```shell
(python38_SimpleITK) [root@ad614c78a12c SimpleITK-build]# conda list | grep numpy
numpy                         1.21.2           py38h6fc94f6_0
numpy-base                1.21.2           py38h6ba5a95_0
```
How can I solve this problem?
thanks.

OS: CentOS Linux release 8.5.2111 ( Docker container )
arch: aarch64
cmake version: 3.22.1
gcc version: 10.3.1
Python: 3.8.12
R version: 4.1.2

**Comment by dave3d** [comment]
I don't know what's going on there.  But we just posted our first Linux aarch64 wheels.  Have you tried those?

https://github.com/SimpleITK/SimpleITK/releases/download/v2.2rc1/SimpleITK-2.2.0rc1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl

**Comment by HappyCockroach** [comment]
It's a network problem. I used a proxy network.
Now, I can successfully compile.

The first Linux aarch64 wheels is good choice, but I want a complete SimpleITK, not just the python interface, so I want to compile from source.

After I compiled it, 9 test cases failed.
I'm not sure if there are bugs here.
I'll create a new issue for the failed test cases.

Thanks.
