### ISSUE TITLE
9 test cases failed on centos8-aarch64

### ISSUE THREAD

**Issue by HappyCockroach** [SimpleITK/SimpleITK#1571]
Follow the compile guide:
[https://simpleitk.readthedocs.io/en/v2.1.0/building.html](url)

I can successfully compile SimpleITK, but there are 9 test cases failed:
```shell
104:BasicFilters.ProcessObject_NumberOfThreads
2050:Python.SLICImageFilter.minimum
2053:R.SLICImageFilter.minimum
2056:Tcl.SLICImageFilter.minimum
2059:Java.SLICImageFilter.minimum
2061:BasicFilters.SLICImageFilter
2649:CXX.Example.ImageRegistrationMethodDisplacement1
2651:Python.Example.ImageRegistrationMethodDisplacement1
2653:R.Example.ImageRegistrationMethodDisplacement1
```

1. **For the test case 104:**
```shell
/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK/Testing/Unit/sitkBasicFiltersTests.cxx:359: Failure
Expected equality of these values:
  gNum+1
    Which is: 129
  filter.GetGlobalDefaultNumberOfThreads()
    Which is: 128
/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK/Testing/Unit/sitkBasicFiltersTests.cxx:363: Failure
Expected equality of these values:
  gNum+1
    Which is: 129
  caster2.GetNumberOfThreads()
    Which is: 128
/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK/Testing/Unit/sitkBasicFiltersTests.cxx:364: Failure
Expected equality of these values:
  gNum+1
    Which is: 129
  caster2.GetGlobalDefaultNumberOfThreads()
    Which is: 128
```
My server has 128 cores, maybe it doesn't allow the number of threads to exceed the number of cores.
I modified the code for this test case, and the test passed.
```c++
  // filter.SetGlobalDefaultNumberOfThreads(gNum+1);
  // EXPECT_EQ(gNum+1, filter.GetGlobalDefaultNumberOfThreads());
  // EXPECT_EQ(3u, filter.GetNumberOfThreads());

  // sitk::CastImageFilter caster2;
  // EXPECT_EQ(gNum+1, caster2.GetNumberOfThreads());
  // EXPECT_EQ(gNum+1, caster2.GetGlobalDefaultNumberOfThreads());

  filter.SetGlobalDefaultNumberOfThreads(gNum);
  EXPECT_EQ(gNum, filter.GetGlobalDefaultNumberOfThreads());
  EXPECT_EQ(3u, filter.GetNumberOfThreads());

  sitk::CastImageFilter caster2;
  EXPECT_EQ(gNum, caster2.GetNumberOfThreads());
  EXPECT_EQ(gNum, caster2.GetGlobalDefaultNumberOfThreads());
```

2.  **For the test case SLICImageFilter.minimum:**
```shell
<DartMeasurement name="RMSEDifference BasicFilters_SLICImageFilter_minimum.nrrd" type="numeric/float">1.4964</DartMeasurement>
<DartMeasurement name="RMSEDifference" type="numeric/float">1.4964</DartMeasurement>
<DartMeasurement name="Tolerance" type="numeric/float">0.05</DartMeasurement>
<DartMeasurementFile name="ExpectedImage" type="image/png">/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/Testing/Temporary/BasicFilters_SLICImageFilter_minimum.nrrd_Expected.png</DartMeasurementFile>
<DartMeasurementFile name="ActualImage" type="image/png">/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/Testing/Temporary/BasicFilters_SLICImageFilter_minimum.nrrd_Actual.png</DartMeasurementFile>
<DartMeasurementFile name="DifferenceImage" type="image/png">/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/Testing/Temporary/BasicFilters_SLICImageFilter_minimum.nrrd_Difference.png</DartMeasurementFile>
<DartMeasurement name="DifferenceImage Minimum" type="numeric/double">0</DartMeasurement>
<DartMeasurement name="DifferenceImage Maximum" type="numeric/double">11</DartMeasurement>
<DartMeasurement name="DifferenceImage Mean" type="numeric/double">0.456978</DartMeasurement>
/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/Testing/Unit/sitkSLICImageFilterTest.cxx:231: Failure
Value of: imageCompare.compare( output, "", "" )
  Actual: false
Expected: true
ImageCompare: image Root Mean Square (RMS) difference was 1.4964 which exceeds the tolerance of 0.05
```
The difference was 1.4964 which exceeds the tolerance of 0.05.
Is this a bug on the aarch64 platform?
Is there a problem with the logic of the SLICImageFilter.minimum function?
Or, the tolerance 0.05 is a wrong number?

3. **For the test case ImageRegistrationMethodDisplacement1:**
```shell
Gaussian smoothing parameters:
   m_GaussianSmoothingVarianceForTheUpdateField: 0
   m_GaussianSmoothingVarianceForTheTotalField: 1.5
Optimizer stop condition: GradientDescentOptimizerv4Template: Convergence checker passed at iteration 11.
Iteration: 11
Metric value: -0.3433355
Reading test transform: "/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/Testing/Temporary/RImageRegistrationMethodDisplacement1.hdf5"...
Reading baseline displacement: "/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/ExternalData/Testing/Data/Baseline/ImageRegistrationMethodDisplacement1.mha"...
<DartMeasurement name="RMSDifference ImageRegistrationMethodDisplacement1.mha" type="numeric/float">0.402929</DartMeasurement>
Reading baseline displacement: "/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/ExternalData/Testing/Data/Baseline/ImageRegistrationMethodDisplacement1.1.mha"...
<DartMeasurement name="RMSDifference ImageRegistrationMethodDisplacement1.1.mha" type="numeric/float">0.137498</DartMeasurement>
Reading baseline displacement: "/root/miniconda3/envs/python38_SimpleITK/SimpleITK/SimpleITK-build/SimpleITK-build/ExternalData/Testing/Data/Baseline/ImageRegistrationMethodDisplacement1.2.mha"...
<DartMeasurement name="RMSDifference ImageRegistrationMethodDisplacement1.2.mha" type="numeric/float">3.05223</DartMeasurement>
<DartMeasurement name="Tolerance" type="numeric/float">0.02</DartMeasurement>
```
It looks the same as above, the RMS Difference exceeds the tolerance.

Are these bugs on the aarch64 platform? Or, the tolerance is wrong?
thanks.

**Comment by blowekamp** [comment]
Thank you for the detailed post. What version of SimpleITK are you compiling? And it is assumed it is in "Release" mode.

1. ITK has a hard coded limit of 128 threads in some places, it looks like this was encountered. Perhaps ITK, or the test should be updated. Have you used SimpleITK/ITK filters up to 128 threads where there were still performance gains this that many threads? Are there algorithms you are using that scale that well?

2. and 3. Are likely not bugs, but difference in numeric tolerances. Both of these methods are iterative, and differences can grow with more iterations. We can see if the test could be improved to be more stable or introduce new baseline images.

**Comment by HappyCockroach** [comment]
1. Perhaps because of the size of the input data, more cores don't show better performance. The limitation of 128 may be reasonable in most cases.

2. I tried compiling 4 versions of the source code.
`https://codeload.github.com/SimpleITK/SimpleITK/tar.gz/refs/tags/latest`
`https://codeload.github.com/SimpleITK/SimpleITK/tar.gz/refs/tags/v2.2rc1`
`git clone https://github.com/SimpleITK/SimpleITK.git`
```shell
git clone https://github.com/SimpleITK/SimpleITK.git

# Restore the code to the latest tag.
git checkout latest
```
When I used the first two pre-release versions, the compilation failed.There was such an error.
```shell
-- Building SimpleITK version "2.2.0.dev-gGITDIR-NOTFOUND"
-- Found Java: /usr/bin/java (found version "11.0.13") found components: Development Runtime
-- Processing json files...
-- Processing json files...done
-- Found Java: /usr/bin/java (found version "11.0.13")
CMake Error at Wrapping/R/CMakeLists.txt:65 (math):
  math cannot parse the expression: "9000 + ": syntax error, unexpected $end
  (7).

-- Adding Google Test source directory as subdirectory.
-- Generating tests...
-- Generating tests...Done
-- Configuring incomplete, errors occurred!
```
The source code of the later two versions can be successfully compiled.
The failed test cases are the same.

3. As I adjust the number of iterations, the RMS Difference becomes larger and larger.
But it should be convergent.As the number of iterations increases, the RMS Difference almost remains unchanged.
Maybe there should be a new baseline image.

All in all, these failed test cases won't affect my use of simpleITK, right?
thsnks.

**Comment by blowekamp** [comment]
1. The number of threads test is fixed in :#1574

**Comment by blowekamp** [comment]
2. Using the automatically generated Github source tarball process the following warning:
```
CMake Warning at CMake/sitkSourceVersion.cmake:41 (message):
  Unable to determine source version!

  Please use the git repository or an official source distribution.
```

The official tarball distributions are in the Github releases pages, and have names like: SimpleITK-2.2rc1.tar.gz These official distributions contain an additional file which container the needed versioning information derived from the git repository.

However, this state should be a "warning" and not an error. The following patch addresses the error: #1576

**Comment by blowekamp** [comment]
3. Yes, most likely some baseline images should be added. Not all algorithms and data converge to the same location. There can be multiple local optima. Or an algorithm could use more regularization and smoothing of the input. Also in the case of displacement fields, there can be homogeneous regions where different displacements yield the same value and the particular parameter may not converge.

Your built version of SimpleITK is fine up to the numeric tolerances and variability of the algorithm and data as far as I can tell.

**Comment by dave3d** [comment]
FYI, I got some of the same failed tests.  Here's the output I got:

	844 - Python.SLICImageFilter.minimum (Failed)
	846 - BasicFilters.SLICImageFilter (Failed)
	1062 - CXX.Example.ImageRegistrationMethodDisplacement1 (Failed)
	1064 - Python.Example.ImageRegistrationMethodDisplacement1 (Failed)

I only built the C++ and Python versions.

**Comment by blowekamp** [comment]
PR to file the SLIC filter in InsightSoftwareConsortium/ITK#3220

**Comment by blowekamp** [comment]
With the 2.2 RC and the distributed ARM wheels all the tests are passing.
