### ISSUE TITLE
`SimpleITK_ITKDistanceMap` build errors using latest ITK and SimpleITK

### ISSUE THREAD

**Issue by jamesobutler** [SimpleITK/SimpleITK#1578]
As part of https://github.com/Slicer/Slicer/pull/5954, I've been testing latest ITK and SimpleITK. I did a clean build of Slicer using ITK as of https://github.com/InsightSoftwareConsortium/ITK/commit/6925c8c6dda4435b5476c92386b02c23f1da5ef4 and SimpleITK as of https://github.com/SimpleITK/SimpleITK/commit/bbebc757e6a12666e29f21278ea8cae9e45dcf17.

There appears to be an issue with `SimpleITK_ITKDistanceMap`. Is this a known issue when using these latest versions?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2338	invalid pixel type [C:\S5R\SimpleITK-build\SimpleITK-build\Code\BasicFilters\src\SimpleITK_ITKDistanceMap.vcxproj] [C:\S5R\SimpleITK-build\SimpleITK.vcxproj]	SimpleITK	C:\S5R\SimpleITK\Code\Common\include\sitkImage.h	149	
Error	C2672	'itk::simple::Image::InternalInitialization': no matching overloaded function found [C:\S5R\SimpleITK-build\SimpleITK-build\Code\BasicFilters\src\SimpleITK_ITKDistanceMap.vcxproj] [C:\S5R\SimpleITK-build\SimpleITK.vcxproj]	SimpleITK	C:\S5R\SimpleITK\Code\Common\include\sitkImage.h	151	
Error	C2770	invalid explicit template argument(s) for 'void itk::simple::Image::InternalInitialization(PixelIDToImageType<typelist::TypeAt<itk::simple::InstantiatedPixelIDTypeList,VPixelIDValue>::Result,VImageDimension>::ImageType *)' [C:\S5R\SimpleITK-build\SimpleITK-build\Code\BasicFilters\src\SimpleITK_ITKDistanceMap.vcxproj] [C:\S5R\SimpleITK-build\SimpleITK.vcxproj]	SimpleITK	C:\S5R\SimpleITK\Code\Common\include\sitkImage.h	151	
Error	C2338	invalid pixel type [C:\S5R\SimpleITK-build\SimpleITK-build\Code\BasicFilters\src\SimpleITK_ITKDistanceMap.vcxproj] [C:\S5R\SimpleITK-build\SimpleITK.vcxproj]	SimpleITK	C:\S5R\SimpleITK\Code\Common\include\sitkImage.h	149	
Error	C2672	'itk::simple::Image::InternalInitialization': no matching overloaded function found [C:\S5R\SimpleITK-build\SimpleITK-build\Code\BasicFilters\src\SimpleITK_ITKDistanceMap.vcxproj] [C:\S5R\SimpleITK-build\SimpleITK.vcxproj]	SimpleITK	C:\S5R\SimpleITK\Code\Common\include\sitkImage.h	151	
Error	C2770	invalid explicit template argument(s) for 'void itk::simple::Image::InternalInitialization(PixelIDToImageType<typelist::TypeAt<itk::simple::InstantiatedPixelIDTypeList,VPixelIDValue>::Result,VImageDimension>::ImageType *)' [C:\S5R\SimpleITK-build\SimpleITK-build\Code\BasicFilters\src\SimpleITK_ITKDistanceMap.vcxproj] [C:\S5R\SimpleITK-build\SimpleITK.vcxproj]	SimpleITK	C:\S5R\SimpleITK\Code\Common\include\sitkImage.h	151	
```

**Comment by blowekamp** [comment]
We has a similar error on 32-bit windows on the SimpleITK dashboard:
https://open.cdash.org/viewBuildError.php?buildid=7706362

This was just addressed in #1577. We had been talking about stopping this legacy build.

Is this a 32-bit build? or Or is the CMake variable `ITK_USE_64BITS_IDS` still set to OFF? Or other configuration info on how this issue related to 32-bit `long` types was encountered.

**Comment by jamesobutler** [comment]
This was not a 32-bit build. It was 64-bit. Looking at the SimpleITK configuration, `SimpleITK_INT64_PIXELIDS` was OFF. Looking at the ITK configuration `ITK_USE_64BITS_IDS` was ON.

**Comment by blowekamp** [comment]
I'll need to investigate the effect of `SimpleITK_INT64_PIXELIDS=OFF` as that may be disabling the 64 bit pixel type used here. It may or may not be windows specific.

**Comment by jamesobutler** [comment]
It appears Slicer sets `SimpleITK_INT64_PIXELIDS=OFF` just as a recommended option from you way back in the day. It was initially set as an option to configure with it being OFF in Slicer in https://github.com/Slicer/Slicer/commit/11ef4228af23bfd52c7f12b0bbf15e107f8d5a87.

> From Brad: I enable 64-bit integers as pixel types. This can be disabled
> as a CMake option, as its likely not worth the cost for Silcer.

@blowekamp If you think there are better defaults to have for Slicer configuration here in 2022, please let me know. Thanks!

**Comment by blowekamp** [comment]
Yes, please try with`SimpleITK_INT64_PIXELIDS=ON`. It will take a little longer to build, and the binaries will be a little bigger.

This option has been enable as a default with "Visual Studio 2010". So it is likely time to remove this option.

**Comment by jamesobutler** [comment]
With my incremental build with `SimpleITK_INT64_PIXELIDS=ON`, it appears the SimpleITK build as part of the Slicer superbuild has succeeded.

**Comment by blowekamp** [comment]
Please see the proposed changed here: #1579 which enforces SimpleITK_INT64_PIXELIDS to be enabled with 64-bit builds.
