### ISSUE TITLE
GridImageSource() cannot handle Cor and Sag images

### ISSUE THREAD

**Issue by PatrikBrynolfsson** [SimpleITK/SimpleITK#1595]
There seems to be a bug in GridImageSource(). There is no grid in the returned image when supplying a Sag or Cor image.  This can be confirmed by combining this the GridImagesource() with the NodeITKDICOMOrientImageFilter(). 

Further, in the ITK filter, m_WhichDimensions controls in which dimensions the grid lines appear. Is it possible to expose this setting in the simple ITK version as well?

Thanks!

**Comment by blowekamp** [comment]
To you have sample code to reproduce the issue?

**Comment by PatrikBrynolfsson** [comment]
Sure! I put something together in python. I discovered the bug in a C# project, but this behaves the same.
```
import SimpleITK as sitk

path_to_input_image = "C:\\Temp\\image.mhd"
ax_grid = "C:\\Temp\\ax_grid.mhd"
sag_grid = "C:\\Temp\\sag_grid.mhd"

# Read image
image = sitk.ReadImage(path_to_input_image)

# Ensure Ax image
ax_image = sitk.DICOMOrient(image, "LPS")

# Ensure Sag image
sag_image = sitk.DICOMOrient(image, "PIR") 

for (img, file_name) in zip([ax_image, sag_image], [ax_grid, sag_grid]):

    grid_filter = sitk.GridImageSource()
    grid_filter.SetDirection(img.GetDirection())
    grid_filter.SetOrigin(img.GetOrigin())
    grid_filter.SetSpacing(img.GetSpacing())
    grid_filter.SetSize(img.GetSize())

    grid_filter.SetSigma(1)
    grid_filter.SetGridOffset([0, 0, 0])
    grid_filter.SetGridSpacing([20, 20, 20])

    grid = grid_filter.Execute()

    sitk.WriteImage(grid, file_name)

```

**Comment by PatrikBrynolfsson** [comment]
Can you reproduce the behaviour I am seeing? Is there a bug in the filter, or am I somehow using it wrong?

**Comment by blowekamp** [comment]
No I can't because I don't have the images you referenced. Please directly provide the values for the filter that are required to reproduce the bug. It may just be the direction cosine matrix, or maybe spacing too etc. Narrowing down which of these are significant to reproduce the bug is a good step to figuring out what the problem is too.
