### ISSUE TITLE
Python sitk.Resampling error : TypeError: _r_image() got multiple values for argument 'transform'

### ISSUE THREAD

**Issue by PaulJehanno** [SimpleITK/SimpleITK#1596]
Hello, I am having a hard time trying to understand how sitk.Resample parses the arguments, because it seems I "provided multiple values for argument transform" which doesn't make sense.

```python
import SimpleITK as sitk
grid = sitk.GridSource(outputPixelType=sitk.sitkFloat32,
    size=(250, 250, 100),
    sigma=(0.5, 0.5, 0.5),
    gridSpacing=(5.0, 5.0, 5.0),
    gridOffset=(0.0, 0.0, 0.0),
    spacing=(0.2,0.2, 0.2)
)

sitk.Resample(
  grid,
  [250, 250, 100],#output size
  transform=sitk.Transform(),
  interpolator=sitk.sitkNearestNeighbor,
  outputOrigin=grid.GetOrigin(),
  OutputSpacing=grid.GetSpacing(),
  outputDirection=grid.GetDirection(),
  defaultPixelValue=0.0,
  outputPixelType=grid.GetPixelID(),
  useNearestNeighborExtrapolator=False,
)
```

 raises the following error : 
```
File ~/miniforge3/envs/paire_inference_new/lib/python3.8/site-packages/SimpleITK/extra.py:113, in Resample(image1, *args, **kwargs)
    110 if "size" in kwargs:
    111     return _r(*args, **kwargs)
--> 113 return _r_image(image1, *args, **kwargs)

TypeError: _r_image() got multiple values for argument 'transform'
```

It seems from what I understand about the file `extra.py` that when the first argument is an Image, it passes to `_r_image(*args, **kwargs)` but this function does not handle the first argument "output_size" so it passes the output_size argument as first keyword argument ("transform") but as I already have a transform in the kwargs, it breaks and tells I have too many transforms.
How can this happen? How can I fix it? THanks,

my settings : 
- OS M1 Mac 12.1 Monterey
- python 3.8.8
- sitk 2.1.1

**Comment by PaulJehanno** [comment]
damn, sorry for the typo 🙈

**Comment by blowekamp** [comment]
I am re-opening this issue as the error message you got was not helpful (incorrect).

The [follow](https://github.com/SimpleITK/SimpleITK/blob/master/Wrapping/Python/SimpleITK/extra.py#L115) `except` is hiding the useful keyword error message which is a TypeError. And needs to be adjusted.
