### ISSUE TITLE
Wrong Origin with ConstantPad

### ISSUE THREAD

**Issue by LangDaniel** [SimpleITK/SimpleITK#1600]
I'm reading different nifty images, using ConstantPad to establish a minimal image size.
However, there seems to be a problem with the image origin after padding.

As a minimal example I tried:
```
img = sitk.ReadImage(path_to_nii)
img_origin = img.GetOrigin()
img_spacing = img.GetSpacing()

print(f'direction: {img.GetDirection()}')
print(f'origin:\t {img_origin}')
print(f'spacing:\t {img_spacing}')

lower_pad = [100, 20, 0]
upper_pad = [0, 0, 0]

expected_origin = np.array(img_origin) - (np.array(lower_pad) * np.array(img_spacing))

padded = sitk.ConstantPad(img, lower_pad, upper_pad, constant=0)

print(f'expected origin:\t {expected_origin}')
print(f'padded origin:\t {padded.GetOrigin()}')
```
Output:
>direction: (0.9372311410520767, 2.3505955909658455e-07, -0.34870874991075257, 0.34870874414354336, 4.231158757126697e-08, 0.9372311389063418, -2.3505956452782662e-07, 0.9999999999999715, 4.231158984466573e-08)
>origin:	 (-74.09725189208984, -171.79188537597656, -85.048828125)
>spacing:	 (0.40234375, 0.40234375, 1.9994282722473145)
>expected origin:	 [-114.33162689, -179.83876038,  -85.04882812]
>padded origin:	 (-111.80616297435188, -185.82196409410298, -93.09569366752511)

It seems like this has something to do with the direction of the images?
Because adding `img = sitk.DICOMOrient(img)` in the second line fixed the problem
for some of the cases but also not for all of them.
Setting the origin by `padded.SetOrigin(expected)` fixed the problem.

My SimpleITK version is 2.1.1

**Comment by LangDaniel** [comment]
Ok sorry, realized that this is due to the non uniform direction matrix.
But this makes addition of, let's say 20mm in axial direction, rather hard, right?

**Comment by zivy** [comment]
Hello @LangDaniel,

The padding is done with respect to the image array, that is then positioned in physical space using the direction cosine, origin and spacing information. When the direction cosine matrix is not the identity, just padding will not do what you thought it would.

If you want to "pad" in a specific direction, make all images have identity direction cosine matrix, you can define a new image grid and resample the original onto it. This is a computationally more expensive operation than just padding, but you have full control of the new grid (origin, direction cosine, spacing).
