### ISSUE TITLE
Doxygen links to ITK are broken

### ISSUE THREAD

**Issue by brandonfosso** [SimpleITK/SimpleITK#1604]
I was looking through some of the SimpleITK documentation and noticed that the links to ITK are broken.

For example, consider the [AbsImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1AbsImageFilter.html) page. In the 'Detailed Description' section under 'See Also', clicking on the [link](https://www.itk.org/Doxygen/html/classitk_1_1AbsImageFilter.html) to its ITK counterpart yields a 404 page.

It is possible to get to the [desired page](https://itk.org/Doxygen/html/classitk_1_1AbsImageFilter.html) manually.

Comparing the links side by side:
```
From SimpleITK:    https://www.itk.org/Doxygen/html/classitk_1_1AbsImageFilter.html
Manual Navigation: https://itk.org/Doxygen/html/classitk_1_1AbsImageFilter.html
```
shows that the only difference is the `www` in the first one.

[www.itk.org](http://www.itk.org/) and [itk.org](https://itk.org/) take you to different places in a browser leading to the issue described.

**Comment by blowekamp** [comment]
@thewtex

**Comment by blowekamp** [comment]
Thank for reporting the issue. I brought this to the [attention of the ITK team](https://discourse.itk.org/t/maintenance-today/4738/6) and the issue has been addressed. The www links work again.
