### ISSUE TITLE
c# SimpleITK crashes (randomly) with memory access violation in heavily threaded applications

### ISSUE THREAD

**Issue by DrDryg** [SimpleITK/SimpleITK#1607]
I experience crashes in simpleITK when using it in a c# application with many threads. The crashes are random and quite illusive. They hardly ever happen in visual studio, while they are much more prevalent when running the software alone. However, I can typically get crashes every time I run the program for a while, and then it stops and I can run it 100 times with no crash.

A number of different faults can occur but all seem related to memory access, I will show some example dumps below. To reproduce the problem one has to run multiple threads in parallel using 100% cpu and just create any SimpleITK object. For instance a filter. Nothing needs to be done with the filter. Initially I had the error in a ITK that I compiled myself with Elastix, but the issue is there for the latest official binaries too (SimpleITKCSharp v2.1.1). 

The following code manage to reproduce the issue with some reliability:
(Ive tried disposing the itk object and placing it in a using statement also - without success.)

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.ExceptionServices;
using System.Security;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using itk.simple;


namespace ITKCrashProject
{
    class Program
    {
        static void Main(string[] args)
        {
            AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;
            // itk.simple.ProcessObject.SetGlobalDefaultThreader("Platform");

            //itk.simple.MedianImageFilter filter = new itk.simple.MedianImageFilter();
            Console.WriteLine("Starting");
            try
            {
                ThreadedLoop(50);
            }
            catch (Exception e)
            {
                string exceptionMessage = e.Message;
                Console.WriteLine(exceptionMessage);
                Console.ReadLine();
            }
            Console.WriteLine("Done!");
            Console.ReadKey();
        }

        [HandleProcessCorruptedStateExceptions, SecurityCritical]
        private static void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            Console.WriteLine(e.ExceptionObject.ToString());
            Console.ReadLine();
        }

        private static void ThreadedLoop(int n)
        {
            // Spin up n threads
            Thread[] threads = new Thread[n];

            for (int i = 0; i < n; i++)
            {
                threads[i] = new Thread((ThreadStart)delegate
                {
                    RunNode();
                }
            );

                threads[i].Start();
            }

            while (threads.Any(x => x.IsAlive))
            {
                Thread.Sleep(20);
            }
        }

        private static void RunNode()
        {
            Thread itkThread = new Thread(
                  (ThreadStart)delegate
                  {
                      
                    // Do some heavy stuff!
                    string name = "";
                    DiscreteGaussianImageFilter filter = new itk.simple.DiscreteGaussianImageFilter();
                    long k = 0;
                        for (int i = 0; i < 10_000; i++)
                        {
                        name = filter.GetName();
                            for (int j = 0; j < 100_000; j++)
                            {
                                k = k + i + j;
                            }
                        }
                        Console.WriteLine($"Value is {k} {name}");
                  }
                  );

            itkThread.Start();
            while (itkThread.IsAlive)
            {
                Thread.Sleep(20);
            }

        }
    }
}
```

The code is compiled in Visual Studio Community 2019. In A console application .NET Framework 4.7.2. It runs on Win 10, Intel i7 6 core (i7-5820K) with 64GB of RAM. The issue is not only on this computer, I have seen it on a Ryzen 7, 5800H laptop too.

Examples of errors (note that these were produced with the Gaussian filter replaced with an Median Filter in some cases):

In Windows Event Viewer I get errors like these:

![image](https://user-images.githubusercontent.com/36692294/155546757-452ab58b-9c5b-4e16-95d8-bcb6518f2361.png)

and 

![image](https://user-images.githubusercontent.com/36692294/155547098-0fb4439e-9ea4-458a-85ab-81e8cdc2cf14.png)

These are quite uninformative but for the first of these (which is the most common) I manage to get a screen dump of the application showing:

![image](https://user-images.githubusercontent.com/36692294/155547614-eed8bef1-f9a0-494c-8082-4d7accc834f8.png)

Ive also manage to catch dumps like this:

![image](https://user-images.githubusercontent.com/36692294/155547902-92b6fa44-f05d-4bcb-9df7-60d07a790cf6.png)

A few (a little more informative) captures from the Event Viewer are:

![image](https://user-images.githubusercontent.com/36692294/155548528-9cd70cb2-9fd0-403c-a1c8-018279f76c8a.png)

![image](https://user-images.githubusercontent.com/36692294/155548629-c54b6ed1-a99b-4bd9-bed9-d5580efde0f9.png)

![image](https://user-images.githubusercontent.com/36692294/155548683-ba58556c-f252-49dd-93a6-6727b5a00e43.png)

From here I dont really know what to do. So I hope I can get some help. Perhaps it is just some stupid mistake Ive done that I have to take some special care when using SimpleITK in a threaded environment. Or perhaps there is something deeper hiding here. Grateful for some help.

**Comment by blowekamp** [comment]
Hello,

I haven't had a chance to test your code. But after looking at it I have notice two things:
 - There are no calls to SimpleITK in the main thread before the threading starts
 - The SimpleITK filters are not executed, really very little SimpleITK code is run.

This two points indicate there may be a problem with the initialization of the CSharp/SimpleITK library when concurrently accessed during library initialization.

There are a couple calls to SimpleITK before the thread `ThreadedLoop` that are commented out. Does the issue occur if they lines are not commented out? Why are they there?

**Comment by DrDryg** [comment]
Thanks a lot for your answer, it looks like it solves the issue to just first create a filter in the main thread! The out commented code was just there from some previous testing. If I include the initial creation of a filter in the main thread I don't get the crash (0 of 100 runs). If I don't include it I get 62 crashes out of 100 runs. So those numbers are rather convincing. I will continue my testing, I've had some cases before when it seemed to start working, but didnt. But it is very hopeful and consistent with previous behavior, that either the original much larger program crashed the first time it run or it just kept working. One question that remains is if SimpleITK is fully initialized after creating a single filter in the main thread or do I have to create many different object to initialize different parts of SimpleITK?

**Comment by blowekamp** [comment]
> One question that remains is if SimpleITK is fully initialized after creating a single filter in the main thread or do I have to create many different objects to initialize different parts of SimpleITK? Or is there some preferred way of initializing the library?

It is likely that the issue related to how and when Chap loads the native binary libraries not being concurrent thread safe. By just using any SimpleITK CSharp method in a single threaded fashion it ensure the native library is initialized safely.

The SimpleITK/ITK libraries are initialized with C++ static initialization which occurs automatically when the library is loaded. Most of the time this occurs when the executable or language library is loaded/imported. I suspect for CSharp is delaying this process.

I will add an entry to the FAQ to document this requirement before threading.

**Comment by blowekamp** [comment]
Could you please check if calling something as simple as like `itk.simple.Version_ToString()` also solved the problem?

Thanks

**Comment by DrDryg** [comment]
Using itk.simple.Version.ToString() doesnt solve the problem. But oddly, the  number of fails decreases with this line of code included.  I ran two batches with 100 runs each. With the ToString it fails in about 10% of the cases. Without it fails most of the cases.

**Comment by blowekamp** [comment]
Thank you for the question.
