### ISSUE TITLE
ImageSeriesReader.GetGDCMSeriesFileNames not able to get dicom files

### ISSUE THREAD

**Issue by TimZaragori** [SimpleITK/SimpleITK#1612]
I have a folder with all the images of my CT series but trying to retrieve them with `ImageSeriesReader.GetGDCMSeriesFileNames(dicom_dir)` returns an empty list. It seems that the function is unable to find the files if their path starts with a `.`. In my case, with the workstation I am using in the department to extract my images, it is always the case with as instance file names like `.CT..0003.0001.2022.03.08.17.15.11.796875.35115570.IMA`

I change my loading function to handle this particular case with the following:
```
def load_dicom_image(dicom_dir):
    series_reader = sitk.ImageSeriesReader()
    series_img_list = series_reader.GetGDCMSeriesFileNames(dicom_dir)
    if not series_img_list:
        series_img_list = [os.path.join(dicom_dir, _) for _ in os.listdir(dicom_dir)]
    series_reader.SetFileNames(series_img_list)
    series_reader.MetaDataDictionaryArrayUpdateOn()
    series_reader.LoadPrivateTagsOn()
    image = series_reader.Execute()
    return image
```
However, according to the answers in #1609, this is working only if the files are in the right order which is not my case. Thus, the only solution I found was to rename all the files if they are starting with `.`. Why `ImageSeriesReader.GetGDCMSeriesFileNames(dicom_dir)` is unable to find these files? Is there a trick to bypass this ?

**Versions**

SimpleITK Version: 2.1.1 (ITK 5.2)
python 3.8.12

**Comment by zivy** [comment]
Hello @TimZaragori 

This is a "feature" very deep in the software stack (SimpleITK->ITK->GDCM). The GDCM directory class [will not take into account unix type hidden file](https://github.com/malaterre/GDCM/blob/929db3d7ad5e7f70a50ba0873fda459fadb2f9a9/Source/Common/gdcmDirectory.h#L34). As the file names start with a dot they are hidden files and ignored by GDCM.

You will need to either rename the files or create symbolic links to them using names that do not start with dot. A safe and generic solution is to use a temporary directory, where we know that the renaming will not overwrite any other existing files, see code below. 

Note that this code will return the first series in a directory. If your directory contains multiple series you will have to add some more logic (will also likely require user interaction if they need to select a specific series from several).
```
import SimpleITK as sitk
import platform
import tempfile
import os
import shutil

def load_dicom_image(dicom_dir):
    file_names = os.listdir(dicom_dir)
    # create temporary directory with unique file names for all the files found in the
    # original directory. On OSX/linux these are soft links to the original files. On
    # Windows we need to copy them over due to OS limitations, takes more time.
    with tempfile.TemporaryDirectory() as tmpdirname:
        if platform.system() == "Windows":
            for i, fname in enumerate(file_names):
                shutil.copy(os.path.abspath(fname), os.path.join(tmpdirname, str(i)))
        else:
            for i, fname in enumerate(file_names):
                os.symlink(os.path.abspath(fname), os.path.join(tmpdirname, str(i)))
        # read from the temporary directory
        reader = sitk.ImageSeriesReader()
        reader.MetaDataDictionaryArrayUpdateOn()
        reader.LoadPrivateTagsOn()
        reader.SetFileNames(sitk.ImageSeriesReader_GetGDCMSeriesFileNames(tmpdirname))
        return reader.Execute()

```
