### ISSUE TITLE
N4 corrected image too bright

### ISSUE THREAD

**Issue by m-reuter** [SimpleITK/SimpleITK#1614]
Hi, 

thanks for this amazing project. 

I have a problem with N4 bias correction: 

When running the Examples/N4BiasFieldCorrection/N4BiasFieldCorrection.py
the corrected image is globally noticeably brighter than the input (+30 or more intensity increase in WM everywhere). This is for both images:  corrected_image and corrected_image_full_resolution (which are identical for me, except for float32 vs float64). 

This did not happen when running the N4 from ITK (in c++), where the corrected image has a similar overall brightness as the input. 

I am using v 2.1.1 installed with pip and am running this on a typical "orig" image from freesurfer (uchar) after converting it to nifti. It gets converted to float when it is read in. Doing an external conversion to float gives the same problem. 

What is also funny: i) it requires the input to N4 to be float, and ii) the output is written as a float image, but has only integer values in it? Even the corrected_image_full_resolution (float64) has only integers in it after it is written out. 

Thanks..

**Comment by blowekamp** [comment]
closed by #1613

**Comment by m-reuter** [comment]
Hi, this should not be closed. It is unrelated to my bugfix in #1613 .

**Comment by blowekamp** [comment]
Could you please provide the "N4 from ITK" code for comparison?

**Comment by m-reuter** [comment]
I looked into it more and the codes were using different masks by default, which caused the difference.
