### ISSUE TITLE
create mask of ball around voxel coordinate

### ISSUE THREAD

**Issue by m-reuter** [SimpleITK/SimpleITK#1618]
Not really an issue, but question or feature request: 

This may be simple, but I could not find it anywhere. I am trying to create a binary mask of a ball with a given radius around a give voxel coordinate. Is there a function for that? 

ApproximateSignedDistanceMap seems like shooting sparrows with cannons and is slow. And EllipseSpatialObject (and then rasterizing the object to image grid) does not seem to exists. 

Thanks for any hints.

**Comment by gdevenyi** [comment]
https://itk.org/ITKExamples/src/Filtering/MathematicalMorphology/CreateABinaryBallStructuringElement/Documentation.html

**Comment by gdevenyi** [comment]
https://stackoverflow.com/a/67370371

**Comment by m-reuter** [comment]
Thanks for the quick reply !!
Thresholding the Gaussian worked.
