### ISSUE TITLE
conversion to uint8 (uchar) not working when writing image on mac

### ISSUE THREAD

**Issue by m-reuter** [SimpleITK/SimpleITK#1619]
Hi, 

```
ucharimage = sitk.Cast(sitk.Clamp(floatimage,lowerBound=0,upperBound=255),sitk.sitkUInt8)
sitk.WriteImage(ucharimage, outname)
```
converts float to uhcar and writes a uchar image on linux, but not on Mac. There the pixel type is changed to uchar, but the written image is still float.

**Comment by dave3d** [comment]
That shouldn't happen.  Here is a test program I just tried on my Mac:

    import SimpleITK as sitk

    floatimage = sitk.GaussianSource()

    ucharimage = sitk.Cast(sitk.Clamp(floatimage,lowerBound=0,upperBound=255),sitk.sitkUInt8)
    sitk.WriteImage(ucharimage, "gaussian.nrrd")

    gaussian = sitk.ReadImage("gaussian.nrrd")
    print(gaussian.GetPixelIDTypeAsString())

And here is the output I got on my Mac:

    8-bit unsigned integer

So the file I wrote out was with unsigned char voxels, as expected.

**Comment by m-reuter** [comment]
thanks for testing. I get the same result as you. 

It is a bug in FreeSurfer v6 mri_info command showing the wrong pixel type, which has been fixed in newer releases. On my mac I was using version 6 and on linux version 7.2 of FreeSurfer.
