### ISSUE TITLE
Let sitk.DiscreteGaussianImageFilter support difference variances per direction

### ISSUE THREAD

**Issue by jonasteuwen** [SimpleITK/SimpleITK#163]
Referring to the discussion at http://public.kitware.com/pipermail/insight-users/2017-May/054511.html

The DiscreteGaussianImageFilter should allow setting variances for each direction. This can be useful when filter in-plane but not in-depth before resampling.

**Comment by blowekamp** [comment]
Thanks for reporting this missing option.

**Comment by blowekamp** [comment]
I examined the related reclusive filters. The `SmoothingRecursiveGaussianImageFilter` is also missing the array interface, while the other Laplacian, GradientMagnitude only have the scalar.
