### ISSUE TITLE
OSX dotnet packaging issue (".dylib" vs ".so")

### ISSUE THREAD

**Issue by vincenzoml** [SimpleITK/SimpleITK#1634]
Hi,

I have tested the dotnet package of the release `SimpleITK-2.2.0rc2.post79`, and found out that I need to rename the native library from ".so" to ".dylib" in order for the dotnet runtime to find it. I wonder if the csharp test is run using mono, maybe, and then that could be the culprit. I'm using the (now standard) dotnet package from microsoft, which is mit-licensed and multi-platform, and can also cross-compile packages.

Apart from this bug, I've been able to cross-compile from any to any of win,linux, and osx with no problem a test program. That's amazing!

To reproduce the osx bug one should do the following steps on a mac: 

1) install the dotnet sdk from microsoft https://dotnet.microsoft.com/en-us/download

2) clone this repository https://github.com/vincenzoml/SimpleITK-FSharp-Example

3) cd to the repository and run `dotnet run`

Actually I *cannot* execute the above three steps as I cannot install dotnet on the only osx account that I have. So what I did (but it should make no difference) is:

1) clone the repository on a machine with dotnet installed

2) run `dotnet publish -r osx-x64` 

3) copy the two files in `bin/Debug/net6.0/osx-x64/` to the target osx machine

The SimpleITK version and ITK version should be printed (note that msbuild will download the zip file from the simpleitk release page automatically), however that does not happen. Here is the problem

```
vincenzo@maxima ~ % ./testSimpleITK
Unhandled exception. System.TypeInitializationException: The type initializer for 'itk.simple.SimpleITKPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSimpleITKCSharpNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibSimpleITKCSharpNative, 1): image not found
   at itk.simple.SimpleITKPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_SimpleITK(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at itk.simple.SimpleITKPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at itk.simple.SimpleITKPINVOKE.SWIGExceptionHelper..ctor()
   at itk.simple.SimpleITKPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at itk.simple.SimpleITKPINVOKE.Version_VersionString()
   at itk.simple.Version.VersionString()
   at <StartupCode$testSimpleITK>.$Program.main@() in /mnt/c/Users/vince/data/local/repos/SimpleITK-FSharp-Example/Program.fs:line 1
zsh: abort      ./testSimpleITK
```

Setting the `DYLD_PRINT_LIBRARIES` environment variable prints a lot more information which however does not clarify the issue any further.

Renaming the native library from .so to .dylib on the target machine solves the problem.

**Comment by vincenzoml** [comment]
Just for completeness, in a new branch of that repository I added a csharp test and can confirm that the bug does not depend on the choice of the language, that is, is also present in the csharp version.

**Comment by blowekamp** [comment]
You are correct that we are building and testing the the Mac CSharp libraries with mono.

**Comment by vincenzoml** [comment]
I found out that it's actually a bug in mono, inherited from glib, at least according from one answer to this question:

https://stackoverflow.com/questions/47225350/how-to-access-native-apis-from-mono-command-line-app

So probably "the right way" is to rename the .so to .dylib before zipping. The "very right way" would be to use dotnet instead of mono, as dotnet is converging on all platforms. As far as I understand, mono will become much less relevant with the release of .net 7 which is now at preview 3.

**Comment by vincenzoml** [comment]
See here https://www.mono-project.com/docs/advanced/pinvoke/ for a more official statement on the osx bug in mono.

**Comment by blowekamp** [comment]
Here is a PR (#1637) which updates the CMake code to produce a dylib library on OSX. It works locally, and on the current azure devops CI. It's not clear when mono was updated to support dylib, but it seems to currently support dylibs.

**Comment by vincenzoml** [comment]
Are you completely sure it's OK to still use mono, and not dotnet? I am unsure whether mono is going to be outdated soon.

**Comment by vincenzoml** [comment]
It's true, all managed dlls are binary compatible between mono and dotnet, this includes the managed part of simpleITK, and compiled programs. There is something fishy here though: even if all dlls should be compatible, they are binary different between the different versions of the simpleITK binary (one per platform). 

Ideally, there should be a way to produce just ONE dll (maybe the windows one would be the ideal candidate) and then just the native library for each platform. 

Right now I don't know more about this aspect, and am referencing the managed library by path depending on the architecture just to be sure. That has pitfalls though, for instance I need to set RuntimeIdentifier in the project file even if the user did not want to do that.

**Comment by vincenzoml** [comment]
Awaiting the nightly binaries but where will I find them? Just on the releases page?

**Comment by blowekamp** [comment]
> Awaiting the nightly binaries but where will I find them? Just on the releases page?

The nightly binaries are published here: https://github.com/SimpleITK/SimpleITK/releases/tag/latest



> It's true, all managed dlls are binary compatible between mono and dotnet, this includes the managed part of simpleITK, and compiled programs. There is something fishy here though: even if the three managed dlls of the three simpleITK packages should be compatible, they are binary different between the different versions of the simpleITK binary (one per platform).
> 

The thing todo would be to example the SWIG generated cs files to determine what the difference it between the platforms in the source code. Binary difference could be from the source code or the compiler generate code, or even just some meta information encoded by the compiler ( paths?, os?, versions?).

**Comment by vincenzoml** [comment]
I tested the binary release by producing binaries on linux for linux, windows and osx, using the repository here: https://github.com/vincenzoml/SimpleITK-dotnet-quickstart 

then I also tested the binary release by compiling the same code directly on windows. I can't do the same directly on osx but I have no reasons to think it wouldn't work.

So far this is excellent!

Please feel free to link the above repository, I'd like to keep it up to date, add more documentation and see if other people is interested in using simpleitk with dotnet. 

Eventually I will create a nuget package, or find someone who can do it (unless the simpleitk organization itself wants to take the burden), but for the moment I want to try to keep the repository up-to-date with the latest simpleitk version. How do I track the new releases (nightly for the moment, and then stable from when stable will distribute the binaries)?

**Comment by vincenzoml** [comment]
I want to add, dotnet can be installed without admin rights following the instructions here:

https://docs.microsoft.com/it-it/dotnet/core/tools/dotnet-install-script

After doing this I confirm that just cloning the quickstart repository and running "dotnet run" is sufficient to make SimpleITK work on osx.

**Comment by blowekamp** [comment]
Welcome to the SimpleITK community. 

This looks terrific! It looks like the perfect way to use SimpleITK in the .Net environment. Glad to hear the new fix for OS X worked.

The best place for this would be adding it to the main SimpleITK repository in the "Examples" directory. Would you be interested in contributing the quickstarts in a PR?

> I want to try to keep the repository up-to-date with the latest simpleitk version. How do I track the new releases (nightly for the moment, and then stable from when stable will distribute the binaries)?

SimpleITK 2.2rc3 will be published in the next couple of week, after a couple build issues are resolved. That should be a version publish in the Github Releases that can be used in this quickstart/example. The nightly version changes whenever there are changes in the repository. This also deleted the old nightly version so that the old binaries are no longer available. This enables manual downloads and development with latest features but makes it difficult to depend or publish items which depend on the nightly builds. 

>Eventually I will create a nuget package, or find someone who can do it (unless the simpleitk organization itself wants to take the burden), but for the moment I want to try to keep the repository up-to-date with the latest simpleitk version. How do I track the new releases (nightly for the moment, and then stable from when stable will distribute the binaries)?

This is another terrific contribution. It would be great to publish an official SimpleITK nugget package directly from the SimpleITK project. Integrating some scripts and processes into the release process to also publish nuggets is certainly something we can accommodate. How to build the nugget, providing code to do so, testing and what changes to the current building and packages are all welcomed contributions.

**Comment by blowekamp** [comment]
@vincenzoml  The SimpleITK [v2.2rc3](https://github.com/SimpleITK/SimpleITK/releases/tag/v2.2rc3) release contains the fixed OS X CSharp package. The quick start example you wrote can be updated to reference this release tag.

The published packages RC package resolve this issue.

**Comment by vincenzoml** [comment]
Hi, sorry for not replying for quite some time. So: it would be great to contribute to the examples section of the simpleitk site. Is it managed in github? I don't have time right now, I am fully overbooked until july, but then will do my best to submit a PR.

Thanks for the release, will test as soon as possible (unfortunately maybe in july too).
