### ISSUE TITLE
ImageSeriesReader reading images incorrectly

### ISSUE THREAD

**Issue by six6egrees** [SimpleITK/SimpleITK#1636]
Hi,

I am using SimpleITK 2.1.1.1 build py37h82bb817_0. I am trying to read a DICOM series with python containing a binary mask from a segmentation. ImageSeriesReader returns an empty image with only zeroes. The image can be correctly opened with 3D Slicer or ImageJ. Using ImageFileReader on a single slice, the resulting image is better, although instead of zeros and ones I get zeros and 0.9999.... which is also surprising, given that the RescaleSlope of the file is 1. Here is the code I use:

```
import SimpleITK as sitk
import os 

test_path = '.\\SE5'

reader = sitk.ImageSeriesReader()  
dicom_names = reader.GetGDCMSeriesFileNames(test_path)
reader.SetFileNames(dicom_names)
image = reader.Execute()

reader2 = sitk.ImageFileReader()
reader2.SetImageIO('GDCMImageIO')
reader2.SetFileName(os.path.join(test_path, '0000006K'))
image2 = reader2.Execute()

filt = sitk.MinimumMaximumImageFilter()
filt.Execute(image)  
print(filt.GetMaximum()) #0.0

filt.Execute(image2)
print(filt.GetMaximum()) #0.9999999975098001
```

Here are the relevant DICOM attributes of the image (I have omitted attributes unrelated to pixel data):

[0020,0032]	ImagePositionPatient -348.632812, -348.632812, -872.330017	
[0020,0037]	ImageOrientationPatient	 1, 0, 0, 0, 1, 0	
[0028,0002]	SamplesPerPixel	1	
[0028,0004]	PhotometricInterpretation	MONOCHROME2	
[0028,0010]	Rows	256	
[0028,0011]	Columns	256	
[0028,0030]	PixelSpacing 2.734375, 2.734375	
[0028,0100]	BitsAllocated	16	
[0028,0101]	BitsStored	16	
[0028,0102]	HighBit	15	
[0028,0103]	PixelRepresentation	1	
[0028,1050]	WindowCenter	0.5	
[0028,1051]	WindowWidth	1	
[0028,1052]	RescaleIntercept	0	
[0028,1053]	RescaleSlope	1	
[0054,0081]	NumberOfSlices	259

**Comment by zivy** [comment]
Hello @six6egrees,

Please see if [this FAQ entry](https://simpleitk.readthedocs.io/en/master/faq.html#why-does-my-image-appear-to-be-empty-all-black-blank-when-visualized) addresses your question. Is the volume really all zeros or is it just the visualization?

With respect to the `0.9999...` value vs. 1, this looks like the reading is interpreting the image as having floating point values (rescale slope can be any decimal string 1.0, 0.1 etc).

**Comment by zivy** [comment]
Hi @six6egrees,

There is no resampling when the image is just read. 

The only thing I can think of is that the series is potentially corrupted, multiple slices occupy the same location. When you read them in, a slice without a segmentation "overwrites" the one with segmentation (they are both in the same physical location). This is just an educated guess.

Can you share the DICOM series so that we can reproduce the issue and debug it? Otherwise, I can only guess and that won't get you very far.

**Comment by six6egrees** [comment]
Thank you, @zivy 

That could be the case. I'm having some problems with Slicer now: while Slicer can load and correctly visualize the image, when I tried to export the data as a DICOM series the exported files become empty. Which is very strange.

I will check tomorrow if the data can be shared. Meanwhile I'll try to look into the files, maybe I can reproduce this error with synthetic data which I can share.

**Comment by six6egrees** [comment]
@zivy Turns out the source of the problem was a very low RescaleSlope that only occurs if the slice has non-zero pixel values, essentially setting the whole image to zeros. Slicer and ImageJ must have ignored it.

Thank you for your help, and sorry to waste your time!

**Comment by six6egrees** [comment]
Dear @zivy 

Although changing the rescale slope of my files solved my problem, I had some more time to look into this and there is indeed a very unexpected behaviour from SimpleITK. It all boils down to DICOM image series with variable RescaleSlope parameters. I am now attaching a zip archive containing a file set created with SimpleITK using the method described in the [documentation](https://simpleitk.readthedocs.io/en/v1.1.0/Examples/DicomSeriesFromArray/Documentation.html) with slight modifications. In the file set, `4.dcm` and `5.dcm` are slices containing a rectangular area filled with the value '1'. All other voxels are set to zero in the entire series. After saving these files with `RescaleSlope = 1`, I modified the `RescaleSlope` of `'0.dcm'` to 10, `'4.dcm'` to 0.9 and all the other slices to 4.5.


[test_files.zip](https://github.com/SimpleITK/SimpleITK/files/8643481/test_files.zip)

The behaviour is the following: if the first slice in the series has an integer `RescaleSlope` value, than any other slice following it will have their `RescaleSlope` value rounded down to the nearest integer when `ImageSeriesReader` scales them during reading. In the above example, the slice corresponding to `'4.dcm'` will be empty and the slice corresponding to `'5.dcm'` will have values equal to 4 instead of 4.5. Setting the `RescaleSlope` of `'0.dcm'` to a non-integer value eliminates this problem. It also doesn't matter what type I use in python to set the value (using `float(10.0)` and `int(10)` gives the same results), the value representation of the attribute in the DICOM file stays exactly the same.

**Comment by zivy** [comment]
Hello @six6egrees,

Can confirm that this is indeed a bug. 

When reading an image series, the pixel type of the image series is deduced from the pixel type of the first slice. This works 99% of the time, but it is not a correct assumption as you've shown (the DICOM standard allows for this, so it is not a contrived example). A quick workaround is to explicitly specify the pixel type when reading. 

Code illustrating the problem and workaround:
```
import SimpleITK as sitk

series_files = sitk.ImageSeriesReader_GetGDCMSeriesFileNames("test_files")
print(f"Pixel type deduced from volume (equivalent to using image 0): {sitk.ReadImage(series_files).GetPixelIDTypeAsString()}")
print(f"Pixel type deduced from image 0: {sitk.ReadImage(series_files[0]).GetPixelIDTypeAsString()}")
print(f"Pixel type deduced from image 1: {sitk.ReadImage(series_files[1]).GetPixelIDTypeAsString()}")

sitk.Show(sitk.ReadImage(series_files), "automatically determined pixel type from first slice")
sitk.Show(sitk.ReadImage(series_files, sitk.sitkFloat32), "user defined pixel type")
```

**Comment by zivy** [comment]
@blowekamp can you take a look at this?

I suspect the [issue arises here](https://github.com/SimpleITK/SimpleITK/blob/aff11ddc90bde4cc1669bb54a60dec52d50c0507/Code/IO/src/sitkImageSeriesReader.cxx#L137-L145), but not sure.

**Comment by blowekamp** [comment]
@zivy Can you please make a PR adding your code to reproduce the issue as a test? Then I can work on a fix.
