### ISSUE TITLE
How's DoubleThreshold working?

### ISSUE THREAD

**Issue by Secret-Lin** [SimpleITK/SimpleITK#1639]
The description of DoubleThreshold is: 
Double threshold uses the narrow threshold image as a marker image and the wide threshold image as a mask image in the geodesic dilation. Essentially, the marker image (narrow threshold) is dilated but constrained to lie within the mask image (wide threshold). Thus, only the objects of interest (those pixels that survived the narrow threshold) are extracted but the those objects appear in the final image as they would have if the wide threshold was used.
But can anyone give me a mathematical explanation if I pass [L1, L2, L3, L4] as input parameters? For example, I pass [L1,L2] in binary filter, I get { x| L1< x <L2 }.
Or where can I access the source code of this filter? I Tried python but only get the SWIG. And I can not build the C++ version on my mac.
Thx a lot!!!!!!

**Comment by zivy** [comment]
Hello @Secret-Lin,

Please see the [source code from ITK](https://github.com/InsightSoftwareConsortium/ITK/blob/70351d1fe4832a10186dc19b78e131e0ae8d0995/Modules/Filtering/MathematicalMorphology/include/itkDoubleThresholdImageFilter.hxx#L66-L110).

**Comment by blowekamp** [comment]
I believe the documentation string you are looking for are in SimpleITK as under the SetThreshold[1-4] methods:
https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1DoubleThresholdImageFilter.html#a0027bd3b80d1b443bc73b9df1b0a88a0

**Comment by blowekamp** [comment]
Thank you for the question.
