### ISSUE TITLE
Python 3.11 wheels

### ISSUE THREAD

**Issue by Czaki** [SimpleITK/SimpleITK#1642]
Python 3.11 beta 1 wheels were released on May 19, 2022. Python developer guide promise that python binary interfaces will be stable, so it allows starting to build wheel preparation now (wheels built with beta release should work with the stable release if depends only on public API).  

As release wheels for python 3.10 take a long time and python 3.11 will bring really nice improvements for error reporting then many people may want to switch their base python development environment to python 3.11. 

So I would like to ask if there are plans to release python 3.11 wheels close to the python 3.11 release?

**Comment by blowekamp** [comment]
Adding a link to [PEP 664 – Python 3.11 Release Schedule ](https://peps.python.org/pep-0664/). The current scheduled release data for Python 3.11 is 3.11.0 final: Monday, 2022-10-03. 

We use Azure Dev Ops Hosted servers for the majority of the CI and packaging for SimpleITK. They maintain their [virtual environments on Github](https://github.com/actions/virtual-environments). Having these VM support Python 3.11 will be a blocker to get the 3.11 wheels.

We have not specific timeline for 3.11 wheels, but anticipate being more timely with them than the 3.10 wheels.

**Comment by Czaki** [comment]
cibuildwheel maintainers already working on having the possibility to build wheels with python 3.11 (installing from pkg and nuget) independently of python on the host runner.

I do not see your configuration (yaml), but if you want I may help with trying to use cibuildwheel.

**Comment by Czaki** [comment]
> While Windows and MacOSX are built natively on the AZP hosted systems. These first build the SimpleITK "core" C++ libraries, then as a separate build

Did I correctly understand that `ctest` call is building base libs? 

https://github.com/SimpleITK/SimpleITK/blob/2ea09383411f7429fca348b9b0634989fb3c4382/Testing/CI/Azure/templates/package-win-job.yml#L22 

Or is it in another place?

**Comment by blowekamp** [comment]
Yes, ctest is used to configure, build, and test the "base" or "core" SimpleITK C++ library and then submit the results to the cdash server. This core library is then used for each version python, java, C# etc.

Then ctest is used again for the python wheel: https://github.com/SimpleITK/SimpleITK/blob/2ea09383411f7429fca348b9b0634989fb3c4382/Testing/CI/Azure/scripts/win_build_python.sh

**Comment by Czaki** [comment]
@blowekamp there are no linux and windows 3.11 wheels on pypi. I also do not see them on the release page. Could this be fixed? 
https://github.com/SimpleITK/SimpleITK/releases/tag/v2.2.1

**Comment by blowekamp** [comment]
The wheels have been uploaded.
