### ISSUE TITLE
Want to add an interface for CompositeTransform to get the composite result (single Transform)

### ISSUE THREAD

**Issue by GouZi2019** [SimpleITK/SimpleITK#1649]
Hi, 

Thanks for your efforts to separate the `CompositeTransform` from `Transform` and make the use of it clean and clear.

Everything is going well until I realize the scaling and squaring approach. The method requires a field _**s**_ to be cumulatively composed with itself _n_ times. I implemented it with the following codes:
```
# square it n times
n = 10
s = sitk.CompositeTransform(sitk.DisplacementFieldTransform(a_little_v))
for __ in range(int(n)):
    s.AddTransform(s)
```

After the for-loop, I used _**s**_ to deform the image and get the displacement field all takes very much time.
After I used `FlattenTransform()` and `GetNumberOfTransforms()`, I found that there are 1024 transforms in total. It's easy to understand why it takes a very long time to resample a image, since _**s**_ has to composite1024 transformations!

In order to speed up, I just need to keep the result after each composite, however I found out that `CompositeTransform` does not have such an interface. Referring to #1291 , I implemented it in the following way:
```
s = sitk.DisplacementFieldTransform(a_little_v)
trans2displace = sitk.TransformToDisplacementFieldFilter()
trans2displace.SetReferenceImage(self.img0)

for __ in range(int(n)):
    s_temp = sitk.CompositeTransform([s,s])
    s = sitk.DisplacementFieldTransform(trans2displace.Execute(s_temp))
```
This requires me to convert the `CompositeTransform` to `DisplacementField` and then to `DisplacementFieldTransform` and finally to `CompositeTransform`.

Is it possible to expect a more elegant interface built directly into the `CompositeTransform` to get the composite result directly?

**Comment by GouZi2019** [comment]
> For this case, doing the math directly on the displacement field image would be the way to go. After the computation, the it could be converted into a single DisplacementFieldTransform.

Hi, blowekamp

Does sitk have a filter to calculate the displacement field composition?

**Comment by zivy** [comment]
Hello @GouZi2019,

The implementation you have is actually what I have done in the past. I would discourage maintaining multiple displacement fields in memory at the same time if they are supposed to be composed. Keeping the memory usage low by combining them in each iteration is safer in terms of program completion (less likely to run out of memory). 

I don't think there is an elegant solution with respect to the `CompositeTransform` interface. The composite transform does not necessarily contain deformation fields, so the output type needs to be the most generic transform type from those contained in the composite. A simplistic approach would be to always return a displacement field transform, but that consumes a lot of memory compared to a composition of global transformations (affine).
