### ISSUE TITLE
[Bug]: Nifti File writer does not save sitkImage directions

### ISSUE THREAD

**Issue by waltsims** [SimpleITK/SimpleITK#1651]
Hi all,

I'm trying to write a simple script to sample a volume and save the resulting samples as NIFTI files in the same coordinate space as the original volume. In the process of doing this, I discovered that sitk.WriteImage() does not save the direction meta data to the NIFTI file.

I believe this is a bug and have a minimal example to reproduce the behavior. 

```Python
import SimpleITK as sitk
import numpy as np

if __name__ == '__main__':
    theta = np.deg2rad(20)
    img = sitk.GridSource(size=(64, 64), outputPixelType=sitk.sitkUInt16)
    euler2d_transform = sitk.Euler2DTransform()
    euler2d_transform.SetAngle(theta)
    img = sitk.Resample(img, euler2d_transform)
    img.SetDirection(
        np.multiply(np.reshape(img.GetDirection(), (2, 2)),
                    np.reshape(euler2d_transform.GetMatrix(), (2, 2))).flatten())
    img.SetOrigin(euler2d_transform.TransformPoint(img.GetOrigin()))
    sitk.WriteImage(img, 'test.nii.gz')
    img1 = sitk.ReadImage('test.nii.gz')
    assert img == img1
```

This sample returns the following error:

``` Error
RuntimeError: Exception thrown in SimpleITK Equal: /Users/runner/work/1/sitk-build/ITK-prefix/include/ITK-5.2/itkImageToImageFilter.hxx:220:
ITK ERROR: BinaryFunctorImageFilter(0x7f88acc9c650): Inputs do not occupy the same physical space! 
InputImage Direction: 9.3969262e-01 0.0000000e+00
0.0000000e+00 9.3969262e-01
, InputImage_1 Direction: 1.0000000e+00 0.0000000e+00
0.0000000e+00 1.0000000e+00

	Tolerance: 1.0000000e-06

```
Happy to discuss if I am mistaken.

Best,
Walter

**Comment by blowekamp** [comment]
Your matrix is not orthonormal, and contains scaling.

You are using the element-size multiplication`np.multiply` not matrix multiplication `np.matmul`.

**Comment by waltsims** [comment]
Wow, thanks for pointing that out! If SimpleITK had warned it was discarding a non-orthonormal direction matrix on saving, I would have found this sooner.

**Comment by blowekamp** [comment]
Please consider reporting the request for a warning to ITK: 
https://github.com/InsightSoftwareConsortium/ITK/issues
