### ISSUE TITLE
How to solve compilation errors under arm64 architecture

### ISSUE THREAD

**Issue by wangyuyuyujun** [SimpleITK/SimpleITK#1657]
version：
1.simpleitk:2.1.1.1
2.ITK:5.2.1
3.python:3.7.9
4.SWIG:4.0.2
5.Gtest:1.18
6.Lua:5.3.5
I want to build simpleitk on the arm64 architecture. After I install the above dependencies, ccmake displays as follows:
![}V8 IA1{$ODGSE$ 20LFU~Q](https://user-images.githubusercontent.com/103105509/178098936-cf72b259-48d0-4d70-84de-670548c63a0d.png)
When ccmake is executed successfully, execute the command make -j$(nproc) to compile simpleitk, and the following error occurs:
![{W EK{{LSX4LZ{T_S2_((D5](https://user-images.githubusercontent.com/103105509/178098980-c10fd94b-f7c5-476d-89b7-429c6550e77f.png)
Considering that there was an error in compiling the file in examples, I closed the examples in ccmake, and then the compilation and installation succeeded. However, the above error was reported when using simpleitk to test the use case (HelloWorld). I don't know what the problem is. I hope you can help me. Thank you very much

**Comment by blowekamp** [comment]
Please enable "Module_SimpleITKFilters" in your ITK build.

**Comment by wangyuyuyujun** [comment]
> Please enable "Module_SimpleITKFilters" in your ITK build.

According to your description, I solved this problem. Thank you very much
