### ISSUE TITLE
ObjectnessMeasureImageFilter over multiple scales

### ISSUE THREAD

**Issue by mareikethies** [SimpleITK/SimpleITK#1658]
Hi, 
is there a way to compute the response of the ObjectnessMeasureImageFilter as the maximum over multiple scales? This is typically done, e.g., for the Frangi vesselness filter to detect vessel-like structures on different scales. 
Any idea would be appreciated.

**Comment by gdevenyi** [comment]
This is in C++ pure ITK, but it might give you some ideas,
https://github.com/BIC-MNI/EZminc/blob/ITK4/tools/itk_vesselness.cpp

**Comment by gdevenyi** [comment]
As this place is for bugs, you might have a better time at https://discourse.itk.org/

**Comment by zivy** [comment]
Hello @mareikethies,
The relevant filters are [SmoothingRecursiveGaussianImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1SmoothingRecursiveGaussianImageFilter.html), [JoinSeriesImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1JoinSeriesImageFilter.html) and [MaximumProjectionImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1MaximumProjectionImageFilter.html).

Code below:
```
import SimpleITK as sitk

sigmas = [2, 4, 8, 16]
input_image = sitk.ReadImage("fundus.png", sitk.sitkFloat32)

# Set the parameters for the objectness measure according to specific input, 
# for example the vessels in the fundus image are dark, so brightObject=False
images = [
    sitk.ObjectnessMeasure(
        sitk.SmoothingRecursiveGaussian(input_image, s),
        alpha=0.5,
        beta=0.5,
        gamma=5.0,
        scaleObjectnessMeasure=False,  # changed from default value
        objectDimension=1,
        brightObject=False, # changed from default value
    )  
    for s in sigmas
]
result = sitk.MaximumProjection(sitk.JoinSeries(images), projectionDimension=images[0].GetDimension())
sitk.WriteImage(result, "vesselness_multiscale.mha")
```

Input and resulting output image:
![input](https://user-images.githubusercontent.com/338645/178289514-756cd74b-6f6c-4440-9045-79725d7d44e8.png)
![output](https://user-images.githubusercontent.com/338645/178289913-d65d8283-e322-47af-9780-9b8680976f4b.png)

**Comment by mareikethies** [comment]
Thanks a lot!

**Comment by blowekamp** [comment]
Just the MaximumImageFilter can be used over the MaximumProjectionImageFilter. Something like:

```
result = sitk.Maximum(*images)
```

should work.

**Comment by zivy** [comment]
Following @blowekamp's suggestion the code has been updated. Note that the relevant filter is NaryMaximumImageFilter and not MaximumImageFilter which only works for two images.
