### ISSUE TITLE
Median averaging through numpy and SimpleITK gives different outputs

### ISSUE THREAD

**Issue by Gab-D-G** [SimpleITK/SimpleITK#1659]
Hi,

I attempted generating an average image from a set of images using the https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1MedianProjectionImageFilter.html. The set of images was first concatenated to form a 4D image with https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1JoinSeriesImageFilter.html before averaging over the 4th dimension (see code below). However, I compared the output with a numpy implementation I was previously using, and the output from SITK seems less sensible. I am not sure what could lead those divergences between the two implementations.

```python
########################## numpy

import SimpleITK as sitk
import numpy as np
file_list = ['template_sharpen_shapeupdate_anat_mask.nii.gz', 'template_sharpen_shapeupdate_output_warped_image.nii.gz', 'template_sharpen_shapeupdate_anat.nii.gz', 'template_sharpen_shapeupdate.nii.gz']

array_list = []
for file in file_list:
    array = sitk.GetArrayFromImage(sitk.ReadImage(file))
    shape = array.shape # we assume all inputs have the same shape
    array = array.flatten()
    array_list.append(array)

concat_array = np.array(array_list)
average = np.median(concat_array, axis=0)
average = average.reshape(shape)

average_img = sitk.GetImageFromArray(average, isVector=False)
average_img.CopyInformation(sitk.ReadImage(file_list[0]))
sitk.WriteImage(average_img, 'median_numpy.nii.gz')


########################## SITK
### The code below was run with SimpleITK==2.2.0rc3

import SimpleITK as sitk
file_list = ['template_sharpen_shapeupdate_anat_mask.nii.gz', 'template_sharpen_shapeupdate_output_warped_image.nii.gz', 'template_sharpen_shapeupdate_anat.nii.gz', 'template_sharpen_shapeupdate.nii.gz']

image_list = []
for file in file_list:
    image_list.append(sitk.ReadImage(file, sitk.sitkFloat64))
joined = sitk.JoinSeries(image_list)

# the projection filters in 4D can only operate in versions >=v2.2rc1 https://github.com/SimpleITK/SimpleITK/releases/tag/v2.2rc1
project_filter = sitk.MedianProjectionImageFilter()
project_filter.SetProjectionDimension(3)
median = project_filter.Execute(joined)
sitk.WriteImage(median, 'median_sitk.nii.gz')

```
![image](https://user-images.githubusercontent.com/34081874/178570710-60c6a50a-0b04-4a9f-b272-41b43af5329e.png)

**Comment by zivy** [comment]
Hello @Gab-D-G,

The issue is that you aren't creating an average image, you are creating a median image. When the number of inputs to the median computation is **even**: numpy returns the average of the two middle values, ITK/SimpleITK returns the larger of the two.

Likely reasoning behind ITK choice (makes this a feature not a bug): When estimating a label image using a median voting scheme, combining output of multiple classifiers, we don't want to create values that weren't in the original images.

Below is a minimal working example illustrating the difference. Comment out one of the lines in the `image_list` to see that when the number of entries is odd the two implementations return the same value:
```
import SimpleITK as sitk
import numpy as np

image_list = [sitk.Image([1]*3,sitk.sitkFloat64) + 1000,
              sitk.Image([1]*3,sitk.sitkFloat64) + 2000,
              sitk.Image([1]*3,sitk.sitkFloat64) + 3000,
              sitk.Image([1]*3,sitk.sitkFloat64) + 4000]
concat_array = np.array([sitk.GetArrayFromImage(img).flatten() for img in image_list])

med_sitk = sitk.MedianProjection(sitk.JoinSeries(image_list), image_list[0].GetDimension())[:,:,0]
med_np = np.median(concat_array, axis=0)

print(f"SimpleITK median: {med_sitk[0,0,0]}.")
print(f"numpy median: {med_np[0]}.")
```

**Comment by gdevenyi** [comment]
@zivy one thing I can't find is anywhere that documents this implementation detail, I can find it in the "Notes" section for numpy, https://numpy.org/doc/stable/reference/generated/numpy.median.html

If this isn't mentioned somewhere, I think it's a documentation BUG

**Comment by zivy** [comment]
@gdevenyi, this is a gray area between "bug" in ITK [code](https://github.com/InsightSoftwareConsortium/ITK/blob/23da3dfa79152648f3d38050ee147df47f41ce0a/Modules/Filtering/ImageStatistics/include/itkMedianProjectionImageFilter.h#L71-L77) and "bug" in ITK [documentation](https://github.com/InsightSoftwareConsortium/ITK/blob/23da3dfa79152648f3d38050ee147df47f41ce0a/Modules/Filtering/ImageStatistics/include/itkMedianProjectionImageFilter.h#L29-L47).

Would you be willing to create a DOC pull request on this for ITK? This is automatically propagated into the SimpleITK documentation - so two birds with same stone.

**Comment by blowekamp** [comment]
Recently there were some changes in the ITK LabelMap filters related to the computation of the median. For that particular case the computation involved histograms: https://github.com/InsightSoftwareConsortium/ITK/pull/2525

But similar consideration for defined the "correct" behavior, and correcting the algorithm to that could be made.

**Comment by blowekamp** [comment]
As discussed this behavior and definition for the median operation comes from ITK. If a discussion and change to the algorithm or additional documentation is to take place, an [issue in ITK](https://github.com/InsightSoftwareConsortium/ITK/issues).
