### ISSUE TITLE
Is it possible to transform points using a defined resampling grid?

### ISSUE THREAD

**Issue by Vathsan** [SimpleITK/SimpleITK#1660]
I was referring to https://simpleitk.org/SPIE2019_COURSE/02_images_and_resampling.html and use the following logic to Resample the registered image (to get rid of the black pixels).
```
extreme_points = [moving_image.TransformIndexToPhysicalPoint((0,0)), 
                  moving_image.TransformIndexToPhysicalPoint((moving_image.GetWidth(),0)),
                  moving_image.TransformIndexToPhysicalPoint((moving_image.GetWidth(),moving_image.GetHeight())),
                  moving_image.TransformIndexToPhysicalPoint((0,moving_image.GetHeight()))]
inv_final_transform = final_transform.GetInverse()

extreme_points_transformed = [inv_final_transform.TransformPoint(pnt) for pnt in extreme_points]
min_x = min(extreme_points_transformed)[0]
min_y = min(extreme_points_transformed, key=lambda p: p[1])[1]
max_x = max(extreme_points_transformed)[0]
max_y = max(extreme_points_transformed, key=lambda p: p[1])[1]

# Use the original spacing (arbitrary decision).
output_spacing = moving_image.GetSpacing()
# Identity cosine matrix (arbitrary decision).   
output_direction = moving_image.GetDirection()#[1.0, 0.0, 0.0, 1.0]
# Minimal x,y coordinates are the new origin.
output_origin = [min_x, min_y]
# Compute grid size based on the physical size and spacing.
output_size = [int((max_x-min_x)/output_spacing[0]), int((max_y-min_y)/output_spacing[1])]

 moving_resampled = sitk.Resample(moving_image, output_size, final_transform, sitk.sitkLinear, 
                                 output_origin, output_spacing, output_direction)
```
I get the expected output.
Given a set of landmark coordinates (of fixed image) how do I find the corresponding set of landmark coordinates in the resampled image? 
I tried using **final_transform.TransformPoint(x, y))** function to achieve this. But this seems to transform the points using the fixed image grid as the resampling grid.

**Comment by Vathsan** [comment]
Hello @zivy,

Thanks for the quick reply. Maybe I should state what I am trying to achieve more clearly. 

1. I know a set of landmark coordinates (x and y) in the fixed image
![Screenshot from 2022-07-14 13-47-30](https://user-images.githubusercontent.com/29911181/179070556-671db614-037d-4be1-ac8a-4f7d6b6b91c9.png)

2. I use **final_transform.TransformPoint(x, y))**  to find the corresponding landmark coordinates in the registered image. Plot with transformed coordinates on the registered image,
![Screenshot from 2022-07-14 13-36-50](https://user-images.githubusercontent.com/29911181/179068777-79cddf5b-ad38-4524-9712-eaadeebedd96.png)

3. I resample the resulting image to get rid of the black pixels. Which works fine.

4. When I plot the transformed coordinates on the resampled image. They do not align. 
![Screenshot from 2022-07-14 13-45-15](https://user-images.githubusercontent.com/29911181/179070186-2c7ecc17-0f9c-4a79-9d5a-83945f39c03b.png)

I need to find the coordinates of the transformed landmark points on the resampled image. Any thoughts on this?

**Comment by zivy** [comment]
When you resample you are mapping points from the fixed image coordinate system to the moving image coordinate system, you do not need to map the landmarks from the fixed image to the moving_resampled image, you just use the same coordinates for plotting, pseudo-code:
```
landmarks_in_fixed_image[(x1,y1)...(xn,yn)]
tx = register(fixed_image, moving_image)

# plotting option 1
# be careful here as some points may map outside the moving image
plot_on_image(moving_image, [tx(pnt) for pnt in landmarks_in_fixed_image])
 
# plotting option 2
plot_on_image(resample(moving_image,fixed_image, tx), landmarks_in_fixed_image)
```

**Comment by Vathsan** [comment]
Thanks for the explanation. Since I am using plots for visualisation, Is there a way to retrieve the coordinates (after mapping) from the moving image coordinate system?

**Comment by zivy** [comment]
There is no need to retrieve the coordinates from the plot of the resampled moving image, you get the coordinates using the transformation:
```
landmarks_in_moving_image = [tx(pnt) for pnt in landmarks_in_fixed_image]
```
Also be aware that:
```
landmarks_in_moving_image_resampled == landmarks_in_fixed_image[(x1,y1)...(xn,yn)]
```
