### ISSUE TITLE
Update ElastixImageFilter and TransformixImageFilter Doxygen comments

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#1665]
The Doxygen comment strings are minimal to non-existent for the above classes. The class level documentation needs improvement.

**Comment by blowekamp** [comment]
@N-Dekker

**Comment by N-Dekker** [comment]
Initial work: https://github.com/SimpleITK/SimpleITK/compare/master...N-Dekker:SimpleITK:Add-doxygen-to-ElastixImageFilter  Is that the way you would like it?

**Comment by blowekamp** [comment]
The formatting looks good! Thank for for working on this 😄
