### ISSUE TITLE
Image registration. Filter does not support fixed image type

### ISSUE THREAD

**Issue by mikhail-rozum** [SimpleITK/SimpleITK#1672]
Hey there!
I'm new in ITK and now trying to reproduce the example from the documentation (https://simpleitk.readthedocs.io/en/master/link_ImageRegistrationMethod1_docs.html).
I use C#, and create a new Console application with the following code:

```
static void Main(string[] args)
{
    var fixedImgPath = @"1.png";
    var movingImgPath = @"2.png";

    var reader = new ImageFileReader();

    reader.SetImageIO("PNGImageIO");
    reader.SetFileName(fixedImgPath);
    var fixedImage = reader.Execute();

    reader.SetImageIO("PNGImageIO");
    reader.SetFileName(movingImgPath);
    var movingImage = reader.Execute();

    ImageRegistrationMethod R = new ImageRegistrationMethod();
    R.SetMetricAsMeanSquares();
    double maxStep = 4.0;
    double minStep = 0.01;
    uint numberOfIterations = 200;
    double relaxationFactor = 0.5;
    R.SetOptimizerAsRegularStepGradientDescent(maxStep,
        minStep,
        numberOfIterations,
        relaxationFactor);
    R.SetInitialTransform(new TranslationTransform(fixedImage.GetDimension()));
    R.SetInterpolator(InterpolatorEnum.sitkLinear);

    Transform outTx = R.Execute(fixedImage, movingImage);
}
```

But it throws with an exception
![image](https://user-images.githubusercontent.com/13016376/180234476-343ade77-cb29-4125-9099-2b142211a8f4.png)
I tried using DICOM files, JPEG for input but result is the same.
Could anyone say what I do wrong?

Thank you

**Comment by zivy** [comment]
Hello @mikhail-rozum,

The registration framework requires that the images have a pixel type of `float`. You are missing the `reader.SetOutputPixelType( PixelIDValueEnum.sitkFloat32 );` from the example. 

If you want the code to be flexible with respect to the on-disk image type, same code will work for jpg, DICOM, png etc., don't set the imageIO explicitly (no need for `reader.SetImageIO("PNGImageIO");`). When this is not specified SimpleITK will try to read using all the supported file format readers and will return a failure only if none of them work.

Finally, there is no need to repeatedly set the imageIO type if you are using the same IO type.

**Comment by mikhail-rozum** [comment]
> Hello @mikhail-rozum,
> 
> The registration framework requires that the images have a pixel type of `float`. You are missing the `reader.SetOutputPixelType( PixelIDValueEnum.sitkFloat32 );` from the example.
> 
> If you want the code to be flexible with respect to the on-disk image type, same code will work for jpg, DICOM, png etc., don't set the imageIO explicitly (no need for `reader.SetImageIO("PNGImageIO");`). When this is not specified SimpleITK will try to read using all the supported file format readers and will return a failure only if none of them work.
> 
> Finally, there is no need to repeatedly set the imageIO type if you are using the same IO type.

It solved the issue. Thank you a lot for such a quick answer!
