### ISSUE TITLE
Can (should?) an ImageFileReader have access to Transform* functions?

### ISSUE THREAD

**Issue by gdevenyi** [SimpleITK/SimpleITK#1683]
The `itk::simple::Image Class` has the functions:
```
std::vector< double > 	TransformContinuousIndexToPhysicalPoint (const std::vector< double > &index) const
std::vector< double > 	TransformIndexToPhysicalPoint (const std::vector< int64_t > &index) const
std::vector< double > 	TransformPhysicalPointToContinuousIndex (const std::vector< double > &point) const
std::vector< int64_t > 	TransformPhysicalPointToIndex (const std::vector< double > &point) const
```

Which as far as I understand it, do not require/operate on the actual pixel/voxel data of an image. As such, I think these functions should be exposed from an initialized ImageFileReader:
```
reader = sitk.ImageFileReader()
reader.SetFileName(file)
reader.ReadImageInformation()
```

As at this point all the necessary information is loaded.

There are a variety of cases where one might want to load the metadata from a collection of files and use this function to calculate something about physical space, without loading the pixel/voxel data ( see https://discourse.itk.org/t/finding-the-largest-physical-region-bounding-box-across-an-arbitrary-number-of-input-files-simpleitk for example)

**Comment by blowekamp** [comment]
Going down the route of adding support for all the functions of an Image to the ImageFileReader does not seem the correct route.

For this particular problem, and these particular methods, the size of the image does not matter. So a possible solution ( not too elegant ) would be to create a image of size 1, and copy the metadata from the ImageFileReader to the Image of size 1.

**Comment by gdevenyi** [comment]
```python
img = sitk.Image([1,1,1], sitk.sitkFloat32)
reader = sitk.ImageFileReader()
reader.SetFileName(file)
reader.ReadImageInformation()
#img = sitk.Image(reader.GetSize(), sitk.sitkFloat32)
img.SetSpacing(reader.GetSpacing())
img.SetOrigin(reader.GetOrigin())
img.SetDirection(reader.GetDirection())
dims = reader.GetSize()
spcs = img.GetSpacing()
```

Does seem to do what I wanted. Thanks!

**Comment by gdevenyi** [comment]
I'm a bit surprised that `TransformContinuousIndexToPhysicalPoint` which I'm using on the image doesn't complain that the image is size 1, it will happily accept the numbers from the `reader.GetSize()` I'm using.
