### ISSUE TITLE
NumPy array dtype may not be found when converting to `Image`

### ISSUE THREAD

**Issue by yoda-vid** [SimpleITK/SimpleITK#1685]
Converting a NumPy array to a SimpleITK `Image` object may give a pixel ID error when given a NumPy array loaded externally.

Here is an example that gives a reproducible error in my testing on Windows but no error on macOS:

```
import numpy as np
import SimpleITK as sitk
import tifffile

# generate np array
dtype = np.uint32
img = np.zeros([3, 4, 5], dtype=dtype)
print("Generated img:", img.shape, img.dtype)

# no error when converting directly from np array
img_sitk = sitk.GetImageFromArray(img)

# save and reload np array using another lib
path = "annotation.tiff"
tifffile.imwrite(path, img)
img = tifffile.imread(path)
print("Reloaded img:", img.shape, img.dtype)

# gives me pixel ID error on Windows
img_sitk = sitk.GetImageFromArray(img)
print(img_sitk.GetPixelIDTypeAsString())
```

On Windows, my output is:

```
Generated img: (3, 4, 5) uint32
Reloaded img: (3, 4, 5) uint32
Traceback (most recent call last):
  File "C:\Users\user\venvs\vmag3\lib\site-packages\SimpleITK\extra.py", line 195, in _get_sitk_pixelid
    return _np_sitk[numpy_array_type.dtype]
KeyError: dtype('uint32')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sitk_npdtype.py", line 21, in <module>
    img_sitk = sitk.GetImageFromArray(img)
  File "C:\Users\user\venvs\vmag3\lib\site-packages\SimpleITK\extra.py", line 303, in GetImageFromArray
    id = _get_sitk_pixelid(z)
  File "C:\Users\user\venvs\vmag3\lib\site-packages\SimpleITK\extra.py", line 200, in _get_sitk_pixelid
    raise TypeError('dtype: {0} is not supported.'.format(numpy_array_type.dtype))
TypeError: dtype: uint32 is not supported.
```

I loaded the uint32 image in Tifffile because of the `ITK ERROR: TIFFImageIO(000001BCBD86FA10): Unable to read tiff file: Sorry, can not handle images with 32-bit samples` error when loading it in SimpleITK, and sometimes I'm converting an array preloaded from another library. `np.uint16` has worked fine on both platforms, so the issue appears specific to certain dtypes and/or platforms.

I am not a NumPy expert, but I think the error may have to do with mapping the NumPy dtype in the function below. Perhaps the dtype identity check in the dict and `np.issubdtype` do not always match the given dtype because of [dynamic construction](https://stackoverflow.com/a/26921882/1911852)?

https://github.com/SimpleITK/SimpleITK/blob/0523b837baaf5d2b557ba498f5e0ff876d755448/Wrapping/Python/SimpleITK/extra.py#L172-L200

As a workaround, I used a similar approach as the function for the data type matching but tried an equality check instead, which appeared to work in my limited testing:

```

print("image dtype == dtype?", img.dtype == dtype)
print("image dtype is dtype?", img.dtype is dtype)
print("image dtype is sub-dtype?", np.issubdtype(img.dtype, dtype))
_np_sitk = {
    np.character: sitk.sitkUInt8,
    np.uint8: sitk.sitkUInt8,
    np.uint16: sitk.sitkUInt16,
    np.uint32: sitk.sitkUInt32,
    np.uint64: sitk.sitkUInt64,
    np.int8: sitk.sitkInt8,
    np.int16: sitk.sitkInt16,
    np.int32: sitk.sitkInt32,
    np.int64: sitk.sitkInt64,
    np.float32: sitk.sitkFloat32,
    np.float64: sitk.sitkFloat64,
    np.complex64: sitk.sitkComplexFloat32,
    np.complex128: sitk.sitkComplexFloat64,
}
try:
    img_sitk = sitk.GetImageFromArray(img)
    print("loaded to Image directly")
except TypeError:
    for key, val in _np_sitk.items():
        if key == img.dtype:
            print("found matching dtype from key:", key)
            img_sitk = sitk.Image(img.shape[::-1], val)
```

My output on Windows is:

```
Generated img: (3, 4, 5) uint32
Reloaded img: (3, 4, 5) uint32
image dtype == dtype? True
image dtype is dtype? False
image dtype is sub-dtype? False
sitk_npdtype.py:52: DeprecationWarning: Converting `np.character` to a dtype is deprecated. The current result is `np.dtype(np.str_)` which is not strictly correct. Note that `np.character` is generally deprecated and 'S1' should be used.
  if key == img.dtype:
found matching dtype from key: <class 'numpy.uint32'>
```

If this issue make sense, perhaps an equality check could be added to the exception handler in `_get_sitk_pixelid`? Or the type mapping dict could use the dtype name as a string instead? I'm happy to add a PR if this seems reasonable.

Test platforms: Windows 10, macOS 10.14, Python 3.8, NumPy 1.23, tifffile 2022.7.28, current SimpleITK from "Latest Developmental Binaries,"  2.2.0rc4.post2.

**Comment by blowekamp** [comment]
The Numpy documentation makes it clear that types and numpy scalars are not the same type even though they can be used interchangeable in numpy:
https://numpy.org/doc/stable/reference/arrays.dtypes.html

I am looking to reproduce the issue with out `tifffile`. Can the following reproduce the issue:
```
img = np.zeros([3, 4, 5], dtype=np.dtype('uint32'))
img_sitk = sitk.GetImageFromArray(img)
```

The solution will likely be to add `dtype.type` if a couple places in the function `_get_sitk_pixelid`.

**Comment by yoda-vid** [comment]
> I am looking to reproduce the issue with out `tifffile`. Can the following reproduce the issue

Thanks for looking into this. I tried this on Windows and Mac but wasn't able to reproduce the issue. I tried a couple other constructors but also couldn't reproduce it these ways:

```
img = np.zeros([3, 4, 5], dtype=np.dtype('uint32'))
img_sitk = sitk.GetImageFromArray(img)

img = np.zeros([3, 4, 5], dtype=np.dtype(np.uint32))
img_sitk = sitk.GetImageFromArray(img)

img = np.zeros([3, 4, 5], dtype=np.dtype('>u4'))
img_sitk = sitk.GetImageFromArray(img)
```

**Comment by blowekamp** [comment]
We have reproduced a similar issue with:
```
img = np.zeros([3, 4, 5], dtype=np.dtype('uintc'))
img_sitk = sitk.GetImageFromArray(img)
```

**Comment by blowekamp** [comment]
Also np.longlong and np.int64 are have similar issues.

The comparison of actual `dtypes` is well defined as opposed to the np.scalar_types. So the proposed solution convert the types to dtypes for comparison.

**Comment by yoda-vid** [comment]
I can confirm that the proposed type mapping in #1687 works for my original scenario of converting a NumPy array reloaded by `tifffile`. It also works when directly converting arrays constructed with `np.dtype('uint32')`, `np.dtype('uintc')`, `np.dtype('u4')`, or `np.dtype('<u4')`.

One small scenario where I still get the error is for `np.dtype('>u4')` on Windows (because the native byte order is little endian?). I imagine this is somewhat of an edge case.

Thanks for your fix.

**Comment by blowekamp** [comment]
@dzenanz ITKPython may contain a similar bug.

**Comment by dzenanz** [comment]
Thanks for the note Brad!
