### ISSUE TITLE
Build errors för SimpleITK 2.2 rc4

### ISSUE THREAD

**Issue by PatrikBrynolfsson** [SimpleITK/SimpleITK#1689]
Hello, 

I'm trying to build SimpleITK 2.2 rc4 on a Windows machine using VS 2019. I get errors for the Elastix and SimpleITK projects for both debug and release. I disabled BUILD_EXAMLPES and BUILD_TESTING, and enabled SimpleITK_USE_ELASTIX. Does anyone have any tips?

I downloaded the code from Github (https://github.com/SimpleITK/SimpleITK/tree/v2.2rc4)

![image](https://user-images.githubusercontent.com/35365778/183431694-67402a19-8175-4fdd-bb12-2c04facb2403.png)

**Comment by dave3d** [comment]
I have successfully built and tested Elastix/SimpleITK on my Windows system.  I do not have Minc on my system.  It looks like there's an overlap of symbols from the Standard C library.  Should you be linking against Minc's time.c.obj when building with Visual Studio?

**Comment by PatrikBrynolfsson** [comment]
Perhaps, I don't know. Do you know how I control that?

**Comment by PatrikBrynolfsson** [comment]
I think I will just wait for the compiled dll which I assume will be available with the new release, but there might be other users with similar problems that will be happy to have your insights :)

**Comment by dave3d** [comment]
Are you building with shared libraries?  I don't think Elastix will build of shared libraries are turned on.  Can you send me your CMake.Cache.txt file so I can see how you're trying to build SimpleITK?

SimpleElastix won't be enabled in the builds we post on PyPi.  It is an experimental feature at this point, and it will probably be a while until it is enabled by default.  I can build you a DLL if you need it.

**Comment by PatrikBrynolfsson** [comment]
Oh, thanks that would be awesome! Of course, finding the error so I can build it myself would be even better :) 

Here is the CmakeCache.txt:
[CMakeCache.txt](https://github.com/SimpleITK/SimpleITK/files/9315837/CMakeCache.txt)

**Comment by blowekamp** [comment]
It is presumed this issue has been addressed by the user. Please reopen if needed to continue the discussion
