### ISSUE TITLE
Update docs for venv

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#1710]
Remove reference to legacy virtualenv.

**Comment by blowekamp** [comment]
@mbopfNIH Can you please look through the sphinx docs for virtualenv and update it?

**Comment by mbopfNIH** [comment]
Very few references to virtualenv found in docs. Also one broken link that I will fix. Trying to learn how to compile Sphinx so I can test it out, but also better learn how it works.
