### ISSUE TITLE
Write dicom series tag 0028|0030 missing a 0

### ISSUE THREAD

**Issue by iamwangxi** [SimpleITK/SimpleITK#1720]
I load an image with spacing (0.759765625, 0.759765625, 1.5) and write to dicom series with [this example](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReadModifyWrite_docs.html) , but when I check the tag with RA, it shows 
![image](https://user-images.githubusercontent.com/23610397/191471989-4bbc073c-d45a-40e0-a267-64735f3fe1a5.png)
and the 0 before . is missing. 
I tried writing this tag myself but it did not work. Is there any way to get the 0 back?

**Comment by zivy** [comment]
Hello @iamwangxi,

That is outside of the users control. The underlying DICOM writer receives this information from the actual image spacings, so it is not something you can change.
