### ISSUE TITLE
Is there any way to get matrix / Affine transform from sitk.CompositeTransform?

### ISSUE THREAD

**Issue by dyollb** [SimpleITK/SimpleITK#1724]
Assuming I have a chain of linear transforms inside a `sitk.CompositeTransform`, is there any way I can get the total affine matrix?

Example:
```
tx1 = sitk.ScaleVersor3DTransform()
tx2 = sitk.AffineTransform(3)
composite_tx = sitk.CompositeTransform([tx1, tx2] 
mat = composite_tx.GetMatrix() # how can I get matrix?
```

**Comment by gdevenyi** [comment]
Looks like you can extract with GetFixedParamters, see
https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/22_Transforms.ipynb

**Comment by dyollb** [comment]
Thanks @gdevenyi . Not sure what yiu are pointing to in the notebook. 
I guess i could multiply the matrix of each transform (back to front?) and then create an affine matrix withe resulting matrix.

**Comment by gdevenyi** [comment]
Sorry, I was pointing at this section, where they create a composite, and then extract the parameters (you'll have to generate the matrix yourself with them)

https://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/22_Transforms.html#Composite-transform-(Transform)

**Comment by gdevenyi** [comment]
I needed to do this for a project, so here's a minimal example, take a simpleitk transform and construct a 3D affine transform in homogenous coordinates:

```python
# trans is a SimpleITK transform
M = np.zeroes((4,4))
M[0:3,0:3] = np.asarray(trans.GetParameters()[0:9]).reshape((3,3))
M[0:3,3] = trans.GetParameters()[9:]
M[3,3] = 1
```

**Comment by gdevenyi** [comment]
After testing some more, you cannot currently flatten affine transforms together, some discussion
https://discourse.itk.org/t/composite-transform-convertion-problem/3749/4

**Comment by zivy** [comment]
Hello @dyollb,

Per the discourse discussion @gdevenyi  pointed to, the issue is that you can't combine the global affine transformations and local deformations to yield a global affine. If you have a composite transformation which only contains global transformations (nested is fine too), that is readily done, a simple extension of the notebook code previously referenced. 

In the code below I arbitrarily set the center to `[0]*dim`. If you want to change the center to something else, please see that notebook section titled **Modify transform center...**:
```
def combine_affine_composite(composite_transform):
  # Flatten the copy of the composite transform, so no nested composites.
  flattened_composite_transform = sitk.CompositeTransform(composite_transform)
  flattened_composite_transform.FlattenTransform()
  tx_dim = flattened_composite_transform.GetDimension()
  A = np.eye(tx_dim)
  c = np.zeros(tx_dim)
  t = np.zeros(tx_dim)
  for i in range(flattened_composite_transform.GetNumberOfTransforms()-1,-1,-1):
    curr_tx = flattened_composite_transform.GetNthTransform(i).Downcast()
    # The translation is unique, needs to be treated seperatly from all other
    # global transformations.
    if curr_tx.GetTransformEnum() == sitk.sitkTranslation:
        A_curr = np.eye(tx_dim)
        t_curr = np.asarray(curr_tx.GetOffset())
        c_curr = np.zeros(tx_dim)
    else:
        A_curr = np.asarray(curr_tx.GetMatrix()).reshape(3, 3)
        c_curr = np.asarray(curr_tx.GetCenter())
        t_curr = np.asarray(curr_tx.GetTranslation())
    A = np.dot(A_curr, A)
    t = np.dot(A_curr, t + c - c_curr) + t_curr + c_curr - c
   
  return sitk.AffineTransform(A.flatten(), t, c)
```

**Comment by dyollb** [comment]
Thanks everyone for the help! @zivy perfect!

**Comment by dyollb** [comment]
@zivy so I tested the code you sent and it works nicely. Btw `sitk.ScaleTransform` doesn't have a `GetTranslation` method:

To share back, here is my version and a test:

```python
def composite_to_affine(composite_tx: sitk.CompositeTransform) -> sitk.AffineTransform:
    """flatten CompositeTransform to a single AffineTransform"""
    composite_tx = sitk.CompositeTransform(composite_tx)
    composite_tx.FlattenTransform()
    tx_dim = composite_tx.GetDimension()
    A = np.eye(tx_dim)
    t = np.zeros(tx_dim)
    c = np.zeros(tx_dim)
    for i in range(composite_tx.GetNumberOfTransforms() - 1, -1, -1):
        curr_tx: sitk.Transform = composite_tx.GetNthTransform(i)
        if isinstance(curr_tx, sitk.TranslationTransform):
            A_curr = np.eye(tx_dim)
            t_curr = np.asarray(curr_tx.GetOffset())
            c_curr = np.zeros(tx_dim)
        else:
            A_curr = np.asarray(curr_tx.GetMatrix()).reshape(3, 3)  # type: ignore [attr-defined]
            get_transl = getattr(curr_tx, "GetTranslation", None)
            if get_transl is not None:
                t_curr = np.asarray(get_transl())
            else:
                t_curr = np.zeros(tx_dim)
            c_curr = np.asarray(curr_tx.GetCenter())  # type: ignore [attr-defined]
        A = np.dot(A_curr, A)
        t = np.dot(A_curr, t + c - c_curr) + t_curr + c_curr - c
    affine = sitk.AffineTransform(A.flatten().tolist(), t.tolist(), c.tolist())
    return affine

    
def test_composite_to_affine():
    t1 = sitk.Euler3DTransform([3.4, 2.0, 0.0], 0.3, 0.2, -0.1, [1.0, 2.0, 3.0])
    t2 = sitk.TranslationTransform(3, [0.9, 0.7, 0.2])
    t3 = sitk.VersorTransform([1, 0, 0], 0.5)
    t4 = sitk.ScaleTransform(3, [1.2, 1.4, 2.0])
    composite = sitk.CompositeTransform([t1, t2, t3, t4])
    affine = composite_to_affine(composite_tx=composite)

    for x in ([0, 0, 0], [1, 1, 1], [23.0, -1.3, 203.4]):
        pc = np.asarray(composite.TransformPoint(x))
        pa = np.asarray(affine.TransformPoint(x))
        np.testing.assert_almost_equal(pc, pa, decimal=6)
```

**Comment by zivy** [comment]
Hello @dyollb,

I have created a [PR](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/pull/385/files) with you as co-author, updating the composite2affine function in the Transformations notebook. Please confirm that you are ok with being listed as co-author, if not I will remove you from that commit (in the past we've had folks who didn't want to be acknowledged even if they contributed).
