### ISSUE TITLE
SimpleITK 2.2 has incomplete type definitions

### ISSUE THREAD

**Issue by razorx89** [SimpleITK/SimpleITK#1734]
With SimpleITK 2.2 the release notes state: 
>Improved types for manual Python procedural methods: Resample, GetArrayFromImage, GetImageFromArray, GetArrayViewFromImage, ReadImage, WriteImage, SmoothingRecursiveGaussian, DiscreteGaussian.

However, with this d0708d084a265de775c96214301188013eb2e3c2 commit a `py.typed` was added, which indicates that the whole Package is *fully* typed. Since most of the symbols are exported from C++, the package is not fully typed and mypy complains with stricter settings.

Here is a minimal example script for type checking:

```python
import SimpleITK as sitk


def foo() -> sitk.Image:
    reader = sitk.ImageSeriesReader()
    # ...
    return reader.Execute()


if __name__ == '__main__':
    foo()
```

python 3.8-3.10 / SimpleITK==2.2
```
❯ mypy .
Success: no issues found in 1 source file
❯ mypy --disallow-untyped-calls --warn-return-any .
main.py:5: error: Call to untyped function "ImageSeriesReader" in typed context
main.py:7: error: Call to untyped function "Execute" in typed context
main.py:7: error: Returning Any from function declared to return "Image"
Found 3 errors in 1 file (checked 1 source file)
```

python 3.8-3.10 / SimpleITK==2.2 / rm `.venv/lib/python3.8/site-packages/SimpleITK/py.typed`
```
❯ mypy --disallow-untyped-calls --warn-return-any .
main.py:1: error: Skipping analyzing "SimpleITK": module is installed, but missing library stubs or py.typed marker
main.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
❯ mypy --disallow-untyped-calls --warn-return-any --ignore-missing-imports .
Success: no issues found in 1 source file
```

python 3.8-3.10 / SimpleITK==2.1.1.2
```
❯ mypy --disallow-untyped-calls --warn-return-any .
main.py:1: error: Skipping analyzing "SimpleITK": module is installed, but missing library stubs or py.typed marker
main.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
❯ mypy --disallow-untyped-calls --warn-return-any --ignore-missing-imports .
Success: no issues found in 1 source file
```

I think due to the `py.typed` file, the default import behavior of untyped symbols is altered. Normally, untyped symbols will be imported with Any types for compatibility reasons. In this case, however, it seems like no Any types are added at all, because the package declares itself as fully typed.

So in my opinion we have two options:
1. Remove `py.typed` in order to only provide partial type hints for the few pure Python functions specified in the wrapper package.
2. Add stub files (`.pyi`) and fully specify the whole API.

/cc @giuliabaldini

**Comment by blowekamp** [comment]
It seems that the current setup is not compatible with the "--disallow-untyped-calls" option. It's not clear if there is significant benefit to the community for that feature. Perhaps there is away to add some type of partial type support with stubs?

https://peps.python.org/pep-0561/#partial-stub-packages

This also may not be compatible with the strictness you are requesting for mypy.
