### ISSUE TITLE
Is it possible to generate Series UIDs using sitk?

### ISSUE THREAD

**Issue by linako111** [SimpleITK/SimpleITK#1739]
Similar to pydicom: https://pydicom.github.io/pydicom/dev/reference/generated/pydicom.uid.generate_uid.html

**Comment by zivy** [comment]
Hello @linako111,

Not exactly. 

We rely on the [ITK UID prefix](https://github.com/InsightSoftwareConsortium/ITK/blob/15d09d6c756b46b4d1c296d8bb13b85f82654ef9/Modules/IO/GDCM/src/itkGDCMImageIO.cxx#L84). We can use it in combination with date and time to create a series UID, as shown [here](https://github.com/SimpleITK/SimpleITK/blob/ad131c9b03e829d43b26267495d2116b29d47b72/Examples/DicomSeriesFromArray/DicomSeriesFromArray.py#L116-L122).

**Comment by linako111** [comment]
Thank you @zivy. Is it safe to use the same prefix for my output dicoms?

**Comment by zivy** [comment]
Hello @linako111,

This is similar to the pydicom root prefix, just the ITK root prefix, different organization. The suffix needs to be unique within the organization. For an authoritative answer please refer to the DICOM standard [chapter 9 Unique Identifiers](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/chapter_9.html).

I'd assume you will be using your organization's prefix. If you don't have one then I believe using the ITK prefix is fine, as that is the tool you used to write the DICOM. 

p.s. In SimpleITK you need to [explicitly tell the writer](https://github.com/SimpleITK/SimpleITK/blob/ad131c9b03e829d43b26267495d2116b29d47b72/Examples/DicomSeriesFromArray/DicomSeriesFromArray.py#L100-L102) to use these meta-dictionary values and not generate ones for you.
