### ISSUE TITLE
Missing Logging Methods

### ISSUE THREAD

**Issue by spinicist** [SimpleITK/SimpleITK#1758]
As discussed here: https://discourse.itk.org/t/sitk-commands-for-n4/5465/2, the `GetCurrentConvergenceMeasurement` and `GetCurrentLevel` methods for N4 have not been wrapped. It would be great to wrap these (and any other similar ones I've missed) so that I can monitor the progress of N4 better.

**Comment by blowekamp** [comment]
Also the `GetElapsedIterations` looks useful for observations.
