### ISSUE TITLE
problem installing latest development wheels directly from releases page

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#1761]
The links to the Python wheel artifacts are no longer part of the web page, so the `pip install --find-links...` doesn't work.

The solution is to explicitly add invisible links to the page. The only constraint is that there are no line-breaks between the links. When there are, it results in a significant amount of empty lines.

The template for the invisible links is:
``` 
 <a href="https://github.com/SimpleITK/SimpleITK/releases/download/latest/WHL_FILE_NAME"></a> 
 ```
 The end result should be a single line inserted under the `pip install...` instructions:
``` 
 <a href="https://github.com/SimpleITK/SimpleITK/releases/download/latest/SimpleITK-2.3.0.dev20-cp310-cp310-macosx_10_9_x86_64.whl"></a><a href="https://github.com/SimpleITK/SimpleITK/releases/download/latest/SimpleITK-2.3.0.dev20-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"></a><a href="https://github.com/SimpleITK/SimpleITK/releases/download/latest/SimpleITK-2.3.0.dev20-cp310-cp310-win_amd64.whl"></a>...
```

**Comment by blowekamp** [comment]
The latest releases contain the required HTML for pip install to work from the release pages.
