### ISSUE TITLE
Configure fails: Factory "FFTImageFilterInit" not contained in ITK_FACTORY_LIST: ""

### ISSUE THREAD

**Issue by yurivict** [SimpleITK/SimpleITK#1763]
```
CMake Error at CMake/sitkTargetUseITK.cmake:40 (message):
  Factory "FFTImageFilterInit" not contained in ITK_FACTORY_LIST: ""
Call Stack (most recent call first):
  Code/BasicFilters/src/CMakeLists.txt:173 (sitk_target_use_itk_factory)
```

Version: 2.2.0
InsightToolkit-5.2.1
clang-14
FreeBSD 13.1

**Comment by blowekamp** [comment]
SimpleITK 2.2.0 requires ITK v5.3rc04 or newer.

**Comment by yurivict** [comment]
What is the version that was compatible with InsightToolkit-5.2.1 ?

**Comment by zivy** [comment]
That would be [v2.1.1](https://github.com/SimpleITK/SimpleITK/releases/tag/v2.1.1).

**Comment by yurivict** [comment]
I think it's better to label versions as RC when the major dependency's version is RC.

**Comment by blowekamp** [comment]
It is not an ideal situation. ITK has not put out a new minor release in over a year and a half, and seem to be treating it's RC's like releases now.

**Comment by blowekamp** [comment]
ITK 5.3.0 has been tagged and SimpleITK 2.2.1 is available to build against it.
