### ISSUE TITLE
update/fix the documentation for the ImageRegistrationMethodLandmark example

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#1770]
Replace the reference to the image registration framework (.. include:: registrationExamplePrefix.rst) with actual documentation.

The landmark based registration is not part of the ImageRegistrationMethod, so the reference is incorrect. Also, describe which SimpleITK transformations are supported by this class and what is the minimal number of points required. What happens when a smaller number is provided. See the [ITK documentation](https://github.com/InsightSoftwareConsortium/ITK/blob/ce57f309f4f4142b80367fd89a88f8dac9d6943a/Modules/Registration/Common/include/itkLandmarkBasedTransformInitializer.h#L36-L86) for details. Possibly look at the ITK code itself to confirm that the documentation is still correct.

**Comment by blowekamp** [comment]
closed by #1750
