### ISSUE TITLE
Python: reader.Execute() on a temporary directory results in a permission error

### ISSUE THREAD

**Issue by zemmyang** [SimpleITK/SimpleITK#1773]
Since I normally work with lists of files (sorted according to metadata from pydicom), I read DICOM files this way:

```
def create_sitk_image(file_list):
    reader = sitk.ImageSeriesReader()
    with tempfile.TemporaryDirectory() as temp_dir:
        for fi in file_list:
            shutil.copy(src=fi, dst=temp_dir)

        dicom_names = reader.GetGDCMSeriesFileNames(temp_dir)
        reader.SetFileNames(dicom_names)
        image = reader.Execute()

    return image
```

and this was working fine for simpleitk 2.0.2, but it seems to have broken in 2.1.1.2. I'm getting a Permission Error on the `image = reader.Execute()`. Seems like there's a problem when tempfile cleans up. Any ideas what's going on here?

**Comment by blowekamp** [comment]
What is the error and stack trace produced?

Also I am not sure the reason the files are copied. Why are the original files not directly passed to the ImageSeriesReader?
