### ISSUE TITLE
FastMarchingUpwindGradient (Python) is broken as of 2.2

### ISSUE THREAD

**Issue by alex-gilman** [SimpleITK/SimpleITK#1801]
Test script to run after installing SimpleITK 2.2.0 or 2.2.1:
```python
import SimpleITK as sitk

sitkImg = sitk.GridSource()
trialPoints = [(0, 0, 0)]
targetPoints = [(2, 0, 10)]
gradientImg = sitk.FastMarchingUpwindGradient(sitkImg, trialPoints, 1, targetPoints)
print("successfully obtained gradient image")
```

Resulting output:

`
Traceback (most recent call last):
  File "/home/agilman/test/simpleitk/./sitk_test.py", line 8, in <module>
    gradientImg = sitk.FastMarchingUpwindGradient(sitkImg, trialPoints, 1, targetPoints)
  File "/home/agilman/test/simpleitk/venv/lib/python3.9/site-packages/SimpleITK/SimpleITK.py", line 26008, in FastMarchingUpwindGradient
    return _SimpleITK.FastMarchingUpwindGradient(*args, **kwargs)
RuntimeError: Exception thrown in SimpleITK FastMarchingUpwindGradient: /tmp/SimpleITK-build/ITK-prefix/include/ITK-5.3/itkFastMarchingUpwindGradientImageFilter.h:267:
ITK ERROR: FastMarchingUpwindGradientImageFilter(0x5633f9ea66f0): No target point set. Cannot set the target reached mode.
`

With SimpleITK 2.1.1.2, the success message is printed.

**Comment by dave3d** [comment]
FYI, I got the same error on 2.2.1, and it worked on 2.1.1.2.  Will investigate further.

**Comment by dave3d** [comment]
Update: So if we use the actual filter object (FastMarchingUpwindGradientImageFilter), the latest SimpleITK works fine.  Something about the procedural version is broken.

**Comment by dave3d** [comment]
https://github.com/InsightSoftwareConsortium/ITK/pull/3354/files
This code is failing because of this recent change to the ITK FastMarchingUpwindGradientImageFilter.

**Comment by alex-gilman** [comment]
The procedural version takes a `numberOfTargets` parameter before the `targetPoints` parameter. The filter json file suggests that the filter's TargetReachedMode gets updated based on the number of targets, but given the change @dave3d mentions, updating the mode without having set the target points themselves could very easily raise an error.

**Comment by blowekamp** [comment]
A PR with a test and solution is in progress now.
