### ISSUE TITLE
SimpleITK 1.0.0 not loading in python 2.7 64 bit (windows 7)

### ISSUE THREAD

**Issue by JoostJM** [SimpleITK/SimpleITK#181]
When upgrading to SimpleITK 1.0.0, it cannot be imported anymore due to a DLL load fail.

![image](https://cloud.githubusercontent.com/assets/18026947/26158862/51f0381c-3b1d-11e7-8ca7-0005e94c69e3.png)

Works fine in Python 3.5.2

**Comment by JoostJM** [comment]
@jcfr

**Comment by blowekamp** [comment]
I assume this was installed with `pip install SimpleITK` with the wheels downloaded from PyPI?

**Comment by jcfr** [comment]
My understanding is that it was.

**Comment by JoostJM** [comment]
yes I pip installed it

**Comment by blowekamp** [comment]
What operating system are you running? Is it new and clean?

I have a guess. Perhaps you are missing the `msvcr90.dll`? You could use the [windows dependency walker](http://www.dependencywalker.com) to verify this, and to look for other problems.

Installing the [MS Visual Studio C++ 2008 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=15336) my resolve this problem.

**Comment by JoostJM** [comment]
@blowekamp I'm running Windows 7. Not especially new or clean.

I'm running visual studio 2015 for most compiling I'm doing (msvcr140.dll), but can that be the issue if install from the wheel (isn't that already compiled?)

**Comment by blowekamp** [comment]
If you are using VS2015 and compiling for py27, that could be problematic. It may produce strange dll error like above. Python 2.7 was compiled with VS 2008, and the binary packages are supposed to be compiled with the same compiler to avoid conflicting runtime environments.

I think if you run the dependency walker on _SimpleITK.pyd it could be insightful.

**Comment by blowekamp** [comment]
Have you been able to solve the problem? Any additional information about the dll dependencies?

**Comment by JoostJM** [comment]
Sorry, no

I haven't had time yet. I will look at it on Monday



Verzonden vanaf mijn Samsung-apparaat


-------- Oorspronkelijk bericht --------
Van: Bradley Lowekamp <notifications@github.com>
Datum: 19-05-17 14:35 (GMT+01:00)
Aan: SimpleITK/SimpleITK <SimpleITK@noreply.github.com>
Cc: Joost van Griethuysen <j.v.griethuysen@nki.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [SimpleITK/SimpleITK] SimpleITK 1.0.0 not loading in python 2.7 64 bit (windows 7) (#181)


Have you been able to solve the problem? Any additional information about the dll dependencies?

-

**Comment by blowekamp** [comment]
I hope you are successful in getting SimpleITK installed. I am closing the issue, please feel free to report the status, and re-open if needed.
