### ISSUE TITLE
How to read/convert an image to binary?

### ISSUE THREAD

**Issue by Vathsan** [SimpleITK/SimpleITK#1834]
Is there a way to convert/read an image as binary image using the library? I need to replace the pixels with value > 0 with 1. 

Something equivalent to numpy's **img[img > 0] = 1**

**Comment by Vathsan** [comment]
Was able to convert the image using the following approach,
```
img_array = sitk.GetArrayFromImage(sitk_image)
img_array[img_array > 0] = 1
sitk_image = sitk.GetImageFromArray(img_array)
```

**Comment by zivy** [comment]
Hello @Vathsan,

That is not the recommended way to do the operation as it involves memory copies between SimpleITK and numpy and you are losing the spatial information associated with the original image. You can readily do this in SimpleITK:
```
binary_image = sitk_image>0
```
To better familiarize yourself with SimpleITK we recommend going over the [Fundamental Concepts](https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html) and [Common Conventions](https://simpleitk.readthedocs.io/en/master/conventions.html). There is also the [Jupyter Notebooks repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) and the [SimpleITK online tutorial](https://simpleitk.org/TUTORIAL/).

**Comment by Vathsan** [comment]
Thanks @zivy 

I get the following error when I try the above approach,
`sitk::ERROR: Pixel type: vector of 8-bit unsigned integer is not supported in 3D by N3itk6simple18GreaterImageFilterE.`

I understand the error is because of  vector of 8-bit unsigned integer is not supported by the class. Is there a way to find what pixel type is supported? I could not find any details in the [documentation](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1GreaterImageFilter.html#details)

**Comment by zivy** [comment]
Hello @Vathsan,

There is no easy way to find which pixel types are supported. In this case all scalar types are supported. 

The operation is comparing a pixel intensity value, scalar, to a constant, this does not generalize to a pixel which is a vector of values.  What is the semantics of `v>c` where `v` is a vector and `c` a constant? Are you expecting `v[0]>c and v[1]>c... and v[100]>c` for an image with vector pixels that have 100 entries (hyperspectral imaging)?

You can obtain each channel as a scalar image using the [VectorIndexSelectionCast](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1VectorIndexSelectionCastImageFilter.html) operation. The converse operation, combining multiple scalar images into a vector image can be done using the [ComposeImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ComposeImageFilter.html).

Finally, note that in ITK/SimpleITK a three valued vector is not RGB it is just a three valued vector not associated with a specific [color space](https://en.wikipedia.org/wiki/Color_space).

**Comment by blowekamp** [comment]
Hello @Vathsan,

Also not that in SimpleITK >2.3.0.dev, the operations you want is directly support for scalar images. That is the following works:
```
img = sitk.Image([10,10,10], sitk.sitkUInt16)
img[img>0] = 1
```

Also If your input image is suppose to be gray scale, you could operate on one of the channels, perform something like [VectorMagnitudeImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1VectorMagnitudeImageFilter.html) to coarsely convert it to scalar.

Additionally, if you are reading the image with SimpleITK, the setting the `OutputPixelType` to a scaler such as `sitk.sitkUInt8` will also convet the pixel type.

**Comment by Vathsan** [comment]
Thanks @zivy  and @blowekamp for the detailed input
