### ISSUE TITLE
Improve formatting for plotted images in Sphinx docs.

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#1859]
The SimpleITK images should be rendered to PNG files with 1:1 pixels and no interpolations performed. The images should be centered. And The size of the images should be controlled with the sphinx mark up, so the images don't look so small in the document.

**Comment by blowekamp** [comment]
@zivy Is there code in the SimpleITK Notebooks which render images with matplotlib with 1:1 pixels?

**Comment by zivy** [comment]
I belive the `vmin`, `vmax` parameters ensure this in [this call to imshow](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/75c92533facd80cf986be99841704ee2ea96d203/Python/gui.py#L211-L218).
