### ISSUE TITLE
Add wrapping for itk::SyNImageRegistrationMethod and itk::BSplineSyNImageRegistrationMethod

### ISSUE THREAD

**Issue by mrguilfoyle** [SimpleITK/SimpleITK#186]
Wrap additional deformable registration methods

**Comment by dave3d** [comment]
For more advanced registration methods possibly consider using other libraries such ANTS or SimpleElastix?

**Comment by blowekamp** [comment]
We are not going to extend SimpleITK to include SyN advanced registration. It is recommended to look into the end user application built by the SyN authors [ ANTs](http://stnava.github.io/ANTs/) .
