### ISSUE TITLE
RuntimeError: Exception thrown in SimpleITK ImageFileWriter_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/GDCM/src/itkGDCMImageIO.cxx:1392: ITK ERROR: GDCMImageIO(0x27016f0): DICOM does not support this component type

### ISSUE THREAD

**Issue by rajkifranciska** [SimpleITK/SimpleITK#1866]
When I run the python [example](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReader_docs.html) of how to read and write DICOM files, it reads the DICOM serie, prints the size, but can't write a dcm file.

My code is just like the example:

    reader = sitk.ImageSeriesReader()
    dicom_names = reader.GetGDCMSeriesFileNames(originalPath)
    reader.SetFileNames(dicom_names)
    image = reader.Execute()
    size = image.GetSize()
    print("Image size:", size[0], size[1], size[2], image.GetPixelIDTypeAsString())

    sitk.WriteImage(image, savepath)

The ERROR message is the following:

RuntimeError: Exception thrown in SimpleITK ImageFileWriter_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/GDCM/src/itkGDCMImageIO.cxx:1392:
ITK ERROR: GDCMImageIO(0x27016f0): DICOM does not support this component type

The _originalPath_ is the dcm serie path, the savepath is  _'./result.dcm'_
The printed output is:
`Image size: 512 512 244 16-bit signed integer`

Unfortunately for privacy reasons I can't share the dicom file.

**Comment by zivy** [comment]
Hello @rajkifranciska,

The 3D image should be saved as multiple 2D slices. Please see [this example](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReadModifyWrite_docs.html) which illustrates how to read, modify and write the final result as a set of DICOM images.
