### ISSUE TITLE
Failed to save study instance UID and series instance UID

### ISSUE THREAD

**Issue by LamFTS** [SimpleITK/SimpleITK#1881]
Dear developer, I am trying to modified some tag value of the series dicom image, I following the structure of this script: `Examples/DicomSeriesReadModifyWrite/DicomSeriesReadModifySeriesWrite.py`, the code can run without error, but study instance UID and series instance UID were not saved to modified files, and the study UID and series UID of the modified files different from slice to slice, I don't how to fix the tricky problem, hope to get some help here, thanks.

**Comment by zivy** [comment]
Hello @LamFTS,

I suspect you are not following the example as is and missed the [relevant line](https://github.com/SimpleITK/SimpleITK/blob/800dba89994a4838f8b289552002542a4a7273e9/Examples/DicomSeriesReadModifyWrite/DicomSeriesReadModifySeriesWrite.py#L72-L74) which configures the writer to use the study and series ID you set in the meta-data dictionary and not create new ones on its own.

**Comment by LamFTS** [comment]
Thanks for your time @zivy , after re-organizing my script, the UID-saving related problem solved, here come another problem, that the z-axial would be reversed, when I scroll to view the modified series in dicom viewer (i.e microdicom), the series display from bottom to the top, which is reversed from the previous order. I try to modified that line setting value of Instance Number ("0020|0013") from `str(i)` to `str(image3D.GetDepth - i)`, but problem still exists, I attach the script below, it may help explain the situation. What's more, I would like to ask a question, is letter in key of tag case-sensitive? I saw some key with different case status, which confusing me. Thank for your generous help again. : )
[untitled10.txt](https://github.com/SimpleITK/SimpleITK/files/10718250/untitled10.txt)

**Comment by zivy** [comment]
Hello @LamFTS,

From your code I see your intent is to do anonymization. I highly recommend not doing this on your own as doing it well is not trivial. Possibly take a look at the following open source resources:
1. [Code from kitware](https://github.com/KitwareMedical/dicom-anonymizer).
2. [Program from PixelMed](http://www.dclunie.com/pixelmed/software/webstart/DicomCleanerUsage.html).

**Comment by LamFTS** [comment]
@zivy , I am so gold to be informed of the method of anonymization, that really help me out of the tricky situation. But I still want to know how to fix the problem of z-axial-reversed, I though maybe one day I would encounter the same problem in another task. : D

**Comment by zivy** [comment]
Hello @LamFTS,

The only DICOM tags that are involved in the ordering are the Image Position (Patient) `0020|0032` and Image Orientation (Patient) `0020|0037`. 

Please make sure that they are not changed during writing. The Instance Number `0020|0013` is not used in this context. It is only "A number that identifies this image". Not sure what is causing the change you are experiencing. Possibly try another DICOM viewer to see if it is a viewer specific issue.

**Comment by LamFTS** [comment]
Dear  ==@zivy ==, thanks for patience and generous help, I finally managed to solve the z-axis reversal after process by inheriting the  Image Position (Patient) `0020|0032` and Instance Number `0020|0013` from original series. What' more, it seems that [the line of "0020|000D"](https://github.com/SimpleITK/SimpleITK/blob/800dba89994a4838f8b289552002542a4a7273e9/Examples/DicomSeriesReadModifyWrite/DicomSeriesReadModifySeriesWrite.py#L82) need modified, Study UID was set correctly only when I change `0020|000D` to `0020|000d`.

**Comment by zivy** [comment]
Hello @LamFTS,

Thanks for identifying the issue and helping us improve SimpleITK. 

This [pull request](https://github.com/SimpleITK/SimpleITK/pull/1899/files), addresses the problem.
