### ISSUE TITLE
`ElastixImageFilter` error during groupwise registration

### ISSUE THREAD

**Issue by yoda-vid** [SimpleITK/SimpleITK#1891]
I encounter an error when running groupwise registration after compiling SimpleITK with `SimpleITK_USE_ELASTIX` enabled, as pointed out to me [here](https://github.com/sanderslab/magellanmapper/issues/438). Groupwise registration previously worked for me in an earlier version of SimpleElastix (v1.1.0) but not in a later build (v2.0.2).

Here is a minimal example:

```
import numpy as np
import SimpleITK as sitk

# construct template image
img_np = np.ones([10, 9, 8])
img_sitk = sitk.GetImageFromArray(img_np)

# combine images to register together
vectorOfImages = sitk.VectorOfImage()
for i in range(4):
    vectorOfImages.push_back(img_sitk)
img_combined = sitk.JoinSeries(vectorOfImages)

# perform groupwise registration
elastix_img_filter = sitk.ElastixImageFilter()
elastix_img_filter.SetFixedImage(img_combined)
elastix_img_filter.SetMovingImage(img_combined)
param_map = sitk.GetDefaultParameterMap("groupwise")
elastix_img_filter.SetParameterMap(param_map)
transform_filter = elastix_img_filter.Execute()
transformed_img = elastix_img_filter.GetResultImage()
```

which gives the error:

```
Traceback (most recent call last):
  File "/opt/.pyenv/versions/3.8.13/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/.pyenv/versions/3.8.13/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/src/yoda-tester/groupwise_reg.py", line 20, in <module>
    transform_filter = elastix_img_filter.Execute()
  File "/opt/src/venvs/vmag2/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 10679, in Execute
    return _SimpleITK.ElastixImageFilter_Execute(self)
RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /opt/src/SimpleITK/Code/ElastixTransformixWrappers/src/sitkElastixImageFilterImpl.cxx:189:
sitk::ERROR: ElastixImageFilter does not support the combination of 4-dimensional 64-bit float fixed image and a 4-dimensional 64-bit float moving image.
```

This issue appears to have been reported in the SimpleElastix repo: https://github.com/SuperElastix/SimpleElastix/issues/468 . It points to the replacement of `SITK_4D_IMAGES` by `SITK_MAX_DIMENSIONS`, which Elastix may not yet support. I tried compiling with `-DSimpleITK_4D_IMAGES=ON` (not sure if this is the right syntax) but got the same error. I also tried replacing all `#ifdef SITK_4D_IMAGES` statements with `#ifdef SITK_MAX_DIMENSIONS`, also to no avail. Are there any workarounds? Elastix has otherwise been working well for me in SimpleITK, really appreciate the integration.

Tested on macOS 12.6.0, Python 3.8.13, SimpleITK v2.2.1 (built on commit 0640d4aa0db519120d5a227ca1390dc9033e6e83).

**Comment by blowekamp** [comment]
With the above patch, you test cast improved. I had to make the following change to cast to float 32:
```
 img_combined = sitk.JoinSeries( [sitk.Cast(img_sitk, sitk.sitkFloat32)]*4)
```

However I still get the following error:
```
>>> transform_filter = elastix_img_filter.Execute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/blowekamp/scratch/sitk/SimpleITK-build/Testing/Installation/venv/lib/python3.11/site-packages/SimpleITK/SimpleITK.py", line 10696, in Execute
    return _SimpleITK.ElastixImageFilter_Execute(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception thrown in SimpleITK ElastixImageFilter_Execute: /Users/blowekamp/src/SimpleITK/Code/BasicFilters/src/sitkCastImageFilter.cxx:95:
sitk::ERROR: Filter does not support casting from casting 32-bit float to 32-bit float
```

**Comment by blowekamp** [comment]
It looks like Elastics instantiated the Cast Image filter to 4D:

https://github.com/SuperElastix/SimpleElastix/blob/master/Code/BasicFilters/src/sitkCastImageFilter.cxx#L49-L53

**Comment by yoda-vid** [comment]
Thank you for the patches! Really appreciate these fixes. I am testing #1894 and will post my results there.
