### ISSUE TITLE
MatchCardinalityImageToImageMetric

### ISSUE THREAD

**Issue by dyollb** [SimpleITK/SimpleITK#1896]
In my experience initializing a transform for registration is the main component that fails. However, given a labelfield/mask in the target/source I believe the initialization is more robust. Given the abundance of CNNs reasonable labelfields can often be obtained (and could be used for initializing the registration).

SimpleITK currently does not offer good similarity metrics for labelfield matching. Two options might easily fix this
1. Adding MatchCardinalityImageToImageMetric from ITK
2. Or: allow matching vector images (one hot) using mean square metric

**Comment by dyollb** [comment]
It seems all the current metrics are based on the "v4" image to image metric and don't share the same base as MatchCardinalityImageToImageMetric, so maybe that would first require changes in upstream ITK.

**Comment by blowekamp** [comment]
Yes, that match cardinality is on the old registration framework and not compatible with the v4 infrastructure.

**Comment by dyollb** [comment]
@blowekamp to enable the vector float/double image for the mean square metric, I guess I could add an `std::enable_if` special case, which ONLY compiles the vector image variant with the mean square metric ([here](https://github.com/SimpleITK/SimpleITK/blob/aff11ddc90bde4cc1669bb54a60dec52d50c0507/Code/Registration/src/sitkImageRegistrationMethod_CreateMetric.hxx)). I would also add the vector image types [here](https://github.com/SimpleITK/SimpleITK/blob/aff11ddc90bde4cc1669bb54a60dec52d50c0507/Code/Registration/src/sitkImageRegistrationMethod_CreateMetric.cxx#L44).

Would this already be enough to expose the vector image workflow to python?
Where is `ImageRegistrationMethod::ExecuteInternal` expanded to the different supported image types?

**Comment by dyollb** [comment]
> @blowekamp to enable the vector float/double image for the mean square metric, I guess I could add an `std::enable_if` special case, which ONLY compiles the vector image variant with the mean square metric ([here](https://github.com/SimpleITK/SimpleITK/blob/aff11ddc90bde4cc1669bb54a60dec52d50c0507/Code/Registration/src/sitkImageRegistrationMethod_CreateMetric.hxx)). I would also add the vector image types [here](https://github.com/SimpleITK/SimpleITK/blob/aff11ddc90bde4cc1669bb54a60dec52d50c0507/Code/Registration/src/sitkImageRegistrationMethod_CreateMetric.cxx#L44).
> 
> Would this already be enough to expose the vector image workflow to python? Where is `ImageRegistrationMethod::ExecuteInternal` expanded to the different supported image types?

So I started implementing SFINAE which delegates to a `CreateScalarMetric` and `CreateVectorMetric` variant, but realized I probably need to use `itk::VectorImageToImageMetricTraitsv4` which is templated over the number of components (`VNumberOfComponents`). 

Since the only reason to enable a "vector metric" is for VectorImages, i.e. variable number of components (say up to 30 or more), we would need to add many explicit instantiations, which would blow up compilation time and binary size.

I guess this path is not worth following...

**Comment by blowekamp** [comment]
Thank you for digging into this. Starting support for vector image registration would be quite a welcomed feature to add, but yet is appears that the VectorImageToImage traits are all fixed type. It is not clear to me if the documentation of VectorToImageMetricTraits should refer to an Image of Vectors and not support for `VectorImage`. The "ideal"/time consuming solution would be to implement traits which have the variable length vector traits, but there are a lot of unknowns there.

Another possibility is phrasing the problem as a multi-value optimization. That is setting up the problem as a set of pair wise registrations with metrics, but optimizing for one transform. There is some support for that within the ITKv4 registration framework. It would require some work looking into ITK example, and Ants registration know the working use cases the components where implemented for. Perhaps a topic in ITK discourse would get responses from the relevant developers or more detailed references for this approach.

**Comment by dyollb** [comment]
> 

Thanks @blowekamp! I started a topic on [ITK discourse](https://discourse.itk.org/t/metrics-for-registration-of-labelmaps/5755).

**Comment by zivy** [comment]
Closing, see discussion on ITK discourse.
