### ISSUE TITLE
Feature request: Hough Transform Filter

### ISSUE THREAD

**Issue by maribernardes** [SimpleITK/SimpleITK#1897]
Would love to have HoughTransform included in SimpleITK

**Comment by zivy** [comment]
Hello @maribernardes,

Is there a particular reason for adding the two ITK Hough filters (line and circle)? They are only available for 2D images and the same functionality is available in OpenCV which is focused on 2D image analysis. 

We try to keep SimpleITK as lean as possible, and these are a less used feature of ITK, so we didn't include it. Let us know if this is just out of convenience, not installing OpenCV, or if there is a more compelling reason that SimpleITK should include these filters.

**Comment by zivy** [comment]
We will not be adding the ITK Hough transform filters to SimpleITK, due to the reasoning above (filters are only 2D and better and more widely used implementations are readily available).
