### ISSUE TITLE
Displacement field transform in 3D

### ISSUE THREAD

**Issue by mahimoksha** [SimpleITK/SimpleITK#1898]
temp is a forward 3D displacement field of size DxMxNx3.

`displacement_image = sitk.GetImageFromArray(np.double(temp),sitk.sitkVectorFloat64)`

`tx = sitk.DisplacementFieldTransform(displacement_image)`

`tx.SetInterpolator(sitk.sitkLinear)`

I find the inverse transform using the code below:
`sitk_inverse_displacement_field = sitk.InvertDisplacementField(tx.GetDisplacementField())`

`tx1 = sitk.DisplacementFieldTransform(sitk_inverse_displacement_field)`

`tx1.SetInterpolator(sitk.sitkLinear)`

Using the inverse transform and a resampler I transformed a 3D volume. 
using the same inverse transform i also transform a set of  K 3D points (X,Y,Z) spread uniformly across the surface of the volume.

`px, py, pz =tx1.TransformPoint((x_points,y_points,z_points))`

When i plot the transformed volume and points on paraview, they don't align. can you please help in explaining what i am doing wrong.

**Comment by zivy** [comment]
Closing this issue as it was [cross posted on ITK discourse](https://discourse.itk.org/t/displacement-field-transform-in-3d/5759). See discussion there.
