### ISSUE TITLE
RuntimeError and ITK ERROR

### ISSUE THREAD

**Issue by zzzyzh** [SimpleITK/SimpleITK#1906]
When I use ITK to convert multiple .png into .nii.gz, the following error occurs
RuntimeError: Exception thrown in SimpleITK ImageFileWriter_Execute: /tmp/SimpleITK-build/ITK-prefix/include/ITK-5.3/itkImageFileWriter.hxx:245:
ITK ERROR: ImageFileWriter(0x3465190): Largest possible region does not fully contain requested paste IO regionPaste IO region: ImageIORegion (0x7ffe6ad51d00)
  Dimension: 3
  Index: 0 0 0 
  Size: 240 240 0 
Largest possible region: ImageRegion (0x7ffe6ad51c40)
  Dimension: 3
  Index: [0, 0, 0]
  Size: [240, 240, 0]

What should I do?

**Comment by blowekamp** [comment]
The z-size of zero does not seem right. Where is that coming from?

**Comment by zivy** [comment]
Assuming issue was resolved, please open if not.
