### ISSUE TITLE
Pixel type: 32-bit unsigned integer is not supported in 3D

### ISSUE THREAD

**Issue by michelegentili93** [SimpleITK/SimpleITK#1912]
I get this error, 

> Exception thrown in SimpleITK LabelStatisticsImageFilter_Execute: /Users/runner/work/1/sitk/Code/Common/include/sitkDualMemberFunctionFactory.hxx:193:
> sitk::ERROR: Pixel type: 32-bit unsigned integer is not supported in 3D byN3itk6simple26LabelStatisticsImageFilterE

In a previous post #592, it was the dimension of the pixel. Here the pixel is 1D. 

This is the code

```
import SimpleITK as sitk

# Load the MRI image
image = sitk.ReadImage("./AS0170.nii.gz")

# Smooth the image to reduce noise and enhance edges
smoothed = sitk.CurvatureFlow(image, timeStep=0.125, numberOfIterations=5)

# Apply an intensity threshold to segment the breast tissue
threshold_filter = sitk.BinaryThresholdImageFilter()
threshold_filter.SetLowerThreshold(10)
threshold_filter.SetUpperThreshold(400)
threshold_filter.SetInsideValue(0)
threshold_filter.SetOutsideValue(1)
breast_mask = threshold_filter.Execute(smoothed)

```
This is the image:

`Image (0x7fd1c4f74050)
  RTTI typeinfo:   itk::Image<short, 3u>
  Reference Count: 1
  Modified Time: 4486
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 4466
  UpdateMTime: 4485
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [240, 512, 512]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [240, 512, 512]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [240, 512, 512]
  Spacing: [1, 1, 1]
  Origin: [0, 0, 0]
  Direction: 
-1 0 0
0 -1 0
0 0 1

  IndexToPointMatrix: 
-1 0 0
0 -1 0
0 0 1

  PointToIndexMatrix: 
-1 0 0
0 -1 0
0 0 1

  Inverse Direction: 
-1 0 0
0 -1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x600001e14ae0)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, short>
      Reference Count: 1
      Modified Time: 4482
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7fd154f00000
      Container manages memory: true
      Size: 62914560
      Capacity: 62914560`

**Comment by zivy** [comment]
Hello @michelegentili93,

Can you share the image and the missing code that invokes the `LabelStatisticsImageFilter`?

I assume it is something along the lines of:
```
label_statistics_filter = sitk.LabelStatisticsImageFilter()
label_statistics_filter.Execute(image, breast_mask)

# mean intensity value for all pixels with label zero in the breast_mask
print(label_statistics_filter.GetMean(0))
``` 

Another question, the selection of the inside and outside values for the threshold filter is non-conventional, it works, just not the common practice. Pixels with values in [10,400] will have a value of zero and those outside this range a value of one. Usually, we use one to denote foreground and zero for background and here it seems reversed. It is an arbitrary choice, as you can use any value to denote foreground and background. Just want to confirm that this is the intended behavior.

**Comment by michelegentili93** [comment]
print(label_statistics_filter.GetMean(0))
168.0566764106765

Here is the numpy tensor (512, 512, 240) of the image:

[https://drive.google.com/file/d/1WHMMxhzwm5mlbT9BDFMtxqSHARFZ_cWz/view?usp=sharing](url)

This one is one of the slice.
<img width="304" alt="image" src="https://user-images.githubusercontent.com/15063931/227993623-fcec8d73-cf0d-4829-bc83-74421c1a9d23.png">
