### ISSUE TITLE
C++ static library size

### ISSUE THREAD

**Issue by codarag** [SimpleITK/SimpleITK#1915]
Hello everyone,
I managed to build SimpleITK C++ library at version 2.2.1 with Visual Studio 2019 on Windows 10.

Starting from same configuration, and changing only "BUILD_SHARED_LIBS" on cmake, I'm able to build shared libs when value is 1 and static libs when value is 0.
While shared libraries (lib+dll) are ~126MB in size, static libraries are ~2.66 GB, that is a huge difference.

I need static library into my software but carring 2.66 GB while DLLs are only 126MB is painful... do you have any idea on how to reduce static library size?

Thank you!

**Comment by blowekamp** [comment]
The size of the DLLs and libs are smaller than expected. Application linked to the static libraries usually end up smaller than when linked to shared libraries. Static libraries do not need to be include in an applications run time.

It is not clear to me what you are trying to do with the static libraries where the size is a burden.

**Comment by codarag** [comment]
I need to use only static libraries instead of shared libraries

**Comment by zivy** [comment]
Assuming this issue was resolved. If not, feel free to reopen.
