### ISSUE TITLE
Merge 2D images into nifti files

### ISSUE THREAD

**Issue by huiaixing** [SimpleITK/SimpleITK#1917]
Hello, could you please help me answer a question? I have a nifti format file for liver tumors that I have converted into dozens of 2D images. I used an image segmentation model to color the liver in these images. I would like to know how to use the simpleITK to synthesize these images into nifti files and preserve color information?

**Comment by zivy** [comment]
Hello @huiaixing,

If the images 1.nii and 2.nii are color images, the resulting volume will be in color. If the code above did not work for you, it should, please share two nifti files from the segmentation and we can further investigate the issue.

**Comment by huiaixing** [comment]
@zivy， 
My nii file is not in color. I divided this NII file and added colors to the 2D images, and then wanted to restore these 2D images to nii files. Here is my nii file, which is a nii file for liver tumors.
[volume-0.nii.gz](https://github.com/SimpleITK/SimpleITK/files/11223278/volume-0.nii.gz)

**Comment by zivy** [comment]
Hello @huiaixing,

What you shared is the original anatomical volume (CT), not the segmentation. If what you want to do is overlay a segmentation onto this volume I recommend looking at [this notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/05_Results_Visualization.ipynb) which illustrates how to overlay segmentation results onto images, no need to separate the segmentation into 2D slices.

**Comment by huiaixing** [comment]
@zivy 
Thank you for your answer. This notebook is very helpful, and I will carefully study it.
