### ISSUE TITLE
merge multi nii files to one nii file

### ISSUE THREAD

**Issue by shanfl** [SimpleITK/SimpleITK#1919]
hi,everyone. I split one  polydata into multi part ,then convert them into nii files. and I want convert this nii-files into one nii files . 
using python is simple ,but  I  want it to be c++ code . I need help,plz

**Comment by zivy** [comment]
Hellow @shanfl,

If you have it working in Python, then moving to C++ shouldn't be that hard. 

Please look at the [Simple C++/CMake example](https://simpleitk.readthedocs.io/en/master/link_CppCMake_docs.html) and the usage of the `ImageSeriesReader` in the [DICOM read example](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReader_docs.html). In the nifti case, you will need to sort the image files according to the z coordinate yourself (this is what the `sitk::ImageSeriesReader::GetGDCMSeriesFileNames` method does). It is assumed that you have [built SimpleITK](https://simpleitk.readthedocs.io/en/master/building.html) locally. If you are only interested in the C++ library, turn off all of the language wrappings.
