### ISSUE TITLE
Use only corresponding points based transformation

### ISSUE THREAD

**Issue by PolarBean** [SimpleITK/SimpleITK#1933]
Hi,

I have many corresponding points (more than 100) between two volumes. I would like to transform one volume to the other using these points. However, these volumes have vastly different appearances and so I would like to avoid using any other metric than deforming based solely on the corresponding points (I have tried and it runs out of memory). Is it possible to use SimpleElastix in this way? using the CorrespondingPointsEuclideanDistanceMetric as the only transformation?

Thank you in advance.

**Comment by zivy** [comment]
Hello @PolarBean,

Don't know about SimpleElastix, @N-Dekker can possibly help here?

Have you looked at the [LandmarkBasedTransformInitializerFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1LandmarkBasedTransformInitializerFilter.html) with a BSplineTransform? The filter under the hood is [BSplineScatteredDataPointSetToImageFilter](https://itk.org/Doxygen/html/classitk_1_1BSplineScatteredDataPointSetToImageFilter.html) which seems to be close to what you are asking for.

**Comment by PolarBean** [comment]
this looks perfect! thank you. Is it specified anywhere the format that the points should be in? If not I will experiment. Thanks for your help

**Comment by zivy** [comment]
Point coordinates should be in flat list [x1, y1, z1, x2, y2, z2...]. Described in the usage examples of the `LandmarkBasedTransformInitializer` in the toolkit's [Jupyter notebooks repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks).

**Comment by PolarBean** [comment]
perfect, thank you for all your help
