### ISSUE TITLE
SimpleITK cannot seem to read nrrd or nhdr files on linux

### ISSUE THREAD

**Issue by Kevin-DIDIER** [SimpleITK/SimpleITK#1951]
Hello,
My problem is that when I try to read nhdr or nrrd files using unity and c# the library return me this error : 
```
ApplicationException: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK-build/ITK-prefix/include/ITK-5.3/itkImageBase.hxx:77:
ITK ERROR: Image(0x7fa70c083180): Zero-valued spacing is not supported and may result in undefined behavior.
Refusing to change spacing from [1, 1, 1] to [0, 0, 0]
itk.simple.ImageFileReader.Execute () (at <59be0a83576d4e2db91507aa51007218>:0)
``` 

It occurs when i try to use the ImageFileReader execute function this way :

```c#
ImageFileReader reader = new ImageFileReader();  
 reader.SetFileName(filePath);  
 Image image = reader.Execute();
``` 

Which works when I load .tiff files.
However, using the same code on windows is working, 
do you have an idea of what could be the problem ?
I tried with the 2.2.1 and 2.2.0 library with no changes, the files seems to not be ill-formed as well because they open correctly on Windows.

**Comment by blowekamp** [comment]
Are you able to share the data files?

**Comment by Kevin-DIDIER** [comment]
I don't think I'm allowed to, will ask
