### ISSUE TITLE
simpleITK has no attribute DICOMOrient

### ISSUE THREAD

**Issue by NirutaDhimal** [SimpleITK/SimpleITK#1967]
SimpleITK version: 2.2.1
Language: Python

This is the code I am running
<img width="483" alt="Screen Shot 2023-07-28 at 4 18 03 pm" src="https://github.com/SimpleITK/SimpleITK/assets/58328226/1c02ea62-9dc3-49ae-a9fb-b26b9c9519bc">

I am getting this error
![Uploading Screen Shot 2023-07-28 at 4.20.27 pm.png…]()

**Comment by NirutaDhimal** [comment]
@zivy Thanks for replying. I am not sure why this is happening, 
OS: Ubuntu 18.04.6 LTS
Python Version: Python 3.9.13 installed via pip on a conda virtual environment

**Comment by zivy** [comment]
Hello @NirutaDhimal,

I tried to recreate your setting, conda environment with Python 3.9.13 on ubuntu. I then installed SimpleITK via `pip install SimpleITK` and it is version 2.2.1. The `DICOMOrient` method is available.

Possibly something is corrupt with your environment. Please create a basic environment and see if it works:
```
conda create -n basic_sitk python=3.9.13
conda activate basic_sitk
pip install SimpleITK
python -c "import SimpleITK as sitk; sitk.DICOMOrient()"
```
You should get an error saying `DICOMOrient` is missing a required argument. This shows the function is available.

**Comment by NirutaDhimal** [comment]
Hi @zivy
I created a basic environment like you said and it works. There is probably something corrupt in my environment. Thank you for helping me.

**Comment by NirutaDhimal** [comment]
@zivy
I installed SimpleElastix on the basic_sitk environment using pip 
`pip install SimpleITK-SimpleElastix
python -c "import SimpleITK as sitk; sitk.DICOMOrient()"` 
I received the same "SimpleITK has no attribute DICOMOrient" error. Before posting an issue I tried running the DICOMOrient on different virtual environments and they all have simpleElastix installed. Can you please try it on your end as well?
Thank you

**Comment by dave3d** [comment]
SimpleITK-SimpleElastix is using SimpleITK version 2.0.2rc2, which does not have DICOMOrient.

You can see what version of SimpleITK you have as follows:
    
`print(sitk.Version().ExtendedVersionString())`

SimpleITKElastix is not produced by us, so it is does not have the latest SimpleITK version.
