### ISSUE TITLE
LandmarkBasedTransformInitializerFilter does not accept BSplineTransform

### ISSUE THREAD

**Issue by siboles** [SimpleITK/SimpleITK#197]
[error.zip](https://github.com/SimpleITK/SimpleITK/files/1043183/error.zip)

RuntimeError: Exception thrown in SimpleITK LandmarkBasedTransformInitializerFilter_Execute: /opt/miniconda2/conda-bld/simpleitk_1491578024069/work/build/ITK-prefix/include/ITK-4.11/itkLandmarkBasedTransformInitializer.hxx:75:
itk::ERROR: LandmarkBasedTransformInitializer(0x31204f0): Unsupported Transform Type BSplineTransform

**Comment by blowekamp** [comment]
It's better to provide the sample code inline like this:
```
import SimpleITK as sitk
import numpy as np

img = sitk.GetImageFromArray(np.random.rand(10,10))
fixed_pts = np.array([0, 0, 3, 2, 2, 1, 6, 7])
moving_pts = np.array([1, 1, 4, 1, 1, 3, 5, 8])

ix = sitk.BSplineTransformInitializer(img, (2, 2), 1)
landmarkTx = sitk.LandmarkBasedTransformInitializerFilter()
landmarkTx.SetFixedLandmarks(fixed_pts)
landmarkTx.SetMovingLandmarks(moving_pts)
landmarkTx.SetBSplineNumberOfControlPoints(8)
landmarkTx.SetReferenceImage(img)
initialTx = landmarkTx.Execute(ix)
```

The third parameter for the `BSplineTransformInitializer` is the spline order. It defaults to `3`. The ITK LandmarkBasedTransformInitializer only works with spline orders of `3`. Please try changing to the following:

```
ix = sitk.BSplineTransformInitializer(img, (2, 2), order=3)
```

We'll add a special check for the spline order to produce a better error message.
