### ISSUE TITLE
fail to install simpleITK due to gdc

### ISSUE THREAD

**Issue by YaoyaoYueee** [SimpleITK/SimpleITK#1971]
<img width="1054" alt="issue" src="https://github.com/SimpleITK/SimpleITK/assets/94213074/bc0cfc3c-f063-4292-988d-831edf24abff">

**Comment by zivy** [comment]
Hello @awuaq,

The information provided is insufficient for us to help you. What operating system, compiler, CMake version were used? Also, we highly recommend using the SuperBuild. For detailed instructions please see [read-the-docs](https://simpleitk.readthedocs.io/en/master/building.html).

**Comment by zivy** [comment]
Closing, assuming question was resolved following the read-the-docs instructions. Feel free to reopen if needed.
