### ISSUE TITLE
SIEMENS .ima MagnetomVision files

### ISSUE THREAD

**Issue by deydeepwashu** [SimpleITK/SimpleITK#1973]
Hello - I am working with older SIEMENS .ima files from a MagentomVision Scanner - from what I have tried ITK doesn't seem to be able to read in these kinds of files.

This was my error:

RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /Users/runner/work/1/sitk/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader

Is there functionality available to read these kinds of files? If not - is there a way I can try and read them with another tool?

I am fairly certain they are MagentomVision files and not simply dicoms that have been renamed with another extension - I can't open them in pydicom, nibabel or other tools that are equipped to handle dicom.

**Comment by zivy** [comment]
Hello @deydeepwashu,

Based on the tools that you tried it sounds like this is either a corrupt file or it doesn't comply with the DICOM standard. 

SimpleITK uses [GDCM](https://github.com/malaterre/GDCM) under the hood (file extension doesn't matter, SimpleITK tries to read files using all of the supported IOs till one succeeds or all fail). 

The only tool that you haven't mentioned is [DCMTK](https://dicom.offis.de/dcmtk.php.en). Try loading the file using [Slicer](https://www.slicer.org/), it uses DCMTK under the hood, so no need to write code to try it.
