### ISSUE TITLE
CMake hangs on M1

### ISSUE THREAD

**Issue by shersoni610** [SimpleITK/SimpleITK#1976]
Hello, 

I am trying to install the software on M1. It always hangs at the same place: 

CMake Warning at Code/BasicFilters/src/CMakeLists.txt:13 (add_library):
   Target "SimpleITK_ITKSmoothing" requests linking to directory directory
   "/opt/homebrew/lib".  Targets may link only to libraries.  CMake is
   dropping the item.
 Call Stack (most recent call first):
   Code/BasicFilters/src/CMakeLists.txt:136 (add_filter_library)

 CMake Warning at Code/BasicFilters/src/CMakeLists.txt:13 (add_library):
   Target "SimpleITK_ITKSmoothing" requests linking to di

**Comment by blowekamp** [comment]
Please follow our guidelines for reporting an issue so that we have more informations about your environment, and how it was setup:
https://github.com/SimpleITK/SimpleITK#report-an-issue
