### ISSUE TITLE
sitk::ERROR: Pixel type: 32-bit unsigned integer is not supported in 3D byN3itk6simple15MaskImageFilterE

### ISSUE THREAD

**Issue by Czaki** [SimpleITK/SimpleITK#1991]
**Describe the bug**

When upgrade SimpleITK from 2.2.1 to 2.3.0 my test stopped working. It looks like  `sitk.Mask` stop supporting uint32

```
   /tmp/tox/py38-PyQt5-all/lib/python3.8/site-packages/PartSegCore/segmentation/segmentation_algorithm.py:238: in _segmentation_calculation
      return sitk.GetArrayFromImage(sitk.RelabelComponent(sitk.Mask(ws, sitk.Cast(seg_image, ws.GetPixelID())), 20))
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  image = <SimpleITK.SimpleITK.Image; proxy of <Swig Object of type 'itk::simple::Image *' at 0x7f76d5c6d0f0> >
  maskImage = <SimpleITK.SimpleITK.Image; proxy of <Swig Object of type 'itk::simple::Image *' at 0x7f76d58da570> >
  outsideValue = 0, maskingValue = 0
  
      def Mask(image, maskImage, outsideValue=0, maskingValue=0):
          r"""Mask(Image image, Image maskImage, double outsideValue=0, double maskingValue=0) -> Image"""
  >       return _SimpleITK.Mask(image, maskImage, outsideValue, maskingValue)
  E       RuntimeError: Exception thrown in SimpleITK Mask: /tmp/SimpleITK/Code/Common/include/sitkDualMemberFunctionFactory.hxx:190:
  E       sitk::ERROR: Pixel type: 32-bit unsigned integer is not supported in 3D byN3itk6simple15MaskImageFilterE
```

**To Reproduce**

1. Operating system, version, and architecture
 - All trhee os on Github Actions 
2. Programming language, and version [Python 3.8-3.11].
3. Version of SimpleITK 2.3.0
4. How was SimpleITK installed from pip or conda
5. A minimal working example which causes the error.

Following code works with 2.2.1 and crash on 2.3.0:

```python
import numpy as np
import SimpleITK as sitk

a = np.zeros((10, 10, 10), dtype=np.uint32)
b = np.ones((10, 10, 10), dtype=np.uint32)

a_itk = sitk.GetImageFromArray(a)
b_itk = sitk.GetImageFromArray(b)
sitk.Mask(a_itk, b_itk)
```

**Expected behavior**

The existing code should keep working.

**Comment by zivy** [comment]
Hello @Czaki,

This is not a bug, it is a behavior change in the [2.3.0 release](https://github.com/SimpleITK/SimpleITK/releases/tag/v2.3.0): "Change `MaskImageFilter` and `MaskNegatedImageFilter` to only support `sitkUInt8`..." .

If you change to SimpleITK version 2.3.0 you will need to update your code accordingly.

**Comment by Czaki** [comment]
Why do you introduce breaking change without bumping major number? 
There are multiple use cases (like napari plugins) when the user is not a code developer and just installs packages from PyPi so he will get the broken application. 

Here example of a different code that is broken by this change. 
https://github.com/haesleinhuepf/napari-simpleitk-image-processing/blob/83ae92fb2212b1b2aa225e3c6fb2ca414b1b8258/src/napari_simpleitk_image_processing/_simpleitk_image_processing.py#L516

Even if it needs to be changed there should be at least one release that supports both signatures for smooth migrations.

**Comment by blowekamp** [comment]
I would agree that this is a compatibility bug.

Sorry that the new version of SimpleITK is causing problems for your application. We will look into restoring support for pixel types in the MaskImageFilter, although it may produce warnings or be less efficient. Hopefully this can be done in a patch release.

> Why do you introduce breaking change without bumping major number? There are multiple use cases (like napari plugins) when the user is not a code developer and just installs packages from PyPi so he will get the broken application.

We work closely with the ITK development. ITK promotes backwards compatibility, and does a good job with it. There are always tweaks in algorithms, and processes which may have impact on results so I'd recommend pinning to `major.minor.*`, which could by pass this issue. This change appears to have gone too far.

The problematic code: 
`sitk.Mask(ws, sitk.Cast(seg_image, ws.GetPixelID()))` 

For compatibility with all version, it can be updated to ( will reduce the memory used ):
`sitk.Mask(ws, sitk.Cast(seg_image, sitk.sitkUInt8))`

Or using the slightly more explicit:
`sitk.Mask(ws, seg_image != 0)`
`


> EDIT.
> Additionally, SimpleITK do not export `PixelIDValueEnum` so it is not possible to simply cast to unit8 based on documentation, and the requirement to use `sitk.GetPixelIDValueFromString` that in documentation is mentioned as a function created especially for R does not look like a stable solution for python (at this moment `sitk.GetPixelIDValueFromString("sitkUInt8")` works for me - but it uses names not compatible with numpy one).

The `PixelIDValueEnum` identifiers are available in the SimpleITK namespace such as `sitkUInt8` which was used above. Where did the information that the `sitk.GetPixelIDValueFromString` method was required come from? Is there some documentation that we could help clarify?

Yes, SimpleITK pixel types and names and many other conventions are not compatible with numpy. SimpleITK bridges between ITK conventions and python conventions. Unfortunately it does not seamlessly integrate with python and numpy and usually there is a translation step coming into SimpleITK and going out of numpy. Masking the this step can lead to several kinds of bugs, that are best avoided by making the translation explicit.

**Comment by Czaki** [comment]
> The `PixelIDValueEnum` identifiers are available in the SimpleITK namespace such as `sitkUInt8` which was used above. Where did the information that the `sitk.GetPixelIDValueFromString` method was required come from? Is there some documentation that we could help clarify?

Id not found it. I just come to Cast documentation: https://simpleitk.org/doxygen/latest/html/namespaceitk_1_1simple.html#af8c9d7cc96a299a05890e9c3db911885 Where I got information that I need to use `PixelIDValueEnum` as second value to function. 

However, I found that I could not use `sitk.PixelIDValueEnum` as it raised an exception, so I started looking for a method to get this value and land with this function. 

Putting enum members in a global namespace is an uncommon practice, and I do not expect it.

Pythonic is to use `module.EnumClass.member` not `module.member`. Maybe some examples in the documentation will help. 


> Unfortunately it does not seamlessly integrate with python and numpy and usually there is a translation step coming into SimpleITK and going out of numpy

I was thinking about introduce aliases `PixelIDValueEnum.uint8` as alias for `PixelIDValueEnum.sitkUInt8`. But I could understand that it may be not so simple in case of wrappers generated from C++ code. 

> For compatibility with all version, it can be updated to ( will reduce the memory used ):
> `sitk.Mask(ws, sitk.Cast(seg_image, sitk.sitkUInt8))`

It will work with SimpleITK bellow 2.3.0? 

I have written this code in a time of 1.x.x. I have performed a few tests and it looks working, but reading the release notes does not suggest using sitkUInt8 as backward compatible. It only informs that until this release both types need to be identical, a there was a decision to break it and change it to sitkUInt8.

**Comment by blowekamp** [comment]
> Id not found it. I just come to Cast documentation: https://simpleitk.org/doxygen/latest/html/namespaceitk_1_1simple.html#af8c9d7cc96a299a05890e9c3db911885 Where I got information that I need to use `PixelIDValueEnum` as second value to function.

This the C++ Doxygen. As it is documentation for C++ this is a bit different, but there are some basic patterns that repeatedly occur and most developers pick up on them quick. Usually have going through a [SimpelITK tutorial](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) they are known.

In addition to the Notebook tutorials above there are the Sphinx docs which contains languages specific examples: https://simpleitk.readthedocs.io/en/master/


> However, I found that I could not use `sitk.PixelIDValueEnum` as it raised an exception, so I started looking for a method to get this value and land with this function.

The `Enum` class in Python was introduced in 3.4, so it's not too new. The numpy type ids are in the numpy space so the having the `PixelIDValueEnum` be under the sitk namespace does make since. There are may conventions with enum. I do think it is a good idea to have them under a `module.EnumClass.member` too. Please create a feature request to add this convention for enums to SimpleITK.

> I was thinking about introduce aliases `PixelIDValueEnum.uint8` as alias for `PixelIDValueEnum.sitkUInt8`. But I could understand that it may be not so simple in case of wrappers generated from C++ code.

There are some details encoded in the underlying numpy dtype, ( byte order ) that can present some complications, but creating a map from numpy to sitk types is a reasonable way to do things.



> > The `PixelIDValueEnum` identifiers are available in the SimpleITK namespace such as `sitkUInt8` which was used above. Where did the information that the `sitk.GetPixelIDValueFromString` method was required come from? Is there some documentation that we could help clarify?
> 
> Id not found it. I just come to Cast documentation: https://simpleitk.org/doxygen/latest/html/namespaceitk_1_1simple.html#af8c9d7cc96a299a05890e9c3db911885 Where I got information that I need to use `PixelIDValueEnum` as second value to function.
> 
> However, I found that I could not use `sitk.PixelIDValueEnum` as it raised an exception, so I started looking for a method to get this value and land with this function.
> 
> Putting enum members in a global namespace is an uncommon practice, and I do not expect it.
> 
> Pythonic is to use `module.EnumClass.member` not `module.member`. Maybe some examples in the documentation will help.
> 
> > Unfortunately it does not seamlessly integrate with python and numpy and usually there is a translation step coming into SimpleITK and going out of numpy
> 
> I was thinking about introduce aliases `PixelIDValueEnum.uint8` as alias for `PixelIDValueEnum.sitkUInt8`. But I could understand that it may be not so simple in case of wrappers generated from C++ code.
> 
> > For compatibility with all version, it can be updated to ( will reduce the memory used ):
> > `sitk.Mask(ws, sitk.Cast(seg_image, sitk.sitkUInt8))`
> 
> It will work with SimpleITK bellow 2.3.0?

I only testing 2.1.0, 2.2.0, 2.3.0. 

> 
> I have written this code in a time of 1.x.x. I have performed a few tests and it looks working, but reading the release notes does not suggest using sitkUInt8 as backward compatible. It only informs that until this release both types need to be identical, a there was a decision to break it and change it to sitkUInt8.

We can update the notes for clarification.

**Comment by Czaki** [comment]
> This the C++ Doxygen. As it is documentation for C++ this is a bit different, but there are some basic patterns that repeatedly occur and most developers pick up on them quick. Usually have going through a [SimpelITK tutorial](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) they are known.

But when one maintains code then going to tutorial is not the common thing (until bump major version). when I open the Python doc here https://simpleitk.readthedocs.io/en/master/conventions.html#images-as-parameters and see the link to `Cast` I land in C++ Doxygen. 



> Please create a feature request to add this convention for enums to SimpleITK.

I will do and try to contribute to documentation 

> I only testing 2.1.0, 2.2.0, 2.3.0.

❤️ 

> We can update the notes for clarification.

❤️

**Comment by blowekamp** [comment]
The legacy behavior was restored and a deprecated message produced in version 2.3.1
