### ISSUE TITLE
missing numpy dependency in python wheels and conda package

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#2004]
Installing SimpleITK using pip or conda into a minimal virtual environment, containing only the basic packages installed during environment creation, does not enforce the dependency on numpy. numpy isn't installed when SimpleITK is.

The following code raises an exception `ImportError: NumPy not available.`:
```
import SimpleITK as sitk
image = sitk.Image([1,1], sitk.sitkUInt8)
arr = sitk.GetArrayFromImage(image)
```

**Comment by blowekamp** [comment]
numpy should be an optional package not a require package. This may be the expected behavior.

**Comment by zivy** [comment]
Sounds reasonable, this is the only place where SimpleITK depends on numpy. Also, I suspect this is an unlikely scenario, encountered when installing SimpleITK into a pristine virtual environment with no other packages beyond the bare minimum.

Will close the issue.
