### ISSUE TITLE
Extend sitk.ReadImage()/WriteImage() to support pathlib.Path()

### ISSUE THREAD

**Issue by bdzyubak-aiq** [SimpleITK/SimpleITK#2038]
**Is the feature request related to a problem? Please describe.**
While strings are handled as inputs, Path, a common alternative, is not and reading/writing crashes. 

**Describe the proposed solution**
Add str(input) inside the two functions so that conversions don't have to be done on the user end. 

**Describe any alternatives to consider**
None. The above is a simple usability fix. 

**Additional context**
None

**Comment by blowekamp** [comment]
This feature is available in SimpleITK versions 2.2.0 and above.
