### ISSUE TITLE
simpleITK python acts differently while reading metadata with upper or lower case hexadecimal label

### ISSUE THREAD

**Issue by xingyunjohn1** [SimpleITK/SimpleITK#2047]
**Describe the bug**
I can only read series description ('0008|103e' or '0008|103E') with lower case ('0008|103e').

**To Reproduce**

1. Operating system, version, and architecture
 - OS: Windows 11 PRO 21H2
 - Architecture: Intel x86_64
2. Programming language, and version: Conda Python 3.8.17
3. Version of SimpleITK [e.g. 1.1.0], output of the SimpleITK Version() function:  2.3.1 (ITK 5.3)
4. How was SimpleITK installed?
 - [x] binary distribution [e.g. python -m pip install SimpleITK]

5. A minimal working example which causes the error.
```Python
import SimpleITK as sitk

def read_dicom_series_description(dicom_path, key):
    reader = sitk.ImageFileReader()
    reader.SetFileName(dicom_path)
    reader.LoadPrivateTagsOn()
    reader.ReadImageInformation()
    
    if reader.HasMetaDataKey(key):
        series_description = reader.GetMetaData(key)
    else:
        series_description = 'NA'
    
    return series_description

dicom_path = r'path\to\your\dicom'
key = "0008|103E"
print(f"Series Description with {key}:", read_dicom_series_description(dicom_path, key))
key = "0008|103e"
print(f"Series Description with {key}:", read_dicom_series_description(dicom_path, key))
print(sitk.Version())
```
**Expected behavior**

> Series Description with 0008|103E: 3 Plane Localizer 
> Series Description with 0008|103e: 3 Plane Localizer 
> SimpleITK Version: 2.3.1 (ITK 5.3)
> Compiled: Nov  1 2023 12:40:43

**Unexpected behavior**

> Series Description with 0008|103E: NA
> Series Description with 0008|103e: 3 Plane Localizer 
> SimpleITK Version: 2.3.1 (ITK 5.3)
> Compiled: Nov  1 2023 12:40:43

**Comment by blowekamp** [comment]
This behavior was recently documented in the examples here: bee90d54942f54bd5042cd6877a5ee96cae1073e

@zivy Perhaps we need to clarify the documentation in the Image readers too?

**Comment by dzenanz** [comment]
[This example](https://simpleitk.readthedocs.io/en/v1.2.2/Examples/DicomSeriesReadModifyWrite/Documentation.html) still uses uppercase (`"0020|000D", # Study Instance UID`), which just bit me. I spent 1.5 hours chasing this down (derived series does not match the original one at study level).

**Comment by blowekamp** [comment]
> [This example](https://simpleitk.readthedocs.io/en/v1.2.2/Examples/DicomSeriesReadModifyWrite/Documentation.html) still uses uppercase (`"0020|000D", # Study Instance UID`), which just bit me. I spent 1.5 hours chasing this down (derived series does not match the original one at study level).

Is there specific change in the Example, SimpleITK documentation or in ITK that would help address this issue?

**Comment by dzenanz** [comment]
Yes, changing that to lower case `"0020|000D"` -> `"0020|000d"` might save some trouble to somebody in the future.

**Comment by zivy** [comment]
Hello @dzenanz, sorry about that. [This PR](https://github.com/SimpleITK/SimpleITK/pull/2057) addresses the issue.
