### ISSUE TITLE
Figure illustrating image concepts doesn't have clear text

### ISSUE THREAD

**Issue by dstansby** [SimpleITK/SimpleITK#2050]
**Describe the bug**
The image explaining image concepts is showing up at low resolution for me, which makes the text hard to read.

**To Reproduce**

Go to https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html#lbl-image-metadata:

![Screenshot 2024-02-20 at 16 22 27](https://github.com/SimpleITK/SimpleITK/assets/6197628/eec70001-ea07-4e4f-b10e-2764df157eab)

1. Operating system, version, and architecture
 - OS: [e.g. OSX 12.6.8 ]
 - Architecture: [e.g. Apple ARM M1]
2. Programming language, and version [e.g. Python 2.7.14, R 3.2.3].
3. Version of SimpleITK [e.g. 1.1.0], output of the SimpleITK Version() function.
4. How was SimpleITK installed?
 - binary distribution [e.g. python -m pip install SimpleITK]
 - built it from source [e.g. devtools::install_github("SimpleITK/SimpleITKRInstaller")]
5. A minimal working example which causes the error.

**Expected behavior**

**Images**
If applicable, include a minimal sized sample input and output image. Or SimpleITK commands to synthetically generate
an input.

**Additional context**

**Comment by gdevenyi** [comment]
Its fine for me.

**Comment by blowekamp** [comment]
This image is an SVG. It does appear clearer in Chrome than Safari, but not nearly as bas as the posted image. It may be some font issue.

**Comment by dstansby** [comment]
I'm using Firefox 122.0.1 on macOS 14. Maybe changing the font (to something sans-serif?) would help?

**Comment by gdevenyi** [comment]
Can confirm its bad on Firefox 123 on Kubuntu 22.04. My screenshot is from an Electron Chrome (v???)

**Comment by zivy** [comment]
This is the original image from ITK which is not easy to modify, so keeping it as is till ITK updates its documentation.
