### ISSUE TITLE
ThresholdImage filter in Python

### ISSUE THREAD

**Issue by ppieperhoff** [SimpleITK/SimpleITK#2051]
Dear ITK developers,
I encountered a somewhat non-intuitive behaviour of the ThresholdImage filter in SimpleITK, using the Python-interface
(python 3.10.12, on Linux).
My aim is that I want to keep all voxel values above a threshold of e.g. 10.
The following code: 

    t = sitk.ThresholdImageFilter()
    t.SetOutsideValue(0)
    t.SetLower(10)
    out_image = t.Execute(in_image)

yields an image that contains only zeros. Obviously, because the upper threshold is by default 1.

However, the following code

    t = sitk.ThresholdImageFilter()
    t.SetOutsideValue(0)
    t.SetLower(10)
    t.SetUpper(256)
    out_image = t.Execute(in_image)

yields different results, depending on the data type of the input image, i.e. when the input image has type unsigned character (8 bit), the output image contains only zeros. It seems, that the upper threshold 256 is simply type-casted to unsigned character, yielding an upper threshold of zero.
However, when I cast the input image to e.g. 16bit-unsigned int ( out_image = t.Execute( sitk.Cast(in_image, sitk.sitkUInt16) ) ),
the threshold-filter works correctly.

But the problem is, that in order to "disable" the upper threshold, I must set the upper threshold equal to the maximal voxel value in the input image, and this depends on its data type. 
It would be more intuitive, when the type casting of the thresholds taked into account the value range of the input image. E.g., when the input image has type unsigned character, an upper threshold of  256 or larger is replaced by 255 (or simply ignored).
An alternative would be, that the upper or lower threshold could be explicitly disabled.

**Comment by blowekamp** [comment]
Changing the behavior of the filters may break others code.

It looking the the C++ ITK has `ThresholdAbove`, `ThresholdBelow` and `ThresholdOutside` which are missing in the SimpleITK interface. 
https://itk.org/Doxygen/html/classitk_1_1ThresholdImageFilter.html#ae77a7917417c094691036b5a5c85a02b

Would these method be suitable for your purpose?

**Comment by blowekamp** [comment]
Addressed in PR #2068
