### ISSUE TITLE
Add docs on how to set/get the mask on an image

### ISSUE THREAD

**Issue by dstansby** [SimpleITK/SimpleITK#2053]
**Is the feature request related to a problem? Please describe.**
I'm currently trying to understand how to set a mask on an image, but struggling to find any information on this in the user guide. The only bit on masks I can find is https://simpleitk.readthedocs.io/en/master/conventions.html#mask-image-types-and-default-values, but that just describes the mask data type, not how to set a mask.

**Describe the proposed solution**
Documentation on how to set a mask on an image.

**Comment by blowekamp** [comment]
This issue was cross posted in ITK Discourse: https://discourse.itk.org/t/how-to-get-image-mask-in-simpleitk/6470/2

Which describes the differences between a SimpleITK image masks which are different than numpy array masking.
