### ISSUE TITLE
How to convert DisplacementFieldTransform to Image format and save it?

### ISSUE THREAD

**Issue by yuanpengpeng** [SimpleITK/SimpleITK#2074]
How to convert DisplacementFieldTransform to Image format and save it?
For example, as shown below:
   final_transform = sitk.DisplacementFieldTransform(displacement_field)
I want to save final_transform to .nii.gz format

**Comment by dave3d** [comment]
The method [GetDisplacementField](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1DisplacementFieldTransform.html#a9e942dd186ed2c4c3e1951caea8cfe29) returns an Image that you can save as .nii.gz with the WriteImage function.
