### ISSUE TITLE
RuntimeError std::exception without informative message

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#208]
For some "active measurement" functions, if the data is not available an std::exception is thrown which contains no informative error message.

This happens for the ImageSeriesReader if we call the GetMetaDataKeys and the meta-data dictionary wasn't read (didn't set MetaDataDictionaryArrayUpdateOn before calling the reader's execute).

Interestingly, for another class where I expected similar behavior, the method returned a valid value, zero, which is similar to returning an empty dictionary:
```
import SimpleITK as sitk
fltr = sitk.LabelOverlapMeasuresImageFilter()
fltr.GetDiceCoefficient()
```
 We seem to have an inconsistency here whether to throw exceptions or return a value.

**Comment by blowekamp** [comment]
The `LabelOverlapMeasuresImageFilter::GetDiceCoefficient` is different from what function pointer "active measurement" such as `ImageSeriesReader::GetMetaDataKeys(unsigned int)` or 1LabelShapeStatisticsImageFiler::NumberOfPixels(unint64_t)`. The latter are implemented with std(::tr1)::function to form closures with the underlying ITK filters. In the json both are under the `measurement` dictionary field, but the later ones have the `active` field set to true.

Now, that is the difference in the underlying implementation. Should there be a different behavior? Should the both throw an exception or should they both have a default value?

**Comment by blowekamp** [comment]
@zivy Can you look into this to see if it's still an issue.

**Comment by zivy** [comment]
The main issue was with the inconsistency, throwing exceptions vs. a default return value. After digging into this, it appears that this is what ITK does. Changing ITK to throw an exception when a Get method is invoked before the value is available is a cross ITK change and is outside our scope.
