### ISSUE TITLE
Race condition in ErodeObjectMorphologyImageFilter

### ISSUE THREAD

**Issue by makarovNick** [SimpleITK/SimpleITK#2095]
**GlobalDefaultNumberOfThreads affects result**
Applying ErodeObjectMorphologyImageFilter on binary image produces different result with 
GlobalDefaultNumberOfThreads > 1

**To Reproduce**

1. Operating system, version, and architecture
 - OS: [Ubuntu 18.4]
Architecture:        x86_64
CPU(s):              16
2. Programming language: Python 3.9.14]
3. Version of SimpleITK:
tested on 2.1.0, 2.2.0, 2.3.1

5. How was SimpleITK installed?
 - binary distribution [e.g. python -m pip install SimpleITK]
6. A minimal working example which causes the error.
data - [shape.zip](https://github.com/SimpleITK/SimpleITK/files/14981544/shape.zip)
```python3
import SimpleITK as sitk
img = sitk.ReadImage("shape.nrrd")

sitk.ProcessObject.SetGlobalDefaultNumberOfThreads(1)
eroded_img = sitk.ErodeObjectMorphology(img)
result_volume = sitk.GetArrayFromImage(eroded_img).sum()
print("Expecting volume: ", result_volume)

sitk.ProcessObject.SetGlobalDefaultNumberOfThreads(16)
for _ in range(10):
    eroded_img = sitk.ErodeObjectMorphology(img)
    volume = sitk.GetArrayFromImage(eroded_img).sum()
    if result_volume != volume:
        print("Wrong result! Got", volume)
```
Got:
```
Expecting volume:  6039
Wrong result! Got 6213
Wrong result! Got 6109
Wrong result! Got 6046
Wrong result! Got 6119
Wrong result! Got 6212
Wrong result! Got 6042
Wrong result! Got 6183
Wrong result! Got 6212
Wrong result! Got 6044
```

**Expected behavior**
Expecting eroded image to be the same

**Additional context**
Also Is it supposed to work differently from sitk.BinaryErode ? Because sitk.BinaryErode gives different result for this image :)

**Comment by blowekamp** [comment]
I usually use the Binary Morphology filters or a Grayscale Morphology filters to perform binary morphology operations.

I was able to reproduce the race condition, and reviewed the code for the ObjectMorphology filters. It appears that there is a fundamental issue with the set of filters using the "output" image to both sample the kernel and write to it.

This is an ITK issue could you please repost the issue onto InsightSoftwareConsortium/ITK?
