### ISSUE TITLE
Discrepancy in Image Size and Spacing Order When Converting from Numpy Array to SimpleITK Image

### ISSUE THREAD

**Issue by javierlopezrodriguez** [SimpleITK/SimpleITK#2135]
Hello!

I encountered an issue where the order of the dimensions and spacing is inconsistent when converting a 3D numpy array to a SimpleITK image. Specifically, the image size and spacing appear to be misaligned between the numpy array and the SimpleITK image. I don't understand why this happens.

```
import SimpleITK as sitk
import numpy as np

# Example numpy array
np_array = np.random.rand(200, 300, 300).astype(np.float32)  # Shape (Z, Y, X)

# Spacing for numpy array (dz, dy, dx)
spacing = (0.795, 0.776, 0.776)  # Corresponding to (Z, Y, X)

# Convert numpy array to SimpleITK image
sitk_image = sitk.GetImageFromArray(np_array)
sitk_image.SetSpacing(spacing)

# Print to check the size and spacing
print("Size:", sitk_image.GetSize())
print("Spacing:", sitk_image.GetSpacing())
```

Expected output:
```
Size: (200, 300, 300)
Spacing: (0.795, 0.776, 0.776)
# in (Z, Y, X) order
# or
Size: (300, 300, 200)
Spacing: (0.776, 0.776, 0.795)
# in (X, Y, Z) order
```

Actual output:
```
Size: (300, 300, 200) # (X, Y, Z)
Spacing: (0.795, 0.776, 0.776) # (Z, Y, X)
```

I'm new to this library so I'm probably missing something, but I have not found anything in the documentation related to the order in which I need to set the spacing, so I would assume it has to be in the same order as the dimensions of the numpy array. Thanks in advance!

**Comment by gdevenyi** [comment]
The spacing of numpy vs SimpleITK images are different, described in the notebook here:
https://simpleitk.org/SimpleITK-Notebooks/01_Image_Basics.html

It looks like you're trying to the spacing using the numpy array ordering whereas the spacing call is a SimpleITK call, which needs to be in SimpleITK ordering.

**Comment by javierlopezrodriguez** [comment]
I missed that, thank you!
