### ISSUE TITLE
Link errors building v2.3.1 on Windows with Elastix: LNK2005 duplicate symbols in minc2.lib itkminc2-5.3.lib itktiff-5.3.lib

### ISSUE THREAD

**Issue by ryanseghers** [SimpleITK/SimpleITK#2166]
**Describe the bug**
I'm getting link errors when compiling SimpleITK v2.3.1 (with Elastix enabled) on Windows. I get the same errors from both a command-line and a Visual Studio build. I'm building Release x64 config.

I'm on an up-to-date Win 11 machine, latest Visual Studio 2022 Pro (and have tried a previous version), and latest Windows SDK (I've tried 10.0.19041.0, 10.0.22621.0, and 10.0.26100.0). 

Here are some examples of the errors:
itktiff-5.3.lib(tif_luv.obj) : error LNK2005: __ucrt_int_to_float already defined in itktiff-5.3.lib(tif_aux.obj) [C:\ACP\SimpleITK-build\Elastix-build\Core\elastix_exe.vcxproj] [C:\ACP\SimpleITK-bui
ld\Elastix.vcxproj]

minc2.lib(time.c.obj) : error LNK2005: current_cpu_seconds already defined in itkminc2-5.3.lib(time.obj) [C:\ACP\SimpleITK-build\Elastix-build\Core\elastix_exe.vcxproj] [C:\ACP\SimpleITK-build\Elasti
x.vcxproj]

itkgdcmMSFF-5.3.lib(gdcmDirectionCosines.obj) : error LNK2005: "public: __cdecl gdcm::DirectionCosines::DirectionCosines(double const * const)" (??0DirectionCosines@gdcm@@QEAA@QEBN@Z) already defined
 in gdcmMSFF.lib(gdcmDirectionCosines.cxx.obj) [C:\ACP\SimpleITK-build\Elastix-build\Core\elastix_exe.vcxproj] [C:\ACP\SimpleITK-build\Elastix.vcxproj]

All the rest of the (50 or so) errors are just other symbols in these same object files.

**To Reproduce**

1. Operating system, version, and architecture
 - OS: Windows 11
 - Architecture: x64
2. Programming language, and version: I'm trying to build.
3. Version of SimpleITK: v2.3.1 tag
4. How was SimpleITK installed? I'm trying to build
5. A minimal working example which causes the error:
set SIMPLE_ITK_VERSION_TAG=v2.3.1
set TOP_DIR=C:\ACP
set BUILD_DIR=%TOP_DIR%\SimpleITK-build
md %TOP_DIR%
cd %TOP_DIR%
git clone --branch %SIMPLE_ITK_VERSION_TAG% https://github.com/SimpleITK/SimpleITK.git
md %BUILD_DIR%
cd %BUILD_DIR%
cmake -D SimpleITK_USE_ELASTIX=True ../SimpleITK/SuperBuild
cmake --build . --config Release

**Expected behavior**
The build should work without error.

**Images**

**Additional context**

**Comment by blowekamp** [comment]
The versions you are using a a couple years old. We have just updated Elastix since the 2.4rc2 release: https://github.com/SimpleITK/SimpleITK/pull/2104

Could you please try building with the current master to see if the issue is still exists?

**Comment by ryanseghers** [comment]
I just tried master and it fails earlier in the build, and without turning on elastix, so completely default build:
   ...
    Generating Code...
    ITKTestKernel.vcxproj -> C:\ACP\SimpleITK-build\ITK-build\lib\Release\ITKTestKernel-5.4.lib
    Building Custom Rule C:/ACP/SimpleITK-build/ITK/Modules/Core/TestKernel/src/CMakeLists.txt
    itkTestDriver.cxx
ITKCommon-5.4.lib(itkMultiThreaderBase.obj) : error LNK2005: "public: static void __cdecl itk::MultiThreaderBase::SetGlobalDefaultNumberOfThreads(unsigned int)" (?SetGlobalDefaultNumberOfThreads@Mult
iThreaderBase@itk@@SAXI@Z) already defined in ITKCommon-5.3.lib(ITKCommon-5.3.dll) [C:\ACP\SimpleITK-build\ITK-build\Modules\Core\TestKernel\src\itkTestDriver.vcxproj] [C:\ACP\SimpleITK-build\ITK.vcxproj]
(and many more from these same lib files)

**Comment by blowekamp** [comment]
What CMake version are you using?

**Comment by ryanseghers** [comment]
I've done all the above tries with 3.26.3 but have a build running now with the latest 3.30.1.

**Comment by ryanseghers** [comment]
It also failed for me with cmake 3.30.1, and then also 3.27.9. However, a colleague built successfully so I conclude there is some other tool or environment variable that is different on my machine that is causing the problem but I'm not going to try to track it down so closing this issue.
