### ISSUE TITLE
How do I convert single .dcm file into a sequence with pydicom

### ISSUE THREAD

**Issue by jiaomei222** [SimpleITK/SimpleITK#2175]
How do I convert single .dcm file into a sequence with pydicom
![357367329-cb8809c7-c8d0-4bb7-9754-15dc093df70c](https://github.com/user-attachments/assets/e2b93782-c242-411e-88bd-89f16e7151b1)

![357367375-4cd9aa6f-0c8b-49db-ac9b-cb193222144c](https://github.com/user-attachments/assets/4d3ce2b4-cece-4a27-aeab-c51cf2dd9c4e)

**Comment by zivy** [comment]
Hello @jiaomei222,
This is the issue tracker for SimpleITK not pydicom, so you are asking the question in the wrong place. 

Having said this, using SimpleITK, you can split a multi-frame DICOM file into the separate frames using a slight change to [this example](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReadModifyWrite_docs.html), see code below:

```
import SimpleITK as sitk

import sys
import time
import os

if len(sys.argv) < 3:
    print(
        "Usage: python "
        + __file__
        + " <DICOM file> <output_directory>"
    )
    sys.exit(1)

file_reader = sitk.ImageFileReader()
file_reader.LoadPrivateTagsOn()
file_reader.SetFileName(sys.argv[1])
image3D = file_reader.Execute()
direction = image3D.GetDirection()


writer = sitk.ImageFileWriter()
# Use the study/series/frame of reference information given in the meta-data
# dictionary and not the automatically generated information from the file IO
writer.KeepOriginalImageUIDOn()

# Copy relevant tags from the original meta-data dictionary (private tags are
# also accessible).
tags_to_copy = [
    "0010|0010",  # Patient Name
    "0010|0020",  # Patient ID
    "0010|0030",  # Patient Birth Date
    "0020|000D",  # Study Instance UID, for machine consumption
    "0020|0010",  # Study ID, for human consumption
    "0008|0020",  # Study Date
    "0008|0030",  # Study Time
    "0008|0050",  # Accession Number
    "0008|0060",  # Modality
    "0008|0031",  # Series Time
    "0008|0021",  # Series Date
    "0008|0008",  # Image Type
    "0020|000e",  # Series Instance UID
    "0008|0012",  # Instance Creation Date
    "0008|0013",  # Instance Creation Time
]

series_tag_values = [
    (k, image3D.GetMetaData(k.lower()))
    for k in tags_to_copy
    if image3D.HasMetaDataKey(k.lower())
] + [
    (
        "0020|0037",
        "\\".join(
            map(
                str,
                (
                    direction[0],
                    direction[3],
                    direction[6],
                    direction[1],
                    direction[4],
                    direction[7],
                ),  # Image Orientation (Patient)
            )
        ),
    ),
    (
        "0008|103e",
        image3D.GetMetaData("0008|103e")
        if image3D.HasMetaDataKey("0008|103e")
        else "",
    ),  # Series Description is an optional tag, so may not exist
]

for i in range(image3D.GetDepth()):
    image_slice = image3D[:, :, i]
    # Tags shared by the series.
    for tag, value in series_tag_values:
        image_slice.SetMetaData(tag, value)
    #   Image Position (Patient)
    image_slice.SetMetaData(
        "0020|0032",
        "\\".join(map(str, image3D.TransformIndexToPhysicalPoint((0, 0, i)))),
    )
    #   Instance Number
    image_slice.SetMetaData("0020|0013", str(i))

    # Write to the output directory and add the extension dcm, to force writing
    # in DICOM format.
    writer.SetFileName(os.path.join(sys.argv[2], str(i) + ".dcm"))
    writer.Execute(image_slice)
sys.exit(0)
```

**Comment by jiaomei222** [comment]
> Hello @jiaomei222, This is the issue tracker for SimpleITK not pydicom, so you are asking the question in the wrong place.
> 
> Having said this, using SimpleITK, you can split a multi-frame DICOM file into the separate frames using a slight change to [this example](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReadModifyWrite_docs.html), see code below:
> 
> ```
> import SimpleITK as sitk
> 
> import sys
> import time
> import os
> 
> if len(sys.argv) < 3:
>     print(
>         "Usage: python "
>         + __file__
>         + " <DICOM file> <output_directory>"
>     )
>     sys.exit(1)
> 
> file_reader = sitk.ImageFileReader()
> file_reader.LoadPrivateTagsOn()
> file_reader.SetFileName(sys.argv[1])
> image3D = file_reader.Execute()
> direction = image3D.GetDirection()
> 
> 
> writer = sitk.ImageFileWriter()
> # Use the study/series/frame of reference information given in the meta-data
> # dictionary and not the automatically generated information from the file IO
> writer.KeepOriginalImageUIDOn()
> 
> # Copy relevant tags from the original meta-data dictionary (private tags are
> # also accessible).
> tags_to_copy = [
>     "0010|0010",  # Patient Name
>     "0010|0020",  # Patient ID
>     "0010|0030",  # Patient Birth Date
>     "0020|000D",  # Study Instance UID, for machine consumption
>     "0020|0010",  # Study ID, for human consumption
>     "0008|0020",  # Study Date
>     "0008|0030",  # Study Time
>     "0008|0050",  # Accession Number
>     "0008|0060",  # Modality
>     "0008|0031",  # Series Time
>     "0008|0021",  # Series Date
>     "0008|0008",  # Image Type
>     "0020|000e",  # Series Instance UID
>     "0008|0012",  # Instance Creation Date
>     "0008|0013",  # Instance Creation Time
> ]
> 
> series_tag_values = [
>     (k, image3D.GetMetaData(k.lower()))
>     for k in tags_to_copy
>     if image3D.HasMetaDataKey(k.lower())
> ] + [
>     (
>         "0020|0037",
>         "\\".join(
>             map(
>                 str,
>                 (
>                     direction[0],
>                     direction[3],
>                     direction[6],
>                     direction[1],
>                     direction[4],
>                     direction[7],
>                 ),  # Image Orientation (Patient)
>             )
>         ),
>     ),
>     (
>         "0008|103e",
>         image3D.GetMetaData("0008|103e")
>         if image3D.HasMetaDataKey("0008|103e")
>         else "",
>     ),  # Series Description is an optional tag, so may not exist
> ]
> 
> for i in range(image3D.GetDepth()):
>     image_slice = image3D[:, :, i]
>     # Tags shared by the series.
>     for tag, value in series_tag_values:
>         image_slice.SetMetaData(tag, value)
>     #   Image Position (Patient)
>     image_slice.SetMetaData(
>         "0020|0032",
>         "\\".join(map(str, image3D.TransformIndexToPhysicalPoint((0, 0, i)))),
>     )
>     #   Instance Number
>     image_slice.SetMetaData("0020|0013", str(i))
> 
>     # Write to the output directory and add the extension dcm, to force writing
>     # in DICOM format.
>     writer.SetFileName(os.path.join(sys.argv[2], str(i) + ".dcm"))
>     writer.Execute(image_slice)
> sys.exit(0)
> ```

Thank you very much for your reply and it works well, I apologize for saying the wrong name.

**Comment by zivy** [comment]
Hello @jiaomei222,
Closing this issue. Happy to see the code addressed your needs.
