### ISSUE TITLE
[Python] Nifti metadata cannot be modified

### ISSUE THREAD

**Issue by Karol-G** [SimpleITK/SimpleITK#2177]
**Describe the bug**
It is not possible in Python to load a Nifti image, modify existing metadata attributes, and save the image with the new metadata. No exception is thrown but all modified metadata is discarded.

**To Reproduce**

1. Operating system, version, and architecture
- Ubuntu 20.04.6 LTS

2. Programming language
- Python 3.12.4

3. Version of SimpleITK
- SimpleITK Version: 2.3.1 (ITK 5.3)
- Compiled: Nov  1 2023 12:24:28

4. How was SimpleITK installed?
- pip install SimpleITK

5. A minimal working example which causes the error.

```python
import SimpleITK as sitk

load_filepath = "image.nii.gz"
save_filepath = "new_image.nii.gz"

print("Load image...")
image_sitk = sitk.ReadImage(load_filepath)
print("intent_code: ", image_sitk.GetMetaData("intent_code"))
print("ITK_FileNotes: ", image_sitk.GetMetaData("ITK_FileNotes"))
print("pixdim[1]: ", image_sitk.GetMetaData("pixdim[1]"))
image_sitk.SetMetaData("intent_code", "1002")
image_sitk.SetMetaData("ITK_FileNotes", "Test")
image_sitk.SetMetaData("pixdim[1]", "15")
sitk.WriteImage(image_sitk, save_filepath)

print("Load new image...")
image_sitk = sitk.ReadImage(save_filepath)
print("intent_code: ", image_sitk.GetMetaData("intent_code"))
print("ITK_FileNotes: ", image_sitk.GetMetaData("ITK_FileNotes"))
print("pixdim[1]: ", image_sitk.GetMetaData("pixdim[1]"))
```

**Expected behavior**
Image should be saved with modified metadata.

**Comment by gdevenyi** [comment]
I'm pretty sure the "metadata" you're modifying (excepting the ITK_FileNotes) is considered fundamental imaging properties which are used during reading into an ITK image, and hence written out again to accurately represent the data. You might have better luck with nibabel which allows arbitrarily modifying the NIFTI structure with no restrictions.

In the case of ITK_FileNotes I think that is also automatically generated.

For you example, can you please show the output.

**Comment by zivy** [comment]
Hello @Karol-G,

Confirming @gdevenyi's response with respect to the `intent_code` and `pixdim` entries. ITK deduces the values from the image itself and meta-data dictionary content is ignored. You can change the image data if you want to change these (i.e. `image_sitk.SetSpacing(new_spacing)`).

With respect to the `ITK_FileNotes` that is possibly an issue in ITK. This isn't the actual field in the [nifti header format](https://nifti.nimh.nih.gov/pub/dist/src/niftilib/nifti1.h). The field is called `descrip` in the header and is limited to 79 characters (the 80'th is the null character).

Please close this issue and open an issue on the [ITK issue tracker](https://github.com/InsightSoftwareConsortium/ITK/issues) requesting support for writing the `ITK_FileNotes` metadata dictionary entry if it exists. Feel free to point back to this issue to provide context.

**Comment by Karol-G** [comment]
Thank you for your quick responses. I wasn't aware that ITK deduces the values from the image and ignores the metadata dict.

**Comment by Karol-G** [comment]
I opened a question regarding my problem [here](https://discourse.itk.org/t/save-a-custom-attribute-in-header-of-nifti/7178).
