### ISSUE TITLE
Problem in Win32 Release mode 

### ISSUE THREAD

**Issue by mahdiye-imanpanah** [SimpleITK/SimpleITK#2188]
Hi guys
I need the 32-bit version of SimpleITK c#, so I tried to build it using Cmake - Visual Studio 2022.
I set the platform to Win32 and the configuration to Release, the build is successful and I have access to these files after building-> SimpleITKCSharpManaged.dll and SimpleITKCSharpNative.dll
The problem is that while using these DLLs, even when my project type is x86 and release mode, my application crashes.
What should I do to fix this problem?

**Comment by zivy** [comment]
Hello @mahdiye-imanpanah,

For us to help you, you will need to be more specific, beyond application crashes. Possibly provide a minimal working example.

As a first step, try to run the basic C# examples from read-the-docs [Hello World](https://simpleitk.readthedocs.io/en/master/link_HelloWorld_docs.html) or [CSharp Integration](https://simpleitk.readthedocs.io/en/master/link_CSharp_docs.html) and let us know if those crash on your system (this code is known to run correctly).

**Comment by mahdiye-imanpanah** [comment]
I checked the dlls on projects you shared, it crashes too.

The error is like below:
"System.AccessViolationException
Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

You should know that the program works fine with the binaries in the release part of sitk Github in x64 in both release and debug mode.(I need to build the SimpleItk manually)

I tried to build SimpleItk in both x64 and x86 using Cmake3.30 and Visual Studio 2022 and after building the SimpleITKCSharpNative.dll and SimpleITKCSharpManaged were created but they don't act like binaries in this part:https://github.com/SimpleITK/SimpleITK/releases/download/v2.4.0/SimpleITK-2.4.0-CSharp-win64-x64.zip

I used the SimpleItk build construction to build:
https://simpleitk.readthedocs.io/en/master/buildingWindows.html#building-simpleitk-in-visual-studio

Is there something wrong with the building process?
How should I build the source to get the right DLLs?

**Comment by dave3d** [comment]
I don't think SImpleiTK or ITK have supported 32-bit builds in a long time.  So it would not surprise me that it doesn't work.

**Comment by zivy** [comment]
@blowekamp, any insight 😉 on this?

**Comment by mahdiye-imanpanah** [comment]
@zivy @dave3d @blowekamp 
I know SimpleItk might not work in 32-bit, but my main problem is that even when I build it in 64-bit mode(the one I built using Camke and Visual Studio "not" the binaries in the Sitk Github page)the same crash happens.
I believe if the build steps are correct the output of 64-bit should be the same as the ones in the below link:
https://github.com/SimpleITK/SimpleITK/releases/download/v2.4.0/SimpleITK-2.4.0-CSharp-win64-x64.zip
Do you agree??
I just want to know how to build SimpleItk that works correctly even in 64-bit mode.
Any help would be appreciated.

**Comment by blowekamp** [comment]
With either of your builds are you able to successfully run the test suit?

**Comment by mahdiye-imanpanah** [comment]
I tried to run the tests and the result is attached to this message in a text file.
It also can be helpful to help me and give me points on how to build the SimpleItk c# correctly.
[SitkTestResult.txt](https://github.com/user-attachments/files/17173452/SitkTestResult.txt)
@blowekamp

**Comment by blowekamp** [comment]
By knowing the test fail we have narrowed down the problem and eliminated the issue of  how you are building your application to an issue. What is the output of one of the failing tests:

`ctest -V -R CSharp.AbsImageFilter.short`

**Comment by mahdiye-imanpanah** [comment]
I just tried to build it using Visual Studio 2019 instead of 2022 and problem solved.
Thank you all dears 
@blowekamp @zivy @dave3d

**Comment by zivy** [comment]
Hello @mahdiye-imanpanah,

You are welcome. Best of luck with your work.

**Comment by dave3d** [comment]
@mahdiye-imanpanah I'm glad to hear that you got it working.

**Comment by blowekamp** [comment]
Thank you for posting the solution. We do have a 64-bit build of windows with CSharp enabled running in Github Action:
https://github.com/SimpleITK/SimpleITK/blob/master/.github/workflows/BatchBuild.yml#L51-L61

I am going to conclude that this is a Win32 specific issue and does not need further attention.

Also note that the vs2019 MSVC toolset can be selected it VS 2022 with [CMAKE_GENERATOR_TOOLSET](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html) CMake [configuration variable](https://github.com/SimpleITK/SimpleITK/blob/master/.github/workflows/Package.yml#L116).
