### ISSUE TITLE
`SyntaxWarning` in Python 3.12 

### ISSUE THREAD

**Issue by fepegar** [SimpleITK/SimpleITK#2189]
## Describe the bug

This is not really a bug, just a slightly annoying warning:

```python-traceback
SyntaxWarning: invalid escape sequence '\s'
```

It happens because of this line

https://github.com/SimpleITK/SimpleITK/blob/df1d8445de88392ab9df549a0791bf72dcc3e157/Wrapping/Python/SimpleITK/extra.py#L476

which was introduced four years ago in https://github.com/SimpleITK/SimpleITK/commit/3acb4c5af3566d49fe98e0c51592c778a52bc97a.

I haven't seen that syntax in other Python files, but I have seen in some header files such as

https://github.com/SimpleITK/SimpleITK/blob/df1d8445de88392ab9df549a0791bf72dcc3e157/Code/Common/include/sitkInterpolator.h#L41

so I'm guessing it was an accident.

[Python 3.12 upgraded the `DeprecationWarning` to a `SyntaxWarning`](https://docs.python.org/3/whatsnew/3.12.html#other-language-changes) and that's why we see it now by default.

### Python 3.11

```bash
uv venv --python 3.11 sitk311
source sitk311/bin/activate
uv pip install SimpleITK
python -Wd -c "import SimpleITK"  # note the flags to show deprecation warnings
```

Output:

```python-traceback
<frozen importlib._bootstrap>:241: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute
<frozen importlib._bootstrap>:241: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute
<frozen importlib._bootstrap>:241: DeprecationWarning: builtin type swigvarlink has no __module__ attribute
/private/tmp/sitk311/lib/python3.11/site-packages/SimpleITK/extra.py:466: DeprecationWarning: invalid escape sequence '\s'
  """Blurs an image by separable convolution with discrete
```

### Python 3.12

```bash
uv venv --python 3.12 sitk312
source sitk312/bin/activate
uv pip install SimpleITK
python -c "import SimpleITK"
```

Output:

```python-traceback
/private/tmp/sitk312/lib/python3.12/site-packages/SimpleITK/extra.py:466: SyntaxWarning: invalid escape sequence '\s'
  """Blurs an image by separable convolution with discrete
```

**Comment by fepegar** [comment]
I've opened a PR:
- https://github.com/SimpleITK/SimpleITK/pull/2190

**Comment by dave3d** [comment]
But that "\sa" tag is for the Doxygen document generation.

**Comment by fepegar** [comment]
Hi, @dave3d.

> But that "\sa" tag is for the Doxygen document generation.

If that is the case, wouldn't it have to be in many other places in that Python file? I found only that unique instance.
It seems the Doxygen references work with or without that tag. Similar doc from the same file:

https://github.com/SimpleITK/SimpleITK/blob/df1d8445de88392ab9df549a0791bf72dcc3e157/Wrapping/Python/SimpleITK/extra.py#L38

**Comment by blowekamp** [comment]
The Doxygen syntax need to be removed from the extra.py file. Care to make a pull request?

**Comment by fepegar** [comment]
Thanks, @blowekamp. I have: https://github.com/SimpleITK/SimpleITK/issues/2189#issuecomment-2375251162

**Comment by MattTheCuber** [comment]
This was fixed in September, but the problem is still occurring for me on the latest release from PyPi. Does anyone know why this is?

**Comment by blowekamp** [comment]
What is the output of: `python -Wd -c "import SimpleITK; print(SimpleITK.__version__)"`

**Comment by MattTheCuber** [comment]
```
$ python -Wd -c "import SimpleITK; print(SimpleITK.__version__)"

<frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute
<frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute
<frozen importlib._bootstrap>:488: DeprecationWarning: builtin type swigvarlink has no __module__ attribute
2.4.1
```

**Comment by MattTheCuber** [comment]
Not sure why that warning didn't print this time. But the line is there:

```
$ python -c "import SimpleITK; print(SimpleITK.__version__); from SimpleITK.extra import DiscreteGaussian; print(DiscreteGaussian.__doc__)"
2.4.1
Blurs an image by separable convolution with discrete
 gaussian kernels. This filter performs Gaussian blurring by
 separable convolution of an image and a discrete Gaussian
 operator (kernel).

 This function directly calls the execute method of DiscreteGaussianImageFilter
 in order to support a procedural API.

Also See
--------
  \sa itk::simple::DiscreteGaussianImageFilter for the object oriented interface

```

**Comment by fepegar** [comment]
According to #2190, the fix is for SimpleITK >= [2.5.0b1](https://github.com/SimpleITK/SimpleITK/releases/tag/v2.5.0b1). That's why you're seeing it on v2.4.0.

![Image](https://github.com/user-attachments/assets/f8460756-1e03-4de8-af83-4f26aba5bbf1)

**Comment by MattTheCuber** [comment]
I see, so 2.5.0 will have the fix. Thanks for explaining!

**Comment by blowekamp** [comment]
@MattTheCuber 2.5.0 in published on PyPI, and on the Github releases. Please confirm that it has addressed your issue.

**Comment by MattTheCuber** [comment]
That seems to work. Thanks!
