### ISSUE TITLE
Data Corruption in Large Multi-Component Images

### ISSUE THREAD

**Issue by bertramRISC** [SimpleITK/SimpleITK#2220]
Hi, I noticed a bug affecting large multi-component images (e.g., 400x400x400 with 100 components). Specifically, the methods SimpleITK::Compose and SimpleITK::DICOMOrient produce corrupted images when processing large datasets.

1. Operating system, version, and architecture
 - OS: Windows 11, 24H2
 - Architecture: x64,  Intel(R) Core(TM) i7-13700F
 - 128 GB RAM
2. Programming language, and version: **Python 3.11.10**
3. Version of SimpleITK: **2.4.0**
4. How was SimpleITK installed?
 **- python -m pip install SimpleITK**
5. A minimal working example which causes the error.

This snippet reproduces the bug by creating an image with dimensions (size, size, size) and 100 components using sitk.Compose(...).
The test data consists of a list of SimpleITK images, one for each component, where slices along the last dimension (corresponding to the first dimension in NumPy) are filled at different positions for each component. The images are then written to an NRRD file, which is visualized using 3D-Slicer. In 3D-Slicer, the file is loaded as a segmentation image and viewed in the coronal slicing mode.

```
import SimpleITK as sitk
import numpy as np

size = 400
images = list()
for i in range(100):
    data = np.zeros((size, size, size), dtype=np.uint8)
    data[i:i+1, :, :] = 1
    images.append(sitk.GetImageFromArray(data))

img = sitk.Compose(images)
sitk.WriteImage(img, 'test.nrrd', True)
```

**Expected behavior**

The expected result is an image with 100 alternating labeled slices. However, when a size of 400 is used, gaps appear due to data corruption. This is not the case for a smaller size of e.g., 100.

Result using a size of 400 (first 100 slices): corrupted labels.
<img width="300" alt="size100" src="https://github.com/user-attachments/assets/69fb6d60-c931-42f0-ac76-50b1a1f99c73" />

Result using a size of 100: correct behaviour.
<img width="200" alt="size100" src="https://github.com/user-attachments/assets/c40e28d7-ad2a-4f3a-b04c-2b219612413e" />

**Additional context**
Beyond this artificial example, I observed this behavior when working with large multi-object segmentations, specifically the TotalSegmentator dataset. I encountered the issue while attempting to combine all 104 segmentation images into a single multi-component image for faster processing.

The issue occurs not only when composing multi-component images with SimpleITK::Compose but also when processing a loaded image using SimpleITK::DICOMOrient.

**Comment by zivy** [comment]
Hello @bertramRISC,

I tried to replicate the issue (on OSX) and was unable to, both SimpleITK (2.4.0) results and Slicer (5.6.2) visualization look as expected. Possible issue can be due to `Compose`, `Write` or Slicer behavior.

To check if it is a SimpleITK issue, run the following code that checks the result of `Compose` and `Write`:
```
import SimpleITK as sitk
import numpy as np

size = 400
images = list()
for i in range(100):
    data = np.zeros((size, size, size), dtype=np.uint8)
    data[i:i+1, :, :] = 1
    images.append(sitk.GetImageFromArray(data))

img = sitk.Compose(images)

# check Compose filter behavior
# iterate over the range set above and extract the multi-component z slice
# then extract the relevant component which matches the z slice number and
# check its value
for i in range(100):
  if not (sitk.GetArrayViewFromImage(sitk.VectorIndexSelectionCast(img[...,i], i)) == 1).all():
      print(f"compose filter: problem with component {i}")


sitk.WriteImage(img, 'test.nrrd', True)


# check Write/Read filter behavior
# iterate over the range set above and extract the multi-component z slice
# then extract the relevant component which matches the z slice number and
# check its value
img = sitk.ReadImage('test.nrrd')
for i in range(100):
  if not (sitk.GetArrayViewFromImage(sitk.VectorIndexSelectionCast(img[...,i], i)) == 1).all():
      print(f"write/read: problem with component {i}")
```

Let us know if this works as expected on your side. If yes, then possibly there is an issue with Slicer display.

**Comment by blowekamp** [comment]
I was able to reproduce the issue on windows.

**Comment by bertramRISC** [comment]
> Hello @bertramRISC,
> 
> I tried to replicate the issue (on OSX) and was unable to, both SimpleITK (2.4.0) results and Slicer (5.6.2) visualization look as expected. Possible issue can be due to `Compose`, `Write` or Slicer behavior.
> 
> To check if it is a SimpleITK issue, run the following code that checks the result of `Compose` and `Write`:
> 
> ```
> import SimpleITK as sitk
> import numpy as np
> 
> size = 400
> images = list()
> for i in range(100):
>     data = np.zeros((size, size, size), dtype=np.uint8)
>     data[i:i+1, :, :] = 1
>     images.append(sitk.GetImageFromArray(data))
> 
> img = sitk.Compose(images)
> 
> # check Compose filter behavior
> # iterate over the range set above and extract the multi-component z slice
> # then extract the relevant component which matches the z slice number and
> # check its value
> for i in range(100):
>   if not (sitk.GetArrayViewFromImage(sitk.VectorIndexSelectionCast(img[...,i], i)) == 1).all():
>       print(f"compose filter: problem with component {i}")
> 
> 
> sitk.WriteImage(img, 'test.nrrd', True)
> 
> 
> # check Write/Read filter behavior
> # iterate over the range set above and extract the multi-component z slice
> # then extract the relevant component which matches the z slice number and
> # check its value
> img = sitk.ReadImage('test.nrrd')
> for i in range(100):
>   if not (sitk.GetArrayViewFromImage(sitk.VectorIndexSelectionCast(img[...,i], i)) == 1).all():
>       print(f"write/read: problem with component {i}")
> ```
> 
> Let us know if this works as expected on your side. If yes, then possibly there is an issue with Slicer display.

Thank you for looking into this and getting back to me so quickly! I tried running your code on my system, and in both cases—compose and read/write checks—it produced 100 problem messages, one for each component.

In your example, however, since the data is already corrupted after the Compose check, the Read/Write check will inevitably fail, regardless of how ReadImage or WriteImage function. To investigate further, I modified the second check as follows:

```
# check Write/Read filter behavior
img2 = sitk.ReadImage('test.nrrd')
if not np.array_equal(sitk.GetArrayViewFromImage(img), sitk.GetArrayViewFromImage(img2)):
    print(f"write/read problem ")
```

The Compose check still fails, but the Read/Write problem no longer occurs, indicating that these steps do not further change the data.

**Comment by bertramRISC** [comment]
> I was able to reproduce the issue on windows.

Could this be a Windows-specific issue related to memory fragmentation? This is just speculation, but it occurred to me that the boundary size of 355 (i.e., 100 * 355³ * 1 Byte = 4.17GB) I determined for reproducing the issue is suspiciously close to the 4GB limit on 32-bit systems. I haven’t worked with C++ memory allocation in a while, but I can imagine that Windows, also on my 64-bit system, might behave differently around the 32-bit threshold. This could cause code that relies on contiguous memory blocks to fail.

If this is the case, the affected code could fail more broadly if the memory allocated for images becomes fragmented—an issue that can occur on any OS when RAM is exhausted and large contiguous blocks cannot be allocated.

However, I doubt memory exhaustion was the issue during my tests, as my system has 128 GB of RAM, with around 20% reserved according to Task Manager. If fragmentation is the cause, it may be due to a hardcoded Windows behavior instead.

**Comment by bertramRISC** [comment]
@zivy: I further modified your example to use the ITK python wrapper instead:

```
import itk
import numpy as np

size = 400

from itk import itkImagePython, itkVectorImagePython
ImageType = itkImagePython.itkImageUC3
VectorImageType = itkVectorImagePython.itkVectorImageUC3

compose_filter = itk.ComposeImageFilter[ImageType, VectorImageType].New()
for i in range(100):
    data = np.zeros((size, size, size), dtype=np.uint8)
    data[i:i + 1, :, :] = 1
    # Convert numpy array to ITK image
    itk_image = itk.image_from_array(data)
    compose_filter.SetInput(i, itk_image)

compose_filter.Update()
img = compose_filter.GetOutput()

# check Compose filter behavior
# iterate over the range set above and extract the multi-component z slice
# then extract the relevant component which matches the z slice number and
# check its value
errors = 0
for i in range(100):
    slice_component = itk.VectorIndexSelectionCastImageFilter[VectorImageType, ImageType].New()
    slice_component.SetInput(img)
    slice_component.SetIndex(i)
    slice_component.Update()
    array_slice = itk.array_from_image(slice_component.GetOutput())

    if not (array_slice[i, :, :] == 1).all():
        print(f"compose filter: problem with component {i}")
        errors += 1

print(f"Total errors: {errors}")
```

Running the test 10 times, I get a different number of errors, between 19 and 92 (specifically: 55, 74, 41, 37, 49, 56, 19, 45, 65, 92). 

The problem seems to extend to the wrapped ITK functions.

**Comment by bertramRISC** [comment]
I found it curious that with ITK, the number of errors varies, while it fails for all components with SimpleITK. This seems to stem from the use of `sitk.GetArrayViewFromImage(sitk.VectorIndexSelectionCast(img[..., i], i))`.

Upon debugging, I found that:

`np.unique(sitk.GetArrayViewFromImage(sitk.VectorIndexSelectionCast(img[..., 0], 0))) `

produced [0, 1, 12, 15, 68, 80, 170, 183, 234, 240]

while 

`np.unique(sitk.GetArrayFromImage(sitk.VectorIndexSelectionCast(img, 0))[0, ...]) `

produced [1].

By adapting the second line in the check, I was able to reproduce the varying number of errors observed with the ITK wrapper.
In my opinion, both lines should yield the same result, which suggests the problem extends to the indexing/slicing of SimpleITK images.

Adapted check:

```
errors = 0
for i in range(100):
  if not (sitk.GetArrayFromImage(sitk.VectorIndexSelectionCast(img, i))[i, ...] == 1).all():
      print(f"compose filter: problem with component {i}")
      errors += 1

print(f"Total errors: {errors}")
```

**Comment by blowekamp** [comment]
I have create some test for this issue here: #2221 

My next step is to create a C++ ITK test which SImpleITK or python.

**Comment by blowekamp** [comment]
> I found it curious that with ITK, the number of errors varies, while it fails for all components with SimpleITK. This seems to stem from the use of `sitk.GetArrayViewFromImage(sitk.VectorIndexSelectionCast(img[..., i], i))`.
> 
> Upon debugging, I found that:
> 
> `np.unique(sitk.GetArrayViewFromImage(sitk.VectorIndexSelectionCast(img[..., 0], 0))) `

Yes, this is a good observation. Using `GetArrayViewFromImage` on a temporary or stack image, causes  access to a release buffer.

**Comment by blowekamp** [comment]
A patch has been submitted upstream which should address the issue.
