### ISSUE TITLE
Installation error at CMake/sitkSourceVersion.cmake:38 (include): include could not find load file

### ISSUE THREAD

**Issue by kaspermarstal** [SimpleITK/SimpleITK#228]
When a user is downloading the zip file from Github, and not via `git clone`, the following error occurs because the .git directory is missing:

     Installation error at CMake/sitkSourceVersion.cmake:38 (include): include could not find load file

The issue continuous to resurface as has briefly been discussed in SuperElastix/SimpleElastix#105. Can we provide a solution to this problem?

**Comment by blowekamp** [comment]
So the versioning of SimpleITK was designed to inspect the git repository, or fall back to a generated `sitkSourceVersions.cmake` file from packaged bundled by the "Utilities/Maintenance/SourceTarball.bash" script. The problem only occurs with the zips or tar balls generated by Github or another naive archiving.

This use case should still produce a warning that a proper full version can not be obtained.

We'll need to find some values for the version information that will compare as less than any version with the proper information, and clearly marks the version as unknown.

https://github.com/SimpleITK/SimpleITK/blob/d2fdbdde0cbb494c8033e55e7c729282736dc6bc/CMake/sitkSourceVersion.cmake#L34-L40

**Comment by blowekamp** [comment]
This should be resolved by the following topic:
https://github.com/SimpleITK/SimpleITK/compare/fef8296367c2c522f94cc17f203e0721a8713abc%5E%5E...fef8296367c2c522f94cc17f203e0721a8713abc
