### ISSUE TITLE
A question about images with components

### ISSUE THREAD

**Issue by chsasank** [SimpleITK/SimpleITK#239]
Hi,

I hope this is the right place to ask questions/support about usage of library.

I have three single channel images `img_r, img_g, img_b`. 
I want to make an image `img_rgb` with three components using above three images. 
I have searched in the documentation and googled but couldn't find a way to do this.
Can you please help me.

Thanks,
Sasank.

**Comment by blowekamp** [comment]
I believe you are looking for the `ComposeImageFilter`: https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ComposeImageFilter.html

Keep in mind the all the inputs must be the same type, and occupy the same physical space.

And its inverse would be the `VectorIndexSelectionCastImageFilter`. ( yes, that is a long name, and yes it would be nice to have this feature in operator[]):

https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1VectorIndexSelectionCastImageFilter.html

**Comment by chsasank** [comment]
Thanks!
