### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by TheChymera** [SimpleITK/SimpleITK#246]
I am looking to package your software for Gentoo - I have queried the source code for dependencies, but I could only find numpy explicitly mentioned. Do you perhaps have a lit of required dependencies? I assume ITK itself is required for the package to do useful things?

**Comment by blowekamp** [comment]
That would be wonderful to have SimpleITK packaged for Gentoo!

You may be interested in issue #92 for an on going discussion for Debian packaging. There are several patches on the release branch and are needed. We are about to make a 1.0.1 on the release branch which will contain these fixes.

I'm updating the documentation to for this questions.

**Comment by TheChymera** [comment]
If you could add a file listing the dependencies as well as their minimum required versions (if you are aware of such - for most packages I assume you don't know, which is fine, but e.g. for ITK you seem to be aware of a specific version requirement).

**Comment by blowekamp** [comment]
Please see #247, for where I am documenting this.

SimpleITK has a very flexible build system, and support a large number of languages. For most users who just want to build SimpleITK the super build, which provides the dependencies works very easily. The versions used for this dependencies are in the Superbuild directory. In the "External_*.cmake" files.

**Comment by TheChymera** [comment]
Thank you :) 
Gentoo tries to avoid bundled dependencies, so ideally I am looking to specify them explicitly for the package manager (which manages them based on the package graph of each user).

**Comment by blowekamp** [comment]
The building documentation has been updated with this specific issue.
I am closing the topic, but feel free to ask more questions, open a new topic or suggest improvements.
