### ISSUE TITLE
Error while executing b-spline registration

### ISSUE THREAD

**Issue by subhajitchatu** [SimpleITK/SimpleITK#254]
Hi,

I was using some registration methods like bspline, demons etc. Suddenly I have encountered the below problem while going to execute b-spline registration for two 3D images of sizes (256*256*60) and after executing some iterations , it printed the error on terminal, the code terminated. What could be the possible reason and how I can correct the issue?

**CODE**
`def bspline_registration_multires(fixed, moving):`
   
    registration_method = sitk.ImageRegistrationMethod()

    # Determine the number of BSpline control points using the physical spacing we want for the control grid. 
    grid_physical_spacing = [70.0, 70.0, 70.0] # A control point every 50mm
    image_physical_size = [size*spacing for size,spacing in zip(fixed.GetSize(), fixed.GetSpacing())]
    mesh_size = [int(image_size/grid_spacing + 0.5) \
                 for image_size,grid_spacing in zip(image_physical_size,grid_physical_spacing)]

    initial_transform = sitk.BSplineTransformInitializer(image1 = fixed,
                                                         transformDomainMeshSize = mesh_size, order=3)
    registration_method.SetInitialTransform(initial_transform)

    registration_method.SetMetricAsMattesMutualInformation(50);
    #registration_method.SetMetricAsANTSNeighborhoodCorrelation(4);
    #registration_method.SetMetricAsJointHistogramMutualInformation();
    # Settings for metric sampling, usage of a mask is optional. When given a mask the sample points will be 
    # generated inside that region. Also, this implicitly speeds things up as the mask is smaller than the
    # whole image.

    #registration_method.SetMetricSamplingStrategy(registration_method.RANDOM)
    #registration_method.SetMetricSamplingPercentage(0.01)

    # Multi-resolution framework.            
    registration_method.SetShrinkFactorsPerLevel(shrinkFactors = [4,2,1])
    registration_method.SetSmoothingSigmasPerLevel(smoothingSigmas=[2,1,0])
    registration_method.SmoothingSigmasAreSpecifiedInPhysicalUnitsOn()

    registration_method.SetInterpolator(sitk.sitkLinear)
    registration_method.SetOptimizerAsLBFGSB(gradientConvergenceTolerance=1e-5, numberOfIterations=200)
    registration_method.AddCommand( sitk.sitkIterationEvent, lambda: command_iteration_bspline2(registration_method) )
    registration_method.AddCommand( sitk.sitkMultiResolutionIterationEvent, lambda: command_multi_iteration_bspline2(registration_method) )

    outTx = registration_method.Execute(fixed, moving)`

**Error**
 `File "ImageGen.py", line 576, in bspline_registration_multires
    outTx = registration_method.Execute(fixed, moving)
File "/usr/local/lib/python2.7/dist-packages/SimpleITK/SimpleITK.py", line 11064, in Execute
    return _SimpleITK.ImageRegistrationMethod_Execute(self, fixed, moving)
RuntimeError: Exception thrown in SimpleITK ImageRegistrationMethod_Execute: /home/subha/build/ITK/Modules/Core/Common/src/itkMultiThreader.cxx:416:
itk::ERROR: MultiThreader(0x4cf8d60): Exception occurred during SingleMethodExecute`

Thanks

Regards
Subhajit

**Comment by blowekamp** [comment]
What are your command callbacks defined as?  If you remove those AddCommand calls does the error still happen?

**Comment by subhajitchatu** [comment]
Callbacks are there to print the iteration number and metric value for each step. Meanwhile when I commented that out and surprisingly that error is not coming, but don't know why the function is taking so long time(~20min for 256*256*60 size image) even with only 3 iterations. Anyway I could not find out the reason of the issue while I was trying to print. Is it a threading related issue?

**Comment by blowekamp** [comment]
Could you please provide the code for your call backs? You may be doing something that violates the threading model or there could be a bug in the interface.

I am not familiar with your registration to know the reason for the performance profile. You need to evaluate the optimization paths, and determine where it is taking so long, then determine if it's necessary or what can be done to improve it.

**Comment by subhajitchatu** [comment]
Callbacks are:


 `def command_iteration_bspline2(method) :`
    `print("{0:3} = {1:10.5f}".format(method.GetOptimizerIteration(),
                                     method.GetMetricValue()))`
    `print("\t#: ", len(method.GetOptimizerPosition()))`


 `def command_multi_iteration_bspline2(method) :`
       `print("--------- Resolution Changing ---------")`

Thanks

**Comment by blowekamp** [comment]
This may be related to the exception handing from the python code into the C++ code.

Could you add a try/except inside you function definitions:
```
try:
  ...
catch Exception as e:
   print e.message
except:
  print "Unknown exception"
```

**Comment by blowekamp** [comment]
I presume the issue has been addressed. Please feel free to reopen if additional information is required.

**Comment by subhajitchatu** [comment]
Sorry for reopening the issue. I have commented out AddCommand functions, it worked that time but this time it came again with the same code discussed above. Error messages are shown below.

   ` outTx = bspline_registration_multires(fixed,moving)
  File "ImageRegistrationMethod1.py", line 574, in bspline_registration_multires
    outTx = registration_method.Execute(sitk.Cast(fixed, sitk.sitkFloat32),sitk.Cast(moving, sitk.sitkFloat32))
  File "/usr/local/lib/python2.7/dist-packages/SimpleITK/SimpleITK.py", line 11064, in Execute
    return _SimpleITK.ImageRegistrationMethod_Execute(self, fixed, moving)

RuntimeError: Exception thrown in SimpleITK ImageRegistrationMethod_Execute: /home/subha/build/ITK/Modules/Core/Common/src/itkMultiThreader.cxx:420:
itk::ERROR: MultiThreader(0x498d1d0): Exception occurred during SingleMethodExecute
std::bad_alloc`
