### ISSUE TITLE
Python wrapping for FixedPointInverseDisplacementFieldImageFilter

### ISSUE THREAD

**Issue by rcarthigesan** [SimpleITK/SimpleITK#255]

**Comment by blowekamp** [comment]
The filter you are requesting is already wrapped.

Currently there are two filters to invert displacement fields in SimpleITK:
 * [InvertDisplacementFieldImageFilter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1InvertDisplacementFieldImageFilter.html)
  * [InverseDisplacementFieldImageFilter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1InverseDisplacementFieldImageFilter.html)

There are two additional filters in ITK which can invert displacement fields:
 * [IterativeInverseDisplacementFieldImageFilter](https://itk.org/Doxygen/html/classitk_1_1IterativeInverseDisplacementFieldImageFilter.html)
 * Remote module: [FixedPointInverseDisplacementFieldImageFilter](https://itk.org/Doxygen/html/classitk_1_1FixedPointInverseDisplacementFieldImageFilter.html)

**Comment by ramanacarthigesan** [comment]
Sorry, I meant to write "FixedPointInverseDisplacementFieldImageFilter", which is not yet wrapped.

Apologies for the confusion. Will adjust the title accordingly.

**Comment by blowekamp** [comment]
Please see pull request #257. To use the filter you will need to compile SimpleITK yourself from the Superbuild with the added CMake option `-DModule_FixedPointInverseDisplacementField=ON`.

**Comment by rcarthigesan** [comment]
Hi,

I just tried doing this. After building was complete, the FixedPointInverseDisplacementFieldImageFilter module wasn't included in the Python wrapping.

However, it _was_ included in the ITK build - when I look at the SimpleITK-build/ITK-build/Modules/Remote/ directory, there is a folder named FixedPointInverseDisplacementFieldImageFilter.

Not sure why this is happening?

For reference, this is the code I used for building:

`SimpleITK-build ramana$ cmake -DCMAKE_CXX_COMPILER:STRING=/usr/bin/clang++ -DCMAKE_C_COMPILER:STRING=/usr/bin/clang -DModule_FixedPointInverseDisplacementField=ON PYTHON_EXECUTABLE=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python PYTHON_INCLUDE_DIR=/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 PYTHON_LIBRARY=/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib WRAP_TCL=OFF WRAP_JAVA=OFF WRAP_RUBY=OFF WRAP_R=OFF WRAP_CSHARP=OFF WRAP_LUA=OFF WRAP_PYTHON=ON ../SimpleITK/SuperBuild/`

**Comment by blowekamp** [comment]
That configuration looks correct. Does the "Code/BasicFilters/json/FixedPointInverseDisplacementFieldImageFilter.json" file exist in you SimpleITK source tree? Did you check SimpleITK out from git? What is the git hash you are using?

**Comment by rcarthigesan** [comment]
The "Code/BasicFilters/json/FixedPointInverseDisplacementFieldImageFilter.json" file isn't present.
I used `git clone http://itk.org/SimpleITK.git` to get SimpleITK. Was this incorrect?

**Comment by blowekamp** [comment]
I apologize for not being clearer with the state of the GitHub workflow. I have a pull request ( #257 ) in this repository for this feature, it has not been merged into the master or next branch yet; It is only proposed.

Here are the instructions for checking out the patch, located at the bottom of the pull request:
```
git checkout -b blowekamp-AddFixedPointInverseDisplacementFieldImageFilter master
git pull https://github.com/blowekamp/SimpleITK.git AddFixedPointInverseDisplacementFieldImageFilter
```
HTH

**Comment by rcarthigesan** [comment]
Sorry, as you can tell I'm very new to this and I'm not quite clear.
Will these steps build correctly?

1. `git clone https://github.com/blowekamp/SimpleITK.git AddFixedPointInverseDisplacementFieldImageFilter`

2. Then use the cmake code as I wrote above, but with `../SimpleITK/SuperBuild/` replaced by `../AddFixedPointInverseDisplacementFieldImageFilter/SuperBuild/`

**Comment by blowekamp** [comment]
Lets start over ( this will take longer to compile, but be clean):

```
git clone http://itk.org/SimpleITK.git
cd SimpleITK
git fetch  https://github.com/blowekamp/SimpleITK.git AddFixedPointInverseDisplacementFieldImageFilter
git checkout FETCH_HEAD -b AddFixedPointInverseDisplacementFieldImageFilter
```

You should not need to specify the compiler to CMake. You may want to look at [this FAQ entry](https://simpleitk.readthedocs.io/en/master/Documentation/docs/source/faq.html#why-does-the-superbuild-fail-compiling-pcre-on-mac-os-x).

Then you will need to compile, with something like:
```
mkdir bld
cd bld
cmake -DModule_FixedPointInverseDisplacementField=ON PYTHON_EXECUTABLE=/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python PYTHON_INCLUDE_DIR=/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 PYTHON_LIBRARY=/System/Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib WRAP_DEFAULT=OFF  WRAP_PYTHON=ON ../SuperBuild/
make -j
```

**Comment by rcarthigesan** [comment]
Thank you very much, will give this a try.

**Comment by blowekamp** [comment]
Thank you for your questions. If your problem is not resolved you are welcome to reopen the issue.
