### ISSUE TITLE
Explicitly enable C++11 support

### ISSUE THREAD

**Issue by msmolens** [SimpleITK/SimpleITK#260]
On Linux, I configure ITK 4.12 to build with C++11 by setting the following CMake options:
```
-DCMAKE_CXX_STANDARD:STRING=11
-DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON
-DCMAKE_CXX_EXTENSIONS:BOOL=OFF
```
I configure the SimpleITK SuperBuild with those same options and  set `ITK_DIR` to the ITK build. However, this doesn't enable C++11, and the SimpleITK build fails:

Configure step:
```
-- Performing Test CXX_HAS_stdcxx11
-- Performing Test CXX_HAS_stdcxx11 - Success
-- Checking if c++11 is required...
-- Checking if c++11 is required... NO
```
Build step error, for example:
```
.../SimpleITK/Code/Explicit/src/sitkExplicitITKDefaultVectorPixelAccessor.cxx:19:
.../ITK-build/Modules/Core/Common/itkConfigure.h:59:6: warning: #warning "WARNING:  The current project is configured to use a C++ standard version older than the C++ standard used for this build of ITK" [-Wcpp]
     #warning "WARNING:  The current project is configured to use a C++ standard version older than the C++ standard used for this build of ITK"
      ^
```

How can I explicitly enable C++11 for the SimpleITK SuperBuild?

**Comment by blowekamp** [comment]
I have always just added the proper flag to CMAKE_CXX_FLAGS, i.e. `-DCMAKE_CXX_FLAGS:STRING=-std=c++11`. The CMake variable you set were not propagate from the super build to the sub-projects.

I have a proposed patch #261, that I have not tested but should work for this case. I need to verify some behavior and compatibilities with CMake versions and interactions with CXX_FLAGS.

**Comment by jcfr** [comment]
@blowekamp  Thanks for fixing the issue and integrating into master. I am doing a test build with Slicer and will keep you posted.

**Comment by blowekamp** [comment]
It is recommended to still use `-DCMAKE_CXX_FLAGS:STRING=-std=c++11` due to [CMP0067](CMP0067), unless CMake>3.8.2. 

Please take note of the following:
https://github.com/SimpleITK/SimpleITK/blob/next/CMake/sitkCheckCXX11.cmake#L21-L29

There are several different ways to specify and detect C++11 ( or greater ) features with CMake. It is not clear to me what the best practices are for different versions of CMake compatibility. If you have any recommendations or suggestions for improvements they are welcomed.

**Comment by jcfr** [comment]
Considering that policy `CMP0067` was added in recent CMake version, your approach makes sense.

Based on this, in Slicer, we expect CMake >= 3.8.2 when enabling C++11

https://github.com/Slicer/Slicer/blob/d1739110b572771aa5e6b2804713b3a8c787c605/CMakeLists.txt#L4-L7
