### ISSUE TITLE
MaskNegatedImageFilter crash with unexpected template dispatch error

### ISSUE THREAD

**Issue by dpshamonin** [SimpleITK/SimpleITK#263]
Hi Developers,
I've run into strange crash with MaskNegatedImageFilter. The error message is:

Traceback (most recent call last):
File "W:/work/Tests/MaskNegatedImageFilter/test.py", line 43, in <module>
main()
File "W:/work/Tests/MaskNegatedImageFilter/test.py", line 35, in main
distance_inside = distance_inside_filter.Execute(distance, air)
File "W:\tk\Anaconda3\envs\p35\lib\site-packages\SimpleITK\SimpleITK.py", line 46336, in Execute
return _SimpleITK.MaskNegatedImageFilter_Execute(self, image, maskImage)
RuntimeError: Exception thrown in SimpleITK MaskNegatedImageFilter_Execute: C:\d\VS14-Win64-pkg\SimpleITK\Code\Common\include\sitkProcessObject.h:277:
sitk::ERROR: Unexpected template dispatch error!

```
import SimpleITK as sitk


def main():
    reader = sitk.ImageFileReader()
    reader.SetFileName('hand.mhd')
    itk_image = reader.Execute()

    # get the skin mask
    skin_filter = sitk.BinaryThresholdImageFilter()
    skin = skin_filter.Execute(itk_image, 3.0, 3.0, 1, 0)

    # get the air mask
    air_filter = sitk.BinaryThresholdImageFilter()
    air = air_filter.Execute(itk_image, 0.0, 0.0, 1, 0)

    # construct distance filter
    distance_filter = sitk.SignedMaurerDistanceMapImageFilter()
    distance_filter.SetUseImageSpacing(True)
    distance_filter.SetSquaredDistance(False)
    distance = distance_filter.Execute(skin)

    # mask1 filter
    perform_mask1 = True
    if perform_mask1:
        distance_outside_filter = sitk.MaskImageFilter()
        distance_outside = distance_outside_filter.Execute(distance, air)

        writer1 = sitk.ImageFileWriter()
        writer1.SetFileName('distance_outside.mhd')
        writer1.Execute(distance_outside)

    # mask2 filter
    distance_inside_filter = sitk.MaskNegatedImageFilter()
    distance_inside = distance_inside_filter.Execute(distance, air)

    writer2 = sitk.ImageFileWriter()
    writer2.SetFileName('distance_inside.mhd')
    writer2.Execute(distance_inside)


if __name__ == '__main__':
    main()
```

(Could provide the data 'hand.mhd' on request)

I specially don't understand this crash because the MaskImageFilter works fine.
And to my understanding both of this filters have similar execution logic.
SimpleITK 1.0.1 with Python 3.5, 3.6 on Windows 7 64

Thanks,

**Comment by blowekamp** [comment]
This error message is not helpful and needs to be improved.

The error has to due with the Images' pixels types which are passed to the `MaskedNegatedImageFilter`. The pixel type of the images,`distance` and `air`, are `sitkFloat32` and `sitkUInt8` respectfully. The `MaskedNegatedImageFilter` expects the inputs to be the same pixel.

On the other hand, the `MaskImageFilter` is a robust filter which supports the input images being of different pixel types, which is why the call to this filter works. The `MaskedNegatedImageFilter` expects that the inputs are the same type.

I would recommend just using the Python logical not operator, `!`, on the mask image and use the `MaskedImageFilter` again.

**Comment by dpshamonin** [comment]
Thanks Bradley, 
I was suspecting types mismatch, but indeed was confused by the error message.

**Comment by dpshamonin** [comment]
Issue resolved by using sitk.Cast()
Closed.
```
import SimpleITK as sitk


def main():
    reader = sitk.ImageFileReader()
    reader.SetFileName('hand.mhd')
    itk_image = reader.Execute()

    # get the skin mask
    skin_filter = sitk.BinaryThresholdImageFilter()
    skin = skin_filter.Execute(itk_image, 3.0, 3.0, 1, 0)

    # get the air mask
    air_filter = sitk.BinaryThresholdImageFilter()
    air = air_filter.Execute(itk_image, 0.0, 0.0, 1, 0)

    # construct distance filter
    distance_filter = sitk.SignedMaurerDistanceMapImageFilter()
    distance_filter.SetUseImageSpacing(True)
    distance_filter.SetSquaredDistance(False)
    distance = distance_filter.Execute(skin)

    # convert to float
    air_float = sitk.Cast(air, distance.GetPixelID())

    # mask1 filter
    distance_outside_filter = sitk.MaskImageFilter()
    distance_outside = distance_outside_filter.Execute(distance, air)

    writer1 = sitk.ImageFileWriter()
    writer1.SetFileName('distance_outside.mhd')
    writer1.Execute(distance_outside)

    # mask2 filter
    distance_inside_filter = sitk.MaskNegatedImageFilter()
    distance_inside = distance_inside_filter.Execute(distance, air_float)

    writer2 = sitk.ImageFileWriter()
    writer2.SetFileName('distance_inside.mhd')
    writer2.Execute(distance_inside)

    # define final dtf
    dtf = -1.0 * distance_outside + distance_inside

    writer3 = sitk.ImageFileWriter()
    writer3.SetFileName('dtf.mhd')
    writer3.Execute(combine)


if __name__ == '__main__':
    main()
```
