### ISSUE TITLE
[Help Wanted] SimpleITK 1.x Java libs for mac 

### ISSUE THREAD

**Issue by mickaeltardy** [SimpleITK/SimpleITK#268]
Currently only Windows Java libs are available for download for the latest 1.0.1 on http://www.simpleitk.org/SimpleITK/resources/software.html. The last mac lib was provided for the 0.9.1 in 2015. Is there any technical reason for mac libs not being generated anymore? 

I've just built the 1.1.0.dev2774 and building it by my own was ok-ish, but I'm wondering if there might be any issues afterwards. Any ideas?

**Comment by dave3d** [comment]
Yeah, that's probably an oversight.  I just built and tested the latest version on Mac/Java and it was fine.  I'll let @blowekamp know when he gets back from vacation next week.

**Comment by blowekamp** [comment]
I believe the proper way for packaging for Java would be to target Maven. We are in need of a packager who can help with packaging for Maven to ensure compatibility with their conventions.
