### ISSUE TITLE
Fix warning: 'self' is a python keyword, renaming to '_self'

### ISSUE THREAD

**Issue by jcfr** [SimpleITK/SimpleITK#277]
```
/Users/kitware/Dashboards/Nightly/Slicer-0-build/SimpleITK/Code/Common/include/sitkCommand.h:50: Warning 314: 'self' is a python keyword, renaming to '_self'
/Users/kitware/Dashboards/Nightly/Slicer-0-build/SimpleITK/Code/Common/include/sitkCommand.h:50: Warning 314: 'self' is a python keyword, renaming to '_self'
/Users/kitware/Dashboards/Nightly/Slicer-0-build/SimpleITK/Code/Common/include/sitkCommand.h:46: Warning 314: 'self' is a python keyword, renaming to '_self'
```

**Comment by blowekamp** [comment]
This has been a long standing warning,that we have suppressed on the SimpleITK Dashboard. I'll update this issue why the current information about the status of the warning.

**Comment by jcfr** [comment]
Sounds good. Thanks for the feedback.

I will also add a suppression. For future reference, 

https://github.com/SimpleITK/SimpleITK/blob/1fe5059bcbf7c845343fc56ca618d0d3c416b117/CMake/CTestCustom.cmake.in#L67-L68

**Comment by blowekamp** [comment]
This appears to be a SWIG issue related to the `director` feature. By removing the following line the warning goes away:
https://github.com/SimpleITK/SimpleITK/blob/67834089d070484004cfca195dc4e580fabd4418/Wrapping/Python/Python.i#L791
However, that feature is needed to enable users to derived from the sitk::Command class.

There is no 'self' in the C++ code that could produce this warning, so it assumed that it's likely an internal SWIG issue. As this warning appear not to effect the produced code, and there is no know solution to stop that warning for this case, I am closing this issue as not going to fix, and affirming the recommendation to suppress it.
