### ISSUE TITLE
Compilation problem for MingGW 

### ISSUE THREAD

**Issue by u0078867** [SimpleITK/SimpleITK#28]
Hi,

first of all, thanks for the big effor of bringing this library to life, it's amazing!
I am trying to compilethe current master branch of SimpleITK (because I really need urgently the registration part fro Python), but I get the following error during ITK compilation with MingGW 4.6.2:

[ 93%] Building CXX object Modules/IO/TIFF/src/CMakeFiles/ITKIOTIFF.dir/itkTIFFI
mageIO.cxx.obj
c:/SimpleITK/SimpleITK-build-gcc/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx:1:0:
 warning: -fPIC ignored for target (all code is position independent) [enabled b
y default]
c:/SimpleITK/SimpleITK-build-gcc/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx: In
member function 'int itk::TIFFReaderInternal::Open(const char_)':
c:/SimpleITK/SimpleITK-build-gcc/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx:74:2
0: error: aggregate 'itk::TIFFReaderInternal::Open(const char_)::_stat64 fs64' h
as incomplete type and cannot be defined
c:/SimpleITK/SimpleITK-build-gcc/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx:75:3
3: error: invalid use of incomplete type 'struct itk::TIFFReaderInternal::Open(c
onst char_)::_stat64'
c:/SimpleITK/SimpleITK-build-gcc/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx:74:1
2: error: forward declaration of 'struct itk::TIFFReaderInternal::Open(const cha
r_)::_stat64'
make[5]: **\* [Modules/IO/TIFF/src/CMakeFiles/ITKIOTIFF.dir/itkTIFFImageIO.cxx.ob
j] Error 1
make[4]: **\* [Modules/IO/TIFF/src/CMakeFiles/ITKIOTIFF.dir/all] Error 2
make[3]: **\* [all] Error 2
make[2]: **\* [ITK-prefix/src/ITK-stamp/ITK-build] Error 2
make[1]: **\* [CMakeFiles/ITK.dir/all] Error 2
make: **\* [all] Error 2

I am using the procedure described here for ITK: http://www.itk.org/Wiki/ITK/Configuring_and_Building/MinGW

My OS is : Windows 7 64-bit.
With VS 2012 Express, it works like a charm.

Am I using a too old compiler?

Thanks

Davide

**Comment by blowekamp** [comment]
Out of date. A new ticket with the current issue with MinGW is needed.
