### ISSUE TITLE
i can't read image use simpleitk

### ISSUE THREAD

**Issue by unyqhz** [SimpleITK/SimpleITK#285]
I am new to simpleitk,and I find that I can't use the attribute"ReadImage".So I can't read image use simpleitk,I looked into your tutorial and googled it,but still don't know why.And I reinstalled it three times.Please help me.Thank you

**Comment by unyqhz** [comment]
![Uploadi

ng 1.JPG…]()

**Comment by unyqhz** [comment]
the error is like this ":AttributeError: module 'SimpleITK' has no attribute 'ReadImage'"

**Comment by blowekamp** [comment]
Please specify the package file you are using and where you got it from. Along with a complete snippet of code to reproduce your problem.

**Comment by unyqhz** [comment]
i used pip install SimpleItk and pip install "C:\Users\pyn\Downloads\SimpleITK-1.0.1-cp35-cp35m-win_amd64.whl",nothing changed.
the code is simple,i just want to read some .mhd files
following is my code:
for i in range(df_nodule.shape[0]):
    img_file = files_path + df_nodule.loc[i,'seriesuid'] + '.mhd' #imgfile
    if os.path.exists(img_file):
        print("Sample the %s.mhd" % df_nodule.loc[i,'seriesuid'])
        nodule_x = df_nodule.loc[i, 'coordX']
        nodule_y = df_nodule.loc[i, 'coordY']
        nodule_z = df_nodule.loc[i, 'coordZ']
        full_image_info = sitk.ReadImage(img_file)
        full_scan = sitk.GetArrayFromImage(full_image_info)  

the error is  this ":AttributeError: module 'SimpleITK' has no attribute 'ReadImage'"

**Comment by blowekamp** [comment]
I am unable to reproduce your problem. What Python distribution and version are you using? Where did you obtain it? Where did you obtain your SimpleITK? Have your tried to compile SimpleITK your self? Do have other Python versions or distributions installed? Are you using virtualenv? Have you tried reinstalling in a clean virtual environment? There is something conflicting in you environment causing problems.

**Comment by blowekamp** [comment]
Hello, Do you have any additional information about your problem? Have you found a solution or work around?

**Comment by unyqhz** [comment]
sorry,I haven't find any solution and everything seems fine,so I am still confused 


发件人：Bradley Lowekamp <notifications@github.com>
发送时间：2017-09-14 03:07
主题：Re: [SimpleITK/SimpleITK] i can't read image use simpleitk (#285)
收件人："SimpleITK/SimpleITK"<SimpleITK@noreply.github.com>
抄送："unyqhz"<panyini1994@pku.edu.cn>,"Author"<author@noreply.github.com>

Hello, Do you have any additional information about your problem? Have you found a solution or work around?

**Comment by zivy** [comment]
@unyqhz 

My advice is to start from the beginning, as it is unclear what is causing the issue you have:

From the command line, create a new virtual environment in the current directory:

```
virtualenv sitkpy --no-site-packages 
```

Activate it (you appear to be on windows):
```
sitkpy\Scripts\activate 
```

Install SimpleITK:
```
pip install SimpleITK
```

Run Python and check that the installation worked (assuming Python 3.x):

```
import SimpleITK as sitk; print(sitk.Version())
```

If the above printed the expected version then try to read a single file:
```
import SimpleITK as sitk
my_file_name = 'my_input.mhd'
img = sitk.ReadImage(my_file_name)
```

**Comment by unyqhz** [comment]
It can work now,thanks a thousand times!   you are so kind!

**Comment by zivy** [comment]
You're welcome.
