### ISSUE TITLE
Image filters "FastMarchingUpwindGradientImageFilter" and "CollidingFrontsImageFilter" are missing

### ISSUE THREAD

**Issue by espdev** [SimpleITK/SimpleITK#29]
Hello everyone!

I have not found the ITK filters `FastMarchingUpwindGradientImageFilter` and `CollidingFrontsImageFilter` in the package SimpleITK. Are these filters not available in SimpleITK permanently or is it possible to add filters and make my own build in SimpleITK? 

If these filters are currently missing in SimpleITK, it would be great to implement them.

**Comment by blowekamp** [comment]
Hello,

These filter don't look too hard to wrap. Nothing is really "permanent" ITK and SimpleITK are all open source which can be customized :)

This should be just a matter of writing the needed json to describe the filters to the code generation system. I think I can get this done by early next week, however help would be appreciated.

Are you able to compile and build the SimpleITK next/master branch? Perhaps you can help contribute by writing a example for these filters?

Thanks,
Brad

**Comment by espdev** [comment]
Thank you for your quick answer. I would be very glad to help you to implement the support for filters in SimpleITK. However, I need time to understand the generation of filter codes as well as description of filters classes in json format. I will look through the existing descriptions, read documentation, and try to write something in the nearest future.

I can also write the examples of filters usage using the Python language when they are implemented in SimpleITK.

**Comment by blowekamp** [comment]
Adding these two will require modifying the template in addition to the json file. There is a special fast marching template: https://github.com/SimpleITK/SimpleITK/blob/57d648744586e48fe26cf077d65ab6cd8ba0e642/Code/BasicFilters/templates/sitkFastMarchingImageFilterTemplate.h.in it needs to be generalized to take multiple seed points. This would take quite some experience tweaking to get this to work.

**Comment by espdev** [comment]
Filter `FastMarchingUpwindGradientImageFilter` adds new entity `TargetPoints`. Filter `CollidingFrontsImageFilter` adds two new entities: `SeedPoints1` and `SeedPoints2`. 

Does the existing template `FastMarchingImageFilter` suit for them? Maybe, you need some other template(s)?

**Comment by blowekamp** [comment]
The FastMarching template likely should be generalized to handled these multiple seed points in a general way. I'm likely the best one to do that.

**Comment by blowekamp** [comment]
Current work in progress:

https://issues.itk.org/jira/browse/SIMPLEITK-613#comment-26839

https://github.com/blowekamp/SimpleITK/tree/SIMPLEITK-613_AddFastMarchinUpwindGradientAndCollidingFronts

**Comment by espdev** [comment]
> Current work in progress

It's great!

> What is the difference between the FastMarchingUpwindGradientImageFilter and FastMarchingUpwindGradientImageFilterBase?

I didn’t use to FastMarchingUpwindGradientImageFilterBase. In my C++ projects I use ITK filter without **Base**. I need TargetPoints for solution of my problem.

**Comment by blowekamp** [comment]
The ITKv4 of the FastMarching filter provided a modular stopping criteria. So the TargetPoints stopping condition can be used with the base fast marching to the FastMarchingUpwindGradientImageFilterBase. Is the UpwindGradientImage needed?

http://www.itk.org/Doxygen/html/classitk_1_1FastMarchingStoppingCriterionBase.html

**Comment by espdev** [comment]
I think in this case the UpwindGradientImageFilter will be of no use. The FastMarchingUpwindGradientImageFilterBase filter will be enough.

**Comment by blowekamp** [comment]
found minor issue in itk:
http://review.source.kitware.com/#/c/18924/

**Comment by blowekamp** [comment]
Update branch:
https://github.com/blowekamp/SimpleITK/tree/SIMPLEITK-613_AddFastMarchinUpwindGradientAndCollidingFronts

It compiles with the additional patch above. I have not tested it, and I am not even sure what is expected for the outputs.

**Comment by espdev** [comment]
> found minor issue in itk

Oh, I should say I didn't notice this bug because I used the same type of the input and output images...

Thank you! I will try to build your branch (and patch for itk) and check how it works. :)

**Comment by espdev** [comment]
Unfortunately, I cannot build your branch `SIMPLEITK-613_AddFastMarchinUpwindGradientAndCollidingFronts` via SuperBuild. 

I get these errors:
http://pastebin.com/GxxynkfM

I use MS VS2012 and CMake 3.1.0
I try to build `WRAP_PYTHON` only.

**Comment by blowekamp** [comment]
OK, I had forgotten about that bug with VS 2012's std library.... Can you get VS 2010? And build with shared libraries enabled?

**Comment by espdev** [comment]
Thank you. I try to build in VS2010. 

The release build with static has failed (after long-long time):
```
LINK : fatal error LNK1102: out of memory
```
linker.exe process out of maximum memory size for 32-bit.

However, build with shared libraries is succeeded! I will test it soon.

**Comment by blowekamp** [comment]
Great! You will need to manually add the dlls to you path something like:
set( ENV{PATH} "${CTEST_DASHBOARD_ROOT}/SimpleITK-build/bin;${CTEST_DASHBOARD_ROOT}/SimpleITK-build/ITK-prefix/bin;$ENV{PATH}" )

I have made good progress in updating the json for the generated test. The output looks pretty nice, and I under stand how this would be useful.

Writing an example of using this filter would be a great way to contribute.

Thanks!

**Comment by espdev** [comment]
I wrote a simple test. It seems to me that these filters work correctly! :)

My test code:
```python
import SimpleITK as Sitk

def upwind_fast_marching(speed_image):
    fm = Sitk.FastMarchingUpwindGradientImageFilter()
    fm.AddTrialPoint((192, 228, 94))
    return fm.Execute(speed_image)

def colliding_front(speed_image):
    cf = Sitk.CollidingFrontsImageFilter()
    cf.AddSeedPoint1([158, 209, 93])
    cf.AddSeedPoint2([210, 238, 94])
    return cf.Execute(speed_image)

if __name__ == '__main__':
    reader = Sitk.ImageFileReader()
    writer = Sitk.ImageFileWriter()

    reader.SetFileName('speed_image.mha')
    speed_image = reader.Execute()

    levelset_image = upwind_fast_marching(speed_image)

    writer.SetFileName('fast_marching.mha')
    writer.Execute(levelset_image)

    levelset_image = colliding_front(speed_image)

    writer.SetFileName('colliding_fronts.mha')
    writer.Execute(levelset_image)
```

And my test speed image for input:
https://dl.dropboxusercontent.com/u/17400742/speed_image.mha


I may write the examples for filters usage. Where is it possible to read about the contributing, rules and guidelines relating to SimpleITK examples?

Thanks!

**Comment by blowekamp** [comment]
Great! I created a little test in the JSON file for the CollidingFront with an image that was black dots on a white background. I think I get how that filer can be quite useful now.

There is some links to information on contributing and development here:
http://www.itk.org/Wiki/SimpleITK#Development

In short you can use gerrit or a git hub pull request, any contribution will be appreciated. 

Currently this branch has been merged into the next branch along with an ITK update. I still need to fix some of the test for a couple languages but it's not too far off. However, the more I have gotten into the fast marching the more I think the interface needs more tweaking to make the stopping criteria more generic. This may be another topic though.

**Comment by espdev** [comment]
Thank you very much! I will try to contribute. :)

**Comment by blowekamp** [comment]
This topic has been merged into master.
