### ISSUE TITLE
Issues regarding simpleITK operations

### ISSUE THREAD

**Issue by subhajitchatu** [SimpleITK/SimpleITK#293]
Hi,

I have found two issues or rather doubts while using SimpleITK.

1. When after registration, I am going to write the result image into .nii or .dcm file, all the pixel locations are being changed to integer values

  `selx = sitk.SimpleElastix()`
  `sitk.WriteImage(selx.GetResultImage(),"testdce.nii")`

The Input image have voxels like (103.68,141.32,37.50) <x,y,z>. But there is no float values in testdce.nii. I want the pixels to be as it was in the input file. How to achieve this?

2. I have encountered a strange issue while using bspline method:

       `
       `selx = sitk.SimpleElastix()
        selx.SetFixedImage(fixed)
        selx.SetMovingImage(moving)
        parameterMapVector = sitk.VectorOfParameterMap()
        parameterMapVector.append(sitk.GetDefaultParameterMap("rigid"))
        parameterMapVector.append(sitk.GetDefaultParameterMap("affine"))
        parameterMapVector.append(sitk.GetDefaultParameterMap("bspline"))
        selx.SetParameterMap(parameterMapVector)`

Here when I am using bspline, after writing the image into testdce.nii, I have found out that there are some black holes in the image is constructed, there is no sign of these holes in original image.
When I commented out bspline only, it's working appropriately. 

Please look into my doubts and waiting for your suggestion.

**Comment by blowekamp** [comment]
You appear to be using the [SimpleElastix](https://github.com/SuperElastix/SimpleElastix) and not just SimpleITK. Can you demonstrate the issue with SimpleITK alone? Otherwise, you should report the problem to SimpleElastix.

**Comment by blowekamp** [comment]
duplicate SuperElastix/SimpleElastix#127
