### ISSUE TITLE
Inconsistent Java wrappings between Windows and Linux (x86-64)

### ISSUE THREAD

**Issue by kdunee** [SimpleITK/SimpleITK#295]
Swig has issues (https://github.com/swig/swig/issues/646) with generating consistent Java wrappings for integer types on certain 64-bit platforms, e.g:

Windows:
```
public void add(long x) {
     SimpleITKJNI.VectorInt64_add(swigCPtr, this, x);
}
```

Linux:
```
public void add(int x) {
     SimpleITKJNI.VectorInt64_add(swigCPtr, this, x);
}
```

Windows:
```
public java.math.BigInteger getPixelAsUInt64(VectorUInt32 idx) {
     return SimpleITKJNI.Image_getPixelAsUInt64(swigCPtr, this, VectorUInt32.getCPtr(idx), idx);
}
```

Linux:
```
public long getPixelAsUInt64(VectorUInt32 idx) {
     return SimpleITKJNI.Image_getPixelAsUInt64(swigCPtr, this, VectorUInt32.getCPtr(idx), idx);
} 
```

Of which choosing `BigInteger` in one case and `long` in another is the most problematic.

The problems occur across multiple swig versions (tested: 3.0.8, 3.0.9, 3.0.12), different SimpleITK versions (tested: 0.10.0, 1.0) and compilers.

In my case the issue can be fixed by following the instructions in https://github.com/swig/swig/pull/649, using the patched swig and adding:

```
#if defined(SWIGWORDSIZE64)
%apply unsigned int { size_t };
%apply const unsigned int & { const size_t & };
#endif
```

to `Wrapping/Java/Java.i`

---

original conversation: http://itk-users.7.n7.nabble.com/ITK-users-Generating-compatible-Java-wrappings-of-SimpleITK-between-Windows-and-Linux-x86-64-td38694.html

a full diff between windows and linux generated wrappings:
[simpleitk.txt](https://github.com/SimpleITK/SimpleITK/files/1303577/simpleitk.txt)

**Comment by blowekamp** [comment]
Thank you for posting you issue on GitHub. Having the SimpleITK issue and the SWIG issues linked with help with getting the appropriate patches tested, updated, and merged.

**Comment by blowekamp** [comment]
So for the JAVA type used for unsigned 64-bit integers, should this be mapped to Java's `long` for all cases or are there some cases where `BigInteger` should be used?

**Comment by blowekamp** [comment]
Your addition to Java.i, converts 64-bit unsigned integers to 32-bit signed integers. That is a significant reduction in the value of the size type! Wouldn't using C++ "long long" be better to get Java's `long` type?

What do you think of the usage of Java's `BigInteger`? Should that be avoided, and these values be truncated to signed 64-bit `long` integers?

**Comment by kdunee** [comment]
Admittedly, I have no experience with swig, having previously worked manually with JNI, so I borrowed the snippet as-is. Is it mapping `size_t` to `unsigned int`? If that's the case I would indeed be worried.

Lack of unsigned types in Java is unfortunate and leaves no other option for `uint64_t` values (`unsigned long long` on most 32-bit architectures and 64-bit windows, `unsigned long` on 64-bit UNIXes) but to use `BigInteger` - we couldn't trade convenience for half the value range. That's what I was worried about with the wrapping produced on Linux by mainline swig - lots of `uint64_t`s translated to Java `long`s - same size, different range.

**Comment by kdunee** [comment]
Please correct me if I'm wrong, but on x86-64 this would be ideal:

| C++ | Java |
|---|---|
| `short` / `int16_t` | `short` |
| `unsigned short` / `uint16_t` | `int` |
| `int` / `int32_t` | `int` |
| `unsigned int` / `uint32_t` | `long` |
| `long` / `int64_t` | `long` |
| `unsigned long` / `uint64_t` / `unsigned long long` / `size_t` / `void*` | `BigInteger` |

Optionally the pointers could use `long` if their Java value doesn't matter and if they could be copied bitwise instead of by value, but I suppose this already happens (`long swigCPtr`).

**Comment by blowekamp** [comment]
That is close, and correct for 64-bit linux, and OS X. But a significant complication is that for 64-bit windows sizeof(long)==4. Additionally, the sizeof(long) changes on 32-bits vs 64-bit on OSX/linux.

Establishing the expected results, is a very good idea. Along with adding tests to ensure that the SWIG results are as expected is likely the place to start. I think validating the sitk::Image::GetPixelAs methods is where to begin.

**Comment by blowekamp** [comment]
These are underlying tricky issue. The current situation seems to be working OK.
