### ISSUE TITLE
Typo in installation documentation

### ISSUE THREAD

**Issue by sumanthneerumalla** [SimpleITK/SimpleITK#309]
[https://github.com/SimpleITK/SimpleITK/blob/next/Documentation/docs/source/installation.rst#id1](https://github.com/SimpleITK/SimpleITK/blob/next/Documentation/docs/source/installation.rst#id1)

In the text for the python documentation there are two typos:

link: [https://github.com/SimpleITK/SimpleITK/blob/next/Documentation/docs/source/installation.rst#id1](https://github.com/SimpleITK/SimpleITK/blob/next/Documentation/docs/source/installation.rst#python-binary-files)

The words (recommend) reccommend  and (virtual) virual are mispelled.

**Comment by blowekamp** [comment]
Care to make a pull request?

**Comment by sumanthneerumalla** [comment]
Just did it link to pull request [here](https://github.com/SimpleITK/SimpleITK/pull/310)

**Comment by blowekamp** [comment]
closed by #310
