### ISSUE TITLE
4D image support in SimpleITK

### ISSUE THREAD

**Issue by kaspermarstal** [SimpleITK/SimpleITK#31]
Dear Bradley and friends,

I have long been impressed by the goal and execution of development of this library and you guys have my utmost respect. It solves an important but often overlooked problem is this field, namely  making the science-y algorithms user-friendly so the (often not so technical) clinical personnel can actually put them to good use.

I have humbly forked this library to integrate the [elastix registration library](http://elastix.isi.uu.nl/) and ease the learning curve for new elastix users. However, [SimpleElastix](https://github.com/kaspermarstal/SimpleElastix) does not support groupwise registration at the moment because of the lack of support for 4D images in SimpleITK. I recall having read it was a deliberate choice not to support 4D images in order to make the interface as simple as possible. I am less inclined to start hacking away at the robust internal API and would like to know what the prospects are for native 4D support before I start implementing it in SimpleElastix myself?

**Comment by kaspermarstal** [comment]
The long compile time and large binary size is a valid concern and a 4D CMake option is a good solution. I would happy to contribute such a feature upstream. Let me know if you prefer a Github pull request or another type of workflow (create branch from your JIRA etc).

To answer your question, I definitely agree that multichannel images cover most people's needs. In this case however, four spatial dimensions are required because of the implementation of groupwise registration in elastix which unfortunately does not take VectorImages but only one big 4D volume.

**Comment by blowekamp** [comment]
Great to hear that you would like to take up this issue.

We use JIRA( https://issues.itk.org ) to track, schedule, prioritize and assign issue. Along with breaking larger tasks into smaller ones. Most issues become a branch of master of the format SIMPLEITK-###_DESCIPTION, where there are merged into next for testing until complete then merged into master.

Please create JIRA issue(s) to for this tasks and assign them to yourself. We can continue the discussion there. Then doing a pull request on Github with the topic is fine.
