### ISSUE TITLE
Fix Github's default branch for development/checkout.

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#316]
Currently for the official origin: https://itk.org/SimpleITK.git, the default branch is "master". So that when a clone is done the default check is the stable "master" branch.

However, currently the default branch on Github is "next". This has the advantage that by default pull requests specify they are to be merged into the "next" branch. ( Which they will be first merged into "next", for nightly testing, then "master" later ). The downside of the "next" default branch is that new clone, will default to the "next", and many contributors base their branches off of "next".

The setup for development scripts should help is properly configuring a contributors repository for contributing.

**Comment by addisonElliott** [comment]
I'm not sure if this will be any help for you.

But here is a guide from Github explaining how to change the default branch: https://help.github.com/articles/setting-the-default-branch/

Although, I'm not sure if the guide will apply since the repository is **mirrored** to Github.

**Comment by blowekamp** [comment]
Yes, we are aware of how to configure Github's default branch.

This issue was to describe the problem of defaulting to the "next" branch on Github, document the consequences. Then figure out how to clarify the the process with the `SetupForDevelopement` scripts, to ensure ease of contribution.

For those who have been working with itk.org as the origin and ran the `SetupForDevelopment` this would not be a problem. 

Do you have any suggestions for how to improve and description how to get properly setup?

**Comment by addisonElliott** [comment]
Ahh sorry, I misread your original statement. I understand why you want the default branch to be next now.

Maybe the best approach would be to simply document this in the README that the user needs to create their topic branch off of the master branch.

Another step we can take is to automatically checkout the master branch in the `SetupForDevelopment` branch as a starting point for the user. 

Another thought I had was to try and check the parent branch for a commit in the `pre-commit` hook but that sounds like it may be more work that its worth.

**Comment by blowekamp** [comment]
Fixed with using Github as the official upstream and removal of the `next` branch.
