### ISSUE TITLE
 Image compressing while using sitk.WriteImage() 

### ISSUE THREAD

**Issue by subhajitchatu** [SimpleITK/SimpleITK#328]
Hi,

I have encountered a strange problem regarding reading of a .nii image using SimpleITK.

I have 209MB  "read.nii" file, I have just read it using 

`readImg = sitk.ReadImage("read.nii",sitkFloat32)`

and then just write it back using

`sitk.WriteImage(readImg,"output.nii")`

the "output.nii" becomes 103.2 MB

I want to know why is it happening? Is anything I am missing here.

Thanks

**Comment by blowekamp** [comment]
If you read the image without the specifying the outputPixelType what is the pixel type?

```
readImage = sitk.ReadImage("read.nii")
print(readImage.GetPixelIDTypeAsString())
```

**Comment by subhajitchatu** [comment]
I was wrong, this has a 64 bit Float type. So issue has been fixed.
