### ISSUE TITLE
LBFGSB Optimizer acting erratically with upper/lower bound

### ISSUE THREAD

**Issue by Shusil** [SimpleITK/SimpleITK#337]
LBFGSB optimizer exits with erratic output when specifying the upper/lower parameter bounds, whereas it works as expected without bounds. 
It would also be great if the bounds could be set for individual parameters through an array (as in itk https://itk.org/Doxygen/html/classitk_1_1LBFGSBOptimizerv4.html#a140f0840d84ab1b83142f1f906fe7c70) versus providing a single value (in SimpleITK https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ImageRegistrationMethod.html#abbc7ac9efb6de282513e41a8a8d81db7)

Attached is a sample code:

    import SimpleITK as sitk
    import numpy as np
    import matplotlib.pyplot as plt
    %matplotlib inline

    def command_iteration(method):
        print("{0:3} = {1:10.5f} : {2}".format(method.GetOptimizerIteration(),
                                       method.GetMetricValue(),
                                       method.GetOptimizerPosition()))
    # Fixed Image
    fixedImage = np.zeros((30,30))
    fixedImage[10:20,10:20] = 1
    sitkFixedImage = sitk.GetImageFromArray(fixedImage)

    # Moving Image
    movingImage = np.zeros((30,30))
    movingImage[11:21,11:21] = 1
    sitkMovingImage = sitk.GetImageFromArray(movingImage)

    # Define and Execute Registration Method
    registration_method = sitk.ImageRegistrationMethod()
    optimized_transform = sitk.TranslationTransform(2)
    registration_method.SetMetricAsMeanSquares()
    registration_method.SetMetricSamplingStrategy(registration_method.NONE)
    registration_method.SetInterpolator(sitk.sitkLinear)
    # registration_method.SetOptimizerAsLBFGSB(maximumNumberOfFunctionEvaluations=2000)
    registration_method.SetOptimizerAsLBFGSB(maximumNumberOfFunctionEvaluations=2000,lowerBound=-5.0,upperBound=5.0)
    registration_method.SetInitialTransform(optimized_transform)
    registration_method.AddCommand(sitk.sitkIterationEvent,lambda: command_iteration(registration_method))
    registration_method.Execute(sitkFixedImage,sitkMovingImage)

    sitkResampledMovingImage = sitk.Resample(sitkMovingImage, sitkFixedImage, optimized_transform, sitk.sitkLinear,
                                             0.0, sitkFixedImage.GetPixelIDValue())
    resampledMovingImage = sitk.GetArrayFromImage(sitkResampledMovingImage)

    # Display Outputs
    plt.figure(), plt.imshow(np.abs(fixedImage-movingImage),cmap='gray'), 
    plt.title('Image Difference: Before Registration')
    plt.figure(), plt.imshow(np.abs(fixedImage-resampledMovingImage),cmap='gray'), 
    plt.title('Image Difference: After Registration')

**Comment by blowekamp** [comment]
Regarding setting the bounds per parameter component. The space used for optimization can be scaled with either the OptimizerScales or the OptimerzerWeights.

When you say "erratic output" do you mean non-deterministic? or that the solution is just not good?

ITK's LBFGS optimizer has never performed well with a low number of parameters like in this case. I have not looked into it further to determine if that is the nature of the sparse hessian approximation the LBFGS utilizes or if it's an issue with the implementation.

There is also a new ITK LBFGS optimizer that may be of interest. I'll look into wrapping that.

**Comment by Shusil** [comment]
Thanks Brad. 
Using OptimizerScales or OptimizerWeights is definitely a work around. I believe it would have an effect of slowing down the learning rate for some parameters instead of limiting their bounds. ITK LBFGS optimizer would be a great addition!

By "erratic output" I meant the following outputs obtained from the sample code for different upper/lower bounds:
### Set the lower bound [Fail]:
The similarity metric as well as the parameter values are garbage. The optimizer exits after first iteration.
0 = 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.00000 : (1.7976931348623157e+308, 1.7976931348623157e+308)

### Set both lower and upper bounds [Fail]:
The upper bound is assigned to the parameters. The optimizer exits after first iteration.
0 =    0.20480 : (5.0, 5.0)

### Do not set upper/lower bounds [Succeed]:
The optimizer converges at the right solution of translation parameters (1.0,1.0).
  0 =    0.04222 : (0.0, 0.0)
  0 =    0.00408 : (0.7071067811865476, 0.7071067811865476)
  0 =    0.00408 : (0.7071067811865476, 0.7071067811865476)
  1 =    0.00010 : (1.0451243068521912, 1.0451243068521912)
  1 =    0.00010 : (1.0451243068521912, 1.0451243068521912)
  2 =    0.00000 : (0.9995777464464997, 0.9995777464464997)
  2 =    0.00000 : (0.9995777464464997, 0.9995777464464997)

**Comment by blowekamp** [comment]
Thank you for reporting the issue. I have created a patch for the bug: #340

**Comment by blowekamp** [comment]
The pull request was merged, and resolved the issue.
