### ISSUE TITLE
Dicom to stl Conversion

### ISSUE THREAD

**Issue by HimajaKanampalli** [SimpleITK/SimpleITK#34]
Thank you for making the dicom2stl.py
But I am facing some issues while converting entire dicom directory or zip file.
Single image is converting to stl format, but not entire directory.

Error:
Reading Dicom zip file: Dicom.zip
Error: no series foundctory.

Error:
Traceback (most recent call last):ctory.

Error:
File "dicom2stl.py", line 257, in
img, modality = loadZipDicom( fname[0] )
TypeError: 'NoneType' object is not iterable

How to load entire dicom directory (or) zip format for conversion.(Dicom to stl)? What is the commandline for this conversion?

**Comment by blowekamp** [comment]
Where did you get dicom2stl.py from it is not part of the SimpleITK repository. Was it from @dave3d ?

**Comment by dave3d** [comment]
The question was re-posted in the proper place, so this issue can be closed.

**Comment by blowekamp** [comment]
https://github.com/dave3d/dicom2stl/issues/1
