### ISSUE TITLE
Source of Variability in BFGS BSpline Registration?

### ISSUE THREAD

**Issue by siboles** [SimpleITK/SimpleITK#342]
I believe BFGS should be deterministic, but I am seeing variability in the convergence behaviour when performing a registration twice on the same image pair (see example below).

> Elapsed Iterations - Run 1: 36
> Final Metric Value - Run 1: -0.8261218809138697

> Elapsed Iterations - Run 2: 31
> Final Metric Value - Run 2: -0.8193961659593083

This variability is greater than what I would expect from machine precision, but perhaps it is round-off error? I set the metric sampling to be regular in the example below. Are there other stochastic elements that could contribute to the discrepancies?

`

    import SimpleITK as sitk
    import numpy as np
    
    moving = sitk.GetImageFromArray(np.random.rand(100, 100))
    bx = sitk.BSplineTransformInitializer(moving, (3,3), 3)
    displacements = np.random.uniform(-5, 5, len(bx.GetParameters()))
    bx.SetParameters(displacements)
    fixed = sitk.Resample(moving, bx)
    
    for i in range(2):
        rx = sitk.ImageRegistrationMethod()
        ix = sitk.BSplineTransformInitializer(fixed, (3,3), 3)
        rx.SetInitialTransform(ix)
        rx.SetMetricSamplingStrategy(rx.REGULAR)
        rx.SetMetricAsCorrelation()
        rx.SetMetricUseFixedImageGradientFilter(False)
        rx.SetOptimizerAsLBFGSB(numberOfIterations=100)
        
        tx = rx.Execute(fixed, moving)
        print("Elapsed Iterations - Run {:d}:".format(i+1), rx.GetOptimizerIteration())
        print("Final Metric Value - Run {:d}:".format(i+1), rx.GetMetricValue())

`

**Comment by blowekamp** [comment]
What is the behavior if you se the seed parameter in this member function:
 https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ImageRegistrationMethod.html#a8b891c62404a8dc5010241fea619c932

On Nov 17, 2017, at 6:43 PM, Scott Sibole <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe BFGS should be deterministic, but I am seeing variability in the convergence behaviour when performing a registration twice on the same image pair (see example below).

Elapsed Iterations - Run 1: 36
Final Metric Value - Run 1: -0.8261218809138697

Elapsed Iterations - Run 2: 31
Final Metric Value - Run 2: -0.8193961659593083

This variability is greater than what I would expect from machine precision, but perhaps it is round-off error? I set the metric sampling to be regular in the example below. Are there other stochastic elements that could contribute to the discrepancies?

`

import SimpleITK as sitk
import numpy as np

moving = sitk.GetImageFromArray(np.random.rand(100, 100))
bx = sitk.BSplineTransformInitializer(moving, (3,3), 3)
displacements = np.random.uniform(-5, 5, len(bx.GetParameters()))
bx.SetParameters(displacements)
fixed = sitk.Resample(moving, bx)

for i in range(2):
    rx = sitk.ImageRegistrationMethod()
    ix = sitk.BSplineTransformInitializer(fixed, (3,3), 3)
    rx.SetInitialTransform(ix)
    rx.SetMetricSamplingStrategy(rx.REGULAR)
    rx.SetMetricAsCorrelation()
    rx.SetMetricUseFixedImageGradientFilter(False)
    rx.SetOptimizerAsLBFGSB(numberOfIterations=100)

    tx = rx.Execute(fixed, moving)
    print("Elapsed Iterations - Run {:d}:".format(i+1), rx.GetOptimizerIteration())
    print("Final Metric Value - Run {:d}:".format(i+1), rx.GetMetricValue())


`

**Comment by siboles** [comment]
Interesting that the RNG seed would be set there. Thanks for pointing that out. This did indeed remove the variability. However, one needs to also be careful not to use seed=0, since that is the enumerator value for sitkWallClock. I made this mistake initially...

Adding,

`rx.SetMetricSamplingPercentage(0.1, seed=42)`

to the original code produced:

> Elapsed Iterations - Run 1 26
> Final Metric Value - Run 1 -0.8190323782545297
>
> Elapsed Iterations - Run 2 26
> Final Metric Value - Run 2 -0.8190323782545297

I do feel that this is very nonintuitive behaviour though, since setting the sampling strategy to REGULAR would suggest there is no need for an RNG. Is it possible that the sampling strategy is being ignored?

**Comment by blowekamp** [comment]
Here is the implementation of the REGULAR sampling strategy:
https://github.com/InsightSoftwareConsortium/ITK/blob/b260bae77729fecf2b3ff772343adb6299399838/Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx#L956-L983

So each regular place sample is displaced with a gaussian distribution with 1/3 the pixel spacing. This is a technique to reduce aliasing that may happen during the sampling of the metric.

Yes it should be documented better in the SimpleITK and ITK interfaces.

**Comment by siboles** [comment]
Okay this was very enlightening. I see the benefit of this behaviour in protecting us from ourselves as far as aliasing goes. Perhaps, the REGULAR sampling strategy could default to a set seed value, so the aliasing could be reduced, but the behaviour would still be repeatible.

**Comment by blowekamp** [comment]
I believe this question has been answered. Please feel free or re-open if needed.
