### ISSUE TITLE
ImageFileWriter doesn't update srows when image metadata is modified

### ISSUE THREAD

**Issue by unimusic** [SimpleITK/SimpleITK#346]

**Comment by blowekamp** [comment]
Please see the [ReadMe](https://github.com/SimpleITK/SimpleITK/blob/next/Readme.md#report-an-issue) for how to properly report an issue. A detailed description is needed to define the problem and reproduce it.

**Comment by unimusic** [comment]
1) No error message; problem is in the lack of modification of image metadata.
2) Operating system: Ubuntu 16.04.1
3) Programming language: Python 2.7.12
4) Version of SimpleITK: 1.1.0.dev457-ga9ef5 (ITK 4.12)
5) Built from source: Compiled Nov 30 2017 17:50:17
6) Example:
import SimpleITK as sitk
path = 'N17-1.0.1.scan.nii.gz'
newpath = 'demoimg.nii.gz'
img = sitk.ReadImage(path)
print 'original image srow_x value:'
print img.GetMetaData('srow_x')
img.SetMetaData('srow_x', '0 0 0 0')
print 'new image srow_x value (supposed):'
print img.GetMetaData('srow_x')
sitk.WriteImage(img, newpath)
newimg = sitk.ReadImage(newpath)
print 'new image srow_x value (actual):'
print newimg.GetMetaData('srow_x')

[N17-1.0.1.scan.nii.gz](https://github.com/SimpleITK/SimpleITK/files/1576541/N17-1.0.1.scan.nii.gz)

**Comment by blowekamp** [comment]
I have briefly looked into the Nifty format, and the itkNIFTIImageIO.
- the itkNIFTIImageIO does not use the metadata dictionary when writing the NIFTI file but does use the [quaternion field to represent the direction cosine matrix](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx#L1906-L1972).
- NIFTI has several representation for how to set the image orientation ( [see Orientation information](https://brainder.org/2012/09/23/the-nifti-file-format/) )
- In SimpleITK the orientation information can be updated by: `Image::SetDirection`. After writing and then reading file the image's direction cosine matrix is preserved.

**Comment by unimusic** [comment]
Hmm, interesting. I am trying to read in a series of compressed DICOM images and convert them to nifti while preserving the metadata information, which is proving not straightforward at all. I ended up reading in each slice and decompressing them, resaving them as uncompressed DICOM images, and using dcm2nii to convert those files to nii format.

**Comment by blowekamp** [comment]
From my brief look at the ITK NiftiImageIO, I did not see it writing the ITK meta-data dictionary to the nifti format which is aligned with the behavior you observed. Writing the MetaDataDictionary to Nifti certainly could be added to ITK upstream.

Using the SeriesReader it may be tricky to get the proper meta-data elements for each slice. You may be better off reading the slices separately.

Glad to hear you found a solution for your task.
