### ISSUE TITLE
Access metadata without loading the image array

### ISSUE THREAD

**Issue by fargiolas** [SimpleITK/SimpleITK#356]
Working with MetaImage medical data I often need to access some of the metadata contained in the MHD file without actually loading the image.
Usually it's because I just need to do some coordinate transformation and I need the values of origin, spacing and direction but not the actual data.

As far as I can tell the only way to do this is to load the image with ReadImage, like this
```
mhd = sitk.ReadImage(filename)
origin = mhd.GetOrigin()
spacing = mhd.GetSpacing()
direction = mhd.GetDirection()
```

But this loads the whole array into memory and can quickly eat away precious mem when working with many parallel jobs.

Is there a way to access metadata from SimpleITK without loading the image?

**Comment by blowekamp** [comment]
Currently, SimpleITK does not have such a feature, but it is of much interest. I'm going to code up the proposed interface to see if it meets you needs and share the pull request. Please stay tuned...

**Comment by blowekamp** [comment]
Please see pull request #357 for the proposed interface.

This does not use the procedural interface but the object oriented one. For your use case the usage would be:
```
reader = sitk.ImageFileReader()
reader.SetFileName(filename)
reader.MetaDataRead()
origin = reader.GetOrigin()
spacing = reader.GetSpacing()
direction = reader.GetDirection()
```
Does the proposed interface meet your requirements? What do you think?

**Comment by fargiolas** [comment]
Looks pretty fine to me. No problem with using the object oriented interface.

**Comment by blowekamp** [comment]
The feature topic has been merged into the next branch for testing on the dashboard. It will likely  make it to the master branch next week.

**Comment by blowekamp** [comment]
This topic has been merged into master.

**Comment by fargiolas** [comment]
Thank you @blowekamp for working on this! Could you add a few lines to the stackoverflow answer with a short example of the new interface?
