### ISSUE TITLE
iterate over the transformation stack in a composite transform

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#361]
There is a need for accessing (setting/getting) the whole transformation stack from a composite transform. For example one may want to compress the transformation stack, a set of global transformations can be combined into a single Affine transformation, or if the stack includes non-rigid transformations it can be combined into a DisplacementFieldTransform.

**Comment by dave3d** [comment]
May not really be needed?  Can be implemented easily by keeping a set of transformations on the side. (Composite shouldn't be used as a container for transforms?)
