### ISSUE TITLE
SimpleITK and nonrigid transformation

### ISSUE THREAD

**Issue by yousefis** [SimpleITK/SimpleITK#363]
I'm using SimpleITK in python to read 3d images.

    import SimpleITK as sitk
    mhd = sitk.ReadImage('fixed.png')

I am looking for a function or a way to apply a non-rigid transformation like bspline over the image. as I got the transformation functions get one fixed and one moving image and then apply the transformation to get a registered result. (optimizes a cost function by transforming the moving image in order to match the moving image on the fixed image)

    fixed = sitk.ReadImage('fixed.png', sitk.sitkFloat32)
    moving = fixed#sitk.ReadImage('moving.png', sitk.sitkFloat32)
    transformDomainMeshSize=[8]*moving.GetDimension()
    tx = sitk.BSplineTransformInitializer(fixed,
                                      transformDomainMeshSize )

    R = sitk.ImageRegistrationMethod()
    R.SetMetricAsCorrelation()
    R.SetOptimizerAsLBFGSB(gradientConvergenceTolerance=1e-5,
                       numberOfIterations=1000,
                       maximumNumberOfCorrections=5,
                       maximumNumberOfFunctionEvaluations=1000,
                       costFunctionConvergenceFactor=1e+7)
    R.SetInitialTransform(tx, True)
    R.SetInterpolator(sitk.sitkLinear)
    outTx = R.Execute(fixed, moving)

but I have only one image and looking for a way that I can define a random vector field (a kernel) and can apply it over the image and get a deformed image!
every idea would be appreciated.

**Comment by zivy** [comment]
This is quit straightforward. Please see [this Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/70_Data_Augmentation.ipynb
) for an example of using a DisplacementFieldTransform to deform an image (radial_distort function).

I would also recommend looking at the following two notebooks to gain a good understanding of working with transformations and resampling:
1. [transforms and resampling](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/21_Transforms_and_Resampling.ipynb) from our main notebook repository.
2. [images and resampling](https://github.com/SimpleITK/SPIE2018_COURSE/blob/master/images_and_resampling.ipynb) from an upcoming course repository - has some more prose on the process of resampling.
