### ISSUE TITLE
How can I convert Nifti to DICOM by simpleITK?

### ISSUE THREAD

**Issue by EdwardMa12593** [SimpleITK/SimpleITK#378]
I want to convert Nifti data to Dicom data. Following is my code
```python
nii_data_path = 'F:/TestData/'
dicom_output_path = 'F:/TestDataDicom/'
patients = os.listdir(nii_data_path)
patients.sort()

for s in patients:
    NiftyImg = sitk.ReadImage(nii_data_path + s)
    Img = sitk.GetArrayViewFromImage(NiftyImg)
    Slic_Num = len(Img)
    print(s, Slic_Num)
    for slic in range(Slic_Num):
        DicomFileName = dicom_output_path + s.split('.nii')[0] + "-" + str(slic) + ".dcm"
        sitk.WriteImage(Img[slic,:,:], DicomFileName)
        print('Successifully write: ', slic)
```
However, the data type seems to be wrong.
Following is the error information
```python
NotImplementedError: Wrong number or type of arguments for overloaded function 'WriteImage'.
  Possible C/C++ prototypes are:
    itk::simple::WriteImage(itk::simple::Image const &,std::string const &,bool)
    itk::simple::WriteImage(itk::simple::Image const &,std::vector< std::string,std::allocator< std::string > > const &,bool)
```
Looking forward to your help.
Best wishes!
Edward

**Comment by blowekamp** [comment]
Have you seen the [Dicom Series From Array](http://simpleitk.readthedocs.io/en/next/Examples/DicomSeriesFromArray/Documentation.html) example?

**Comment by EdwardMa12593** [comment]
Thanks for your reply. It helps me a lot.

**Comment by Nicholasxin** [comment]
@EdwardMa12593 I still do not understand how to write nii file to dicom series.  Can you share the code? Or give some hint to help. Thanks a lot!

**Comment by Neeemoo** [comment]
@JunMa11 I too can't find a solution and would appreciate it if you would share your code with us

**Comment by zivy** [comment]
Dear @Nicholasxin, @Neeemoo ,

To convert a nii image to a DICOM series all you need to do is:
a. Read the image:
```
image3D  = sitk.ReadImage('my_image.nii') 
```
b. Modify the example @blowekamp  [pointed to in the original response](https://simpleitk.readthedocs.io/en/next/Examples/DicomSeriesFromArray/Documentation.html).

You need to be careful when setting the DICOM tags, as these are specific to your images, e.g. modality tag [0008|0060](https://dicom.innolitics.com/ciods/cr-image/general-series/00080060).

**Comment by Neeemoo** [comment]
Thanks a lot for your fast reply, appreciate it!

**Comment by Joevaen** [comment]
> Dear @Nicholasxin, @Neeemoo ,
> 
> To convert a nii image to a DICOM series all you need to do is:
> a. Read the image:
> 
> ```
> image3D  = sitk.ReadImage('my_image.nii') 
> ```
> 
> b. Modify the example @blowekamp [pointed to in the original response](https://simpleitk.readthedocs.io/en/next/Examples/DicomSeriesFromArray/Documentation.html).
> 
> You need to be careful when setting the DICOM tags, as these are specific to your images, e.g. modality tag [0008|0060](https://dicom.innolitics.com/ciods/cr-image/general-series/00080060).

Did you solve that? I still don't what I should do.
