### ISSUE TITLE
ImageSeriesReader GetMetaDataKeys uses numbers instead of text

### ISSUE THREAD

**Issue by unimusic** [SimpleITK/SimpleITK#382]
1. No error message; my issue is that when getting metadata keys from a DICOM series, the keys are in terms of Group and Element instead of Tag Name. I would like to have an option of both, for greater usability.
2. Operating system: Ubuntu 16.04.1
3. Programming language: Python 2.7.12
4. Version of SimpleITK: 1.1.0.dev457-ga9ef5 (ITK 4.12)
5. Built from source: Compiled Nov 30 2017 17:50:17
6. Example:
import SimpleITK as sitk
reader = sitk.ImageSeriesReader()
reader.MetaDataDictionaryArrayUpdateOn()
reader.LoadPrivateTagsOn()
path = 'demoFolder'
series_IDs = reader.GetGDCMSeriesIDs(path)
dicom_names = reader.GetGDCMSeriesFileNames(path, series_IDs[-1])
reader.SetFileNames(dicom_names)
image = reader.Execute()
reader.GetMetaDataKeys(0)

**Comment by blowekamp** [comment]
Thank you for your complete post.

This could be a layer on top of SimpleITK's interface, but is beyond the scope of SimpleITK itself. I believe a simple dictionary mapping the DICOM Group and Element to a string, either a  "Name" or a "Keyword" could easily be done.
