### ISSUE TITLE
remote modules documentation

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#384]
Add the list of remote modules available in SimpleITK to read-the-docs. The list should specify whether the module is available as part of the binary release or requires a local build (is it on or off by default).

**Comment by blowekamp** [comment]
Should all filters be documented in Doxygen? Should we list which ITK Module each filter is in in the Doxygen? Should we form a DOxygen Module tab with sublists of which module each filter belongs to?

**Comment by blowekamp** [comment]
SimpleITK is no longer going to prioritize enabling remote module in customized build, and continue to focus on quality core functionality.
