### ISSUE TITLE
"brew install simpleitk" fails

### ISSUE THREAD

**Issue by HackerMD** [SimpleITK/SimpleITK#39]
Installation via *homebrew* resulted in the following error:

```
==> Downloading https://downloads.sourceforge.net/project/simpleitk/SimpleITK/0.8.0/Source/SimpleITK-0.8.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/simpleitk-0.8.0.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/simpleitk/0.8.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FI
==> make install
/tmp/simpleitk20160210-88654-1y48yu9/SimpleITK-0.8.0/Code/BasicFilters/include/sitkWhiteTopHatImageFilter.h:138: Error: Line indented less than expected (line 4 of pythoncode)
/tmp/simpleitk20160210-88654-1y48yu9/SimpleITK-0.8.0/Code/BasicFilters/include/sitkWhiteTopHatImageFilter.h:148: Error: Line indented less than expected (line 4 of pythoncode)
make[2]: *** [Wrapping/SimpleITKPYTHON_wrap.cxx] Error 229
make[1]: *** [Wrapping/CMakeFiles/SimpleITK_PYTHON.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by blowekamp** [comment]
@iMichka has done the work on the home brew recipe:
https://github.com/Homebrew/homebrew-science/blob/master/simpleitk.rb

As you are trying to build the older 0.8.0, and not the latest release of 0.9.1 I am going to suggest that you are using an old out of date script. What are you doing to try to install SimpleITK in Homebrew?

**Comment by HackerMD** [comment]
I simply did `brew install simpleitk`.

When I call `brew search simpleitk` I also get only one option.

**Comment by iMichka** [comment]
Hi
I am wondering why do you try to build simpleITK 0.8.0 ? Is there a particular reason for this ?
If not, please ```brew update && brew upgrade && brew install simpleitk```.

Please follow the instructions in the bug reporting guideline to upload a full build log:
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#create-an-issue

Note that the simpleITK formula is probably broken anyway as there was a strong dependency on ITK. With simpleITK 0.9.0, simpleITK is built using the superbuild mechanism, which is much more robust.

**Comment by iMichka** [comment]
I just realised we are not on the homebrew bug tracker :) I think it is more common to report homebrew build bugs on the homebrew bug tracker; package maintainers can often solve specific build problems by themselves, without bothering the upstream devs. But there is general rule for this, so let's keep only one bug open here for the moment.

**Comment by HackerMD** [comment]
``brew upgrade`` did the trick. Thank you guys!
