### ISSUE TITLE
sitk.WriteImage writes out corrupted image when the pixel type is int64

### ISSUE THREAD

**Issue by woxuankai** [SimpleITK/SimpleITK#398]
Hi,

I tried to use sitk.GetImageFromArray and sitk.WriteImage to save an int64 array but got wrong nifti image. However, if I convert the array to int8, everything seems to be fine.
I'm using SimpleITK 1.0.1 installed with pip3 and python 3.6.4 provided by the latest Archlinux.

Here's the screenshot of rightly (int8) and wrongly (int64) saved image. 
(As both ITK-snap and MRICron failed to display the saved int64 image properly, I'd assume there's something wrong with the saved int64 image instead of the software I used to visualize nifti images.)
![origin](https://user-images.githubusercontent.com/17685639/35966354-89a733e8-0cf8-11e8-895e-38c4fedabcbb.png)
![corrupted](https://user-images.githubusercontent.com/17685639/35966393-a28dad10-0cf8-11e8-86c0-a03716630a82.png)

I also wrote a code snippet to reproduce the bug and input/output image file is also attached.

```
import numpy as np
import SimpleITK as sitk
img = sitk.ReadImage('./a103262782.nii.gz')
arr = sitk.GetArrayFromImage(img)
arr64 = arr.astype(np.int64)
img64 = sitk.GetImageFromArray(arr64)
sitk.WriteImage(img64, 'test.nii.gz')

```
[test.nii.gz](https://github.com/SimpleITK/SimpleITK/files/1706473/test.nii.gz)
[a103262782.nii.gz](https://github.com/SimpleITK/SimpleITK/files/1706471/a103262782.nii.gz)

Thank you

**Comment by blowekamp** [comment]
There could easily be something wrong with your visualization programs that is outside SimpleITK. A better test is to read the writing file back into SimpleITK and check the values.

- I am able to reproduce some writing problems of int64 with Nifty Images.
- You should use 'sitk.Cast(img, sitk.sitkInt64)' as this will preserve the images' meta data such as spacing, origin, and direction cosine matrix
- Have you tried writing a MetaIO file with extension ".mha", there may be better support.
- SimpleITK 1.1rc1 was tag yesterday, and will be announced shortly on [ITK discourse](https://discourse.itk.org). This contains some int64 fixes from ITK.

**Comment by woxuankai** [comment]
Thank you for your advice!

- I saved int64 image as .mha file and then used ITK-snap to visualize it, everything seems to be all right!!!

- I tried to loaded saved int64 nifti image, coverted it to numpy array using sitk.GetArrayFromImage and visualize the array with OpenCV, but got same strange image only.

```
import numpy as np
import SimpleITK as sitk
import cv2 
img = sitk.ReadImage('./test.nii.gz') # test.nii.gz is the saved int64 image
arr = sitk.GetArrayFromImage(img)
cv2.imshow('title', arr[10]/4.0) # display the 10th slice, the maximum value of saved image is 4
cv2.waitKey()
```

**Comment by blowekamp** [comment]
I believe I have a patch which will help with this issue. Additionally SimpleITK 1.1 will be built against ITK 4.13 which include additional 64-bit IO integer fixes.
