### ISSUE TITLE
Using weighted masks/images in registration

### ISSUE THREAD

**Issue by vikramc1** [SimpleITK/SimpleITK#399]
I’m trying to register two image volumes using Simple ITKs affine registration and an implementation of a deformable registration, written in C, using ITK. From these images I am creating a non-binary mask that indicates the confidence/weight that should be given to data in a certain regions. I know that it is possible to pass in binary masks for both the fixed and moving images for both of these methods.  However, is it possible to use non-binary masks as described above on either the fixed or moving images or both?

**Comment by blowekamp** [comment]
That is an interesting idea.

If you consider the how the weights would be applied to the cost functions, it is not clear to me if any would behave as you are expecting. Although you could derive a metric for this specific purpose, or look into multi-image/multi-channel registration.

One way a weighting could be constructed is by the distribution of pointed used to sample the metric. If the image is sampled more where it is important and less where it is not, would that not be equivalent to applying a weight? While ITK does explicitly support specifying an explicit point set for sampling, SimpleITK does not currently. But we do support masks used for sampling. So if you binarize you grayscale image into a binary image, and interpret that as sampling you may arguably achieve equivalent results.

**Comment by blowekamp** [comment]
Closing the question asked. Please free to reopen if more information is needed or continue the discussion.

**Comment by vikramc1** [comment]
Thank you for your response! I’ll try to look into alternatives to perform this functionality if it remains an issue for me.
