### ISSUE TITLE
Problems with GrayscaleMorphologicalClosingImageFilter

### ISSUE THREAD

**Issue by skn123** [SimpleITK/SimpleITK#404]
I am trying to use this function (wrapped in SimpleITK) in my code and I get this compile error. 
ITK - Fresh from github branch
SimpleITK - Fresh from github branch
compiler - clang 4.0
OS - Ubuntu 16.04

``In file included from /usr/local/include/ITK-5.0/itkGrayscaleMorphologicalClosingImageFilter.h:21:
/usr/local/include/ITK-5.0/itkKernelImageFilter.h:99:14: error: implicit instantiation of undefined template 'itk::FlatStructuringElement<2>'
  KernelType m_Kernel;
             ^
/usr/local/include/ITK-5.0/itkVanHerkGilWermanErodeDilateImageFilter.h:42:10: note: in instantiation of template class
      'itk::KernelImageFilter<itk::Image<float, 2>, itk::Image<float, 2>, itk::FlatStructuringElement<2> >' requested here
  public KernelImageFilter< TImage, TImage, TKernel >
         ^
/usr/local/include/ITK-5.0/itkVanHerkGilWermanDilateImageFilter.h:40:10: note: in instantiation of template class
      'itk::VanHerkGilWermanErodeDilateImageFilter<itk::Image<float, 2>, itk::FlatStructuringElement<2>, itk::MaxFunctor<float> >' requested
      here
  public VanHerkGilWermanErodeDilateImageFilter< TImage, TKernel, MaxFunctor< typename TImage::PixelType > >
         ^
/usr/local/include/ITK-5.0/itkGrayscaleMorphologicalClosingImageFilter.h:147:12: note: in instantiation of template class
      'itk::VanHerkGilWermanDilateImageFilter<itk::Image<float, 2>, itk::FlatStructuringElement<2> >' requested here
  typename VanHerkGilWermanDilateFilterType::Pointer m_VanHerkGilWermanDilateFilter;
           ^
/home/naths/Downloads/xip-src-0.4-r3444/src/database/itk/generated/SoItkGrayscaleMorphologicalClosingImageFilter.cpp:216:7: note: in
      instantiation of template class 'itk::GrayscaleMorphologicalClosingImageFilter<itk::Image<float, 2>, itk::Image<float, 2>,
      itk::Neighborhood<float, 2, itk::NeighborhoodAllocator<float> > >' requested here
                                                FilterType::Pointer filter = FilterType::New();
                                                ^
/usr/local/include/ITK-5.0/itkKernelImageFilter.h:26:43: note: template is declared here
template< unsigned int VDimension > class FlatStructuringElement;
``

I have checked that this problem is also there with itk 4.13

**Comment by blowekamp** [comment]
Do yo have sample code you are trying to compile? I looking like this error may be emitting from a file: `SoItkGrayscaleMorphologicalClosingImageFilter.cpp`

ITK is undergoing a major revision change, and is currently unstable. I do would not recommend building against it's master.
