### ISSUE TITLE
Wish: Expose C++ code to R

### ISSUE THREAD

**Issue by zarquon42b** [SimpleITK/SimpleITK#42]
I started playing with SimpleITK and R and currently try to create displacement images with each voxel being represented by a 3D vector.
Would it be possible to expose C++ code to R to allow overcoming the slow for loops in R. That way, you could pass the R-data via Rcpp and then call the implemented functions directly (after linking the created dynlib to SimpleITK)..
Best
Stefan

**Comment by blowekamp** [comment]
Hello,

I experimented with something similar to what you request in Python. Please find the topic here [1].

Basically, Something like the following code would be added to the R library:
%wrapper %{
SWIGEXPORT itk::simple::Image * convertSwigSimpleITKImage( SEXP obj )
{
  itk::simple::Image *img;
  if (SWIG_ConvertPtr(obj, (void **) &img,  SWIGTYPE_p_itk__simple__Image, ??) == -1)
    return NULL;
  return img;
}
%}

You can look at the generated SimpleITKR_wrap.cxx file for more information.

I'd expect with this interface you should be able to work the Rcpp, but I haven't used it.

If you are able to give it a try, please share the results!

[1] https://github.com/SimpleITK/SimpleITK/compare/master...blowekamp:AddCXXConvertInterfaceToPythonLibrary

**Comment by zarquon42b** [comment]
Hi, thanks for your answer.
I will check it out.

**Comment by zarquon42b** [comment]
Hi,
It is actually quite easy. The `extern` declaration of the SimpleITK function does the trick. I started a package and added a simple function that calls the SimpleITK code on C++ level (getting the image dimensions; see: https://github.com/zarquon42b/RcppSimpleITK/blob/master/src/test.cpp). I will try to pass indices and values as matrices and run the image filling on C++ too. Theoretically, this should work.

**Comment by blowekamp** [comment]
The problem with your approach is that you are dependent on the swig generated interface, which is not a public interface that is define and is subject to change.

Explicitly declaring a Public method, as I suggest, to get a C++ sitk object from a R Swigged object is better for the long term as it ensure compatibility. This would require just one method as oppose each member function in yours.

Is there an advantage to your approach that I am missing?

**Comment by zarquon42b** [comment]
OK, now I got what you meant (I have no experience with SWIG yet). I tested it and it works on my local machine (I have not pushed it yet). To make things portable, this approach requires a more tedious setup for a dependent R-package, involving configure scripts and cmake and a complete install of SimpleITK (not only the created R-package) 
My naive lazy man's approach would have worked with the self-contained SimpleITK R-package without the need of the rest of SimpleITK and as all functions are targeting SEXP objects passing data would be fairly easy.

**Comment by blowekamp** [comment]
I suppose I have a longer run view of being lazy. Your approach would work for one project, but maintaining it when something changes, or re-using it for multiple projects would be very difficult.

Yes, you will need to include the SimpleITK headers, and link against SimpleITK libraries. Fortunately, if you just use SimpleITK, you don't need ITK directly as it's not exposed as a public dependency. This should make things much easier.

CMake would take care of a lot of this, but integrating it in with the R packaging system you are using would be difficult.

**Comment by zarquon42b** [comment]
OK, let's call it short-sightedly lazy ;) 
Integrating cmake and R-package installation can actually work: I am already doing it in my package [RvtkStatismo](https://github.com/zarquon42b/RvtkStatismo)
After some further testing, I will issue a pull request regarding the necessary changes in R.i (in SimpleITK)

**Comment by zarquon42b** [comment]
I got it up and running, including cmake and configure scripts. The example function (called 'test' successfully updates an sitk::Image's origin via the C++ interface and Rcpp.

**Comment by zarquon42b** [comment]
FYI: the wrapping works brilliantly. In the new R-package, I added functionality to fill vector images using a matrices containing indices and vectors, and it is very fast now and allows any kind of image operations on C++ level.
