### ISSUE TITLE
RuntimeError: Exception thrown in SimpleITK ReadImage

### ISSUE THREAD

**Issue by tiantian-li** [SimpleITK/SimpleITK#434]
I run the code on Ubuntu16.04 in the virtual machine. The python version is python2.7 which is installed from anaconda2. The following error occurred when I ran the code of brain tumor image segmentation:

RuntimeError: Exception thrown in SimpleITK ReadImage: /opt/miniconda2/conda-bld/simpleitk_1520545023187/work/Code/IO/src/sitkImageReaderBase.cxx:97:
sitk::ERROR: Unable to determine ImageIO reader for "Image_Data/LG/0001"

I don't know why this problem arises. How should I solve this problem? Sincerely hope that you can help me solve it.Thanks

**Comment by blowekamp** [comment]
Do you know what type if image file that is? Many of the ITK's available ImageIOs use the file extension to determine if they can read the file.

**Comment by tiantian-li** [comment]
The code reads the .mha image files. I've run this code on Windows and it can be run successfully.But the error above is occured when i run it on Ubuntu. I don't know how to solve it. Could you please give me some help?

**Comment by blowekamp** [comment]
You can check the following:
- Verify that the file exists and you are passing to SimpleITK properly. Try something like: `os.path.isfile("Image_Data/LG/0001") `
- Your filename does not have a file extension. It should. If it is a MetaData image file formats add ".mha"
- Verify your file is of the proper size, and make sure the file is not corrupt.

**Comment by yionly1994** [comment]
同学，我是在查N4BiasFieldCorrection的时候看到你的，你能教我一下怎么在windows下安装吗，如果可以的话留个联系方式给我，我的邮箱是66470861@qq.com
ps：我看了你的上传，你应该是中国人哈哈

**Comment by charlesity** [comment]
Hi, I am getting the exact same error. Did anyone solve this problem?

**Comment by Angeluz-07** [comment]
This problem also arises when you use `sitk.ReadImage()` with files in Raw data storage format, i.e. the SOP Class UID is `1.2.840.10008.5.1.4.1.1.66`.

**Comment by jjagtap** [comment]
> You can check the following:
> 
> * Verify that the file exists and you are passing to SimpleITK properly. Try something like: `os.path.isfile("Image_Data/LG/0001") `
> * Your filename does not have a file extension. It should. If it is a MetaData image file formats add ".mha"
> * Verify your file is of the proper size, and make sure the file is not corrupt.

It worked for me. windows vs ubantu issue in finding the path.

**Comment by Catadanna** [comment]
Hallo, had the same problem. I get the following error when trying to open a Dicom file (dcm extension): 

```
Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:107:
sitk::ERROR: Unable to determine ImageIO reader for PATH_TO_IMAGE
```

I use:
Ubuntu 18, 
Python 3.7.6
Kaggle notebook

Now, the path is OK, the file exists. I can read the file correctly with pydicom.
I could read other files in other circumstances with the same function. 

Any help would be appreciated.

**Comment by zivy** [comment]
Hello @Catadanna,

Can you share the image? That would greatly help us in figuring out the issue. Also, which version of SimpleITK are you using? We are close to releasing SimpleITK2.0 and [release candidate 3 is available online](https://github.com/SimpleITK/SimpleITK/releases) for testing.

**Comment by Catadanna** [comment]
@zivy : I use SimpleITK version 1.2.4. It happened with several dicom images, which I could properly open with pydicom.

**Comment by zivy** [comment]
Hi @Catadanna,

Based on your input we really do need a sample image so that we can figure out what is the issue.

It could be a DICOM compliance issue where pydicom is more relaxed about reading vs. gdcm being more strict (library used under the  SimpleITK hood). For now this is just speculation as we can't reproduce the issue without a sample image.

**Comment by Catadanna** [comment]
Here, zipped:
[img.zip](https://github.com/SimpleITK/SimpleITK/files/5212928/img.zip)

**Comment by zivy** [comment]
Hie @Catadanna,

My setup: ubuntu18, SimpleITK RC3, Python 3.7.6.

I ran the following from the command line: `python -c 'import SimpleITK as sitk; sitk.Show(sitk.ReadImage("img.dcm"))'` and it worked without a problem. Displayed an axial CT slice thoracic-abdominal region.

Could this be something with your use of a Kaggle notebook?

**Comment by rekon** [comment]
> Hallo, had the same problem. I get the following error when trying to open a Dicom file (dcm extension):
> 
> ```
> Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:107:
> sitk::ERROR: Unable to determine ImageIO reader for PATH_TO_IMAGE
> ```
> 
> I use:
> Ubuntu 18,
> Python 3.7.6
> Kaggle notebook
> 
> Now, the path is OK, the file exists. I can read the file correctly with pydicom.
> I could read other files in other circumstances with the same function.
> 
> Any help would be appreciated.

I am also getting the same error when I am trying to read from (NFS)  mounted directory inside docker

**Comment by zivy** [comment]
Hello @Catadanna 

A second look at the error message indicates that the file name you are giving is `PATH_TO_IMAGE` I suspect you have a bug in your code, quoting the variable instead of using its content:
`sitk.ReadImage('PATH_TO_IMAGE')` instead of  `sitk.ReadImage(PATH_TO_IMAGE)`

**Comment by jjagtap** [comment]
Try the following code. Make sure the 'dicom_folder' or your folder has some Dicom files.

import os
import SimpleITK as sitk # pydicom
filepath = "/research/projects/......../dicom_folder/"
for each in os.listdir(filepath):
    imgObj=sitk.ReadImage(os.path.join(filepath,each))
    ndarray=sitk.GetArrayFromImage(imgObj)    
    writeObj=sitk.GetImageFromArray(ndarray)
    writeObj.CopyInformation(imgObj)
    writer = sitk.ImageFileWriter()
    writer.SetFileName(filepath+each+'.nii.gz')
    writer.Execute(writeObj)

**Comment by rekon** [comment]
Hello,
The issue was due to corrupted files, once proper files were provided, the issue got resolved

**Comment by anirban1513** [comment]
I am getting the same error! 

What to do?? 

RuntimeError: Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK-build/ITK/Modules/IO/Meta/src/itkMetaImageIO.cxx:491:
itk::ERROR: MetaImageIO(0x5626ef6dffe0): File cannot be read: /data/lobedata/LUNG_LOBE_CT_Data/Train/Image/1.3.6.1.4.1.14519.5.2.1.6279.6001.307835307280028057486413359377.mhd for reading.
Reason: No such file or directory


But I checked that the file is there. 

I am using ubuntu 18.04. SimpleITK 1.2.4

**Comment by zivy** [comment]
Hello @anirban1513 ,

Two things you can check:
1. Confirm that the image file is not corrupt (try loading into [SITK-SNAP](http://www.itksnap.org/)).
2. Confirm that the raw portion of the data is also in that directory. The mhd format consists of two files, the header text file and the raw pixel data file. Check that the ElementDataFile listed in the header does indeed exist in the expected location.

**Comment by hafedh-hichri** [comment]
found a solution i do not know if this code works for you  but try it out 

`from medpy.io import load
import numpy as np
image_data1= load('1.mha')
img1 = image_data1[0] `


img1 is the imge in numpy 
to print the numpy array as an image : 

`import matplotlib.pyplot as plt
plt.imshow(img1)`

**explanation**

### image_data contains a 3D image and a "header" 

image_data[0] contains the 3D image  in type numpy 
and image_data[1] contains the header
