### ISSUE TITLE
DICOM dose files

### ISSUE THREAD

**Issue by ceps1986** [SimpleITK/SimpleITK#435]
Is there an easy way to read DICOM RT_dose files within SimpleITK?
I'm currently loading the 3D dose matrix as numpy and converting to sitk, but I was hoping to find a better way to do this within sitk. 
I look forward to hearing from you! Thank you for all your help

**Comment by blowekamp** [comment]
We have focused SimpleITK to provide access to DICOM bulk image data and generic access to the meta-data. SimpleITK does not have access to extended structured DICOM data like RT_dose information.
