### ISSUE TITLE
How can I distinguish several different DICOM series which in a same directory?

### ISSUE THREAD

**Issue by Williamongh** [SimpleITK/SimpleITK#436]
Thanks for your work and share.
Here I have several different DICOM series, they are all in a same directory. I want to use these code to identify different DICOM image:
```
imageReader = sitk.ImageSeriesReader()
dicom_names = imageReader.GetGDCMSeriesFileNames(path)
print(dicom_names )
```
Then I found I can only get the first image.
I wonder how can I identify them, and get the right image I want?
Thank you !

**Comment by zivy** [comment]
You will first need to get the list of series ids in the directory:
`series_ids = imageReader.GetGDCMSeriesIDs(path)`

Then you select the relevant series (somehow), and get the specific file names associated with it:
```
i=3
imageReader.GetGDCMSeriesFileNames(path, series_ids[i])
```

For an example with a dropbox see [this Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/03_Image_Details.ipynb).

You may be interested in the examples shown in the notebooks in general, see the [main notebook repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks).

**Comment by Williamongh** [comment]
Thanks a lot! It works!
BTW, here is a new question. After I read a DICOM series, I want get the meta data with it:
```
imageReader= sitk.ImageSeriesReader()
imageReader.LoadPrivateTagsOn()
series_ids = imageReader.GetGDCMSeriesIDs(path)
series_file_names = imageReader.GetGDCMSeriesFileNames(path, series_ids [0])
imageReader.SetFileNames(series_file_names)
image = imageReader.Execute()  # type: sitk.Image
print(image.GetMetaDataKeys())
```
But it returns an empty list, what should I do? 
Thank you !

**Comment by zivy** [comment]
Three points:

1. In SimpleITK, the returned image will not have a meta data dictionary - rationale: this is most often a 3D image where each of the 2D images from which it was created had a separate meta-data dictionary. We can't know how to combine them together (there is slice specific information in each).

2. To access the meta-data keys and information on a per-slice basis you have three functions, as illustrated below:
```
slice_number = 0
slice_keys = imageReader.GetMetaDataKeys (slice_number) 
imageReader.HasMetaDataKey(slice_number, '0010|0010')
imageReader.GetMetaData(slice_number, '0010|0010')
```
3. You are missing a line before "LoadPrivateTagsOn" which tells the reader to actually load the tags:
```imageReader.MetaDataDictionaryArrayUpdateOn()```

**Comment by Williamongh** [comment]
Thank you for your time. It helps a lot!
I've solved my problem.
