### ISSUE TITLE
Show method does not preserve pixel spacing

### ISSUE THREAD

**Issue by nocnokneo** [SimpleITK/SimpleITK#438]
My expectation is that with the code below:

```py
import SimpleITK as sitk
image = sitk.Image(64, 64, sitk.sitkFloat32)
image.SetSpacing((2.0, 3.0))
sitk.Show(image) # Image shown in ImageJ has unity pixel spacing
```

The image shown in ImageJ should have the same pixel spacing as `image` (`(2.0, 3.0)` in this case).

**Comment by blowekamp** [comment]
This is an unfortunate limitation of ImageJ. It does not render anisotropic pixel spacing. You can configure `sitk.Show` to use another external viewer such as [3D Slicer](https://www.slicer.org/) or [ITKSnap](http://www.itksnap.org/pmwiki/pmwiki.php). This is documented in the S[impleITK Notebooks](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/03_Image_Details.html) and in the Doxygen for [Show](https://itk.org/SimpleITKDoxygen/html/namespaceitk_1_1simple.html#a86cb9e226d455efca3ba034dc2154605).

**Comment by nocnokneo** [comment]
I understand that ImageJ doesn't _render_ anisotropic pixel spacing, but it does support measurements on an image with anisotropic pixel spacing.

Even when using isotropic pixel spacing as in:

```py
import SimpleITK as sitk
image = sitk.Image(64, 64, sitk.sitkFloat32)
image.SetSpacing((2.0, 2.0))
sitk.Show(image) # Image shown in ImageJ has unity pixel spacing
```

The image shown in ImageJ by `Show` has 1 unit pixel spacing in all directions. From Analyze > Set Scale ... menu, this is what I see:

![image](https://user-images.githubusercontent.com/514960/38585388-aed7a67e-3ce7-11e8-90fc-d02c8f5d06f8.png)

**Comment by blowekamp** [comment]
The intermediate file should have the spacing in it. Do you know what file formats that ImageJ supports with spacing?  You can configure the file extension used by Show.

On Apr 10, 2018, at 5:52 PM, Taylor Braun-Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


I understand that ImageJ doesn't render anisotropic pixel spacing, but it does support measurements on an image with anisotropic pixel spacing.

Even when using isotropic pixel spacing as in:

import SimpleITK as sitk
image = sitk.Image(64, 64, sitk.sitkFloat32)
image.SetSpacing((2.0, 2.0))
sitk.Show(image) # Image shown in ImageJ has unity pixel spacing

The image shown in ImageJ by Show has 1 unit pixel spacing in all directions. From Analyze > Set Scale ... menu, this is what I see:

[image]<https://user-images.githubusercontent.com/514960/38585388-aed7a67e-3ce7-11e8-90fc-d02c8f5d06f8.png>

**Comment by nocnokneo** [comment]
Yep, using NRRD fixed it:

```
import os
os.environ["SITK_SHOW_EXTENSION"] = ".nrrd"
```

Being the default format used by SimpleITK and one designed for medical imaging I'd assumed that NIFTI supported pixel spacing information. Does it not? If not, perhaps the default format used by `Show` should be changed to NRRD?

**Comment by nocnokneo** [comment]
Thanks for following up. I've filed an upstream bug: https://github.com/fiji/fiji/issues/191

> We choose NIFTI over NRRD as the default export file format because ImageJ supports all pixel types for NIFTI, where as ImageJ does not support complex pixel types with NRRD file types.

I see. That's unfortunate...

**Comment by nocnokneo** [comment]
Looks like `sitk.Show()` is using `.mha`, at least for some users.[1] Has the default file format only recently changed to NIFTI?

[1] http://lists.openmicroscopy.org.uk/pipermail/ome-users/2018-May/007060.html

**Comment by dave3d** [comment]
When the Show function uses Fiji, the default image format is set to '.mha'.  We did that because for '.nii' Fiji brings up the Bio-Formats Import Options dialog box.
