### ISSUE TITLE
GetSize() and GetSpace()

### ISSUE THREAD

**Issue by wentaozhu** [SimpleITK/SimpleITK#441]
Is the GetSize() based on space of (1, 1, 1) if the image is of 3 dimensions, or based on space as GetSpace()?

**Comment by wentaozhu** [comment]
The reason why I asked the question is because the GetImageFromArray() and GetArrayFromImage() are not symmetric. GetArrayFromImage() makes the size of array the same as image size. But GetImageFromArray is not.

**Comment by wentaozhu** [comment]
And SetSpacing() for the GetArrayFromImage() does not work.

**Comment by richardbeare** [comment]
GetSize() returns dimension in voxels.

GetSpacing() returns the size of a single voxel.

If you import an image to a python? array, fiddle with it, then convert it back then it is usually necessary to use the CopyInformation method to copy all the original metadata, such as spacing, to the new image. There is no SetSpacing for arrays, as they are not image objects.

Have a look at:

http://simpleitk.github.io/SimpleITK-Notebooks/01_Image_Basics.html

**Comment by wentaozhu** [comment]
Thank you! I will take a look at it！
