### ISSUE TITLE
Writing TIFF image with compression in python with SimpleITK

### ISSUE THREAD

**Issue by rcasero** [SimpleITK/SimpleITK#444]
Is it possible to write a TIFF file using compression in the python interface of SimpleITK? I think the `useCompression` flag from the C++ API is not implemented

https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ImageFileWriter.html#details

```
Self& itk::simple::ImageFileWriter::Execute | ( | const Image & | ,
  |   | const std::string & | inFileName,
  |   | bool | useCompression
  | )

```
In principle, the idea would be having something like

```
import SimpleITK as sitk
sitk.WriteImage(imout, '/tmp/foo.tif',  useCompression=True)
```

This, however, may be an incomplete solution, as TIFF allows several types of compression, e.g. LZW (lossless), JPEG (lossy)...

**Comment by blowekamp** [comment]
Currently there is not what to do this. But this is a good idea for new feature.

**Comment by rcasero** [comment]
Thanks, @blowekamp . In case somebody needs that option, it can be done with [tifffile](https://github.com/blink1073/tifffile/blob/master/tifffile/tifffile.py), e.g.

```
import tifffile
tifffile.imsave(outfilename, im, compress='LZMA',
                resolution=(1000, 1000, 'CENTIMETER'))
```
