### ISSUE TITLE
How to apply a 2D transform on RGB (vector) image?

### ISSUE THREAD

**Issue by adizhol** [SimpleITK/SimpleITK#449]
Hi,

I have two RGB images, which I want to register, and I use their gray-scale images for the registration process. 
How can I efficiently apply this transform on the moving RGB image, without warping each channel separately?

Thanks,

**Comment by blowekamp** [comment]
The [ResampleImageFilter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ResampleImageFilter.html) can operate on multi-component  Images with the Vector pixel types (a.k.a RGB/Color images).

**Comment by adizhol** [comment]
Yes, but the transform dimension is 2,  where as the  image dimension is 3,
and I get an error from itk.

**Comment by blowekamp** [comment]
Please provide a minimal example of the problem you are encountering. Along with the meta-data for the image. 

From your description I expect your 2D Image to be represented like this:
```

In [1]: import SimpleITK as sitk

In [2]: img_2D_RGB = sitk.Image((10,10), sitk.sitkVectorUInt8, 3)

In [3]: print img_2D_RGB
VectorImage (0x7fd73faa1420)
  RTTI typeinfo:   itk::VectorImage<unsigned char, 2u>
  Reference Count: 1
  Modified Time: 777
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 0
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [10, 10]
  BufferedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [10, 10]
  RequestedRegion: 
    Dimension: 2
    Index: [0, 0]
    Size: [10, 10]
  Spacing: [1, 1]
  Origin: [0, 0]
  Direction: 
1 0
0 1

  IndexToPointMatrix: 
1 0
0 1

  PointToIndexMatrix: 
1 0
0 1

  Inverse Direction: 
1 0
0 1

  VectorLength: 3
  PixelContainer: 
    ImportImageContainer (0x7fd73faa15d0)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, unsigned char>
      Reference Count: 1
      Modified Time: 778
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7fd73faa1620
      Container manages memory: true
      Size: 300
      Capacity: 300
```

**Comment by adizhol** [comment]
I solved the problem by using isVector=True argument in ImageFromArray()

moving_rgb = sitk.Cast(sitk.GetImageFromArray(moving_strip_rgb,isVector=True), sitk.sitkVectorFloat32)

Thanks!
