### ISSUE TITLE
Cannot read mha files in parallel from C#

### ISSUE THREAD

**Issue by javier-alvarez** [SimpleITK/SimpleITK#45]
It could be related to this issue: http://www.itk.org/pipermail/insight-users/2014-June/050467.html

Nifti files can be read in parallel from C#.

Do you know what file formats are not thread safe?

**Comment by blowekamp** [comment]
There are a few different types of thread safety [1]. I am assuming you want conditionally thread safety, that is for example spawning many thread each reading files at the same time with different SimpleITK/ITK Readers.

No, I don't know which file formats are concurrent thread safe. It has to do with many 3-rd party libraries, and how they deal with globals and initializations. ITK's ImageIO model certainly should be concurrent thread safe, but not all the third party libraries are.

The MetaIO library is one that I would hope to be concurrent thread safe. This library is maintained by members of the ITK community [2], contributions to improve that library would be welcomed.

HTH,
Brad

[1] https://en.wikipedia.org/wiki/Thread_safety
[2] https://github.com/Kitware/MetaIO
