### ISSUE TITLE
repeating load data leads to very slow reading speed

### ISSUE THREAD

**Issue by chenjx1005** [SimpleITK/SimpleITK#452]
my SimpleITK==1.0.1
I write a simple script to see the read time of a ~300MB mhd file.

```
import time
import numpy as np
import SimpleITK as sitk

def load_itk_image(filename):
    itkimage = sitk.ReadImage(filename)
    numpyImage = sitk.GetArrayFromImage(itkimage)

    numpyOrigin = np.array(list(reversed(itkimage.GetOrigin())))
    numpySpacing = np.array(list(reversed(itkimage.GetSpacing())))

    return numpyImage, numpyOrigin, numpySpacing

N = 1
s = time.time()
for i in range(N):
    numpyImage, numpyOrigin, numpySpacing= load_itk_image("test.mhd")
print "itk", (time.time() -s) * 1.0 / N
```

when I set N = 1, the output is 
`itk 0.379504203796`
however when I set N = 5, the output become
`itk 3.00394558907`
It seems if I repeat read the data, the average reading speed reduce to 1/10 of the original speed.

**Comment by blowekamp** [comment]
Please see the Readme for additional information that should be reported. OS, package etc.

**Comment by blowekamp** [comment]
Thank you for providing the same code. I was unable to reproduce the issue on OS X or Linux with the PiPy 1.1.0 version for Python 2.7 64-bits.  I suspect it may be related to the memory allocations required and system dependent. I believe your code will peak at having 3X the image in memory. You can remove one by deleted variables in your loop:
```
for i in range(N):
    numpyImage, numpyOrigin, numpySpacing= load_itk_image("test.mha")
    del numpyImage, numpyOrigin, numpySpacing
```

**Comment by blowekamp** [comment]
I presume the issue has been resolved. Please feel free to reopen if needed, or post the solution that worked for you.
