### ISSUE TITLE
Read individual frames of multi-frame DICOM image

### ISSUE THREAD

**Issue by hackermd** [SimpleITK/SimpleITK#456]
In case of multi-frame images, `ImageFileReader` loads the entire pixel data element into memory at once when executed. However, this may not be desired under certain circumstances, for example if the image is very large. It would thus be great if one could read only a subset of frames from a file.

Is this supported in a way that I missed or is there a workaround?

It looks like GDCM supports reading parts of the pixel data element via [StreamImageReader](https://github.com/InsightSoftwareConsortium/ITK/blob/30206c0ec0cfecb6df9dec22e9a54e98463189db/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmStreamImageReader.h) and/or [ImageRegionReader](https://github.com/InsightSoftwareConsortium/ITK/blob/b437c28a01e4b76d35b740bdf49c2419808e6400/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageRegionReader.h). However, this functionality doesn't seem to be exposed as part of ITK's [GDCMImageIO](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/GDCM/src/itkGDCMImageIO.cxx).

**Comment by blowekamp** [comment]
Adding streaming support to SimpleITK's ImageFileRead is on the todo list. But I am not certain what the support of the GDCMImageIO is for this. I recommend asking the ITK comminity if GDCMImageIO supports this feature on the ITK forum: https://discourse.itk.org

**Comment by blowekamp** [comment]
There is an initial implementation of streamed reading for SimpleITK here #468. Additionally the ability to specify the which ImageIO to use for reading is added here, and that has been merged into the next branch for testing.


With these features implemented, if ITK supports this format than SimpleITK will. Additionally, if you compile SimpleITK with DCMTK over GDCM you can select that with the set ImageIO feature.

**Comment by blowekamp** [comment]
With the patch #468 and the updated GDCM in the ITK release this feature should not be reasonably implemented.
