### ISSUE TITLE
Inconsistencies between input types of sitk.Mask and sitk.MaskNegated

### ISSUE THREAD

**Issue by kevin-keraudren** [SimpleITK/SimpleITK#46]
https://github.com/SimpleITK/SimpleITK/blob/master/Code/BasicFilters/json/MaskImageFilter.json#L10
```
  "pixel_types" : "NonLabelPixelIDTypeList",
  "pixel_types2" : "IntegerPixelIDTypeList",
```

https://github.com/SimpleITK/SimpleITK/blob/master/Code/BasicFilters/json/MaskNegatedImageFilter.json
```
  "pixel_types" : "BasicPixelIDTypeList",
```

This means that you can have working code with `sitk.Mask`, and switching to `sitk.MaskNegated` will break.

```python
In [34]: sitk.Mask(sitk.Image(64, 64, sitk.sitkFloat32),sitk.Image(64, 64, sitk.sitkUInt8))
Out[34]: <SimpleITK.SimpleITK.Image; proxy of <Swig Object of type 'std::vector< itk::simple::Image >::value_type *' at 0x11d4ce900> >

In [35]: sitk.MaskNegated(sitk.Image(64, 64, sitk.sitkFloat32),sitk.Image(64, 64, sitk.sitkUInt8))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-35-36620ed8802d> in <module>()
----> 1 sitk.MaskNegated(sitk.Image(64, 64, sitk.sitkFloat32),sitk.Image(64, 64, sitk.sitkUInt8))

[...]/lib/python3.5/site-packages/SimpleITK/SimpleITK.py in MaskNegated(image, maskImage)
  45785
  45786     """
> 45787     return _SimpleITK.MaskNegated(image, maskImage)
  45788 class MaximumEntropyThresholdImageFilter(ImageFilter_0):
  45789     """

RuntimeError: Exception thrown in SimpleITK MaskNegated: /tmp/simpleitk20160218-43180-pucekk/Code/Common/include/sitkProcessObject.h:277:
sitk::ERROR: Unexpected template dispatch error!
```

Pixel types are defined here:
https://github.com/SimpleITK/SimpleITK/blob/master/Code/Common/include/sitkPixelIDTypeLists.h

Ideally, `sitk.MaskNegated` should support the same data types as `sitk.Mask`.

As a side note, there seems to be a typo in https://github.com/SimpleITK/SimpleITK/blob/master/Code/Common/include/sitkPixelIDTypeLists.h#L168
as "interger" sounds weird. Besides, this TypeList seems unused in the project:

```
grep -r IntergerLabelPixelIDTypeList *
Code/Common/include/sitkPixelIDTypeLists.h:typedef UnsignedIntegerPixelIDTypeList IntergerLabelPixelIDTypeList;
```

**Comment by blowekamp** [comment]
Hello,

Thank you for the report. I'll fix that typo real quick. Contribution for fixes are welcomed and encouraged.

The main reason for the different choice is due compilation time and size. Here is the o files on my system:
9.5M May 10 16:27 Code/BasicFilters/src/CMakeFiles//SimpleITKBasicFilters8.dir/sitkMaskImageFilter.cxx.o
729K May 10 16:26 Code/BasicFilters/src/CMakeFiles//SimpleITKBasicFilters8.dir/sitkMaskNegatedImageFilter.cxx.o

The additional support of "dual dispatch" along with the additional vector pixel types makes the compiled code more that 10X bigger!

When working with SimpleITK in Python you can easily add "==0" to the second argument to accomplish the same operations. While the MaskNegate filter can be convenient, it does not really add significant functionality to justify the addition cost.

**Comment by kevin-keraudren** [comment]
Thanks for explaining the templating limitations and pointing out the "==" operator!

```python
In [1]: %paste
import SimpleITK as sitk
import numpy as np

def mask_negated_eq():
    sitk.Mask(sitk.Image(64, 64, sitk.sitkFloat32), sitk.Image(64, 64, sitk.sitkUInt8)==0)

def mask_negated_abs():
    sitk.Mask(sitk.Image(64, 64, sitk.sitkFloat32),
              sitk.AbsoluteValueDifference(sitk.Image(64, 64, sitk.sitkUInt8),1))

def compare(img1,img2):
    return np.array_equal(sitk.GetArrayFromImage(img1), sitk.GetArrayFromImage(img2))

img = sitk.GetImageFromArray(np.random.randint(0,255,size=(33,29,57)))
mask = sitk.Cast(img > 128, sitk.sitkUInt8)

res1 = sitk.Mask(img, mask==0)
res2 = sitk.Mask(img, sitk.AbsoluteValueDifference(mask,1))

print(compare(res1,res2))

## -- End pasted text --
True

In [2]: %timeit mask_negated_eq
10000000 loops, best of 3: 21.8 ns per loop

In [3]: %timeit mask_negated_abs
10000000 loops, best of 3: 28.7 ns per loop
```

I'll go for the "==0"!
