### ISSUE TITLE
empty Inverse deformation field

### ISSUE THREAD

**Issue by Borda** [SimpleITK/SimpleITK#465]
Hello, I am facing a strange behavior, I want to invert a deformation field so I could do a reverse transformation on registered image pair, but the function returns empty field... 
see also [how to use simpleitk get inverse displacement field
](https://stackoverflow.com/questions/46697791/how-to-use-simpleitk-get-inverse-displacement-field)

```
import SimpleITK as sitk
import numpy as np

deform = np.zeros((150, 200, 2), dtype=float)
disp_field = sitk.GetImageFromArray(deform, isVector=True)

deform = sitk.GetArrayFromImage(disp_field)
print deform.shape
deform_inv = sitk.GetArrayFromImage(sitk.InverseDisplacementField(disp_field))
print deform_inv.shape
```
gives following:
```
(150, 200, 2)
(0, 0, 2)
```
for SimpleITK Version: 1.1.0 (ITK 4.13), Compiled: Mar 26 2018 15:04:35

**Comment by blowekamp** [comment]
You are not setting any of the parameters, and the size is defaulting to 0:
```
 sitk.InverseDisplacementField?
Signature: sitk.InverseDisplacementField(*args, **kwargs)
Docstring:
InverseDisplacementField(Image image1, VectorUInt32 size, VectorDouble outputOrigin, VectorDouble outputSpacing, unsigned int subsamplingFactor=16) -> Image
```
If you use the object oriented interface you can use the [SetReferenceImage](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1InverseDisplacementFieldImageFilter.html#a31550a55a42c0728498dcddb16c1ef9b) method.

**Comment by Borda** [comment]
Thanks for such quick response, but should not be there a warning message that you did not set some mandartory parameters or set some reasonable default values?
```
sitk.InverseDisplacementField(disp_field,
                              size=disp_field.GetSize(),
                              outputOrigin=(0.0, 0.0),
                              outputSpacing=(1.0, 1.0))
```

**Comment by blowekamp** [comment]
I agree this is not very good behavior, and may be un expected.

But it did the exact thing it was specified to do. It was just unexpected that the default size was 0. The other filters to invert displacement fields, InvertDisplacementFieldImageFilter and IterativeInverseDisplacementFieldImageFilter, may meet you expectations as the input and output domain always match. So it is a "feature" and not a :bug: of that the ITK filter was written so that you have to specify the output domain for the inversion :smile:

**Comment by blowekamp** [comment]
Thanks for the clear illustration of the problem. That does not look like good results. IT looks like you have some large deformations there that may contain folds, and may not be 1:1 mapping, so the assumption of the method may be violated.

I'd recommend posting the to the general ITK community at https://discourse.itk.org. This question is about details about the algorithm, and there are several other alternative algorithms to invert displacements field that may be better.

**Comment by Borda** [comment]
yes, I agree that there are some folds and I cannot simply use an interpolation from `scipy` for warping output image, but it is what I got from the demons registrations and somehow the `DisplacementFieldTransform` and `ResampleImageFilter` is able to handle it and gives me right warped images.

**Comment by Borda** [comment]
I was using `FastSymmetricForcesDemonsRegistrationFilter`

**Comment by blowekamp** [comment]
Please mode the topic to the wider ITK community.

**Comment by Borda** [comment]
OK, and what channel do you recommend? For example, I do not see an option to add the issue in [Jira](https://insightsoftwareconsortium.atlassian.net/projects/ITK/issues/ITK-3546?filter=allopenissues)

**Comment by blowekamp** [comment]
I'd recommend posting to the general ITK community at https://discourse.itk.org. You do not appear to have encountered a bug, but need help choosing the appropriate method and understand their requirements.
