### ISSUE TITLE
std::bind missing in SimpleITK build on mac

### ISSUE THREAD

**Issue by jcfr** [SimpleITK/SimpleITK#477]
xref https://issues.slicer.org/view.php?id=4439

We were wondering with this issue originally submitted by @pieper was fixed.

Cc: @lassoan

**Comment by blowekamp** [comment]
This issue is only encountered when the SimpleITK superbuild is not used. Using C++03 with OS X SDKs>10.6 is not supported due to missing TR1 methods.
