### ISSUE TITLE
No error, but cannot show image

### ISSUE THREAD

**Issue by JianJuly** [SimpleITK/SimpleITK#483]
**when i use  show function, there shows no error, but ImageJ cannot be invoked. Anyone can tell me what happend?**

```python
import SimpleITK as sitk

image = sitk.ReadImage('A2-2064594/d-00015.dcm')
sitk.Show(image, debugOn=True)
```

The outputs:

```python
Debug: In /opt/miniconda2/conda-bld/simpleitk_1521812412263/work/Code/IO/src/sitkShow.cxx, line 434: FindApplication search path: [ ./Fiji.app, /home/jianjunming/bin/Fiji.app, /opt/Fiji.app, /usr/local/Fiji.app ]
Result: /home/jianjunming/bin/Fiji.app/ImageJ-linux64


WARNING: In /opt/miniconda2/conda-bld/simpleitk_1521812412263/work/build/ITK/Modules/IO/Meta/src/itkMetaImageIO.cxx, line 659
MetaImageIO (0x2726000): Unsupported or empty metaData item 0008|0090 of type NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEfound, won't be written to image file

WARNING: In /opt/miniconda2/conda-bld/simpleitk_1521812412263/work/build/ITK/Modules/IO/Meta/src/itkMetaImageIO.cxx, line 659
MetaImageIO (0x2726000): Unsupported or empty metaData item 0008|1050 of type NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEfound, won't be written to image file

WARNING: In /opt/miniconda2/conda-bld/simpleitk_1521812412263/work/build/ITK/Modules/IO/Meta/src/itkMetaImageIO.cxx, line 659
MetaImageIO (0x2726000): Unsupported or empty metaData item 0020|1040 of type NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEfound, won't be written to image file

Debug: In /opt/miniconda2/conda-bld/simpleitk_1521812412263/work/Code/IO/src/sitkShow.cxx, line 514: Show command: '/home/jianjunming/bin/Fiji.app/ImageJ-linux64' '-eval' 'open("/tmp/TempFile-16126-0.mha"); rename("/tmp/TempFile-16126-0.mha");' 

```

**Comment by JianJuly** [comment]
it's solved adding cv2.waitKey() in the end. But why? So weird

**Comment by blowekamp** [comment]
Please copy and paste the error as ASCII, your image chops off the error message, and it content will not be searchable for future users to benefit.

Yes the interaction between SimpleITK and OpenCV is very odd. If you don't import cv2 does everything work normally?

If you have resolved you own issue please close the topic.

**Comment by JianJuly** [comment]
if i don't import cv2, and don't use cv2.waitKey(),  it doesn't work, just like my first comment. and if i use  cv2.waitKey(), that works well.

**Comment by blowekamp** [comment]
Please try to execute from the python program from the command line and not you GUI.

On Jun 4, 2018, at 10:08 PM, Jian <notifications@github.com<mailto:notifications@github.com>> wrote:


if i don't import cv2, and don't use cv2.waitKey(), it doesn't work, just like my first comment. and if i use cv2.waitKey(), that works well.

**Comment by JianJuly** [comment]
Wow, i make it to execute from the command line. But why not Pycharm?

**Comment by blowekamp** [comment]
I would look into how PyCharm handles the execution process. It seems like it is killing all subprocess when the execution of Python ends.

**Comment by JianJuly** [comment]
So what should i  do to use PyCharm to run this code?

**Comment by JianJuly** [comment]
@blowekamp Could u  help me with how to use PyCharm to run this code?

**Comment by blowekamp** [comment]
This is an issue with PyCharm, which I don't have access to. You addition of a pause at the end is a reasonable work around. 

I'll repeat what I believe is the PyCharm behavior:
> It seems like it is killing all subprocess when the execution of Python ends.

**Comment by JianJuly** [comment]
@blowekamp Thanks, I get it
