### ISSUE TITLE
Data\manifest.json does not exist

### ISSUE THREAD

**Issue by pranitapradhan91** [SimpleITK/SimpleITK#484]
Hello all,

I am new to SimpleITK. I am using Python 3.6.2 and have already installed SimpleITK using conda based distributions. I am trying to run a code (setup00 under Python) from this link [http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/](url). When I run the line `sitk.Show(sitk.ReadImage(fetch_data("SimpleITK.jpg")), "SimpleITK Logo", debugOn=True)` I get an error saying manifest.json not found. Do I have to download it from somewhere or am I missing something during installation?

**Comment by blowekamp** [comment]
Thank you for your interest in SimpleITK and SimpleITK Notebooks.

This is an issue with using the Notebooks. Please read the [readme](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/tree/master/Python) in that project and if the problem continues open an issue for that project.

**Comment by landodo** [comment]
The error message is as follows:
```
AssertionError: ERROR, E:\simpleitk-notebooks\Utilities\../Data\manifest.json does not exist
```
----
# Solution Steps:
1. Create '../Data/manifest.json' file.
2. from '../Utilities/downloaddata.py' copy Example json file contents to step 1 'manifest.json'

so the final content of the '../Data/manifest.json' file was obtained as:
```json
{
 "SimpleITK.jpg": {
  "sha512": "f1b5ce1bf9d7ebc0bd66f1c3bc0f90d9e9798efc7d0c5ea7bebe0435f173355b27df632971d1771dc1fc3743c76753e6a28f6ed43c5531866bfa2b38f1b8fd46"
 },
 "POPI/meta/00-P.mhd": {
  "url": "http://tux.creatis.insa-lyon.fr/~srit/POPI/Images/MetaImage/00-MetaImage.tar",
  "archive": "true",
  "sha512": "09fcb39c787eee3822040fcbf30d9c83fced4246c518a24ab14537af4b06ebd438e2f36be91e6e26f42a56250925cf1bfa0d2f2f2192ed2b98e6a9fb5f5069fc"
 },
 "CIRS057A_MR_CT_DICOM/readme.txt": {
  "archive": "true",
  "sha512": "d5130cfca8467c4efe1c6b4057684651d7b74a8e7028d9402aff8e3d62287761b215bc871ad200d4f177b462f7c9358f1518e6e48cece2b51c6d8e3bb89d3eef"
 }
}
```
