### ISSUE TITLE
N4BiasFieldCorrection Inputs do not occupy the same physical space!

### ISSUE THREAD

**Issue by bigbigbean** [SimpleITK/SimpleITK#487]
I just attempted to use sitk.N4BiasFieldCorrection for MRI pre-processing, as following:
`
import SimpleITK as sitk

 def fun():
    image = "06-t1c.nii.gz"
    img=sitk.ReadImage(image)
    img_data=sitk.Cast(img,sitk.sitkFloat32)
    img_mask = sitk.ReadImage("06-t1c_mask.nii.gz")
    img_mask = sitk.Cast(img_mask,sitk.sitkUInt8)
    print(img_data)
    print(img_mask)
    corrected_img = sitk.N4BiasFieldCorrection(img_data, img_mask)

    new_img=input('Enter the name of the Bias Field Corrected Image : ')
    sitk.WriteImage(corrected_img,new_img)
    print ("Finished N4 Bias Field Correction.....")

 if __name__=='__main__':
   fun()
`

The input_data and img_mask which were printed are totally same, including the origin and spacing.
 
However, it returned the error:
`RuntimeError: Exception thrown in SimpleITK N4BiasFieldCorrection: c:\d\vs14-win64-pkg\simpleitk-build\itk-prefix\include\itk-4.13\itkImageToImageFilter.hxx:241:
itk::ERROR: SubtractImageFilter(00000290C7A6F6E0): Inputs do not occupy the same physical space! 
InputImage Origin: [-1.7155302e+02, -8.9103783e+01, -8.1737661e+00], InputImage_1 Origin: [-4.4941406e+01, -3.2285156e+01, -1.1874999e+01]
	Tolerance: 4.6875000e-07
InputImage Spacing: [4.6875000e-01, 4.6875000e-01, 4.9999995e+00], InputImage_1 Spacing: [4.4941406e+01, 3.2285156e+01, 1.1874999e+01]
	Tolerance: 4.6875000e-07`
Thank you for your help.

**Comment by blowekamp** [comment]
Thank you for closing the issue. How did you resolve it?

**Comment by bigbigbean** [comment]
@blowekamp  Actually I did not fix this issue, but I found this code could run well on all other MR images, only one MR image would show this error. I tried to SetOrigin and SetSpacing but cannot fix this issue. Finally, I used Slicer software to do the N4 bias field correction for this MR image.   Maybe this MR image has something wrong? Do you know the reason? Thank you.

**Comment by blowekamp** [comment]
Seeing the full meta-data of the images may useful. We can see from the error message that inside the N4 Filter there is a subtraction filter which has inputs whose spacing does not match, we need to figure out why that is happending.

Can you share your images?

**Comment by bigbigbean** [comment]
[01-t1c.nii.gz](https://github.com/SimpleITK/SimpleITK/files/2118140/01-t1c.nii.gz)
@blowekamp Here is my image. 
Today, I have tried to run the same code on MacOS and Linux system, and they works well with no errors.
But on my Windows system, this image still reported the same error.

**Comment by blowekamp** [comment]
Can you please report the versions of SimpleITK you are using as per the Readme? https://github.com/SimpleITK/SimpleITK/blob/master/Readme.md

**Comment by bigbigbean** [comment]
SimpleITK Version: 1.1.0 (ITK 4.13)
