### ISSUE TITLE
Lua Bindings as a luarocks package

### ISSUE THREAD

**Issue by chsasank** [SimpleITK/SimpleITK#49]
Hi,

It's great that SimpleITK [has](https://itk.org/Wiki/SimpleITK/GettingStarted/Visual_guide_to_building_on_Linux#Using_Lua) lua bindings.
But It's not very clear how to use these bindings in another lua packages like torch. It'd be great if lua bindings are available as a luarocks package. Even better if it can deal with torch tensor. 

If such a package is not very hard to create, I can contribute if somebody is willing to guide me.

Thanks,
Sasank.

**Comment by dave3d** [comment]
I would be glad to make a more Lua portable package, although I haven't don't it before, so I don't really know how.  

I have updated the SimpleITK Lua build so that it now creates a module that can be dynamically loaded into a Lua interpreter.  That should show up on github soon.

Presumably making a luarocks package, shouldn't be that difficult, right?

**Comment by chsasank** [comment]
I have never made luarocks package myself, but it doesn't look difficult :
https://github.com/keplerproject/luarocks/wiki/Creating-a-rock

**Comment by blowekamp** [comment]
The topic has been merged into next for testing here is the commit: 46d821676a3ca1d54eb16fe3abbfe982ccdb9dee

The current next branch is a bit unstable today. If you want to try out the loadable module please checkout the above hash and it should be enabled by default. Let us know how it works for you.

Thanks!

**Comment by dave3d** [comment]
I’ll give it a whirl.

dave

David T. Chen, PhD                      [MSC contractor]
mailto:dchen@mail.nih.gov               http://lhncbc.nlm.nih.gov/personnel/david-chen
phone:301.435.3264<tel:301.435.3264>                      iphone:301.524.3174<tel:301.524.3174>
Office of High Performance Computing and Communications
National Library of Medicine

On Jul 1, 2016, at 9:35 AM, Bradley Lowekamp <notifications@github.com<mailto:notifications@github.com>> wrote:


The topic has been merged into next for testing here is the commit: 46d8216<https://github.com/SimpleITK/SimpleITK/commit/46d821676a3ca1d54eb16fe3abbfe982ccdb9dee>

The current next branch is a bit unstable today. If you want to try out the loadable module please checkout the above hash and it should be enabled by default. Let us know how it works for you.

Thanks!

**Comment by dave3d** [comment]
The latest next branch built and tested fine for me, including the Lua stuff.

dave

David T. Chen, PhD                      [MSC contractor]
mailto:dchen@mail.nih.gov               http://lhncbc.nlm.nih.gov/personnel/david-chen
phone:301.435.3264<tel:301.435.3264>                      iphone:301.524.3174<tel:301.524.3174>
Office of High Performance Computing and Communications
National Library of Medicine

On Jul 1, 2016, at 9:35 AM, Bradley Lowekamp <notifications@github.com<mailto:notifications@github.com>> wrote:


The topic has been merged into next for testing here is the commit: 46d8216<https://github.com/SimpleITK/SimpleITK/commit/46d821676a3ca1d54eb16fe3abbfe982ccdb9dee>

The current next branch is a bit unstable today. If you want to try out the loadable module please checkout the above hash and it should be enabled by default. Let us know how it works for you.

Thanks!

**Comment by dave3d** [comment]
I have made a first pass at a luarocks package of SimpleITK.  You can find it here:  https://github.com/SimpleITK/SimpleITKLuaRock

Please try it out and let me know any issues that may arise.

**Comment by blowekamp** [comment]
Please find a first version of the rock spec here:
https://github.com/SimpleITK/SimpleITKLuaRock/releases
