### ISSUE TITLE
How to disable warning in simpleitk.ReadImage in Python

### ISSUE THREAD

**Issue by 01bui** [SimpleITK/SimpleITK#491]
I have a 3D tiff file written from ImageJ. I get these warnings in the terminal when reading this tiff. 

> TIFFReadDirectory: Warning, Unknown field with tag 50838 (0xc696) encountered.
> TIFFReadDirectory: Warning, Unknown field with tag 50839 (0xc697) encountered.

Is it possible to not printing these warnings to the console?

Thanks!

**Comment by blowekamp** [comment]
You can ignore those warning. Those are private TIFF Tags added by ImageJ. Those warning are emitted by liftiff, I don't see any way to suppress them in ITK or SimpleITK. This feature would need to be added to ITK.

**Comment by YannLePoul** [comment]
Just for those who want's to still not see these warnings in python, one solution is to redirect the stderr output of libtiff as exampled [here](https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/).

**Comment by aksg87** [comment]
@YannLePoul 

The code in that blog seems out of date when I tried using it. Wish we could pass an argument into sitk to turn off warnings.

**Comment by Elektropepi** [comment]
You can disable all warning displays of SimpleITK by calling [SetGlobalWarningDisplay](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ProcessObject.html#a99d3df8ad7db82bc587edaa8706d135a).

In python, you simply call `sitk.ProcessObject_SetGlobalWarningDisplay(False)`.

As an example, I'm reading DICOM directories recursively, therefore there are some directories that don't contain any DICOM series and the warning `No Series can be found, make sure your restrictions are not too strong` occurs many times. Therefore I'm temporarily disabling those warnings so important warnings don't get lost in all the output:

```python
    for sub_folder_path, _, _ in os.walk(folder_path):
        sitk.ProcessObject_SetGlobalWarningDisplay(False)
        file_names = sitk.ImageSeriesReader.GetGDCMSeriesFileNames(sub_folder_path)
        sitk.ProcessObject_SetGlobalWarningDisplay(True)
        if len(file_names) < 1:
            continue
        # (...) process file_names
```

**Comment by yliu7366** [comment]
Tested in SimpleITK 2.3.1 and calling sitk.ProcessObject_SetGlobalWarningDisplay(False) does **not** suppress TIFFReadDirectory warning messages such as TIFFReadDirectory: Warning, Unknown field with tag 51123 (0xc7b3) encountered.

**Comment by blowekamp** [comment]
Please create a new issue, and don't revive a issue closed for years.
