### ISSUE TITLE
architecture compatability, unity c# hololens

### ISSUE THREAD

**Issue by kpchad** [SimpleITK/SimpleITK#498]
not sure if it has been tried yet, but I'm trying to use this architecture in a Hololens app. 

when I use the x64 build, it runs perfectly within Unity, but creates an error when publishing app:

> metadata file '...\GeneratedProjects\UWP\Assembly-CSharp\bin\x86\Debug\Assembly-CSharp.dll' could not be found

It makes sense that something architecture related would get messed up since the build needs to be configured to x86 for Hololens.

if I use the x86 build though, I get an error when I run it in Unity: 

> Failed to load 'Assets/DICOM_Tools/SimpleITK-1.0.0-CSharp-win32-x86/SimpleITKCSharpNative.dll', expected x64 architecture, but was x86 architecture. You must recompile your plugin for x64 architecture.

If I ignore and just try to build the app in visual studio, I get the 1st error still.

using Unity 2017.4.6f1; VS 2017; SimpleITK 1.1.0 CSharp

**Comment by blowekamp** [comment]
Did you add both the native and managed libraries to your project:
https://itk.org/Wiki/SimpleITK/GettingStarted/A_visual_guide_to_SimpleITK_with_CSharp

You last error message refers to 1.0.0, but you seem to indicate that you are trying to use 1.1.0. Please verify all folders and paths are correct.

**Comment by kpchad** [comment]
You're right, I was using 1.0.0 for the x86 build (the c# sourceforge link on [this ](http://simpleitk.readthedocs.io/en/next/Documentation/docs/source/installation.html)page leads to 1.0.0 still)

I switched it out now though, added the native and managed libraries properly. I got the same error in Unity, and initially got the same error trying to build in visual studio as well. Then I checked the box for "allow /unsafe code" then it appeared to make more progress before giving me this error:

1>  "D:\...\App\Unity\Tools\AssemblyConverter.exe" -platform=uap -lock="D:\...\App\DICOMHL_OS\project.lock.json" -bits=32 -configuration=Debug -removeDebuggableAttribute=False -uwpsdk=10.0.17134.0 -path="." -path="C:\Program Files\Unity\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\dotnet\x86\Debug" "D:\...\App\DICOMHL_OS\Assembly-CSharp.dll" "D:\...\App\DICOMHL_OS\UnityEngine.TextRenderingModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.TerrainPhysicsModule.dll" "D:\...\UnityEngine.TerrainModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.TilemapModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.UIElementsModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.SharedInternalsModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.ScreenCaptureModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.SpriteMaskModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.StyleSheetsModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.SpriteShapeModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.VideoModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.VehiclesModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.UnityWebRequestWWWModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.VRModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.WindModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.WebModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.UnityAnalyticsModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.UNETModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.UIModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.UnityConnectModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.UnityWebRequestTextureModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.UnityWebRequestModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.UnityWebRequestAudioModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.PhysicsModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.AssetBundleModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.ARModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.AnimationModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.AudioModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.CrashReportingModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.CoreModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.ClothModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.AIModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.AccessibilityModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.JSONSerializeModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.InputModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.ParticlesLegacyModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.Physics2DModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.PerformanceReportingModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.ParticleSystemModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.GameCenterModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.dll" "D:\...\App\DICOMHL_OS\UnityEngine.DirectorModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.GridModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.IMGUIModule.dll" "D:\...\App\DICOMHL_OS\UnityEngine.ImageConversionModule.dll" "D:\...\App\DICOMHL_OS\Newtonsoft.Json.dll" "D:\...\App\DICOMHL_OS\UnityEngine.Timeline.dll" "D:\...\App\DICOMHL_OS\nunit.framework.dll" "D:\...\App\DICOMHL_OS\UnityEngine.UI.dll" "D:\...\App\DICOMHL_OS\UnityEngine.SpatialTracking.dll" "D:\...\App\DICOMHL_OS\UnityEngine.HoloLens.dll" "D:\...\App\DICOMHL_OS\UnityEngine.StandardEvents.dll" "D:\...\App\DICOMHL_OS\UnityEngine.Networking.dll" "D:\...\App\DICOMHL_OS\GLTFSerializationUWP.dll" "D:\...\App\DICOMHL_OS\SimpleITKCSharpManaged.dll"
1>  Failed to fix references for field System.Runtime.InteropServices.HandleRef itk.simple.ProcessObject::swigCPtr
1>  Failed to fix references for type itk.simple.ProcessObject
1>  System.Exception: Failed to resolve System.Runtime.InteropServices.HandleRef
1>     at Unity.ModuleContext.Retarget(TypeReference type, GenericContext context)
1>     at Unity.FixReferencesStep.Visit(FieldDefinition field, GenericContext context)
1>     at Unity.FixReferencesStep.Visit(TypeDefinition type)
1>     at Unity.TypeDefinitionDispatcher.DispatchType(TypeDefinition type)
1>     at Unity.TypeDefinitionDispatcher..ctor(ModuleDefinition module, ITypeDefinitionVisitor visitor)
1>     at Unity.FixReferencesStep.ProcessModule()
1>     at Unity.ModuleStep.Execute()
1>     at Unity.FixReferencesStep.Execute()
1>     at Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
1>     at Unity.Operation.Execute()
1>     at Unity.Program.Main(String[] args)
1>D:\...\App\DICOMHL_OS\DICOMHL_OS.csproj(458,5): error MSB3073: The command "(same list of dlls as above)" exited with code 1.
1>
1>Build FAILED.
1>
1>"D:\...\App\DICOMHL_OS\DICOMHL_OS.csproj" (default target) (1) ->
1>(ModifyAppXPackage target) -> 
1>  D:\...\App\DICOMHL_OS\DICOMHL_OS.csproj(458,5): error MSB3073: The command "(same list of dlls as above)" exited with code 1.
1>
1>    0 Warning(s)
1>    1 Error(s)
1>

**Comment by blowekamp** [comment]
This issue appears to be related:
https://github.com/swig/swig/issues/423

**Comment by blowekamp** [comment]
Thank you for your question. I hope your issue has been resolved now. Please feel free to reopen the issue as needed.
