### ISSUE TITLE
Controlling precision for computations

### ISSUE THREAD

**Issue by david-hoffman** [SimpleITK/SimpleITK#503]
Is it possible to control the precision used for computations in the SimpleITK python wrapper?

For instance I'm trying to compute the gradient magnitude of an image:
```python
import SimpleITK as sitk
img = sitk.ReadImage("myfile.mrc")
grad = sitk.GradientMagnitudeRecursiveGaussianImageFilter()
g = grad.Execute(img)
```

But I get a memory error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-5e855a54a8db> in <module>()
----> 1 g = grad.Execute(img)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\SimpleITK\SimpleITK.py in Execute(self, *args)
  31666
  31667         """
> 31668         return _SimpleITK.GradientMagnitudeRecursiveGaussianImageFilter_Execute(self, *args)
  31669
  31670 GradientMagnitudeRecursiveGaussianImageFilter_swigregister = _SimpleITK.GradientMagnitudeRecursiveGaussianImageFilter_swigregister

RuntimeError: Exception thrown in SimpleITK GradientMagnitudeRecursiveGaussianImageFilter_Execute: c:\b\3.6-64\itk-prefix\include\itk-4.13\itkImportImageContainer.hxx:199:
Failed to allocate memory for image.
```

It seems as though the default is `double` precision, but I'm wondering if there's a way to force the computation to use `single` precision.

**Comment by blowekamp** [comment]
That particular filer [produces](https://github.com/SimpleITK/SimpleITK/blob/master/Code/BasicFilters/json/GradientMagnitudeRecursiveGaussianImageFilter.json#L8) an image of `float`. It it a bit of a memory hog with its [ITK implementation](https://itk.org/Doxygen/html/classitk_1_1GradientMagnitudeRecursiveGaussianImageFilter.html), but even at the ITK level for the filter it does not provide control of the internal types.

How much memory does your system have? How what is the dimensions of your image and what it the component type when read?

**Comment by david-hoffman** [comment]
The system has 512 GB. The image output is:

```
Image (00000231600E40A0)
  RTTI typeinfo:   class itk::Image<unsigned char,3>
  Reference Count: 1
  Modified Time: 944
  Debug: Off
  Object Name:
  Observers:
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 934
  UpdateMTime: 943
  RealTimeStamp: 0 seconds
  LargestPossibleRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [12500, 520, 6674]
  BufferedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [12500, 520, 6674]
  RequestedRegion:
    Dimension: 3
    Index: [0, 0, 0]
    Size: [12500, 520, 6674]
  Spacing: [1, 1, 1]
  Origin: [0, 0, 0]
  Direction:
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix:
1 0 0
0 1 0
0 0 1

  PointToIndexMatrix:
1 0 0
0 1 0
0 0 1

  Inverse Direction:
1 0 0
0 1 0
0 0 1

  PixelContainer:
    ImportImageContainer (0000023161507460)
      RTTI typeinfo:   class itk::ImportImageContainer<unsigned __int64,unsigned char>
      Reference Count: 1
      Modified Time: 940
      Debug: Off
      Object Name:
      Observers:
        none
      Pointer: 0000023163364040
      Container manages memory: true
      Size: 43381000000
      Capacity: 43381000000
```

**Comment by blowekamp** [comment]
So your input image is 43GB of uint8 ( one byte). For a single 40byte image of "float" the image would be 172 GB. So you can only have a couple copy of an image this size around before running out of memory, if there a image of the gradient ( which is likely internal for this filter ) you'd be out of memory.

You may be able to run the [RecusiveGaussian ](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1RecursiveGaussianImageFilter.html) followed by the[ GradientMagnitude](https://itk.org/Doxygen/html/classitk_1_1GradientMagnitudeImageFilter.html) this combination should not create an image for the gradient.

This image is likely a noise electron microscopy image. Do you really need to do these operations at full resolution? You could use the [BinShrink](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1BinShrinkImageFilter.html) filter to reduce the resolution. Or you could operator on smaller chunks of the image at a time.

**Comment by david-hoffman** [comment]
Ok, that answers my question, thanks!
