### ISSUE TITLE
ImportError: nomodule named '_SimpleITK'

### ISSUE THREAD

**Issue by haochengd** [SimpleITK/SimpleITK#513]
![error](https://user-images.githubusercontent.com/35961166/42684786-6e78de42-8691-11e8-8076-f4623efdb393.png)
I have installed SimpleITK in the Anaconda Environment using conda install -c simpleitk simpleitk. 
I imported it into the Python Console using "Import SimpleITK" and got the error showed in above image.
I tried to reinstall in a new environment but it failed too.
Any suggestions are highly appreciated.

**Comment by blowekamp** [comment]
Python 3.5.2 is a little old, there have been several patch release for 3.5 since then. And Anaconda is as version 4.5.8 while you have 4.2. So I am going to assume that your Anaconda is out of date and causing problems.

 Are you sure you don't what to use Python 3.6?

- What SimpleITK Python package got downloaded and installed?

Here are some steps to update your conda and create a new update environment:
```
$ conda update conda
$ conda create -n sitk python=3.5
$ activate sitk
$ conda update --all
$ conda install -c simpleitk simpleitk
```

**Comment by blowekamp** [comment]
Can you please run `conda  list`?

You could also try installing SimpleITK via `python -m pip install SimpleITK` from PyPi.

**Comment by haochengd** [comment]
![image](https://user-images.githubusercontent.com/35961166/42700709-d93aa462-86c4-11e8-949a-4800703a8766.png)

**Comment by blowekamp** [comment]
Ahh! You can getting your packages from several unusual places or mirror of places. Conda SimpleITK depends on a couple other conda packages for library dependencies. There is an incompatibility with some of the mirrors you have. I have seen this with using SimpleITK against the conda forge builds before. It appears that you have a mirror of conda forge. I'd recommend only using the official upstream conda packages, not conda-forge and not unofficial mirrors.

Here is my clean env I just created:
```
# Name                    Version                   Build  Channel
certifi                   2018.4.16                py36_0
jpeg                      9b                   hb83a4c4_2
libpng                    1.6.34               h79bbb47_0
libtiff                   4.0.9                hb8ad9f9_1
pip                       10.0.1                   py36_0
python                    3.6.6                hea74fb7_0
setuptools                39.2.0                   py36_0
simpleitk                 1.1.0            py36h6538335_0    simpleitk
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wheel                     0.31.1                   py36_0
wincertstore              0.2              py36h7fe50ca_0
zlib                      1.2.11               h8395fce_2
```

You may have better luck with the pip version of SimpleITK as is has no dependencies.

**Comment by haochengd** [comment]
You are right. I reinstalled the anaconda and use the default source and it works now. Thanks!

**Comment by blowekamp** [comment]
Were you able to get SimpleITK working?

**Comment by haochengd** [comment]
It works. Thanks a lot!
