### ISSUE TITLE
How  can convert ct  .raw/.mhd file to dicom series

### ISSUE THREAD

**Issue by blakeliu** [SimpleITK/SimpleITK#514]

**Comment by blowekamp** [comment]
Thank you for your question. I hope your issue has been resolved now. Please feel free to reopen the issue as needed.

**Comment by alexofficial** [comment]
> 
> 
> [This example](https://simpleitk.readthedocs.io/en/master/Examples/DicomSeriesFromArray/Documentation.html) should get you there. You will need to modify it to read the mhd file (a single line with `ReadImage` instead of the three lines that create an image from a numpy array).
> 
> Please close the issue if this solves your question.

Hey @zivy, the link does not work.

**Comment by zivy** [comment]
Hello @alexofficial,
Thanks for letting us know. I have updated the link in the original post to the current example location.

**Comment by richardbeare** [comment]
Guys,
Here's a tool, [karawun](https://github.com/DevelopmentalImagingMCRI/karawun), I've put together for conversion of surgical workups back to dicom and import to the surgical navigation suite. It uses SimpleITK for the image input and pydicom for dealing with the complex tags. We typically use nifti as our starting point, and I would be interested to hear whether mhd works out of the box. One limitation is that it requires a dicom to act as a source for the expected tags. This is not a problem in the clinical setting. You could experiment using the dicom we provide as an example. As a bonus, it does some of the quantitative dicom - tract files and label images as well as frames of reference for coregistered data.
