### ISSUE TITLE
Error while Running the Registration Method SimpleITK (Ver:1.1.0)

### ISSUE THREAD

**Issue by Skp80** [SimpleITK/SimpleITK#516]
Hi, 
I am trying to run the regular gradient descent method in the SimpleITK algorithm, unfortunately I am getting the following error message:
**RuntimeError: Exception thrown in SimpleITK ImageRegistrationMethod_Execute: ..\..\..\..\..\Users\dashboard\Miniconda3\conda-bld\simpleitk_1520629929391\work\Wrapping\Python\sitkPyCommand.cxx:135:
sitk::ERROR: There was an error executing the Python Callable**.

The images are tiff images of 2 dimensional time. 
The Data types are Float32 bit.
**The Code is as below:**
ref_image = sitk.Cast(sitk.GetImageFromArray(ref_read), sitk.sitkFloat32)
##sitk.Show(ref_image)

prod_image = sitk.Cast(sitk.GetImageFromArray(prod_read), sitk.sitkFloat32)
##sitk.Show(prod_image)
R = sitk.ImageRegistrationMethod()
print(R.SetInitialTransform)
R.SetMetricAsCorrelation()
R.SetOptimizerAsRegularStepGradientDescent(learningRate=1.0,
                                           ##minStep=1e-6,
                                           minStep=0.065,
                                           numberOfIterations=100,
                                           gradientMagnitudeTolerance=1e-8,
                                           )
R.SetOptimizerScalesFromIndexShift()
tx = sitk.CenteredTransformInitializer(fixed, moving, sitk.Similarity2DTransform())
R.SetInitialTransform(tx)
R.SetInterpolator(sitk.sitkLinear)
R.AddCommand( sitk.sitkIterationEvent, lambda: command_iteration(R) )
R.SetDebug = 'on'
outTx = R.Execute(fixed,  moving)
print(outTx)

**Comment by blowekamp** [comment]
There error indicates there is a problem with SimpleITK calling a Python callback. Here is where the call back is created:

> R.AddCommand( sitk.sitkIterationEvent, lambda: command_iteration(R) )

Is the function "command_iteration" defined? Is there a problem in the call of this method?

**Comment by blowekamp** [comment]
Thank you for your question. I hope your issue has been resolved now. Please feel free to reopen the issue as needed.
