### ISSUE TITLE
Using TransformPoint to map points in the spatial domain of the fixed image to points in the spatial domain of the moving image

### ISSUE THREAD

**Issue by TannerSorensen** [SimpleITK/SimpleITK#532]
I am having a problem using the `TransformPoint` method of the class `SimpleITK.DisplacementFieldTransform` to map points in the spatial domain of the fixed image to points in the spatial domain of the moving image. 

I attach a Jupyter Notebook [demons_example.zip](https://github.com/SimpleITK/SimpleITK/files/2234758/demons_example.zip) containing the code (also readable in a markdown file [demons_attempt_01.zip](https://github.com/SimpleITK/SimpleITK/files/2234752/demons_attempt_01.zip)). The code is based on the [Demons registration example](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/66_Registration_Demons.ipynb). 

Basically, I am registering `moving_img` to `fixed_img` using `SimpleITK.DiffeomorphicDemonsRegistrationFilter`. Both images are single sagittal images of the head and neck extracted from a sequence of dynamic MRI. I am trying to register `moving_img` to `fixed_img` and to use the resulting transform to map manually annotated contours from the spatial domain of `fixed_img` to the spatial domain of `moving_img`.

When I apply the transform to `moving_img`, the transformed image matches `fixed_img` (at least qualitatively). However, when I apply the transform to points in the spatial domain of `fixed_img`, the transformed points do not map correctly to the spatial domain of `moving_img`. Basically, points on one structure in`fixed_img` do not map to points on the corresponding structure in `moving_img`. 

The figure below shows a reasonable match between the transformed moving image and the fixed image (see bottom right, where the fixed and result images are compared using `SimpleITK.Compose`). However, the transformed points (bottom center) are not transformed correctly. Am I missing something conceptual here, or is it simply just that the demons registration is not right for my application? 

![output_12_2](https://user-images.githubusercontent.com/6401083/43306537-61b577a2-9130-11e8-8024-ba175861347a.png)

**Comment by blowekamp** [comment]
How did you invert your transform? The one from registration is from `moving_image`->`fixed_image`. But your atlas is on the fix image.

**Comment by TannerSorensen** [comment]
Thank you @blowekamp for the reply. In my original post above, I had not inverted the transform, thinking that the spatial domain of the fixed image was mapped to the spatial domain of the moving image to perform the registration (how it works in Elastix), not the reverse. 

I tried two approaches to fix the issue I am having, but I couldn't get either to work for me. If anyone has insight into this issue, that would be helpful!

# Finding the inverse

I tried inverting the transform using the following function, where `tfm` is the `SimpleITK.DisplacementFieldTransform` object. 

```python
def invert_tfm(tfm):
    
    # initialize the inverse transform with inverse displacement field
    disp_fld = tfm.GetDisplacementField()
    inv_tfm = sitk.DisplacementFieldTransform(sitk.InvertDisplacementField(disp_fld))
    
    # set fixed parameters
    # https://simpleitk.github.io/SPIE2018_COURSE/spatial_transformations.pdf
    field_size = disp_fld.GetSize()
    field_origin = disp_fld.GetOrigin()
    field_spacing = disp_fld.GetSpacing()
    field_direction = disp_fld.GetDirection()
    inv_tfm.SetFixedParameters(field_size+field_origin+field_spacing+field_direction)
    
    return inv_tfm
```

The inverse transform appeared not to map the fixed image coordinates to moving image coordinates very well. The inverse was very nearly the identity transform.

<img width="615" alt="screen shot 2018-07-30 at 11 26 31 pm" src="https://user-images.githubusercontent.com/6401083/43441702-8f6778ee-9450-11e8-996a-369ab145e1e7.png">

See [demons_example_inverse.zip](https://github.com/SimpleITK/SimpleITK/files/2244082/demons_example_inverse.zip) for the code.

# Changing the registration problem

As my goal is just to transform the atlas contours to the source image, I am free to change the nature of the registration problem from the way I formulated it in the original post of this issue. Having difficulty with estimating the inverse, I then tried reversing the direction of the registration problem. That is, I switched `fixed_img` and `moving_img` and registered the atlas image to the source image. In this experiment, I did not need to obtain the inverse of the transform, since the transform obtained through registration mapped spatial coordinates of the atlas image directly to spatial coordinates of the source image. 

Although the registration itself was of poorer quality in this direction, the transform seemed not to work in the same way on individual points as it did on the images.

<img width="616" alt="screen shot 2018-07-30 at 11 49 33 pm" src="https://user-images.githubusercontent.com/6401083/43442598-46dab264-9453-11e8-8cad-b851c88475a5.png">

See [demons_example_atlas2source.zip](https://github.com/SimpleITK/SimpleITK/files/2244084/demons_example_atlas2source.zip) for the code.

**Comment by blowekamp** [comment]
I think you have not updated your labels... the transformation still looks backwards to me. You may find this introductory document useful:
https://simpleitk.readthedocs.io/en/master/Documentation/docs/source/registrationOverview.html

**Comment by TannerSorensen** [comment]
I update this thread with a solution I found. I believe that my main mistake had to do with the points making up the atlas contours: I specified them in pixel units, rather than physical units. Converting the coordinates to physical units appeared to solve my problem. 

The parameterization of the diffeomorphic demons registration still need to be configured, but the attached code demonstrates that the transformation I am applying to the atlas contours is at least doing its job. 

[demons_example.zip](https://github.com/SimpleITK/SimpleITK/files/2278526/demons_example.zip)

**Comment by blowekamp** [comment]
Thanks for updating with your solution.

**Comment by TannerSorensen** [comment]
No problem!

**Comment by TannerSorensen** [comment]
Here is the visualization of the solution:

![solution](https://user-images.githubusercontent.com/6401083/43971125-ccc19684-9c84-11e8-9cde-8b4910685080.png)

The displacement field:

![displacement_field](https://user-images.githubusercontent.com/6401083/43971157-ebb9a3ec-9c84-11e8-82ea-330ebaf76fdb.png)

**Comment by zivy** [comment]
Hello @TannerSorensen,

I wanted to ask whether we could use your data and use-case in our Jupyter notebooks examples? 

It would be a nice addition to the demons notebook as it illustrates the use of index space for plotting and physical space for transforming data/points. Also the images are interesting. If this is ok then I will create an addition to the demons notebook and list you as a co-committer.

**Comment by BenjaminAgthe** [comment]
Hello channel,

I have a similar problem. My transformations are working for images, but not for points. I have gone threw the solution of you @TannerSorensen, thank you very much. My questions are: 

is the transformation calculated in the spacial or physical domain usually!? 

@TannerSorensen The factor of 200/84: Is that the inverted spacing of the image? 

the pictures show the initially misaligned images, images after registration and the registered points

Thanks in advance


![Misaligned_images](https://user-images.githubusercontent.com/39301654/61784941-f7189480-ae0a-11e9-8fc3-dbadc449bb78.png)

![registered](https://user-images.githubusercontent.com/39301654/61784942-f7189480-ae0a-11e9-9847-b83f156d8970.png)

![registered points](https://user-images.githubusercontent.com/39301654/61784943-f7189480-ae0a-11e9-9e2f-9fc8d8e0e4d0.png)

**Comment by blowekamp** [comment]
Please create a new issue for your problem. The transforms operate in physical space not index space. This should be explained on the fundamental concepts section of the documentation: https://simpleitk.readthedocs.io/en/master/Documentation/docs/source/fundamentalConcepts.html

**Comment by BenjaminAgthe** [comment]
Okay i did. https://github.com/SimpleITK/SimpleITK/issues/792 

@TannerSorensen The factor 200/84 is your inverted spacing!?

**Comment by TannerSorensen** [comment]
Yes. The field of view is 200 mm x 200 mm and the images are 84 pixels x 84
pixels.

Best,

Tanner
