### ISSUE TITLE
SimpleITK Show command environment variable on windows doesn't work

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#537]
On windows, when Fiji is in the expected location (e.g. C:\Users\Ziv Yaniv\Fiji.app) the show command works. 

When placing the Fiji directory in an arbitrary location and setting the SITK_SHOW_COMMAND environment variable to point to that location the Show command fails. This issue was reported in [this discourse discussion](https://discourse.itk.org/t/problem-linking-simpleitk-with-imagej/1156/5).

**Comment by dave3d** [comment]
Address in commit dc5c1a1dc511b7e137acd206ee20fe40406838de

**Comment by blowekamp** [comment]
@dave3d is this fix in the release or master branch?

**Comment by dave3d** [comment]
@blowekamp It's on release.
