### ISSUE TITLE
Support for Python 3.7

### ISSUE THREAD

**Issue by jpowie01** [SimpleITK/SimpleITK#551]
### Description
PyPI package supports many versions of Python (up to 3.6). But it doesn't support Python 3.7 (released on 2018-06-27) because packages for this version were not published yet (latest update on 2018-03-26). Is there a plan to support it? Or maybe will you wait for the next release cycle of SimpleITK? If so, when will it happen?

It blocks my project's (and probably many more) upgrade to the newest version of Python.

**Link to PyPI:** https://pypi.org/project/SimpleITK/#files
**Python 3.7 changelog:** https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-0-final

### Reproduction:
1. Install Python 3.7.
2. Try to install SimpleITK using pip.
`pip install SimpleITK`

**Comment by blowekamp** [comment]
Thank you for letting us know that SimpleITK for 3.7 is important to you project. We certainly plan on supporting Python 3.7. I would expect the pypi source tar ball to work with 3.7 though I haven't tested it, and it would take time to compile and build.

The plan was to wait until the 1.2 release to add 3.7 wheels, but that release is running later than initially planned. I'll look into creating 3.7 wheels.

**Comment by jpowie01** [comment]
Great! Thanks for your help :)

**Comment by blowekamp** [comment]
There are not wheels for Python 3.7 on PyPI: https://pypi.org/project/SimpleITK/#files

Enjoy!

**Comment by dave3d** [comment]
You mean "There are NOW wheels"

**Comment by blowekamp** [comment]
😱
Thanks for picking that typo up! 

Please Enjoy the new Python 3.7 Wheels!
