### ISSUE TITLE
Making Background of the image transperant

### ISSUE THREAD

**Issue by Skp80** [SimpleITK/SimpleITK#558]
Would like to know if there are any methods to convert a 2d image background to be transparent.  Like the scenario mentioned in stackoverflow article below:
https://stackoverflow.com/questions/40527769/removing-black-background-and-make-transparent-from-grabcut-output-in-python-opencv-python

**Comment by dave3d** [comment]
I don't of any direct method to do it, but you could use a threshold to select the background, and than put that into the alpha channel.

**Comment by blowekamp** [comment]
Is this questions asking "How do I write an image with an alpha channel"?

**Comment by Skp80** [comment]
No this was to use any segmentation methods to make the background of the image transparent. Like the one provided in the example:
https://stackoverflow.com/questions/40527769/removing-black-background-and-make-transparent-from-grabcut-output-in-python-opencv-python

Are there any methods to make the background of the image transparent.

**Comment by blowekamp** [comment]
Perhaps you are looking for image fusion method to combine multiple images with an "alpha" channel then?

**Comment by Skp80** [comment]
yes, somewhat similar.

**Comment by Skp80** [comment]
Any examples related to this scenario would be helpful....

**Comment by Skp80** [comment]
thanks dave, this works. Thanks for helping with an example.
