### ISSUE TITLE
How to make operations with SimpleITK objects?

### ISSUE THREAD

**Issue by JianJuly** [SimpleITK/SimpleITK#560]
like ABS,  square root, union or something like this.

**Comment by zivy** [comment]
I believe what you want is sitk.Abs(), sitk.Sqrt() (see the [Doxygen documentation](https://itk.org/SimpleITKDoxygen/html/namespaceitk_1_1simple.html) for the object oriented and procedural interfaces), and the bitwise image operators shown in [this Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/02_Pythonic_Image.ipynb).

If this addresses your issue, please close it or provide additional details.

**Comment by JianJuly** [comment]
Problem solved，Thank you  : )
