### ISSUE TITLE
How to resample sitk_image to a new spacing?

### ISSUE THREAD

**Issue by zst1992** [SimpleITK/SimpleITK#561]
I tried to resample sitk image to a new spacing using the following code
```
import numpy as np

import SimpleITK as sitk

image = sitk.ReadImage(path_to_sitk_image)
resample = sitk.ResampleImageFilter()
resample.SetInterpolator = sitk.sitkLinear
resample.SetOutputDirection = image.GetDirection()
resample.SetOutputOrigin = image.GetOrigin()
new_spacing = [1, 1, 1]
resample.SetOutputSpacing = new_spacing

orig_size = np.array(image.GetSize(), dtype=np.int)
orig_spacing = image.GetSpacing()
new_size = orig_size*(orig_spacing/new_spacing)
new_size = np.ceil(new_size).astype(np.int) #  Image dimensions are in integers
new_size = [int(s) for s in new_size]
resample.SetSize = new_size

newimage = resample.Execute(image)
```

However, it returned "Kernel died, restarting" when ran resample.Execute(). Thank you very much.

**Comment by zivy** [comment]
You have two Python bugs (overriding a method instead of providing a value):
```
resample.SetOutputSpacing = new_spacing
```

Should be:
```
resample.SetOutputSpacing(new_spacing)
```

Same goes for
```
resample.SetSize = new_size
```

Please close the issue if this is resolved or provide additional details.

**Comment by JaeDukSeo** [comment]
thanks for this!

**Comment by blowekamp** [comment]
Thank you for your questions. If your problem is not resolved you are welcome to reopen the issue.

**Comment by 1989HD** [comment]
Hi all, 

I too have a question about defining the resampling grid. I would like to rotate and resample .nii volume. Although it generally 'works', I cannot seem to get the resampling grid right. 

Although 2D, I used the following example (see bottom of page, http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/21_Transforms_and_Resampling.html) to generate the script below. Unfortunately, the outcome looks like this: 
![image](https://user-images.githubusercontent.com/41747965/78220168-4c8c6180-74c1-11ea-93ec-fb633d348c7b.png)

I understand that the volume will increase a bit due to the rotation, resulting in 0's around the actual image. What I do not get, is that in the axial view, this does not seem to go as it should, as part of the image falls out of the resampling area.

Do you have an idea of what I might be doing wrong? Thanks in advance!

Regards,

HD


The script: 

`import SimpleITK as sitk
import math

path = '   '

img = sitk.ReadImage(path)

extreme_points = [img.TransformIndexToPhysicalPoint((0,0,0)), 
                  img.TransformIndexToPhysicalPoint((img.GetWidth(),0,0)),
                  img.TransformIndexToPhysicalPoint((img.GetWidth(),img.GetHeight(),0)),
                  img.TransformIndexToPhysicalPoint((0,img.GetHeight(),0)),
                  img.TransformIndexToPhysicalPoint((0,0,img.GetDepth())), 
                  img.TransformIndexToPhysicalPoint((img.GetWidth(),0,img.GetDepth())),
                  img.TransformIndexToPhysicalPoint((img.GetWidth(),img.GetHeight(),img.GetDepth())),
                  img.TransformIndexToPhysicalPoint((0,img.GetHeight(),img.GetDepth()))]



affine = sitk.ReadTransform('tfm.txt')

inv_aff = affine.GetInverse();

extreme_points_transformed = [inv_aff.TransformPoint(pnt) for pnt in extreme_points]

min_x = min(extreme_points_transformed)[0]
min_y = min(extreme_points_transformed, key=lambda p: p[1])[1]
min_z = min(extreme_points_transformed, key=lambda p: p[2])[2]
max_x = max(extreme_points_transformed)[0]
max_y = max(extreme_points_transformed, key=lambda p: p[1])[1]
max_z = max(extreme_points_transformed, key=lambda p: p[2])[2]


nw_spacing = img.GetSpacing()
nw_direction = img.GetDirection()
old_ori = img.GetOrigin();
nw_ori = inv_aff.TransformPoint(old_ori) 



sz_out1 = [math.ceil((max_x-min_x)/nw_spacing[0]),math.ceil((max_y-min_y)/nw_spacing[1]),math.ceil((max_z-min_z)/nw_spacing[2])]

resamp1img = sitk.Resample(img,sz_out1,affine,sitk.sitkAffine,nw_ori,nw_spacing,nw_direction)

sitk.WriteImage(resamp1img,'   ')`

**Comment by vuthea** [comment]
Hi,
Thanks to @1989HD , I solved my problem using C# in Unity. I attached the code below in cased someone has the same problem in C#. Thanks!

`public Image ResampleVoxelSpacing(Image m_img)
{
        List<VectorDouble> extreme_ponts = new List<VectorDouble>();

        VectorInt64 index1 = new VectorInt64(3);
        index1.Add(0);
        index1.Add(0);
        index1.Add(0);
        extreme_ponts.Add(m_img.TransformIndexToPhysicalPoint(index1));

        VectorInt64 index2 = new VectorInt64(3);
        index2.Add(m_img.GetWidth());
        index2.Add(0);
        index2.Add(0);
        extreme_ponts.Add(m_img.TransformIndexToPhysicalPoint(index2));

        VectorInt64 index3 = new VectorInt64(3);
        index3.Add(m_img.GetWidth());
        index3.Add(m_img.GetHeight());
        index3.Add(0);
        extreme_ponts.Add(m_img.TransformIndexToPhysicalPoint(index3));

        VectorInt64 index4 = new VectorInt64(3);
        index4.Add(0);
        index4.Add(m_img.GetHeight());
        index4.Add(0);
        extreme_ponts.Add(m_img.TransformIndexToPhysicalPoint(index4));

        VectorInt64 index5 = new VectorInt64(3);
        index5.Add(0);
        index5.Add(0);
        index5.Add(m_img.GetDepth());
        extreme_ponts.Add(m_img.TransformIndexToPhysicalPoint(index5));

        VectorInt64 index6 = new VectorInt64(3);
        index6.Add(m_img.GetWidth());
        index6.Add(0);
        index6.Add(m_img.GetDepth());
        extreme_ponts.Add(m_img.TransformIndexToPhysicalPoint(index6));

        VectorInt64 index7 = new VectorInt64(3);
        index7.Add(m_img.GetWidth());
        index7.Add(m_img.GetHeight());
        index7.Add(m_img.GetDepth());
        extreme_ponts.Add(m_img.TransformIndexToPhysicalPoint(index7));

        VectorInt64 index8 = new VectorInt64(3);
        index8.Add(0);
        index8.Add(m_img.GetHeight());
        index8.Add(m_img.GetDepth());
        extreme_ponts.Add(m_img.TransformIndexToPhysicalPoint(index8));


        AffineTransform _aff = new AffineTransform(3);
        List<VectorDouble> extreme_points_transformed = new List<VectorDouble>();
        foreach (var pnt in extreme_ponts)
        {
            extreme_points_transformed.Add(_aff.TransformPoint(pnt));
        }

        var min_x = extreme_points_transformed.Min(p => p[0]);
        var min_y = extreme_points_transformed.Min(p => p[1]);
        var min_z = extreme_points_transformed.Min(p => p[2]);

        var max_x = extreme_points_transformed.Max(p => p[0]);
        var max_y = extreme_points_transformed.Max(p => p[1]);
        var max_z = extreme_points_transformed.Max(p => p[2]);


        itk.simple.Transform _tran = new itk.simple.Transform();
        VectorDouble _spacing = new VectorDouble(3);
        _spacing.Add(1);
        _spacing.Add(1);
        _spacing.Add(1);

        VectorUInt32 _mSize = new VectorUInt32(3);
        _mSize.Add((uint) (Math.Ceiling(max_x - min_x) / _spacing[0]));
        _mSize.Add((uint)(Math.Ceiling(max_y - min_y) / _spacing[1]));
        _mSize.Add((uint)(Math.Ceiling(max_z - min_z) / _spacing[2]));

        Debug.Log("new size: " + _mSize[0] + " , " + _mSize[1] + " , " + _mSize[2]);

        Image _resampleImage = SimpleITK.Resample(m_img, _mSize, _tran, InterpolatorEnum.sitkNearestNeighbor, m_img.GetOrigin(), _spacing, m_img.GetDirection(), 0, PixelId.sitkFloat32);

        return _resampleImage;
    }`

**Comment by vkyprmr** [comment]
> I tried to resample sitk image to a new spacing using the following code
> 
> ```
> import numpy as np
> 
> import SimpleITK as sitk
> 
> image = sitk.ReadImage(path_to_sitk_image)
> resample = sitk.ResampleImageFilter()
> resample.SetInterpolator = sitk.sitkLinear
> resample.SetOutputDirection = image.GetDirection()
> resample.SetOutputOrigin = image.GetOrigin()
> new_spacing = [1, 1, 1]
> resample.SetOutputSpacing = new_spacing
> 
> orig_size = np.array(image.GetSize(), dtype=np.int)
> orig_spacing = image.GetSpacing()
> new_size = orig_size*(orig_spacing/new_spacing)
> new_size = np.ceil(new_size).astype(np.int) #  Image dimensions are in integers
> new_size = [int(s) for s in new_size]
> resample.SetSize = new_size
> 
> newimage = resample.Execute(image)
> ```
> 
> However, it returned "Kernel died, restarting" when ran resample.Execute(). Thank you very much.

Hi I am new to SimpleITK and also working with 3d Images. I had a question: `new_size = orig_size*(orig_spacing/new_spacing)` can somebody explain this line to me?

**Comment by 1989HD** [comment]
If you change the voxel size but keep the original size it will deform the image. 

For example: you have an original image of 512*512*640 and a voxel size of [1 1 1] the size in mm is 512*512*640. If you resample the image with voxelszie [0.5 0.5 0.5] while the imagesize stays the same, the actual size in mm will be 256x256x320. 

So if you resample in another voxelsize you have to change your imagesize to maintain the size of the image and vice versa.

**Comment by vkyprmr** [comment]
So, it doesn't matter if I use the same line of code in my script with different voxel size than yours, right?
Or does this need to be different for different purposes?

**Comment by zivy** [comment]
Hello @vkyprmr,

To better understand the process of resampling in ITK/SimpleITK please read the toolkit's [fundamental concepts](https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html), and the [Jupyter notebook on resampling](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/21_Transforms_and_Resampling.ipynb).

**Comment by XUHUI123456** [comment]
Hi, I got the error of "TypeError: Execute() takes 2 positional arguments but 10 were given" when I run:     resample_filter = sitk.ResampleImageFilter()
    resampled_sitk_image = resample_filter.Execute(sitk_image,
                                                   new_size,
                                                   sitk.Transform(),
                                                   sitk_interpolator,
                                                   orig_origin,
                                                   new_spacing,
                                                   orig_direction,
                                                   fill_value,
                                                   orig_pixelid)

**Comment by zivy** [comment]
Hello @XUHUI123456,

The `Execute` method only receives one argument, the image to resample (counting `self`, this makes two arguments). The way you are attempting to use it is similar to the procedural interface which does not create a filter. For additional details on how to use the resampling API, please see [this Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/21_Transforms_and_Resampling.ipynb).

In the future, please do not append questions to old and closed issues. First, see if the question has been answered on the [ITK discourse](https://discourse.itk.org/). If not, ask by either creating a new github issue or a new entry on discourse.

**Comment by blowekamp** [comment]
@XUHUI123456  This style of interface was removed in SimpleITK 2.0. Please see the migration guide for details:
https://simpleitk.readthedocs.io/en/master/migrationGuide2.0.html#filter-s-execute-method
