### ISSUE TITLE
N4BiasFieldCorrectionImageFilter: Getting the bias field with GetLogBiasFieldControlPointLattice 

### ISSUE THREAD

**Issue by mabelzunce** [SimpleITK/SimpleITK#578]
Hi,
Using the N4BiasFieldCorrectionImageFilter, I found out that the bias field can't be obtained from the object as it can be done in ITK by calling N4BiasFieldCorrectionImageFilter::GetLogBiasFieldControlPointLattice. I think this is an important feature because allows you to use a lower resolution image (via shrinking it) to estimate the bias field and then apply it to the high resolution image. Is there any particular reason why this feature was not implemented in SimpleITK?

Best,
Martin

**Comment by blowekamp** [comment]
Yes it would be good to be able to get access to the bias filed to be able to correct other resolution images. I believe I was able to do this be recovering the bias field from the results. The returned image should be `Input/exp(logBiasField)=Output` so `exp(logBiasField)=Input/Output`. You can then resample the  `exp(logBiasField)` to a higher resolutions as desired.

I agree that being able to get direct access to the field is a good feature. I'll have to look into the data structures used a little closer. The `GetLogBiasFieldControlPointLattice` method returns an unstructured set of points for BSpline interpolation. This requires the itkBSplineScatteredDataPointSetToImageFilter to get an interpolated image. I think it may be better to just return the BiasFiled image. Does that meet your needs?

**Comment by mabelzunce** [comment]
I've implemented this temporal solution and the bias field can't be completely recovered because the image has zero values. So, for the purpose of correcting the image is probably fine, but if the visualization of the bias field is needed is better to generate it from the control points and BSpline interpolation.

**Comment by bjw34032** [comment]
I've just come across this problem for myself.  I've previously run a separate program from the shell and then read in the corrected and bias_field files.  I would prefer an in-python solution, so adding the bias field as an output for N4BiasFieldCorrectionImageFilter would be great!

I'll give the simple division a try for now...

**Comment by blowekamp** [comment]
closed by #1232
