### ISSUE TITLE
.NET Core version

### ISSUE THREAD

**Issue by niklr** [SimpleITK/SimpleITK#580]
Greetings,

Are there any plans to provide a .NET Standard version for this project in the near future?
This would greatly increase the number of apps that will be compatible with the library!

Thanks in advance and best regards
Roman

**Comment by blowekamp** [comment]
Do you have a recommend for how SimpleITK which would provide a ".NET Standard" Framework version? Do you have links to specifically what you mean by this? At the core of SimpleITK are standard native C++ libraries that are wrapped for different languages. 

We do provided binaries CSharp binaries:
https://sourceforge.net/projects/simpleitk/files/SimpleITK/1.1.0/CSharp/

**Comment by niklr** [comment]
Indeed, it is actually possible to use the provided CSharp binaries in a .NET Standard project but unfortunately not in .NET Core as far as I can tell.

System.BadImageFormatException: Could not load file or assembly 'SimpleITKCSharpManaged, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

It seems .NET Core does not plan to support C++/CLI according to this discussion: https://github.com/dotnet/coreclr/issues/659

An answer on SO suggests to provide a C API. Mono e. g. supports P/Invoke and .NET Core also supports P/Invoke (see https://stackoverflow.com/questions/39140014/c-cli-support-in-net-core)

**Comment by niklr** [comment]
Is it possible to build the C# version of SimpleITK for Linux x86 / x64? Any hints would be appreciated!
