### ISSUE TITLE
How to read image_series from a folder and remove the repeat ones by order?

### ISSUE THREAD

**Issue by a6225301** [SimpleITK/SimpleITK#581]
Hello, I have a MRI image_series in that folder, and each image is saved by *.IMA file, I want to read the whole folder images by SimpleITK (python), the code I tried is as below

    reader = sitk.ImageSeriesReader()

    dicom_names = reader.GetGDCMSeriesFileNames(case_path)

    reader.SetFileNames(dicom_names)

    image = reader.Execute()
However, when I plot these slices, it seems that lots of them are repeat ones, so i wonder if there are some solutions to remove the repeat slices when i read a image_series from one folder.

**Comment by zivy** [comment]
Hi @a6225301 ,

If you have multiple series in a directory you need to specify which one you want to read. [See if the answer in this discussion](https://github.com/SimpleITK/SimpleITK/issues/436) resolves your issue.

If yes, please close the issue. If not, please provide additional details.

**Comment by blowekamp** [comment]
Thank you for your questions. If your problem is not resolved you are welcome to reopen the issue.
