### ISSUE TITLE
Add wrapper for GetMetricSamplingPercentagePerLevel

### ISSUE THREAD

**Issue by mpinkert** [SimpleITK/SimpleITK#584]
The ImageRegistrationMethod class has no method for getting the 'metric sampling percentage per level' in SimpleITK.  This function exists in the base C++ ITK, but no wrapper was made to port it to SimpleITK.  

The corresponding Set function has already been implemented.

I found this out while trying to implement tests, as part of a workflow where the user performs dozens of registrations in a row.  I'd intended to allow the user to change the sampling metric, but found that I couldn't verify it actually changing to the correct value in a test, and that I couldn't print out the current value to the user.  

This seems like it should be a relatively simple wrapper to implement, as it's just returning a vector double list.

**Comment by blowekamp** [comment]
Thank should be a straight forward method to add. Please come up with a list of "Get" methods you find are missing. Recently we add the a `GetMetricNumberOfValidPoints` method, which is an "active" measurement available in call backs. I have used this to verify the effect of the sampling percentatge.

The design of the SimpleITK ImageRegistrationMethodsv4 is a little different than the ITK class. It provides a single interface which controls all the components of the registration including the optimizer and the metric. As such, there are multiple states and parameters specify to certain states ( e.g. Each optimizer has different parameters ). But we are ware off this limitation and would like to improve the accessibility of parameters, so feedback is appreciated!
