### ISSUE TITLE
3D Spacing not written to TIFF 

### ISSUE THREAD

**Issue by mpinkert** [SimpleITK/SimpleITK#586]
SimpleITK does not write the spacing information for the 3rd dimension when writing to .tif files.  Reopening the saved image in SimpleITK shows the right spacing for first and second dimensions, but not the third.  Minimum example:

```
import SimpleITK as sitk
import numpy as np

some_path = './Img.tif'

img = sitk.GetImageFromArray(np.random.rand(5, 5, 5))
img.SetSpacing([2, 2, 2])
cast_img = sitk.Cast(img, sitk.sitkFloat32)
sitk.WriteImage(cast_img, some_path)

test = sitk.ReadImage(some_path)
test_spacing = test.GetSpacing()

```
test_spacing will give an output of [2, 2, 1] in this case.  

Is this intended behavior/an artifact of tif writing or a genuine bug?

**Comment by blowekamp** [comment]
This issue is dependent on ITK. When it is fixed there it will be fixed in ITK.
