### ISSUE TITLE
work with pydicom v1.1.0 and gdcm v2.6.3  give out VOI LUT warning

### ISSUE THREAD

**Issue by litianqi715** [SimpleITK/SimpleITK#590]
I am working with pydicom v1.1.0 and SimpleITK v1.1.0 on a Ubuntu 16.04 machine.

running following command gives out warning information.
import pydicom
import SimpleITK as sitk
aa=sitk.ReadImage("/home/ltq/data/000001.dcm")

like:
>>> aa=sitk.ReadImage("/home/ltq/data/000001.dcm")
Warning: In /build/gdcm-uIgnvq/gdcm-2.6.3/Source/MediaStorageAndFileFormat/gdcmPixmapReader.cxx, line 830, function bool gdcm::PixmapReader::ReadImageInternal(const gdcm::MediaStorage&, bool)
VOI LUT (0028,3010) are not handled. Image will not be displayed properly

Warning: In /build/gdcm-uIgnvq/gdcm-2.6.3/Source/MediaStorageAndFileFormat/gdcmPixmapReader.cxx, line 830, function bool gdcm::PixmapReader::ReadImageInternal(const gdcm::MediaStorage&, bool)
VOI LUT (0028,3010) are not handled. Image will not be displayed properly

Warning: In /build/gdcm-uIgnvq/gdcm-2.6.3/Source/MediaStorageAndFileFormat/gdcmPixmapReader.cxx, line 830, function bool gdcm::PixmapReader::ReadImageInternal(const gdcm::MediaStorage&, bool)
VOI LUT (0028,3010) are not handled. Image will not be displayed properly

Warning: In /build/gdcm-uIgnvq/gdcm-2.6.3/Source/MediaStorageAndFileFormat/gdcmPixmapReader.cxx, line 830, function bool gdcm::PixmapReader::ReadImageInternal(const gdcm::MediaStorage&, bool)
VOI LUT (0028,3010) are not handled. Image will not be displayed properly

The result seems to be fine. But if I reverse the command, warning information is gone:
import SimpleITK as sitk
import pydicom
aa=sitk.ReadImage("/home/ltq/data/000001.dcm")

Work with dicom v0.9.9 is all fine, but upgrade pydicom to v1.2.0 is not helpful. I am wondering what caused the warning.

**Comment by blowekamp** [comment]
Thank you for your issue. If your problem is not resolved you are welcome to reopen the issue.
