### ISSUE TITLE
Using MultiplyImageFilter for mhd files

### ISSUE THREAD

**Issue by hfarhidzadeh** [SimpleITK/SimpleITK#596]
Hi All,

I have images and corresponding masks, both in mhd. I want to apply mask over image, but sometimes the headers information ( Offset/position ) are slightly different in floating points. As a result, I get an error because of it.

Is there any solution for this problem?

**Comment by blowekamp** [comment]
There are a couple global default tolerances which could be adjusted: https://itk.org/SimpleITKDoxygen100/html/classitk_1_1simple_1_1ProcessObject.html#ae31f487c7d7220c38120128ef02ed74d

There are also corresponding methods to objects if you are using the object oriented interface. 

You could also just copy the meta data to the mask image after you own check that they are close.

**Comment by hfarhidzadeh** [comment]
> There are a couple global default tolerances which could be adjusted: https://itk.org/SimpleITKDoxygen100/html/classitk_1_1simple_1_1ProcessObject.html#ae31f487c7d7220c38120128ef02ed74d
> 
> There are also corresponding methods to objects if you are using the object oriented interface.
> 
> You could also just copy the meta data to the mask image after you own check that they are close.

Thank you for quick response. I will check the link.

I can't copy the meta data as the ElementType and File Name are different. If I could, it would be the easiest way :+1:

**Comment by blowekamp** [comment]
After you load the data you could call sitk::Image::CopyInformation https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1Image.html#afa8a4757400c414e809d1767ee616bd0

Also have you seen: https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1MaskImageFilter.html
