### ISSUE TITLE
CenteredRigid2DTransform is missing

### ISSUE THREAD

**Issue by take5v** [SimpleITK/SimpleITK#597]
Hi,

I'd like to optimize the center of rotation, the angle and the translation in two dimensions. ITK has CenteredRigid2DTransform, but this class was not wrapped in SimpleITK.

Are there any reason for non-wrapping this transform in SimpleITK? Can I initialize sitk.Transform from itk.CenteredRigid2DTransform in python?

Best regards,
Stas

**Comment by blowekamp** [comment]
Hello,

I believe that the gerneral consensus in the ITK community, ( and the medical image registration community as well? ) is that just the Rigid2DTransform is preferred. Here is an old ITK mailing list for reference:
http://itk-users.7.n7.nabble.com/Re-CenteredRigid2DTransform-ResampleImageFilter-td24292.html

Why do you want to optimize both the center and translation? They are redundant and appear to make the optimization problem more difficult.

**Comment by blowekamp** [comment]
I am so just brought this up in conversation in ITK discourse:
https://discourse.itk.org/t/centered-transforms-in-examples/1423

**Comment by take5v** [comment]
Hi,

I have microscopic images to register which usually lack of orientation information (origin + directional cosines) but normally exists in DICOM. I have an issue when a fixed image is 45 degrees rotated with respect to the moving one. Here I first apply the geometry-based centred transform after which centres are still not perfectly matched. And if I apply on top similarity2d or affine transform, registration framework is failed to find the right rotation of moving image. I hope additional optimization of the transform centre may help.

Should I manually specify a coarse orientation or can it be, in principle, computed during optimization?

Best regards,
Stas

**Comment by blowekamp** [comment]
I don't think making the problem more complicated by adding more parameters to the registration will help. You need to figure out how to do good initialization from the data, and that problem is data dependent. Generally to use an optimizer based registration you need to be some what close to the correct answer. There are many techniques that could be used but they are dependent on your data and assumptions that can be made from them. 

Here is one example where different rotations are just evaluated with the Exhaustive Optimizer:
https://simpleitk.readthedocs.io/en/master/Examples/ImageRegistrationMethodExhaustive/Documentation.html

**Comment by take5v** [comment]
Thank you! I agree with having the good initialization is crucial in optimizer based registration.

I tried Exhaustive Optimizer to check the right orientation. Rotation range [-pi, pi] with step pi/4. But it often failed to choose the right one. At such case, the difference in mutual information metric between the "best" orientation and selected one was tiny. In other words, in terms of MI all these initialization cases were far from to be good.

May you recommend initialization techniques for registering 2D grayscale images?

**Comment by blowekamp** [comment]
It really depends on the content of the data, and what assumptions can be made.

**Comment by blowekamp** [comment]
Also when you are trying the different angles, are you initializing the center of rotation? Have you tried visualizing the results of the allied transforms?

**Comment by blowekamp** [comment]
I have updated the ITK examples not to used these transforms:
InsightSoftwareConsortium/ITK@da2b7ee7e1ed2c1fd474df86cde953627096b7ef

Hope this clarifies best practices.
