### ISSUE TITLE
Problem of conversion from nii.gz to dicom files by SimpleITK

### ISSUE THREAD

**Issue by Nicholasxin** [SimpleITK/SimpleITK#599]
I want to convert Nifti data to Dicom data. Following is my code

nii_data_path = 'F:/TestData/'
dicom_output_path = 'F:/TestDataDicom/'
patients = os.listdir(nii_data_path)
patients.sort()

for s in patients:
    NiftyImg = sitk.ReadImage(nii_data_path + s)
    Img = sitk.GetArrayViewFromImage(NiftyImg)
    Slic_Num = len(Img)
    print(s, Slic_Num)
    for slic in range(Slic_Num):
        DicomFileName = dicom_output_path + s.split('.nii')[0] + "-" + str(slic) + ".dcm"
        sitk.WriteImage(Img[slic,:,:], DicomFileName)

However, there comes error:
NotImplementedError: Wrong number or type of arguments for overloaded function 'WriteImage'.
  Possible C/C++ prototypes are:
    itk::simple::WriteImage(itk::simple::Image const &,std::string const &,bool)
    itk::simple::WriteImage(itk::simple::Image const &,std::vector< std::string,std::allocator< std::string > > const &,bool)

I do not understand what the problem is and what the error meaning. 
Thanks for any help!

**Comment by zivy** [comment]
Not sure why you are using the array view, this isn't needed. In any case, the bug is that you are calling WriteImage with a numpy array view and not a SimpleITK image, just do:
```
sitk.WriteImage(NiftyImg[:,:,slic], DicomFileName)
```
Note the change from z,y,x to x,y,z indexing (numpy vs. SimpleITK).

**Comment by Nicholasxin** [comment]
@zivy Thank you a lot ! It helps me lots.
