### ISSUE TITLE
DICOM information when reading series

### ISSUE THREAD

**Issue by cvandijck** [SimpleITK/SimpleITK#60]
When reading a series of dicom images, the dicom header information is not retrieved as well. If only one of those dicom images is read, the dicom information is present as it should be.

```
reader = sitk.ImageSeriesReader()
series_ids = reader.GetGDCMSeriesIDs(dicom_path)
dicom_names = reader.GetGDCMSeriesFileNames(dicom_path, series_ids[0])

reader.SetFileNames(dicom_names)
img1 = reader.Execute()
img2 = sitk.ReadImage(dicom_names[0])

print(img1.GetMetaDataKeys()) #  ()
print(img2.GetMetaDataKeys()) #  ('0008|0005', '0008|0008', '0008|0012', '0008|0013', '0008|0016', ...)
```

I used this data set to test: https://bitbucket.org/somada141/pyscience/raw/master/20141001_SegmentationSimpleITK/Material/MyHead.zip

**Comment by blowekamp** [comment]
This is the expected behavior.

The ITK Image supports a single dictionary, while each DICOM file has a separate dictionary. It would be difficult and likely wrong to try to combine all the DICOM file dictionaries into one. It's not clear to me what your expectation of behavior is here.

We have plans in the future to add methods to the ImageFileReader to allow just reading the meta-data without the image. Would this help with your problem?

**Comment by cvandijck** [comment]
Hi Bradley,

Thank you for your reply. I would think this is not default behaviour as ITK seems to handle this just fine (https://itk.org/Doxygen/html/Examples_2IO_2DicomSeriesReadPrintTags_8cxx-example.html).

Are there any reasons why this should be the case for SimpleITK?

Christophe

Op 9 aug. 2016 17:26 schreef Bradley Lowekamp <notifications@github.com>:

This is the expected behavior.

The ITK Image supports a single dictionary, while each DICOM file has a separate dictionary. It would be difficult and likely wrong to try to combine all the DICOM file dictionaries into one. It's not clear to me what your expectation of behavior is here.

We have plans in the future to add methods to the ImageFileReader to allow just reading the meta-data without the image. Would this help with your problem?

**Comment by blowekamp** [comment]
SimpleITK does not directly expose the ImageIO classes.

The referenced example gets one dictionary from the GDCM ImageIO after the series has been read. This happens to be the tags in the from the last image read in the series.  There is no consolidation from the tags in the series. This behavior can easily be reproduced with the separate read.

With the proposed meta-data read feature, the separate read can skip reading the bulk data making the operation a little more efficient.
