### ISSUE TITLE
R Show function missing

### ISSUE THREAD

**Issue by dave3d** [SimpleITK/SimpleITK#600]
As reported by @zivy, the Show function in R is missing.  I've tracked it down to the following commits:

https://github.com/SimpleITK/SimpleITK/commit/6aa497d921ab97633c689b42f27771d50ab4b57e https://github.com/SimpleITK/SimpleITK/commit/7c0e9aae880d75f05129b225f05bc6e0691fb00f

I tried to figure out what was wrong but couldn't really understand what the file mkNamespace.R was doing.  I did notice that the lowercase function 'show' is mentioned in there, so I tried that, and yes, 'show' works as expected.  

Also I tried the ignorant thing of changing 'show' to 'Show' in the script, but that didn't build.

I would guess and hope that this is a trivial bug for @richardbeare to fix.

**Comment by richardbeare** [comment]
Apologies for that - must be a side effect of attempts at making the package "CRAN compliant" leading to Show not being exported from the R namespace. The lowecase show is the standard generic operation that calls Show - it is the one invoked when an image variable name is typed at the console.

I'll look into it.

**Comment by richardbeare** [comment]
OK,
I'm ready with a patch that exports Show correctly. However there is another issue making it impossible to use another viewer if imagej isn't installed on the host. Filing an issue on that.

**Comment by blowekamp** [comment]
closed by #603
