### ISSUE TITLE
How to covert isotropic binary image to anisotropic?

### ISSUE THREAD

**Issue by John1231983** [SimpleITK/SimpleITK#605]
Hello all, I have two images: isotropic (reference image) and anisotropic (target image). First, I will convert the target image from anisotropic to isotropic image. Then, I apply the thresholding to the isotropic target image to obtain a `seg_image`. The final step is converted back the isotropic resolution of `seg_image` to the original anisotropic (target image). However, the binary image shows a very bad result. It does match with the anisotropic target image when I visualize on ITK-snap. This is my code, what I happened, and how to solve it? 
Note that, I cannot apply thresholding on the anisotropic of target image for some reason

```
import SimpleITK as sitk
##########Input################
# reference_image (1mm x 1mm x 1mm)
# target_image    (0.5mm x 0.5mm x 1mm)
###############################
resample = sitk.ResampleImageFilter()
resample.SetReferenceImage(reference_image)
resample.SetInterpolator(sitk.sitkBSpline)
resampled = resample.Execute(target_image)
###############################
# Threshold image (1mm x 1mm x 1mm)
##############################
print('--------Reslice image after  orientation-------')
seg_image = sitk.BinaryThreshold(resampled,
                           lowerThreshold=100, upperThreshold=400,
                           insideValue=1, outsideValue=0)

###############################
# Unsample/Convert back to target image resolution
# threshold image (1mm x 1mm x 2mm)
##############################
unsample = sitk.ResampleImageFilter()
unsample.SetReferenceImage(target_image)
unsample.SetInterpolator(sitk.sitkBSpline)
unsampled = unsample.Execute(seg_image)

sitk.WriteImage(unsampled, 'output.nii')
```

**Comment by blowekamp** [comment]
It sounds like you are struggling here with your problem. Please narrow down your issue to something specific that you are having trouble with. Narrowing down a problem can frequently help you find a solution yourself. 

I suggest you read our top level read me( https://github.com/SimpleITK/SimpleITK/blob/master/Readme.md). And describe your initial problem with directly threshold of your image.

**Comment by blowekamp** [comment]
I would use the nearest neighborhood or label Gaussian interpolator. Or convert the segmentation to a level set ( 0 level of a distance field ) interpolator that smoothly then threshold the resembled levet set.
