### ISSUE TITLE
How can I get a boundingBox of a binary mask with LabelShapeStatisticsImageFilter()

### ISSUE THREAD

**Issue by huawenqing** [SimpleITK/SimpleITK#606]
I want to get the boundingBox of a binary mask quickly with the GetBouningBox() in LabelShapeStatisticsImageFilter(), but I encounter this problem.

```
imgPath = os.path.join(dataPath,'2_20','2_20.dcm')
maskPath = os.path.join(dataPath,'2_20','anzhongyan_t2-sag.nii.gz')

image = sitk.ReadImage(imgPath)
mask = sitk.ReadImage(maskPath)

lsif = sitk.LabelShapeStatisticsImageFilter()
lsif.Execute(image,mask)
boundingBox = np.array(lsif.GetBoundingBox(1))
```
```
Traceback (most recent call last):
  File "/home/dell/hw/seg/cervical/classification/boundingBox.py", line 14, in <module>
    lsif.Execute(image,mask)
  File "/home/dell/anaconda3/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 43059, in Execute
    return _SimpleITK.LabelShapeStatisticsImageFilter_Execute(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'LabelShapeStatisticsImageFilter_Execute'.
  Possible C/C++ prototypes are:
    itk::simple::LabelShapeStatisticsImageFilter::Execute(itk::simple::Image const &)
    itk::simple::LabelShapeStatisticsImageFilter::Execute(itk::simple::Image const &,double,bool,bool,bool)
```

**Comment by huawenqing** [comment]
I solved this problem by remove the image.

```
imgPath = os.path.join(dataPath,'2_20','2_20.dcm')
maskPath = os.path.join(dataPath,'2_20','anzhongyan_t2-sag.nii.gz')

image = sitk.ReadImage(imgPath)
mask = sitk.ReadImage(maskPath)

label = sitk.GetArrayFromImage(mask)

lsif = sitk.LabelShapeStatisticsImageFilter()
lsif.Execute(mask)

boundingBox = np.array(lsif.GetBoundingBox(1))
```
```
[254 116   9  78  98   8]
```

but the boundingbox seems not correct, is it because the nii format or other question?

**Comment by blowekamp** [comment]
Hello!

Glad to hear you figured out the first problem. The `GetBoundingBox` and ` GetRegion` of the LabelShapeStatisticsImageFilter returns a bounding box is as [xstart, ystart, start, xsize, ysize, zsize].

You may also be interested in the [LabelStatisticsImageFilter ](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1LabelStatisticsImageFilter.html). This also compute the bounding box, it may be more efficient, but the filter takes both the intensity and label image. Additionally it has a `GetRegionMethod` which returns the bounding box as above, and a `GetBoundingBox` method with returns the bounding box as [xmin, xmax, ymin, ymax, zmin, zmax].

**Comment by huawenqing** [comment]
I got it, thank you very much. :smile:

**Comment by Wenting-Xu** [comment]
Is there a program that generates XML files of VOC data set by mask? Thank you very much! @muween

**Comment by zivy** [comment]
Hello @Wenting-Xu,

SimpleITK is an image analysis toolkit, so we don't have a program that allows you to save a mask using the Pascal VOC XML format. You will have to implement your own or look at an existing tool that saves annotations in the VOC format.

**Comment by siavashk** [comment]
> Additionally it has a GetRegionMethod which returns the bounding box as above, and a GetBoundingBox method with returns the bounding box as [xmin, xmax, ymin, ymax, zmin, zmax].

It's actually [x_start, y_start, z_start, x_size, y_size, z_size].
