### ISSUE TITLE
Slice mismatch problem in 3D MRI registration

### ISSUE THREAD

**Issue by bnsmita** [SimpleITK/SimpleITK#643]
Hi,
I have tried to register two 3D stack of images using SimpleITK Affine Registration method. But it failed to register the moving image with the fixed image.
The problem is that there is slice mismatch in the fixed and moving images.
For eg. slice no. 6 of fixed image matches with slice no. 7 of moving image. But the total number of slices in both images are 12.
Also there is movement in slices when I compare fixed with output image.
I have used the following code to register these two images

```
def GlobalAffineRegistration(fixed_image,moving_image):

initial_transform = sitk.CenteredTransformInitializer(sitk.Cast(fixed_image,sitk.sitkFloat32), 
                                                                                   sitk.Cast(moving_image,sitk.sitkFloat32), 
                                                                                   sitk.AffineTransform(3),
                                                                                   sitk.CenteredTransformInitializerFilter.GEOMETRY)


registration_method = sitk.ImageRegistrationMethod()
registration_method.SetMetricAsMattesMutualInformation(numberOfHistogramBins=32)
registration_method.SetInterpolator(sitk.sitkLinear)
registration_method.SetOptimizerAsGradientDescent(learningRate=1.0, numberOfIterations=300, convergenceMinimumValue=1e-6, convergenceWindowSize=10)
registration_method.SetOptimizerScalesFromPhysicalShift()
registration_method.SetInitialTransform(initial_transform, inPlace=False)
final_transform = registration_method.Execute(sitk.Cast(fixed_image,sitk.sitkFloat32) , sitk.Cast(moving_image,sitk.sitkFloat32))
 out = sitk.Resample(moving, fixed, final_transform, sitk.sitkLinear, 0.0, moving.GetPixelID())			
  sitk.WriteImage(out,outFileName)

```

I have attached the fixed, moving and output image respectively in .zip files for a better understanding of my problem.
Moreover when I was using MATLAB imregister function, it was able to detect slice mismatch and take care of it. Please suggest what type of method or parameter setting should I use to get rid of this type of problem.

For 3D visualization check the attached .zip files (fixed, moving, output for 6th slice).

[fixed.zip](https://github.com/SimpleITK/SimpleITK/files/2731633/fixed.zip)

[moving.zip](https://github.com/SimpleITK/SimpleITK/files/2731635/moving.zip)

[output.zip](https://github.com/SimpleITK/SimpleITK/files/2731640/output.zip)

**Comment by bnsmita** [comment]
@zivy 
Can you please help me out in this problem!

**Comment by zivy** [comment]
Closing issue here, discussion can be found [here](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/issues/199).
