### ISSUE TITLE
How to use N4 bias correction?

### ISSUE THREAD

**Issue by huawenqing** [SimpleITK/SimpleITK#646]
My image is in DICOM format and mask in NIFTI format, the dtype are both uint8 or uint16.
I don't know how to operate N4 bias for my MR images. I tried several examples but failed.
There are dtype errors, mismatch errors and so on.
How should I choose the parameters as the examples I see are all used nii format.
Maybe something need to change.
This is one of the code I used but didn't work.

```
def fun():
    image=input('Enter the name and path of the image : ')
    img=sitk.ReadImage(image)
    data=sitk.GetArrayFromImage(img)
    print type(data)
    img_data=sitk.Cast(img,sitk.sitkFloat32)
    img_mask=sitk.BinaryNot(sitk.BinaryThreshold(img_data, 0, 0))
    corrected_img = sitk.N4BiasFieldCorrection(img, img_mask)
    mask=input('Enter the name of the mask image to be saved : ')
    sitk.WriteImage(img_mask,mask)
    new_img=input('Enter the name of the Bias Field Corrected Image : ')
    sitk.WriteImage(corrected_img,new_img)
    print "Finished N4 Bias Field Correction....."

if __name__=='__main__':
   fun()
```

**Comment by zivy** [comment]
Hi @huawenqing,

The bias field correction code expects the pixel type of the image to be a real type (sitk.sitkFloat32 or sitk.sitkFloat64) and the mask to be sitk.sitkUInt8.

To check the pixel type you don't need to convert to numpy and check the dtype there, just:
```
print(img.GetPixelIDTypeAsString())
print(img_mask.GetPixelIDTypeAsString())
``` 
This will tell you what is the pixel type for your image and mask.

If they are not of the expected type, which they aren't, you can either cast the type when reading:
```
img = sitk.ReadImage(image_file_name, sitk.sitkFloat32)
```
or read the original content and then before calling the N4 bias field correction:
```
img = sitk.Cast(img, sitk.sitkFloat32)
```

Please close this issue if the answer resolves your problem, otherwise you will need to post additional details.

**Comment by huawenqing** [comment]
Hi@zivy 
Thank you for your reply. Now I solved the dtype problem.
But I still confused about the maskImage and these two lines.
```
if len ( sys.argv ) > 4:
   maskImage = sitk.ReadImage( sys.argv[4] )
else:
   maskImage = sitk.OtsuThreshold( inputImage, 0, 1, 200 )
```
Which should I choose?
Do the maskImage need N4bias too, or why the maskImage generated from the inputImage?
I tried the first sitk.OtsuThreshold, but error happened:
```
Exception thrown in SimpleITK N4BiasFieldCorrection: c:\d\vs14-win64-pkg\simpleitk-build\itk-prefix\include\itk-4.13\itkImageToImageFilter.hxx:241:
itk::ERROR: SubtractImageFilter(00000194D2712020): Inputs do not occupy the same physical space! 
InputImage Origin: [2.5692644e+01, -8.1022957e+01, 7.8980522e+01], InputImage_1 Origin: [1.2535670e+01, -3.0762479e+01, 2.7294922e+01]
	Tolerance: 3.9062500e-07
InputImage Spacing: [3.9062500e-01, 3.9062500e-01, 4.7999997e+00], InputImage_1 Spacing: [3.1201172e+01, 2.7294922e+01, 1.1400000e+01]
	Tolerance: 3.9062500e-07
```

**Comment by zivy** [comment]
@huawenqing,
I am not sure where you are getting these two lines, this is out of context. 

In any case, the code simply means that either you are reading the mask form file (it was somehow computed previously) or you use the Otsu threshold filter to compute the mask. I can't tell you which one is appropriate because I don't know if you have a mask previously computed.

Now that you have the mask, you need to check that it looks reasonable:
```
sitk.Show(maskImage*255) #assuming here your mask value is 1, output of Otsu
```
If the mask looks ok, then:
```
sitk.N4BiasFieldCorrection(sitk.Cast(img,sitk.sitkFloat32), maskImage)
```
should work and give you the bias corrected image.

**Comment by blowekamp** [comment]
Please see PR #650 for improvements to the example which may help.

**Comment by blowekamp** [comment]
Thank you for your questions. If your problem is not resolved you are welcome to reopen the issue.

**Comment by IsaacLord** [comment]
Im trying to apply this code on multiple image (more than 100) i just put this code on for loop how with different methods, however i got the following errors. It run on one by one images however in loop i got the errors.

Error: 51749 N4BiasFieldCorrectionImageFilter_swigregister = _SimpleITK.N4BiasFieldCorrectionImageFilter_swigregister

RuntimeError: Exception thrown in SimpleITK N4BiasFieldCorrectionImageFilter_Execute: d:\a\1\sitk-build\itk-prefix\include\itk-4.13\itkImageToImageFilter.hxx:241:
itk::ERROR: SubtractImageFilter(000001E58DCBF980): Inputs do not occupy the same physical space!
InputImage Origin: [8.0516953e+01, -1.3090556e+02, 1.4494916e+02], InputImage_1 Origin: [1.9875000e+01, -2.6875000e+01, 3.1875000e+01]
Tolerance: 1.0000000e-06
InputImage Spacing: [1.0000000e+00, 1.0000000e+00, 1.0000000e+00], InputImage_1 Spacing: [2.6875000e+01, 3.1875000e+01, 1.9875000e+01]
Tolerance: 1.0000000e-06.

implementation:

First method:

baseDir=os.path.normpath('C:\Bias_Correction\Data')
files=glob('*.nii')
for f in files:
def N4():
print("N4 bias correction runs.")
inputImage = sitk.ReadImage(f)
# maskImage = sitk.ReadImage("06-t1c_mask.nii.gz")
maskImage = sitk.OtsuThreshold(inputImage,0,1,200)
#sitk.WriteImage(maskImage, "p04_mask.nii.gz")
    inputImage = sitk.Cast(inputImage,sitk.sitkFloat32)
    corrector = sitk.N4BiasFieldCorrectionImageFilter();
    output = corrector.Execute(inputImage,maskImage)
    #sitk.WriteImage(output,"p04.nii.gz")  
    sitk.WriteImage(outputs, os.path.join(baseDir, f[:3] + '_BC' + '.' + 'nii.gz'))
    print("Finished N4 Bias Field Correction.....")

if __name__=='__main__':
    N4()


second method:


import SimpleITK as sitk
import os
from glob import glob
import nibabel as nib
import numpy as np
baseDir = os.path.normpath('C:\Bias_Correction\Data2')
files = glob('*.nii.gz')
print(files)
for f in files:
# load nii file
print("N4 bias correction runs.")
print(f)
inputImage = sitk.ReadImage(f, sitk.sitkFloat32)
# maskImage = sitk.ReadImage("06-t1c_mask.nii.gz")
maskImage = sitk.OtsuThreshold(inputImage, 0, 1, 200)
# sitk.WriteImage(maskImage, "P1.nii.gz")
print("maskImage")
#sitk.WriteImage(maskImage, os.path.join(baseDir, f[:3] + 'maskimage' + '.' + 'nii.gz'))
CastImage = sitk.Cast(inputImage, sitk.sitkFloat32)
print("CastImage")
corrector = sitk.N4BiasFieldCorrectionImageFilter()
print("corrector")
outputs = corrector.Execute(CastImage, maskImage)
print("outputs")
sitk.WriteImage(outputs, os.path.join(baseDir, f[:3] + '_BC' + '.' + 'nii.gz'))
# sitk.WriteImage(output,"06-t1c_output3.nii.gz")
print("Finished N4 Bias Field Correction.....")
print('_____________________________')

**Comment by blowekamp** [comment]
This issue should be address in the lates SimpleITK under development which used ITKv5. You can download the latest python binaries here:
https://github.com/SimpleITK/SimpleITK/releases/tag/latest
