### ISSUE TITLE
Composite transform question

### ISSUE THREAD

**Issue by malikad41292** [SimpleITK/SimpleITK#653]
Hi,
Thank you so much for this library! It's super useful. 
 Do you have an example of using a composite transform for affine and then bspline? 

Thanks!

**Comment by zivy** [comment]
Please see [this jupyter Notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/22_Transforms.ipynb). I believe the section on Composite transformations addresses your need. If not, please provide additional details.

**Comment by blowekamp** [comment]
Closing issue, assuming questions was answered.
