### ISSUE TITLE
resample a single point or point set

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#654]
Add a resample method to the Image class, as suggested in [this discourse discussion](https://discourse.itk.org/t/how-can-i-get-an-interpolated-value-between-voxels/1535).

Proposed interfaces:
```
std::vector< double > GetIntensityAtContinuousIndex(const std::vector &, InterpolatorEnum)
std::vector< double > GetIntensityAtPhysicalPoint(const std::vector &, InterpolatorEnum)
```
Where the input vector is coordinates of a single/multiple points and the return vector is the intensity(s)? Always return double as the interpolation is really carried out using real values. Maybe allow the user to specify the output type?

**Comment by blowekamp** [comment]
A related ITK class is the [LinearInterpolateImageFunction](https://itk.org/Doxygen/html/classitk_1_1LinearInterpolateImageFunction.html) its exposed method is `EvaluateAtContinuousIndex`. I think using that same name be be a good idea. The `Get` prefix implies access to a stored variable while `Evaluate` indicates that there is computation begin done. Also while convenient, I don't think the `AtPhysicalPoint` is necessary.

In ITK, the output type for the interpolator image functions of all pixels seem to be "real" type, even for label interpolators. For SimpleITK it may be sensible to have a 3 return types, `double`, `vector<double>` and `complex<double>`. This would lead to there methods

```
double Image::EvaluateAtContinuousIndexAsScalar(const std::vector &, InterpolatorEnum);
vector<double> Image::EvaluateAtContinuousIndexAsVector(const std::vector &, InterpolatorEnum);
complex<double> Image::EvaluateAtContinuousIndexAsComplex(const std::vector &, InterpolatorEnum);
```

One last complication is I'm not sure the interpolators work with "LabelMap" images.

**Comment by zivy** [comment]
With respect to `AtPhysicalPoint`, that is just for convenience, so we just having `AtIndex` works. Maybe drop the `Continous` in the signature? It is very/too verbose:
```
double Image::EvaluateAtIndexAsScalar(const std::vector &, InterpolatorEnum);
vector<double> Image::EvaluateAtIndexAsVector(const std::vector &, InterpolatorEnum);
complex<double> Image::EvaluateAtIndexAsComplex(const std::vector &, InterpolatorEnum);
```

**Comment by blowekamp** [comment]
For the python interface the "AsBlah" can be dropped and the proper method automatically called, as Python supports different return types. So I think the typical usage will be:
 `img->EvaluateAtContiuousIndex([1.2,3.4,5.6])`
Which mirrors the ITK methods I mentioned, and looks pretty good to me.

**Comment by dave3d** [comment]
Index is in pixel space, right?  So if the user wants to sample the image in physical space, they have to do the transform themselves.

EvaluateAtContinuousIndex look good to me.
