### ISSUE TITLE
Show stalls on Windows 10

### ISSUE THREAD

**Issue by dave3d** [SimpleITK/SimpleITK#661]
When you call Show on Windows 10, Fiji launches successfully, but SimpleITK stall waiting for the process to finish.  So the python prompt does not come back.

**Comment by blowekamp** [comment]
Does the happen with both the old show and the new show class?

**Comment by dave3d** [comment]
Good question.  I was using the Show function.  I'll try the ImageViewer class.  Gotta go fire up the old Windows box attached to our printer.

FYI this was when I tried to run through the SPIE course notes.  So it was using the conda installed SimpleITK.

**Comment by blowekamp** [comment]
Please base the fix on the release branch so it can be merged into 1.2.

**Comment by dave3d** [comment]
So I've determined that v1.2 demonstrates the bug, but the current master does not.  The current master seems to work fine for me.  I don't know why v1.2 doesn't work.  As far as I can tell, no code of any import was changed between v1.2 and now.

**Comment by blowekamp** [comment]
I don't see any significant difference between the two branches that could effect the Show function....

**Comment by blowekamp** [comment]
closed by #681
