### ISSUE TITLE
Safe ITK/C++ exception handling in python

### ISSUE THREAD

**Issue by take5v** [SimpleITK/SimpleITK#680]
Hi,

I'm using python wrapper of sitk for image registration. I'd like to test different combinations of image normalizations so that I test different registration methods within a loop and I'd prefer not failing fast getting one exception but register the rest "good" combinations. Once in the middle of a loop, I can get an exception from ITK metric class e.g. "Joint PDF summed to zero".

So, I've tried to wrap the registration method in a try-except in python. But then I still continuously get the same exception for remaining iterations within a loop. I also tried to reload SimpleITK package.

What is a safe way to handle itk exceptions in python sitk?
Will it be possible to wrap itk exceptions in sitk?

Best regards,
Stas

**Comment by take5v** [comment]
Hi,

I've also found that memory is not released properly from a python wrapper of SITK. Should I call GC every time after execution of registration method in a loop? Are there any plans to fix this?

By now I have to run the registration procedure at the "worker" process apart from the main one to handle memory leak and failing by exceptions.

Best regards,
Stas

**Comment by zivy** [comment]
Hello @take5v,
The exception thrown when "Joint PDF summed to zero" indicates that likely there is no overlap between the two images. This should not happen after a reasonable initialization. Please check this. 

With respect to repeatedly getting the same exception, you will have to post a minimal working example illustrating the issue as the code layout is not clear from your description (also not sure what you mean by "image normalizations").

The code below illustrates a repeated registration starting at different initial transformations. The first transformation will cause an exception with the same problem you are having. The second transformation will result in a successful registration.

The images can be downloaded from [here](https://github.com/zivy/ISBI2018_TUTORIAL_DATA/blob/master/training_001_ct.mha) and [here](https://github.com/zivy/ISBI2018_TUTORIAL_DATA/blob/master/training_001_mr_T1.mha).


```
import SimpleITK as sitk

fixed_image =  sitk.ReadImage('training_001_ct.mha', sitk.sitkFloat32)
moving_image = sitk.ReadImage('training_001_mr_T1.mha', sitk.sitkFloat32) 

# Create a list of initial alignments. The first causes the images to have no overlap
# and will result in an exception. The second will have overlap and a successful registration.
initial_transforms = []
t1 = sitk.Euler3DTransform()
t1.SetTranslation((1000,0,0))
initial_transforms.append(t1)
initial_transforms.append(sitk.CenteredTransformInitializer(fixed_image, 
                                                            moving_image, 
                                                            sitk.Euler3DTransform(), 
                                                            sitk.CenteredTransformInitializerFilter.GEOMETRY))

# Configure registration
registration_method = sitk.ImageRegistrationMethod()
registration_method.SetMetricAsMattesMutualInformation(numberOfHistogramBins=50)
registration_method.SetMetricSamplingStrategy(registration_method.RANDOM)
registration_method.SetMetricSamplingPercentage(0.01)
registration_method.SetOptimizerAsGradientDescent(learningRate=1.0, numberOfIterations=100, convergenceMinimumValue=1e-6, convergenceWindowSize=10)
registration_method.SetOptimizerScalesFromPhysicalShift()

# Run registrations starting at each of the initial transformations
for i_transform in initial_transforms:
    try:
        registration_method.SetInitialTransform(i_transform, inPlace=False)

        final_transform = registration_method.Execute(fixed_image, 
                                                      moving_image)
        print('Final metric value: {0}'.format(registration_method.GetMetricValue()))
        print('Optimizer\'s stopping condition, {0}'.format(registration_method.GetOptimizerStopConditionDescription()))
    except RuntimeError as e:
        print('Got an exception\n' + str(e))
    
```

**Comment by blowekamp** [comment]
I think this issue has been resolved. It it still persists please reopen and provide more details.

**Comment by Ravi-shankar100** [comment]
Hi @take5v 
I am facing the same issue on kaggle notebook submission file.
My code is breaking in for loop in which I'm writing .nii image using SITK.
I have used try and except for solving this but then I still continuously get the same exception as you mentioned.
Can you please help me in fixing this issue.

**Comment by blowekamp** [comment]
Please open a new issue. Please include a minimal reproducible example code, and the output for your problem.
