### ISSUE TITLE
Header mismatch on segmentation image causing flipped segmentation

### ISSUE THREAD

**Issue by divinediu** [SimpleITK/SimpleITK#694]
1.  I have a dicom series 1.dcm
2. I converted 1.dcm to 1.nii with dcm2niigui
3. I have 1_seg.nii.gz created on the 1.nii file with ITK SNAP 3.6 

Now, if I try to load 1.dcm as the main image and 1_seg.nii.gz as the segmentation image, I get  

![image](https://user-images.githubusercontent.com/4358356/53936001-67c64b00-40ce-11e9-9ec3-da049cc793be.png)
![image](https://user-images.githubusercontent.com/4358356/53936022-7ad91b00-40ce-11e9-81bc-1403301046f5.png)
![image](https://user-images.githubusercontent.com/4358356/53936095-bb389900-40ce-11e9-85ea-e6d0795c03a9.png)

The segmentation is not loaded perfectly on the image. It appears flipped and a little out  of order. 
![image](https://user-images.githubusercontent.com/4358356/53936216-25513e00-40cf-11e9-9e88-e13cc571e335.png)

The red is my segmentation, it should have appeared inside the blue circle.  Why is it flipped?

**Comment by blowekamp** [comment]
How have you used SimpleITK here? 

It is tricky to ensure all the meta-data is consistent when changing file formats. I'd recommend inspecting all the meta-data as SimpleITK reads them to determine if it is consistent.

**Comment by blowekamp** [comment]
Thank you for reporting the issue, however I'm not sure how SimpleITK is used here.
