### ISSUE TITLE
GetGDCMSeriesIDs stuck then throws badalloc

### ISSUE THREAD

**Issue by Roulbac** [SimpleITK/SimpleITK#696]
Hi,

I have a fodler with a bunch of .dcm.dcma files.
It contains somes series; I was able to open it with ITK-SNAP without problems.

I ran the following commands on it:
```
reader = sitk.ImageSeriesReader()
uids = reader.GetGDCMSeriesIDs(’./12.2/’)
```
I get a 
`RuntimeError: Exception thrown in SimpleITK ImageSeriesReader_GetGDCMSeriesIDs: std::bad_alloc`

Got this on OsX high sierra and Ubuntu 16, SimpleITK 1.2.0

Here's a link to the dropbox of the dicom folder
https://www.dropbox.com/sh/gi6yvv5fy4n46nt/AABnFoEqbHhUQAA2zAcCXI5Xa?dl=0

**Comment by Roulbac** [comment]
Please hold on for this for a bit, doing some more testing and troubleshooting, might be one series in the entire dicom folder that's causing the problem.
I need to find a way to discard it and only read the other series.

**Comment by blowekamp** [comment]
Hello Roulbac,

I saw your post on ITK discourse: https://discourse.itk.org/t/problem-reading-a-series-uids/1641

It sounds like it's a problem with ITK or the underlying DICOM library, GDCM. I think ITK discourse is a good place for this questions/issue. I'll leave it to the DICOM experts there.
