### ISSUE TITLE
sitk::Show with color image produces error

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#70]
With ImageJ 1.46r on Redhat 7 linux I am seeing the following error when trying to show an RGB image:

In [10]: sitk.Show(sitk.LabelToRGB(sitk.SLIC(img, 20)), debugOn=True)
FindApplication search path: [ /opt/Fiji.app, /usr/local/Fiji.app ]
Result: 
FindApplication search path: [ /opt/Fiji.app, /usr/local/Fiji.app ]
Result: 
FindApplication search path: [ /opt/ImageJ, /usr/local/ImageJ ]
Result: /opt/ImageJ/imagej
Show command: '/opt/ImageJ/imagej' '-e' 'open("/tmp/TempFile-8140-3.nii"); rename("/tmp/TempFile-8140-3.nii"); ' '-e' 'run("Make Composite", "display=Composite");' 

In [11]: 
Image display and analysis program. Opens formats including:
UNC, Analyze, Dicom, NIFTI, Tiff, Jpeg, Gif, PNG ...

imagej [options] image [ image2 ... image3 ] -> open images

basic options:
  -h        print help and more options
  -o        open images in existing ImageJ panel if one exists
  -p <N>    open images in existing ImageJ panel number <N>
  -x <MB>   set available memory (default=16000 max=515800)

advanced options:
  -c        enable plugin compilation within imagej
  -d        use development version
  -v        be verbose (vv or vvv increases verbosity)

options for batch processing:
  -e 'Macro Code'            execute macro code
  -r 'Menu Command'          run menu command
Quotation marks '' are required around commands including spaces
Commands can be sent to open ImageJ panels with the -p option

options for macros:
imagej [-i image] [-b|-m] [arg1 ... argN] 
  -b macro    run macro without graphics window
  -m macro    run macro
"image" will be opened before macro is run
all following arguments are passed to macro

Documentation - http://rsb.info.nih.gov/ij/ 
Report problems with this software to 

Only one command option (-b -e -m OR -r) may be specified

Having the macro over 2 arguments appears to be the problem. If the command is change to just one "-e" then it works:

os.environ["SITK_SHOW_COLOR_COMMAND"] =  "%a -e ' open(\"%f\"); rename(\"%t\"); run(\"Make Composite\", \"display=Composite\");'"

**Comment by blowekamp** [comment]
@dave3d Any progress on this issue?

**Comment by dave3d** [comment]
@blowekamp This issue was fixed with the following commit:

https://github.com/SimpleITK/SimpleITK/commit/f0359d14b0423c4263fce98d5c751ccc32391f64
