### ISSUE TITLE
Please someone wrap CannySegmentationLevelSetImageFilter for c#

### ISSUE THREAD

**Issue by pettaa123** [SimpleITK/SimpleITK#705]

**Comment by pettaa123** [comment]
Thank you so much 👍 Will the method be available in c# for me if I add the json file and build it normally? Or do I have to add somethin so any cmake file?

**Comment by blowekamp** [comment]
I'd recommend [checking out this PR locally](https://help.github.com/en/articles/checking-out-pull-requests-locally), re-running CMake, then building. The new class should then be available in all languages.

**Comment by pettaa123** [comment]
Did you miss SetIsoSurfaceValue()?

**Comment by blowekamp** [comment]
Thanks for giving it a try. I added the two requested items.

 We initially passed on adding the "IsoSurfaceValue" parameter to all the LevelSet filters because it's trivial to just shift the input image by a constant so that the desired iso-value is zero. 
Do you think the added SetIsoSurfaceValue method adds significantly to the utility?

**Comment by pettaa123** [comment]
Thank you so much so far 👍 . Unfortunately the IsoSurfaceValue it is not that trivial for me and I am misunderstanding something totally wrong. 
If I dont set the IsoSurfaceValue explicitly to something else than 0.0 my guess is not growing. In my oppinion it is not clear how to setup the input images/parameters correctly. The CannySeg doc says:  For a binary image you will want to set your isosurface value halfway between your on and off values (i.e. for 0's and 1's, use an isosurface value of 0.5) . For me is not clear if this relates to the seed-image or maybe to the feature image greyvalues in the area of the seed?
I use the following parameters:
![seed](https://user-images.githubusercontent.com/31046837/54812722-1bf9d100-4c8c-11e9-9c33-ac9649234f1d.png)
![feature](https://user-images.githubusercontent.com/31046837/54812723-1bf9d100-4c8c-11e9-8180-9a058204747f.png)
![output](https://user-images.githubusercontent.com/31046837/54812724-1bf9d100-4c8c-11e9-98d3-7f62db3da4ae.png)

`
ItkImage featureImage = SimpleITK.ReadImage("C:/feature.png", PixelIDValueEnum.sitkFloat64);
ItkImage seedImage = SimpleITK.ReadImage("C:/seed.png", PixelIDValueEnum.sitkFloat64);
CannySegmentationLevelSetImageFilter caLevSet = new CannySegmentationLevelSetImageFilter();
caLevSet.SetAdvectionScaling(0.5);
caLevSet.SetPropagationScaling(4.5);
caLevSet.SetCurvatureScaling(3);
caLevSet.SetMaximumRMSError(0.05);
caLevSet.SetNumberOfIterations(2000);
caLevSet.SetThreshold(7);
caLevSet.SetVariance(1);
caLevSet.SetIsoSurfaceValue(127.5);
caLevSet.ReverseExpansionDirectionOn();
ItkImage output = caLevSet.Execute(seedImage, featureImage);
output = SimpleITK.Cast(output, PixelIDValueEnum.sitkUInt8);`

Apparently I do something wrong because the seed should grow with positive advection and propagation. Instead I have to reverse expansion direction.

Best regards :)

**Comment by blowekamp** [comment]
The first thing I would try to do is reproduce the ITK example in simpleITK:
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Examples/Segmentation/CannySegmentationLevelSetImageFilter.cxx

You can even add this example in a sub-directory of the Examples directory and create a PR.

**Comment by pettaa123** [comment]
Doing that I tried to generate the input first. This comes from thresholdsegmentation, but I had no succes so far. Nevertheless,  I think the GetCannyImage() method doesn't work. I get following error if I try to view the methods output:
{"Exception thrown in SimpleITK Show: c:\\git\\simpleitk\\simpleitk-build\\itk-prefix\\include\\itk-4.13\\itkImageFileWriter.hxx:290:\nitk::ERROR: ImageFileWriter(0000015039A30D30): Largest possible region does not fully contain requested paste IO regionPaste IO region: ImageIORegion (0000004D191FA3C0)\n  Dimension: 2\n  Index: 0 0 \n  Size: 0 0 \nLargest possible region: ImageRegion (0000004D191FA4B0)\n  Dimension: 2\n  Index: [0, 0]\n  Size: [0, 0]\n"}

using the following code: 
`ItkImage output = caLevSet.Execute(seedImage, oriImage);
            ItkImage canny = caLevSet.GetCannyImage();
            SimpleITK.Show(canny);`

According to [this](https://itk.org/pipermail/insight-users/2011-November/043043.html) it seems to me that GetCannyImage() doesn't update the pipeline?

best regards :)

**Comment by blowekamp** [comment]
Thanks for reporting this issue. This may be an issue with ITK, I'll have to investigate.

**Comment by pettaa123** [comment]
> 
> 
> The first thing I would try to do is reproduce the ITK example in simpleITK:
> https://github.com/InsightSoftwareConsortium/ITK/blob/master/Examples/Segmentation/CannySegmentationLevelSetImageFilter.cxx
> 
> You can even add this example in a sub-directory of the Examples directory and create a PR.

I ported the example. When iterating 15 times, the output looks pretty similar to the outputs documented in ITK software guide. But when iterating to convergence(about 60 iterations) the result looks definetly not like in ITK's documentation. https://github.com/pettaa123/SimpleITK/tree/CannySegExample

**Comment by pettaa123** [comment]
![CannySegmentationLevelSetImageFilterVentricle1 - 15 Iterations](https://user-images.githubusercontent.com/31046837/56673582-d0867880-66b8-11e9-9c93-5dd6a0342775.png)

![CannySegmentationLevelSetImageFilterVentricle1 - convergence](https://user-images.githubusercontent.com/31046837/56673642-ed22b080-66b8-11e9-98a3-f010ee73d7d7.png)

**Comment by blowekamp** [comment]
This is with C# code? Can you share your code?

There are quite a large number of steps and parameters in this example, its quite easy for a small difference to occur when re-implementing it.

**Comment by pettaa123** [comment]
If everything went well you can see the used code in here https://github.com/pettaa123/SimpleITK/tree/CannySegExample

**Comment by blowekamp** [comment]
The one difference I spotted was the C# example used float64/double while the ITK example used float. Aside from that as long as the initial level set looks is the same the test case looks good to me.

These level set have been tricky to reproduce the examples before.

**Comment by pettaa123** [comment]
Ok, can you tell me where to get the ventricle seed from for the testing advice in cmakelist. So far only Brainprotondensityslice is already given

**Comment by pettaa123** [comment]
I tried it with float32, the convergence result looks same as with float64

My used inputdata
![ThresholdSegmentationLevelSetImageFilterVentricle](https://user-images.githubusercontent.com/31046837/56718099-6d3f2980-673e-11e9-807d-d481fcf0a7b6.png)
![BrainProtonDensitySlice](https://user-images.githubusercontent.com/31046837/56718107-6fa18380-673e-11e9-9a25-497623a49aea.png)
outputdata
![CannySegmentationLevelSetImageFilterVentricle1](https://user-images.githubusercontent.com/31046837/56718114-70d2b080-673e-11e9-95a4-40fab7cac58f.png)

**Comment by blowekamp** [comment]
I see a list of seeds under the `ShapeDetectionLevelSet` section in the software guide. In [Table 4.4.](https://itk.org/ITKSoftwareGuide/html/Book2/ITKSoftwareGuide-Book2ch4.html#x37-191266r4)

It looks like your levelest is shrinking in stead of expanding. Try multiplying by "-1" and/or toggling `ReverseExpansionDirection`.

**Comment by blowekamp** [comment]
I have implemented the example in python. The advection term should be negative ten (-10): InsightSoftwareConsortium/ITK#774

**Comment by pettaa123** [comment]
I think the issue regarding the getcannyimage method is still unsolved?
