### ISSUE TITLE
FastMarching Seeds in c# - NodeType?

### ISSUE THREAD

**Issue by pettaa123** [SimpleITK/SimpleITK#710]
Hi, I started porting the ThresholdSegmentationImageFilter example from ITK to SimpleITK c#.
Unfortunately I dont get how to convert ITK's NodeType to VectorUIntList properly for FastMarching. Please give me advice.

I added the current version to my [Fork](https://github.com/pettaa123/SimpleITK/blob/exampleThresholdSeg/Examples/CSharp/ThresholdSegmentationLevelSetImageFilter.cs)

**Comment by blowekamp** [comment]
If you are able to build SimpleITK from the source, I'd look at the generated tests for some of these tricky cases. Here is the section from `FastMarchingImageFilterTest.java`:
```
        // Set parameters
      filter.clearTrialPoints();
      {
        int v[] = {70,70};
        VectorUInt32 idx = new VectorUInt32();
        for (int i = 0; i < inputs[0].getDimension(); i++) {
          idx.add(v[i]);
        }
        filter.addTrialPoint(idx);
      }
      {
        int v[] = {200,180};
        VectorUInt32 idx = new VectorUInt32();
        for (int i = 0; i < inputs[0].getDimension(); i++) {
          idx.add(v[i]);
        }
        filter.addTrialPoint(idx);
      }
```

CSharp should quite similar

**Comment by pettaa123** [comment]
Thanks! I cant reproduce the output of ITK's ThresholdSegmentationFilter example. The only big difference I see between my version and the example is that I didnt set up a distance for the seed node. In the end the Thresholdsegmenter doesnt start iterating with fastmarching output as it is.

**Comment by blowekamp** [comment]
The value of the seeds is optionally the last component of the each seed in the seed list. For example for 2D { {p0_0, p0_1, v0},{p1_0, p1_1, v1}}, where v0 is the value for point p0.

TODO: Clearly, there is much need for documentation and an example for this filter.

**Comment by blowekamp** [comment]
Started an example here: #713

**Comment by pettaa123** [comment]
awesome , i am going to port that to c# then. In this [ITK example](https://itk.org/Doxygen/html/Examples_2Segmentation_2ThresholdSegmentationLevelSetImageFilter_8cxx-example.html) the seed is set to negative value: -5. I dont think this is possible with unsigned int VectorUint32.

**Comment by pettaa123** [comment]
I ported your fastmarching example to [c#](https://github.com/pettaa123/SimpleITK/blob/exampleThresholdSeg/Examples/CSharp/FastMarchingSegmentation.cs)
The ![result](https://user-images.githubusercontent.com/31046837/54989437-cb021980-4fb8-11e9-89ed-d3c49c52c344.png) is not correct

**Comment by blowekamp** [comment]
Generally, I believe you can just use arithmetic to adjust the time of the propagation as a post processing step. Just add 5 to the stopping value, and subtract 5 from the output.

Yes, this is an unfortunate limitation of the current interface... Do you think it is a significant limitation? and have a suggestions of improvement?

**Comment by blowekamp** [comment]
Thank you for your help in creating these examples.
