### ISSUE TITLE
SITKImage to VtkImageData

### ISSUE THREAD

**Issue by pettaa123** [SimpleITK/SimpleITK#717]
If there isnt a method yet converting sitkimage to vtkImageData, this would be a awsome feature

**Comment by blowekamp** [comment]
This would be quite a useful tool. However, I think it should be a separate python module and not in SimpleITK. There is certainly a need for a hight level SimpleITK package with contains algorithms and other functionality based on the SimpleITK python module along and in combination with other modules.

**Comment by dave3d** [comment]
I wrote a module to do that for another project that you're free to use.

https://github.com/dave3d/dicom2stl/blob/master/sitk2vtk.py
