### ISSUE TITLE
[Help Wanted] ImportError: No module named _SimpleITK on Windows after install through SuperBuild with cmake and vanilla python

### ISSUE THREAD

**Issue by RNMahon** [SimpleITK/SimpleITK#721]
Hello, 

I have been having issues installing SimpleITK on Windows 10 using Cmake, Visual Studio 2019 and vanilla python 2.7.  Pip install would not work because the ITK build directory was longer than 50 characters, so I built SimpleITK using cmake and the Superbuild.  I also installed the setup.py in the python wrapper.  SimpleITK and the SimpleITK...egg-info files show up in the site-packages for the python libs but I get "ImportError: No module named _SimpleITK" when trying to import in python (see attached .png) 

Any help would be appreciated.  I did not change any of the cmake settings for the superbuild so I believe libraries are static.  Also, I do not have anaconda or enthought python distributions installed.

Thank you!

![Python_Error](https://user-images.githubusercontent.com/12072356/55486626-a29e9e80-55fa-11e9-96a9-1168d03b0c8e.png)

**Comment by blowekamp** [comment]
Hello,

It sounds like you tried several things and they would not work for you.
- Python 2.7 is approaching its end of life. Please try a newer Python like 3.6 you should easily be able to get the Windows 64 Python 3.6 binaries with pip. Unfortunately we don't have SimpleITK 1.2.0 Python 2.7 binaries for windows 64 due to some compiler limitations (VS2009). 

Before we try to debug how you are trying to build SimpleITK and install it. Lets see if we can get you up and running with a pre-build binary.

**Comment by RNMahon** [comment]
Unfortunately, I need Python 2.7 to run the imaging API for the software I am using in my research and there is no alternative.  The API dose not support Python 3 yet, but they are working on it with no release date set.  

To answer your question, I started trying to install Simple ITK with `pip install SimpleITK` but when that failed under several compilers, I followed the instructions in the "Building using SuperBuild" and "Python installation" sections of documentation: I downloaded the source code, created a separate build directory, went into the build directory and issued the command `cmake <path to source directory>/SimpleITK/SuperBuild`.  The SuperBuild installed with no issues then I moved to the SimpleITK build /Wrapping/Python directory and issued the command `python Packaging/setup.py install`.  The SimpleITK package now shows up in the site packages and is displayed with `pip list`.  I have both the source and build directories in the C:\ so as to be available to all users and I issued commands from an administration account.  I will admit to being far more familiar with Unix/Linux than Windows.

**Comment by blowekamp** [comment]
I have just been able to compile and test Windows 64 for Python 2.7 on a new system. I should be able to package it in the next couple of days.

**Comment by blowekamp** [comment]
> To answer your question, I started trying to install Simple ITK with `pip install SimpleITK` but when that failed under several compilers, I followed the instructions in the "Building using SuperBuild" and "Python installation" sections of documentation: I downloaded the source code, created a separate build directory, went into the build directory and issued the command `cmake <path to source directory>/SimpleITK/SuperBuild`. The SuperBuild installed with no issues then I moved to the SimpleITK build /Wrapping/Python directory and issued the command `python Packaging/setup.py install`. The SimpleITK package now shows up in the site packages and is displayed with `pip list`. I have both the source and build directories in the C:\ so as to be available to all users and I issued commands from an administration account. I will admit to being far more familiar with Unix/Linux than Windows.

Most likely the linking of the large library did not complete successfully. So the package create is missing the compiled C++ library, so it's not usable.

For ABI compatibility with python 2.7 VS2008 is needed. There is a repackage version targeting Python 2.7 that can easily be used: https://www.microsoft.com/en-us/download/details.aspx?id=44266 Here is some information on how to use that compiler with CMake: https://github.com/scikit-build/scikit-build/issues/34

This is what I'm using on my new configuration for packaging.

**Comment by RNMahon** [comment]
@blowekamp  Thank you for the information.  I have uninstalled Visual Studio 2019 and used python 2.7 VS2008 install.  As a side note, I originally tired as one of the compiler options previously with pip.  Pip install still gives the same error about the ITK build directory being too long.  Now when I run the superbuild (git installed source binaries), it provides the output in about 5s, with no error message but dose not appear to install ITK or SWIGs. When I went into the build directory there is no Wrapping directory, which is very different than last time.  
![image](https://user-images.githubusercontent.com/12072356/55972182-09eacd00-5c51-11e9-8f47-e396bd06c2bb.png)

the cmake error log now has this information:
[CMakeError.log](https://github.com/SimpleITK/SimpleITK/files/3069655/CMakeError.log)

**Comment by blowekamp** [comment]
Did you run "CMake --build . --config Release"? It looks like your configuration is OK.

I would recommend creating and working in "C:\bld" for building SimpleITK on windows.

There should be a SimpleITK python 2.7 windows 64 package shortly...

**Comment by RNMahon** [comment]
Sorry, I had tired the cmake --build after configuration before the previous comment, but I had forgotten to execute the build command from one directory up so it wasn't finding the right cache file.  Appears to be running ok now, and I will let you know how it goes once done.  I will also keep and eye out for the SimpleITK python 2.7 package package.  I cannot than you enough for all your help so far.

**Comment by blowekamp** [comment]
Hello,

SimpleITK 1.2.0 for Python 2.7 for Windows 64-bits is packaged uploaded to test.pypi.org. Please download the wheel and test it:
https://test.pypi.org/project/SimpleITK/1.2.0/#files

Enjoy!

**Comment by RNMahon** [comment]
I installed the test wheel and there were no issues with the pip install.  Import into Python was also successful.  Thank you.  

As an update, the Super Build from source I started yesterday kept running into errors with the NMake compiler not finding the '.dlfcn.h' file at different points in the install.

**Comment by blowekamp** [comment]
I have uploaded the wheel to the main PyPI, so you should be able to just `pip install SimpleITK` and be good to go.

I don't recall seeing that error before. I used the "ninja" generator. Using the VS for Python 2.7 is a little different that normal compilers. I ran into some problems while missing runtime libraries when I built with a Debug configuration.

Do you still have need to compile SimpleITK yourself? Other wise, could you please close this issue.
