### ISSUE TITLE
can this tool be used for immunohistochemistry images?

### ISSUE THREAD

**Issue by rojinsafavi** [SimpleITK/SimpleITK#722]
can this tool be used for immunofluorescence images?

**Comment by zivy** [comment]
Hello @rojinsafavi ,

Welcome to SimpleITK!

We need a bit more information to give a complete answer, as immunohistochemistry images is not a specific image file format.

SimpleITK works with a variety of image formats (png, nrrd, tiff, dcm...).  Once you read the image all the algorithms/operations are not aware of the original format. 

So, generally speaking the answer to your question is yes. You just need to be able to read the image from disk. Either using SimpleITK or if you have your own custom reader that can output a numpy array, we can convert that array to a SimpleITK image.

 hope this helps
      Ziv

**Comment by rojinsafavi** [comment]
Thanks for the quick response. It is TIFF (immunofluorescence imaging). 

I have 4 microscopic images from 4 adjacent slides, which should cover ~2-cell in z-stack. I need to align those slides ( I think it is called image registration).
Ideally, I need to make a pipeline that aligns these four images into a single one, and outputting the "moving" and "rotation" matrices of each image.

Is that a possible thing with your package?

Thank you very much!

**Comment by zivy** [comment]
SimpleITK can read Tiffs. In general the answer is yes, you can register your images using the building blocks provided by SimpleITK. Unfortunately, SimpleITK is a toolkit (set of building blocks) and not a program for registration (a turnkey solution). You will have to implement the registration workflow yourself. 

We do have [examples](https://simpleitk.readthedocs.io/en/master/Examples/index.html) and a set of [Jupyter notebooks](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) illustrating various SimpleITK registration use cases.

**Comment by rojinsafavi** [comment]
Sorry I'm a newbie in image registration processing. What is the final output that I will get after registration? Will I get x,y, and z axis ? ( basically the rotation)?

 Right now I am trying your python notebooks, and I keep getting this error:
`RuntimeError                              Traceback (most recent call last)
<ipython-input-6-08df0daf77d1> in <module>()
      5                                             initialNeighborhoodRadius=5,
      6                                             numberOfIterations=4,
----> 7                                             multiplier=8)

/Users/rojinsafavi/miniconda2/lib/python2.7/site-packages/SimpleITK/SimpleITK.pyc in VectorConfidenceConnected(image1, seedList, numberOfIterations, multiplier, initialNeighborhoodRadius, replaceValue)
  69501 
  69502     """
> 69503     return _SimpleITK.VectorConfidenceConnected(image1, seedList, numberOfIterations, multiplier, initialNeighborhoodRadius, replaceValue)
  69504 class VectorConnectedComponentImageFilter(ImageFilter_1):
  69505     """

RuntimeError: Exception thrown in SimpleITK VectorConfidenceConnected: /scratch/dashboard/SimpleITK-OSX10.6-x86_64-pkg/SimpleITK/Code/Common/include/sitkMemberFunctionFactory.hxx:196:
sitk::ERROR: Pixel type: 16-bit unsigned integer is not supported in 3D byN3itk6simple36VectorConfidenceConnectedImageFilterE`

**Comment by zivy** [comment]
No problem. We are all new to something at some point or other.

The result of a registration is a transformation, this can be a rigid transformation (e.g. [Euler3DTransform](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1Euler3DTransform.html) or a variety of other transformations. Once you get that from the registration framework you will usually resample the "moving" image and combine the moving and fixed images in a variety of ways.

With respect to the error, in which noteobook is this happening? Also, what is your environment (looks like miniconda and python 2.7. This setup should work with simpleitk 1.2.0 on mac (does for me). Did you make any changes to the notebook?

**Comment by rojinsafavi** [comment]
Thanks for the explanation. It seems the the error is coming from the fact that my input image is an RGB. I was able to get rid of the error by only giving one of the channels to the script. Is that something that you were expecting? the tool is not compatible with multi-channel images yet?

**Comment by zivy** [comment]
As usual the answer is "it depends". Some algorithms/filters expect a single channel image, some work with multi-channel images. For example see [this segmentation notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/30_Segmentation_Region_Growing.ipynb) which starts by working on a single channel image and then works on a two channel image. 

For registration purposes you should probably use a single channel. This channel doesn't need to be the same in terms of intensity, but should represent the same structures across the different images. I do recommend reading a bit on registration so that you can perform it in a knowledgeable way. To extract a single channel from a multi-channel image use the [VectorIndexSelectionCastFilter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1VectorIndexSelectionCastImageFilter.html). 

Finally, RGB is a color space. SimpleITK has no notion of color space we just see this as a three channel image (it could be any of RGB, CMYK, HSV... or non of them, a multispectral image).

**Comment by blowekamp** [comment]
This sounds like an interesting applications for SimpleITK. I should find it useful for you problem. Please feel free to post back with additional questions.
