### ISSUE TITLE
ResampleImageFilter, missing method  SetExtrapolator()

### ISSUE THREAD

**Issue by myron** [SimpleITK/SimpleITK#747]
ITK (native) allows to specify interpolation values outside of the image boundaries using SetExtrapolator() method of  ResampleImageFilter, 
https://itk.org/Doxygen/html/classitk_1_1ResampleImageFilter.html

However in SimpleITK (python), there is no way to set the Extrapolator
https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ResampleImageFilter.html

In particular when resampling 3D images to a different resolution with linear interpolation, there is visible artifact on the very last row/column (because the default Extrapolator is zero padding)

please add SetExtrapolator() support. thanks

**Comment by blowekamp** [comment]
Thank you for reporting this missing functionality.
