### ISSUE TITLE
Bitmap To SimpleITK Image

### ISSUE THREAD

**Issue by pettaa123** [SimpleITK/SimpleITK#748]
Hi, I really need a way of creating a SimpleITK Image from a Bitmap, because I have dozens of Bitmaps in an array that I cant save on disk and read again to work on them.

Ist there a way with Marshal.Copy?

**Comment by pettaa123** [comment]
I’ll give the importimage filter a try

**Comment by blowekamp** [comment]
Here is an example which should help:
https://github.com/SimpleITK/SimpleITK/blob/master/Examples/CSharp/ImageGetBuffer.cs

**Comment by pettaa123** [comment]
I tried it like that:

` Bitmap bitmap = new Bitmap(@"C:\Data\L00000.bmp");  //bitmap.PixelFormat=8bppIndexed
IntPtr handle = bitmap.GetHbitmap();

uint width = (uint)bitmap.Width;
uint height = (uint)bitmap.Height;
SitkImage sitkImage = new SitkImage(width,height,PixelIDValueEnum.sitkUInt8);
IntPtr sitkImageBuffer = sitkImage.GetBufferAsUInt8();

Marshal.WriteIntPtr(sitkImageBuffer,handle);

SimpleITK.Show(sitkImage);`

But I retrieve only wrong 8 pixels

**Comment by blowekamp** [comment]
You usage of `Marshal.WriteIntPtr` would only copy  32-bits. The linked example used `Marshal.Copy` to copy the whole buffer.

**Comment by pettaa123** [comment]
`Bitmap bitmap = new Bitmap(@"C:\Data\L00000.bmp");  //bitmap.PixelFormat=8bppIndexed
BitmapData bitmapData = bitmap.LockBits(new Rectangle(0, 0, bitmap.Width,bitmap.Height ), ImageLockMode.ReadOnly, bitmap.PixelFormat);
int bitmapByteSize = bitmapData.Stride * height;
byte[] bitmapByteArray = new byte[bitmapByteSize];
//copy bitmap to byte[] before, because cant copy via Marshap from IntPtr to IntPtr
Marshal.Copy(bitmapData.Scan0, bitmapByteArray, 0, bitmapByteSize);
bitmap.UnlockBits(bitmapData);

SitkImage sitkImage = new SitkImage((uint)bitmap.Width,(uint)bitmap.Height,PixelIDValueEnum.sitkUInt8);
IntPtr sitkImageBuffer = sitkImage.GetBufferAsUInt8();
     
Marshal.Copy(bitmapByteArray, 0, sitkImageBuffer, bitmapByteSize);

SimpleITK.Show(sitkImage);`

It works like this. I think this worth an example because interacting with unmanaged memory is not that natural in C#. What do u say?

**Comment by blowekamp** [comment]
Including this in an example would be very nice!

I'd recommend taking the existing `ImageGetBuffer.cs` and renaming to to `ImageSetGetBuffer.cs` and showing how the buffer can be moved in each direction.

**Comment by blowekamp** [comment]
Thank you for your questions. If your problem is not resolved you are welcome to reopen the issue.
