### ISSUE TITLE
histogramequalization class

### ISSUE THREAD

**Issue by HyunjiEllenPak** [SimpleITK/SimpleITK#749]
Hi, I'm using simpleITK python version. and I'm struggling with AdaptiveHistogramEqualizationImageFilter.

I'm dealing with nifti volume (800x800x400) not using downsampling now.
Then, when I used AdaptiveHistogramEqualizationImageFilter with the volume, CPU utility was occupied 100% and It continued and didn't show me the result. The state and my code is below.
![image](https://user-images.githubusercontent.com/16814077/57578171-0baee700-74c2-11e9-9be9-532f0ee16b12.png)
![image](https://user-images.githubusercontent.com/16814077/57578213-955eb480-74c2-11e9-9da2-e5eac431a667.png)

So I think I used the wrong code(?!) or I did something wrong(?!).
How can I do histogram-equalization for the nifti volume correctly?

**Comment by zivy** [comment]
The issues you are seeing come from the original ITK implementation. Please see these two posts on the ITK discourse forum [[1](https://discourse.itk.org/t/adaptive-histogram-equalization-for-3d-images-long-run-time/1705)], [[2](https://discourse.itk.org/t/adaptivehistogramequalizationimagefilter-parameter-tuning/1738)].

Note that the standard histogram equalization algorithm for the whole image is not implemented in ITK as indicated in the second post.

**Comment by blowekamp** [comment]
The `AdaptiveHistogramEqualization` filters does local contrast enhancement. I'm guessing that you are looking for a traditional histogram equalization image filter to make the histogram flat.

We do provide a histogram matching filter[1][2]. If you provide a generated image with a flat histogram, ( perhaps generated with `np.linspace` converted to an sitk `Image`), you can do the equivalent operation.


[1]https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1HistogramMatchingImageFilter.html
[2] https://itk.org/Doxygen/html/classitk_1_1HistogramMatchingImageFilter.…

**Comment by blowekamp** [comment]
Thank you for your questions. If your problem is not resolved you are welcome to reopen the issue.
