### ISSUE TITLE
How to build a CPP example

### ISSUE THREAD

**Issue by chsasank** [SimpleITK/SimpleITK#75]
Hi,

I'm trying to use simpleitk.h in a CPP file. I was not able to figure out how to build this cpp file. 

I have built SimpleITK using instructions from [here](https://itk.org/Wiki/SimpleITK/GettingStarted/Visual_guide_to_building_on_Linux).

Can somebody please provide me with the g++ flags to compile this cpp file? Please excuse me if this is too basic, but I don't have experience with Cmake.

Sasank.

**Comment by blowekamp** [comment]
So first off I assume you have built and compiled SimpleITK from the source code?

Once SimpleITK is compiled, it is recommended you use CMake to configure your project. You will need to create a CMakeLists.txt file. The SimpleITK Examples folder is able to be run as an separate project which uses SimpleITK. I'd start by copying the following: https://github.com/SimpleITK/SimpleITK/blob/master/Examples/CMakeLists.txt#L1-L27 in you a new directly with the one cxx file used. This should be a quick way to get started using SimpleITK in C++.

**Comment by chsasank** [comment]
Thanks a lot! That is very helpful!
