### ISSUE TITLE
Direction, Origin, and Spacing based on reference image toggle option?

### ISSUE THREAD

**Issue by MichaelX9** [SimpleITK/SimpleITK#752]
I am using SimpleITKs ResampleImageFilter to perform a segmentation mask registration. It worked well for the vast majority of my cases but was unable to properly correct geometrical errors in one specific case. I noted that in ITKs original documentation, there existed an option to toggle on the use of the reference image to set the geometrical parameters of the mask (origin, spacing, and direction). I attempted to emulate this manually by setting them directly in my code, but since it still gives an error, I was wondering if the SetUseReferenceImage attribute was available to toggle in SimpleITK, or if it is just always default True?

**Comment by blowekamp** [comment]
There is no "toggle". There is only `[SetReferenceImage](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ResampleImageFilter.html#a850affc7fc3ce420c04f754d5d7773a5)`, which *immediately* sets the output image's size, origin, spacing and direction matrix. Later calls to `SetSize` for example will override the values of the reference image.

**Comment by MichaelX9** [comment]
I am using the SetReferenceImage field, but for some reason, when I observe the values for the input image and the segmentation mask after the resample filter runs, there are very minute differences in the two sets of origin, spacing, and direction values. Is there any particular reason this may be happening?  Thanks.

**Comment by blowekamp** [comment]
Can you share your code and the difference you are seeing?

**Comment by blowekamp** [comment]
Thank you for your questions. If your problem is not resolved you are welcome to reopen the issue.
