### ISSUE TITLE
How to assign a 3-dimension seed for fastmarching filter?

### ISSUE THREAD

**Issue by Ranglage** [SimpleITK/SimpleITK#753]
I've already read the example of the fastmarching filter.
In this example

>seedValue = 0
>trialPoint = (seedPosition[0], seedPosition[1], seedValue)
>fastMarching.AddTrialPoint(trialPoint)"

However, in ITK, the code will like this
>node = levelSetNode()
>node.SetValue(seedValue)
>node.SetIndex(seedPosition)
>seeds = itk.VectorContainer[
>    itk.UI, levelSetNode].New()
>seeds.Initialize()
>seedValue = 0
>seeds.InsertElement(0, node)

Here comes the question
If I want to process 3-dimension data, how to assign the trialPoint?
Is it like this?
>trialPoint = (seedPosition[0], seedPosition[1], seedPosition[2], seedValue)

**Comment by blowekamp** [comment]
> If I want to process 3-dimension data, how to assign the trialPoint?
Is it like this?

>>trialPoint = (seedPosition[0], seedPosition[1], seedPosition[2], seedValue)

That is correct.

More generically we could have the example be like:
```
 seedPosition = (1,2,3) 
 seedValue = 10 
trialPoint = (*seedPosition, seedValue)       
```

Do you think that would be clearer?

**Comment by blowekamp** [comment]
Thank you for your questions. If your problem is not resolved you are welcome to reopen the issue.
