### ISSUE TITLE
interpolation when more than 2 slices get involved 

### ISSUE THREAD

**Issue by hfarhidzadeh** [SimpleITK/SimpleITK#755]
Hi,

I want to know how simpleITK does the interpolation when more than 2 slices on Z dimension get involved? In other word, when the Z spacing is less than 0.5, how SimpleITK weights involved slices? what would be the coefficients?

Thanks

**Comment by blowekamp** [comment]
Hello,

With what algorithm/method/filter are you talking about? May of these do support an [interpolator](https://itk.org/SimpleITKDoxygen/html/namespaceitk_1_1simple.html#a7cb1ef8bd02c669c02ea2f9f5aa374e5), which treats x,y and z as equal for symmetric interpolation.

**Comment by hfarhidzadeh** [comment]
Thank you for quick response. I am using linear interpolation.

**Comment by zivy** [comment]
You appear to have answered your own question, but just in case: For linear inerpolation in 2D the underlying math is [bilinear](https://en.wikipedia.org/wiki/Bilinear_interpolation) and in 3D [trilinear](https://en.wikipedia.org/wiki/Trilinear_interpolation).

**Comment by hfarhidzadeh** [comment]
Let me clarify my question. I am trying to interpolate 3D image with Z spacing 0.4 and resample it to 1. Clearly I need to do interpolation for 3 consecutive slices. Now the question is how simpleITK does interpolation? It does interpolation of 3 slices at one, or it takes first 2 slices, do interpolation and then interpolated result and 3rd slice?
  
Thanks

**Comment by zivy** [comment]
Thanks for clarifying your question. With linear interpolation in 3D we only consider the two slices that are adjacent to the point at which you want the value.  If you want to take more slices into account during the interpolation you can use windowed-sinc interpolation, but I have never found that to be necessary.

To test if this really matters you can try linear interpolation and any of the more complex interpolation schemes, see @blowekamp's response above for link, and compare the results.
To check for the worst case, just look at the maximal absolute difference between all voxels. The [StatisticsImageFilter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1StatisticsImageFilter.html) also computes mean, std...

```
stat_filter = sitk.StatisticsImageFilter()
stat_filter.Execute(sitk.Abs(image_linear - image_lanczos))
print(stat_filter.GetMaximum())
```
where `image_linear` and `image_lanczos` were resampled with the same setup except the interpolator.

**Comment by blowekamp** [comment]
You may find this SimpleITK Notebook useful for experimenting with interpolators:
http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/Python_html/20_Expand_With_Interpolators.html

For your particular problem, which is downsampling or increasing the spacing, the interpolators, ( even a Sinc interpolator ) don't behave differently. By that I mean they still have the same size neighborhood as when you are keeping the same spacing. The nyquist limit may be reached, and introduction aliases are possible. To overcome this a preprocessing the input to the resample filter may be a good idea with a kernel such as a Gaussian.

**Comment by hfarhidzadeh** [comment]
Thank you to both of you @blowekamp @zivy . It seems SimpleITK takes last two slices and uses for interpolation. I have c++ code to replicate what I got from SITK python version and am getting exact same result.
