### ISSUE TITLE
how to preserve the direction cosine matrix after resampling

### ISSUE THREAD

**Issue by wpgao** [SimpleITK/SimpleITK#756]
Recently, I had write a batch to resample a series of MR volumes. However, there is one problem that the direction cosine matrix of the output volume is not the same as that of the input volume.
Thanks！

reader=sitk.ImageFileReader()
writer=sitk.ImageFileWriter()
reader.SetFileName(str(fi_d))
inputVolume=reader.Execute()
    resample=sitk.ResampleImageFilter()
    resample.SetInterpolator(sitk.sitkLinear)
    resample.SetTransform(sitk.Transform(3,sitk.sitkIdentity))
    resample.SetOutputDirection(reader.GetDirection())
    print(reader.GetDirection())
    resample.SetOutputOrigin(reader.GetOrigin())
    out_spacing=[1.0,1.0,1.0]
    resample.SetOutputSpacing(out_spacing)
    original_spacing=reader.GetSpacing()
    original_size=reader.GetSize()
    out_size=[int(np.round(original_size[0](original_spacing[0]/out_spacing[0]))),int(np.round(original_size[1](original_spacing[1]/out_spacing[1]))),int(np.round(original_size[2]*(original_spacing[2]/out_spacing[2])))]
    resample.SetSize(out_size)
    resample.SetDefaultPixelValue(0.0)
    out=resample.Execute(inputVolume)
    prefix="%s_iso.nii"%fileName
    resampleVolumeFilePath=os.path.join(self.saveVolumeDir,prefix)
    writer.SetFileName(str(resampleVolumeFilePath))
    writer.Execute(out)

**Comment by blowekamp** [comment]
Thank you for your report.

Your code is not properly formatted for Python with indent's so I can't follow the logic.

Have you checked the image before writing it to verify if the  `DirectionCosine` is properly set through the `Resample` filter?  We need to narrow down the problem to IO or how the `ResampleImageFilter` is being used.

**Comment by wpgao** [comment]
Sorry about that!
First, I read a MR volume from a file (.nii) using ImageFileReader; 
Second, I used ResampleImageFilter to resample the volume to an isotropic one. 
Last, I write the isotropic volume into a file(.nii) using ImageFileWriter.
The problem is how to get the DirectionCosine, it seems that there is no such a function. I try to use GetDirection, but not correct!

**Comment by blowekamp** [comment]
The`Image::GetDirection` is the method.

**Comment by wpgao** [comment]
I'm confused about it. The DirectionCosine shown in SPM display module was different from what I got using this function. So, is there any difference between them?

**Comment by blowekamp** [comment]
I don't know what "SPM display module" is, much less what processing it's doing.

**Comment by wpgao** [comment]
SPM is short for Statistical Parametric Mapping (https://www.fil.ion.ucl.ac.uk/spm/）, it can be used to voxel-based morphological analysis. Its module Display can be used to show the MR volume.

**Comment by wpgao** [comment]
The solution should be set the meta information, such as "srow_x","srow_y","srow_z", before using ImageFileWriter. Therefore, I should create an image, set these meta information and copy the resampled data into this image, and save it to a file!
