### ISSUE TITLE
Missing complex support for GetArrayFromImage and GetImageFromArray

### ISSUE THREAD

**Issue by brynolf** [SimpleITK/SimpleITK#763]
In python it is not possible to create a SimpleITK image from a complex numpy array, or to extract a complex numpy array from a SimpleITK image with pixel type sitkComplexFloat32 or sitkComplexFloat64.

**Comment by blowekamp** [comment]
It looks like the `sitk::Image::GetBufferAsComplexFloat32` methods are missing too.

**Comment by blowekamp** [comment]
Closed by #771

To get the buffer from an Image of complex pixel the scalar method should be called i.e GetBufferAsDouble or GetBufferAsFloat.
