### ISSUE TITLE
resample sitk image

### ISSUE THREAD

**Issue by IsmaelAlajeli** [SimpleITK/SimpleITK#774]
I tried to resample sitk image to a new spacing using the following code

import numpy as np

import SimpleITK as sitk

image = sitk.ReadImage(image_path)
resample = sitk.ResampleImageFilter()
resample.SetInterpolator = sitk.sitkLinear
resample.SetOutputDirection = image.GetDirection()
new_Origin = [-1.112846729755400e+02, -80.113129695816000, 20.969425400772000]
resample.SetOutputOrigin = (new_Origin)
new_spacing = [1.375, 1.375, 3]
resample.SetOutputSpacing = (new_spacing)
print(image)
orig_size = np.array(image.GetSize(), dtype=np.int)
orig_spacing = image.GetSpacing()
new_size = orig_size*(orig_spacing/new_spacing)
new_size = np.ceil(new_size).astype(np.int) #  Image dimensions are in integers
new_size = [int(s) for s in new_size]
resample.SetSize = (new_size)

newimage = resample.Execute(image)

it gives this error 

    none
    new_size = orig_size*(orig_spacing/new_spacing)
  Source: (none)
TypeError: unsupported operand type(s) for /: 'tuple' and 'list'

**Comment by dave3d** [comment]
orig_spacing and new_spacing are of types tuple and list.  You cannot divide tuple by a list.  You need to iterate through them and divide each number in orig_spacing by the corresponding number in new_spacing.

**Comment by IsmaelAlajeli** [comment]
@dave3d thanks for your reply 
orig_spacing = [1.625, 1.625, 3.6]
new_spacing= [1.375, 1.375, 3]
could you please let me know how can I iterate through them and divide each number in orig_spacing by the corresponding number in new_spacing?

**Comment by dave3d** [comment]
scaled_spacing = [x/y for x,y in zip(orig_spacing, new_spacing)]
new_size = [x*y for x,y in zip(orig_size, scaled_spacing)]

**Comment by blowekamp** [comment]
You can use a list comprehension combined [zip](https://docs.python.org/3.3/library/functions.html#zip). Here is an example with just two lists:
```
[ os/ns for os, ns in zip(orig_spacing, new_spacing)]   
```
