### ISSUE TITLE
Access Metadata from mhd file

### ISSUE THREAD

**Issue by JKomp** [SimpleITK/SimpleITK#782]
This question is similar to #356 but I get odd results...

Using the code from [https://simpleitk.readthedocs.io/en/master/Examples/DicomImagePrintTags/Documentation.html](url)

```
reader = sitk.ImageFileReader()

reader.SetFileName( filename )
reader.LoadPrivateTagsOn();

reader.ReadImageInformation();

for k in reader.GetMetaDataKeys():
    v = reader.GetMetaData(k)
    print("({0}) = = \"{1}\"".format(k,v))
```
I get the result:

```
(ITK_InputFilterName) = = "MetaImageIO"
```
so there's only one key, yet GetSpacing() and the other queries work fine. How do I access all the other tags that don't have direct accessors? If I try GetMetaData('0028|0030') for the spacing, I get an invalid key error.

I'm missing something here and I'd appreciate some help.

**Comment by zivy** [comment]
Hello @JKomp ,

This is a bit strange. Can you share your image? 

In any case, no matter the image format, the spacing, size, origin and direction cosine matrix are accessible via explicit function calls: `reader.GetSpacing()`, `reader.GetOrigin()`,...

When reading DICOM, this information will also be available via the `GetMetaData` method using the corresponding string keys.

The mention of MetaImageIO makes me suspect that the image isn't in DICOM format and thus it is likely that it's dictionary doesn't have a key corresponding to the string 0028|0030.

**Comment by zivy** [comment]
Sorry, just realized your question's title stated that you were working on a mhd file, so it is clear why the dictionary doesn't contain the string 0028|0030.  It appears that the file doesn't have any interesting information in the dictionary (it could have additional stuff, but not in this case).

**Comment by JKomp** [comment]
Thanks zivy. I can share the file if that would help. There is metadata somewhere because when I open the mhd/raw file with slicer 3D it shows metadata. I'm currently, actually trying to debug a completely different problem. I'm trying to translate the mhd/raw back to DICOM because some of the tools I'm using only understand DICOM. When I read the exported dcm file into slicer, it reads each individual slice as a new patient. Thus, something in my metadata is wrong and I'm digging into the original mhd file to figure it out.

The mhd/raw combination is pretty big so I don't think pasting it here would be good. Perhaps I only need the mhd for debug, or could the remaining metadata actually be buried in the raw?

**Comment by zivy** [comment]
In general, you should be able to open the mhd file in a text editor and see the human readable metadata.

If you are writing the slices one at a time, I am assuming a volume here, there is no connection between them. In DICOM nomenclature, they don't belong to the same study and series. Generally speaking the mhd format will not have study-series information (in some cases it might have this meta-data, but that is rare).

Likely [this example](https://simpleitk.readthedocs.io/en/master/Examples/DicomSeriesFromArray/Documentation.html) is what you want.

If this doesn't work for you, you'll have to share the file with us somehow so that we can look into what is going wrong.

**Comment by JKomp** [comment]
Thanks for the pointer. That was, indeed the code that I was using, though with some additional metadata. While I still don't understand where some of the metadata that Slicer finds in the original mhd/raw combo is coming from, I was able to solve the general problem I was fighting. The code you point to above doesn't set the Study Instance UID (0020|000d). That was causing my 409 slice dicom to be read in as 409 patients and 409 studies. Setting that value to 1 fixed the problem.
