### ISSUE TITLE
Access Metadata of NRRD without loading image array

### ISSUE THREAD

**Issue by jamesobutler** [SimpleITK/SimpleITK#788]
## Background
Currently using SimpleITK with Slicer nightly which is Slicer's SimpleITK fork which is at SimpleITK v1.2 with some backports (see [slicer-v1.2.0-2019-02-27-dc5c1a1](https://github.com/Slicer/SimpleITK/commits/slicer-v1.2.0-2019-02-27-dc5c1a1) branch).
I'm attempting to read the metadata of a NRRD image file, but I'm having trouble following the example as detailed below.

https://simpleitk.readthedocs.io/en/master/Examples/DicomImagePrintTags/Documentation.html#

> Reading an entire image potentially is memory and time intensive operation when the image is large or many files must be read. The image information and meta-data dictionary can be read without the bulk data by using the ImageFilerReader’s object oriented interface, with use of the ImageFileReader::ReadImageInformation method.

## MetaImage successfully has metadata read
I first tested the example with a MetaImage file.  I had an mhd file and then changed the filename of the corresponding data file so that the mhd was no longer connected to the RAW file to confirm it wasn't trying to load that file.
```python
reader = sitk.ImageFileReader()
reader.SetFileName("C:/Path/To/File.mhd")
reader.LoadPrivateTagsOn()
reader.ReadImageInformation()
reader.GetMetaDataKeys()
# successfully prints the meta data info
```
## Problem: NRRD fails to have metadata read
I then tested with a NRRD file which also has similar metadata keys. I had an mhd file and then changed the filename of the corresponding data file so that the nhdr was no longer connected to the RAW file to confirm it wasn't trying to load that file.

It is here where I'm trying to read NRRD metadata without loading the image array, but it is still trying to access the raw data file.
```python
reader = sitk.ImageFileReader()
reader.SetFileName("C:/Path/To/File.nhdr")
reader.LoadPrivateTagsOn()
reader.ReadImageInformation()
# fails with traceback
```
```log
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\JamesButler\AppData\Local\NA-MIC\Slicer 4.11.0-2019-07-06\lib\Python\Lib\site-packages\SimpleITK\SimpleITK.py", line 8676, in ReadImageInformation
    return _SimpleITK.ImageFileReader_ReadImageInformation(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_ReadImageInformation: D:\D\P\Slicer-0-build\ITK\Modules\IO\NRRD\src\itkNrrdImageIO.cxx:246:
itk::ERROR: NrrdImageIO(00000292DCC3BEA0): ReadImageInformation: Error reading C:/Users/JamesButler/Desktop/NHDR/CineVolume.seq.nhdr:
[nrrd] nrrdLoad: trouble reading "C:/Users/JamesButler/Desktop/NHDR/CineVolume.seq.nhdr"
[nrrd] nrrdRead: trouble
[nrrd] _nrrdRead: trouble reading NRRD file
[nrrd] _nrrdFormatNRRD_read: couldn't open the first datafile
[nrrd] nrrdIoStateDataFileIterNext: couldn't open "C:/Users/JamesButler/Desktop/NHDR/CineVolume.raw" (data file 1 of 1) for reading
```

**Comment by blowekamp** [comment]
The NRDD header only file or the `nhdr` file should be human readable ASCII, which you can inspect. From the error message "[nrrd] nrrdLoad: trouble reading "C:/Users/JamesButler/Desktop/NHDR/CineVolume.seq.nhdr" it appears you NRRD file has a header, and a separate data file. It appears the IO in unable to locate the data file. Does this file exist?

**Comment by zivy** [comment]
Hello @jamesobutler,

I believe it is just trying to access the raw file to confirm that it exists, not read it. As you intentionally modified the raw file name in the header the read fails. If you create an empty raw file (touch file_name.raw) you will see that the read image information succeeds, even if the raw file doesn't contain anything.

**Comment by jamesobutler** [comment]
Yes, I've purposely de-linked the header file from the data file to confirm, for sure, that the data file wasn't being read as part of the process of reading the header.

@zivy I created a "CineVolume.raw" 0 byte file using my editor and was then able to read the nhdr successfully. Is there another way to confirm that it was actually ignoring the RAW and not simply reading in the 0 byte RAW file?

So NRRD requires the data file always be present to read the separated header (nhdr), but for Metaimage the data file doesn't have to be preset to read the separated header (mhd).
I was expecting this behavior to be the same which caused the confusion. Is this something that could be standardized or is the current behavior related to the standard of each file type?

**Comment by blowekamp** [comment]
The NRDD IO for ITK is provided by the [Teem library](http://teem.sourceforge.net/index.html) this behavior would fall under them. I would presume there is some check to determine if the file is a valid NRRD, and there it is checked that the referenced file exists. So one might say you don't have a valid NRRD file.

To test it you could go to the other extreme and create an image which is larger than your available memory :grin:

**Comment by jamesobutler** [comment]
One of my use cases is that I have the NHDR file and the corresponding RAW file in my onedrive cloud account. I have the NHDR locally pulled down. The RAW file has its link to the cloud, but hasn't been downloaded locally. It will show up in the list of files in the directory, but when it is attempted to be used, it will then pull it down from the cloud.

For what I'm doing I just want to read the NHDR, but with what is currently happening, it is forcing the download of the RAW file which makes me think it is trying to read it when it doesn't need to.

**Comment by zivy** [comment]
Hi @jamesobutler,

Unfortunately, these behaviors are dependent on third party libraries, in this case [NrrdIO](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/NrrdIO/src/NrrdIO). Each library enforces different constraints so it is hard for ITK/SimpleITK to be perfectly consistent. 

From a quick look at the [ITK code](https://github.com/InsightSoftwareConsortium/ITK/blob/fc688e7a2c89967e3d6cbb779f87ec37a4e4750b/Modules/IO/NRRD/src/itkNrrdImageIO.cxx#L278) that SimpleITK wraps it appears that the raw intensities are not read, at least in ITK we are requesting that they not be read.

**Comment by blowekamp** [comment]
Out of curiosity would just checking if the file exist e.g. `bash -c "test -f some_file"` cause it to be pull down?

**Comment by jamesobutler** [comment]
If I use command prompt and do `IF EXIST "path/to/file.raw" ECHO The file exists`, then I get the output of "the file exists" and the file does not get pulled down. 

If I use python and do a `os.path.exists("path/to/file.raw")` call, the raw file also does not get pulled down.

**Comment by zivy** [comment]
Based on your test, I suspect that the nrrd library is trying to open the file as a way of checking that it exists, and that triggers the download, but this is just a hunch.

**Comment by jamesobutler** [comment]
I'm not a normal bash user but using git-bash on my windows machine `bash -c "test -f some_file"` did seem to pull it down.

**Comment by blowekamp** [comment]
I am closing this issue it sounds like it related to how the lower level NRRD / teem library handle reading files and how that interacts with your cloud volume. So, I think this is outside the scope of our interface.
