### ISSUE TITLE
SimpleITK Compile Issue while Performing Build Step for PCRE 

### ISSUE THREAD

**Issue by johnashcroft105** [SimpleITK/SimpleITK#79]
I'm building SimpleITK on MacOSX 10.11.5 from github using the following code

cd ~
git clone https://github.com/SimpleITK/SimpleITK
cd SimpleITK
mkdir build
cd build
cmake ../SuperBuild

I get the following error, which has been reported previously (https://github.com/SimpleITK/SimpleITK/issues/33)

[ 19%] Performing build step for 'GTest'
Scanning dependencies of target gtest
[ 25%] Building CXX object CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 50%] Linking CXX static library lib/libgtest.a
[ 50%] Built target gtest
Scanning dependencies of target gtest_main
[ 75%] Building CXX object CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[100%] Linking CXX static library lib/libgtest_main.a
[100%] Built target gtest_main
[ 20%] Performing install step for 'GTest'
[ 21%] Completed 'GTest'
[ 21%] Built target GTest
Scanning dependencies of target PCRE
[ 23%] Performing build step for 'PCRE'
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** [PCRE-prefix/src/PCRE-stamp/PCRE-build] Error 2
make[1]: *** [CMakeFiles/PCRE.dir/all] Error 2
make: *** [all] Error 2

Despite running the suggested workaround:

cmake -DCMAKE_CXX_COMPILER:STRING=/usr/bin/clang++ -DCMAKE_C_COMPILER:STRING=/usr/bin/clang ../SuperBuild

I still get the same error when running
sudo make

[ 10%] Built target ITK
[ 21%] Built target Lua
[ 32%] Built target GTest
[ 34%] Performing build step for 'PCRE'
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** [PCRE-prefix/src/PCRE-stamp/PCRE-build] Error 2
make[1]: *** [CMakeFiles/PCRE.dir/all] Error 2
make: *** [all] Error 2

Any suggestions for fixing this issue?

Thanks in advance

**Comment by dave3d** [comment]
I've seen that issue before in the past.  Did you recently install or upgrade Xcode?  Have you run the "xcode-select" command to set the active developer directory?  If not, give that a try.

**Comment by johnashcroft105** [comment]
I don't use Xcode for anything, and haven't upgraded or installed it recently. I have version 7.3.1

xcode-select --version
//returns: 
xcode-select version 2343.
// and I ran:
sudo xcode-select --reset
// for good luck
xcode-select --print-path
// returns:
/Applications/Xcode.app/Contents/Developer

still no luck with the PCRE build

**Comment by dave3d** [comment]
What version of cmake are you running?  As I said in that previous, closed issue, back then I worked around it by building my own copy of swig.  I think, though, that the problem went away with more recent versions of cmake.

**Comment by johnashcroft105** [comment]
Hey Dave,
 
You were right. My X-Code was out of date. I updated to version 8.1, but was still running into the same problem.

The solution was to download command line tools from the apple developer site as follows:

1) Open Xcode app. 2) Click on Xcode > Open Developer Tools > More Developers Tools. That will take you to Downloads for Apple Developers web site. Use your AppStore Id to login. 3) Download Command Line Tools for your Mac OS X version.

This appears to be a common problem: eg. http://stackoverflow.com/questions/23260748/manual-install-of-xcode-command-line-tools-not-working/23319506#23319506

Thanks for your help.

Cheers.

**Comment by dave3d** [comment]
I'm glad to hear that you're figured out the solution.  And it's good that we now have the answer here for others to find.

**Comment by johnashcroft105** [comment]
Had another tripup during the build.

When turning WRAP_PYTHON  ON I got the following error: 
# 
ERROR:

 CMake Error at
 /Applications/CMake.app/Contents/share/cmake-3.5/Modules/FindPackageHandleStan
 dardArgs.cmake:148 (message):
   Could NOT find PythonLibs: Found unsuitable version "2.7.10", but required
   is exact version "2.7.12" (found /usr/lib/libpython2.7.dylib)
 Call Stack (most recent call first):

 /Applications/CMake.app/Contents/share/cmake-3.5/Modules/FindPackageHandleStan
 dardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)

 /Applications/CMake.app/Contents/share/cmake-3.5/Modules/FindPythonLibs.cmake:
 265 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
   /Users/markrichardson/SimpleElastix/src/CMake/sitkLanguageOptions.cmake:71
 (find_package)
   SuperBuild.cmake:236 (include)
   CMakeLists.txt:24 (include)

#
SOLUTION:

1) open  /Users/xxxxxx/SimpleElastix/src/CMake/sitkLanguageOptions.cmake in textwrangler
2) Change Line71 from:
    find_package ( PythonLibs ${PYTHON_VERSION_STRING} EXACT ${_QUIET_LIBRARY} )
To:
   find_package ( PythonLibs ${PYTHON_VERSION_STRING} )

I wonder if you've run into this before, or if you have any thoughts on this one. The rest of the build ran well, and all the tests were successful.

#
/ /
NOTE:
python -v     # returns:
/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.pyc matches /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py
import site # precompiled from /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.pyc

... etc ...
#

Cheers

**Comment by blowekamp** [comment]
Unfortunately it's not too uncommon for CMake to "automatically" find and python executable and a python library whose versions don't match or are from different installed python. You should verify that the PYTHON_EXECUTABLE and the PYTHON_LIBRARY refers to the same installed Python. Otherwise problems may occur.

Also SimpleElastix may be missing important features that SImpleITK has. Please report SimpleElastix issues in there repo first:
https://github.com/kaspermarstal/SimpleElastix

**Comment by johnashcroft105** [comment]
File was here: 

/Users/xxxxxx/SimpleITK/src/CMake/sitkLanguageOptions.cmake

sorry for that
