### ISSUE TITLE
GetImageFromArray does not work 

### ISSUE THREAD

**Issue by bionick87** [SimpleITK/SimpleITK#791]
I tried a thousand solutions but when I download the new pip / binaries GetImageFromArray doesn't work.

line 3727, in __init__
    this = _SimpleITK.new_Image(*args)
RuntimeError: Exception thrown in SimpleITK new_Image: /tmp/SimpleITK/Code/Common/src/sitkImage.cxx:89:
sitk::ERROR: Unsupported number of dimesions specified by size: [ 2457600 ]!

**Comment by dave3d** [comment]
You're using SimpleITK version 1.2.0?  I just ran a little test script, and it worked ok for me.  Here's my script:

```
import platform
import SimpleITK as sitk
import numpy as np

arr = np.zeros((10,10))

print("numpy array:", arr)

print(sitk)
print(sitk.Version())
print ("Python version:", platform.python_version())


img = sitk.GetImageFromArray(arr)
print("sitk image size:", img.GetSize())
```

And here's the output I get:

> numpy array: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
>  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
> <module 'SimpleITK' from '/Users/dchen/anaconda3/lib/python3.7/site-packages/SimpleITK/__init__.py'>
> SimpleITK Version: 1.2.0 (ITK 4.13)
> Compiled: Jan  3 2019 21:33:26
> 
> Python version: 3.7.3
> sitk image size: (10, 10)

**Comment by bionick87** [comment]
Hi dave,

Thanks. 

It is a strange error but I tried simple itk in one machine and then in another, in the first it works in the other one.

I have re-downloaded anaconda but it doesn't want to work and gives me the same error, I don't know what to do honestly!

I wanted to know if simple itk interacts with some system libraries and what can it generate in this error?

import numpy as np
import nibabel as nib
import os
import SimpleITK  as sitk

def nii_load_itk(path):
    return sitk.ReadImage(path)

def convert_to_numpy(Image):
    return sitk.GetImageFromArray(Image)

def load_vol(path):
     return convert_to_numpy(nii_load_itk(path))


path   = "./anyfile.nii.gz"
nib_vol  = nib.load(path).get_fdata()
print(nib_vol.shape)

itk_vol = load_vol(path)
print(itk_vol.shape)


anaconda version:

curl -O https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh
 
Best,

Nico

**Comment by blowekamp** [comment]
```
sitk::ERROR: Unsupported number of dimesions specified by size: [ 2457600 ]!
```

This error message indicates that your NumPy array is 1D if size 2457600. SimpleITK does not support 1D image.

Please provide a minimal example to reproduce your problem. Dave provided a good example of what is expected. Were you able to execute Dave's code OK?

**Comment by dave3d** [comment]
Your function convert_to_numpy uses sitk.GetImageFromArray which converts **from** a numpy array **to** a SimpleITK Image.  If you really want to convert **to** a numpy array, you need to use sitk.GetArrayFromImage.

I tried your sample code, and you are calling sitkGetImageFromArray and passing in a SimpleITK Image when it expects a numpy array.

**Comment by bionick87** [comment]
You're right, my mistake. Thank you!
