### ISSUE TITLE
Applying registration transforms onto points/Physical vs. Index Space

### ISSUE THREAD

**Issue by BenjaminAgthe** [SimpleITK/SimpleITK#792]
Hello channel,

I am quite new to SITK. I have a similar problem to https://github.com/SimpleITK/SimpleITK/issues/532. My sitk transformations are working for images, but not for points by using TransformPoints.

My problem is the following: I have to knee label images of femur bone, from which I want to take sample points of one fixed image and find the corresponding points in the moving image. Therefore I calculate a transform from moving to fixed and use its TransformPoints to calculate the corresponding points in the other image. 

My pipeline is as follows:

1. My initial points are sampled in the index space since i convert the fixed image to a numpy array.

2. Calculating a normal affine transform

3. warp images using the sitk resampler (should not do that much, since both images have same resolution (384, 384, 160)

4. warp points using transform points.

As you can see in the pics below: The points are aligned with the transform and have similar shape to the registered image. However it is smaller!? 

Anyone an idea!?
Thanks in advance

![Misaligned_images](https://user-images.githubusercontent.com/39301654/61784941-f7189480-ae0a-11e9-8fc3-dbadc449bb78.png)

![registered](https://user-images.githubusercontent.com/39301654/61784942-f7189480-ae0a-11e9-9847-b83f156d8970.png)

![registered points](https://user-images.githubusercontent.com/39301654/61784943-f7189480-ae0a-11e9-9e2f-9fc8d8e0e4d0.png)

**Comment by blowekamp** [comment]
You said your fixed points are in the index space of the fixed image. But at step 4 you transform point are still in physical space. Perhaps you need to convert from physical space to index space with `fixed_image.TransformPhysicalPointToContinuousIndex`

Also in step 3 you need to specify the output meta-data for the physical range of the resulting image.

**Comment by BenjaminAgthe** [comment]
So full pipeline would be: 

1. Sample point indices

2. Get points by using `moving_image.TransformContinuousIndexToPhysicalPoint`

3. Calculate transform (done in physical space) from moving to fixed

4. `transform.TransformPoints(point)`

5. Get indices by using `fixed_image.TransformPhysicalPointToContinuousIndex`

**Comment by blowekamp** [comment]
I believe your problem as been solved so I'm closing the issue. Please re-open if needed.

**Comment by cntontis** [comment]
(I dont know if I should open a new issue, but my problem is exactly the same.) The only difference is that the proposed approach doesn't work for me.
Images are the same size. and when I use the resample as in this issue it works fine.
Here is my final transformation
```
itk::simple::Transform
 BSplineTransform (000002A6FF0FF0A0)
   RTTI typeinfo:   class itk::BSplineTransform<double,2,3>
   Reference Count: 3
   Modified Time: 1211661
   Debug: Off
   Object Name:
   Observers:
     none
   CoefficientImage: [ 000002A683BA9C20, 000002A683BAA190 ]
   TransformDomainOrigin: [-0.625, -0.625]
   TransformDomainPhysicalDimensions: [2304.25, 1312.25]
   TransformDomainDirection: 1 0
0 1

   GridSize: [9, 9]
   GridOrigin: [-384.667, -219.333]
   GridSpacing: [384.042, 218.708]
   GridDirection: 1 0
0 1
```

and here is an example of my attempt to transform a point
```python
[2173. 1233.]    # indexed point
(2173.0, 1233.0) # moving_image.TransformContinuousIndexToPhysicalPoint([2173. 1233.])
(2174.3411790844652, 1327.8135024643282) # transformed physical point
(2174.3411790844652, 1327.8135024643282) # moving_image.TransformPhysicalPointToContinuousIndex((2174.3411790844652, 1327.8135024643282))
```
for the last line i also trying using the fixed image to transform it but I wasn't very successful. Any help is more than welcome
