### ISSUE TITLE
SimpleITK .ImageSeriesReader cannot use GetGDCMSeriesFileNames

### ISSUE THREAD

**Issue by carrylv** [SimpleITK/SimpleITK#794]
run pycharm, error in /usr/bin/python3.5 :munmap_chunk(): invalid pointer

**Comment by blowekamp** [comment]
Hello, thank you for reporting your issue. Please see ["Report an Issue"](https://github.com/SimpleITK/SimpleITK#support), for a list of important information that should be included when reporting a bug.

**Comment by blowekamp** [comment]
This bug report lacks information to reproduce. If information is added so that it can be reproduced, then the issue can be reopened and confirmed.
