### ISSUE TITLE
Feature request - BinaryPruningImageFilter

### ISSUE THREAD

**Issue by szhorvat** [SimpleITK/SimpleITK#800]
This is a request to add `BinaryPruningImageFilter` to SimpleITK. Even if it is a 2D-only filter, this is extremely useful functionality. Adding it should not wait for a working 3D implementation.

**Comment by blowekamp** [comment]
I will look in to wrapping this filter again in the next week or so. If I recall correctly, there were other issues with this filter. Would you be willing to test out the PR and and see if the filter will work for your use case?

**Comment by szhorvat** [comment]
> Would you be willing to test out the PR and and see if the filter will work for your use case?

Yes, absolutely.

**Comment by szhorvat** [comment]
I think I would be able to build SimpleITK from sources and test the function from C++ when it's ready. I have something to hook up SimpleITK to Mathematica—for personal use—using other tools than SWIG. This is how I would be using it. Mathematica has a pruning filter but it's not good enough for my use case (it is extremely slow).

**Comment by blowekamp** [comment]
Closed by #803
