### ISSUE TITLE
How to get corresponding point coordinates from registration results?

### ISSUE THREAD

**Issue by cs123951** [SimpleITK/SimpleITK#802]
Hi, I have applied affine registration to get the warped image.

`   import SimpleITK as sitk
    elastixImageFilter = sitk.ElastixImageFilter()
    elastixImageFilter.LogToConsoleOff()

    elastixImageFilter.SetFixedImage(sitk.ReadImage(fixed_filename))
    elastixImageFilter.SetMovingImage(sitk.ReadImage(moving_filename))
    para = sitk.GetDefaultParameterMap("affine")
    para["WriteResultImage"] = ["false"]
    elastixImageFilter.SetParameterMap(para)
    elastixImageFilter.Execute()

    result_img = elastixImageFilter.GetResultImage()`

But I do not know how to get get corresponding point coordinates.
That is, for (x0,y0,z0) in fixed image, (x1,y1,z1) in moving image, I want to find the corresponding point in the warped image.
I am not sure if SimpleITK has any kind of this  function.

Thank you.

**Comment by zivy** [comment]
You appear to be using SimpleElastix and not SimpleITK. Please ask the question on their [GitHub issues](https://github.com/SuperElastix/SimpleElastix/issues),
