### ISSUE TITLE
.NET API: Unexpected behavior of Equals (VectorUInt32)

### ISSUE THREAD

**Issue by Voxelworld** [SimpleITK/SimpleITK#829]
SimpleITKs Vector comparison (e.g. VectorUInt32) seems to be mapped to the default .NET implementation, so when comparing different vector instances with the same values it fails.

Code to reproduce:
```
var a = new itk.simple.VectorUInt32(new uint[] { 1, 2, 3 });
var b = new itk.simple.VectorUInt32(new uint[] { 1, 2, 3 });

a.Equals(b) // FALSE
a == b // FALSE
a.Equals(a) // TRUE
```

A custom implementation would be very helpful to support simple comparision like
`image1.GetSize() == image2.GetSize()`.

**Comment by blowekamp** [comment]
Thank you for your suggestion. The interface for std::vector comes the default SWIG wrapping for the class. To change the interface either a contribution to SWIG needs to be made or the wrapping from the vector class needs to be copied and improved locally.
