### ISSUE TITLE
Remove label objects with properties below or greater than a threshold 

### ISSUE THREAD

**Issue by yliu7366** [SimpleITK/SimpleITK#841]
ITK has LabelShapeOpeningImageFilter to remove label objects with properties below or greater than a lambda threshold but I can not find the filter in SimpleITK. What is the SimpleITK way to edit label objects? Is it possible to include LabelShapeOpeningImageFilter in SimpleITK? Thanks.

**Comment by blowekamp** [comment]
The shape statistics can be computed with [`LabelShapeStatisticsImageFilter` ](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1LabelShapeStatisticsImageFilter.html) in SimpleITK. Then the [`ChangeLabelImageFilter`](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ChangeLabelImageFilter.html) or [`ChangeLabelLabelMapFilter'](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ChangeLabelLabelMapFilter.html) can be used.

Here is an example on how to combine them:
```
In [1]: import SimpleITK as sitk                                                                                                                                                                     

In [2]: img = sitk.ReadImage("cthead1.png")                                                                             

In [3]: labels = sitk.SLIC(img)                                                                                                                                                                      

In [4]: stats = sitk.LabelShapeStatisticsImageFilter()                                                                                                                                               

In [5]: stats.Execute(labels)                                                                                                                                                                        

In [6]: relabelMap =  { i : 0 for i in stats.GetLabels() if stats.GetRoundness(i) < .5 }                                                                                                             

In [7]: output = sitk.ChangeLabel(labels, changeMap=relabelMap)                                                                                                                                      

```

This example is similar to what can be accomplished with the `LabelShapOpeningImageFilter`. However, much more complicated criteria can be constructing so this approach is significantly more flexible and powerful, so there is not need to wrap that filter in SimpleITK.

**Comment by yliu7366** [comment]
Great, thank you! this is exactly what I need. A followup question: after running sitk.ChangeLabel, I used sitk.LabelMapToBinary to save the modified label map to a binary image but failed with error message about 32bit unsigned integer unsupported. Please help.

My code and the error message:

output = sitk.ChangeLabel(labels, changeMap=relabelMap) 
labelImg = sitk.LabelMapToBinary(output)

RuntimeError: Exception thrown in SimpleITK LabelMapToBinary: /tmp/SimpleITK/Code/Common/include/sitkMemberFunctionFactory.hxx:209:
sitk::ERROR: Pixel type: 32-bit unsigned integer is not supported in 2D byN3itk6simple27LabelMapToBinaryImageFilterE

**Comment by blowekamp** [comment]
As per the error message, you pixel type is of "32-bit unsigned integer" or `sitkUInt32`. The LabelMap filters require a pixel types like `sitkLabelUInt32`. 

If you want an image of 0's and 1's then you can simply wrote `binaryImage = output != 0`.
