### ISSUE TITLE
Issue reading HDF5 image

### ISSUE THREAD

**Issue by mbrist** [SimpleITK/SimpleITK#844]
I have an HDF5 image that I am able to read with other libraries. But when I try to load with sitk.ReadImage I get the following error:

```
HDF5-DIAG: Error detected in HDF5 (1.8.17) thread 0:
  # 000: D:\a\1\sitk-build\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5D.c line 358 in itk_H5Dopen2(): not found
    major: Dataset
    minor: Object not found
  # 001: D:\a\1\sitk-build\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5Gloc.c line 430 in itk_H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  # 002: D:\a\1\sitk-build\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5Gtraverse.c line 861 in itk_H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  # 003: D:\a\1\sitk-build\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found

Traceback (most recent call last):
RuntimeError: Exception thrown in SimpleITK ReadImage: D:\a\1\sitk-build\ITK\Modules\IO\HDF5\src\itkHDF5ImageIO.cxx:1041:
itk::ERROR: HDF5ImageIO(000001EC3F5C46B0): H5Dopen2 failed
```

I am struggling to interpret this error - is it a problem with the .h5 file, or could I be missing some dependencies?

**Comment by blowekamp** [comment]
I  do not recognize these error. What other libraries are you able to read the file with? Please provide the needed basic information in your issue: https://github.com/SimpleITK/SimpleITK#report-an-issue

**Comment by rdsouza15** [comment]
@mbrist @blowekamp Was there any resolution to this? 

I am running into the same issue while trying to read in a HDF5 file. The file and datasets can be opened using HDFView.  I have followed the examples in the following but continue to run into this error. Any help is greatly appreciated. 

> https://simpleitk.readthedocs.io/en/master/Examples
> https://itk.org/Doxygen/html/examples.html

**Comment by blowekamp** [comment]
The is not current Image IO to handle standard HDF5 Image files.

Here is the [itk::HDF5ImageIO](https://itk.org/Insight/Doxygen/html/classitk_1_1HDF5ImageIO.html) class. The documentation described a non-standard HDF5 Image stored. I presume you are trying to read a file with this format standard format: https://support.hdfgroup.org/HDF5/doc/ADGuide/ImageSpec.html

I would suggest posting to [ITK discourse](https://discourse.itk.org) to ask if anyone as an ITK image file reader for the HDF5 Image specfication.
