### ISSUE TITLE
support for point sets

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITK#86]
Add support for point-sets in the registration framework:

1. In the ImageRegistrationMethod class, allow the user to provide a point-set as the samples for intensity based registration (currently a workaround to doing this is to create a mask based on the point set).

2. Support point-set to point-set registration.

3. Support point-set (surface) to image registration.

4. Support point-set Read/Write.

**Comment by blowekamp** [comment]
There is no plan to add point set to simpleitk.
