### ISSUE TITLE
3D point cloud registration?

### ISSUE THREAD

**Issue by ectg** [SimpleITK/SimpleITK#860]
Hi,

Does SITK (Python) have functions that perform point cloud or mesh registration?

(I was unable to find anything in the documentation. )

Thanks!

**Comment by zivy** [comment]
Hello @ectg,
SimpleITK does not have point cloud based registration. 

You can try itk (Python) which I believe has all the components you need to create the relevant registration pipeline, see [this C++ example](https://itk.org/Doxygen/html/Examples_2RegistrationITKv4_2IterativeClosestPoint2_8cxx-example.html) which you will need to translate into Python.

Or you could try SimpleElastix which appears to have [relevant functionality](https://simpleelastix.readthedocs.io/PointBasedRegistration.html).
