### ISSUE TITLE
Feature request - Distance measurements, colocalization

### ISSUE THREAD

**Issue by landowark** [SimpleITK/SimpleITK#862]
I'd like to suggest a way to determine the edge-to-edge or centre-to-centre distances for 3D labelled objects in sitk as well as maybe a way to tell the number of overlapping voxels for each object. This feature is fairly common among imagej plugins and is very useful.

**Comment by dave3d** [comment]
For overlapping objects, you should be able to get the intersection and that use LabelShapeStatisticsImageFilter to count the number of voxels in that intersection with the GetNumberOfPixels method.

Also you can use the same filter to get the centroid of each object with the GetCentroid method.

I'm not sure about edge to edge distance.  Perhaps compute a distance map for one object.  And then use the other object as a mask and find the minimum distance with that mask?

**Comment by landowark** [comment]
Ah. Okay, that worked great. Can I stll request distance as a feature, or would I have to take that to ITK itself?

**Comment by blowekamp** [comment]
I still don't fully understand your requests. Perhaps including a couple images for example would help.

But yes, this is something that would need to be done in ITK. However, I have been thinking about expanding the label measure measurements, it is of interest to me.

**Comment by landowark** [comment]
In our work we would like to know the distance of certain genes from the nuclear center as it becomes apparent that the spatial organization affects the transcription. It's also useful to know (for example) the distance of a protein from the edge of the nucleus. 
I currently trying to determine how much two proteins colocalize and at what distance from the edge of the nucleus (most of the examples of sitk I've seen are things like MRIs but it works for 3D-SIM images pretty well.)
I'm using an ImageJ plugin called DiAna (https://www.sciencedirect.com/science/article/pii/S1046202316304649?via%3Dihub) at the moment, but I hate Java and it's better for me if I have more control over the program than ImageJ allowed.
![1-s2 0-S1046202316304649-fx1_lrg](https://user-images.githubusercontent.com/14314236/67986084-3fa8d080-fbf8-11e9-827d-855ac9cff505.jpg)

**Comment by richardbeare** [comment]
A relatively standard approach that might work for you is to compute a distance transform from the nuclei. The [distance transform](https://itk.org/SimpleITKDoxygen120/html/classitk_1_1simple_1_1SignedMaurerDistanceMapImageFilter.html) creates takes a mask image and transforms it to another image in which every voxel is the distance from that position to the nearest position in the mask with the other value (i.e. off voxels get replaced with the distance to the nearest on voxel, and vice versa). The "signed" in the filter name indicates that both on and off voxels get replaced. 

You can compute a minimum or mean of this field in the segmented protein blobs. This will give you a measure related to the distance between the edges of the masks.

If you're interested in the distance between centroids then you're probably best off extracting the centroids with one of the shape filters and computing the distances directly with python/R whatever. You could also do a mix of both - compute the distance map from the nucleus mask then look up the distance at the location of the protein centroids.

**Comment by zivy** [comment]
Hello @landowark,

Would you be interested in helping us develop a notebook that does what you need? We would need you to contribute some data, making it freely and publicly available. We would also need your guidance with respect to the background (biological motivation for the question the notebook is answering), and what exactly you want to calculate. The result will go into our [main notebook repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks).

I am happy to work with you on developing such a notebook that includes the functionality you need (I guess some sort of segmentation and then the overlap measures, distances between objects etc.). 

If you are interested, please contact me directly (zivyaniv@nih.gov).

**Comment by dave3d** [comment]
Addressed by https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/commit/fc79e1f2ec6ab2fd9ee87c3a0fff254da6c8babd
