### ISSUE TITLE
Error when build simpleElastix with SImpleITK

### ISSUE THREAD

**Issue by colddie** [SimpleITK/SimpleITK#865]
I got following error when building SimpleElastix with version 1.2 SimpleITK
/home/tsun/bin/SimpleElastix-master/build/Code/BasicFilters/src/sitkStatisticsImageFilter.cxx:140:1: error: invalid user-defined conversion from ‘itk::Image<double, 2>::ConstPointer {aka itk::SmartPointer<const itk::Image<double, 2> >}’ to ‘itk::DataObject*’ [-fpermissive]
 filter->SetInput( 0, image1 );

I know it is a different build-up, but I guess the error is related to SimpleITK.

Thanks

**Comment by blowekamp** [comment]
Yes, it is a fork of this project. Probably best to report it here: https://github.com/SuperElastix/SimpleElastix

This is related to building against ITKv5. SimpleITK have been updated for compatibility with ITKv5. This patch looks like it may have been the update for this issue:
6052c5def2e20cfab5425ed62776ddc23f0bfc6f
