### ISSUE TITLE
Discussion about documentation 

### ISSUE THREAD

**Issue by chsasank** [SimpleITK/SimpleITK#87]
Hi,
Can you please give some instructions to build doxygen documentation of the project?
I tried passing `-DBUILD_DOXYGEN:BOOL=ON` to cmake superbuild but it doesn't seem to work:

```
-- Configuring done   
-- Generating done      
CMake Warning:     
CMake Warning:  
  Manually-specified variables were not used by the project:    
                                   
    BUILD_DOXYGEN                          
                                                               
-- Build files have been written to: /home/users/sasank/simpleitk_lua/bb/build
```

I am thinking of using doxygen xml to create sphinx documentation using [breathe](https://breathe.readthedocs.io/en/latest/index.html).

Thanks in Advance,
Sasank.

PS: It'll be great if you can also upload xml output of doxygen.

**Comment by dave3d** [comment]
The documentation isn't currently built in the Superbuild.  To build the docs, you need to set BUILD_DOXYGEN in the SimpleITK-build sub directory within the Superbuild directory.  Then you can do a make Documentation within SimpleITK-build.

Let us know how that sphinx/breathe process goes for you.  I looked into it a little bit, but, having never used it before, I didn't get very far.  It would be really cool if you could get it working.

**Comment by chsasank** [comment]
I have compiled (some) docs by 

```bash
mkdir build && cd build
cmake ../SimpleITK/ -DBUILD_DOXYGEN=ON
make Documentation
```

This produced doxygen XML at `build/Documentation/xml`. 

I got some breathe documentation up and working at https://github.com/chsasank/sitk-docs .

To use this, copy doxygen xml output to `source/doxyxml` and run `make livehtml`.
I already added some documentation sourced from simpleitk notebooks with some modifications of my own. Have a look at it. I think it looks awesome ;)

Idea is to host this on readthedocs.

SimpleITK is pretty awesome as I realise after using it more and more. But documentation is very lacking. We can write user guide along the lines of http://scikit-image.org/docs/stable/user_guide.html
and convert examples with lot more explantation/images like here: http://scikit-image.org/docs/stable/auto_examples/index.html

**Comment by chsasank** [comment]
Check this out. I have deployed on gh-pages.
 https://chsasank.github.io/sitk-docs/index.html

**Comment by blowekamp** [comment]
Wow that looks awesome!

Can you get the full C++ API referenced there?

Regarding the example. The SimpleITK-Notebooks is the place for learning to use SimpleITK in Python and now R. These are designed to have prose and code to explain things.

The [Examples](https://github.com/SimpleITK/SimpleITK/tree/master/Examples) has repeated examples for many languages. The difficulty with these is that they are repeated in different languages and duplicate prose would not be maintainable. A system is needed to write the prose and integrate all languages in to the resulting document.

Do you think you could automate the build process of the Sphinx documentation? Please look at the .travis.yml [.travis.yml](https://github.com/SimpleITK/SimpleITK/blob/master/.travis.yml) file.

**Comment by chsasank** [comment]
>Can you get the full C++ API referenced there?

Ideally, yes. But I couldn't get it working because some errors with Latex or because immaturity of breathe. 

>The Examples has repeated examples for many languages. The difficulty with these is that they are repeated in different languages and duplicate prose would not be maintainable.

We  should be able to do something there. Gallery is made by http://sphinx-gallery.readthedocs.io/
It supports only python for now. May be we can modify the html output with js a bit to include equivalent code for other languages.  Like [here](https://itk.org/ITKExamples/src/Core/QuadEdgeMesh/CutMesh/Documentation.html).


> The SimpleITK-Notebooks is the place for learning to use SimpleITK in Python and now R.

A user guide more like [this](https://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py) would be more useful. Notebooks cannot replace usual documentation.

> Do you think you could automate the build process of the Sphinx documentation? 

We should be able to do it. Instructions for breathe are here: https://breathe.readthedocs.io/en/latest/readthedocs.html

**Comment by chsasank** [comment]
Hi,

I've modified sphinx-gallery to support python and lua. (https://github.com/sphinx-gallery/sphinx-gallery/pull/197)
From this point, supporting other languages shouldn't be so hard. Also, sharing prose between examples should be easily implementable.

Now, the question is would you people be interested in contributing to such a documentation? I'm no expert in registration and segmentation. Therefore, your help is necessary to explain those examples and to make this whole gallery thing happen. 

If you're interested, I'll write/fix all the sphinx related code. 

Sasank.

paging @dave3d, @blowekamp

**Comment by blowekamp** [comment]
The biggest concern here is the duplication of efforts and locations for information causing problems for maintaining current information.

Currently here is the SimpleITK documentation landscape:

- [SimpleITK Wiki](https://itk.org/Wiki/SimpleITK) - The "hub" for information and links, [FAQ](https://itk.org/Wiki/SimpleITK/FAQ), [Getting Started](https://itk.org/Wiki/SimpleITK/GettingStarted), [Build Instructions](https://itk.org/Wiki/SimpleITK/GettingStarted#Build_It_Yourself), Visual Guides to Build and Installation: [CSharp](https://itk.org/Wiki/SimpleITK/GettingStarted/A_visual_guide_to_SimpleITK_with_CSharp), [Linux](https://itk.org/Wiki/SimpleITK/GettingStarted/Visual_guide_to_building_on_Linux), [Java](https://itk.org/Wiki/SimpleITK/GettingStarted/A_visual_guide_to_SimpleITK_in_Java) along with links to other documentation and tutorials.
- [SimpleITK Doxygen](https://itk.org/SimpleITKDoxygen/html/index.html)  - This primarily is the C++ API reference. It can be challenging to some users to map their language to  the C++ API, but hopefully by studying some of the [Examples](https://itk.org/SimpleITKDoxygen/html/examples.html) that are in the [repository](https://github.com/SimpleITK/SimpleITK/tree/master/Examples) and [tested](https://open.cdash.org/index.php?project=SimpleITK) nighty, translation between languages can by done. Additionally, Doxygen automatically links between the API and the Examples. There is also nominal written information on select topics on the (Related)[https://itk.org/SimpleITKDoxygen/html/pages.html] pages section for the (repo)[https://github.com/SimpleITK/SimpleITK/tree/master/Documentation/Doxygen]
- [SimpleITK Notebooks](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/) - This contains interactive 'tutorial' style material. @zivy has been working on expanding it to the R language, and extending and improving it. There is work that could be done to improve the introductory material with the information in the style of your writing.
- ITK Documentation - There is a wealth of exiting ITK documentation: [The ITK Software Guide](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjl6OLisMnRAhVBQyYKHTfwAlcQFggcMAA&url=https%3A%2F%2Fwww.itk.org%2FItkSoftwareGuide.pdf&usg=AFQjCNHKnXV7ORxAkqLvVeRVXHktR-vybQ&sig2=QDQRXRTEEdHKscNYKWkUYg) which introduces some concepts and topic but is also a compendium of [examples](https://itk.org/Doxygen/html/examples.html). Then there are a couple other examples projects: [ITK Examples](https://itk.org/ITKExamples/) and [ITK WIKI Examples](https://itk.org/Wiki/ITK/Examples). And there again is the [ITK Doxygen](https://itk.org/Insight/Doxygen/html/) which we have conveniently linked from the SimpleITK Doxygen.

**Comment by blowekamp** [comment]
Continuing... (that post was long enough with lots of links I didn't want to loose)...

I agree with you, that we are in need of "guide" style documentation, and better integrated examples.

Are you proposing a new independent repo, new example, new notebooks, and new prose?

I am much more interesting in integrating the existent items, and reusing existing examples/notebooks, along with consolidating prose, and web interfaces helping to integrate the resources. Can you help with this in you propose framework?

**Comment by chsasank** [comment]
As you have listed above, it's evident that the whole documentation is quite disjoint. It requires a one single place for the whole documentation. Something like simpleitk.readthedocs.io. 

We should be able to move most of the existing documentation to sphinx relatively easily.
-  Wiki Pages : Probably easiest to move. Just involves copy pasting.
- Notebooks: Material from here can be our 'user guide'. Like explanation about transforms, how to do registration etc. As you've mentioned lot of prose needs to be added.
- Examples: These are quite important. Right now, there's very little explanation as to what a particular example does. For example,see how nicely histogram equalisation is explained in [skimage's documentation](http://scikit-image.org/docs/stable/auto_examples/color_exposure/plot_equalize.html) 

As for doxygen, we can have both existing doxygen and api reference section in sphinx.

> duplication of efforts

I think you're right in that there might be duplication of efforts. We can salvage as much text as possible from existing notebooks/wiki. Examples require more effort though.

**Comment by chsasank** [comment]
To illustrate, I'll show what I've done to write https://chsasank.github.io/sitk-docs/index.html

- Wiki page: (incomplete)[Installation](https://chsasank.github.io/sitk-docs/installation.html) page is partially from https://itk.org/Wiki/SimpleITK/GettingStarted
- Notebooks: [Image Basics](https://chsasank.github.io/sitk-docs/image.html) is consolidated from following notebooks:
00 Setup
01 Image Basics
02 Pythonic Image
03 Image Details
- Examples: [Canny Edge](https://chsasank.github.io/sitk-docs/auto_examples/edges/plot_canny.html#sphx-glr-auto-examples-edges-plot-canny-py) example is well explained example from doxygen. Prose is from scikit image.

**Comment by blowekamp** [comment]
Hrmm... Consolidate vs Duplicate ( replace ).

Let's start here:

The Examples in the SimpleITK repository needs to be there for testing and integration. The Sphinx must use the same code/repo and add the framework to have prose reference examples in all languages.  The copying of documentation from another project (scikit-image) is not acceptable.

Similarly the notebooks should use the (select) notebooks from the SimpleITK notebooks repository. And those note books should be updated with improved prose. Perhaps we should have a set of notebooks there: Introduction to: Image, Transform, Registration, Segmentation. That are used in both locations? The trick is there is some information that that is general and some that it language specific, so some way need to be established to do document the different languages fairly.

Your installation material is very brief. It may be that for now we have brief info in Sphinx that references the wiki. The current advantage of the wiki, is it allow for users to easily contribute update, and extend the every changing build platforms, and language installation information. What maybe nice to to get the wiki, in the TOC, and (maybe) as a sub-page on the right-hand side.

I hope that explains more my hope for consolidation and not duplication.

**Comment by chsasank** [comment]
>  The copying of documentation from another project (scikit-image) is not acceptable.

Obviously. I've put the text for canny detection as a placeholder.

> And those note books should be updated with improved prose.

I'm suggesting doing away with having notebook as a source of documentation itself. Right now they are not searchable. As an user, having to go through those notebooks was a really bad experience. 

Frankly, I was appalled to find some of the most important details about Image object, specifically that of voxel to world coordinate relation tucked away in notebooks. I had to quite a lot of searching around, before putting together the whole thing.

I mean, this was the reason I embarked up on this project. SimpleITK has most functions required for a medical imaging engineer but the documentation is fragmented and lacking.

> Your installation material is very brief.

Of course, because it was a draft. Have a look now. I've improved to illustrate my idea.

> The current advantage of the wiki, is it allow for users to easily contribute update

It's quite easy for sphinx based documentation too. Just raise a PR with documentation change.

**Comment by blowekamp** [comment]
The simplest place to add documentation on the image's index to physical space would be the [sitk::Image class](https://github.com/SimpleITK/SimpleITK/blob/master/Code/Common/include/sitkImage.h). It is quite easy to improve the existing Dxygen documentation via a PR.

Thank you for sharing what led you down the path to update the documentation. It is good to know that you are trying to use SimpleITK as a new users, and it's reasonable to NOT need to read ITK proper's documentation to get started with SimpleITK. Certainly some introductory information is missing.

There is a lot of great information in the SimpleITK notebooks, and there has been a bunch of recent hard work done on that project. While there are certainly not the introductory type of information you were looking for they are a great interactive documentation resource.

For the sphinx based documentation to be a valid platform for comprehensive documentation it need the full C++ API reference in an easy navigable format. I think getting breathe to work with all the SimpleITK Doxygen will be  challenge. Reorganizing the SimpleITK Examples diretory similar to the [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples) repository, where each example is a directory with multiple "Code" files, and a single RST text would work well.

As you have said generating the required content is going to be a large effort.

**Comment by chsasank** [comment]
Hi,

Sorry for taking time to reply. I've worked on sphinx documentation to make my point better.

I'll now give fleshed out examples why we should move from

- wiki: All the information in wiki is now exported to friendly sphinx documentation. Check out [Installing SimpleITK](https://chsasank.github.io/sitk-docs/installation.html) and [build instructions](https://chsasank.github.io/sitk-docs/building/build.html)

- Notebooks: Thanks to [sphinx-gallery's notebook styled examples](http://sphinx-gallery.readthedocs.io/en/latest/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py), you can see how [10 matplotlib's imshow](http://insightsoftwareconsortium.github.io/SimpleITK-Notebooks/10_matplotlib's_imshow.html) notebook has been converted, for brevity into three different guides at [Visualizing Images](https://chsasank.github.io/sitk-docs/user_guide/visualization/visualization.html). You'll observe that you can download each of these as notebooks. You can see source by downloading python file. (BTW I also fixed some bugs in `myshow`)
 

As for doxygen, we can keep it as it is and link using [doxylink](https://pythonhosted.org/sphinxcontrib-doxylink/). I also raised issue at breathe repo regarding the error I was facing https://github.com/michaeljones/breathe/issues/304, which will hopefully be fixed.

`ITKExamples` seems cool. We can model our example gallery based on it.

Sasank.

**Comment by chsasank** [comment]
Hi,
What do you think of the above? I have improved documentation and put them on readthedocs too: simpleitk.readthedocs.io.

Sasank.

**Comment by blowekamp** [comment]
Hi,

This is really outstanding work and the documentation looks version good. This is a wonder prototype of what Sphinx based documentation could look like for SimpleITK. It is very convincing that this is the platform the SimpleITK community should change to purse for documentation. Firstly there are a couple administrative type things that should be done:

1. Please clearly mark your documentation as not the official SimpleITK documentation, and link to the "scattered official" documentation pages. Something like starting the home page with "Welcome to the prototype Sphinx SimpleITK documentation." Then describe that this is a prototype for consolidating the scatted official documentation which can be found on the wiki, doxygen, and simpleitk notebooks ( with links).

2. The SimpleITK code is under the Apache software license. For the documentation and web pages the we have used a Creative Common license. I believe the CC Attribution 3.0 Unported is appropriate (https://creativecommons.org/licenses/by/3.0/), can you please change to this license? Also keep in mind that many people have worked and contributed to the content that you have consolidated.

3. I think that simpleitk.readthedocs.io should be reserved for official documentation from the SimpleITK GitHub organization. Using that URL could confuse users for the official documentation. Could your repo be perhaps simpleitk-prototype.readthedocs.org? Then we could have the official read the docs just be a page of links firstly to your prototype, then to the other resources. We are quickly preparing for the SimpleITK 1.0 release, we will be updating the wiki and other resource, and we need to ensure there is no confusion where to get the updated information.

On to the important work of how to better integrate your work and the existing SimpleITK Examples. I have refactored the SimpleITK/Examples directory so that the sub-directories are not an example in different language. 

- a RST description of each example could go into these sub directories.
- The Sphinx prototype could then incorporate this subdirectories into the documentation. These examples should reside in the main SimpleITK repo, and the doc repo should use them.

Thanks again! And I look forward to start integrating some of your work into the main repositories.

**Comment by chsasank** [comment]
Glad that you appreciate my work!

1. Changed the name to 'SimpleITK prototype'. 
2. Changed license wherever I have put apache.
3. We can make the simpleitk.readthedocs.io private or protected(discoverable only with url) for now. 
> We are quickly preparing for the SimpleITK 1.0 release, we will be updating the wiki and other resource, and we need to ensure there is no confusion where to get the updated information.

I think we should develop all the relevant documentation in Sphinx and release it along with v1.0. We can then retire other fragmented resources.

As for example directory, I think examples should have plots/example images. Without images, examples are not as approachable. RST + code wouldn't have the images. We should think of a better implementation.

**Comment by blowekamp** [comment]
In readthedocs can you please delete the current "simpleitk" project, and recreated it as "simpleitk-prototype". I would like to have SimpleITK/SimpleITK use simpleitk.readthedocs.io.

Thanks you very much!

**Comment by chsasank** [comment]
I did what you suggested. 

But I'm not sure if you can have simpleitk.readthedocs.io :(. 
I cannot have now because readthedocs says 'a project exists by than name'

**Comment by blowekamp** [comment]
Me too :(

PLEASE LET ME create the account. I'll try again in an hour.

Thank you.

**Comment by blowekamp** [comment]
A skeleton Sphix documentation has been merged into master and is operational on readthedocs.

Details of how to get images into the documentation without storing the date in the main source code repository still has not been addressed.

Review content can now be added. Content which may become dates or in accurate should be a low priority for documentation associated with a version.

Thanks again for shoving this issue forward.

**Comment by blowekamp** [comment]
A directory for Sphinx has been setup to enable improved documentation and contributions.

**Comment by chsasank** [comment]
@blowekamp 
Hi,

I think it's a good idea to have a separate repo for docs/tutorials. Can have it's own .gitignore etc. We can even then build on gh-pages.

Sasank.

**Comment by blowekamp** [comment]
Thank you for your continued interest.

Certainly, some documentation like the InsightSoftwareConsortium/SimpleITK-Notebooks and specific tutorials for events such as InsightSoftwareConsortium/SimpleITKTutorialSPIE2016 have been in separate repositories.

Regarding the `.gitignore`, those can be placed in a subdirectories, so it should be easy to be able to customize if for the `docs` directory.

I don't think building a subdirectory, and uploading it to an arbitrary repo or branch should be very difficult.

**Comment by chsasank** [comment]
Thanks. I'll create a PR with whatever I already have.

**Comment by blowekamp** [comment]
Please make a series of small commits, such as:
* Migrating the current pages ( updated for 1.0.0 release ) Wiki to sphinx
* Improving the Sphinx style and page layout
* nice introductory pages on Images and Transforms

The small commits are needed to aid in reviewing and identify the steps to build the new documentation infrastructure.

Open issues:
* How to store and reference images. We want to avoid storing in the repository. For the CMake build processes there is a process which uses MD5/SHA512 to download data from a variety of servers, this will likely need to be supported in the docs infrastructure.
* How to integrate the `Examples` directory into the Sphinx documentation. There is required support for multiple languages. Additionally, there should be a single prose file for each example which references the code.

This is to ensure that the documentation and examples are maintainable and synchronized to reduce duplication.

**Comment by chsasank** [comment]
> How to store and reference images. We want to avoid storing in the repository. For the CMake build processes there is a process which uses MD5/SHA512 to download data from a variety of servers, this will likely need to be supported in the docs infrastructure.

I am using manifest.json mechanism you people are using to store the data. So, images are fetched the time scripts are run.

> How to integrate the Examples directory into the Sphinx documentation.

A custom directive with js will probably do. But we cannot execute them and show outputs like in user guide unfortunately.
