### ISSUE TITLE
sitk paster filter not support 4D image?

### ISSUE THREAD

**Issue by colddie** [SimpleITK/SimpleITK#872]
Hi,

I was trying to paste a 3D volume into a 4D volume.
		imgs1 = sitk::Paste(imgs, resampled_out, resampled_out.GetSize(), extractIndex);

got following error
terminate called after throwing an instance of 'itk::simple::GenericException'
  what():  /home/tsun/bin/SimpleElastix-master/Code/Common/include/sitkMemberFunctionFactory.hxx:185:
sitk::ERROR: Pixel type: 32-bit float is not supported in 4D by N3itk6simple16PasteImageFilterE or SimpleITK compiled with SimpleITK_4D_IMAGES set to OFF.

I have SimpleITK_4D_IMAGES on. Does it mean pasteImageFilter not support 4D image?

**Comment by zivy** [comment]
Hi @colddie ,

The paste filter expects the two images to have the same dimensionality, you can't paste a 3D image into a 4D image, see code below for problem and solution (2D-3D case):
```
import SimpleITK as sitk

dest_img = sitk.Image([256,256,256], sitk.sitkUInt8) + 255 # 3D white image

# following code will not work:
src_img = sitk.Image([10,10], sitk.sitkUInt8) #2D black image
sitk.Show(sitk.Paste(dest_img, src_img, src_img.GetSize(), [0,0], [100,100,0]))   

# this code will work:
src_img = sitk.Image([10,10,1], sitk.sitkUInt8) #3D black image with third dimension equal to one
sitk.Show(sitk.Paste(dest_img, src_img, src_img.GetSize(), [0,0,0], [100,100,0]))   
```
The [JoinSeries filter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1JoinSeriesImageFilter.html) may also be relevant here.

**Comment by colddie** [comment]
Hi @zivy zivy,

Here is a piece of my codes trying to copy a 3D volume to 4D volume with your suggestion on using JoinSeries filter. Unfortunately, it gave the same error info as I just posted. 

   namespace sitk = itk::simple;
   std::vector<int> extractIndex(4);
    imgs = sitk::Image([10,10,10,10], sitk.sitkFloat32);
    resampled_out = sitk.Image([10,10,10], sitk.sitkFloat32);
    sitk::Image tmpimgs = sitk::JoinSeries(resampled_out);

    extractIndex[0] = 0;
    extractIndex[1] = 0;
    extractIndex[2] = 0;
    extractIndex[3] = 1;
    imgs1 = sitk::Paste(imgs, tmpimgs, tmpimgs.GetSize(), extractIndex);	
    sitk::ImageFileWriter writer1;
    writer1.SetFileName( std::string("onframe_t.nii") );
    writer1.Execute(imgs1);

**Comment by blowekamp** [comment]
Support for 4D images is rather limited with just: reading, writing, extract, join series, and the slice filters supporting 4D operations.

**Comment by colddie** [comment]
@blowekamp I see. Can you suggest a workaround for my problem with Simple ITK?

**Comment by zivy** [comment]
Hi @colddie ,

If you are working with temporal 3D images, a possible workaround is to keep them separate when you process them (list of 3D images). You can then join them into a 4D image in the end:
```
first3D_image = sitk.Image([10,10,10], sitk.sitkFloat32)  
second3D_image = sitk.Image([10,10,10], sitk.sitkFloat32) 
res4DImage = sitk.JoinSeries([first3D_image, second3D_image]) 
```

**Comment by blowekamp** [comment]
I do not know your larger problem so there may be a better way from the beginning to accomplish this. You would need to Use the ExtractImageFilter on `imgs` to create 10 volumes of size `[10,10,10]` then join it with the new resampled image.

Think about using a list of 3D images, until you need to join the series into a 4D image to write.

**Comment by colddie** [comment]
Thank you all for the suggestion, Yes that is definitely a method. My problem is to generate a series of 3D volume (316), then combined them together as one 4D volume. I guess I need to make a list of images, but what is the best way to create such a list in SimpleITK?

**Comment by blowekamp** [comment]
It looks like you are using C++. and `std::vector<sitk::Image>` would be find. Also, SimpleITK uses lazy copying under the hood so it should be very efficient to move images around in stl data structures.

**Comment by colddie** [comment]
Thank you! That is exactly what I want. @blowekamp

**Comment by beathvn** [comment]
> Hi @colddie ,
> 
> If you are working with temporal 3D images, a possible workaround is to keep them separate when you process them (list of 3D images). You can then join them into a 4D image in the end:
> 
> ```
> first3D_image = sitk.Image([10,10,10], sitk.sitkFloat32)  
> second3D_image = sitk.Image([10,10,10], sitk.sitkFloat32) 
> res4DImage = sitk.JoinSeries([first3D_image, second3D_image]) 
> ```

this works fine for me, but what I get is a ([10, 10, 10, 2]) sized image. What I would need is a ([2, 10, 10, 10]) image. How could I specify the axis, where it should join?

**Comment by blowekamp** [comment]
With SimpleITK 2.0, 5D image are supported out of the box with this operations. This issue is quite old.
