### ISSUE TITLE
 sitk.Resample  outputs empty img while trying to adjust direction

### ISSUE THREAD

**Issue by srkeyan** [SimpleITK/SimpleITK#878]
# Problem:
    I am trying to adjust direction of mask to the direction of img, using sitk.Resample
    But, this process sometimes will output empty mask with all 0.
    No idea why, Can someone help me !!

# code :    
    new = sitk.Cast(sitk.GetImageFromArray(mask_arr), sitk.sitkUInt8)
    new.SetOrigin(mask.GetOrigin())
    new.SetSpacing(mask.GetSpacing())
    new.SetDirection(mask.GetDirection())
    
    transform = sitk.TranslationTransform(3)
    interpolator = sitk.sitkNearestNeighbor
    default_value = 0
    # Resample(Image image1, Image referenceImage, Transform transform, 
    # itk::simple::InterpolatorEnum interpolator, double defaultPixelValue=0.0, 
    #                 itk::simple::PixelIDValueEnum outputPixelType) -> Image
    resampled = sitk.Resample(mask, img, transform,
                         interpolator, default_value)
    
    print('\noutput:')
    print('resampled mask.max: ', sitk.GetArrayFromImage(resampled).max())
    
# output 1, Falied:

    ## input
    img size: (512, 512, 18)
    mask size: (512, 512, 18)
    img spacing: (0.6953125, 0.6953125, 8.0)
    mask spacing: (0.6953125, 0.6953125, 8.0)
    img direction: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
    mask direction: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
    
    ## now, mask is not empty
    mask.max:  1
    
    ## after resampling, mask is empty
    resampled mask.max:  0
    
# but the same method may success sometime
# output 2, Success:
    
    ## input
    img size: (512, 512, 42)
    mask size: (512, 512, 42)
    img spacing: (1.0, 1.0, 1.0)
    mask spacing: (1.0, 1.0, 1.0)
    img direction: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
    mask direction: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
    
    ## now, mask is not empty
    mask.max:  1
    
    ## after resampling, mask is not empty
    resampled mask.max:  1
        
# output 3, Success:
    ## input
    img size: (384, 384, 12)
    mask size: (384, 384, 12)
    img spacing: (0.52083331346512, 0.52083331346512, 2.3999996185302734)
    mask spacing: (0.5208333134651184, 0.5208333134651184, 2.399998903274536)
    img direction: (1.0, 0.0, 0.0, 0.0, -0.21, 0.97, 0.0, -0.97, -0.21)
    mask direction: (1.0, 0.0, 0.0, 0.0, 0.21, 0.97, 0.0, 0.97, -0.21)
    
    ## now, mask is not empty
    mask.max:  255
    
    ## after resampling, mask is not empty
    resampled mask.max:  255

**Comment by zivy** [comment]
Hello @srkeyan,

Based on the information you provided it is hard to understand what is the problem you are encountering. Please create a short code snippet that includes an appropriate image and mask which illustrates the problem. 

Also I am surprised by the output3, where the resulting img and resampled mask directions are different while the size and spacing is the same. The Resample filter creates a grid based on the image and then resamples the mask onto that grid, so the grid settings for the resampled mask and the image should be the same (origin, size, spacing, direction).

**Comment by srkeyan** [comment]
Hello, @zivy ,thank you so much for your apply.

I have renewed my question, hope it's more clear now.
The main problem is that resampling sometimes makes mask all empty.

**Comment by zivy** [comment]
Hello @srkeyan ,

Unfortunately, I still don't understand the issue. The first section of the code creates an image called `new`  (copy of information from `mask_arr`) which is not used in later in the resampling code. This whole section can be removed as it has no effect on the resampling. I guess this was not your intent. Please edit the code so that the `new` image is used.

**Comment by dave3d** [comment]
Closing.  If this is still a problem, please re-open.
