### ISSUE TITLE
Loading and ordering dicom 3d time series (4D)

### ISSUE THREAD

**Issue by manuel-lincbiotech** [SimpleITK/SimpleITK#879]
Hello,
I am trying to load 4d dicom images (volumes acquired during time series). When I pass the dicom files to sitk.ImageSeriesReader() it loads everything in 3D. In my case I have 4 slices per volume and a total of 25 volumes (100 images total) so when loading it gets a volume of dimensions (256,256,100) intead of the desired (256,256,4,25). I´ve checked the ordering along 3D and it seems to be ordering them right (although I can´t be completely sure, due to the nature of the images). 

I know that the order of the volumes has to be done through the time of the acquisition tag (Content time in my example) as I tried it with pydicom and worked. I would like to know if there is a way to load the images in a (256,256,4,25) way and if not, how can I know the rule with which it was ordered (or maybe I can specify that rule beforehand?) and try to manually change the dimensions afterwards or something

Thanks in advance

**Comment by zivy** [comment]
Hello @manuel-lincbiotech,

The GDCM reader returns the set of files based on series, and in your case all images belong to the same series. What puzzles me is that they are loaded as 256x256x100. I expect a 4D (3D+time) image to be a set of 3D images that occupy the same space, so I don't know what happens when multiple 2D slices that are in the same spatial location are loaded.

A possible workaround:
1. `GetGDCMSeriesFileNames` - get all file names in the series (ordered along the z axis).
2. Use an `ImageFileReader` (`file_reader.ReadImageInformation` to read the meta-data from each image without reading the bulk pixel data).
3. Separate image file names based on time, but keep the z order.
4. For each timeframe use `ImageSeriesReader` and set the file names to the sublist you got in step 3.
5. You now have a list of 3D volumes, use the `JoinSeries` filter to create one 4D volume.

I am not sure you need step 5 as it is common to work on each 3D volume separately: register them to each other for computing deformations, propagating segmentations, or comparing segmented structures over time...

**Comment by manuel-lincbiotech** [comment]
Hello @zivy,
Yes, actually it took me my all this morning to figure it out but in the end I did exactly what you are proposing. Works perfectly this way. 

Thanks!

**Comment by chushan89** [comment]
> Hello @manuel-lincbiotech,
> 
> The GDCM reader returns the set of files based on series, and in your case all images belong to the same series. What puzzles me is that they are loaded as 256x256x100. I expect a 4D (3D+time) image to be a set of 3D images that occupy the same space, so I don't know what happens when multiple 2D slices that are in the same spatial location are loaded.
> 
> A possible workaround:
> 
> 1. `GetGDCMSeriesFileNames` - get all file names in the series (ordered along the z axis).
> 2. Use an `ImageFileReader` (`file_reader.ReadImageInformation` to read the meta-data from each image without reading the bulk pixel data).
> 3. Separate image file names based on time, but keep the z order.
> 4. For each timeframe use `ImageSeriesReader` and set the file names to the sublist you got in step 3.
> 5. You now have a list of 3D volumes, use the `JoinSeries` filter to create one 4D volume.
> 
> I am not sure you need step 5 as it is common to work on each 3D volume separately: register them to each other for computing deformations, propagating segmentations, or comparing segmented structures over time...

Hi, there are several time information in dicom tag. Which tag should be used in step 3, in order to separate files?

**Comment by manuel-lincbiotech** [comment]
In my case I´ve done this with different images that required time ordering. In all cases I used the tag 'content time' (0008|0033). This should give you the time at which it was created as stated in https://dicom.innolitics.com/ciods/cr-image/general-image/00080033 
Take into account that the time is usually stated as a number representing something like hours minutes seconds... so you might need to convert those values to correctly order them. In the cases I´ve tested this I had to apply this code. Assumming time variable already contains the list of 'content time' values:

`hh = np.modf(times / 10000)
mm = hh[0]
hh = hh[-1]
mm = np.modf(mm * 100)
ss = mm[0] * 100
mm = mm[-1]
mm = np.modf((times - hh * 10000) / 100)[1]
times = hh * 3600 + mm * 60 + ss`


The final time should be the times in seconds, I would then suggest apply a sort method in case they are not ordered and then substract the minimum so the times start at 0 (in case you need this). Hope this works for you.

**Comment by manuel-lincbiotech** [comment]
Sorry about the code, for some reason it was not stated in different lines as I copied them. Assume a new line appears when a = is stated

**Comment by chushan89** [comment]
Thanks, @manuel-lincbiotech .
I played with the tag 'content time' (0008|0033), for a 4D dicom series, there are 18 different time points. However, when I load the data with Mevislab or Itksnap, the 4D data has 9 time points. 
Do you have experiences with this?

**Comment by manuel-lincbiotech** [comment]
Well @chushan89, In my case I have nerver been able to load 4d dicom in itk snap as 4D, they always appeared as 3D stacks where all the slices of all the volumes were stacked together so I´m not sure. What I came across once was in dicom 4d series where there were more time points that did not correspond to actual images (like some info reports mixed with the dicom images). In those cases I do not remember what appeared at the content time tag (maybe Inf values but not sure), but I´m sure that in the tag '0020|1041' (slice location) the value was either Inf or NaN for those slices so I could delete those playing with that. I can´t guarantee this is the same. Dicom images may vary a lot  from one to another, might depend a lot on your specific problem and image type, it could also be that Mevislab or itksnap are not correctly opening them (as I said my experience with itksnap for 4D images has only worked right with .nii files, not so much with dicom, abouth Mevislab I haven´t worked with it).

**Comment by chushan89** [comment]
The MultiVolumeImporter of Slicer3D is quit useful to to understand the loading of 4D CT. 
https://github.com/fedorov/MultiVolumeImporter/blob/b701ca17079dd855f9efc4002f7f734cf5fce5d8/MultiVolumeImporterPlugin.py#L19
