### ISSUE TITLE
Can´t load .IMA (Dicom from old siemens machine)

### ISSUE THREAD

**Issue by manuel-lincbiotech** [SimpleITK/SimpleITK#880]
Hello,

I'm trying to save a 4D mri image (heart cines). The thing is they are .IMA instead of the usual .dcm this seems to be the way siemens call their dicoms, also I think the machine is a bit old (probably +12 years). When I use sitk.ImageSeriesReader.GetGDCMSeriesFileNames() it always return an empty tuple. Sometimes I also get a warning window saying:

WARNING: In D:\a\1\sitk-build\ITK\Modules\IO\GDCM\src\itkGDCMSeriesFileNames.cxx, line 75
GDCMSeriesFileNames (0000014A3B90D770): C:\Users\Manuel_LincBiotech\Desktop\Doctorado\Base datos clÃ­ncio\283229 - copiacine\Nueva carpeta is not a directory

WARNING: In D:\a\1\sitk-build\ITK\Modules\IO\GDCM\src\itkGDCMSeriesFileNames.cxx, line 109
GDCMSeriesFileNames (0000014A3B90D770): No Series were found

WARNING: In D:\a\1\sitk-build\ITK\Modules\IO\GDCM\src\itkGDCMSeriesFileNames.cxx, line 75
GDCMSeriesFileNames (0000014A3B90CC80): C:\Users\Manuel_LincBiotech\Desktop\Doctorado\Base datos clÃ­ncio\283229 - copiacine\Nueva carpeta is not a directory

WARNING: In D:\a\1\sitk-build\ITK\Modules\IO\GDCM\src\itkGDCMSeriesFileNames.cxx, line 122
GDCMSeriesFileNames (0000014A3B90CC80): No Series can be found, make sure your restrictions are not too strong

Not sure why I can´t load them, I tried changing manually the extension to .dcm, also tried with just one of the files with sitk.ImageFileReader() and it says the file doesn´t exist. 

I know that the files are actually dicoms as I opened them with pydicom. I would prefer to stick with simpleitk to convert them directly to .nii but if it can´t read these maybe I´ll read the arrays with pydicom and then convert the arrays to sitk.

**Comment by dave3d** [comment]
The first warning suggests to me that it's a problem with the path name.  I would try getting rid of all the spaces in all the file and directory names.

**Comment by manuel-lincbiotech** [comment]
Ah that´s right. True, spaces are not something good in paths. Already changed it and it worked.
Thanks @dave3d
