### ISSUE TITLE
SimpleITK convert DICOM series to one Nifti file, the srow_x, srow_y and srow_z are all 0 vectors

### ISSUE THREAD

**Issue by workpet** [SimpleITK/SimpleITK#887]
### Description
I tried to convert DICOM series to one nifti file using SimpleITK, but after I check the saved file with nibabel headers, the vectors of srow_x, srow_y and srow_z are all 0 vectors. How can we update these parameters and save the right information? Thanks.

### Steps to Reproduce

```
import numpy as np
import os
import SimpleITK as sitk
import nibabel as nib

if __name__=="__main__":
    
    dir_proj = r"U:\nrrd2nifiti\5029513\405_Messungen_Lunge_Read_1"   
    ID = r"1.3.46.670589.33.1.63638650262276435800003.5530420843397701827"    

    # directory for corresponding DiCOM file
    dir_dicom = os.path.join(dir_proj,ID)
    
    print('=> reading the dicoms with SimpleITK')
    series_reader = sitk.ImageSeriesReader() 
    dicom_names = series_reader.GetGDCMSeriesFileNames( dir_dicom )
    series_reader.SetFileNames(dicom_names)
    dicom_img = series_reader.Execute()   
    
    print('center is ', dicom_img .GetOrigin() )
    print('direction is ',dicom_img .GetDirection() )
    print('spacing is ', dicom_img .GetSpacing() )
    
    out_file = r"test.nii.gz"
    
    print('=> writing the nifti file with SimpleITK')
    writer = sitk.ImageFileWriter()
    writer.SetFileName(out_file)
    writer.Execute(dicom_img)
    
    
    print('=> reading nifti with nibabel')
    n1_img = nib.load(out_file)
    print(n1_img.header)   
```
### Actual behavior
=> reading the dicoms with SimpleITK
center is  (-177.10000610351562, -6.400000095367432, -333.0)
direction is  (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
spacing is  (0.68359375, 0.68359375, 1.0)
=> writing the nifti file with SimpleITK
=> reading nifti with nibabel
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 512 512 308   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1.         0.68359375 0.68359375 1.         0.         0.
 0.         0.        ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : scanner
sform_code      : unknown
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 1.0
qoffset_x       : 177.1
qoffset_y       : 6.4
qoffset_z       : -333.0
**srow_x          : [0. 0. 0. 0.]
srow_y          : [0. 0. 0. 0.]
srow_z          : [0. 0. 0. 0.]**
intent_name     : b''
magic           : b'n+1'

### Expected behavior
If we convert with dicom2nifti modules (https://github.com/icometrix/dicom2nifti), and read it back, we can get. 

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  3 512 512 308   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1.         0.68359375 0.68359375 1.         1.         1.  1.        1.        ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 0
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 1.0
qoffset_x       : 177.1
qoffset_y       : 6.4
qoffset_z       : -333.0
**srow_x          : [ -0.68359375  -0.           0.         177.1       ]
srow_y          : [-0.         -0.68359375  0.          6.4       ]
srow_z          : [   0.    0.    1. -333.]**
intent_name     : b''
magic           : b'n+1'

###  Versions
SimpleITK  1.2.4
Python 3.6
nibabel 2.5.1

**Comment by dave3d** [comment]
I took a look at ITK's Nifti IO code:

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx

It doesn't look like there is anything in there that sets the **srow** fields.  It does look like when a Nifti file is read the srow data gets pulled into the image's meta data dictionary, but there's nothing going the other way.

**Comment by blowekamp** [comment]
> Actual behavior
> 
> => reading the dicoms with SimpleITK
> center is (-177.10000610351562, -6.400000095367432, -333.0)
> direction is (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
> spacing is (0.68359375, 0.68359375, 1.0)

This looks like the SimpleITK DICOM reader did not read the tag the same way as dicom2nifti. When just reading the DICOM files the direction matrix information is just the identity. GDCM is reading the DICOM tags differently than dicom2nifti.

Also note there are 3 different ways to compute coordinates from a NIFT file:
https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/qsform.html
It appears that ITK's output file uses method 2.

**Comment by workpet** [comment]
> I took a look at ITK's Nifti IO code:
> 
> https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
> 
> It doesn't look like there is anything in there that sets the **srow** fields. It does look like when a Nifti file is read the srow data gets pulled into the image's meta data dictionary, but there's nothing going the other way.

Thanks for the information, but I guess it will be nice to have that too, even though it is a little bit redundant.

**Comment by workpet** [comment]
> > Actual behavior
> > => reading the dicoms with SimpleITK
> > center is (-177.10000610351562, -6.400000095367432, -333.0)
> > direction is (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
> > spacing is (0.68359375, 0.68359375, 1.0)
> 
> This looks like the SimpleITK DICOM reader did not read the tag the same way as dicom2nifti. When just reading the DICOM files the direction matrix information is just the identity. GDCM is reading the DICOM tags differently than dicom2nifti.
> 
> Also note there are 3 different ways to compute coordinates from a NIFT file:
> https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/qsform.html
> It appears that ITK's output file uses method 2.

Got it. Thanks for the information.
