### ISSUE TITLE
ImageRegistrationMethod.MetricEvaluate - Spacing error

### ISSUE THREAD

**Issue by michaelzenkay** [SimpleITK/SimpleITK#898]
I am borrowing the simple ITK implementation of the Mutual information Metric to compare performance of an external registration software compared to ANTS. It works if I initialize my images from nifti, but not if I bring in an arbitrary numpy array.

Here is the Gist of how I am using it

> 
> import SimpleITK as sitk
> import numpy as np
> import nibabel as nib
> 
> I = nib.load(image1).get_data()
> J =nib.load(image2).get_data()
> 
> I = sitk.Cast(sitk.GetImageFromArray(I), sitk.sitkFloat32)
> J = sitk.Cast(sitk.GetImageFromArray(J), sitk.sitkFloat32)
> 
> R = sitk.ImageRegistrationMethod()
> R.SetMetricAsMattesMutualInformation()
> MMI = R.MetricEvaluate(I, J)

and it works great

However, If I bring in a numpy array, I get a spacing error (even if I explicitly define spacing):

> ERROR: Image(0x32256f0): A spacing of 0 is not allowed: Spacing is [0, 0]

Also, I wonder why it is throwing a 2d spacing error when my input is 3d?

This is the Gist of a numpy array that would feed into the MetricEvaluate

> 
> I = np.zeros((100,100,100))
> I = sitk.GetImageFromArray(I)
> I.SetSpacing((1.0,1.0,1.0))
> I = sitk.Cast(I, sitk.sitkFloat32)
> 
> J = np.zeros((100,100,100))
> J = sitk.GetImageFromArray(J)
> J.SetSpacing((1.0,1.0,1.0))
> J = sitk.Cast(I, sitk.sitkFloat32)
> 
> R = sitk.ImageRegistrationMethod()
> R.SetMetricAsMattesMutualInformation()
> MMI = R.MetricEvaluate(I, J)
>> ERROR: Image(0x32256f0): A spacing of 0 is not allowed: Spacing is [0, 0]

**Comment by blowekamp** [comment]
Hello,

Thank you for providing a minimal example. I was able to reproduce your error.

This line has the wrong variable as a function argument:
`J = sitk.Cast(I, sitk.sitkFloat32)`

If I set the metric with "SetMetricAsCorrelation()", then the error goes away.

If I initialized the images with `np.random.rand(100,100,100)` then the error does not occur.

I am concluding that this is a corner case error in ITK's `MattesMutualInformation` metric when both images are all zeros, then the internal data structure ( an Image) has the reported invalid size.

Please report this bug to: [InsightSoftwareConsortium/ITK](https://github.com/InsightSoftwareConsortium/ITK)
