### ISSUE TITLE
How to pass a specific label to sitk.LabelOverlapMeasuresImageFilter and evaluation method?

### ISSUE THREAD

**Issue by luciaL** [SimpleITK/SimpleITK#935]
I could not find the document of every function and its usage. [https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1LabelOverlapMeasuresImageFilter.html](url) This website seems cracked. 

Could you tell me how   a specific label to sitk.LabelOverlapMeasuresImageFilter?

**Comment by blowekamp** [comment]
The itk.org website has been revamped. The Doxygen documentation should be fixed shortly.

https://discourse.itk.org/t/itk-org-website-revamp/2578

**Comment by blowekamp** [comment]
You can find an example of how to use the filter in our notebooks:
https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/c8c455b614c5cd3325ca1c160f78df17b5b82c5d/Python/34_Segmentation_Evaluation.ipynb

The old URL are being worked on. Right now this works:
https://itk.org/SimpleITKDoxygen/classitk_1_1simple_1_1LabelOverlapMeasuresImageFilter.html

**Comment by luciaL** [comment]
Thank you so much for your reply.

**Comment by turtleizzy** [comment]
Sorry for replying in a closed issue but even after reading the aforementioned documentation and ipython notbooks,  I couldn't find a way to pass a label to measures in python binding of sitk.LabelOverlapMeasuresImageFilter. Is it a bug?

**Comment by zivy** [comment]
Hello @turtleizzy,

In the future, please open a new issue or ask on [ITK discourse](https://discourse.itk.org/). 

Documentation for the relevant class, [LabelOverlapMeasuresImageFilter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1LabelOverlapMeasuresImageFilter.html).

Also, I recommend using our latest release candidate (see [installation instructions](https://github.com/SimpleITK/SimpleITK/releases)) as release 2.0 of the toolkit will be done in the near future.

With respect to obtaining the overlap measures, your code should look something like:
```
overlap_measures_filter = sitk.LabelOverlapMeasuresImageFilter()
overlap_measures_filter.Execute(seg1, seg2)
#Compare two segmentations where we combine all labels (any value that isn't zero)
overlap_measures_filter.GetJaccardCoefficient()
#Compare two segmentations where we are only interested in a specific label (e.g. label=2)
overlap_measures_filter.GetJaccardCoefficient(2)
```

Please close this issue if this addressed your question, or provide additional details if not.

**Comment by turtleizzy** [comment]
> Hello @turtleizzy,
> 
> In the future, please open a new issue or ask on [ITK discourse](https://discourse.itk.org/).
> 
> Documentation for the relevant class, [LabelOverlapMeasuresImageFilter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1LabelOverlapMeasuresImageFilter.html).
> 
> Also, I recommend using our latest release candidate (see [installation instructions](https://github.com/SimpleITK/SimpleITK/releases)) as release 2.0 of the toolkit will be done in the near future.
> 
> With respect to obtaining the overlap measures, your code should look something like:
> 
> ```
> overlap_measures_filter = sitk.LabelOverlapMeasuresImageFilter()
> overlap_measures_filter.Execute(seg1, seg2)
> #Compare two segmentations where we combine all labels (any value that isn't zero)
> overlap_measures_filter.GetJaccardCoefficient()
> #Compare two segmentations where we are only interested in a specific label (e.g. label=2)
> overlap_measures_filter.GetJaccardCoefficient(2)
> ```
> 
> Please close this issue if this addressed your question, or provide additional details if not.

Thank you so much for your reply. I tested following code on SimpleITK==1.2.2 and 1.2.4(latest version on pypi), both didn't work.

```
# python 3.6, SimpleITK == 1.2.2 / 1.2.4

import SimpleITK as sitk
import numpy as np

im1 = sitk.GetImageFromArray(np.pad(np.ones([7, 7, 7], np.uint8), 1))
im2 = sitk.GetImageFromArray(np.pad(np.ones([5, 5, 5], np.uint8), 2))
labelMeasures = sitk.LabelOverlapMeasuresImageFilter()
labelMeasures.Execute(im1, im2)

print(labelMeasures.GetJaccardCoefficient())
# 0.36443148688046645
print(labelMeasures.GetJaccardCoefficient(1))
# TypeError: GetJaccardCoefficient() takes 1 positional argument but 2 were given
```

**Comment by zivy** [comment]
Hello @turtleizzy,

Please use the release candidate, per my suggestion above (it includes the missing function). The error is raised because the function that received the label number was added after these releases.

**Comment by turtleizzy** [comment]
> Hello @turtleizzy,
> 
> Please use the release candidate, per my suggestion above (it includes the missing function). The error is raised because the function that received the label number was added after these releases.

Sorry I missed the release candidate part. Thanks again for your help!
