### ISSUE TITLE
Doxygen build does not respect FORBID_DOWNLOADS

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#94]
As mentioned in #92, the documentation target still tries to download the ITK tags even when FORBID_DOWNLOADS is specified. 

Should the ITK_DOXYGEN_TAG_LOCATION  be required, if there downloads are forbidden?

**Comment by blowekamp** [comment]
@ghisvail I don't see ITK Doxygen available in debian packages:
 https://packages.debian.org/source/stretch/insighttoolkit4

Ideally there would be provided ITK Doxygen tags from debian that SimpleITK could use, and we could configure SimpleITK Doxygen to have hyper-links to the ITK Doxygen on the local file system.

**Comment by ghisvail** [comment]
> I don't see ITK Doxygen available in debian packages

You are correct and that's a bug. I'll file a request for building a corresponding documentation package.

> Ideally there would be provided ITK Doxygen tags from debian that SimpleITK could use

Absolutely, although there is a high chance the tags don't end up where the build system currently expects them to be. So, `ITK_DOXYGEN_TAG_LOCATION` would be desirable to inject this custom path without patching.

**Comment by blowekamp** [comment]
Closed by pull request #99
