### ISSUE TITLE
RelabelComponentImageFilter returns wrong object sizes

### ISSUE THREAD

**Issue by PatrikBrynolfsson** [SimpleITK/SimpleITK#951]
I have tested this in Python. 

If I run the RelabelComponentImageFilter on my original labelmap where I have 15 regions, I get the correct number of regions from GetNumberOfObjects() which returns (15) and corresponding volumes in pixels using the GetSizeOfObjectsInPixels() method:
(129530, 37814, 25879, 2951, 2906, 2877, 2875, 2827, 2789, 2778, 2715, 2702, 2661, 2661, 2528) 

If I decide to sort objects by size, all works as well, and when I also set a minimum_object_size (2800) I get a reduced number of objects (8) and the corresponding volumes using the GetSizeOfObjectsInPixels() method:
(129530, 37814, 25879, 2951, 2906, 2877, 2875, 2827)

So far so good. However, if I DON'T sort by object size and set a minimum_object_size, GetNumberOfObjects() returns (8) and GetSizeOfObjectsInPixels() retuns
(37814, 129530, 0, 0, 0, 2877, 0, 0). This is obviously wrong. 

Looking at the resulting image, I can assertain that I get labels (1, 2, 6, 9, 10, 13, 14, 15). It would also be handy with a method that returns the remaining labels aftet the volume filtering.

**Comment by zivy** [comment]
Hello @PatrikBrynolfsson,

Was able to confirm this as a bug. Need to check if in ITK or SimpleITK.

MWE in SimpleITK:
```
import SimpleITK as sitk
import numpy as np

img = sitk.GetImageFromArray(np.array([[1,0,0], [2,2,0],[3,3,3]]))

filter = sitk.RelabelComponentImageFilter()

# With sorting on
filter.SetMinimumObjectSize(2)
filter.SortByObjectSizeOn()
print(sitk.GetArrayFromImage(filter.Execute(img)))
print(filter.GetNumberOfObjects())
print(filter.GetSizeOfObjectsInPixels())
print('*'*10)

# With sorting off
filter.SetMinimumObjectSize(2)
filter.SortByObjectSizeOff()
print(sitk.GetArrayFromImage(filter.Execute(img)))
print(filter.GetNumberOfObjects())
print(filter.GetSizeOfObjectsInPixels())
```

**Comment by blowekamp** [comment]
The fix has been merged into ITK and SimpleITK. New SimpleITK binaries will be created tonight with the fixes. You can find out how to download the latest version here: https://simpleitk.readthedocs.io/en/master/installation.html#latest-binaries
