### ISSUE TITLE
Memory access violations in dotnet code on concurrent access to the underlying buffer of an image

### ISSUE THREAD

**Issue by vincenzoml** [SimpleITK/SimpleITK#958]
I have a sample function in FSharp that implements a pixel-by-pixel copy of a monochrome image by accessing the image buffers directly. I run the function a number of times in parallel on a multi-core machine, and the program crashes with various memory access violations. The function is designed to access the underlying buffer of the source image by calling "GetBufferAs..." in each thread (which is the same for each thread). Then a new image is created, its underlying buffer is accessed, and the copy is done.

If the "GetBuffer" method of the source image is called only once, outside of the various threads, the program works. If instead, "new" is *not* called and the source image is used as destination, the program works too. So this must be a bug in the interaction between "new(a)" and "a.getBufferAs". 

Anyway, to reproduce the bug, you can clone the VoxLogicA repository and checkout the "bugsquash" branch.

Detailed instructions

1) Install dotnet core sdk (I use version 3.1) from here:

https://dotnet.microsoft.com/download

2) Clone the VoxLogicA repository: 

git clone https://github.com/vincenzoml/VoxLogicA.git

This includes my own build of simpleitk. I've tried to build 1.2.4 with itk 4.something (default from current master branch of the simpleitk repository) and nothing changed. I've tried to change the itk tag to v5.0.1 but I can't build, I get errors while compiling simpleitk. 

3) Checkout the bugsquash branch:

git checkout bugsquash

4) cd src 

5) dotnet run -c linux-x64 (or win-x64, or osx-x64, depending on your operating system)

The program may finish (and print "all done") but very often it just crashes in unpredictable ways.

Here is the source code of the test program:

https://github.com/vincenzoml/VoxLogicA/tree/bugsquash/src

 
```
#nowarn "9"

open Microsoft.FSharp.NativeInterop
open System.Runtime.InteropServices
open itk.simple

let img = SimpleITK.Cast(SimpleITK.VectorIndexSelectionCast(SimpleITK.ReadImage("test.png"),0ul),PixelIDValueEnum.sitkFloat32)
img.MakeUnique()

let buflen = int (img.GetNumberOfPixels() * img.GetNumberOfComponentsPerPixel())

let task () =           
    // Move the following two lines, and the last one of this function, to the global scope, and the program works
    let imgHandle = GCHandle.Alloc(img)
    let imgPtr = NativePtr.ofNativeInt<uint8> (img.GetBufferAsFloat())    

    // Change the following line to 'let res = img' and the program works
    let res = new Image(img)
    
    res.MakeUnique()            

    let resHandle = GCHandle.Alloc(img)
    let resPtr = NativePtr.ofNativeInt<uint8> (res.GetBufferAsFloat())                    

    for i = 0 to buflen - 1 do
        NativePtr.set resPtr i (NativePtr.get imgPtr i)

    resHandle.Free()

    imgHandle.Free()

Array.Parallel.iter task (Array.create 30 ())
printfn "All done."

```

**Comment by vincenzoml** [comment]
I just noted that inbetween the several experiments that I made, I forgot the "makeunique" call out of the "task()" function; putting it inside the task function does not change the result. On github I've changed that bit, just for clarity.

**Comment by vincenzoml** [comment]
Additionally, sometimes instead of just crashing, the program also prints:

WARNING: In /home/vincenzo/data/remote/SimpleITK-Build/ITK/Modules/Core/Common/src/itkLightObject.cxx, line 206
LightObject (0x7efda8003810): Trying to delete object with non-zero reference count.

I've also tried to disable garbage collection in fsharp (that can be done using the methods in System.GC), but the problem does not disappear.

**Comment by blowekamp** [comment]
Thank you for posting code to reproduce. I can start to look into this issue.

**Comment by dave3d** [comment]
I was able to reproduce the error running your example code.

**Comment by dave3d** [comment]
I got the same error using my build of SimpleITK (latest master on 64-bit linux).

**Comment by vincenzoml** [comment]
@dave3d a question is whether this also happens in C (and python if that can be multi-threaded at all). I don't have plenty of time this week -- and never created a thread in C, btw.

**Comment by vincenzoml** [comment]
Hi again, I tried to translate the example in C++, but no matter if I link *all* the .a from the SimpleITK-Build/SimpleITK-Build/lib directory and also ITK-Common-5.1 and ITKIOPNG-5.1 (that was hard, what is the expected way to compile a C++ program with SimpleiTK?), I end up with: 

/usr/bin/ld: /tmp/cc1x49jj.o: in function `main':
HelloWorld.cpp:(.text+0x8a): undefined reference to `itk::simple::ReadImage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, itk::simple::PixelIDValueEnum, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: HelloWorld.cpp:(.text+0xf5): undefined reference to `itk::simple::Show(itk::simple::Image const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: HelloWorld.cpp:(.text+0x11e): undefined reference to `itk::simple::Image::~Image()'
/usr/bin/ld: HelloWorld.cpp:(.text+0x1c0): undefined reference to `itk::simple::Image::~Image()'
collect2: error: ld returned 1 exit status

 Here's the program I'm trying to run

#include <SimpleITK.h>
#include <sitkImageOperators.h>
#include <iostream>
#include <stdlib.h>
// create convenient namespace alias
namespace sitk = itk::simple;
using namespace sitk;

int main ( int argc, char* argv[] ) {
  Image image = sitk::ReadImage("test.png");
  Show(image, "Hello World: C++", true );
  return 0;
}

**Comment by blowekamp** [comment]
Hello,

Just some comments:
- With multi-threading, the general practice is to consider global or shared variable constant and only modify thread-local variables. This can some times be cleanly done by passing the shared variable as constant parameters to the threaded function. This conventions clarifies the access available to there threaded functions.
- In the like code, [this line ](https://github.com/vincenzoml/VoxLogicA/blob/bugsquash/src/Program.fs#L16) would modify the non-thread local variable and cause problems.
- This line:
 > `let img = SimpleITK.Cast(SimpleITK.VectorIndexSelectionCast(SimpleITK.ReadImage("test.png"),0ul),PixelIDValueEnum.sitkFloat32)
img.MakeUnique()`
 - - There is not need to call `MakeUnique()` at the end as the functions return a new object.
 -- Also the `VectorIndexSelectionCast` can take a 3rd argument for the output pixel type, which makes the `Cast` not needed. This line can be simplified to:
`let img = SimpleITK.VectorIndexSelectionCast(SimpleITK.ReadImage("test.png"),0ul,PixelIDValueEnum.sitkFloat32)`

I'm not a .Net programmer and the documentation for [`GCHandle.Alloc` ](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.gchandle.alloc?view=netframework-4.8) does not give me the needed context to understand the .Net reference counting being used here. My expectation is that the outer context should hold ownership to img, and the thread should hold ownership to local `res`. What is not known to me is if the `GCHandle.Alloc` and `NativePtr.ofNativeInt` methods are concurrent thread safe.

**Comment by blowekamp** [comment]
The following code works safely in Python:
```
import SimpleITK as sitk

from threading import Thread

img = sitk.Cast( sitk.ReadImage("cthead1.png"), sitk.sitkFloat32)


def task(const_img):

    local_img = sitk.Image(const_img)

    #  make unique for local modification
    local_img.MakeUnique()

    # Python code can not be executed concurrently in Python,
    # but sitk filters would be fast as they unlock the GIL
    for y in range(local_img.GetSize()[1]):
        for x in range(local_img.GetSize()[0]):
            local_img.SetPixel(x,y, 1)

threads = []
for i in range(40):
    threads.append(Thread(target=task, args=(img,)))

print("Starting threads...")
for t in threads:
    t.start()

print("Waiting for threads...")

for t in threads:
    t.join()

print("Done")
```

**Comment by vincenzoml** [comment]
Dear @blowekamp , thanks for the clarification! Copying the image seems to fix my problem. But does "new Image(img)" also copy the underlying memory in the new thread or just the Image object? That is, does it consume memory? 

Alternatively could I attempt to call "MakeUnique" in the same thread that creates an image? What happens then? 

Another question: this all started when I first encountered problems last month; at the times I had *never* called MakeUnique but smaller programs just worked fine. Is this because GetBufferAs... already calls MakeUnique? When exactly is MakeUnique needed? I still don't get this.

Regarding GCHandle.Alloc and NativePtr.ofNativeInt, these are both thread-safe, and are very simple methods; GCHandle.Alloc serves to "pin" an object. Until one calls GCHandle.Free, the object cannot be revoked by the garbage collector. That is needed in SimpleITK/dotnet when holding a reference to the underlying buffer. Whereas "NativePtr.ofNativeInt" does not even touch the data, just turns a "nativeint" into a type-safe pointer (but still, unsafe w.r.t. bounds checking, since it's just a unmanaged pointer).

**Comment by vincenzoml** [comment]
Closing the issue as it's not a bug! And thanks for your prompt reply.

**Comment by blowekamp** [comment]
> Dear @blowekamp , thanks for the clarification! Copying the image seems to fix my problem. But does "new Image(img)" also copy the underlying memory in the new thread or just the Image object? That is, does it consume memory?

The line `new Image(img)` creates a new `sitk::Image` that reference's the old data. The data will be copied when the image is modified with e.g. `SetPixel`, non-const `GetBufferAs..` or explicitly `MakeUnique` is called.

> 
> Alternatively could I attempt to call "MakeUnique" in the same thread that creates an image? What happens then?

I believe that is what is occurring in my Python example. It explicitly creates a thread local copy of the data. This call is actually not needed in my example as first call to `SetPixel` will implicitly call `MakeUnique` but when dealing with threading it can be useful to explicitly create thread local deep copies, to clarify the threading pattern being used. The important thing here is no thread modifies `img`.

> 
> Another question: this all started when I first encountered problems last month; at the times I had _never_ called MakeUnique but smaller programs just worked fine. Is this because GetBufferAs... already calls MakeUnique? When exactly is MakeUnique needed? I still don't get this.

The non-constant `GetBufferAs..` methods call `MakeUnique` before writing. All the methods in `sitk::Image` call `MakeUnique` before the Image is modified. This is called "LazyCopying" and does work transparently until explicit local copies are need to ensure a threading pattern is correctly being used.

**BUG**
I believe the source of your bug is the call "img.GetBufferAsFloat()" which called the *non-constant* version, causing `MakeUnique` to be called on the global img, violating the threading model of not modifying the globals.

I am not familiar with F#, but you should be calling the constant method! Is there a way to declare `img` a variable as `const` in F#? Otherwise, you are creating and additional copy of `img`, when `img.GetBuffer..` is called.


I create a `Dockerfile`to reproduce  your test. I believe you updated the test so I was unable to get it to fail with the change/


```
FROM ubuntu:18.04

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
  cmake \
  build-essential \
  curl \
  wget \
  git \  
  ninja-build \
  software-properties-common \
  python \
  emacs \
  && apt-get clean

RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
 dpkg -i packages-microsoft-prod.deb && \
 add-apt-repository universe && \
 apt-get update && \
 apt-get install -y apt-transport-https && \
 apt-get update && \
 apt-get install -y dotnet-sdk-3.1 && \
 apt-get clean

RUN git clone https://github.com/vincenzoml/VoxLogicA.git && cd VoxLogicA && git checkout bugsquash
RUN chmod o+w -R VoxLogicA

ENV HOME /tmp
WORKDIR VoxLogicA/src
CMD dotnet run -r linux-x64
```

**Comment by vincenzoml** [comment]
Hi, thanks for the Dockerfile; please replace "git checkout bugsquash" with "git checkout d3e95c11284c4b0a084394d2011a1cc4490bc3e8" and test again (yes I updated the branch with the solution).

I need to investigate the "const" issue but I believe that in dotnet we see just one method (or are you sure that in C# you can call the const version of getBufferAs()?). 

Anyway: how can I tell what version of "getBufferAs" is being called? Any debug flag to activate or indirect tests (e.g. checking whether my bug disappears...)?

**Comment by vincenzoml** [comment]
@blowekamp right now I believe there's no way to call the "const" version of GetBufferAs... (from csharp too, probably). Maybe you can consider providing an overloaded version with a parameter (bool readonly = false). Anyway: as far as I understand, the additional copy issue is only when I have done "new(img)" to copy an image, but in my case all images are different. Am I correct in assuming that "MakeUnique" will not create a copy in some cases, e.g.:

img = ReadImage("filename")
img.MakeUnique() // no additional copy created, correct?

**Comment by blowekamp** [comment]
@vincenzoml Yes, there appears to be a lot of opinions on [const-ness in the C# or .Net Community](https://stackoverflow.com/questions/3263001/why-are-const-parameters-not-allowed-in-c).

>  Am I correct in assuming that "MakeUnique" will not create a copy in some cases, e.g.:
> 
> img = ReadImage("filename")
> img.MakeUnique() // no additional copy created, correct?

In this case, since `img` uniquely references the image data, then no copying occurs.

**Comment by vincenzoml** [comment]
@blowekamp I've updated my bugsquash branch:

1) there are now two directories called "fsharp" and "csharp"; both exhibit the bug, one for each language. 

2) the directory src is gone (now it's called fsharp).

3) I reverted the fsharp source to exhibit the bug.

So to replicate the bug in csharp you need "cd csharp && dotnet run -r linux-x64" and same for fsharp "cd fsharp && dotnet run -r linux-x64"

Thanks for your help so far. Again, best is to overload the methods in SimpleITK adding a boolean flag (also if there are other methods whose behaviour changes depending on the modifiers). 

So for the moment I'll see how I can use thread local storage to address these issues, but indeed getting a "readonly" method that does not call makeunique would be the ideal solution.

**Comment by blowekamp** [comment]
Currently the `GetBuffer...` methods are strongly types. Would C#/F# be able to handle a `void` pointer? and to the casting?

**Comment by vincenzoml** [comment]
Hi, well, the GetBuffer methods return a "Nativeint" in F# or "IntPtr" in
C#. Both are the same thing: an untyped pointer. In C# the method
"toPointer()" converts an IntPtr into a "void*". In FSharp, one needs to
cast it to a typed pointer to use it (that's what "NativePtr<uint8>" does
in my code). So yes, both languages in some sense can handle void pointer,
but in which sense? Could you perhaps add a method called
"GetReadOnlyBuffer" or a static function maybe?

Vincenzo


Il giorno gio 30 gen 2020 alle ore 20:31 Bradley Lowekamp <
notifications@github.com> ha scritto:

**Comment by vincenzoml** [comment]
The proposed fix resolves this issue.
