### ISSUE TITLE
Plot the displacement field of B-Spline transformation

### ISSUE THREAD

**Issue by reox** [SimpleITK/SimpleITK#964]
There was already a similar issue (#932) but it regarded the Jacobian. I like to plot something similar, but directly the displacement field of the transformation.
I wrote this function here to visualize the field:
```
def get_deformation_field(image, transform):
    displ = sitk.TransformToDisplacementField(transform, 
                                  sitk.sitkVectorFloat64,
                                  image.GetSize(),
                                  image.GetOrigin(),
                                  image.GetSpacing(),
                                  image.GetDirection())
    det = sitk.GetArrayFromImage(sitk.DisplacementFieldJacobianDeterminant(displ))
    vectors = sitk.GetArrayFromImage(displ)
    
    x, y = det.shape
    X, Y = np.meshgrid(np.arange(0, x, 1), np.arange(0, y, 1))
    U = vectors[:,:,0]
    V = vectors[:,:,1]
    
    print(det.shape)
    print(vectors.shape)
    print(U.shape)
    print(V.shape)
    
    plt.imshow(det, cmap='jet')
    plt.colorbar()
    plt.quiver(X, Y, U, V)
```
which should work for 2D images.
I assume that the return value of `TransformToDisplacementField` is a vector field, containing vectors with the same dimension as the input transformation - right?
Assuming that I have an image with size `(40, 50)` and a spacing of `1`, the code should produce the correct result, but instead I get this:
![Figure_1](https://user-images.githubusercontent.com/431045/73848619-bde4c680-4828-11ea-9e37-98524587d102.png)

Output of the shapes:
```
(40, 50)
(40, 50, 2)
(40, 50)
(40, 50)
```

Instead of using the functions, I also applied the transformation to a set of points and calculated the difference, which lead to this:
```
    x, y = image.GetSize()
    X, Y = np.meshgrid(np.arange(0, x, 1), np.arange(0, y, 1))
    
    U = np.zeros(X.shape)
    V = np.zeros(Y.shape)
    for index, value in np.ndenumerate(X):
        px, py = transform.TransformPoint((float(value), float(Y[index])))
        U[index] = px - value
        V[index] = py - Y[index]
    plt.quiver(X, Y, U, V, angles='xy', scale_units='xy', scale=1)

```
which looks like this:
![Figure_2](https://user-images.githubusercontent.com/431045/73848979-6abf4380-4829-11ea-95d2-8714db4cc353.png)

and would make more sense to me.
Should the vector field which is the result of `TransformToDisplacementField` not look the same?
Why are my coordinates flipped around in the output?

Thanks in Adavance!

**Comment by blowekamp** [comment]
Hello,

The SimpleITK ( and ITK ) images are indexed and size as `image[X, Y, Z]` with the x axis being the fastest. While as Numpy arrays are index `array[z, y, x]` and the x-axis is still the fastest. This is the conventions for accessing the same buffer in these two libraries. It is unfortunate that they are different.

So the problem is the interfacing between Numpy and SimpleITK coordinates.

The `np.meshgrid` does have a [long note about this issue](https://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html).

HTH,
Brad

**Comment by reox** [comment]
So plotting `plt.quiver(Y, X, V, U)` instead of `plt.quiver(X, Y, U, V)` should resolve the issue? The image obviously fits now, but the result still does not look like the displacement field:
![Figure_3](https://user-images.githubusercontent.com/431045/73857795-b842ad00-4837-11ea-9a94-ec426beb1e23.png)

Or is this correct?! Comparing with the Jacobian plot in the background, my solution using the vector transformation looks more reasonable - at least to me :D

**Comment by reox** [comment]
Yet another question emerged from that: The parameters from the BSplineTransformation, how are they ordered in the list? I found a single example which removed the Z displacement of the control points by setting the first len(params)//3 values to zero - so I assume the ordering of the Values is `z_0, z_1, ..., z_n, y_0, y_1, ..., y_m, x_0, x_1, ..., x_p`?

**Comment by zivy** [comment]
Hello @reox,

The standard ordering in ITK/SimpleITK is x-y-z, [x_0...x_N,y_0...y_N,z_0...z_N] and not z-y-x which is the standard in numpy.

**Comment by reox** [comment]
@zivy thanks for the reply, but then this makes no sense: 
https://github.com/faustomilletari/VNet/blob/584c1502f369f2547e7ed384f9cc25beb09f65e1/utilities.py#L85-L93
So is this code wrong in removing the z-displacements as it actually removes the x-displacements?
Or is this yet another notation mix-up, as the original image probably was zyx hence the x coordinates in ITK looked like the z coordinates?

I actually tried this now by creating a displacement field manually like `[1,2,3,4, ..., 0, 0, 0, 0, ...]`, hence it should only affect the x coordinate - which it does.

**Comment by zivy** [comment]
Hello @reox,

Looks like a bug in that code, or it could be that the documentation there is wrong. While we all trust the documentation it is always best to create a simple test (pun intended). For projects that have been going on for a long while it is not uncommon to have discrepancies between code and comments. Code is updated but we forget to update the documentation.

Bottom line, only trust your tests. I will create an issue to improve the BSpline documentation (either add an example or discuss in the [relevant Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/22_Transforms.ipynb)).

**Comment by reox** [comment]
thanks for the clarification! I think I understand the ordering now.
Yes, I should have done these simple experiments already yesterday ;)
