### ISSUE TITLE
Is it possible to read multiple .mhd files as one 3D image? 

### ISSUE THREAD

**Issue by alexofficial** [SimpleITK/SimpleITK#965]
I have multiple folders which consist of multiple .mhd files (all slices). I would like to know if it is possible to read all of them as one 3D image.

**Comment by blowekamp** [comment]
Hello alexofficial,

Have you looked into using the [ImageSeriesReader](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ImageSeriesReader.html)?

**Comment by alexofficial** [comment]
> 
> 
> Hello alexofficial,
> 
> Have you looked into using the [ImageSeriesReader](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ImageSeriesReader.html)?

Yes, I would like to have similar functionality as the Static Public Member Functions (**GetGDCMSeriesIDs** and **GetGDCMSeriesFileNames**)

Thus, I wonder if I can achieve the same by having **.mhd** files instead of **DICOM**. 

Do you have any suggestions?

**Comment by zivy** [comment]
Hello @alexofficial 

Below is code that does what you want. It assumes all mhd files in the directory belong to the same volume. Please close the issue if this resolved it, or provide additional details.

```
import SimpleITK as sitk
import glob
import os

def get_sorted_mhd_file_list(dir_name):
    file_reader = sitk.ImageFileReader()
    file_information = []
    for file_name in glob.glob(os.path.join(dir_name,'*.mhd')):
        file_reader.SetFileName(file_name)
        file_reader.ReadImageInformation()
        file_information.append((file_reader.GetOrigin()[2], file_name))
    _, file_names = zip(*sorted(file_information))
    return file_names    
        
file_names = get_sorted_mhd_file_list('.')
sitk.Show(sitk.ReadImage(file_names))
```

**Comment by alexofficial** [comment]
Hello @zivy,

Thank you for your help. I managed to do it in the opposite way. (directly save a Dicom 3D to .mhd 3D)
