### ISSUE TITLE
Segmentation fault in ConnectedComponentsImageFilter with image dimensions 2x1

### ISSUE THREAD

**Issue by vincenzoml** [SimpleITK/SimpleITK#970]
Hi, I have found a bug in `ConnectedComponentsImageFilter` with image dimension 2x1. I'm using ubuntu and SimpleITK 1.2 in this experiment but can try other versions if needed. 

The program is simple:

```F#
    let flt = new ConnectedComponentImageFilter()
    flt.SetFullyConnected(true)
    SimpleITK.WriteImage(flt.Execute(SimpleITK.ReadImage("in.png")),"out.png")
```

It crashes with segmentation fault on the attached image.

I created a test case as a branch of the VoxLogicA project: 

https://github.com/vincenzoml/VoxLogicA/tree/BugInSimpleITKLabelCC

Note that the image is very small so clicking on it below may be difficult.

![in](https://user-images.githubusercontent.com/2283125/74357165-ceb0b180-4dbf-11ea-8833-eaf53f6f0493.png)

**Comment by zivy** [comment]
Hello @vincenzoml,

This was fixed in the latest release. Please see the [latest development binaries](https://github.com/SimpleITK/SimpleITK/releases).

Feel free to reopen if you find this does not resolve the issue.

**Comment by vincenzoml** [comment]
@zivy  thanks! Does this mean the fix is not yet in a stable release? If so, will it be in 1.2.5 or 2.0? Do you have a release date in mind? 

PS: I develop in .net for multi-platform; should you consider to release also development and stable binaries for .net in OSX, Windows and Linux, that would be of great help for our project. 

I'm available to help if needed! 

It's actually very simple: you need to compile simpleitk with CSharp enabled in cmake (follow your own instruction to set up the development environment or cross-compilation!) and then releasing four generated files: SimpleITKCSharpManaged.dll (cross-platform) and one binary for each platform: libSimpleITKCSharpNative.so for linux, libSimpleITKCSharpNative.dylib for osx, and libSimpleITKCSharpNative.dll for windows. We already do that (check the VoxLogicA project, "lib" directory) but for us it's difficult to compile on windows and osx since my own development platform is linux.

Get in touch if you want to proceed and need further help!

**Comment by blowekamp** [comment]
There was also this bug recent fixed in ITK:
https://github.com/InsightSoftwareConsortium/ITK/pull/1589

I am updating SimpleITK to the current ITK master now, so this related issue will also be addressed.

**Comment by blowekamp** [comment]
> PS: I develop in .net for multi-platform; should you consider to release also development and stable binaries for .net in OSX, Windows and Linux, that would be of great help for our project.
> 
> I'm available to help if needed!
> 
> It's actually very simple: you need to compile simpleitk with CSharp enabled in cmake (follow your own instruction to set up the development environment or cross-compilation!) and then releasing four generated files: SimpleITKCSharpManaged.dll (cross-platform) and one binary for each platform: libSimpleITKCSharpNative.so for linux, libSimpleITKCSharpNative.dylib for osx, and libSimpleITKCSharpNative.dll for windows. We already do that (check the VoxLogicA project, "lib" directory) but for us it's difficult to compile on windows and osx since my own development platform is linux. Once the three binaries have been deployed, I can cross-compile for windows and osx without switching platforms, which is great for using simpleitk.
> 
> Get in touch if you want to proceed and need further help!

Yes assistance would be quite welcomed. We need to get the Azure CI to automatically build and change the .net binaries. There is a bit more involved. Please crate a new issue and we can continue the conversation there.
