### ISSUE TITLE
Metadata not preserved after application of Filters

### ISSUE THREAD

**Issue by hemmer** [SimpleITK/SimpleITK#994]
### Context
I would like to use the metadata associated with a sitk.Image throughout a program. However I find that application of a filter wipes out the metadata. Is this intended behaviour and is there a way to prevent it from happening? I've given SeriesNumber in the example below, but it might as well be padding or some other value that would be useful to know through the program.

### Example code
```
import SimpleITK as sitk


def main():
    image = sitk.Image(32, 32, sitk.sitkFloat32)
    image.SetMetaData("(0020,0011)", "123")
    print("SeriesNumber (0020,0011):", image.GetMetaData("(0020,0011)"))

    image2 = sitk.DiscreteGaussian(image, [1.0, 1.0, 1.0])
    print("SeriesNumber (0020,0011):", image.GetMetaData("(0020,0011)"))
    try:
        print("SeriesNumber (0020,0011):", image2.GetMetaData("(0020,0011)"))
    except RuntimeError as e:
        print(e)

    image3 = sitk.BinaryThreshold(image)
    try:
        print("SeriesNumber (0020,0011):", image3.GetMetaData("(0020,0011)"))
    except Exception as e:
        print(e)

    print(sitk.SITK_ITK_VERSION_MAJOR, sitk.SITK_ITK_VERSION_MINOR, sitk.SITK_ITK_VERSION_PATCH)


if __name__ == '__main__':
    main()

```

### Output
```
SeriesNumber (0020,0011): 123
SeriesNumber (0020,0011): 123
Exception thrown in SimpleITK Image_GetMetaData: C:\d\VS14-Win64-pkg\SimpleITK-build\ITK\Modules\Core\Common\src\itkMetaDataDictionary.cxx:88
:
itk::ERROR: Key '(0020,0011)' does not exist
Exception thrown in SimpleITK Image_GetMetaData: C:\d\VS14-Win64-pkg\SimpleITK-build\ITK\Modules\Core\Common\src\itkMetaDataDictionary.cxx:88
:
itk::ERROR: Key '(0020,0011)' does not exist
4 13 1
```

### Expected behaviour
Metadata persists after application of filters (i.e. above exception is not throw).

###  Version
SimpleITK: 1.2.0
ITK: 4.13.1
Python: 3.6.8

**Comment by zivy** [comment]
Hello @hemmer,

This is a feature, as implicitly propagating the original meta-data throughout a set of operations can be problematic/dangerous. For example, your original image had a modality of CT and then you did edge detection. The resulting image is not a CT, so you don't want the metadata to automatically propagate.

If you need the **modified** meta-data in the end:
1. create a copy of the meta-data dictionary 
2. process the image
3. update the meta-data dictionary based on what you did
4. set the image meta-data using the updated dictionary.

Please close the issue if this clarified things.

**Comment by hemmer** [comment]
That makes a lot of sense, thanks for clarifying. The workaround you suggest is what I was doing so far (or a whitelisted sensible subset of it).

It's unfortunate that sitk.Image doesn't have a concept of padding (in the sense of PixelPaddingValue) as this would be a useful attribute to carry with the image (like GetOrigin() etc).
