### ISSUE TITLE
error when running "sitk.ReadImage(controlmaskfile, sitk.sitkFloat64)"

### ISSUE THREAD

**Issue by shiyu2011** [SimpleITK/SimpleITK#998]
RuntimeError: Exception thrown in SimpleITK ReadImage: /scratch/dashboard/SimpleITK-OSX10.6-x86_64-pkg/SimpleITK-build/ITK/Modules/IO/TIFF/src/itkTIFFImageIO.cxx:452:
itk::ERROR: TIFFImageIO(0x7ff03c510e30): Unable to read tiff file: Sorry, can not handle images with 64-bit samples

**Comment by zivy** [comment]
Hello @shiyu2011,
This exception explicitly says that the TIFFImageIO can't handle the type of image you provided. There are other image reader settings that also support TIFF, possibly one of them does support the image type you provided.
To see which ImageIO class supports which image type run:
```
import SimpleITK as sitk
print(sitk.ImageFileReader())
```
TIFF is supported by TIFFImageIO and LSMImageIO. Explicitly selecting an ImageIO is illustrated in [this Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/03_Image_Details.ipynb) under the heading "finer control".

If your image is OME-TIFF, the answer is a bit more complicated (will require that you build SimpleITK yourself).
